influxdata/ui

cypress/e2e/flows.test.ts, cypress/fixtures/routes.json, src/notebooks/components/FlowCard.tsx, src/notebooks/components/FlowCards.tsx, src/notebooks/components/FlowCreateButton.tsx, src/notebooks/components/FlowPage.tsx, src/notebooks/components/FlowsIndex.tsx, src/notebooks/components/FlowsIndexEmpty.tsx, src/notebooks/components/Notebook.tsx, src/notebooks/components/header/index.tsx, src/notebooks/context/notebook.current.tsx, src/notebooks/context/notebook.list.tsx, src/notebooks/context/notebook.tsx, src/notebooks/index.ts, src/pageLayout/constants/navigationHierarchy.ts, src/shared/containers/SetOrg.tsx
* feat(flows): empty state for index page
* feat(wip): link to flows from index page
* feat(wip): rename flows
* feat: name flows
* fix: set feature flags
* test: skip flagged test
=> feat: flows index (#19448)

src/cloud/components/RateLimitAlert.tsx, src/cloud/components/RateLimitAlertContent.tsx
Cherry picks https://github.com/influxdata/influxdb/pull/19463
* feat(ui): change rate limit content for payg
* feat(ui): open support portal in new tab
=> feat(ui): change rate limit content for payg (#19463)

src/templates/actions/creators.ts, src/templates/api/index.ts, src/templates/components/CommunityTemplateEnvReferences.tsx, src/templates/components/CommunityTemplateImportOverlay.tsx, src/templates/components/CommunityTemplateOverlay.tsx, src/templates/components/CommunityTemplateParameters.tsx, src/templates/components/CommunityTemplateResourceContent.tsx, src/templates/reducers/index.test.ts, src/templates/reducers/index.ts, src/types/templates.ts
https://github.com/influxdata/influxdb/pull/19456
=> feat(community-templates): parameterization

yarn.lock
somewhere along the way, we forgot to add the lockfile after running `yarn add`
=> fix: add updated lockfile

cypress.json, cypress/e2e/dashboardsIndex.test.ts, cypress/e2e/tasks.test.ts, src/dashboards/components/dashboard_index/DashboardsIndex.tsx, src/dashboards/components/dashboard_index/DashboardsTableEmpty.tsx, src/shared/constants/index.ts
Closes https://github.com/influxdata/influxdb/issues/19447
* Remove ability to import from a template
=> fix: remove ability to import from a template

cypress.json, cypress/e2e/buckets.test.ts, cypress/e2e/dashboardsView.test.ts, cypress/e2e/login.test.ts, cypress/e2e/onboarding.test.ts, cypress/e2e/telegrafs.test.ts, cypress/e2e/tokens.test.ts, cypress/fixtures/user.json, cypress/support/commands.ts
use this for overrides: https://docs.cypress.io/guides/guides/environment-variables.html#Option-2-cypress-env-json
=> feat: move cypress over to using env variables

src/templates/components/CommunityTemplateEnvReferences.tsx
Closes: https://github.com/influxdata/idpe/issues/8498
- Adds a bucket dropdown to the parameterization UI
_neat!_
=> feat(community-templates): use the buckets dropdown selector

src/writeData/components/clientLibraries/Arduino.md
Fixed a typo on Load Data, Telegraf Button for Arduino.
=> fix: spelling correction

src/notebooks/components/header/Submit.tsx, src/notebooks/components/minimap/MiniMap.tsx, src/notebooks/context/notebook.current.tsx, src/notebooks/context/schemaProvider.tsx, src/notebooks/pipes/Data/BucketSelector.tsx, src/notebooks/pipes/Data/FieldsList.tsx, src/notebooks/pipes/Data/index.ts, src/shared/actions/schemaThunks.ts, src/shared/utils/flowSchemaNormalizer.ts
i was a good engineer and kept all of these changes real clean and scoped behind a commit in the git log. prolly first time in my career. real proud of myself.
JUST SOME POLISH TO THE LIFECYCLE METHODS
and my inner russ yelling "how is it so hard to have everything alphabetically ordered"
=> fix: cleanup some metric selector stuff

src/shared/actions/schemaThunks.ts
it turns out that system buckets are special buckets that have a special format. if a bucket doesn't have an org id set on it, lets have that bucket inherit the orgid from the user.
=> fix: allow system buckets in the metric selector

package.json, src/shared/components/BandPlot.tsx, src/shared/utils/vis.test.ts, src/shared/utils/vis.ts, src/timeMachine/actions/index.ts, src/timeMachine/components/view_options/BandOptions.tsx, src/timeMachine/components/view_options/LineOptions.tsx, src/timeMachine/constants/index.ts, src/timeMachine/constants/queryBuilder.ts, src/timeMachine/constants/visGraphics.tsx, src/timeMachine/reducers/index.ts, src/views/helpers/index.ts, yarn.lock
Closes idpe #8337
Updates Band Plot options to allow the user to set the upper, main, and lower portions of the band.
=> feat: update Band Plot options

src/notebooks/components/FlowCards.tsx, src/notebooks/components/FlowsIndex.tsx, src/notebooks/pipes/Data/AggregateWindowSelector.tsx, src/notebooks/pipes/Data/SearchBar.tsx, src/notebooks/pipes/Data/Selectors.tsx, src/notebooks/pipes/Data/style.scss, src/notebooks/pipes/Data/view.tsx
- Make flows index view centered
- Increase size of aggregate dropdown in metric selector to avoid text-wrapping
- Integrate selector with focus interactions on search bar
=> refactor: add some polish to flows

.gitignore, cypress/e2e/communityTemplates.test.ts, package.json, src/templates/components/CommunityTemplateResourceContent.tsx
closes https://github.com/influxdata/influxdb/issues/19606
There are two issues that needed to be fixed to the code under test that using the test templates revealed. Those were fixed, and then the test was committed.
=> test: update community template e2e test

.eslintrc.js, src/cloud/apis/demodata.ts, src/dashboards/components/dashboard_index/DashboardCards.tsx, src/shared/components/EmptyQueryView.tsx, src/variables/utils/hydrateVars.ts
see: https://github.com/influxdata/giraffe/pull/290
=> chore: make eslint require curly braces

cypress/e2e/communityTemplates.test.ts, src/templates/containers/CommunityTemplatesIndex.tsx
Closes https://github.com/influxdata/influxdb/issues/19590
=> feat: allow Enter key to be used in Community Templates input

cypress/e2e/communityTemplates.test.ts, src/templates/actions/thunks.ts, src/templates/utils/index.test.ts, src/templates/utils/index.ts
closes #19599
This fixes the template.md file, originally it tried to search for it on influxdb, but now it routes to github properly
=> feat: fixing the template.md link

CHANGELOG.md
changelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelogchangelog
=> chore(changelog): added a changelog for logging changes in a log

src/shared/utils/formatStatValue.test.ts, src/shared/utils/formatStatValue.ts
Closes https://github.com/influxdata/giraffe/issues/295
Stay in sync with Giraffe
=> fix: keep formatStatValue in sync with same file in Giraffe

.circleci/config.yml
=> build(wip): smoke test

src/notebooks/pipes/Data/FilterTags.tsx, src/notebooks/pipes/Data/TagSelectors.tsx, src/notebooks/pipes/Data/style.scss
closes #81 
cleans up the filtering branching
=> fix: allows one to deselect tags individually

src/pageLayout/constants/navigationHierarchy.ts
closes influxdata/idpe#8764
just re implementing influxdata/influxdb#19551 in the ui repo so it'll show up on cloud
=> chore: migrate bug fix

src/index.tsx, src/shared/components/NotFound.tsx, src/shared/containers/GetOrganizations.tsx, src/shared/containers/SetOrg.tsx
closes #119 
This fixes the 404 page so it now properly routes and does not get called everytime the page loads
=> fix: fixing the 404 not displaying

.circleci/config.yml
hopefully this unblocks some builds for folks
=> fix: dont look at the branch names cause ariel cant name things good

src/shared/copy/notifications.ts, src/templates/actions/creators.ts, src/templates/actions/thunks.ts, src/templates/components/CommunityTemplateInstallOverlay.tsx, src/templates/reducers/index.test.ts, src/templates/reducers/index.ts
removes the unused redux elements of templates.
follow up to: https://github.com/influxdata/ui/pull/174
=> refactor: remove legacy templates from redux

cypress/e2e/buckets.test.ts, cypress/e2e/checks.test.ts, cypress/e2e/explorer.test.ts, cypress/e2e/flows.test.ts, cypress/e2e/labels.test.ts, cypress/e2e/orgs.test.ts, cypress/e2e/queryBuilder.test.ts, cypress/e2e/tokens.test.ts, src/alerting/components/builder/ThresholdCondition.tsx, src/alerting/components/builder/ThresholdValueInput.tsx
These are adjustments made to our e2e tests
=> test(e2e): review e2e

.circleci/config.yml
now that tests pass, lets wait for them to succeed before passing the images along the deployment pipeline
=> feat: gate deploys on e2e tests

.circleci/config.yml
=> build: add nightly e2e tests against firefox

global.d.ts, src/timeMachine/constants/queryBuilder.test.ts, src/timeMachine/constants/queryBuilder.ts
Closes influxdata/influxdb#19256
=> fix: derivative to use hardcoded value of 1s

package.json, yarn.lock
=> chore: upgrade clockface dependency to 2.3.5

.circleci/config.yml, cypress/e2e/queryBuilder.test.ts, cypress/e2e/tasks.test.ts, cypress/e2e/tokens.test.ts, cypress/e2e/variables.test.ts, cypress/fixtures/tokens.json, package.json, yarn.lock
Looks like yet _another_ `dev/shm` issue with Firefox.  This time had to adjust `monitor-ci` and increase the `dev/shm` size on the `cypress` image.
=> fix: nightly e2e

package.json, yarn.lock
=> chore: upgrade to latest version of flux-lsp

src/flows/components/ExportTaskOverlay/ExportTaskOverlay.tsx, src/flows/components/header/Submit.scss, src/flows/components/header/Submit.tsx, src/flows/context/pipe.tsx, src/flows/context/query.tsx, src/flows/pipes/Bucket/index.ts, src/timeMachine/components/SubmitQueryButton.tsx, src/types/flows.ts
=> feat(run-query): adds a dropdown to flows to allow for running and previewing queries

src/flows/context/schemaProvider.tsx
=> fix: resolved issue where selecting a second bucket in the metric selector crashed the app

src/shared/components/ScatterPlot.tsx, src/shared/components/ViewSwitcher.tsx
=> fix: use time range in Scatterplot

src/flows/context/query.tsx, src/flows/pipes/Bucket/index.ts, src/flows/pipes/Data/index.ts, src/flows/pipes/Query/index.ts
closes #162 
closes influxdata/idpe#8802
=> fix: remove that variable nonsense

src/cloud/utils/reporting.test.ts, src/cloud/utils/reporting.ts
=> fix(app-metrics): explicitly trim whitespace and newlines from tags

webpack.common.ts
OH BOY
closes #220 
run `make build NODE=chronograf && make restart NODE=chronograf` to see the changes applied
=> feat: sass hmr

cypress/e2e/checks.test.ts
Closes: #240 
Bonitoo has written some e2e tests for us.  Until we get forked repo credentials worked out I'm just going to copy the branches and push them up myself.  
This is one of those tests.
=> test(e2e): bonitoo checks filtering

cypress/e2e/checks.test.ts
Closes: #205 
Bonitoo has written some e2e tests for us. Until we get forked repo credentials worked out I'm just going to copy the branches and push them up myself.
This is one of those tests.
=> test: create deadman check

cypress/e2e/tokens.test.ts
Closes #217 
Bonitoo has written some e2e tests for us. Until we get forked repo credentials worked out I'm just going to copy the branches and push them up myself.
This is one of those tests.
=> test: select all buckets in Generate Read/Write token

cypress/e2e/buckets.test.ts
Closes: #206 
Bonitoo has written some e2e tests for us. Until we get forked repo credentials worked out I'm just going to copy the branches and push them up myself.
This is one of those tests.
=> test: new buckets tests

src/shared/constants/fluxFunctions.ts
bringing over the changes from https://github.com/influxdata/influxdb/pull/19899
=> feat(fluxFunctions): add functions for flux v0.92

src/tasks/actions/thunks.ts
bringing over https://github.com/influxdata/influxdb/pull/19685/files
=> fix(tasks): cloning tasks makes actions shared in task list view

src/writeData/components/telegrafPlugins/stackdriver.md
closes: https://github.com/influxdata/influxdb/issues/19766
=> fix(telegraf): fixing broken stackdriver readme

cypress/e2e/tasks.test.ts
Closes: influxdata/influxdb#19942
=> fix: firefox task test

cypress/e2e/buckets.test.ts
closes #172 
So when i turned off the skip nothing failed locally, or in PR so far -_- .
=> test: turn off skip

src/shared/components/FluxTablesTransform.tsx, src/timeMachine/components/RawFluxDataTable.test.tsx, src/timeMachine/components/RawFluxDataTable.tsx
This PR removes some feature flags for some of the parser unification work that's been done
=> chore: remove flags

package.json, yarn.lock
Related to #238 
Let's turn on the tick generator in Tools.
=> chore: update giraffe

package.json, yarn.lock
Upgrade to [Flux LSP v0.5.23](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.23)
=> build: upgrade flux-lsp-browser to v0.5.23

cypress/e2e/buckets.test.ts, cypress/e2e/checks.test.ts, cypress/e2e/communityTemplates.test.ts, cypress/e2e/dashboardsIndex.test.ts, cypress/e2e/dashboardsView.test.ts, cypress/e2e/explorer.test.ts, cypress/e2e/flows.test.ts, cypress/e2e/labels.test.ts, cypress/e2e/loadDataSources.test.ts, cypress/e2e/nav.test.ts, cypress/e2e/notificationEndpoints.test.ts, cypress/e2e/notificationRules.test.ts, cypress/e2e/orgs.test.ts, cypress/e2e/queryBuilder.test.ts, cypress/e2e/scrapers.test.ts, cypress/e2e/tasks.test.ts, cypress/e2e/telegrafs.test.ts, cypress/e2e/tokens.test.ts, cypress/e2e/variables.test.ts, cypress/support/commands.ts
Tests will no longer depend on what is returned from `/debug/provision` endpoint.
=> feat(uie2e): Remove the dependence of tests on what is returned from /debug/provision

package.json, src/shared/visualization/types/Band/index.tsx, yarn.lock
Closes idpe 9144
- update giraffe
- use "Band" instead of "Band Plot" in the dropdown for consistency
=> chore: update giraffe and use name "Band" in plot dropdown

package.json, yarn.lock
[Flux LSP `v0.5.24`](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.24)
=> build: Upgrade to flux-lsp-browser v0.5.24

cypress/e2e/shared/checks.test.ts
=> test: threshold check

.circleci/config.yml, cypress/e2e/shared/explorer.test.ts
this will get us up to date with a current IDPE build
=> build: ssl fix

src/client/unity.yml, src/types/billing.ts
Closes #326 
One question for me is how to get the current user's email.  Seems odd to have an entire endpoint just for this one string.  Turns out there was a bunch of information on the `Account` struct that we don't use for the billing page at all.
=> feat(wip): Billing Page

src/shared/actions/schemaThunks.ts, src/shared/copy/notifications.ts
This PR just adds a more relevant error message
=> chore: fix up error message

src/flows/index.ts, src/pageLayout/constants/navigationHierarchy.ts
=> chore: update notebooks nav icon and name

src/flows/components/panel/Results.tsx, src/timeMachine/components/Vis.tsx
=> chore: remove UI feature flag

src/flows/pipes/RawFluxEditor/index.ts
=> fix: less aggressive whitespace trimming

src/flows/components/AddButtons.tsx, src/flows/components/EmptyPipeList.tsx, src/flows/components/FlowContextMenu.tsx, src/flows/components/FlowCreateButton.tsx, src/flows/components/header/Submit.tsx, src/flows/components/header/TimeRangeDropdown.tsx, src/flows/components/panel/FlowPanelTitle.tsx, src/flows/components/panel/InsertCellButton.tsx, src/flows/components/panel/RemovePanelButton.tsx, src/flows/components/panel/Results.tsx, src/flows/context/flow.current.tsx, src/flows/context/runMode.tsx, src/flows/pipes/MetricSelector/AggregateWindowSelector.tsx, src/flows/pipes/MetricSelector/FieldSelectors.tsx, src/flows/pipes/MetricSelector/MeasurementSelectors.tsx, src/flows/pipes/MetricSelector/TagSelectors.tsx, src/flows/pipes/ToBucket/ExportTaskOverlay/context.tsx, src/flows/pipes/Visualization/ExportDashboardOverlay/ExportDashboardButtons.tsx, src/flows/pipes/Visualization/view.tsx
Closes https://github.com/influxdata/ui/issues/109
- Rename a handful of events to match GA naming conventions
- Instrument all the things
=> feat(notebooks): update eventing to match google analytics

src/flows/components/FlowsExplainer.tsx, src/flows/index.ts, src/flows/style.scss
=> feat(notebooks): update notebooks documentation link

src/buckets/components/context/csvUploaderProvider.tsx, src/buckets/components/csvUploader/CsvUploaderBody.tsx, src/buckets/components/csvUploader/CsvUploaderWizard.tsx, src/buckets/containers/BucketsIndex.tsx
Closes #428
The current CSV uploader is set to the assumption that the incoming CSVs are Ms formatted times rather than basing it off of something more determinsitic
Calculate the time based on length to determine whether the time is `ms`, `s`, `us`, or `ns`
=> feat: makes CSV times more deterministic

package.json, src/types/flows.ts, yarn.lock
Moves types that were previously in Giraffe into ui
=> chore: fix breaking change from giraffe 2.0.0

src/authorizations/components/BucketsTokenOverlay.tsx, src/authorizations/utils/permissions.test.ts, src/authorizations/utils/permissions.ts
refactor fridays.  part of the tokentab ecosystem
=> test: refactor fridays; added a test and comments (code is clearer, renamed a method for clarity)

.circleci/config.yml, cypress/e2e/shared/checks.test.ts, cypress/e2e/shared/explorer.test.ts, cypress/e2e/shared/tasks.test.ts
This will let us see for certain that the monitor-ci branch in question passes oss e2e tests
=> fix: point at my branch for circleci oss test verification

cypress/e2e/shared/explorer.test.ts, cypress/e2e/shared/tasks.test.ts
=> chore: enable fix broken test that had been skipped 

.circleci/config.yml
=> fix: lhr fails on master because of Invalid pr link

src/onboarding/containers/LoginPageContents.tsx
This PR removes the feature flag for the Azure SSO option on the Cloud UI login screen.
=> feat: removes the azureSSO flag

src/views/helpers/index.test.ts, src/views/helpers/index.ts
put all the 'tick' properties together
also testing the 'legend properties which were grouped together when doing the colorize rows (for legend) feature
Closes #453
=> test: adding refactoring to simplify graph configurations.

src/shared/apis/query.test.ts, src/templates/components/CommunityTemplateInstallOverlay.test.tsx
Closes #415 
Co-authored-by: Zoe Steinkamp <zoe.steinkamp@gmail.com>
see: https://github.com/influxdata/ui/pull/532 (this is a copy/paste job from that branch, which was long running and seemed to have problems on CI)
=> test(communityTemplate): integration test for install overlay

assets/images/plugin-simple.svg, src/cloud/components/RateLimitAlertContent.tsx, src/cloud/components/RateLimitOverlay.scss, src/cloud/components/RateLimitOverlay.tsx, src/cloud/components/SeriesCardinalityIncreaseForm.tsx, src/overlays/components/OverlayController.tsx, src/overlays/reducers/overlays.ts, src/style/chronograf.scss
Closes # https://github.com/influxdata/cloud-growth/issues/19
This PR adds a new Overlay when a PAYG user hits the series cardinality limit. From the overlay they are able to kick off the Install the Cardinality Now template to help resolve the issue. They can also send an email to support to request a series cardinality increase.
Series Cardinality Limit Alert
Series Cardinality Limit Overlay
Request an increase
Send Increase request email to support
Install template
Cardinality Now dashboard
=> feat: integrate series cardinality template

src/external/monaco.autogrow.ts, src/flows/pipes/RawFluxEditor/function.tsx, src/flows/pipes/RawFluxEditor/functions.tsx, src/flows/pipes/RawFluxEditor/style.scss, src/flows/pipes/RawFluxEditor/view.tsx
This migrates the function reference functionality from data explorer to notebooks. not a perfect 1:1 from a product perspective, but close enough to serve as a stand in to scratch the itch while we have talks about better ways to do it
=> feat: notebook function reference

src/shared/constants/fluxFunctions.ts
bringing over the change from https://github.com/influxdata/influxdb/pull/20495
=> chore(fluxFunctions): change v1 to schema

src/flows/context/flow.current.tsx, src/flows/context/tags.tsx, src/flows/pipes/QueryBuilder/AddButton.tsx, src/flows/pipes/QueryBuilder/AggregationSelector.tsx, src/flows/pipes/QueryBuilder/BucketSelector.tsx, src/flows/pipes/QueryBuilder/CardList.tsx, src/flows/pipes/QueryBuilder/context.tsx, src/flows/pipes/QueryBuilder/index.ts, src/flows/pipes/QueryBuilder/style.scss, src/flows/pipes/QueryBuilder/view.tsx, src/flows/style.scss
While we figure out if people like notebooks, and the effect of the new metric selector exploration on their forming of that view point, i figured it'd be good to hedge our bets on that interface by adding back in everyone's favorite query builder interface to notebooks.
=> feat: query builder

package.json, yarn.lock
[Flux LSP v0.5.30](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.30)
=> chore: Upgrade flux-lsp-browser to v0.5.30

src/buckets/actions/__mocks__/thunks.ts, src/templates/components/CommunityTemplateInstallOverlay.test.tsx, src/templates/components/CommunityTemplatesInstalledList.test.tsx
=> test: InstalledList tests

src/dataLoaders/actions/dataLoaders.ts
Closes #582 
here is a screenshot:
=> fix: #582 better token failure error messages

src/shared/copy/notifications.ts, src/templates/components/CommunityTemplateInstallOverlay.test.tsx
=> test: Integration test overlay failures

package.json, yarn.lock
=> chore: update to girafe v2.0.1

src/flows/components/FlowCards.tsx
Sorts flows by name and then by id so they are always in a consistent order on the Notebooks page.
=> feat: sorts flows by name and id

package.json, src/shared/components/GeoPlot.test.tsx, src/shared/components/GeoPlot.tsx, src/shared/utils/vis.ts, yarn.lock
Closes idpe #9574
Introduces the error message for missing lat/lon data when attempting to view map type
=> feat: error message for missing map type data

package.json, yarn.lock
[Flux LSP v0.5.32](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.32)
=> build: Upgrade flux-lsp-browser to v0.5.32

src/visualization/components/internal/AxisTicksGenerator.tsx, src/visualization/components/internal/TimeTickInput.tsx, src/visualization/types/Band/options.tsx, src/visualization/types/Graph/options.tsx, src/visualization/types/Heatmap/options.tsx, src/visualization/types/Mosaic/options.tsx, src/visualization/types/Scatter/options.tsx, src/visualization/types/SingleStatWithLine/options.tsx
Closes #557 
Text change per product.
=> fix: change wording for tick marks per ticket

src/visualization/types/Scatter/TimeAutoToggle.test.tsx, src/visualization/types/Scatter/TimeAutoToggle.tsx, src/visualization/types/Scatter/options.tsx
Closes #19867
Introduces auto scale toggle for time domain. This PR is the updated version of https://github.com/influxdata/ui/pull/498, which was closed due to significant changes in the visualization process causing significant merge conflicts
=> feat: time domain auto toggle

src/timeMachine/components/Vis.tsx, src/visualization/types/Table/view.tsx
apparently we got a bunch of weirdos around here that enable raw data view before even running a query, or expect their table visualizations to update when they change variables.
this one goes out to them
=> fix: empty raw table view and variable refreshes

src/shared/utils/vis.test.ts, src/shared/utils/vis.ts, src/visualization/types/Map/index.tsx, src/visualization/types/Map/view.tsx
Closes #9749
This pr addresses numerous issues with the bonitoo code that was ported over for an initial maps demo, adding typing, tests, and removing side effects.
=> fix: address bonitoo utils for geo map code plus add tests and typing

src/annotations/actions/thunks.ts, src/annotations/reducers/index.ts, src/dashboards/components/DashboardPage.tsx, src/shared/components/RefreshingView.tsx, src/types/annotation.ts, src/visualization/types/Graph/view.tsx
Connects #620 
Fetches annotations and stores them in redux. Doesn't render them yet.
=> feat: add annotations fetching->redux

assets/images/plan-graphic--free.svg, src/cloud/components/experiments/DatalessEmptyState.scss, src/cloud/components/experiments/DatalessEmptyState.tsx, src/dashboards/components/dashboard_index/DashboardsTableEmpty.tsx, src/style/chronograf.scss, src/tasks/components/EmptyTasksList.tsx
Experiment code for https://github.com/influxdata/cloud-growth/issues/8
An experiment where users who have not yet loaded data into the application will see a prompt on the resource page empty states to load data instead of to create that resource.
=> feat(experiment): empty state prompts to load data

src/flows/context/api.tsx, src/flows/context/flow.list.tsx
Issue https://github.com/influxdata/idpe/issues/8685
Removes `notebooks-api` flag.
=> chore: removes notebooks-api feature flag

.gitignore, package.json, src/client/swagger/managedFunctions.yml, src/functions/components/FunctionCard.tsx, src/functions/components/FunctionCards.tsx, src/functions/components/FunctionContextMenu.tsx, src/functions/components/FunctionCreateButton.tsx, src/functions/components/FunctionListEmpty.tsx, src/functions/components/LastRunFunctionStatus.tsx, src/functions/containers/FunctionListPage.tsx, src/functions/context/api.tsx, src/functions/context/function.list.tsx
Closes #9784 and #9785
I'm currently mocking the responses from the API, and add and remove functions don't yet work those are up next!
Please let me know if I'm using context variable and file names wrong. Keeping in mind that this is very much placeholder will be thrown out one day code!
=> feat(managed-functions): Add functions list page that is hydrated from context

src/dashboards/components/dashboard_index/DashboardsTableEmpty.tsx, src/tasks/components/EmptyTasksList.tsx
Update the experiment id for the Empty State Prompt test.
=> chore(experiment): update experimentID

src/shared/components/RefreshingView.tsx, src/timeMachine/components/Vis.tsx, src/timeMachine/selectors/index.ts, src/visualization/components/View.tsx, src/visualization/index.ts, src/visualization/types/Graph/view.tsx
=> Feat: render annotations

package.json, yarn.lock
Upgrades lodash to improve best practices lighthouse score
=> chore: upgrades lodash to latest

.circleci/config.yml
=> chore: disable lhr until a fix is available

.circleci/config.yml, cypress/e2e/cloud/billing.test.ts, cypress/e2e/cloud/communityTemplates.test.ts, cypress/e2e/cloud/usage.test.ts, cypress/e2e/cloud/users.test.ts
Closes #737 
Reenables cloud tests.
=> test: re-enable cloud tests

cypress/e2e/cloud/buckets.test.ts, cypress/e2e/cloud/geoOptions.test.ts
Some tweaks to cloud e2e tests so they will pass in IDPE-CI
https://app.circleci.com/pipelines/github/influxdata/idpe?branch=genehynson%2Fui-e2e-cloud-tests
K8s-IDPE PR: https://github.com/influxdata/k8s-idpe/pull/2433
=> test: make cloud tests pass in IDPE CI

src/visualization/types/SingleStat/options.tsx, src/visualization/types/SingleStatWithLine/options.tsx
Closes #738 
seems like these didn't get copy pasta'd correctly
=> fix: add back a toggle in view options

src/flows/components/FlowsIndex.tsx, src/flows/style.scss
Closes #709 
just.. deletes it
=> feat: remove the feedback cta

package.json, yarn.lock
=> chore: upgrade to giraffe version 2.4.0

src/authorizations/components/BucketsTokenOverlay.tsx, src/shared/components/FluxMonacoEditor.tsx, src/visualization/types/Heatmap/options.tsx, src/visualization/types/Scatter/options.tsx, src/visualization/types/SingleStatWithLine/options.tsx
just some quick ones
Closes #752 
Closes #713 
Closes #692
Closes #610
=> fix: general bug fixing

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This attempts to fix the issue templates. do not run prettier on these files please.
Closes #
=> fix: fixing issue templates

.circleci/config.yml
Merge this first: https://github.com/influxdata/monitor-ci/pull/182 ✅ 
Re-enable lighthouse after upgrading to v7.0.0
=> chore: turns on lighthouse

.circleci/config.yml, cypress/e2e/shared/queryBuilder.test.ts
Related: https://github.com/influxdata/idpe/issues/9087
Fixes an IDPE CI test failure by specifying which toggle button to click.
IDPE CI: ✅  https://app.circleci.com/pipelines/github/influxdata/idpe?branch=genehynson%2Fcypress-slim
=> test: multiple toggle switch test failure

src/flows/components/panel/Results.tsx, src/flows/components/panel/ResultsPagination.tsx, src/flows/pipes/RawFluxEditor/style.scss, src/flows/style.scss, src/types/flows.ts
=> feat: new raw table!

.circleci/config.yml
=> chore: added a quick comment about the cypress image

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.34](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.34)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.34

src/annotations/actions/creators.ts, src/annotations/actions/thunks.ts, src/annotations/api/index.ts, src/shared/copy/notifications.ts
=> feat: delete annotations to redux and the API

src/tasks/containers/TaskPage.tsx
Attempts to fix: https://github.com/influxdata/influxdb/issues/20887 
(Not sure if UI is the right place to fix this problem.)
=> fix: tasks options in script

src/annotations/actions/thunks.ts, src/annotations/api/index.ts, src/annotations/components/AnnotationCard.tsx, src/annotations/components/AnnotationsTab.tsx, src/annotations/components/controlBar/AnnotationPill.tsx, src/annotations/components/controlBar/AnnotationPills.tsx, src/annotations/components/controlBar/AnnotationsSearchBar.tsx, src/annotations/reducers/index.ts, src/types/annotation.ts, src/visualization/types/Graph/view.tsx
Closes #828 
Cleans up various small dings and rough edges we've picked up.
- Connects stream color to annotation color, and puts it into redux so it's not a repeated hex string everywhere
- Cleans up variable names
=> chore: cleanup annotation code

cypress/e2e/shared/checks.test.ts, package.json, src/alerting/components/AlertingIndex.scss, src/annotations/components/controlBar/AnnotationsControlBar.tsx, src/visualization/components/internal/LegendOrientation.tsx, yarn.lock
upgrading clockface, to use proper toggle buttons.  and getting all the clockface improvements since 2.4.1
=> chore: upgrading clockface to 2.6.2

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.35](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.35)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.35

src/annotations/components/controlBar/AnnotationsControlBar.test.tsx, src/annotations/components/controlBar/AnnotationsControlBar.tsx, src/annotations/components/controlBar/AnnotationsSearchBar.tsx
Closes #846 
Current Progress:
`Searching through streams  ✅`
`Selecting a stream from the drop down ✅`
`Closing out a stream pill ✅`
`Toggling one-click annotation writing ✅`
`🟡` = in progress
`✅` = completed
=> test: annotations control bar integration tests

src/visualization/types/Map/api.ts, src/visualization/types/Map/view.tsx
=> feat: update ui to request map token from map service

src/annotations/components/AnnotationsControlBarToggleButton.tsx
=> fix: fixes typo for AnnotationsControlBarToggleButton testID

README.md
I'm trying to create an image built with the changes added in https://github.com/influxdata/monitor-ci/pull/187
=> chore(update): just making a silly change for no reason

README.md
=> chore(update): incorporate latest changes to monitor-ci

src/visualization/types/SimpleTable/PagedTable.tsx
=> fix: we shouldnt rely on anything

.github/pull_request_template.md
A dumb change to move our pipeline forward to a new commit sha which will clear the CircleCI cache
=> docs: dumb change

.circleci/config.yml
=> chore: update lhr image when running lhr report

src/client/swagger/unity.yml
Closes #960 
This PR is an attempt to write out an API definition for the `/me` endpoint that will be developed by the Quartz API
=> feat: add yml definition for the /me endpoint

src/billing/api/index.ts, src/billing/components/BillingPageContents.tsx, src/billing/components/marketplace/MarketplaceBilling.tsx, src/billing/components/marketplace/MarketplaceLink.tsx, src/billing/components/marketplace/PurplePanel.tsx, src/billing/components/marketplace/SubscriptionManagerPanel.tsx, src/billing/reducers/index.ts, src/billing/reducers/mockBillingData.ts, src/client/swagger/unity.yml, src/types/marketplace.ts
Closes https://github.com/influxdata/idpe/issues/9970
This PR adds a billing page for PAYG Marketplace users based on the Quartz specifications
=> feat: marketplace UI integrated for the billing page

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.37](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.37)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.37

global.d.ts, src/checkout/CancelButton.tsx, src/checkout/context/checkout.tsx, src/checkout/shared/FormInput.tsx, src/checkout/shared/FormSelectDropdown.tsx, src/types/adminds.ts
Related to #877
This doesn't fully close the issue since there's still the matter of the [ZuoraClient](#870) form interactions that should be integrated in order to fully encapsulate the `isDirty` state. Once that PR is up we should be able to close out the issue
=> feat: cart abandonment

src/visualization/types/SimpleTable/InnerTable.tsx
Closes #887 
you mean you guys can't read unix epoch?
looks like this after fix:
=> fix: format times as times for humans

src/shared/copy/notifications.ts
=> fix: update query cancelled notification text

README.md
=> docs: adds k8s-idpe docs to readme

src/visualization/types/SimpleTable/InnerTable.tsx
Closes #1019 
booleans didn't work.. now they do!
=> fix: booleans for SimpleTable

cypress/e2e/cloud/checkout.test.ts, package.json, src/billing/api/index.ts, src/billing/components/PaymentInfo/PaymentForm.tsx, src/billing/components/PaymentInfo/PaymentPanelBody.tsx, src/billing/thunks/index.ts, src/checkout/CheckoutForm.tsx, src/checkout/context/checkout.tsx, src/shared/components/CreditCardForm/index.test.tsx, src/shared/components/CreditCardForm/index.tsx
=> chore: extract zuora form out of checkout

package.json, yarn.lock
=> chore: upgrade clockface 2.6.8

package.json, yarn.lock
Closes #
Updating clockface. I made a mistake on the previous version of clockface of not actually exporting the pagination component. This version has that fixed.
=> chore: update Clockface

README.md, src/checkout/CheckoutForm.tsx, src/shared/components/CreditCardForm/index.tsx
=> chore: add cart abandonment check

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.38](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.38)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.38

src/billing/api/index.ts, src/billing/components/BillingContactInfo.tsx, src/billing/components/Free/Free.tsx, src/billing/components/Free/FreePanel.tsx, src/billing/components/Free/OrgLimitStat.tsx, src/billing/components/Free/OrgLimits.tsx, src/billing/components/PayAsYouGo/NotificationSettingsOverlay.tsx, src/billing/reducers/index.ts, src/billing/thunks/index.ts, src/checkout/SuccessOverlay.scss, src/checkout/context/checkout.tsx, src/shared/copy/notifications.ts, src/types/billing.ts, src/usage/UsagePage.tsx
This PR cleans up and integrates some missing dependencies for the UI based on the API contracts
=> feat: connect missing pieces for UI unification

src/timeMachine/actions/queries.ts
Closes #959 
Made some assumptions more guarded
=> fix: fixed issue with cancellation that was causing the app to crash

.circleci/config.yml
Installs UserPilot to the application as a replacement for Walkme.
=> feat: install UserPilot as a Walkme replacement

cypress/e2e/shared/tasks.test.ts, src/tasks/actions/thunks.ts
Reverts influxdata/ui#1063
was causing issues: https://github.com/influxdata/idpe/issues/10299
=> fix: reverts 1063 until we get to the bottom of it

cypress/e2e/cloud/flows.test.ts, src/flows/components/PipeList.tsx, src/flows/pipes/MetricSelector/index.ts, src/flows/pipes/QueryBuilder/index.ts
if you put a notebooks into presentation mode.. then refresh the page... it's not going to show you anything.
that's terrible!
so lets load the visualization when you hit the page
part of #1083
=> fix: run populated flows on load

src/annotations/components/AddAnnotationOverlay.tsx, src/annotations/components/EditAnnotationForm.tsx, src/annotations/components/EditAnnotationOverlay.tsx, src/annotations/components/annotationForm/AnnotationForm.tsx
Closes #980 
Adds initial validation that just checks that a message and summary/time is included. Will eventually morph as we understand more about how we want to validate incoming forms
=> fix: initial validation check

src/types/ast.ts
Closes #
Fixes a bug in the ast logic which will allow for support for more complex extern objects
=> fix: bug in ast for MemberAssignment

__mocks__/@influxdata/flux-parser.ts, __mocks__/@influxdata/flux.ts, cypress/e2e/shared/tasks.test.ts, cypress/support/commands.ts, src/tasks/actions/thunks.ts
Closes #883 
This time it should close the issue for real. Updated the regex to properly assert replacing the task name declaration rather than the first string like it was in the previous PR (#1063)
=> feat: fixed name cloning to target the task name

cypress/e2e/shared/buckets.test.ts, src/buckets/components/BucketAddDataButton.tsx, src/buckets/containers/BucketsIndex.tsx
=> chore: remove feature flag

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.39](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.39)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.39

cypress/e2e/shared/explorer.test.ts
Closes #481 
Unskipped the test because it doesn't fail 🥳
=> chore: unskipped test because it works now

assets/index.html, cypress/e2e/oss/onboarding.test.ts, src/index.html, src/onboarding/components/CompletionStep.tsx, src/onboarding/components/InitStep.tsx, src/onboarding/constants/index.ts
=> chore: change references from InfluxDB 2.0 to InfluxDB Cloud

src/functions/components/FunctionForm.scss, src/functions/components/FunctionHeader.tsx, src/functions/components/FunctionResponse.tsx, src/functions/context/function.list.tsx
Added some dapper scrollbars, 
Changed save button behavior to prevent navigating away from the page.
=> feat(managed-functions): Styling improvements, change save and close behavior

.circleci/config.yml
adding in a lighthouse build that is using our production build settings. it was breaking my brain that it wasn't seeing compressed javascript in the static output. should bump some numbers
=> feat: trying something

src/functions/components/FunctionResponse.tsx
I forgot to remove the other scrollbars I had added :(
=> feat(managed-functions): remove non-dapper scrollbars

src/client/swagger/unity.yml
Updates the unity swagger to the correct url.
=> fix: update unity swagger to have correct url

src/flows/pipes/Downsample/index.ts, src/flows/pipes/Downsample/view.tsx
for some reason it wasn't working so good, but it looked like it should have worked
=> fix: get downsample back in the game

cypress/e2e/shared/dashboardsIndex.test.ts, cypress/e2e/shared/tasks.test.ts, mocks/dummyData.ts, src/dashboards/actions/creators.ts, src/dashboards/components/dashboard_index/DashboardsIndex.tsx, src/dashboards/constants/index.ts, src/dashboards/reducers/dashboards.test.ts, src/dashboards/reducers/dashboards.ts, src/resources/selectors/getAll.ts, src/shared/utils/mocks/resourceToTemplate.ts, src/templates/components/createFromTemplateOverlay/CreateFromTemplateOverlay.tsx, src/types/dashboards.ts, src/types/resources.ts
Closes #844 
**Before**
**After**
=> chore: make dashboards filter term persist across pages

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.40](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.40)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.40

cypress/e2e/shared/tasks.test.ts
=> fix: fix cypress mistyping issue

src/Logout.tsx, src/shared/constants/index.ts
Closes #1182 
This PR is a feature flagged implementation for the UI's logout functionality that will drastically simplify the process involved in logging a user out. However, this is not fully feature ready as we still need to whitelist the returnTo URL in the tenant's app-wide [Allowed Logout URLs as per the docs](https://auth0.github.io/auth0.js/global.html#logout)
=> feat: log the user out of auth0 and redirect to IDPE after

cypress/e2e/shared/tasks.test.ts, cypress/index.d.ts, cypress/support/commands.ts, package.json
=> fix: test after getting focus

cypress/e2e/shared/dashboardsView.test.ts
=> fix: fix dashboardsView cypress test flakiness

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.41](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.41)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.41

cypress/e2e/shared/dashboardsView.test.ts, src/flows/components/header/Submit.tsx
Closes #1158 , https://github.com/influxdata/ui/issues/1263
Also fixes and refactors flaky dashboard test
=> chore: conditionally render dropdown arrow

src/client/swagger/unity.yml
Updates unity yaml
- error definitions for me, users, and invite endpoints.
- removes links from invite schema
=> chore(unity): add error definitions for users page endpoints

src/views/helpers/index.ts, src/visualization/types/Map/GeoOptions.tsx
=> fix: update map data point colors to influx purple

src/Signin.tsx, src/shared/actions/flags.ts
Closes #1179 
This PR adds a pre-authentication request to the public feature flag API in order to set pre-authentication feature flags to the UI.
=> chore: integrate request to public feature flags

src/variables/utils/validation.test.ts, src/variables/utils/validation.ts
for idpe#9771
this validates them properly on the front end.
adding unit tests too
=> fix: validate variable names on creation properly

README.md
Adds some k8s-idpe instructions to readme
=> docs: adds instructions for cypress tests k8s-idpe

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.42](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.42)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.42

cypress/e2e/cloud/annotations.test.ts
Closes #1258 , #1259
Fixes two flaky annotations tests
=> test: fix flaky annotations tests

package.json, yarn.lock
=> fix: patch Giraffe

package.json, yarn.lock
=> chore: update Giraffe to 2.9.0

src/writeData/components/clientLibraries/Java.md, src/writeData/components/clientLibraries/Kotlin.md, src/writeData/components/clientLibraries/Scala.md, src/writeData/components/clientLibraries/Swift.md
Related to
- https://github.com/influxdata/influxdb-client-java/pull/222
- https://github.com/influxdata/influxdb-client-java/pull/211
1. Added example how to use WriteApi in Kotlin
2. Added note about cross building in Scala
3. Updated Swift package version
=> docs(clientLibs): updated Kotlin examples to reflect actual version of client

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.43](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.43)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.43

.circleci/config.yml
Tests the monitor-ci branch....i hope
=> chore: update the circleci config to test against local UI build image

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.44](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.44)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.44

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.45](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.45)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.45

src/timeMachine/components/ViewTypeDropdown.tsx, src/visualization/types/Map/view.tsx
=> chore: add event logging to maps type

cypress/e2e/cloud/billing.test.ts, cypress/e2e/cloud/checkout.test.ts, package.json, src/me/actions/thunks/index.ts, src/utils/api.ts
=> feat: connected the quartz me endpoint

src/annotations/components/EditAnnotationForm.tsx
=> fix(annotations): send edit cancel event rather than create cancel event

cypress/e2e/cloud/flows.test.ts, src/flows/components/PipeList.tsx
Closes #1161 
Adds insert button to the top of notebooks as shown here:
=> feat: add insert button to top of flow pipe list

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.46](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.46)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.46

src/visualization/components/internal/AxisTicksGenerator.tsx, src/visualization/utils/useAxisTicksGenerator.ts
Closes #1462 
Removes the feature flag `axisTicksGenerator` and makes this feature permanent.
=> feat: remove feature flag for axisTicksGenerator

src/shared/copy/notifications.ts, src/visualization/components/annotationUtils.ts, src/visualization/types/Heatmap/view.tsx, src/visualization/types/Histogram/view.tsx, src/visualization/types/Map/view.tsx, src/visualization/types/Mosaic/view.tsx, src/visualization/types/Scatter/view.tsx, src/visualization/types/SingleStat/view.tsx
Closes #1431
Doesn't work with gauge.
https://user-images.githubusercontent.com/146112/119177478-39b85180-ba21-11eb-9eac-9f4585a5d038.mov
=> feat: notify uers that annotations are unsupported on that graph type

src/visualization/types/Heatmap/view.tsx, src/visualization/types/Histogram/view.tsx, src/visualization/types/Map/view.tsx, src/visualization/types/Mosaic/view.tsx, src/visualization/types/Scatter/view.tsx, src/visualization/types/SingleStat/view.tsx
=> fix: only show annotation notification if annotations is in write mode

scripts/run-monitor-ci-tests.bash
=> revert: "chore: ci works from fork (#1454)"

cypress/e2e/cloud/home.test.ts
=> fix: fix flaky test

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.47](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.47)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.47

src/annotations/components/annotationForm/AnnotationStartTimeInput.tsx
Closes #1328
Renders the time in the annotation form in the format the user selects via the dashboard
https://user-images.githubusercontent.com/146112/119576495-b58e0300-bd6d-11eb-9ea7-a040ac1517fa.mov
=> feat(annotations): respect local or utc time

package.json, src/annotations/actions/thunks.ts, src/annotations/components/AddAnnotationOverlay.tsx, src/annotations/components/EditAnnotationForm.tsx, src/annotations/components/annotationForm/AnnotationForm.tsx, src/annotations/components/annotationForm/AnnotationTimeInput.tsx, src/types/annotation.ts, src/visualization/types/Graph/view.tsx, src/visualization/types/Heatmap/view.tsx, src/visualization/types/Histogram/view.tsx, src/visualization/types/Map/view.tsx, src/visualization/types/Mosaic/view.tsx, src/visualization/types/Scatter/view.tsx, src/visualization/types/SingleStat/view.tsx, src/visualization/types/SingleStatWithLine/view.tsx, src/visualization/utils/annotationUtils.ts, yarn.lock
Closes #1417 
adds ranged annotations to graph (xy) and graph + singlestat
allows for editing and deleting of those annotations too
=> feat: add ranged annotations to xy graph and graph + singlestat graph

cypress/e2e/cloud/annotations.test.ts
Closes #1370 
im trying to see if removing the exist will help. Its hard to recreate the flakyness, im going to try to get to flake during pr
=> test: trying to remove flakiness from annotations e2e tests

src/visualization/types/Map/view.tsx
=> chore(annotations): don't alert user that annotations aren't available on maps

scripts/run-monitor-ci-tests.bash
CI works from fork...again 😅 
the issue last time was with my `if [ -n $PULL_REQUEST ]` statement. I needed to add quotes around $PULL_REQUEST for the condition to work correctly. I tested it by setting the UI_BRANCH to `master` and making PULL_REQUEST unset. Totally works now.
=> chore: ci works from fork

cypress/e2e/shared/dashboardsView.test.ts
Closes #
Addresses a flaky test by removing an unnecessary check (since its already addressed by the url change factor in the edit modal check test)
=> chore: remove unnecessary check bc its included in the edit test

cypress/e2e/shared/dashboardsView.test.ts
Closes #
This test has some serious firefox issues (the behavior itself works just fine in firefox and is also tested by another test, making this test unnecessary). Therefore, i'm removing it.
=> chore: remove unnecessary test

src/flows/components/FlowPage.tsx
Closes #
Allows for dynamic setting of notebook title
https://user-images.githubusercontent.com/29473622/120022845-98964180-bfb2-11eb-935c-d1a647545fdf.mov
=> feat: notebook title

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.48](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.48)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.48

src/usage/context/usage.tsx
=> chore: update the csv response split to split double new lines rather than returns and newlines

cypress/e2e/shared/explorer.test.ts, package.json, src/annotations/components/controlBar/AnnotationsControlBar.tsx, src/visualization/types/Band/view.tsx, src/visualization/types/Graph/view.tsx, src/visualization/types/SingleStatWithLine/view.tsx, src/visualization/utils/annotationUtils.ts, yarn.lock
Closes #1484
* adds annotations to band plot; with the requisite giraffe upgrade
* refactored out annotation layer code, simpler to add now
* adds back two skipped e2e tests that pass now
=> feat: add annotations to band plot

src/shared/components/cells/CellContext.tsx
Closes #10695 (https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/idpe/10695)
Enables cloning of note cell in a dashboard
=> chore: add ability to clone note cell

src/usage/context/usage.tsx
This is just a sanity check. This should be working as is, it works in my browser but the output of the split is a single array with the last result
=> chore: moved some things for clarity on usage data

cypress/e2e/shared/checks.test.ts, src/alerting/components/builder/HelpButton.tsx, src/buckets/components/BucketExplainer.tsx, src/buckets/components/lineProtocol/LineProtocolHelperText.tsx, src/checks/components/CheckMessageCard.tsx, src/checks/components/ChecksColumn.tsx, src/dashboards/components/variablesControlBar/VariablesControlBar.tsx, src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx, src/me/components/Docs.tsx, src/me/components/Support.tsx, src/notifications/endpoints/components/EndpointsColumn.tsx, src/notifications/rules/components/RulesColumn.tsx, src/telegrafs/components/TelegrafExplainer.tsx, src/usage/BillingStatsPanel.tsx
Similar to https://github.com/influxdata/influxdb/pull/20754
=> fix: updating the docs links

cypress/e2e/shared/telegrafs.test.ts, src/telegrafs/components/CollectorCard.tsx
https://user-images.githubusercontent.com/29473622/120684618-87db4500-c464-11eb-923a-dcadc5155571.mov
Closes #1558 
Adds the ability to clone a telegraf config
=> feat: clone telegraf configs

src/shared/utils/vis.ts, src/usage/context/usage.tsx
=> chore: give me a break

src/flows/pipes/Visualization/Controls.tsx, src/flows/pipes/Visualization/view.tsx
because not everyone has the sidebar feature flag on immediately after deploying it
=> fix: turn visualizations options back on

src/shared/components/Filter.tsx, src/shared/utils/ast.ts
another PR to remove some lodash stuff
=> chore: remove isArray

src/timeMachine/reducers/index.ts, src/visualization/utils/formatStatValue.ts, src/visualization/utils/useVisDomainSettings.ts
general chore to reduce the usage of lodash
=> chore: remove isNumber

src/normalizers/localStorage/dashboardTime.ts, src/shared/components/Filter.tsx, src/shared/utils/latestValues.ts, src/visualization/utils/formatStatValue.ts
Another refactor friday chore to remove lodash usage
=> chore: remove isString from codebase

cypress/e2e/cloud/annotations.test.ts, src/annotations/components/annotationForm/AnnotationTimeInput.tsx
=> chore: e2e range annotations tests, adding in band annotation tests too

src/shared/constants/thresholds.ts, src/views/helpers/index.ts, src/visualization/types/Map/GeoOptions.tsx, src/visualization/types/Map/properties.ts, src/visualization/types/Map/view.tsx, src/visualization/types/SingleStat/options.tsx
=> feat: fixing the color picker for maps

src/telegrafs/components/TelegrafConfigOverlayForm.tsx
=> chore: removed the rest of the feature flag

src/shared/utils/upperFirst.test.ts, src/shared/utils/upperFirst.ts, src/visualization/components/internal/LegendOrientation.scss, src/visualization/components/internal/LegendOrientation.tsx, src/visualization/components/internal/StaticLegend.scss, src/visualization/components/internal/StaticLegend.tsx, src/visualization/constants.ts
=> feat: add metrics for customization of legend orientation and static legend

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.49](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.49)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.49

src/shared/components/cells/CellContext.tsx
Closes #
Fix test id for copy cell work
=> chore: fix test id

cypress/e2e/cloud/annotations.test.ts, yarn.lock
~~Skip for now~~
Let's try committing the yarn.lock to see if the flakiness goes away.
=> fix: commit yarn.lock after a version bump

src/shared/constants/thresholds.ts, src/visualization/types/Map/properties.ts, src/visualization/types/Map/view.tsx
The Threshold setting for changing colors on data points in map is still broken. This pr fixes that issue.
=> fix: point colors in maps

src/telegrafs/components/TelegrafOutputOverlay.tsx
Closes #
updates the telegraf output config in the UI to have the latest options (commented out) so that users can see what's available to them. see https://github.com/influxdata/telegraf/tree/da7f2c7a934b5dc763ab10c7db02fe65b201686e/plugins/outputs/influxdb_v2 for more details
=> feat: updating telegraf output config with additional options

src/dataLoaders/components/DataLoadersOverlay.scss, src/writeData/components/WriteDataHelperBuckets.tsx, src/writeData/components/fileUploads/CSV.md, src/writeData/components/fileUploads/LP.md, src/writeData/components/fileUploads/UploadDataDetailsView.tsx
=> feat: updates to file  uploads page

.prettierignore
=> fix: prettier ignore markdown files

package.json, src/shared/reducers/autoRefresh.ts, yarn.lock
Upgrading us to 5.3.6 in an effort to slowly bring us up to latest
=> chore: upgrades immer to 5.3.6

cypress/e2e/cloud/annotations.test.ts
Closes #1370
Round 2 of trying to fix flakey annotations test. Following other tests that use .should(be.visible)
=> fix: trying should(be.visible) on annotations flakey test

package.json, yarn.lock
Yet another bump along the journey to getting immer to latest
=> chore: bumps immer to 7.0.15

src/flows/context/flow.current.tsx, src/flows/context/resource.hook.tsx, src/flows/context/results.tsx, src/types/flows.ts
Closes #1723 
This PR enables the cross tab sync for notebooks. No more errors!
=> fix: notebook cross tab fix

package.json, src/App.tsx, yarn.lock
Upgrading to 9.0.3 didn't work, trying 8.0.1
=> chore: upgrade immer to 8.0.1

cypress/e2e/cloud/annotations.test.ts, package.json, src/annotations/components/controlBar/AnnotationsControlBar.tsx, src/visualization/utils/annotationUtils.ts, yarn.lock
Closes #1758
now that we add point annotations with a shift+click; need to update the ui and update the tests.
=> fix: zoom out fixes

package.json, src/shared/utils/vis.ts, src/views/helpers/index.ts, src/visualization/types/Map/GeoOptions.scss, src/visualization/types/Map/GeoOptions.tsx, src/visualization/types/Map/LatLonColumnOptions.tsx, src/visualization/types/Map/S2ColumnOptions.tsx, src/visualization/types/Map/properties.ts, src/visualization/types/Map/utils.ts, src/visualization/types/Map/view.tsx, yarn.lock
Closes #1029 #1027 
This pr adds the ability to allow users to pick the lat/lon or s2 columns in the customization options.
=> feat: add customization options for lat/lon or s2 column in maps

package.json, src/shared/components/cells/Cell.scss, src/visualization/constants.ts, yarn.lock
Closes #1749 
https://user-images.githubusercontent.com/10736577/123011160-c03fb600-d374-11eb-843a-b39016f50d06.mp4
=> fix: allow horizontal scrollbar on Dashboard cells to accomodate static legend content

cypress/e2e/shared/dashboardsView.test.ts
Closes #
shortens timing and fixes some minor flake
=> chore: add fix to timing to shorten

src/cloud/components/onboarding/useGetUserStatus.ts
Closes #
Puts request behind feature flag not just reponse
=> chore: update to not run unless behind flag

package.json, yarn.lock
Closes #1803 
Latest Giraffe running in the UI going through the steps:
https://user-images.githubusercontent.com/10736577/123373467-4b1ddd80-d53a-11eb-95bf-63b49641cdec.mp4
=> fix: update Giraffe

src/onboarding/containers/LoginPageContents.tsx
=> chore: change from error to logging error

src/onboarding/containers/LoginPageContents.tsx
sso login has been tested in staging. now removing feature flag and is ready for prod.
=> chore: remove feat flag for ssoLogin

src/shared/utils/vis.test.ts, src/shared/utils/vis.ts, src/visualization/types/Map/api.test.ts, src/visualization/types/Map/view.test.tsx
This is a continuation of pr from an old pr: https://github.com/influxdata/ui/pull/1770
=> chore: test maps visualization utils for getting geo coordinates

src/shared/constants/fluxFunctions.ts
=> fix: fixing typos in fluxFunctions

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.51](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.51)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.51

cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts, cypress/support/commands.ts, src/flows/components/Sidebar.tsx, src/writeData/components/ClientCodeQueryHelper.tsx
Closes #1469 
Add tests for Copy to Clipboard functionality.
=> chore: add notebook copy  to clipboard tests

src/visualization/types/Map/utils.ts
Closes #1816 
Simple fix so no more crashing due to _field not existing
=> fix: fix for crashing on customize

src/utils/datetime/README.md
adds a small readme for the datetime formatter
=> docs: added readme for datetime formatter

src/visualization/types/Map/GeoOptions.scss, src/visualization/types/Map/LatLonColumnOptions.tsx, src/visualization/types/Map/S2ColumnOptions.tsx
=> fix: styling on geo customization options

src/timeMachine/components/SubmitQueryButton.tsx
=> fix: remove react warning

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.52](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.52)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.52

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/design-epic.md, .github/ISSUE_TEMPLATE/feature_request.md
Adding a design cycle template
=> chore: Update issue templates

intl.d.ts, src/utils/datetime/formatters.test.ts, src/utils/datetime/formatters.ts, tsconfig.json, tsconfig.test.json
Closes #1943
Adds relative formatting to the date formatter
>15 minutes ago
>1 day ago
>2 years ago
```ts
const formatter = createRelativeFormatter()
const date = new Date(1126816200) // 09/15/2005 8:30:00 PM
formatter.formatRelative(date) // 14 years ago
```
=> feat: relative DateTime formatter

package.json, src/shared/utils/vis.ts, src/visualization/types/Map/S2ColumnOptions.tsx, src/visualization/types/Map/view.tsx, yarn.lock
=> fix: maps selection for s2 cell id tag

src/authorizations/components/ViewTokenOverlay.tsx, src/shared/components/CodeSnippet.tsx
Closes #1937
Easy fix for EOD Friday 😎
=> fix: change notification text

src/checkout/context/checkout.tsx, src/shared/components/CreditCardForm/index.tsx
This PR adds events to the zuora form so that we can track when it renders successfully and when it fails to render
=> chore: add events for the zuora form

src/visualization/types/Map/GeoOptions.tsx, src/visualization/types/Map/properties.ts, src/visualization/types/Map/view.tsx
Closes #1951 
Alright this fixes the options in notebooks.
=> fix: Fix options in notebooks

cypress/e2e/shared/legends.test.ts, src/dashboards/components/DashboardPage.tsx
=> fix: add assertion for existence before continuing in legends.test

src/flows/components/FromTemplatePage.tsx
For use in our onboarding userpilot
Closes #1351
=> feat: demo data notebook

package.json, yarn.lock
Upgrade flux-lsp-browser to [v0.5.53](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.53)
=> build(lsp): Upgrade to flux-lsp-browser v0.5.53

src/flows/pipes/Visualization/view.tsx
what a bad gif
ANYWHO this adds back the ability for someone to download their visualization as a CSV. if you have the sidebar enabled, it'll show up in the dropdown menus instead of the top panel (not pictured)
=> fix: add downloading back into the game

cypress.json, cypress/e2e/shared/annotations.band.test.ts, cypress/e2e/shared/annotations.range.test.ts, cypress/e2e/shared/annotations.singlestat.test.ts, cypress/e2e/shared/annotations.xy.test.ts
connects https://github.com/influxdata/ui/issues/2012
Turns back on annotations and skips the couple of flaky ones while'st we work on a fix
=> test: turn on annotations tests

cypress/e2e/shared/annotations.band.test.ts, cypress/e2e/shared/annotations.range.test.ts, cypress/e2e/shared/annotations.singlestat.test.ts, cypress/e2e/shared/annotations.xy.test.ts
=> test: annotations e2e tests are back on the menu, boys

package.json, yarn.lock
=> chore: updating giraffe version for easier annotation editing

assets/index.html
Closes #
Updates the influxdb site description.
=> fix: update description

src/annotations/components/annotationForm/AnnotationForm.tsx
Closes #2057
part of : #1844
This PR removes `moment` from `AnnotationForm.tsx`
=> refactor: remove moment from AnnotationForm.tsx

src/utils/datetime/formatters.test.ts, src/utils/datetime/formatters.ts
Part of #2099
As described in the issue, we need that formatter case. This PR adds it with its accompanying tests.
=> feat: formatter case YYYY-MM-DD for our new datetime formatter

src/utils/datetime/formatters.test.ts, src/utils/datetime/formatters.ts
Part of #2099
As described in the issue, we need that formatter case. This PR adds it with its accompanying tests.
=> feat: YYYY-MM-DD hh:mm:ss.sss added to the date formatter

src/index.tsx
Closes #
Changes the import and testing against the prod image shows this worked, so here's hoping
=> fix: global search css

cypress/e2e/cloud/about.test.ts, cypress/e2e/cloud/billing.test.ts, cypress/e2e/cloud/checkout.test.ts, cypress/e2e/cloud/operator.test.ts, cypress/e2e/cloud/usage.test.ts, cypress/e2e/cloud/users.test.ts, src/billing/components/Free/PAYGConversion.tsx, src/checkout/SuccessOverlay.tsx, src/organizations/components/OrgProfileTab.tsx, src/pageLayout/components/UserWidget.tsx, src/pageLayout/constants/navigationHierarchy.ts, src/shared/components/CloudUpgradeButton.tsx, src/shared/components/CloudUpgradeNavBanner.tsx, src/shared/containers/GetOrganizations.tsx, src/shared/containers/SetOrg.tsx
This PR is part of a process to remove ALL the existing unity feature flags in favor of 1 permanent feature flag
=> chore: consolidate feature flags

src/me/components/Resources.tsx, src/me/components/UsagePanel.tsx, src/me/containers/MePage.tsx
Closes #
This is a placeholder implementation for the usage panel, and will only be shown once IDPE provides us with a count endpoint for resources, as currently our implementation requires us to pull in the resources themselves and do a count, which is super inefficient.
=> feat: ui placeholder implementation for usage panel

src/shared/components/TimeSeries.tsx
Closes #2137
checks if the component is unmounting before setting state
=> fix: prevent memory leak in TimeSeries.tsx

src/flows/components/panel/Handle.tsx, src/flows/style.scss
Closes #2062
Adjusts the panel resizer to have a similar appearance and interaction to the clockface one
https://user-images.githubusercontent.com/29473622/127173352-7bcd7a96-a2c4-4fc8-8935-ffef0f284eda.mov
=> feat: panel resizer

src/flows/context/flow.list.tsx
Closes #https://github.com/influxdata/influxdb/issues/20692
=> chore: generate notebooks names based on user name and not org name

src/flows/components/Sidebar.tsx
=> fix: hide convert to flux from too many things

src/cloud/components/onboarding/EngagementLink.tsx
=> chore: update param name to uppercase

.gitignore, package.json
Closes #
This adds the commands for yarn generate to also pull in the pinned items routes
=> chore: add pinned items service

src/flows/components/Sidebar.scss
=> fix: overcome maps z-index

src/flows/templates/types/flux.ts
Closes #2151
just hit up `/notebook/from/flux` to see the magic
=> feat: add flux notebook template

src/visualization/types/Map/properties.ts
=> fix: bring back the zoom for maps on notebooks

cypress/e2e/cloud/about.test.ts, cypress/e2e/cloud/billing.test.ts, cypress/e2e/cloud/checkout.test.ts, cypress/e2e/cloud/operator.test.ts, cypress/e2e/cloud/usage.test.ts, cypress/e2e/cloud/users.test.ts, src/billing/components/Free/PAYGConversion.tsx, src/checkout/SuccessOverlay.tsx, src/organizations/components/OrgProfileTab.tsx, src/pageLayout/components/UserWidget.tsx, src/pageLayout/constants/navigationHierarchy.ts, src/shared/components/CloudUpgradeButton.tsx, src/shared/components/CloudUpgradeNavBanner.tsx, src/shared/containers/GetOrganizations.tsx, src/shared/containers/SetOrg.tsx
This PR rips out a lot of the old conditional logic for unification and consolidates the unity feature flags under the uiUnificationFlag that's currently toggled on in every environment but tools (since we don't have a tools quartz, it'll cause problems)
=> chore: remove the old flags and consolidated the logic for the new flag

cypress/e2e/cloud/home.test.ts, src/onboarding/containers/LoginPage.tsx
this removes the loginRedirect feature flag
=> chore: remove loginRedirect flag

cypress/e2e/cloud/about.test.ts, src/organizations/components/OrgProfileDeletePanel.tsx, src/organizations/containers/OrgProfilePage.tsx, src/shared/selectors/flags.ts
This removes the selfDeletion feature flag
=> chore: remove the selfDeletion feature flag

cypress/e2e/shared/flows.test.ts
This PR _should_ fix the issue with the breaking test since the test-ID couldn't be found.
=> fix: fix tests that broke from changes

src/me/components/DocSearchWidget.scss, src/me/components/DocSearchWidget.tsx, src/shared/search/GlobalSearch.tsx
Closes #
Minor css changes and hotkey to one that is less cluttered
=> chore: minor cleanup

cypress/e2e/util/annotationsSetup.ts
Closes #1945
See: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3553/workflows/4e3f8ae0-ac69-4ac7-8801-3204d6e82e55
=> test: add guard statement in annotation e2e editing tests

src/flows/pipes/Markdown/view.tsx, src/flows/pipes/RawFluxEditor/view.tsx
=> fix: forgot to remove autogrow

src/flows/context/flow.list.tsx, src/flows/templates/types/default.ts
it was strange to me that this option wasn't defined with the rest of the notebook templates
=> fix: normalize where default notebooks are defined

src/flows/context/flow.list.tsx, src/shared/components/FluxMonacoEditor.tsx
This was some random attempt to address some latency issues that currently exist on flows that are pretty impossible to recreate locally. It also addresses an issues that crops up in the monaco editor experience when we update the component and try to edit the raw flux. The app crashes, it shouldn't do that, so we're plopping in an ErrorBoundary
=> chore: fix some bugs about monaco editor crashing

src/shared/constants/fluxFunctions.ts
Closes #
adds option argument for min / max
=> fix: update args for min max

src/flows/pipes/Visualization/Controls.tsx, src/flows/pipes/Visualization/index.ts
=> fix: removing weird interfaces

cypress/e2e/cloud/buckets.test.ts, src/shared/components/resource_sort_dropdown/generateSortItems.ts
=> fix: change from string to float for bucket retention sorting

src/writeData/components/telegrafPlugins/mqtt_consumer.md
=> fix: links in mqtt consumer

package.json, src/operator/constants.tsx
Updated the OpenAPI SHA and removed the onboarding status reference for the operator page
=> chore: update SHA and remove onboarding status of users for operator page

src/visualization/types/Table/properties.ts, src/visualization/types/Table/view.tsx
Closes #860 
* updates the  properties file to use those defaults
=> fix: use giraffe table

src/flows/pipes/Visualization/Controls.tsx
=> fix: view options not updating

src/flows/shared/Resizer.scss
=> fix: css error state

src/flows/components/Sidebar.scss
=> fix: cleaning up the padding on the sidebar

src/flows/pipes/Notification/Endpoints.tsx
=> fix: updating alert function signature

src/flows/pipes/Notification/index.ts
=> feat: rename notifications but keep the type

cypress/e2e/util/annotationsSetup.ts, src/annotations/components/AnnotationsControlBarToggleButton.tsx, src/annotations/components/annotationForm/AnnotationForm.tsx, src/dashboards/components/DashboardPage.tsx, src/dataExplorer/components/DataExplorerPage.tsx, src/visualization/types/Heatmap/view.tsx, src/visualization/types/Histogram/view.tsx, src/visualization/types/Mosaic/view.tsx, src/visualization/types/Scatter/view.tsx, src/visualization/types/SingleStat/view.tsx, src/visualization/utils/annotationUtils.ts
Closes #2261
what it says on the tin
=> chore: remove annotations and rangeAnnotations flags and checks

src/dashboards/components/DashboardHeader.tsx, src/shared/components/graph_tips/GraphTips.tsx
Closes #2261 
Missed some flags with this: https://github.com/influxdata/ui/pull/2306
=> chore: remove lingering annotations flags

src/flows/pipes/Notification/Threshold.tsx
this is the easy part #2286 so i can rename the issue to focus on adding deadman checks
=> feat: alert condition capitalization

src/flows/pipes/Notification/Threshold.tsx, src/flows/pipes/Notification/index.ts
=> feat: pivot alert threshold columns

src/me/components/DocSearchWidget.tsx, src/me/containers/MePage.scss, src/shared/search/DocSearch.tsx, src/shared/search/GlobalSearch.scss, src/shared/search/GlobalSearch.tsx
Closes #
Minor css cleanup and some more logging context for docsearch
=> chore: minor css cleanup and more logging

scripts/run-monitor-ci-tests.bash
Require remocal jobs to pass in our CI before merging
=> chore(ci): require remocal to pass

src/cloud/apis/reporting.ts, src/cloud/utils/reporting.ts, src/index.tsx
Closes #2003 
This PR adds campaign data (UTM parameters) to events data send to Rudderstack.
=> feat: track campaign in rudderstack

src/flows/context/query.tsx
Closes #2237 
**Before**
**After**
=> fix: query cancellation fix

cypress/tsconfig.json
Found that we should be scanning all .ts files in sub-directories in our cypress ts-config
=> test: fix cypress tsconfig

cypress/e2e/shared/flows.test.ts, src/flows/components/FlowsExplainer.tsx, src/flows/components/FlowsIndex.tsx, src/flows/components/PresetFlows.scss, src/flows/components/PresetFlows.tsx, src/flows/components/PresetFlowsButtons.tsx, src/flows/components/controlSearchBar.scss
Closes #
Makes the scroll all purdy for the notebooks presets and removes the flag so that this can be a first class feature
=> feat: onscroll handle notebooks presets

cypress/e2e/shared/annotations.range.test.ts, cypress/e2e/util/annotationsSetup.ts, package.json, yarn.lock
=> chore: bumping up clockface for more robust annotation tests

src/alerting/components/AlertingIndex.scss, src/alerting/components/AlertingIndex.tsx, src/flows/context/flow.list.tsx, src/flows/pipes/Schedule/view.tsx, src/flows/templates/types/blank.ts, src/flows/templates/types/default.ts, src/flows/templates/types/flux.ts, src/flows/templates/types/notification.ts, src/flows/templates/types/task.ts, src/tasks/components/TaskHeader.tsx, src/timeMachine/components/Queries.scss, src/timeMachine/components/Queries.tsx
adds the extra ctas, normalizes name, changes notification to alert in one more place
=> fix: notebook template cleanup

cypress/e2e/shared/legends.test.ts, src/visualization/components/internal/StaticLegend.tsx, src/visualization/utils/useStaticLegend.ts
Closes #2305
Removes flagging code around `staticLegend`
=> chore: remove static legend flagging code

cypress/e2e/cloud/geoOptions.test.ts, src/shared/utils/vis.test.ts, src/shared/utils/vis.ts, src/visualization/types/Map/GeoOptions.tsx, src/visualization/types/Map/index.tsx, src/visualization/types/Map/view.tsx
Connects #2307
Removes `mapGeo` and `mapGeoOptions` flag checks from code.
=> chore: remove mapGeo and mapGeoOptions flag checks

src/flows/pipes/Notification/view.tsx
Closes #2433 
moving the needle
=> fix: add loading state to alerts

src/me/components/PinnedItems.scss, src/me/components/PinnedItems.tsx
Closes #
Fixes css and adds panel display for pinned items
=> chore: fix css and add panel background

src/me/components/DocSearchWidget.tsx
Adds some missing links to the doc search widget
=> chore: add more links to the doc search widget

package.json, src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx, src/authorizations/components/redesigned/ResourceAccordion.tsx, src/authorizations/components/redesigned/ResourceAccordionHeader.tsx, src/authorizations/components/redesigned/customApiTokenOverlay.scss
Closes #2446 
This pr fixes the issues surrounding the accordion and the header toggles. Also, have added some styling changes around the accordion
=> fix: accordion header toggles when individual resources are empty

src/flows/context/query.tsx, src/flows/pipes/Notification/Threshold.tsx, src/flows/pipes/Notification/view.tsx, src/flows/pipes/Schedule/ExportTaskOverlay/context.tsx
Closes #2286 
This feature adds deadman alerts as a possible option in the dropdown for the alerts panel. There's a lot of repetition here so I'm open to a different approach, especially one that isn't as brute-forced with setting the variables, but maybe it's not as brute forced as I think it is? Tried making do with the reduce function but things were getting a little out of control in there.
=> feat: completed deadman check functionality

cypress/e2e/shared/telegrafs.test.ts, src/dataLoaders/components/collectorsWizard/select/StreamingSelector2.tsx
=> test: adding new e2e test for new Create Telegraf page

src/dashboards/components/dashboard_index/DashboardCard.tsx, src/flows/components/FlowCard.tsx, src/tasks/components/TaskCard.tsx
=> chore: wrap in flag for pinned updates

src/cloud/components/onboarding/useGetUserStatus.ts
Closes #
There is a console.warn that for some reason was not removed, this is removing it.
=> chore: remove console warn that is unnecessary

package.json, yarn.lock
Closes #1673
update clockface to fix icon warning in console
=> chore: clockface update for icon error

package.json, src/shared/containers/SetOrg.tsx, src/shared/containers/index.tsx, src/tasks/actions/thunks.ts, src/tasks/pagination/TasksList.tsx, src/tasks/pagination/TasksPage.tsx
Closes #2169
Adds pagination to the tasks list.
Feature flagged behind `paginatedTasks`
https://user-images.githubusercontent.com/146112/132560351-b5bbacea-b52a-4ddd-b714-5dd9d42a8619.mov
=> feat: add pagination to the tasks page

cypress/e2e/shared/dashboardsIndex.test.ts
Minor changes to cypress/e2e/shared/dashboardsIndex.test.ts to try and reactivate import dashboard test.
=> chore: attempt to reactivate test import dashboard json

src/authorizations/actions/creators.ts, src/authorizations/actions/thunks.ts, src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx, src/authorizations/components/redesigned/GenerateTokenDropdown.tsx, src/authorizations/components/redesigned/ResourceAccordion.tsx, src/authorizations/reducers/index.test.ts, src/authorizations/reducers/index.ts, src/overlays/components/OverlayController.tsx, src/shared/copy/notifications.ts, src/types/resources.ts
=> feat: create token overlay has all the resources

package.json, src/shared/components/SearchableDropdown.scss, src/timeMachine/components/AggregationSelector.tsx, src/timeMachine/components/builderCard/BuilderCard.scss
=> fix: Dataexp clockface styling issues

src/flows/pipes/Columns/index.tsx, src/flows/pipes/Notification/Threshold.tsx, src/flows/pipes/Visualization/view.tsx
Closes #2580
The column editor wasn't working if there was a yield in the query for some reason. Now it works.
=> fix: column editor yield fix 

src/flows/components/panel/FlowPanel.tsx
=> chore: add flag for preview from here functionality

src/flows/components/Sidebar.tsx
Closes #2473
Adds "convert to flux" to visualization panel dropdown
=> chore: add convert to flux to vis dropdown

cypress/e2e/shared/buckets.test.ts, src/buckets/components/BucketAddDataButton.scss, src/buckets/components/BucketAddDataButton.tsx, src/buckets/components/BucketContextMenu.tsx, src/buckets/components/CreateBucketButton.tsx, src/buckets/components/DemoDataBucketCard.tsx, src/buckets/components/DemoDataDropdown.scss, src/buckets/components/DemoDataDropdown.tsx, src/buckets/components/Retention.scss, src/buckets/components/createBucketForm/BucketOverlayForm.tsx, src/buckets/components/createBucketForm/CreateBucketOverlay.tsx, src/buckets/components/createBucketForm/UpdateBucketOverlay.tsx
=> fix: fixing styling issues on buckets page with new clockface version

cypress/support/commands.ts
We've had some weirdness where `/flush` requests fail and then cause subsequent `/provision` requests to fail. This change retries the /flush after a failed /provision
=> chore: if provsion fails, flush and retry

src/alerting/components/AlertingIndex.tsx, src/dataExplorer/components/DataExplorerPage.tsx, src/shared/components/cta.scss, src/tasks/components/TaskHeader.tsx, src/tasks/components/TasksHeader.tsx, src/tasks/containers/TasksPage.tsx, src/timeMachine/components/Queries.scss, src/timeMachine/components/Queries.tsx
some changes to the existing CTA interfaces as requested by design
=> fix: cta design feedback

src/me/components/GettingStarted.tsx, src/me/components/Resources.tsx, src/pageLayout/containers/TreeNav.tsx, src/shared/components/CloudUpgradeButton.tsx
Closes #2397 
Cosmetic issues addressed on homepage. Clockface 3.0 changes the grey shade so things were being muted. 
Cloud upgrade button removed from nav bar. and the one on top right of the app given the right color
=> fix: cosmetic issues on homepage

src/billing/components/PayAsYouGo/CancellationPanel.tsx, src/organizations/components/OrgProfileDeletePanel.tsx
=> feat: track cancel service initiation

cypress/e2e/shared/telegrafs.test.ts, src/dataLoaders/components/DataLoadersOverlay.scss, src/dataLoaders/components/side_bar/SideBar.scss, src/shared/components/CodeSnippet.scss, src/telegrafs/components/CollectorCard.tsx, src/telegrafs/components/Collectors.tsx
=> fix: cosmetic changes to context menu, fixed associated tests for Telegraf

cypress/e2e/shared/tokens.test.ts, src/authorizations/components/AllAccessTokenOverlay.tsx, src/authorizations/components/BucketsSelector.scss, src/authorizations/components/BucketsTokenOverlay.tsx, src/authorizations/components/GenerateTokenDropdown.tsx, src/authorizations/components/TokenRow.tsx, src/authorizations/components/redesigned/GenerateTokenDropdown.tsx
Closes #2401 
Tokens page context menu was changed. deprecating the context menu component in favor of clockface buttons.
Tests were fixed with the new context menu.
Overlay spacing changed.
=> fix: cosmetic issues with tokens page with clockface beta, context menu and the tests

src/dataLoaders/components/verifyStep/ConnectionInformation.tsx
=> fix: add the telegraf troubleshooting docs link

src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx, src/authorizations/components/redesigned/ResourceAccordion.tsx
=> feat: tokens accordion bugs with toggle and sorting

src/dashboards/components/dashboard_index/DashboardCards.tsx, src/tasks/components/TasksList.tsx
Closes #2641 
Fixes react memory leaks in taskslist and dashboardcards components
=> chore: fix memory leak

src/me/components/DocSearchWidget.scss, src/me/components/PinnedItems.scss, src/me/components/PinnedItems.tsx
Closes #2642
Fixes some css shenanigans for pinned items container in the home page and the doc search widget component
=> fix: pinned items and doc search css

src/tasks/pagination/TasksList.tsx
Closes #2655
Pagination takes filtered list length into account when calculating pages
https://user-images.githubusercontent.com/146112/134059710-6d2a53aa-52ca-4586-8006-0f9524d85735.mov
=> feat(task pagination): calculate pages based on filtered list

src/dataLoaders/actions/dataLoaders.ts, src/dataLoaders/components/collectorsWizard/CollectorsStepSwitcher.tsx, src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep2.tsx, src/dataLoaders/components/collectorsWizard/select/StreamingSelector2.tsx, src/dataLoaders/components/collectorsWizard/verify/PluginConfigSwitcher.tsx, src/writeData/components/PluginCreateConfigurationCustomize.tsx, src/writeData/components/PluginCreateConfigurationFooter.tsx, src/writeData/components/PluginCreateConfigurationWizard.tsx
Closes #1745 
Closes #1556 
https://user-images.githubusercontent.com/6667389/133513370-a1f32180-52b2-4abc-a973-806edbb8906f.mov
=> feat: connecting the new Telegraf page to the edit config page

src/writeData/components/PluginCreateConfigurationCustomize.tsx
Part of #2160 
Removes an unused prop from a component.
=> chore: remove unused prop

cypress/e2e/cloud/pinned.test.ts, cypress/e2e/shared/flows.test.ts, src/buckets/components/BucketContextMenu.tsx, src/flows/components/FlowContextMenu.scss, src/flows/components/FlowContextMenu.tsx, src/flows/components/FlowCreateButton.tsx, src/flows/components/Sidebar.scss, src/flows/components/Sidebar.tsx, src/flows/components/header/Submit.tsx, src/flows/components/panel/InsertCellButton.scss, src/flows/components/panel/InsertCellButton.tsx, src/flows/pipes/Visualization/Controls.tsx, src/timeMachine/components/FluxToolbar.scss, src/writeData/components/ClientCodeCopyPage/InstallPackageHelper.tsx
Closes #2404 
Function panel:
Panels,  (Not sure why the syntax highjlighting isnt working ):
Card context menu changes :
=> fix: Notebooks cosmetic changes in clockface beta

src/billing/components/Free/OrgLimitStat.tsx, src/billing/components/PayAsYouGo/PlanTypePanel.scss, src/organizations/components/OrgProfileDeletePanel.tsx, src/organizations/components/OrgProfileTab.tsx, src/users/components/UserInviteSubmit.tsx
Closes #2653 
cosmetic changes for Usage,billing, user , about pages
=> fix: Usage,billing, user , about pages clockface 3.0

package.json, src/annotations/api/index.ts, src/timeMachine/reducers/index.ts
Trying to update the open api sha and had to fix a few things so tests pass
=> chore: update open api sha

src/secrets/components/CreateSecretForm.tsx, src/secrets/components/EditSecretForm.tsx, src/secrets/components/SecretCard.tsx, src/secrets/components/SecretContextMenu.tsx, src/secrets/components/SecretsTab.tsx
Closes #2667 
Adds event tracking for various secrets page uses.
=> chore: add secrets eventing

src/flows/components/header/index.tsx, src/flows/context/flow.query.tsx
- fix flag name
- handle undefined org
=> fix: notebook flag bugs

src/authorizations/components/AllAccessTokenOverlay.tsx, src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx, src/authorizations/components/redesigned/ResourceAccordion.tsx, src/authorizations/components/redesigned/customApiTokenOverlay.scss, src/authorizations/utils/permissions.ts
Closes #1929 
After selecting permissions for resources, user can now click generate token button and create token with specified permissions.
https://user-images.githubusercontent.com/66275100/134246910-a0b90f65-1206-430f-9964-8ac211b4ef58.mov
=> feat: generate token button calls api

src/App.tsx, src/flows/components/FlowPage.tsx, src/flows/components/FromTemplatePage.tsx, src/flows/components/header/SaveState.tsx, src/flows/components/header/index.tsx, src/flows/context/flow.current.tsx, src/flows/context/flow.list.tsx, src/flows/context/results.tsx, src/flows/context/shared.tsx, src/flows/pipes/MetricSelector/view.tsx, src/flows/pipes/QueryBuilder/view.tsx, src/flows/pipes/ToBucket/view.tsx, src/flows/style.scss, src/types/flows.ts
base mechanism for ephemeral notebook. there are still some things to do based on the figma, but i wanna make sure people take it for a spin before we start investing more into it.
=> feat: ephemeral notebook

src/alerting/components/AlertingIndex.tsx, src/dataExplorer/components/DataExplorerPage.tsx, src/shared/components/cta.scss, src/tasks/components/TasksHeader.tsx
Closes #2695 
Adds close button on flows CTAs like so:
=> feat: add close button on flows CTAs

src/buckets/pagination/BucketList.tsx, src/buckets/pagination/BucketsIndex.tsx, src/buckets/pagination/BucketsTab.tsx, src/shared/components/tabbed_page/TabbedPageHeader.tsx, src/shared/containers/SetOrg.tsx, src/shared/containers/index.tsx, src/tasks/pagination/TasksList.tsx, src/types/shared.ts
Starts #2627
Adds the first parts of structure for paginated buckets. There are some more tweaks that need to be made, but this code is behind a feature flag and there's enough of it to get a review on.
=> feat(flagged): bucket pagination

src/flows/templates/types/task.ts
=> feat: better supported text

src/buckets/components/createBucketForm/MeasurementSchema.scss, src/buckets/components/createBucketForm/MiniFileDnd.test.tsx, src/buckets/components/createBucketForm/MiniFileDnd.tsx, src/buckets/components/createBucketForm/SchemaToggle.tsx
=> feat: create mini file dnd element

src/me/components/DocSearchWidget.scss, src/shared/search/GlobalSearch.scss
Closes #2673
Removes the branding
=> chore: remove algolia branding

src/tasks/components/TasksHeader.tsx, src/tasks/containers/TasksPage.tsx
Closes #2727
**Working with Paginated Tasks**
**Working without Paginated Tasks**
=> fix: move the notebooks nag css for tasks into the file its used

cypress/e2e/shared/telegrafPlugins.test.ts, src/resources/selectors/index.ts, src/types/dataLoaders.ts, src/writeData/components/AddPluginToConfiguration.tsx, src/writeData/components/PluginAddToExistingConfiguration/Configure.tsx, src/writeData/components/PluginAddToExistingConfiguration/Customize.tsx, src/writeData/components/PluginAddToExistingConfiguration/Footer.tsx, src/writeData/components/PluginAddToExistingConfiguration/StepSwitcher.tsx, src/writeData/components/PluginAddToExistingConfiguration/Wizard.tsx, src/writeData/components/PluginCreateConfigurationCustomize.tsx, src/writeData/components/PluginCreateConfigurationFooter.tsx, src/writeData/components/PluginCreateConfigurationOptions.tsx, src/writeData/components/PluginCreateConfigurationStepSwitcher.tsx
Closes #1744 
Closes #1748 
Closes #2696 
Create a new config with a plugin. Then add the same plugin again to the same config:
https://user-images.githubusercontent.com/10736577/135343488-788300ed-566e-4fcf-808a-ca9b293ce54c.mp4
Create a new config with a plugin. Then add a different plugin to the same config:
https://user-images.githubusercontent.com/10736577/135344225-7afd0d4b-750d-4989-aa59-266241fdeae4.mp4
=> feat: add editing an existing telegraf config with a plugin

src/buckets/actions/thunks.test.ts, src/buckets/actions/thunks.ts, src/buckets/api/index.ts, src/external/monaco.flux.server.ts
Closes #2628
flagged behind `fetchAllBuckets` feature flag
=> feat(flagged): fetch all buckets from the API

cypress/e2e/shared/telegrafs.test.ts
Needed to make the pipeline pass again.
=> test: update flag in telegrafs e2e test

src/dataLoaders/components/collectorsWizard/select/StreamingSelector2.tsx, src/dataLoaders/reducers/telegrafEditor.ts, src/writeData/constants/contentTelegrafPlugins.ts, src/writeData/index.ts
=> chore: untangle the use of "TelegrafPlugin" as an interface name

src/flows/components/ReadOnly.tsx, src/flows/components/ReadOnlyHeader.tsx, src/flows/components/header/TimeRangeLabel.tsx
Closes #2773 
Shared notebooks display time range and time zone
https://user-images.githubusercontent.com/6411855/135892390-dfb68202-fe42-4c92-a859-c5e6ef3e3d06.mov
=> feat: shared notebooks get time range / zone

src/flows/components/PipeList.tsx, src/flows/components/ReadOnly.tsx, src/flows/components/header/TimeRangeDropdown.tsx, src/flows/components/header/index.tsx, src/flows/context/flow.query.tsx, src/flows/style.scss
Closes #2787
- Centers the resizer on the panel
- When toggling the share menu, don't `queryAll`
- Add eventing for creating, deleting, and visiting shared notebooks
- Change the color of the share icon when the notebook is already shared
=> chore: misc notebooks things

.gitignore, cypress/e2e/shared/dashboardsIndex.test.ts
This PR adds a test that ensures that both export options work properly.
=> test(cypress): export dashboard

src/buckets/pagination/BucketList.tsx, src/tasks/pagination/TasksList.tsx
=> fix: minimum totalPages allowed is 1

src/buckets/pagination/BucketList.tsx, src/tasks/pagination/TasksList.tsx
See #2801
This is an attempt to fix persistent scrollbars. Since this seems to be system dependent and hard to recreate, I'm not sure if this will fix the issue.
=> fix(pagination): set scroll to auto to remove persistent horizontal scrollbar

src/buckets/pagination/BucketsTab.tsx, src/tasks/pagination/TasksPage.tsx
Closes: https://github.com/influxdata/ui/issues/2764
Added that to the buckets and tasks page
https://user-images.githubusercontent.com/18511823/136086753-07f52109-ef0a-4711-9f8b-38232bf8f27d.mov
=> feat: store search term in url for buckets and tasks

src/flows/templates/types/bucket.ts
Closes #2878
fixes an error caused by a weird merge from the other day. works now!
=> fix: from bucket template fix

src/flows/context/flow.current.tsx
Some tidying up of implementation details as we continue down this path.
=> chore: clean up some of the yjs work

cypress/e2e/shared/tokens.test.ts
Closes #3083 
Updated the test to check if the button exists before actually clicking on it.
=> fix: Tokens delete flaky test

src/authorizations/components/redesigned/EditTokenOverlay.tsx, src/authorizations/components/redesigned/ResourceAccordion.tsx, src/authorizations/components/redesigned/customApiTokenOverlay.scss
=> feat: overlay scrollbars

src/flows/components/ClientList.tsx, src/flows/components/Sidebar.scss
=> fix: export client css got borked

src/flows/pipes/ToBucket/view.tsx
=> fix: fix to bucket dropdown issue

src/flows/components/FromTemplatePage.tsx, src/flows/components/header/index.tsx, src/flows/context/flow.current.tsx, src/flows/context/flow.list.tsx, src/types/flows.ts
This PR introduces serialization and hydration of data as it flows in and out of chatrooms so that the API doesn't have to do those operations prior to writing data
=> feat: serialize and hydrate data before setting it into the ydoc

src/organizations/components/DeleteOrgContext.tsx, src/organizations/components/DeleteOrgOverlay.tsx
Same routing as https://github.com/influxdata/ui/pull/3063
=> feat: add appropriate routing after account deletion

cypress/e2e/cloud/buckets.test.ts, src/buckets/components/createBucketForm/MeasurementSchema.scss, src/buckets/components/createBucketForm/MeasurementSchemaSection.tsx
Closes #3172 
original:
new one:
=> tweaking layout with names

src/flows/templates/types/tools.ts
trying to debug some slow ass notebooks and i need to inject something more than a breakpoint, but it's hard to replicate them locally (they're usually long)
=> feat: import notebook from tools for local debugging

package.json, src/me/components/Resources.tsx, src/me/components/UsagePanel.tsx, src/me/components/UsagePanelDetails.tsx, src/me/containers/MePage.tsx, src/shared/constants/index.ts, src/usage/context/usage.tsx, yarn.lock
Add PAYG Credit Usage Panel
Specifically,
With enough credit
Less than 15 days remaining
=> feat: add payg usage panel

cypress/e2e/shared/tokens.test.ts
=> fix: delete a token test flakiness

src/authorizations/components/redesigned/ResourceAccordion.tsx, src/authorizations/components/redesigned/TokenRow.test.tsx, src/authorizations/components/redesigned/TokenRow.tsx, src/authorizations/components/redesigned/TokensTab.test.tsx
Closes #3187 
Closes #3205
https://user-images.githubusercontent.com/12561526/141204233-5ee57060-9812-4e8e-8c3e-9801e0e7fbb3.mov
^ This is what it used to do 
Below is what it does now
https://user-images.githubusercontent.com/12561526/141204345-acbd5ac9-9125-489c-be04-0ce3fce6b77c.mp4
and here's the new context menu
Deprecate old context menu
fix scroll bar expansion
=> fix: fix context menu styling and scroll bar issue

src/flows/components/panel/FlowPanel.tsx, src/flows/index.ts
Couple places I forgot to change the text from Preview to Run
=> fix(notebooks): Preview --> Run

cypress/e2e/shared/flows.test.ts, src/flows/pipes/Notification/view.tsx, src/shared/selectors/flags.ts
We've tested this feature and are ready to remove the flag
=> chore: remove notebooksExp flag

src/dataLoaders/actions/dataLoaders.ts, src/onboarding/components/CompletionStep.tsx, src/scrapers/actions/thunks.ts, src/types/scrapers.ts
=> chore: remove the client.scrapers

src/checkout/context/checkout.tsx, src/me/components/UsagePanelDetails.tsx, src/usage/context/usage.tsx
We need a checkout code on top of the experiment id.
Use Case. if the user is in the experiment and they choose not to upgrade and then later decide to upgrade. they shouldn’t see the credit.
=> feat: add checkout query param2

src/flows/components/ReadOnlyHeader.tsx, src/flows/components/ReadOnlyPipeList.tsx
Closes influxdata/idpe/issues/12372
Removes export from shared notebooks, updates signup button
=> chore: remove export from shared notebook

src/flows/components/FlowPage.tsx
=> feat: add notebook access event

src/flows/pipes/Schedule/ExportTaskButton.tsx, src/flows/pipes/Schedule/view.tsx
=> feat: changing button text

src/checkout/CheckoutForm.scss
=> chore: change credit banner positioning

src/flows/context/flow.current.tsx
Just some general clean up along the ywebsocket work that should be good to go in with the API work. Still need to massage authentication out with the API
=> chore: removed some no longer relevant code

src/flows/components/header/index.tsx
Closes #3251 
allows for cloning and deleting from the main notebooks page
=> feat: move clone and delete

src/flows/templates/types/bucket.ts
addresses #3327 
might not actually close the issue, but i think it might address some crashes from a schema change that didnt get migrated over
=> fix: stop bucket bleed

src/authorizations/utils/permissions.test.ts, src/authorizations/utils/permissions.ts
=> feat: add remotes and replications OSS resource types

cypress/e2e/shared/dashboardsRefresh.test.ts, cypress/e2e/shared/tasks.test.ts, cypress/support/commands.ts
just a place to run tests a bunch of times
=> chore: unflake tests

cypress/e2e/shared/dashboardsRefresh.test.ts, cypress/e2e/shared/dashboardsView.test.ts, cypress/e2e/shared/explorerVisualizations.test.ts, cypress/e2e/shared/tasks.test.ts, cypress/support/commands.ts
chasing the idea that the flakiness is caused by https://github.com/influxdata/ui/issues/3347
=> fix: remove delays

package.json
required for: https://github.com/influxdata/quartz/issues/4737
=> chore: update openapi SHA to get newest api changes for operator page

src/flows/pipes/Schedule/view.tsx
=> fix: broken template

src/flows/pipes/Schedule/view.tsx
=> fix: error when exporting a task

src/writeData/components/WriteDataSections.tsx
Closes #
Added a grid surrounding the plugin sections, so when the scrolling happens, the scrollbar is moving up/down accordingly.
=> fix: added a grid around all plugin sections

src/authorizations/components/TokenRow.tsx, src/authorizations/components/redesigned/TokenRow.tsx
=> fix: inactive tokens should display greyed out resource card

src/checkout/LogoWithCubo.scss, src/checkout/LogoWithCubo.tsx, src/flows/components/ReadOnlyHeader.tsx, src/shared/components/GetInfluxButton.tsx, src/shared/components/NotFound.scss, src/shared/components/NotFound.tsx
**BEFORE**
**AFTER**
**Also Updated**
Made Icon optional
Made InfluxDB Cloud Icon styling stand-alone
=> chore: add missing button and text

src/flows/pipes/Schedule/view.tsx
Closes #3102
Removed the error message for "Required" before users input anything.
Current view:
=> fix: not showing error before user input anything

src/shared/components/NotFound.scss
Add more padding to panel.
**BEFORE**
**AFTER**
=> chore: add uniform padding

src/flows/pipes/QueryBuilder/BucketSelector.tsx
Clozez #2879 
**BEFORE**
**AFTER**
=> feat: scroll selected bucket into view

src/authorizations/components/TokensRedesignBanner.tsx, src/authorizations/components/TokensTab.tsx
Closes #2108 
PR adds alert banner in `TokensTab`  with information for user on when the tokens new UI is going live. 
Questions: 
- Should we add an 'x' at the top corner of the banner to give user the ability to remove banner?
- Should we change the color of banner to red or some other color that makes it stand out?
=> feat: Tokens redesign banner

cypress/e2e/cloud/buckets.test.ts
Let's see how they perform with repeated runs.
=> test: update buckets tests for cloud explicit buckets

webpack.dev.ts, yarn.lock
=> chore: remove unnecessary config

cypress/e2e/cloud/buckets.test.ts, cypress/e2e/cloud/operator.test.ts, cypress/e2e/cloud/operatorRO.test.ts, src/operator/account/AccountView.tsx, src/operator/constants.tsx
add name and change header of the account operator  page
also add 'account name' to the account list page
Closes influxdata/quartz#4737
=> feat: Account Operator Pages

src/authorizations/components/redesigned/AllAccordionBody.tsx, src/authorizations/components/redesigned/IndividualAccordionBody.tsx, src/authorizations/components/redesigned/customApiTokenOverlay.scss
=> fix: add message when no results found in search

src/flows/context/bucket.scoped.tsx, src/flows/pipes/QueryBuilder/BucketSelector.tsx
=> fix: don't remove bucket from selection, if not exists

package.json
=> chore: updating SHA for multi-account work; no other changes

src/buckets/actions/thunks.ts, src/shared/copy/notifications.ts
Show success notification on bucket delete success.
=> feat: add bucket delete success notification

cypress/e2e/oss/onboarding.test.ts, cypress/e2e/shared/dashboardsRefresh.test.ts, mocks/dummyData.ts, src/Setup.tsx, src/onboarding/actions/index.ts, src/onboarding/components/AdminStep.tsx, src/onboarding/components/OnboardingStepSwitcher.tsx, src/onboarding/containers/OnboardingWizard.tsx, src/onboarding/containers/OnboardingWizardPage.tsx, src/onboarding/containers/SigninPage.tsx, src/onboarding/reducers/index.ts
Closes #3469 
Iterating on some work to remove usages of the client so that we can remove @influxdata/influx - we'll see if we can make that happen
=> chore: remove some more client usages

src/shared/components/NotFound.tsx
Hackathon 2022 POC for deep linking. Flagged behind the `deepLinking` flag.
Redirects the following `/me/` links to their respective areas of the app:
```
/me/alerts => /orgs/$ORG_ID/alerting
/me/billing => /orgs/$ORG_ID/billing
/me/dashboards => /orgs/$ORG_ID/dashboards-list
/me/notebooks => /orgs/$ORG_ID/notebooks
/me/tasks => /orgs/$ORG_ID/tasks
/me/usage => /orgs/$ORG_ID/usage
```
which should allow us to do something like putting `cloud2.influxdata.com/me/billing` into an email and allow all users to get redirected to their billing page. Will most likely require further testing and refinement in cloud environments.
=> feat: deep linking POC for hackathon2022

src/flows/pipes/Notification/endpoints/Slack/readOnly.tsx
=> chore: remove parenthesis from readonly component

src/flows/components/Sidebar.tsx, src/flows/components/panel/FlowPanel.tsx, src/flows/context/flow.current.tsx, src/shared/copy/notifications.ts
=> feat: add deep linking to a pipe

src/flows/context/flow.query.tsx, src/shared/copy/notifications.ts
=> fix: remove success message

cypress/e2e/cloud/billing.test.ts
feature flag setting is being inconsistent and flaky
this is to fix the deployment pipeline.
=> test: reverting billing test to the old style

yarn.lock
The previous commit missed the yarn lock contents. Adding it now.
=> chore: missed yarn lock commit

src/timeMachine/components/Vis.tsx
Closes https://github.com/influxdata/ui/issues/3477
Video:
https://user-images.githubusercontent.com/18511823/149031181-751dfc6d-0eea-42a4-98b1-0a19e89a0852.mov
=> feat: color mapping for when the cell is edited through the time machine

src/visualization/types/Graph/options.tsx, src/visualization/utils/colorMappingUtils.ts
Closes https://github.com/influxdata/ui/issues/3099
Video: 
https://user-images.githubusercontent.com/18511823/149033015-fe2f1228-bee4-4d6d-87ee-f223206f7fe2.mov
=> feat: color mapping for when the cell color family is updated.

src/flows/shared/Resizer.scss
Closes #3416
couldnt find the PR where i fixed this, so i made a new one!
=> fix: split newlines

src/pageLayout/components/UserWidget.tsx
=> chore: added email address to the userWidget

cypress/e2e/shared/dashboardsRefresh.test.ts, src/dashboards/components/DashboardHeader.tsx
This is some clean-up to remove a feature flag on a feature that's been live for a while
=> chore: remove autorefresh flag for dashboards

package.json, yarn.lock
Removed html-to-react since it seems like it's an unused dependency
=> chore: remove html-to-react

package.json, yarn.lock
Update clockface version to v3.1.12. Fixes List bugs.
=> chore: update clockface version

src/authorizations/components/redesigned/DisplayTokenOverlay.tsx
Closes https://github.com/influxdata/ui/issues/3417
Small fix for the confirmation text.
=> fix: text in tokens confirmation page

src/variables/actions/thunks.ts
Closes https://github.com/influxdata/idpe/issues/12824
This code is relevant when creating a new dashboard cell on an empty dashboard (i.e. creating the first cell of a dashboard). See the issue for more context. This is a somewhat scary change for me, so it's hidden behind a feature flag.
- All variables would be hydrated, regardless of whether they were used in the query
_no variables in the query, yet there are 4 queries to fetch and hydrate the variables (plus the actual query request)_
- Only variables used in the query of the new cell will be hydrated. If no variables are present, no variables get hydrated.
_no variables in the query, only a single query request (to run the actual query)_
_two variables, two requests to fetch and hydrate those variables (plus the actual query …
=> fix: only hydrate relevant variables on new cells on empty dashboards

cypress/e2e/shared/notificationRules.test.ts, src/alerting/components/builder/ThresholdValueInput.tsx
Closes https://github.com/influxdata/ui/issues/3399
Video:
https://user-images.githubusercontent.com/18511823/150201180-42ec383a-26be-4f64-b2b6-9899b302e0d6.mov
=> fix: better input status for ThresholdValueInput

cypress/e2e/cloud/billing.test.ts, cypress/e2e/cloud/zuoraOutage.test.ts
removing comments as discussed in pr here:  https://github.com/influxdata/ui/pull/3612#pullrequestreview-855860691
created issue: https://github.com/influxdata/ui/issues/3651
=> chore: removing comments.  no code changes AT ALL

src/users/components/UserList.tsx, src/users/components/UserListItem.tsx
When there is only one user in an account, do not allow that user to be removed from the account.
=> feat: disallow removal of last user from account

src/flows/components/panel/PanelQueryOverlay.tsx, src/flows/pipes/Visualization/view.tsx, src/flows/style.scss
Closes #3548
Closes #3567
just some quick hits
=> fix: some cleanup around notebooks

src/flows/pipes/QueryBuilder/context.tsx
=> fix: bucket selector toggle selection error fix

src/shared/components/DragAndDrop.scss, src/writeData/components/fileUploads/AnnotatedCSV.md, src/writeData/components/fileUploads/LP.md
Closes https://github.com/influxdata/ui/issues/3653
Minor text and color fix.
=> fix: file upload instructions

cypress/e2e/cloud/userAccounts.test.ts, src/accounts/AccountPage.tsx, src/accounts/SwitchAccountOverlay.tsx, src/accounts/context/userAccount.tsx, src/shared/copy/notifications.ts
Closes #3683
the required quartz-mock changes were merged in already; so that is all set (see below for a link to that PR)
screencap: 
https://user-images.githubusercontent.com/3900960/151412117-07b3f38d-9ef4-4a04-9755-316839f1e75f.mov
=> feat: Multi account/rename account

cypress/e2e/oss/explorer.test.ts, cypress/e2e/shared/dashboardsRefresh.test.ts, cypress/e2e/shared/flows.test.ts, src/dashboards/components/DashboardHeader.tsx, src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.scss, src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx, src/style/chronograf.scss, src/timeMachine/components/Queries.tsx, src/timeMachine/components/RefreshDropdown.tsx
Reverts influxdata/ui#3699
Let's try this again
=> revert: Revert "chore: remove the AutoRefreshDropdown Component"

cypress/e2e/shared/dashboardsIndex.test.ts, cypress/e2e/shared/explorer.test.ts
PR adds a test that injects variables into a flux editor.
=> test(cypress): add variable injection test

cypress/e2e/shared/dashboardsView.test.ts
PR adds a test that ensures visibility of variables control bar with and without defined variables.
=> test(cypress): add variable visibility test

src/accounts/AccountPage.tsx, src/accounts/AccountTabContainer.tsx, src/billing/components/BillingPage.tsx, src/buckets/components/createBucketForm/CreateBucketForm.tsx
Closes https://github.com/influxdata/ui/issues/3759
The alignment was not working well because the component hierarchy was wrong. I attempt to fix that. 
Prev:
After the fix:
=> fix: Account page header alignment for multi account

cypress/e2e/shared/buckets.test.ts, src/buckets/components/BucketCardActions.tsx, src/dataLoaders/actions/dataLoaders.ts, src/dataLoaders/components/collectorsWizard/TelegrafUIRefreshWizard.tsx, src/dataLoaders/components/collectorsWizard/select/TelegrafUIRefreshCollectorsStep.tsx, src/dataLoaders/reducers/dataLoaders.ts, src/types/dataLoaders.ts, src/writeData/components/PluginCreateConfiguration/Footer.tsx
Closes https://github.com/influxdata/ui/issues/3188
Video:
https://user-images.githubusercontent.com/18511823/141187555-9ef5eb17-0d73-4244-b90f-9333c5044214.mov
=> feat: add the new telegraf refresh ui path from buckets card

src/writeData/clients/CSharp/initialize.example, src/writeData/clients/R/initialize.example, src/writeData/clients/Swift/initialize.example
Related to https://github.com/influxdata/ui/pull/3704
Read token from system environments for:
- Swift
- C#
- R
=> chore(client_libs): read token from sys envs

package.json, src/flows/components/header/index.tsx, src/shared/copy/notifications.ts
This is an initial pass at adding the save draft state functionality to a notebook.
=> feat: introduction to publish lifecycle

package.json
Removed notebooks share PUT. Need to update UI to use the latest openapi.
=> chore: use updated openapi

package.json, src/cloud/utils/reporting.ts, src/shared/constants/index.ts, yarn.lock
adds amplitude as a reporting mechanism
waiting on https://github.com/influxdata/monitor-ci/pull/342
flag defined in https://github.com/influxdata/idpe/pull/13128
=> feat: adding in amplitude

src/flows/components/Sidebar.tsx
if a panel can make flux, you should be able to reuse that flux
=> feat: pushing more links

cypress/e2e/shared/dashboardsView.test.ts
This PR adds a test that ensures functionality of cell views in dashboards. This PR is a repaired version of PR 3607.
=> test(Cypress): add cellView test

cypress/e2e/shared/flows.test.ts, src/flows/components/Sidebar.tsx
=> chore: remove export to client lib menu item for markdown

cypress/e2e/shared/deepLinks.test.ts, src/shared/components/NotFound.tsx, src/utils/deepLinks.ts
=> feat: add more deeplinks

src/flows/pipes/Visualization/view.tsx
=> chore: fix the ts issue

cypress/e2e/cloud/billing.test.ts
duplicate and incorrect test description. update test description.
=> chore: update test description

src/accounts/context/userAccount.tsx, src/me/actions/thunks/index.ts
Part of: https://github.com/influxdata/ui/issues/3757
Last time I shipped the wrong flag!
=> fix: replace avatarNameForMultiAccountFix with avatarWidgetMultiAccountInfo

cypress/e2e/shared/explorerVisualizations.test.ts, cypress/e2e/shared/flows.test.ts, package.json, src/style/chronograf.scss, src/views/helpers/index.ts, src/visualization/styles/Band.scss, src/visualization/types/Band/icon.tsx, src/visualization/types/Band/options.tsx, src/visualization/types/Band/properties.ts, src/visualization/types/Band/view.tsx, src/visualization/utils/useBandColumns.ts, yarn.lock
Closes #3404 
- gives the user a set of dropdowns to select the column names
- finds the default column for the main column without the user needing to adjust any options
- **_no longer crashes in Notebooks - IT WORKS_**
https://user-images.githubusercontent.com/10736577/153978887-b99345e0-0e32-4fd3-83fe-bb0f436dd671.mp4
=> fix: allow Band plot to work prior to user interaction with options

src/flows/pipes/Notification/endpoints/Mailjet/index.ts, src/flows/pipes/Notification/endpoints/SendGrid/index.ts
Closes #3764 
Closes #3788 
* Mailjet notebook alerts, test alerts and exported tasks, are functional.
* Sendgrid notebook alerts, test alerts and exported tasks, are functional.
* it was all about the flux.
Mailjet:
https://user-images.githubusercontent.com/10232835/154174110-bece220e-81e6-4b5c-94e4-43bc726a5eb0.mov
Sendgrid:
https://user-images.githubusercontent.com/10232835/154174162-db31ffe8-0255-40ee-b47b-c43be2de6b6e.mov
=> fix(3764/3788): mailjet & sendgrid alerts from notebooks

src/me/actions/thunks/index.ts
Part of : https://github.com/influxdata/ui/issues/3757
This function is behaving very differently in different enviornments so we need to print the outputs to see what is going on.
=> chore: trying some console log statements for getMe call

src/flows/components/FlowCards.tsx, src/flows/components/FlowContextMenu.tsx
Closes #3861 
This PR fixed the bug that used to allow users to pin a notebook more than one time. 
https://user-images.githubusercontent.com/14298407/154287606-6624ea71-9f93-4293-8001-8f9549d02389.mov
https://user-images.githubusercontent.com/14298407/154287750-58e598b4-1e98-4460-827d-f9f4be02d9c7.mov
=> fix: prevent duplicated pinned items

src/flows/pipes/Schedule/view.tsx
=> fix(3910): change text on export button

cypress/e2e/shared/flows.test.ts, src/flows/components/Sidebar.tsx, src/flows/pipes/Schedule/view.tsx, src/flows/pipes/Visualization/view.tsx, src/types/flows.ts
added a hidden state so that the user knows an option is available eventually, just not yet because some status hasn't been unlocked. also adds a patch to the schedule dropdown for when users wanna overwrite an existing task
=> fix: hidden vs disabled

src/flows/components/header/VersionHeader/CloneButton.tsx, src/flows/components/header/VersionHeader/RevertButton.tsx
=> chore: clean things up

src/flows/components/header/index.tsx, src/flows/pipes/Visualization/ErrorThresholds/ThresholdEntryColumn.tsx, src/flows/pipes/Visualization/view.tsx
This PR resolves an issue where floats were being coerced to round numbers when the input included a decimal.
=> chore: allow for floats

cypress/e2e/shared/deepLinks.test.ts
=> test: turn on deep link e2e tests

cypress/e2e/shared/tasks.test.ts, src/tasks/actions/thunks.ts, src/tasks/containers/TasksPage.test.tsx
Part 2 (tasks) of idpe 13138
- Cloning tasks will now also clone the labels
https://user-images.githubusercontent.com/10736577/155248265-72f78e1b-e80f-4da6-9283-67ee47182b21.mp4
=> fix: update tasks cloning to include labels

src/me/actions/thunks/index.ts
Reverts influxdata/ui#3881
We don't need the console warn statements anymore.
=> revert: Revert "chore: trying some console log statements for getMe call"

cypress/e2e/shared/telegrafs.test.ts, src/shared/copy/notifications.ts, src/telegrafs/actions/thunks.ts, src/telegrafs/components/CollectorCard.tsx
Part 1 (telegrafs) of idpe 13138
- Cloning telegraf configurations will now also clone the labels
https://user-images.githubusercontent.com/10736577/155422775-5ae8b9b3-add4-4d43-b38a-3939464773ea.mp4
=> fix: update telegraf cloning to include labels

src/authorizations/components/GenerateTokenDropdown.tsx, src/shared/copy/notifications.ts
Fixes https://github.com/influxdata/ui/pull/3906/files#r813422841
=> fix: add token type to notification message for failure to fetch resources

cypress/e2e/shared/tasks.test.ts
=> chore: more flakey test fixes

.gitignore, package.json
Part of #3180 
Add the `fluxdocs` to `generate` script
=> fix: add fluxdocs to yarn generate

package.json
Updates the routes for `fluxdocs`
=> chore: update the openapi SHA

src/flows/pipes/Notification/endpoints/Telegram/index.ts
=> fix: fix telegram message flux issue

src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/HomepageIcons.tsx, src/homepageExperience/components/Navigation.tsx, src/homepageExperience/components/steps/Step.tsx
Connects https://github.com/influxdata/ui/issues/3885
Demo:
https://user-images.githubusercontent.com/18511823/156443965-731671df-24d1-433b-8a86-4501007e6beb.mov
=> feat: vertical subway-styled navigation for the homepage experience

cypress/e2e/cloud/operator.test.ts, cypress/e2e/shared/flows.test.ts
**Flaky Tests**
flows.test.ts
operator.test.ts
**Broken Tests Videos**
https://user-images.githubusercontent.com/1637395/156644486-0b2621c7-cfcb-4606-b775-d7963a202a08.mp4
https://user-images.githubusercontent.com/1637395/156644502-6ba7dcd1-3a2b-4ebf-9d92-c8907185f536.mp4
=> fix: flaky tests fix: flows, operator

cypress/e2e/shared/flows.test.ts
Remove `Link to Panel` from side for querybuilder or figure out why it's not showing up in deployment pipeline.
=> fix: add flow test fix

cypress/e2e/shared/dashboardsIndex.test.ts, src/visualization/types/Graph/view.tsx
Closes: https://github.com/influxdata/ui/issues/3965
Closes: https://github.com/influxdata/ui/issues/3920
Those functions better deal with the uncertainty of columns not existing, inspired from the Band graph's code. 
Video: 
https://user-images.githubusercontent.com/18511823/155772141-2e2b158b-aa29-495b-b1f0-decc4264e715.mov
=> fix: use the getColumnType and getColumn functions in Graph/view

src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/Navigation.tsx, src/homepageExperience/components/steps/Step.tsx, src/homepageExperience/containers/HomepageContainer.tsx, src/homepageExperience/containers/HomepagePythonWizard.tsx, src/homepageExperience/utils.ts, src/shared/containers/SetOrg.tsx, src/shared/containers/index.tsx
Addresses #3882
Adds a basic homepage with a link to the python wizard.
=> feat(firstMile): add landing page

src/writeData/components/fileUploads/CSV.md
=> chore(load-data): added link to install the CLI

src/homepageExperience/components/ConnectionInformation.tsx, src/homepageExperience/components/DataListening.tsx, src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/HomepageIcons.tsx, src/homepageExperience/components/steps/ExecuteQuery.tsx, src/homepageExperience/components/steps/WriteData.tsx, src/homepageExperience/containers/HomepagePythonWizard.tsx
Closes https://github.com/influxdata/ui/issues/3890
Closes #3891 
Closes #3892 
https://user-images.githubusercontent.com/18511823/157506145-1db8d676-6a11-4bab-8848-c7dfd8bdd330.mov
=> feat: WriteData page for homepage experience

src/flows/components/header/index.tsx
Pard of #3800 
This PR removes the feature flag `downloadNotebookPDF` in ui. After this PR is merged, I'll remove the feature flag from idpe.
=> chore: remove feature flag `downloadNotebookPDF`

src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/HomepageIcons.tsx, src/homepageExperience/components/steps/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/Finish.tsx, src/homepageExperience/containers/HomepagePythonWizard.tsx, src/homepageExperience/utils.ts
Closes #3893 
Closes #3894 
Screen recording:
https://user-images.githubusercontent.com/18511823/157739872-5eb5e364-f1d4-49c0-a1d5-5f0d60e9794b.mov
=> feat: Execute aggregate query and finish steps

package.json, src/flows/components/VersionSidebar.scss, src/flows/components/VersionSidebar.tsx, src/flows/components/header/MenuButton.tsx, src/flows/components/header/index.tsx, src/shared/copy/notifications/categories/notebooks.ts, yarn.lock
This PR does some clean up to some of the existing flow header implementation to separate concerns a bit. It also updates the publish lifecycle to the new designs and updates clockface to get some more icons.
=> feat: update the publish design and add some guardrails

src/shared/components/TimeZoneDropdown.tsx
there seems to be some contention around whether or not people find the timezone dropdown useful. instead of blindly yoloing that call, lets see if our users are currently using this feature and where they engage with it most
=> fix: add eventing around controversal dropdown

src/flows/components/FlowsIndex.tsx, src/flows/components/header/MenuButton.tsx
we dont have any metrics around how people are interacting with the list page in notebooks, and missed the whole notebook dropdown interaction
=> fix: some missing events

cypress/e2e/shared/about.test.ts, cypress/e2e/shared/flows.test.ts, cypress/e2e/shared/flowsAlerts.test.ts
=> test: update flows and about tests

cypress/e2e/shared/flows.test.ts
- intercept the specific api call that updates the notebook spec
- hit enter after typing the name to trigger the api call
=> test: fix flows cloning flakiness

src/resources/components/GetResources.tsx, src/shared/search/GlobalSearch.tsx
found another event that was blowing up our unique event  name counter in amplitude
=> fix: whoa cardinality

CODEOWNERS, src/writeData/subscriptions/components/SubscriptionCard.tsx, src/writeData/subscriptions/components/SubscriptionsLanding.tsx, src/writeData/subscriptions/context/api.tsx, src/writeData/subscriptions/context/subscription.list.tsx
Closes https://github.com/influxdata/data-acquisition/issues/175
Adds the ability to delete a subscription
=> feat(sub): delete ability

src/homepageExperience/components/steps/ExecuteAggregateQuery.tsx
Closes https://github.com/influxdata/ui/issues/4140
=> feat: add filter to ExecuteAggregateQuery.tsx

src/homepageExperience/components/steps/InstallDependencies.tsx
=> fix: add python link to InstallDependencies (first mile)

src/writeData/clients/Dart/description.md, src/writeData/clients/Dart/dispose.example, src/writeData/clients/Dart/execute.example, src/writeData/clients/Dart/executeFull.example, src/writeData/clients/Dart/index.ts, src/writeData/clients/Dart/initialize.example, src/writeData/clients/Dart/logo.svg, src/writeData/clients/Dart/query.example, src/writeData/clients/Dart/write.0.example, src/writeData/clients/Dart/write.1.example
Add [`influxdb-client-dar`](https://github.com/influxdata/influxdb-client-dart) into **Client Libraries**.
=> feat(client_libs): add Dart client lib

src/writeData/subscriptions/components/JsonParsingForm.tsx, src/writeData/subscriptions/components/JsonPathInput.tsx, src/writeData/subscriptions/context/subscription.create.tsx
changes type to lowercase and adds timestamp as default name to fix json parsing functionality for create subscription.
=> fix: json parsing

src/homepageExperience/components/steps/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/ExecuteQuery.tsx, src/homepageExperience/components/steps/InitalizeClient.tsx, src/homepageExperience/components/steps/WriteData.tsx, src/homepageExperience/containers/HomepagePythonWizard.tsx
Closes https://github.com/influxdata/ui/issues/4160
Uses the variables to auto-populate the variables in the script.
https://user-images.githubusercontent.com/18511823/159373138-13de82d1-84cb-4881-9650-5551eee82c05.mov
=> feat: auto-populate variables for first mile python

src/accounts/AccountPage.tsx, src/users/components/UserList.tsx
Part of influxdata/quartz#4686
Removes the branching code around the flag `selfRemovalFromAccount`
=> chore: remove branching code around selfRemovalFromAccount

src/homepageExperience/containers/HomepageContainer.scss, src/homepageExperience/containers/HomepageContainer.tsx
Closes https://github.com/influxdata/ui/issues/4174
* Made the page a little more responsive
* adds the documentation panel
Video: 
https://user-images.githubusercontent.com/18511823/159637486-6baa0538-3f77-4cd4-97b3-240dc9f69580.mov
=> fix: styling for the homepage container (first mile), add documentation panel

src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/Navigation.tsx, src/homepageExperience/components/steps/Step.tsx, src/homepageExperience/containers/HomepagePythonWizard.tsx
Closes #4181
https://user-images.githubusercontent.com/146112/159736085-378e946e-1418-470a-8be7-fd919b81dc5a.mov
=> feat(firstMile): make subway navigation links clickable

src/shared/components/resource_sort_dropdown/generateSortItems.ts, src/types/subscriptions.ts, src/writeData/subscriptions/components/SubscriptionCard.tsx, src/writeData/subscriptions/components/SubscriptionsLanding.tsx
Closes https://github.com/influxdata/data-acquisition/issues/95
Adds filter by name and sort by updated at/ name to subscriptions list view.
Adds last modified and status info to details card.
=> feat: subscriptions list

src/buckets/components/CreateBucketButton.tsx, src/buckets/components/Retention.tsx, src/buckets/components/createBucketForm/BucketOverlayForm.tsx, src/buckets/components/createBucketForm/CreateBucketForm.tsx, src/buckets/components/createBucketForm/CreateBucketOverlay.tsx, src/homepageExperience/components/steps/WriteData.tsx, src/writeData/components/WriteDataHelperBuckets.tsx
Closes https://github.com/influxdata/ui/issues/4143
Simplified the bucket form for the first mile experience. 
Video: 
https://user-images.githubusercontent.com/18511823/159787235-c6e76559-3ba4-4afd-aa70-81d6039c71ea.mov
=> feat: make BucketOverlayForm to have a useSimplifiedBucketForm prop

src/homepageExperience/components/steps/InitalizeClient.tsx, src/homepageExperience/components/steps/WriteData.tsx
Closes https://github.com/influxdata/ui/issues/4191
=> chore(firstMile): update code snippets for write data and initialize client pages

src/usage/UsageXYGraph.tsx, src/visualization/utils/colorMappingUtils.ts
Closes https://github.com/influxdata/ui/issues/4194
Closes https://github.com/influxdata/ui/issues/4011
Closes https://github.com/influxdata/ui/issues/4031
Among multiple of similar usage page issues reported.
https://user-images.githubusercontent.com/18511823/159864353-f9e788bc-f5d8-4de6-a27c-84f86e0671bf.mov
=> fix: usage page make it work with `graphColorMapping` flag

src/flows/context/flow.current.tsx
=> fix: fix convert to flux bug

src/flows/components/FlowsIndex.tsx
Closes #4240
i wish i could say i knew what this flag does but i do not
=> fix: weird header

src/flows/pipes/RawFluxEditor/view.tsx, src/timeMachine/components/fluxFunctionsToolbar/FunctionCategory.tsx
=> fix: stop injecting parenthesis

src/writeData/subscriptions/components/BrokerDetails.tsx, src/writeData/subscriptions/components/SubscriptionCard.tsx, src/writeData/subscriptions/components/SubscriptionDetails.tsx
update test ids for update e2e testing
=> fix: update ids

src/shared/copy/notifications/categories/subscriptions.ts, src/writeData/subscriptions/components/SubscriptionDetailsPage.scss, src/writeData/subscriptions/components/SubscriptionDetailsPage.tsx, src/writeData/subscriptions/context/api.tsx, src/writeData/subscriptions/context/subscription.create.tsx, src/writeData/subscriptions/context/subscription.update.tsx
Closes https://github.com/influxdata/data-acquisition/issues/203
Enables the user to start and stop their subscription.
=> feat: start/stop functionality subscriptions

src/homepageExperience/components/steps/nodejs/ExecuteQuery.tsx, src/homepageExperience/components/steps/nodejs/InitalizeClient.tsx, src/homepageExperience/components/steps/nodejs/WriteData.tsx, src/homepageExperience/components/steps/python/ExecuteQuery.tsx, src/homepageExperience/containers/NodejsWizard.tsx
Closes #4249
Based the example on the documentation from the [official js library.](https://github.com/influxdata/influxdb-client-js/blob/master/examples/query.ts)
=> feat(firstMile): add nodejs execute query step

src/flows/pipes/QueryBuilder/context.tsx
Related #3866
I'm not confident that we've seen the last of this bug since it's a difficult one to reproduce locally, but it is reproducible. I _think_ that the crux of the issue here is that we're referencing stale cardMeta when making these state updates, and so we might be setting stale data and never getting past the point of loading as a result of that. By removing the useCallback here, I'm hoping that we can resolve the stale state issue whereby we always reference the state at that point and aren't necessarily relying upon cached data. I was able to inconsistently reproduce the bug linked here in the query builder when I would select a bunch of measurements from a bucket and start adding and removing cards from the list, then refreshing the page. I would be able to reproduce this …
=> fix: potentially fixes the loading state forever bug

src/writeData/clients/Javascript/execute.example, src/writeData/clients/Javascript/executeFull.example
This PR changes javascript client examples to follow influxdata/influxdb-client-js#429 .
=> chore(docs): improve js client examples

cypress/e2e/cloud/subscriptions.test.ts
Helps with: https://github.com/influxdata/data-acquisition/issues/203
=> feat: status e2e

src/pageLayout/containers/TreeNav.tsx
Closes #3449 
Pr adds links to `Help & Support` sub menu items.
=> feat: add links to sub menu items

src/homepageExperience/components/steps/CreateToken.tsx, src/homepageExperience/components/steps/go/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/go/ExecuteQuery.tsx, src/homepageExperience/components/steps/go/InitalizeClient.tsx, src/homepageExperience/components/steps/go/InstallDependencies.tsx, src/homepageExperience/components/steps/go/WriteData.tsx, src/homepageExperience/containers/GoWizard.tsx, src/homepageExperience/containers/HomepageContainer.tsx, src/homepageExperience/containers/NodejsWizard.tsx, src/homepageExperience/containers/PythonWizard.tsx, src/shared/containers/SetOrg.tsx, src/shared/containers/index.tsx
Closes https://github.com/influxdata/ui/issues/4339
Closes https://github.com/influxdata/ui/issues/4340
Closes https://github.com/influxdata/ui/issues/4341
Closes https://github.com/influxdata/ui/issues/4343
Closes https://github.com/influxdata/ui/issues/4350
Closes https://github.com/influxdata/ui/issues/4353
Closes https://github.com/influxdata/ui/issues/4354
Closes https://github.com/influxdata/ui/issues/4355
This PR adds the Go language to the First mile in one go. :)
https://user-images.githubusercontent.com/18511823/162587968-9494352a-0f94-4745-b117-713fd811e036.mov
=> feat: Go for firstmile

src/flows/components/header/index.tsx, src/flows/context/flow.current.tsx
=> chore: central update changes

webpack.prod.ts
Part of https://github.com/influxdata/monitor-ci/issues/345
=> chore(monitor-ci-345): remove bundle analyzer from prod build

src/homepageExperience/components/steps/CreateToken.tsx
Closes #4392
Closes #4223 
- Removes the create token button.
- Creates the token on behalf of the user. It's named `onboarding-$wizardName-token-$date.now()`
- Copies the token into the code block automatically
- Updated initial text
> InfluxDB Cloud uses Tokens to authenticate API access. We've generated an all-access token for you.
https://user-images.githubusercontent.com/146112/163267638-30fb3917-eea7-48f1-9bb5-95383c4bb418.mov
=> feat(firstMile): create the all-access token for the user

src/homepageExperience/components/steps/CreateToken.tsx
Closes https://github.com/influxdata/ui/issues/4139
Figma design: 
Implementation
=> fix(firstMile): create token page update text to figma spec

src/homepageExperience/components/steps/go/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/go/InitalizeClient.tsx
Connects: https://github.com/influxdata/ui/issues/4406
=> fix: tweak code snippets for golang first mile

src/overlays/components/OverlayController.tsx, src/overlays/components/index.tsx, src/overlays/reducers/overlays.ts, src/pageLayout/containers/TreeNav.tsx, src/support/components/FeedbackQuestionsOverlay.tsx
Closes #3456 
Pr creates a Feedback Form Overlay with a simple form that has a text field for description, with a limit of 2500 characters
https://user-images.githubusercontent.com/66275100/163853454-1f3d5c29-9f36-41f4-a5ec-8824729de741.mov
=> (HelpBar): create Feedback & Questions overlay with text field

cypress/e2e/cloud/flows.test.ts, cypress/e2e/shared/checks.test.ts, cypress/e2e/shared/dashboardsIndex.test.ts, cypress/e2e/shared/dashboardsView.test.ts, cypress/e2e/shared/notificationRules.test.ts, cypress/e2e/shared/tasks.test.ts, cypress/e2e/shared/telegrafs.test.ts, src/utils/naming.test.ts, src/utils/naming.ts
Part of #4241 
- fixes the Cypress tests for verifying a clone's name
- updates the date format to be more standardized
=> test: fix tests for verifying clone's name

cypress/e2e/cloud/flows.test.ts
=> fix: fix broken test

src/flows/pipes/Table/index.ts
turns out there's some weirdness with just appending `|> limit` to things, specifically yields here. we have encountered similar issues, and the query experience project is working to more holistically remove the need for these types of patterns, so i'm seeing this as some duct tape until that work is done.
=> fix: insert before yield

src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/steps/Finish.tsx, src/homepageExperience/components/steps/python/ExecuteQuery.tsx, src/homepageExperience/components/steps/python/WriteData.tsx, src/homepageExperience/containers/GoWizard.tsx, src/homepageExperience/containers/HomepageContainer.tsx, src/homepageExperience/containers/NodejsWizard.tsx, src/homepageExperience/containers/PythonWizard.tsx
Closes https://github.com/influxdata/ui/issues/4454
Closes https://github.com/influxdata/ui/issues/4456
Closes https://github.com/influxdata/ui/issues/4459
Closes https://github.com/influxdata/ui/issues/4453
upgrade button is back :( 
"please select bucket" sentence to direct the user.
=> fix: first pass at firstmile bugs

src/homepageExperience/components/steps/nodejs/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/nodejs/ExecuteQuery.tsx, src/homepageExperience/components/steps/nodejs/InitalizeClient.tsx, src/homepageExperience/components/steps/nodejs/InstallDependencies.tsx, src/homepageExperience/components/steps/nodejs/WriteData.tsx
=> chore(firstMile): nodejs usability tweaks

src/homepageExperience/components/steps/Finish.tsx
Closes https://github.com/influxdata/ui/issues/4473
Closes #4251
=> fix(firstMile): show sample app for python only

src/homepageExperience/components/HomepageExperience.scss, src/homepageExperience/components/steps/go/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/go/InstallDependencies.tsx, src/homepageExperience/components/steps/go/WriteData.tsx, src/homepageExperience/components/steps/nodejs/InstallDependencies.tsx, src/homepageExperience/components/steps/python/InstallDependencies.tsx
Closes #4406
Closes #4477
Closes #4478
- Adds a code block for creating a go module
- Adds text explaining this assumes the user has go tools installed
- Changes `WriteData` spaces to tabs
- Removes redeclaration of `results` and `err` in `ExecuteAggregateQuery`
- Changes a couple inline styles to be classes
=> chore(firstMile): tweak golang wizard to be more intuitive

src/homepageExperience/containers/HomepageContainer.tsx, src/me/components/Resources.tsx
Closes https://github.com/influxdata/ui/issues/4493
=> fix: transparent background for docs panel

src/homepageExperience/components/steps/CreateToken.tsx, src/homepageExperience/components/steps/Tokens.tsx, src/homepageExperience/components/steps/go/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/go/ExecuteQuery.tsx, src/homepageExperience/components/steps/go/InitalizeClient.tsx, src/homepageExperience/components/steps/go/WriteData.tsx, src/homepageExperience/components/steps/nodejs/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/nodejs/ExecuteQuery.tsx, src/homepageExperience/components/steps/nodejs/InitalizeClient.tsx, src/homepageExperience/components/steps/nodejs/WriteData.tsx, src/homepageExperience/components/steps/python/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/python/ExecuteQuery.tsx, src/homepageExperience/components/steps/python/InitalizeClient.tsx, src/homepageExperience/components/steps/python/WriteData.tsx, src/homepageExperience/containers/GoWizard.tsx, src/homepageExperience/containers/NodejsWizard.tsx, src/homepageExperience/containers/PythonWizard.tsx, src/homepageExperience/utils.ts
Closes #4483
Closes #4486
- Tweaks the text explaining the process to read more grammatically correct
- Changes `const` variable declarations in the nodejs wizard to be `let`
=> chore(firstMile): update text in wizard to be easier to read

src/homepageExperience/components/FeedbackBar.tsx, src/homepageExperience/components/steps/Finish.tsx, src/homepageExperience/containers/GoWizard.tsx, src/homepageExperience/containers/NodejsWizard.tsx, src/homepageExperience/containers/PythonWizard.tsx
Closes https://github.com/influxdata/ui/issues/4488
https://user-images.githubusercontent.com/18511823/165370641-442974c4-69ea-4448-8d6b-b2d8b793196c.mov
=> fix(firstMile): remember the thumbs up feedback for the session

src/billing/components/PayAsYouGo/NotificationSettingsOverlay.tsx, src/checkout/NotificationSettingsForm.tsx, src/checkout/shared/FormInput.tsx
Part of idpe 14104
Minor changes to the checkout page
=> chore: change wording and add currency symbol

src/checkout/CheckoutForm.scss, src/checkout/CheckoutForm.tsx
Closes idpe 14140
Adds the banner for the $250 free credit offer
=> feat: add credit banner for experiment

src/writeData/subscriptions/components/JsonParsingForm.tsx, src/writeData/subscriptions/components/JsonPathInput.tsx, src/writeData/subscriptions/components/StringParsingForm.tsx, src/writeData/subscriptions/components/StringPatternInput.tsx
Closes https://github.com/influxdata/data-acquisition/issues/283
=> fix: save nested fields/arrays not to default context

src/billing/components/BillingPage.scss, src/billing/components/Free/Free.tsx, src/billing/components/Free/FreePanel.tsx, src/billing/components/Free/PAYGConversion.tsx
=> feat: add Credit 250 panel to Billing Page for experiment

src/dataExplorer/components/NewDataExplorer.tsx, src/dataExplorer/components/Results.tsx, src/dataExplorer/components/ResultsContext.tsx, src/dataExplorer/components/ResultsPane.tsx
turns on the ability to run queries in the experimental DE
=> feat: turn on queries for new DE

src/dataExplorer/components/DataExplorerPage.tsx
Closes #4508 
just changing a flag from a hidden feature
=> chore: renaming flag

src/billing/components/Free/PAYGConversion.tsx, src/checkout/CancelButton.tsx, src/cloud/components/AssetLimitAlert.tsx, src/cloud/components/AssetLimitOverlay.tsx, src/cloud/components/RateLimitAlert.tsx, src/cloud/components/RateLimitAlertContent.tsx, src/cloud/utils/experiments.ts, src/support/components/FreeAccountSupportOverlay.tsx, src/writeData/subscriptions/components/CreateSubscriptionPage.tsx, src/writeData/subscriptions/components/ParsingForm.tsx
=> feat: add eventing for Credit 250 experiment

cypress/e2e/cloud/subscriptions.test.ts
using `deleteSubscription` to remove duplication. use `createBasicLPSubscription` in some places.
=> chore: refactor subscription test

src/dataExplorer/components/ResultsPane.tsx
persist queries across navigation
=> feat: persist queries

src/alerting/components/AlertingIndex.tsx, src/dataExplorer/components/DataExplorerPage.tsx, src/me/components/GettingStarted.tsx, src/members/components/Members.tsx, src/organizations/containers/NoOrgsPage.tsx, src/pageLayout/containers/TreeNav.tsx, src/shared/components/RefreshingView.tsx, src/tasks/components/TaskRunsRow.tsx, src/tasks/components/TasksHeader.tsx, src/templates/components/CommunityTemplateOverlay.tsx, src/variables/components/RenameVariableForm.tsx, src/variables/components/UpdateVariableOverlay.tsx
Related to #4715. We have some hard coded values that we want to make use of global consts for in the event that product direction shift
=> chore: clean up some hard coded values

src/dataExplorer/components/FieldSelector.tsx, src/dataExplorer/components/FluxQueryBuilder.tsx, src/dataExplorer/components/Schema.scss, src/dataExplorer/components/TagSelector.tsx
Related #4510 
This PR updates the hover effect of the fields and tag values. 
https://user-images.githubusercontent.com/14298407/172699371-a88da57e-17ae-496a-af7f-db5ae92e2f22.mov
=> style: update hover effect to current design

package.json
Closes #4651
Updated ui `package.json` reflecting new giraffe version.
=> chore: update giraffe version in ui

src/support/components/ConfirmationOverlay.tsx
Connects https://github.com/influxdata/EAR/issues/3322
=> chore: tweak verbiage of sfdc contact support banner after feedback

src/pageLayout/containers/TreeNav.tsx
Pr removes duplicate Status Page from Help bar and sets it as a cloud feature
=> fix: status page is a cloud feature only

src/shared/components/DefaultErrorMessage.tsx
Co-authored by: Steven Solomon <steven-solomon@github.com>
Closes #4849
Copied from: https://github.com/influxdata/ui/pull/4850, which was from a community contributor.
=> chore(DefaultErrorMessage): open new ui issue link in new tab/window

src/shared/components/FilterList/MinimalistInjectionOption.scss
1 line font change, per design request.
=> fix: font for fluxBrowser

package.json
Update the SHA for the generated Quartz api client.
=> feat: update Quartz api client SHA

src/pageLayout/containers/TreeNav.tsx, src/support/components/FreeAccountSupportOverlay.tsx
=> fix: contact support font size and typo

src/authorizations/components/TokenRow.tsx
Closes #4843 
Changing the last used message to last modified.
=> fix(tokens): changed last used to last modified

src/visualization/utils/useVisDomainSettings.ts
Closes #4870 
Adds events for zooming in and restoring zoom
=> feat: add events for plot zooming

src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
helps https://github.com/influxdata/data-acquisition/issues/387
don't show section as complete on scroll.
=> fix: remove checkmarks

.github/pull_request_template.md
Closes #4867
Adds a PR template with a basic checklist
Let's get meta, here's what it'll look like:
=> docs: update PR template to include a checklist

src/dataExplorer/components/Results.tsx
Closes #4687 
adds the ability to search across rows of data in the results
=> feat: add search

src/flows/pipes/Table/view.scss, src/flows/pipes/Table/view.tsx, src/flows/pipes/Visualization/style.scss
since we added it to the simple table in the data explorer, lets keep the user expectations unified until we can't.
=> feat: normalize table experience

cypress/e2e/shared/fluxQueryBuilder.test.ts
Short term fix of #4907
This PR skips one flaky test for schema browser
=> test: skip flaky test for load more button

src/identity/components/GlobalHeader/OrgDropdown.tsx
Closes https://github.com/influxdata/ui/issues/5032
=> fix(multi-org): org dropdown icons

src/App.tsx, src/utils/vwo.ts
Closes #5012
Adds feature flagged code to make use of the [VWO](https://vwo.com/) A/B testing framework
=> feat(flagged): add code to call out to VWO a/b testing framework

src/homepageExperience/components/steps/SampleAppCard.tsx
PR updates Go boilerplate card to link to go-samples repo. 
The repo contains boilerplate app and several code snippets from the InfluxDB Cloud Go setup flow
=> chore(firstMile): Go boilerplate card links to go-samples repo

src/homepageExperience/components/steps/cli/InitializeClient.tsx, src/homepageExperience/components/steps/cli/InitializeTokenClient.tsx
Closes #4768
Adds the `Initialize Token` page to the CLI onboarding wizard. Screenshots and screen recording below. 
Note: this only adds the `Initialize Token` page and not the nav or other components, those will come in separate PRs.
https://user-images.githubusercontent.com/106361125/179580120-26030bc9-787d-4126-b567-fc91c610f6e4.mov
Updated Screenshots:
=> feat: add Initialize Client CLI onboarding page

cypress/e2e/cloud/helpBar.test.ts, cypress/e2e/shared/helpBar.test.ts, src/pageLayout/containers/TreeNav.tsx
=> chore: removing helpbar feat flag

src/dataExplorer/components/QueryTime.scss, src/dataExplorer/components/QueryTime.tsx, src/dataExplorer/components/Results.scss, src/dataExplorer/components/ResultsPane.tsx
=> feat: moving the errors up a bit

cypress/e2e/cloud/helpBar.test.ts, src/pageLayout/containers/TreeNav.tsx
=> chore: remove helpBarSfdcIntegration feat flag

src/dataExplorer/components/DataExplorerPage.tsx, src/dataExplorer/components/FluxQueryBuilder.scss, src/dataExplorer/components/FluxQueryBuilder.tsx, src/dataExplorer/components/ResultsPane.tsx, src/dataExplorer/context/fluxQueryBuilder.tsx, src/dataExplorer/context/persistance.tsx
Closes #5005 
Closes #5086 
adds a "new script" button to clear out the:
query text
download status
results
=> feat: clear script button

src/homepageExperience/components/steps/Finish.tsx
Closes [#5191](https://github.com/influxdata/ui/issues/5191)
Simple link change. 
=> fix(firstMile): update influxdb university link

cypress/e2e/cloud/helpBar.test.ts
One forgotten test for helpBarSfdc feat flag removal.
=> chore: removing help bar feature flag from one last test

src/pageLayout/constants/navigationHierarchy.ts, src/settings/components/LoadDataNavigation.tsx, src/writeData/subscriptions/components/CloudNativeSources.tsx, src/writeData/subscriptions/components/CloudSubscriptionContent.ts, src/writeData/subscriptions/components/CreateSubscriptionPage.tsx, src/writeData/subscriptions/components/DetailsSubscriptionPage.tsx, src/writeData/subscriptions/components/EmptySubscriptionState.tsx, src/writeData/subscriptions/components/SubscriptionsLanding.tsx
Closes https://github.com/influxdata/data-acquisition/issues/466
Changes "Cloud Native Subscriptions" to "Native Subscriptions". Changes "MQTT Subscriber" to "Native MQTT".
=> chore(sub): Change CNS name

src/shared/components/DynamicFunctionsList.tsx, src/timeMachine/components/FluxToolbar.scss
Closes #5141 
there aren't dupes, just information loss about the function's path between the function subsystem and the user. this adds a little header so the user doesn't get confused
=> feat: adding function path ui

src/homepageExperience/components/steps/Finish.tsx, src/homepageExperience/components/steps/Overview.tsx, src/homepageExperience/components/steps/Tokens.tsx
Subset of https://github.com/influxdata/ui/pull/5199.
=> chore: cleaning up linter warnings from three files within hompeageExperience

src/homepageExperience/components/steps/cli/WriteData.tsx
Closes #5387 
Simply updates code snippet to point to default folder for downloads 
=> fix(firstMileCLI): update csv code snippet text

src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/cli/ExecuteQuery.tsx
Closes #5399 
Fixes the queries on the windows flow so that they work and do not return a 400 error.
=> fix: update windows queries with escape chars

src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderDropdown.scss, src/identity/components/GlobalHeader/GlobalHeaderDropdown/index.tsx
Closes #5307 
https://user-images.githubusercontent.com/18511823/184717098-e9f06c19-f89f-47d3-bb08-911a49247ca0.mov
=> fix(multi-org): disable hover effect in switch button

src/shared/contexts/query.tsx
Closes #5087 
the original issue was pretty sparse with intent, so idk if this hits the mark, but from offline communication it seems like there are issues with determining the range used for calculating windowPeriod and we want to short circuit that and just use the time range passed into the query? i tried to encapsulate that with the least amount of spaghetti before we commit to this path, as we gauge and weigh the impact of it on our users.
=> feat: toggle window period calculation

cypress/e2e/shared/labels.test.ts
Closes https://github.com/influxdata/ui/issues/5473
=> test(labels): skip failing labels tests temporarily until labels service is back

src/identity/components/GlobalHeader/IdentityUserAvatar.tsx, src/identity/components/GlobalHeader/UserPopoverStyles.scss
Closes [#5444](https://github.com/influxdata/ui/issues/5444)
https://user-images.githubusercontent.com/18511823/186028648-baae61df-a100-44d8-925b-00faf47f4cc1.mov
Still works normally: 
=> feat(multi-org): Show user icon when FirstName and LastName are absent 

package.json, yarn.lock
Closes #5507
Upgrades Luxon to the latest version
=> chore(dependencies): upgrade luxon to latest version

package.json, src/tasks/actions/thunks.ts, src/variables/actions/thunks.ts
Added subscription route updates in openapi. Update package.json file with the latest SHA.
Related Issue: https://github.com/influxdata/data-acquisition/issues/441
=> chore: update openapi SHA for subscription updates

src/dataExplorer/components/Schema.tsx
Part of #5501 
We forgot to feature flag the toggle.
=> fix: composition toggle should be feature flagged

src/dataExplorer/shared/utils.ts
As part of the save load epic, we found that we needed more than one component listening to the session storage at a certain key. when we tried it, updates weren't happening outside of the individual `[state, setState]` pairs. this adds a custom event to keep them in sync across their specified keys.
=> fix: keep session stores in sync

src/homepageExperience/components/steps/cli/InstallDependencies.tsx
Closes https://github.com/influxdata/ui/issues/5437
Minor adjustments to the windows CLI flow based on user feedback from @wojciechka 
=> chore(windows-firstMile): add context to the windows flow

src/visualization/components/internal/AdaptiveZoomOption.tsx, src/visualization/types/Graph/options.tsx, src/visualization/types/Graph/view.tsx, src/visualization/utils/useVisDomainSettings.ts
Closes #4988 
Adds the view option for the Adaptive Zoom feature.
https://user-images.githubusercontent.com/10736577/186544602-9245954e-75f6-4713-98b8-5a562a4b0c5b.mp4
=> feat: adds the adaptive zoom view option

package.json, yarn.lock
PR has the patch described here:
https://github.com/influxdata/flux-lsp/pull/572
=> build(lsp): upgrade flux-lsp to 0.8.30

cypress/e2e/cloud/subscriptions.test.ts, src/types/subscriptions.ts, src/writeData/subscriptions/components/BrokerFormContent.tsx, src/writeData/subscriptions/components/CertificateInput.tsx, src/writeData/subscriptions/context/subscription.create.tsx, src/writeData/subscriptions/context/subscription.update.tsx, src/writeData/subscriptions/utils/form.ts
Closes # https://github.com/influxdata/data-acquisition/issues/489
Update per team experience session.
=> chore: add DEFAULT_PORT to test and port placeholder

src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx, src/homepageExperience/components/steps/cli/ExecuteQuery.tsx
Connects https://github.com/influxdata/ui/issues/5392
Removes the `--raw` flag so the results are prettier.
=> fix(firstMile/CLI): better formatted output instead of a raw one

cypress/e2e/shared/editor.test.ts
Conflicting merges within 2 minutes of each other. Name got change, right as I added a test using the name.
=> fix: conflicting merges, changed the name. Update test.

src/languageSupport/languages/flux/lsp/connection.ts, src/languageSupport/languages/flux/lsp/utils.ts
Fulfilling promises made in these PRs:
* to @asalem1 -- https://github.com/influxdata/ui/pull/5592
* to @rockstar -- https://github.com/influxdata/ui/pull/5541
Because we have two conventions for denoting tech debt and future work, tried to balance/incorporate both. FYI.
=> chore: cleanup names and comments

src/flows/pipes/RawFluxEditor/view.tsx
#5697 commit failed linter test. Pr removes an unused import and runs prettier
=> chore: remove unused import

package.json, yarn.lock
Upgrade papaparse to latest version `5.3.2`
=> chore: update papaparse to 5.3.2

package.json, yarn.lock
Upgrade cross-env to the latest one. 
Type: `devDependencies`
=> chore: upgrade cross-env to the latest

src/accounts/context/userAccount.tsx, src/me/actions/thunks/index.ts
Closes #5802 
Clean up `avatarWidgetMultiAccountInfo` feature flag code blocks as they aren't needed anymore.
=> chore: remove avatarWidgetMultiAccountInfo feature flag code

src/languageSupport/languages/flux/lsp/monaco.flux.lsp.ts
Closes #5780 
For architecture design decisions, want more metrics on editor-Lsp usage.
=> chore(5780): track usage of fallback worker

package.json, yarn.lock
Upgrades `normalizr` to the latest (3.6.1)
=> chore: upgrade normalizr to latest

package.json, yarn.lock
Upgrade chroma-js and it's types to latest
=> chore: Upgrade chroma-js and it's types to latest

src/homepageExperience/components/steps/arduino/InitializeClient.tsx
Closes https://github.com/influxdata/ui/issues/5675
=> fix(firstMile/arduino): font size for "Note"

package.json, yarn.lock
=> chore: upgrade auth0-js to latest

package.json, yarn.lock
=> chore: update jest-junit

src/writeData/components/WriteDataHelperBuckets.tsx
Closes [#5674](https://github.com/influxdata/ui/issues/5674)
https://user-images.githubusercontent.com/18511823/191106215-2807cd9f-2ab2-4a7f-a881-c3c162aae049.mov
=> fix(firstMile/arduino): scroll to selected bucket

src/homepageExperience/components/DataListening.tsx
Closes [#5705](https://github.com/influxdata/ui/issues/5705)
https://user-images.githubusercontent.com/18511823/191131853-7cc89d6c-b01d-43f0-adec-c34d8405f883.mov
=> fix(firstMile): fixing listen data component to listen on component mount

package.json, yarn.lock
=> chore: upgrade html2canvas

package.json, yarn.lock
=> chore: upgrade intersection-observer polyfill

src/dataExplorer/components/SaveAsScript.tsx
Closes #5837
updates the copy in the header of the modal to display if script is new or changed
=> fix: update save script text

cypress/e2e/shared/fluxQueryBuilder.test.ts, src/dataExplorer/components/DataExplorerPage.tsx
Closes #5807 
this kicks people out all the way if the newDataExplorer flag is off
=> fix: kick out users if new DE flag is off

package.json, yarn.lock
=> chore: upgrade amplitude

cypress/e2e/cloud/subscriptions.test.ts
closes https://github.com/influxdata/data-acquisition/issues/550
=> fix: provide legit broker host and port for nifi connection check

cypress/e2e/shared/influxCLI.test.ts, src/homepageExperience/containers/HomepageContainer.tsx, src/shared/containers/SetOrg.tsx
Part of #4779 
Removes that flag from the UI.
Next after deleting here, i will delete it from idpe, and then config cat. 
=> chore(firstMile/CLI): remove onboardCLI feature flag

src/dashboards/components/VEO.scss, src/dashboards/components/VEOHeader.tsx
Closes https://github.com/influxdata/ui/issues/5902
https://user-images.githubusercontent.com/18511823/192399956-d8a93e53-f927-4f96-930a-adc05d5be54c.mov
Added it to the same place that the Data Explorer has it at. 
=> feat(VEOHeader): Add Timezone switcher to the header

src/shared/containers/GetOrganizations.tsx
This reverts commit b838e0729387157d7b0de533ca86d5fe9c305c93, which would have, had it hit prod, caused a re-render loop for free users on the account/billing page.
https://user-images.githubusercontent.com/91283923/192641591-851ae4da-645a-4b78-848d-89430a554d44.mov
https://user-images.githubusercontent.com/91283923/192642741-fe150057-7986-47a3-a063-3d697e5d0f8f.mov
=> revert: commit removing quartzMe references from getOrganizations

src/writeData/clients/Dart/description.md, src/writeData/clients/Java/description.md, src/writeData/clients/Kotlin/description.md, src/writeData/clients/PHP/description.md, src/writeData/clients/Scala/description.md, src/writeData/clients/Swift/description.md
Related to https://github.com/influxdata/influxdb-client-php/pull/129
1. Added required dependency to http client for `php` client
2. Update client versions.
=> chore(client_libs): add required dependency to http client [php]

src/homepageExperience/components/HomepageIcons.tsx, src/homepageExperience/containers/HomepageContainer.tsx
Closes #5937
https://user-images.githubusercontent.com/18511823/193656987-b4e2de4c-1e24-4331-9600-1f301e668a9a.mov
=> feat(firstMile): Add MQTT create link to homepage

src/writeData/components/FileUploadSection.tsx, src/writeData/constants/contentFileUploads.ts, src/writeData/graphics/CLIIcon.svg
Closes [#5963](https://github.com/influxdata/ui/issues/5963)
https://user-images.githubusercontent.com/18511823/193681619-c00cee30-2478-4818-8a2c-bb8c19615f1d.mov
=> fix(writeData): fixes some text and icons to match product requirements

cypress/e2e/shared/arduino.test.ts, src/homepageExperience/containers/HomepageContainer.tsx, src/shared/containers/SetOrg.tsx
Closes [#5225](https://github.com/influxdata/ui/issues/5225)
=> chore(firstMile): remove onboardArduino flag

src/visualization/types/Band/options.tsx, src/visualization/types/Band/view.tsx
Closes #5776 
Adds the adaptive zoom feature to Band graphs:
https://user-images.githubusercontent.com/10736577/192910981-0eeb8a3e-9601-44d7-8081-2906d5d090bf.mp4
=> feat: add adaptive zoom to Band

src/me/components/DocSearchWidget.tsx
=> chore: add InfluxDB University to Useful Links

src/shared/components/cells/DashboardCells.tsx
Closes #6001
Cleans up the cell rendering and cell layout code to be less redundant, simpler, and rely on fewer dependencies.
=> chore(dashboards): clean up cell rendering and layout code

cypress/e2e/shared/simpleTable.test.ts, package.json, yarn.lock
Closes #6004  
BEFORE - notice the last row on page 2 overlaps with the edge of the table and horizontal scrollbar:
https://user-images.githubusercontent.com/10736577/194380028-1b0be211-c84f-4145-a064-2c0c4cc4fa5d.mp4
AFTER - fixed, no overlapping:
https://user-images.githubusercontent.com/10736577/194380106-57f707af-8cb7-4e40-b99a-84c98f95c8f7.mp4
=> fix: update Giraffe to fix Simple Table with multiple table headers

src/writeData/subscriptions/components/JsonParsingForm.tsx
Closes https://github.com/influxdata/data-acquisition/issues/536
Updates Json Parsing docs link to https://docs.influxdata.com/influxdb/cloud/reference/json-parsing/
=> chore(sub): update json parsing docs link

src/writeData/clients/CSharp/executeFull.example, src/writeData/clients/CSharp/initialize.example
Closes [#381](https://github.com/influxdata/influxdb-client-csharp/issues/381)
Updated InfluxDB UI to use initializer for InfluxDBClient in csharp-client.
=> feat: Initialize C# client without InfluxDBClientFactory

src/shared/components/cells/Cell.tsx, src/visualization/types/Scatter/options.tsx, src/visualization/types/Scatter/view.tsx
Closes #5777 
Adds the adaptive zoom feature to Scatter plots.
https://user-images.githubusercontent.com/10736577/196310090-7a27749c-fc62-4987-9d68-49af99219c47.mp4
=> feat: add adaptive zoom to Scatter

package.json, yarn.lock
upgrade @types/lodash to latest
=> chore: upgrade @types/lodash to latest

yarn.lock
Follow-up to https://github.com/influxdata/ui/pull/6150
=> chore: commit the lodash upgrade diff

src/writeData/components/FileUploadSection.tsx
Closes #5981  
use the InfluxDB CLI wizard at Load Data > Sources
https://user-images.githubusercontent.com/10736577/197653840-ce605696-ede7-424f-92f0-eb2900cb113a.mp4
=> feat: use InfluxDB CLI wizard on Load Data page

package.json, yarn.lock
Updates @typescript-eslint/parser to latest
=> chore: upgrade @typescript-eslint/parser to latest

src/Setup.tsx, src/index.tsx
Closes https://github.com/influxdata/ui/issues/6172
Moves the fetching up to the Setup layer. 
Change is potentially risky since it's untestable in dev env. If something goes wrong, we need to revert this PR and it should be back to normal. 
=> fix: Fetch FFs on login page

src/writeData/subscriptions/components/BrokerFormContent.tsx, src/writeData/subscriptions/utils/form.ts
Helps https://github.com/influxdata/data-acquisition/issues/565
Removes some subscription feature flag usage.
- subscriptionsClientId
- subscriptionsSSLSupport
Easier to review with `?w=1` : https://github.com/influxdata/ui/pull/6178/files?w=1
=> chore(sub): remove a couple feature flags

src/writeData/clients/Arduino/index.ts, src/writeData/clients/CSharp/index.ts, src/writeData/clients/Dart/index.ts, src/writeData/clients/Go/index.ts, src/writeData/clients/Java/index.ts, src/writeData/clients/Javascript/index.ts, src/writeData/clients/Kotlin/index.ts, src/writeData/clients/PHP/index.ts, src/writeData/clients/Python/index.ts, src/writeData/clients/R/index.ts, src/writeData/clients/Ruby/index.ts, src/writeData/clients/Scala/index.ts, src/writeData/clients/Swift/index.ts, src/writeData/index.ts
Part of #5819  
Removes `require.context` from `src/writeData`
=> refactor: remove dynamic imports from writeData

src/identity/apis/org.ts
Closes #6357 
Helps with #5477 
Add delete-org endpoint to UI api layer.
=> chore: add delete org to api layer

package.json, yarn.lock
=> chore: upgrade @babel/core to 7.20.5

cypress/e2e/shared/fluxQueryBuilder.test.ts, package.json, src/dataExplorer/components/SchemaBrowserHeading.tsx, src/dataExplorer/context/fluxQueryBuilder.tsx, src/dataExplorer/context/persistance.tsx, src/languageSupport/languages/flux/lsp/connection.ts, src/languageSupport/languages/flux/lsp/monaco.flux.lsp.ts, src/languageSupport/languages/flux/lsp/types/executeCommand.ts, src/languageSupport/languages/flux/lsp/types/index.ts, src/languageSupport/languages/flux/lsp/types/methods.ts, src/languageSupport/languages/flux/lsp/types/showMessage.ts, src/languageSupport/languages/flux/lsp/utils.ts, src/languageSupport/languages/flux/lsp/worker/flux.worker.ts, src/shared/components/FluxMonacoEditor.tsx, src/shared/components/MonacoEditor.scss, src/shared/contexts/editor/index.tsx, src/shared/copy/notifications/categories/dashboard.ts, yarn.lock
This is a staging branch, where a chain of PRs (required for the full atomic unit of feature release) are together. Ready for final review, prior to merge.
Previous reviews are seen here:
* [1st PR](https://github.com/influxdata/ui/pull/6344)
* [2nd PR](https://github.com/influxdata/ui/pull/6374)
* [3rd PR](https://github.com/influxdata/ui/pull/6397)
=> chore: merge staging branch after final approval/review.

src/languageSupport/languages/flux/lsp/connection.ts
Follow up improvements to just released yieldless composition.
1. if `shouldRemoveDefaultMsg`, follow new path
* => `_removeDefaultAndUpdateLsp()`
2. attach event listener, that triggers the LSP executeCommand after the model reset is detected.
* debugging locally, still needed a magic number delay --> but smaller.
3. remove event handler after a period of time.
* So is not unintentionally triggered again, with an older toAdd/toRemove payload.
**Result: cut the magic number time significantly.**
* Also cleaned up (added switch stmt) to make it clear which path is taken.
* tested locally with the boosted composition test coverage
* but still pushing the expanded tests in another PR --> so CI runs them 20x. Prevent flaky.
=> fix: reduce delay caused by resetting default text

cypress/e2e/cloud/billing.test.ts, cypress/e2e/cloud/globalHeader.test.ts, cypress/index.d.ts, cypress/support/commands.ts
Fix tests for running on iox e2es.
These changes are needed since there was updates to the billing and global header which are tsm-specific.
=> fix: cloud tests for iox behavior

src/shared/components/FilterList/InjectionOption.tsx
Followup request on [a merged PR](https://github.com/influxdata/ui/pull/6500#discussion_r1073681323).
=> chore: remove old, unnecessary comment

cypress/e2e/shared/arduino.test.ts, cypress/e2e/shared/influxCLI.test.ts, src/homepageExperience/components/steps/Finish.tsx, src/homepageExperience/components/steps/Overview.tsx, src/homepageExperience/components/steps/python/ExecuteQuerySql.tsx, src/homepageExperience/components/steps/python/InitializeClient.tsx, src/homepageExperience/components/steps/python/InstallDependenciesSql.tsx, src/homepageExperience/components/steps/python/WriteData.tsx, src/homepageExperience/components/steps/python/WriteDataSql.tsx, src/homepageExperience/containers/HomepageContainer.tsx, src/homepageExperience/containers/PythonWizard.tsx, src/homepageExperience/utils.ts
This PR adds a new python onboarding experience for IOx users so they can query with SQL from the Python client library. It introduces the new SQL extra for the client library, provides more meaningful write instructions and mock data, and demonstrates querying with SQL and sending to a pandas dataframe.
These changes are behind the `ioxOnboarding` feature flag.
=> feat(ui): Add Python SQL onboarding for IOx

cypress/e2e/shared/helpBar.test.ts, src/homepageExperience/components/steps/Finish.tsx, src/pageLayout/containers/MainNavigation.tsx
Removes InfluxDB University links for IOx organizations throughout the UI until the content there is updated for IOx.
=> chore(ui): remove university links for iox

src/me/components/Resources.tsx
Replace the link in "Learn more" with one to the FAQ.
=> fix(ui): change learn more link

src/homepageExperience/containers/HomepageContainer.tsx
Temporarily removes Golang link from the home page for IOx till that onboarding is updated for SQL.
=> chore(ui): hide go onboarding link

cypress/e2e/shared/nav.test.ts
Part of #6562 
Working on TSM and iox.
=> fix(6562): make nav e2e test compatible with IOx

cypress/e2e/shared/adaptiveZoom.test.ts
=> fix(6562): adaptiveZoom test needs the dashboards featureFlag in CI

src/homepageExperience/components/steps/go/ExecuteQuerySql.tsx, src/homepageExperience/components/steps/go/InstallDependenciesSql.tsx, src/homepageExperience/components/steps/go/WriteDataSql.tsx, src/homepageExperience/containers/GoWizard.tsx, src/homepageExperience/containers/HomepageContainer.scss, src/homepageExperience/containers/HomepageContainer.tsx, src/homepageExperience/utils.ts, src/writeData/components/ClientLibrarySectionSql.tsx
This PR adds Golang instructions for querying with flight-sql.
=> feat(ui): go flightsql onboarding

src/shared/components/dateRangePicker/NewDatePicker.tsx
Closes https://github.com/influxdata/EAR/issues/3921
* existing code was creating a Date type, and under certain circumstances was over-writing this date type with a string type. Then passing to state.
* existing code was doing manual math to adjust dates, and did not properly handle wrap cases (e.g. last day of month). All of this shenanigans was to avoid using a datetime lib to format a date.
* existing code had wrong when it was a base-0 integer for a date part, versus a base 1 (e.g. human reading). Month is base 0, date is base 1 (24th of month is 24th of month).
* this last one produced the actual bug reported in the EAR. 
If you double click on a date, it sets the start/end of the same day. Just at beginning and end hours of the day. …
=> fix(3921): new DatePicker should use proper typing, and not do manual date math.

cypress/e2e/shared/scriptQueryBuilder.sql.test.ts, src/dataExplorer/components/Results.tsx, src/dataExplorer/components/SqlViewOptions.tsx, src/dataExplorer/context/results/childResults.tsx, src/dataExplorer/context/resultsView.tsx, src/shared/components/DropdownList.tsx
=> feat(6587): SQL visualization e2es

src/homepageExperience/components/OptionAccordion/OptionAccordion.scss, src/homepageExperience/components/OptionAccordion/OptionAccordion.tsx, src/homepageExperience/components/OptionAccordion/OptionAccordionElement.tsx, src/homepageExperience/components/OptionAccordion/VisualizeAccordion.tsx, src/me/components/CloudWidgets.tsx
Adds an announcement for the Grafana Flight SQL plugin and highlights the option in the resource list.
=> feat(ui): add grafana announcement

src/me/components/AnnouncementBlock.tsx, src/me/components/CloudWidgets.tsx, src/me/components/CurrentAnnouncement.tsx
This PR:
- Adds a new announcement for InfluxDB Clustered
- Abstracts the announcements into its own component that handles displaying announcements based on the target date
- Adds a missing event capture to the announcement titles.
=> feat(ui): add announcement date handler component

src/me/components/CurrentAnnouncement.tsx
This PR makes updates to the text, time, and URL of the clustered announcement.
=> chore(ui): update text, time, and URL

src/homepageExperience/components/steps/csharp/InitializeClientSql.tsx, src/homepageExperience/components/steps/go/ExecuteQuerySql.tsx, src/homepageExperience/components/steps/go/WriteDataSql.tsx, src/homepageExperience/components/steps/java/ExecuteQuerySql.tsx, src/homepageExperience/components/steps/java/InitializeClientSql.tsx, src/homepageExperience/components/steps/java/InstallDependenciesSql.tsx, src/homepageExperience/components/steps/java/WriteDataSql.tsx, src/homepageExperience/containers/GoWizard.tsx
Updated code examples for v3 clients to new unified API. For more info see changes in releases notes:
C# - 0.2.0 - https://github.com/influxcommunity/influxdb3-csharp/blob/main/CHANGELOG.md#020-2023-08-11
Java/JVM - 0.2.0 - https://github.com/InfluxCommunity/influxdb3-java/blob/main/CHANGELOG.md#020-2023-08-11
GoLang - 0.2.0 - https://github.com/InfluxCommunity/influxdb3-go/blob/main/CHANGELOG.md#020-2023-08-11
=> docs(client_libs): update code examples for v3 client to new unified API

src/homepageExperience/components/steps/csharp/WriteDataSql.tsx, src/homepageExperience/components/steps/nodejs/WriteDataSql.tsx
Updated code examples for v3 clients to new unified `Point` API. For more info see changes in releases notes:
- C# - 0.3.0 - https://github.com/influxcommunity/influxdb3-csharp/blob/main/CHANGELOG.md#030-2023-10-02
- Js/NodeJS - 0.3.0 - https://github.com/influxcommunity/influxdb3-js/blob/main/CHANGELOG.md#030-2023-10-02
=> docs(client_libs): update code examples for v3 client to new `Point` API

package.json, yarn.lock
Closes https://github.com/influxdata/idpe/issues/19075
=> chore: misc updates to address dependabot alerts

package.json, yarn.lock
Helps with https://github.com/influxdata/edge/issues/808
This is https://github.com/influxdata/ui/pull/7023 for release/OSS
=> chore: misc updates to address dependabot alerts (release/OSS)

src/buckets/components/createBucketForm/UpdateBucketOverlay.tsx, src/flows/components/header/MenuButton.tsx, src/flows/components/header/index.tsx, src/flows/context/api.tsx, src/flows/context/flow.current.tsx, src/shared/copy/notifications/categories/notebooks.ts
This is a rebase of @philjb 's OSS cherry-picks in https://github.com/influxdata/ui/pull/7052 after rebasing in recent changes/resolutions. The original branch is maintained for comparison.
=> feat(ui): port #7016, #7021, #7008 to open source release branch
