influxdata/ui

src/shared/constants/index.ts
src/shared/copy/notifications.ts
src/templates/components/CommunityTemplateImportOverlay.tsx
src/templates/containers/CommunityTemplatesIndex.tsx

Closes https://github.com/influxdata/influxdb/issues/19051
- If the template fails installation, it stops installation, rather than attempting to rename the uninstalled template and showing two weird error messages
- Installation messages are shown in the notification indefinitely, and must be closed by the user or navigated away from the page.
- Added a small bit: after a template is successfully installed, it clears the input

fix(community-templates): cleanup how we handle installation errors

---

src/shared/components/ExportOverlay.tsx
src/templates/actions/thunks.ts

Connects https://github.com/influxdata/influxdb/issues/19447
First part of the above ticket:
- Removes Save as Template button from the export overlay
Related to: https://github.com/influxdata/influxdb/pull/19300

fix: remove export as template option from export overlay

---

src/shared/components/ScatterPlot.tsx
src/shared/components/ViewSwitcher.tsx
src/timeMachine/components/view_options/ScatterOptions.tsx

https://github.com/influxdata/influxdb/issues/18981
was a bit unsure about the acceptance criteria for this one, but it seems like we wanted to add the ability to manually set the domain on the x axis for histograms and scatter plots. it exists on histograms, so i just added it onto the scatter plots. also went through and fixed whatever was making the giant auto domain range as well. Problem seemed rooted in mimicking the XYPlot interface to giraffe and assuming that time was significant on the scatter plot, when it's not (more of an explicit declaration of the requirement, whereas XY is more implicit)

feat: add x axis domain manipulation to scatter plot

---

cypress/e2e/communityTemplates.test.ts
src/templates/components/CommunityTemplatesResourceSummary.tsx

Quick fix, there's no ticket associated with this. Changes where the telegraf link goes to in the installed templates list.

feat(community-templates): telegraf now links to setup instructions

---

src/dashboards/actions/thunks.ts

Closes #53 
Variable hydration is currently only context aware when the view has been set. If no view has been set, then all of the variables will be hydrated. 
This issue stems from the fact that the way we are limiting variable hydration is dependent upon the view. Since this current implementation depends on the concept of a view to limit variable hydration, simply changing the order with which things are dispatched (i.e. first the view, then the variables) allows the dashboard to limit variable hydration based on its current implementation. 
Below is an example of three different dashboards:
The first example shows 2 queries being issued (1 for the cell, 1 for the buckets query variable)
The second example shows 3 queries being issued (1 for each cell, none for the query variables …

fix(dashboard-var-hydration): limiting variable hydration of the dashboard to those within the view

---

cypress/e2e/communityTemplates.test.ts
src/templates/actions/thunks.ts

And add the proper url for screenshots. Which i am assuming any photos in setup instructions are named screenshot, we might need to make a change to this code. This means any text below setup instructions in rendered, all other code discarded.
Closes #19502

fix: change to setup instructions rendering only

---

src/dataLoaders/components/BucketsDropdown.tsx
src/templates/components/CommunityTemplateEnvReferences.tsx
src/templates/components/CommunityTemplateImportOverlay.tsx
src/templates/components/CommunityTemplatesInstalledList.tsx

- Adds a width, style property to the bucket dropdown
- When installing a template or removing a template, re-fetch buckets.
- This might cause performance issues on installs with lots of buckets

chore: template parameterization bucket follow up

---

src/templates/components/CommunityTemplateResourceContent.tsx

>i don’t see “Notification Endpoints” displayed in the UI when i try to import a template through the UI. The docker template has one: 
https://influxdata.slack.com/archives/C018NGHFHSM/p1600402190001100
test with [this template](https://github.com/influxdata/community-templates/blob/d4cf430d51ae6d3dfc95ff8faa7c1247ba2a2c64/docker/docker.yml)

feat(community-templates): add notification endpoint description on install

---

.circleci/config.yml
cypress/e2e/tasks.test.ts
cypress/e2e/telegrafs.test.ts

turns out "waiting for the cache to expire" would take months. SO. doing it explicitly here. I think the "build ingress on every test" if more of a hold over to the last time we had to bump the cache, and just forgot about it, but the next coarse of action after this would be to remove the debug bump as well.... and maybe just creating this PR will fix it

chore: bump the docker cache

---

src/templates/components/CommunityTemplateResourceContent.tsx

minor bug: the check mark indicating the resource shouldn't be installed would always render, even though the underlying behavior was correct.

fix(community-templates): don't render unselected task checkmarks

---

src/checks/components/CheckHistory.tsx
src/cloud/components/AssetLimitAlert.tsx
src/cloud/components/AssetLimitOverlay.tsx
src/cloud/components/RateLimitAlert.tsx
src/cloud/components/RateLimitAlertContent.tsx
src/organizations/components/OrgHeader.tsx
src/settings/components/LoadDataHeader.tsx
src/shared/components/CloudUpgradeNavBanner.tsx
src/tasks/components/TaskHeader.tsx
src/tasks/components/TaskRunsPage.tsx

- Changes the messaging for free and PAYG series cardinality limit alerts
- Adds an option for PAYG users to schedule a call in Calendly to resolve series cardinality rate limit breaches
- Adds class names for GA tracking which upgrade CTA buttons were clicked
**FREE**
**PAYG**

feat(ui): Add GA tracking and calendly contact

---

cypress/e2e/nav.test.ts
cypress/e2e/telegrafs.test.ts
cypress/support/commands.ts
src/index.tsx
src/shared/components/NotFound.tsx

Closes influxdata/influxdb#19283
When navigating to a non-existing route a blank page displayed.  
Remove the top level `react-router` `<Switch/>` component that returns the first matching component.   In this case that would be `<Setup/>`.  Didn't think it would be this easy but seems to not interfere with `/onboarding` and works with root and nested routes.

fix: 404 not rendering

---

src/shared/components/BandPlot.tsx
src/shared/constants/index.ts
src/timeMachine/components/view_options/BandOptions.tsx
src/timeMachine/selectors/index.ts

Part of idpe #8337
- save 'mainColumn' properly so that Dashboards can render something in the cell for Band Charts.
- require the user to explicitly set or remove 'upperColumn' and 'lowerColumn'
- no automatic removal of upper and lower columns from Band Options even when they are not included in the response
- Query Builder mode: user selects from dropdowns
- Script Editor mode: user types into text input field

fix: save 'mainColumn' properly and set 'upperColumn' and 'lowerColumn' explicitly

---

src/shared/components/BandPlot.tsx
src/shared/components/HeatmapPlot.tsx
src/shared/components/HistogramPlot.tsx
src/shared/components/MosaicPlot.tsx
src/shared/components/ScatterPlot.tsx
src/shared/components/XYPlot.tsx
src/shared/utils/useLegendOrientation.ts

The initial value from the backend api comes back as 0 for opacity, which doesn't change in props, causing legends to appear invisible. Prevent this by ensuring minimum opacity is always used.

fix: prevent invisible tooltips for the zero value of legendOpacity from the api

---

src/external/monaco.flux.server.ts
src/shared/components/TimeSeries.tsx
src/shared/parsing/flux/response.ts
src/shared/utils/fromFlux.legacy.ts
src/timeMachine/apis/queryBuilder.ts
src/variables/utils/ValueFetcher.ts

Closes #72 
There are a bunch of parsers, which means maintaining a bunch of code. This PR aims to unify the parsers by replacing the usage of `parseResponse` with `fromFlux`
Swapped the places where `parseResponse` was being used with a feature flagged `fromFlux`. The feature flag PR is up in IDPE and the feature flag has been set in configCat

feat(fromFlux): swaps out parseResponse for fromFlux in most places in the UI

---

src/notebooks/pipes/Data/SearchBar.tsx
src/notebooks/pipes/Data/Selectors.tsx
src/notebooks/pipes/Data/index.ts
src/notebooks/pipes/Data/view.tsx

there was a change added that tried to remove a scroll trap within the flows interface when using the metrics selector. it... introduced it's own set of issues, so this PR reverts those changes

fix: removing focus logic to help with usability a bit

---

src/timeMachine/components/view_options/LineOptions.tsx
src/views/helpers/index.ts

Closes https://github.com/influxdata/influxdb/issues/19178
Previously, hoverDimension as a variable was defaulted to have 'auto as a value. But this doesn't actually set the redux state with the correct default hoverDimension. Default view properties should be set in **src/views/helpers/index.ts** which will reflect in redux state.

fix: set default hoverDimension for Line Options to 'auto'

---

src/external/monaco.flux.server.ts
src/index.tsx
src/mockState.tsx
src/shared/utils/featureFlag.ts
src/shared/utils/pageTitles.test.ts
src/shared/utils/pageTitles.ts
src/store/configureStore.test.ts
src/store/configureStore.ts

Closes #124
* Previously, `index.tsx` exported `store` after configuring it. Modules would then import `store` from `index.tsx.`
* I just want to reiterate here: modules **included the entry point of the app which automatically runs and includes the module that included `index.tsx` as part of the code that runs**
* Other modules would import `configureStore` and re-configure the store, which overwrote the store willy nilly.
* Now: `store` is a true [singleton.](https://en.wikipedia.org/wiki/Singleton_pattern) It's created exactly once, and the instance of the created `store` is returned via an exported function. Any place that imported `store` from `index.tsx` or the function `configureStore` now imports the `getStore` function.
* This also includes a change to `pageTitles` and a test for …

fix(redux): export store singleton, rather than configureStore factory function

---

src/dashboards/actions/notes.ts
src/dashboards/actions/thunks.ts
src/dashboards/components/NoteEditorOverlay.tsx

Closes #136 
Moves the side effects of the notes action creator to the dashboard thunk. This resolves the circular dependencies between configureStore and this module.
- `configureStore` builds the empty store based off the initial state the reducers describe
- to do this, `configureStore` imports all the reducers.
- reducers pull in the action creator functions and the name of the actions
- if the actions have outside dependencies (say on `event`, which indirectly depends on `featureFlag`), those are imported and executed before `configureStore` is executed
- by moving the side effects (and more importantly, their dependencies) outside the dependency chain of reducers and action creators,  circular dependencies that flow back to `configureStore` are removed.
```sh
madge --webpack-config …
```

refactor(notes): remove side effects from notes action creator

---

src/alerting/actions/alertBuilder.ts
src/alerting/actions/thunks.ts
src/checks/components/CheckMetaCard.tsx

closes #139 
Moves the single action with side effects of alertBuilder's action creator into a newly minted thunk.
```sh
madge --webpack-config webpack.common.ts src/store/configureStore.ts --image graph.svg --circular
```
- `configureStore` builds the empty store based off the initial state the reducers describe
- to do this, `configureStore` imports all the reducers.
- reducers pull in the action creator functions and the name of the actions
- if the actions have outside dependencies (say on `event`, which indirectly depends on `featureFlag`), those are imported and executed before `configureStore` is executed
- by moving the side effects (and more importantly, their dependencies) outside the dependency chain of reducers and action creators,  circular dependencies that flow back to …

refactor(redux): remove side effects from alertBuilder actions

---

src/shared/actions/me.ts
src/shared/actions/meThunks.ts
src/shared/containers/GetMe.tsx

closes #140
Makes `me` action creators pure by moving the single function with side effects into a thunk
```sh
madge --webpack-config webpack.common.ts src/store/configureStore.ts --image graph.svg --circular
```
- `configureStore` builds the empty store based off the initial state the reducers describe
- to do this, `configureStore` imports all the reducers.
- reducers pull in the action creator functions and the name of the actions
- if the actions have outside dependencies (say on `event`, which indirectly depends on `featureFlag`), those are imported and executed before `configureStore` is executed
- by moving the side effects (and more importantly, their dependencies) outside the dependency chain of reducers and action creators,  circular dependencies that flow back to …

refactor(redux): move me actions with side effects to meThunks

---

src/dataExplorer/components/DeleteDataOverlay.tsx
src/shared/actions/predicates.ts
src/shared/actions/predicatesThunks.test.ts
src/shared/actions/predicatesThunks.ts
src/shared/components/DeleteDataForm/DeleteDataForm.tsx
src/shared/components/DeleteDataForm/FilterRow.tsx
src/shared/components/DeleteDataOverlay.tsx

closes #131
closes #138
Makes `predicates` action creators pure by moving the functions with side effects into `predicatesThunks`
```sh
madge --webpack-config webpack.common.ts src/store/configureStore.ts --image graph.svg --circular
```
- `configureStore` builds the empty store based off the initial state the reducers describe
- to do this, `configureStore` imports all the reducers.
- reducers pull in the action creator functions and the name of the actions
- if the actions have outside dependencies (say on `event`, which indirectly depends on `featureFlag`), those are imported and executed before `configureStore` is executed
- by moving the side effects (and more importantly, their dependencies) outside the dependency chain of reducers and action creators,  circular dependencies that …

refactor(redux): remove side effects from predicates actions

---

src/dashboards/components/DashboardHeader.tsx
src/dashboards/components/DashboardPage.tsx
src/shared/components/TimeSeries.tsx
src/timeMachine/actions/queries.ts
src/views/actions/thunks.ts

The Dashboard Query Cache has been on for a few weeks without any reported issues. This is just some clean-up to remove the feature flag from the UI and establish this cache as the norm

chore(queryCache): remove dashboard queryCache from the UI

---

src/flows/components/header/Submit.tsx
src/flows/context/query.tsx
src/shared/apis/queryCache.ts
src/timeMachine/actions/queries.ts
src/timeMachine/components/SubmitQueryButton.tsx

Closes https://github.com/influxdata/idpe/issues/8328
The cancel query button was previously being toggled onClick, making it not cancellable if a query is triggered some other way
Created a cache to store queryIDs and abortControllers that can be referenced by the cancel button.

feat(cancel-btn): cancel button can now cancel queries no matter how they are issued

---

src/external/monaco.flux.server.ts
src/timeMachine/apis/queryBuilder.ts
src/variables/utils/ValueFetcher.ts

This PR is part of a series of PRs aim to reduce the number of parsers in use in the UI. In particular, this PR aims to remove a parser that has been in use on tools and in production behind a feature flag for the past week without raising any red flags

chore(remove-fromFluxParseReponse): removed parser feature flag

---

.circleci/config.yml

working on moving as much stuff as possible off of jenkins and over to circle, because our neglect of jenkins as gotten to the point where it's upsetting day to day operations.
this extends our current testing pipeline to add a conditional workflow that only runs on master. it builds the production image in tandem with the testing image, waits for the tests to pass, then deploys the production image.
currently not gating on e2e passing until that gets more reliable (mimics current behavior in production pipeline)
depends on https://github.com/influxdata/monitor-ci/pull/99, but like.. real close to each other

feat: deploy with circle ci

---

.circleci/config.yml

watch me learn bash and circle. live. on master.
when i ssh'd into the deploy step and ran the new command as outlined in the script changes, it pushed the correct image all the way to argo, so i think it's in a good spot

fix: pass the correct env vars to the deploy script

---

.circleci/config.yml

we're using an intermediary image for testing, or whenever you use `make update` in local development. currently this image is generated on all pushes to master and built over on jenkins.
but the theme of the day is "DOWN WITH JENKINS"
so... this builds that image on circle instead

feat: keep the ui image around for local development

---

src/shared/parsing/flux/response.test.ts
src/shared/parsing/flux/response.ts
src/timeMachine/utils/rawFluxDataTable.test.ts
src/timeMachine/utils/rawFluxDataTable.ts

Closes https://github.com/influxdata/idpe/issues/8927
NaN is still a `typeof === number` so parsing a NaN was causing the parser to crash.
Make sure that the value is also not `NaN`

fix(parsing-NaN): fixed NaN time conversion bug

---

src/timeMachine/components/WindowPeriod.tsx

In the check's alert builder for setting the schedule every, we are storing it in a state. Updated the `Window Period` in query builder to use that state if we are in the create check overlay.
closes #179

fix(checks): updated window period in checks

---

src/Logout.tsx
src/store/configureStore.ts

closes https://github.com/influxdata/influxdb/issues/19648
this fixes influxdb/19648 where the tokens persist to the next user after logout, this clears the redux store on logout in both cloud and non cloud cases to the tokens and other data will not continue to be stored after logout.

fix: redux state clear after logout

---

src/flows/components/EmptyPipeList.scss
src/flows/components/FlowsExplainer.tsx
src/flows/components/FlowsIndex.test.tsx
src/flows/components/FlowsIndexEmpty.tsx

Closes #144 
This PR adds the redesigned UI for the empty state of the flows index page:
https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=934%3A354

feat(flows-index): redesigned the flows index page to include helper text

---

src/flows/components/ExportTaskOverlay/CreateTaskBody.tsx
src/flows/components/ExportTaskOverlay/ExportTaskButtons.tsx
src/flows/components/ExportTaskOverlay/ExportTaskOverlay.tsx
src/flows/components/ExportTaskOverlay/QueryTextPreview.tsx
src/flows/components/ExportTaskOverlay/TaskDropdown.tsx
src/flows/components/ExportTaskOverlay/UpdateTaskBody.tsx
src/flows/components/ExportTaskOverlay/WarningPanel.tsx
src/flows/components/Flow.tsx
src/flows/components/FlowPage.tsx
src/flows/components/header/Submit.tsx
src/flows/components/header/index.tsx
src/flows/components/panel/ExportTaskButton.tsx
src/flows/components/panel/FlowPanel.tsx
src/flows/context/overlay.tsx
src/flows/context/pipe.tsx
src/flows/pipes/Bucket/view.tsx
src/flows/pipes/Data/index.ts
src/resources/selectors/index.ts
src/shared/components/FluxMonacoEditor.tsx
src/tasks/actions/thunks.ts
src/types/flows.ts

Closes https://github.com/influxdata/influxdb/issues/19603
This PR adds functionality to the `Output to Bucket` flows pipe option by allowing users to create queries and export them as tasks.

feat(export-to): allow queries to be exported as tasks from flows

---

src/flows/context/query.tsx
src/timeMachine/actions/queries.ts
src/timeMachine/components/SubmitQueryButton.tsx

The feature flag for cancelQueryUiExpansion has been enabled on production and tools for two weeks without any complaints. This is just a clean-up to remove it from the UI. Once the UI has been updated, I'll remove the flag from IDPE, followed by config cat

chore(remove-flag): removing cancelQueryUiExpansion flag after being on for two weeks

---

package.json
src/flows/components/panel/Results.tsx
src/shared/parsing/flux/response.test.ts
src/shared/parsing/flux/response.ts
src/timeMachine/components/RawFluxDataGrid.tsx
src/timeMachine/components/RawFluxDataTable.tsx
src/timeMachine/components/Vis.tsx
src/timeMachine/utils/rawFluxDataTable.test.ts
src/timeMachine/utils/rawFluxDataTable.ts
yarn.lock

Closes #201 
The way that the RawDataTable is currently built out, the view layer can't parse partial CSVs and just renders blank data
Update RawDataTable to accept parsed CSVs rather than raw CSVs, and render the data with an optional offset that is applied for UI pagination. Feature flagged this here:
https://github.com/influxdata/idpe/pull/9011

fix(flows-ui-pagination): fixed the UI pagination for flows and feature flagged it

---

src/flows/context/results.tsx

Closes #226 
Previously generated raw data results would be passed into the Raw Data View for a metric selector if a previous selector had been run, and the new metric selector had not.
Copy pasted some work that Boatie told me would create a separate context for the `results` whenever a new input type was injected, it worked.

fix: metric selector from populating with previous results

---

src/utils/env.ts

connects idpe #9047. Read the comments on that ticket for more information about how to reproduce. Not sharing here on a public channel.
**`--sq`**
>Usually the output is made one line per flag and parameter. This option makes output a single line, properly quoted for consumption by shell. 
https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---sq

fix: make git rev-parse head into single line

---

.circleci/config.yml

repo split PLUS migrating off of jenkins while all deploys are blocked for a week and there's fires in prod? i knew this all went a little too smoothly.
this turns on the shas coming from circle, and not whether or not git is installed on the docker image that builds the assets
NOTE: wait until the "trim stuff of of the sha string" PR lands into master

fix: turn circle shas back on

---

src/flows/context/schemaProvider.tsx
src/shared/actions/schemaCreator.ts
src/shared/actions/schemaThunks.ts
src/shared/reducers/schema.ts
src/shared/utils/flowSchemaNormalizer.ts

Closes #231 
Selecting a new bucket was clearing the cache for the existing fields list
Turns out the reducer was clearing the cache, so we just adjusted that

fix(metric-selector): fixed metric selector from clearing cached results when selecting a new bucket in a new metric selector

---

package.json
yarn.lock

Updates to the latest giraffe. Should be no different to the application.
See: https://github.com/influxdata/giraffe/pull/349

chore: update giraffe to 0.42.0 the one that switched to webpack builds

---

package.json
src/dashboards/components/NoteEditorPreview.tsx
src/shared/components/views/MarkdownRenderer.test.tsx
src/shared/components/views/MarkdownRenderer.tsx
src/templates/components/CommunityTemplateReadme.tsx
src/writeData/components/WriteDataDetailsView.tsx
yarn.lock

Closes influxdata/idpe#8810
- Updated from `ReactMarkdown` to `marked` library
- Updated the renderer code to render literal string with image url if the markdown contains `<img>` tag
- Created a test for markdown renderer when markdown has an img tag it should render literal string

fix(markdown): update Markdown Renderer Library to render the components correctly

---

src/flows/context/query.tsx

cause.. you can't "own" a demo data bucket?
uses the flux query parser provided by the flux team to generate an ast of the query, then we walk the tree to find a bucket name in there, and try to cross reference it with the buckets that are existing in the system. Same technique that is used in time machine.
i'm not happy about waiting for buckets to be loaded before we can run a query, feels like a hydrate variables situation, but it is what it is.

feat: derive orgid from bucket selection in query

---

package.json
yarn.lock

Closes https://github.com/influxdata/giraffe/issues/357
`yarn install` also happened to remove an unnecessary entry named `mdurl`. I have confirmed with @Palakp41 that this is not needed and should be removed. I will keep this change because it was automatically made as a result of `yarn install`.

chore: update giraffe to resolve tooltip z-index issue

---

src/shared/utils/vis.ts

This is to close #208 
This is not a perfect solution, because we do not currently allow users to truly edit the tooltip and what it displays. This allows giraffe to call the no formatter option that was added. In the XY plot we do allow people to choose a no format option, and that should do no formatting on the tooltip as well. 
We are planning to come up with a more robust solution in the giraffe upgrade project. I dont want to try and shoehorn in a solution when we are going to get a fleshed out solution in a few weeks

fix: tooltip same units

---

src/authorizations/components/TokenRow.tsx

`TokenRow.tsx` throws a key warning and has RFC3339 formatted machine dates.
This fixes the warning and make the dates readable for humans.

fix: give token row human readable dates; fix key warning

---

src/flows/components/header/Submit.tsx
src/timeMachine/actions/queries.ts
src/timeMachine/components/SubmitQueryButton.tsx

After clicking the cancel on data explorer, we don't get into the componentDidUpdate life-cycle because we are not updating the state of the query status in redux. The query status in the props is from the redux state query results which connects to all the query. Adding a dispatch to update the query status for query result to done when cancelled is clicked, fixes this issue: #idpe/7683 (https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/7683)

fix(de): cancel button cancels all running queries

---

.gitignore
package.json
src/client/unity.yml

Closes: #287 
This is a draft for the `Users` and `Invites` unification API client.  If we can knock out a contract between Quartz and the `ui` then e-commerce and ui can start working in parallel 😸 .

feat(rfc): unity swagger.yml Users and Invites draft

---

src/flows/context/schemaProvider.tsx
src/shared/actions/schemaThunks.ts

Closes #315 
Selecting a bucket with lots of data for the past 4 days makes the metric selector slow
Use the time provided within the flow as a basis for the metric selector range

feat: connect timerange to metric selector

---

src/shared/constants/index.ts
src/shared/utils/errors.ts

Usages of process.env are now reduced to two files - the constants file and an env.ts.
Added and used a constants formatting function to trim whitespace from all string constants that weren't hard coded to a value otherwise.
The process.env usage in env.ts is not easily removed - that file uses a module.exports to export a lambda function and I could not find a way to have that function import information from the general constants file. Given that there are a number of comments about webpack, it seems that file is build time related and thus process.env usage may be appropriate.
Assuming there are no issues with the env.ts remaining in its current state, this closes ticket #237 .

chore: clean up usage of process.env

---

src/flows/pipes/Visualization/view.tsx

the visualization panel expected not to be rendered by the resizer component unless the results had parsed data. something along the line changed, and it broke, so lets guard against that while we figure out some tests

fix: visualization crash

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

The intent of this Pull Request is to introduce templates that will allow for more detailed feature and bug requests through github. 
The content of these templates closely mirrors that of the influxdb repo, so please let me know if there are changes that should be made to the templates.

feat: add-issue-and-bug-templates-for-github

---

src/flows/context/schemaProvider.tsx
src/shared/actions/schemaThunks.ts

for some reason, refreshing the notebooks page would make the metric selector clear the filters you put on there. undid that.

fix: perist metrics on refresh

---

package.json
yarn.lock

Closes https://github.com/influxdata/giraffe/issues/394
Updates giraffe to restore hover point calculation on all data. Limit will instead be placed visually on the `<Tooltip>`

chore: update giraffe

---

src/organizations/components/OrgProfileTab.tsx

Adds a few bits of information to the about page to make it more useful.

feat: add more information to about page

---

.circleci/config.yml

should unblock all the things. also makes sure that firefox is running the same image of the current branch as the chrome version

fix: locking idpe to Nov10th until resolved

---

src/notifications/rules/components/TagRuleOperatorDropdown.tsx

Closes EAR#1932
TagRuleDropdown didn't include `notequal` text in the dropdown. So, when an api is used to update notificationRule to have a tagRule with `notEqual`, ui was erroring out because the dropdown couldn't find `!=` operator in the operators array.

fix(notificationRule): add operator dropdown value for TagRuleDropdown

---

src/cloud/components/RateLimitAlert.tsx

This is a fix to prevent the header experiment from showing on any page except the Load Data page.

fix(experiment): restrict to Load Data page

---

src/flows/context/flow.current.tsx
src/flows/context/flow.list.tsx

this one puts `local_` in front of all locally generated ids used when creating notebooks / panels on the frontend for the local storage mechanism. hopefully this will give us enough of a signal to segment them from api generated ids for when it comes time to migrate them out of local storage and on to the backend, all without changing too much of the internal routing.

feat: prefix locally generated ids

---

src/flows/pipes/ToBucket/ExportTaskOverlay/CreateTaskBody.tsx
src/flows/pipes/ToBucket/ExportTaskOverlay/ExportTaskButtons.tsx
src/flows/pipes/ToBucket/ExportTaskOverlay/TaskDropdown.tsx
src/flows/pipes/ToBucket/ExportTaskOverlay/UpdateTaskBody.tsx
src/flows/pipes/ToBucket/ExportTaskOverlay/WarningPanel.tsx
src/flows/pipes/ToBucket/ExportTaskOverlay/context.tsx
src/flows/pipes/ToBucket/ExportTaskOverlay/index.tsx

- Centralize form logic in context provider
- Submit button always enabled
- Validates entire form when `Submit` is clicked
- Validate inputs when they are changed
- Strengthen `schedule` input validation
- Close overlay on submit (courtesy of @drdelambre)

refactor(notebooks): improve export task form validation

---

src/shared/utils/useLegendOrientation.ts

Closes #178 
Set default values for prod users _before_ the feature flag is turned on. The feature flag will be turned on as soon as the docs team has the documentation for these options.
Previously, only opacity had a default set. Threshold needs a default as well. To set a default, we reverse the condition in the hook and return the default when the flag is off.
**_If we don't do this_**, then the zero value from Go for a number is 0 which will cause the threshold to be 0, which will lead to users saying, "How come my legend is turned sideways now?" when the feature flag gets turned on.
But with a default of 10, then fewer of them will have this "problem". Or at least the users who have this problem definitely also have graphs that have a lot of data in the tooltip, and maybe they will …

feat: set a default for legendOrientationThreshold while the feature flag is still off in prod

---

src/flows/context/flow.current.tsx

found an error on the demo in which data was "being lost" when changing the query period dropdown. seems to be that we were reapplying stale state

fix: dont use stale flow data

---

src/shared/components/inlineLabels/InlineLabelPopover.tsx
src/shared/components/inlineLabels/InlineLabelsEditor.tsx

Closes https://github.com/influxdata/influxdb/issues/17853
fix for popups not closing when esc is pressed.  
clockface will close the popover on the esc key if it is not controlled; but in this case it is controlled by the InlineLabelPopover.
since the input takes all the focus and all the keys, listen on the input for the escape,  and the container of the inline labelpopover controls the popover visible state, so added another handler there to hide it.

feat: fix label popup close on esc key 

---

package.json
yarn.lock

Upgrade `flux-lsp-browser` to [flux-lsp v0.5.25](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.25)
Note: This will disable callbacks for user data and any auto-complete functionality that relies on them. This should not require any change to the ui code. See https://github.com/influxdata/flux-lsp/pull/194 for details.

build(lsp): Upgrade flux-lsp-browser to v0.5.25

---

cypress/e2e/shared/checks.test.ts
jest.config.js
jestSetup.ts
package.json
src/cloud/utils/__mocks__/reporting.ts
src/mockAppState.tsx
src/resources/components/__mocks__/GetResources.tsx
src/shared/actions/__mocks__/notifications.ts
src/shared/utils/__mocks__/errors.ts
src/templates/containers/CommunityTemplatesIndex.test.tsx
src/templates/containers/CommunityTemplatesIndex.tsx
yarn.lock

Closes https://github.com/influxdata/influxdb/issues/19175
* Adds an integration test for the three conditions in `CommunityTemplatesIndex.tsx` function `startTemplateInstall`
* Adds the `testing-library` helper `jest-dom`
* Adds manual mocks for the following functions:
* `src/cloud/utils/reporting`: `event`
* `src/resources/components/GetResources`: `GetResources`
* `src/shared/actions/notifications`: `notify`
* `src/shared/utils/errors`: `reportErrorThroughHoneyBadger`, `parseComponentName`
* To use the mocks, simply pass the path to the `jest.mock` function:
* ```ts
jest.mock('src/cloud/utils/reporting')
jest.mock('src/resources/components/GetResources')
```

test(community-templates): integration test for startTemplateInstall function

---

src/flows/components/header/Submit.tsx
src/flows/components/panel/Results.tsx
src/flows/context/flow.current.tsx
src/flows/context/flow.list.tsx
src/flows/context/pipe.tsx
src/flows/pipes/RawFluxEditor/view.tsx
src/flows/pipes/Visualization/view.tsx

if you open the same flow in two tabs, the page starts refreshing until your browser runs out of memory and crashes. 
the fixes to the lifecycle events are here:
https://github.com/influxdata/ui/compare/alex_break_localstorage?expand=1#diff-92d15362f0fc7f6974a7c37272055303d39845a30d049580e8ecda19cfd1c227R81
https://github.com/influxdata/ui/compare/alex_break_localstorage?expand=1#diff-52d3ae4e913057fdba995356a366de14e201ffd609ba6761558e354baec7d8aaR109
this one added a lot of slowness to the system:
https://github.com/influxdata/ui/compare/alex_break_localstorage?expand=1#diff-52d3ae4e913057fdba995356a366de14e201ffd609ba6761558e354baec7d8aaL110
there are still some notable outstanding issues:
dont try and edit a markdown panel while two tabs are open
dragging the visualization in one side …

fix: clean localstorage event lifecycles

---

src/unity/components/users/InviteListContextMenu.tsx

An unreachable return that firefox warned me about.
Fixes this:

chore: fix an unreachable return the browser complained about

---

src/buckets/components/BucketAddDataButton.tsx
src/buckets/components/BucketCardActions.tsx
src/buckets/components/csvUploader/CsvUploaderBody.tsx
src/buckets/components/csvUploader/CsvUploaderSuccess.tsx
src/buckets/components/csvUploader/CsvUploaderWizard.tsx
src/buckets/components/csvUploader/DragAndDrop.tsx
src/buckets/components/csvUploader/DragAndDropHeader.tsx
src/buckets/components/csvUploader/DragInfo.tsx
src/buckets/containers/BucketsIndex.tsx

The UI allows users to download CSVs of their data, but they can't upload that data. New users with existing data might not want to go through the configuration process of setting up a telegraf in order to write existing data onto a bucket.
Add a CSV uploader to the UI
- Needs a link to CSV format documentation
- Update the `time` to be deterministic based on the data rather than set to MS

feat: csv uploader for the UI

---

package.json
yarn.lock

Upgrade `flux-lsp-browser` to [v0.5.26](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.26)

build(ui): Upgrade flux-lsp-browser to v0.5.26

---

.circleci/config.yml
cypress/e2e/shared/explorer.test.ts

doing this just in case there is an emergency over the holidays, and someone has to deploy to fix it (kind of our only trick right now)
temporarily points to a version of monitor-ci  on a branch with reverts applied to it. the idea is to remove when we unblock the pipeline

fix: reverts ssl changes to open up deployments

---

src/shared/components/graph_tips/GraphTips.tsx

Closes #435
This was never implemented in giraffe, but the text from Dygraphs was copied over

fix: remove outdated graph tips

---

src/flows/components/header/Submit.tsx
src/flows/context/query.tsx
src/flows/pipes/MetricSelector/AggregateWindowSelector.tsx
src/flows/shared/ResizerHeader.tsx

Closes #417
The primary purpose of this PR is to allow users to run queries when clicking the `play` icon in the pipe:
This PR also addresses some random issues that were causing Notebooks to be wonky, namely:
- The run button never being disabled due to a miscalculation in identifying metric selector queries
- removing aggregateOfAggregates as a hack to run queries explicitly when updating an aggregate type and just running the query when an aggregate type is changed
- Only changes the loading state of pipes that are being run

feat: fixed some bugs and allowed users to query from the pipe icon

---

src/buckets/components/context/csvUploaderProvider.tsx
src/buckets/components/csvUploader/CsvUploaderWizard.tsx

Closes #461 
The CSV uploader was incorrectly uploading `_value` data due to the way that the `_value` is derived on writes from the `_field`. This PR fixes that by assigning the `_value` to the `_field`. This PR also addresses some of the performance issues by decreasing the chunk size of the LP being uploaded in order to (hopefully) lower the query run time for a given chunk

fix: csv uploader correctly maps out values

---

.circleci/config.yml

This will get circleci to use the master branch of monitor-ci again.

chore: point circleci at master again

---

.circleci/config.yml

We need to quantify our main page's load time. For that, we are going to use lighthouse. It is added as a service to monitor-ci and will be triggered by ui builds. When the report scores are generated, they will be posted to their respective PRs.

feat: add lighthouse job

---

cypress/e2e/shared/notificationEndpoints.test.ts
cypress/e2e/shared/notificationRules.test.ts

Closes #153 
Enables notification e2e tests and changes test ids to correctly identify input fields.

test: enables notification tests, fixes failures

---

.circleci/config.yml

Closes # https://github.com/influxdata/ui/issues/476
Add master flag to make PR flag mutually exclusive. The issue was that LHR service was failing CircleCI checks on master because lhr service expects a PR but on master, there's no PR. So, adding a flag so that the artifacts still get generated and uploaded but the non-existant PR doesn't get updated.

feat: add lhr support for master branch

---

src/shared/components/CloudUpgradeButton.tsx
src/shared/components/CloudUpgradeNavBanner.tsx

This PR ends the "Collapsed Nav Upgrade Prompt" experiment. It cleans up the experiment code and implements the winning icon variant.

chore(experiment): end experiment and change icon

---

src/shared/components/BandPlot.tsx
src/shared/components/HeatmapPlot.tsx
src/shared/components/HistogramPlot.tsx
src/shared/components/MosaicPlot.tsx
src/shared/components/ScatterPlot.tsx
src/shared/components/ViewSwitcher.tsx
src/shared/components/XYPlot.tsx
src/shared/constants/index.ts
src/shared/utils/useLegendOrientation.ts
src/timeMachine/actions/index.ts
src/timeMachine/components/view_options/BandOptions.tsx
src/timeMachine/components/view_options/HeatmapOptions.tsx
src/timeMachine/components/view_options/HistogramOptions.tsx
src/timeMachine/components/view_options/LegendOrientation.tsx
src/timeMachine/components/view_options/LineOptions.tsx
src/timeMachine/components/view_options/MosaicOptions.tsx
src/timeMachine/components/view_options/ScatterOptions.tsx
src/timeMachine/reducers/index.ts
src/views/helpers/index.ts

Closes #388 
unselected (toggle off)
selected (toggle on)

feat: colorize row toggle

---

src/flows/components/panel/Results.tsx

Moving this out of the schema reducer PR to address the concern separately

fix: these guards fix an error that crashes notebooks when the raw data is undefined

---

src/templates/containers/CommunityTemplatesIndex.test.tsx

Updates community template integration test to check that installer button is visible, which is more specific than the previous check of being in the document.

test: make tighter assertion about installer button being visible

---

src/flows/components/panel/FlowPanel.tsx
src/flows/pipes/MetricSelector/AggregateWindowSelector.tsx
src/flows/pipes/MetricSelector/style.scss
src/flows/pipes/MetricSelector/view.tsx
src/flows/shared/Resizer.scss
src/flows/style.scss

Closes #452
- Refactor panel header and metric selector controls to stack vertically on small displays
- Limit metric selector filters width to an arbitrary 50% of viewport width

fix(notebooks): make panel header & metric selector controls responsive

---

.circleci/config.yml

Part 1: We have some existing weirdness where we load Lighthouse and Cypress images into the compose cloud cluster network and tell it to run things using the internal network routing.
It would be super cool to have these service images built and run outside of the cluster, but point to the cloud cluster (kubernetes.docker.internal or equivalent) when running the tests. Seems pedantic, but the testing infrastructure shouldnt be defined within the "cloud infrastructure" definition and we now have the ability to separate them.
**Story: ** https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/monitor-ci/132

feat: add cross network communication

---

package.json
yarn.lock

Upgrade flux-lsp-browser to [v0.5.27](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.27)

chore: Upgrade flux-lsp-browser to v0.5.27

---

cypress/e2e/shared/checks.test.ts
cypress/e2e/shared/dashboardsView.test.ts
cypress/e2e/shared/explorer.test.ts
cypress/e2e/shared/tasks.test.ts
cypress/support/commands.ts
scripts/start_docker.sh
src/timeMachine/components/TimeMachineFluxEditor.tsx
src/variables/components/VariableDropdown.tsx

Closes https://github.com/influxdata/monitor-ci/issues/124, https://github.com/influxdata/influxdb/issues/20482
Adds a script that has the ability to link clockface and giraffe repos before running `yarn start:docker` when starting the project with monitor-ci.
--> Also fixes broken e2e tests! <--
See monitor-ci PR for more details: https://github.com/influxdata/monitor-ci/pull/156

test: Adds the ability to test clockface and giraffe locally

---

src/App.tsx
src/Setup.tsx
src/perf/components/PageSpinner.tsx
src/shared/containers/SetOrg.tsx
src/shared/containers/index.tsx

Closes #509
Use React Suspense to code split based on routes - improves performance scores by 20 points!

chore: use react suspense to lazy load components by route

---

cypress/e2e/shared/checks.test.ts

While working on: https://github.com/influxdata/ui/pull/515 to resolve certain tests that fail due to "detached" elements.  I'm skipping come common culprits.

test: skip and comment flakey tests

---

cypress/e2e/shared/explorer.test.ts
src/annotations/api/index.ts
src/shared/components/XYPlot.tsx
src/types/annotation.ts

Closes #495
**On XY Plots on accounts where the `annotations` feature flag is on**, double clicking on the graph will write an annotation at the time of the graph.
Clicking on the graph at the time shown in the tooltips:
will produce this response:
```json
[
{
"stream": "default",
"summary": "hi",
"end-time": "2021-01-12T14:00:43.6Z",
"start-time": "2021-01-12T14:00:43.6Z"
}
]
```
Which is the correct date time for my timezone, but in UTC.

feat(flagged): double click annotations to add to graph

---

src/timeMachine/components/RawFluxDataTable.scss

Closes #
Modifies the raw table css element to include the `user-select` attribute that other browsers than chrome support. This will allow selecting the text in safari for one.
see https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
and
https://caniuse.com/?search=user-select

chore: allow raw table selection.

---

.github/PULL_REQUEST_TEMPLATE.md

Makes `Describe your proposed changes text` a comment so it doesn't show up in the PR description.

docs: make Describe your proposed changes text a comment

---

cypress/e2e/shared/checks.test.ts
cypress/e2e/shared/notificationEndpoints.test.ts
cypress/e2e/shared/notificationRules.test.ts

The `cypress/e2e/shared/checks.test.ts`, `cypress/e2e/shared/notificationEndpoints.test.ts`, and `cypress/e2e/shared/notificationRules.test.ts` tests all make assertions that reference `Cypress.config().baseUrl`. 
Cypress deals with routing intelligently and is agnostic to whether or not there is a trailing `/` when routing. But using string interpolation to construct and assert on a url results in a situation where if the baseUrl ends with a `/` the route string asserted on can contain `//` but the url actually contains just one `/`. I've chosen to remove references to `Cypress.config().baseUrl`.  instead asserting the url string include the rest of the route.

feat(e2e-in-KinD): Remove all references to Cypress.baseUrl

---

package.json
yarn.lock

Upgrade flux-lsp-browser to [v0.5.28](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.28)

chore: Upgrade flux-lsp-browser to v0.5.28

---

src/shared/visualization/ViewTypeDropdown.tsx
src/timeMachine/components/WindowPeriod.tsx

Closes https://github.com/influxdata/idpe/issues/9585
When coming from Alerts to DE the viewType is switched via dispatch from 'alerting' to
'de' and while this change occurs, we need to handle undefined props

fix: handles undefined props while switching viewTypes

---

src/buckets/components/context/csvUploaderProvider.tsx
src/buckets/components/csvUploader/CsvUploaderError.tsx
src/buckets/components/csvUploader/CsvUploaderWizard.tsx

Closes #525, #524
Some improvements to the CSV uploader:
1) If the upload fails, the wizard will report the failure. This includes async failures like if the write API requests fails. Some explanation for the failure is provided in the notification.
2) If csv data contains special characters in tag values, these characters are escaped (this only applies to tag columns of string type). 
3) If csv _value column is of string type, it adds quotes around the values
See these example CSVs for trying this out:
[example csv.zip](https://github.com/influxdata/ui/files/5845370/example.csv.zip)

fix: CSV uploader reports failures and parses special characters

---

src/timeMachine/components/FillValues.tsx

Closes https://github.com/influxdata/idpe/issues/9585
See https://github.com/influxdata/ui/pull/529
> When coming from Alerts to DE the viewType is switched via dispatch from 'alerting' to
'de' and while this change occurs, we need to handle undefined props
I found one more instance where this was occurring - `fillValues`

fix: handles undefined fillValues prop

---

cypress/e2e/shared/checks.test.ts
src/shared/components/CheckPlot.tsx

Closes https://github.com/influxdata/idpe/issues/9590
Checks are only compatible with numeric fields. Currently if a non-numeric field is chosen, the page crashes with a runtime error. This change shows the user a friendly error message instead, asking them to choose a numeric field.
Adds e2e test to cover this

fix: error message for incompatible check column types

---

src/buckets/components/context/csvUploaderProvider.tsx

Closes #538 
Allows CSV parser to handle multiple measurement columns when there are multiple types of the `_value` column involved. 
See https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/fromFlux.ts#L62

fix: csv parser understand multi-measurements

---

src/variables/actions/creators.ts
src/variables/actions/thunks.ts
src/variables/reducers/index.test.ts
src/variables/reducers/index.ts

Closes #275
This PR addresses #275 which concerns variables not being reorderable in the dashboards page

fix: reordering variables now working again

---

package.json
yarn.lock

[Flux LSP v0.5.29](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.29)

chore(lsp): Upgrade flux-lsp-browser to v0.5.29

---

src/shared/components/ErrorBoundary.tsx
src/timeMachine/components/Vis.tsx

Closes https://github.com/influxdata/idpe/issues/9584
ErrorBoundary and Vis components were re-rendering on every interaction, even though their
props were identical. This caused performance issues with query editor. 
I added React.memo to both of these components and provided a custom comparison function that uses Lodash's `isEqual` to perform a deep comparison between the props. Shallow comparisons provided by `PureComponent` or simply `===` does not do the trick in this case.
To verify the improvement, upload the attached CSV to a bucket, query data from the last 30 days and show the "raw data view". There will be 120k rows. Start typing in the flux query editor and you shouldn't notice any slow down over time. 
Without this improvement, the table was being re-rendered on every …

fix(performance): prevents unneeded renders on identical props

---

jest.config.js
jestSetup.ts
src/templates/components/CommunityTemplateInstallOverlay.test.tsx
src/templates/containers/CommunityTemplatesIndex.test.tsx
src/variables/reducers/index.test.ts

closes idpe 9623
TypeScript errors were temporarily turned to warnings. After reversing this back, some of the tests written since `warnOnly` was on have failed. This goes through and fixes the errors in those tests.

test: turn off TypeScript warnOnly

---

src/timeMachine/utils/queryBuilder.test.ts
src/timeMachine/utils/queryBuilder.ts

took part of palak's fix;  just needed the part that  zeroed out the group clause if values are absent.
Closes https://github.com/influxdata/influxdb/issues/19216

fix: for #19216

---

src/shared/constants/timeRanges.ts
src/types/queries.ts

Closes # N/A
I often find myself wanting to pick 3 hours for the view of my charts. 6 hours brings in more data than I want and often 1 hour is too little.

chore: Allow selecting 3 hours in dashboard time range picker.

---

src/shared/utils/featureFlag.ts

just orders the output list into a copy, no mutation is done.
Closes #563

fix:  feature flag list is now ordered alphabetically.

---

src/flows/context/flow.list.tsx

fixes notebook duplication bug. When migration completed, state was mutated and ids from API were not saved in state. Next time the user navigates to the page, the migration occurs again. The GET call will return all of these notebooks that were created and re-created from the failed migrations, making it look like there are duplicates.

fix: resolves notebook duplication bug

---

src/dashboards/components/variablesControlBar/VariablesControlBar.scss

Closes #530
Enables wrapping on variable control bar contraction when screen shrinks

fix: wrap variables on shrinking of screen size

---

package.json
yarn.lock

[Flux LSP v0.5.31](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.31)

chore: Upgrade flux-lsp-browser to v0.5.31

---

src/shared/components/DefaultErrorMessage.tsx

Problem: 
After addressing the problem of not having a bug report template for the UI repo, it is now necessary to address the need for the git_sha (version number) to be added to the bug ticket github page in order to provide greater levels of details for bug submissions. 
This PR attempts to address this issue. See screenshot below for proposed resolution.

fix: change-bug-fix-template

---

src/Setup.tsx
src/shared/containers/GetOrganizations.tsx

Fixes "Could not download wasm module" error. Turns out lazy loading the signin component is a bad idea.

fix: wasm download failures due to lazy loading signin

---

src/flows/components/header/index.tsx
src/flows/context/flow.current.tsx
src/flows/context/flow.list.tsx
src/flows/context/query.tsx

Closes #621 
There are three issues:
1. Users were unable to go directly to a shared Notebook url that wasn't in their browser's cache.
2. The FlowProvider expects an id to exist before rendering FlowPage but FlowPage is responsible for getting the id from the url.
3. Going to a notebook directly that doesn't exist throws an error with no message
I fixed (1) by calling `getAll` whenever the `currentID` is changed to pull down the notebooks. I fixed (2) by moving the check for the existence of the down the component tree. If the `flow` prop is undefined, assume it doesn't exist. I fixed (3) by showing an error message that says the notebook couldn't be found.

fix: should get id from url before checking if flow exists

---

src/visualization/types/SingleStat/view.tsx
src/visualization/types/SingleStatWithLine/view.tsx

hotfix for single stat graphs not rendering on prod.
companion to #648

fix: reenable strings for single stat

---

src/dataLoaders/components/collectorsWizard/CollectorsStepSwitcher.tsx
src/dataLoaders/components/collectorsWizard/CollectorsWizard.tsx
src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx
src/dataLoaders/components/collectorsWizard/select/StreamingSelector.test.tsx
src/telegrafs/components/Collectors.test.tsx
src/telegrafs/components/Collectors.tsx

Closes #20727
This PR addresses the bug in the ticket above by removing some prop drilling and localizing where buckets are pulled from. Also adds some tests.

fix: no buckets when opening telegraf config modal error

---

cypress/e2e/shared/checks.test.ts

New test for asserting an external link on the checks page points to a specific page in the documentation.

test(e2e): checks - visiting documentation through external link

---

src/authorizations/actions/thunks.ts
src/shared/copy/notifications.ts

Closes #637 
Adds a specific error message to the failed token creation process for website monitoring bucket

fix: add specific error message to token creation failure

---

src/dashboards/components/DashboardsCardGrid.scss

Closes https://github.com/influxdata/clockface/issues/517
Changes the value of the width of the dashboard card name editor so it doesnt overflow

fix: address overflowing dashboard name editor

---

src/buckets/components/RenameBucketOverlay.tsx
src/organizations/components/RenameOrgOverlay.tsx

Closes #672 
This fixes the bug where overlays were rendering off to the side instead of as overlays
It also adds onEscape functionality, which is nice

fix: overlays render properly and can close with onEscape

---

.github/pull_request_template.md
.github/semantic.yml

- allows revert commits (`"Revert "feat: ride unicorns""`)
- allows any commit to have a semantic commit
- the idea behind this is if you have three or four commits on a branch, and those commits are going to be squash merged into a single semantic commit, it's not really worth making someone force pushing commit changes to be semantic if they're going to be squashed anyway. it's causing more frustration than it's solving
- adds a github pull request template

chore: update github metadata stuff

---

.circleci/config.yml
cypress/e2e/cloud/buckets.test.ts
cypress/e2e/cloud/communityTemplates.test.ts
cypress/e2e/cloud/dashboardsView.test.ts
cypress/e2e/cloud/geoOptions.test.ts
cypress/e2e/oss/buckets.test.ts
cypress/e2e/oss/dashboardsView.test.ts
cypress/e2e/oss/scrapers.test.ts
cypress/e2e/shared/buckets.test.ts
cypress/e2e/shared/checks.test.ts
cypress/e2e/shared/dashboardsIndex.test.ts
cypress/e2e/shared/dashboardsView.test.ts
cypress/e2e/shared/explorer.test.ts
cypress/e2e/shared/labels.test.ts
cypress/e2e/shared/loadDataSources.test.ts
cypress/e2e/shared/notificationEndpoints.test.ts
cypress/e2e/shared/notificationRules.test.ts
cypress/e2e/shared/queryBuilder.test.ts
cypress/e2e/shared/tasks.test.ts
cypress/e2e/shared/telegrafs.test.ts
cypress/e2e/shared/tokens.test.ts
cypress/e2e/shared/variables.test.ts
cypress/fixtures/tokens.json
cypress/support/commands.ts
package.json

Issue: https://github.com/influxdata/idpe/issues/9547
Explanation of changes:
- Add `cy.getByTestID('tree-nav')` after every `cy.visit` in a `beforeEach`. Why: The app seems to run slower in the cluster and this causes a race condition. Basically the tests start execution before the page fully loads. Waiting on the tree-nav element forces the beforeEach to wait for the page to load before starting the tests. 
- Add `orgID` property to the `resource` object for each permission of each token we create during the token tests. The McFly user used in the kind tests isn't a "super user" like monitor-ci's "dev_user". McFly goes through the typical onboarding process and the IDPE authorization service requires that you provide the `orgID` property unless you have these super permissions.
- Set …

test: e2e tests now pass in KinD environment

---

.github/PULL_REQUEST_TEMPLATE.md
.github/pull_request_template.md

I accidentally committed an upper cased version of the pull request template from an old PR. This removes that and makes the lower cased one have the right content.

fix: remove capitalized pull request template file

---

cypress/e2e/shared/queryBuilder.test.ts
package.json
src/timeMachine/components/FillValues.tsx
yarn.lock

* also: changing test as needed for clockface 2.6.1;
This necessitated:
- improving the component as well (you can now click on the label)
- the test now accesses the togglebutton via the label text; which is what the user would do (click on the label)
The FillValue's label is now a child of the togglebutton; so the component hierarchy has changed to be consistent with what the togglebutton is expecting; which takes advantage of the fact that the entire togglebutton (including the children) are now clickable in 2.6.1 
the togglebutton changed just enough to break the querybuilder test, which highlighted/took advantage of  a problem with the test (and/or the togglebutton), so it is now fixed.  
having just one PR with *just* the upgrade and the changes needed for the upgrade.

chore: upgrading to clockface 2.6.1

---

src/templates/utils/index.test.ts
src/templates/utils/index.ts

Closes #675 
updated `validateTemplateURL` to ignore trailing whitespace as well as an optional query attached. Also added tests.

fix: validateTemplateURL whitespace and optional query

---

src/dataExplorer/components/DataExplorer.tsx
src/timeMachine/actions/index.ts
src/timeMachine/actions/queryBuilder.ts
src/timeMachine/actions/queryBuilderThunks.ts
src/timeMachine/components/FunctionModeSelector.tsx
src/timeMachine/components/QueryBuilder.tsx
src/timeMachine/components/TagSelector.tsx
src/timeMachine/components/WindowPeriod.tsx
src/timeMachine/components/queryBuilder/BucketsSelector.tsx

Another joint brought to you by Refactor Friday
- Moves all side effects out of the query builder actions into a thunks file
- Fixes imports

chore: create queryBuilderThunks to store thunks for query builder

---

src/perf/components/LazySVG.tsx
src/writeData/components/WriteDataItem.tsx

Improves performance of `load-data/sources` page by using React Suspense/lazy to load each SVG independently of the rest of the page.
https://user-images.githubusercontent.com/6411855/107820498-be634780-6d2f-11eb-8973-f685903c7123.mov

chore: lazy load svgs

---

src/writeData/components/clientLibraries/Arduino.md
src/writeData/components/clientLibraries/CSharp.md
src/writeData/components/clientLibraries/Go.md
src/writeData/components/clientLibraries/Java.md
src/writeData/components/clientLibraries/Kotlin.md
src/writeData/components/clientLibraries/Node.md
src/writeData/components/clientLibraries/PHP.md
src/writeData/components/clientLibraries/Python.md
src/writeData/components/clientLibraries/Ruby.md
src/writeData/components/clientLibraries/Scala.md
src/writeData/components/clientLibraries/Swift.md

Closes #628 
Links to the respective github repository for a given client library now open in new tabs, which should prevent redirect and go-back related issues seen by users up until now.

fix: link to repo opens in new tab

---

cypress/e2e/shared/buckets.test.ts
cypress/e2e/shared/dashboardsIndex.test.ts

Fixes broken e2e tests that are failing on the master branch. Fixes a race condition where the API doesn't respond immediately and cypress continues anyways. 
I tried to user `cy.intercept` but that only intercepts requests made _from_ the app, not _from_ cypress (in this case the tests are making API requests via cypress commands).

test: fix e2e dashboard and bucket test flakes

---

src/buckets/components/lineProtocol/LineProtocol.thunks.ts

Closes #677
Under this PR, the error message will now be displayed under the red influx sign, and the full error message is still in the console in case someone really has a case of the scrollies and wants to see that bad boy.

fix: better error message for failed line protocol upload

---

cypress/e2e/shared/dashboardsIndex.test.ts
cypress/e2e/shared/queryBuilder.test.ts

Query builder test was failing because selecting the text didn't toggle the radio button.
https://app.circleci.com/pipelines/github/influxdata/idpe/12784/workflows/ce864ec7-7d88-4f3b-9cf0-1c3e0d457635/jobs/243438

test: fixes querybuilder failing test

---

package.json
src/visualization/types/Graph/view.tsx
yarn.lock

Upgrades to [giraffe 2.2.0](https://github.com/influxdata/giraffe/releases/tag/v2.2.0) which gives us a new type definition. Very exciting stuff!
See [Giraffe #477](https://github.com/influxdata/giraffe/pull/477)

chore: upgrade to giraffe 2.2.0

---

src/templates/containers/CommunityTemplatesIndex.tsx
src/templates/utils/index.test.ts
src/templates/utils/index.ts

Closes #697 
This PR introduces an error message for the template url uploader when there is a space in between characters in the url and it also trims the url before submission.

fix: trim url and add error for spaces in between characters in url

---

src/timeMachine/components/Vis.tsx

Closes #719 
wraps the raw data view in the empty query view to help keep visualizations in line.
ultimate solution is to have raw data view be a visualization type, but we are working on remaking that component as the dataview, so i'm hesitant to handle that migration right now.

fix: wrapping raw data view

---

src/annotations/components/annotationForm/AnnotationMessageInput.tsx
src/visualization/types/Graph/view.tsx

Closes #711
- Only allows annotating when the annotation toggle is active.
- Viewing annotations is only possible when the annotation toggle is active

feat: only render and annotate when annotate mode is active

---

src/annotations/api/index.test.ts
src/annotations/api/index.ts
src/annotations/utils/formatQueryString.ts
src/types/annotation.ts
src/visualization/types/Graph/view.tsx

Closes #743
See: https://github.com/influxdata/monitor-ci/pull/173
Some backend changes to annotations were deployed. This makes both systems match. This allows us to turn this out in cloud environments for Influxers.

chore: update annotations to match api changes

---

package.json
yarn.lock

Upgrade Flux LSP to [v0.5.33](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.33)

chore: Upgrade flux-lsp-browser to v0.5.33

---

src/visualization/types/Table/options.tsx

table columns weren't showing up in the table vis options. now they are

fix: show table column options

---

src/overlays/components/index.tsx
src/variables/containers/VariablesIndex.tsx

The Export Variable overlay wasn't working because it was missing the right configuration. This PR attempts to fix it. 
What it was doing: 
after clicking export variable, it just shows `null`
After the fix:

fix: fixes missing configuration for Export Variable Overlay

---

src/visualization/types/Table/options.tsx

got some copy pasta in the keys. crazy that this worked at all.

fix: remove table threshold crash

---

src/shared/utils/vis.ts
src/timeMachine/actions/index.ts
src/timeMachine/components/FunctionModeSelector.tsx
src/timeMachine/components/Vis.tsx
src/timeMachine/constants/queryBuilder.ts
src/timeMachine/reducers/index.ts
src/timeMachine/selectors/index.ts
src/views/helpers/index.ts
src/visualization/types/Mosaic/options.tsx
src/visualization/types/Mosaic/properties.ts
src/visualization/types/Mosaic/view.tsx

Closes #510 
Mosaic updated with options to select the data columns, labels, and separator for the y-axis.

feat: update Mosaic visualization

---

src/shared/constants/colorOperations.ts

Connects https://github.com/influxdata/influxdb/issues/20750
See: https://github.com/influxdata/influxdb/pull/20819
If the value of a single stat with a threshold is negative, it clamps the color value to the nearest positive value, which will be the lowest value for thresholds.

fix: single stats with thresholds won't crash with negative values

---

src/resources/reducers/helpers.test.ts
src/resources/reducers/helpers.ts
src/variables/actions/thunks.ts

Closes #18483
This PR addresses the variables zombie issue mentioned in the above ticket. When a template linked to variables is deleted, associated variables will be removed as well.

fix: variables show after deletion

---

src/shared/components/CSVExportButton.tsx

What is chronograf? This renames the downloaded csv file to be `<date>_influxdb_data.csv`

fix(csvexport): rename downloaded file to influxdb

---

src/buckets/components/context/csvUploaderProvider.tsx
src/buckets/components/csvUploader/CsvUploaderWizard.tsx

Closes #544 
Allows user to cancel csv upload. Clicking cancel will cancel any pending network requests.
https://user-images.githubusercontent.com/6411855/109711454-c0147400-7b53-11eb-8644-d66644b55e55.mov

feat: cancellable csv upload

---

assets/index.html
src/me/components/DashboardsList.tsx
src/me/components/Docs.tsx
src/me/components/Resources.tsx
src/me/components/Support.tsx
src/shared/components/VersionInfo.scss

Closes #520
Improves lighthouse accessibility, best practices, and SEO scores by:
1) changing font color of a couple headers to improve contrast
1) adding `lang="en"` to our index.html
1) adding a meta description to our html (used the meta description for influxdata.com)
1) adding `rel="noopener"` to external links
1) changed h4s to h2s with smaller font 
Also see this clockface PR: https://github.com/influxdata/clockface/pull/581

chore: improve lighthouse accessibility and practices score

---

cypress/e2e/shared/explorer.test.ts
src/cells/actions/thunks.ts
src/dataExplorer/components/DashboardsDropdown.tsx
src/dataExplorer/components/SaveAsCellForm.tsx
src/timeMachine/actions/index.ts
src/timeMachine/components/Queries.tsx
src/timeMachine/reducers/index.ts

Closes #617 
Under the changes proposed in this PR, saving a query as a dashboard cell will redirect to the dashboard with the cell after saving it. If multiple dashboards are chosen, it will navigate to the last dashboard saved to. When returning to the query builder, it will now be reset.

fix: saving a query shouldnt leave query state around

---

cypress/e2e/shared/dashboardsView.test.ts
src/variables/actions/thunks.ts
src/variables/selectors/index.tsx

Closes #18828
The variable hydration process included improper filtering of redux state and the "selected" value was being set to the default or first available option when selecting parent variables, making the dependent variable selection break. This PR introduces a potential fix.

fix: variable dependents function properly

---

src/visualization/utils/getFormatter.ts
src/visualization/utils/timeFormat.ts

Closes #768 
This fix is the first step in updating time formats. The next step is to implement https://github.com/influxdata/ui/issues/770
- 'HH' triggers 24 hour clock format
- Add more choices to allow users to keep 12 hour formats
- Add meridiem to 12 hour formats

fix: respect 24 hour clock formats and allow more choices

---

.prettierignore

I've run into crazy git hell issues due to inconsistent case of files. This is to keep the case consistent with what we have in source control, which is `.github`. https://github.com/influxdata/ui/tree/master/.github

chore: fix case of prettierignore to match source control

---

src/annotations/actions/creators.ts
src/annotations/components/controlBar/AnnotationsControlBar.tsx
src/annotations/reducers/index.test.ts
src/annotations/reducers/index.ts
src/annotations/selectors/index.ts
src/dashboards/components/DashboardPage.tsx
src/visualization/types/Graph/view.tsx

Closes #730
Closes #725 
adds a toggle/checkbox button to the annotations bar, to enable 1-click annotations (double click still works too; since a double click has a single click in it)
annotations can only be written when the toggle is enabled.

feat: annotation write mode toggle

---

src/visualization/types/Table/Table.tsx

Follow-up to #768 just for Tables, because Tables are weird and try to do their own thing. We will not stand for this.

fix: update Tables to get the time formatter like every other graph type

---

src/flows/components/Flow.tsx
src/flows/components/FlowPage.tsx
src/flows/components/header/Submit.tsx
src/flows/components/header/TimeRangeDropdown.tsx
src/flows/components/header/index.tsx
src/flows/context/flow.query.tsx
src/flows/context/pipe.tsx
src/flows/context/query.tsx
src/flows/pipes/MetricSelector/AggregateWindowSelector.tsx
src/flows/pipes/QueryBuilder/context.tsx
src/flows/pipes/ToBucket/ExportTaskButton.tsx
src/flows/pipes/Visualization/ExportDashboardOverlay/Visualization.tsx
src/flows/shared/ResizerHeader.tsx
src/shared/utils/getMinDurationFromAST.ts

The query context that exists in flows was way too coupled with the generateMap pipeline. Took some time this morning to decouple those concepts. This also consolidates all AST node manipulation for this query path to a single file in order to keep that craziness contained. There might be some more work to do there, but less than before.
Hopefully we can move the caching layer stuff into this context as well, to help detangle that bit from time machine and allow all interfaces to use it effectively.
This also brought up the fact that any variables will be set to the selection you made at the last dashboard you visited. There's no current plans on supporting that interface on a notebook yet, just a fun fact that might bite us later.
closes #543

feat: standalone query context

---

src/timeMachine/selectors/index.ts

Closes #789 
Save the correct column. Duh! Otherwise Mosaic won't render in Dashboard cells.

fix: save the correct column to allow Mosaic cells to render in Dashboards

---

src/annotations/components/AnnotationsToggleButton.tsx

Closes #793 
The Annotation toggle button on-hover message was wrong as described in #793. This PR fixes it. 
Screen shots:

fix: annotation toggle button message fixed

---

src/shared/components/graph_tips/GraphTips.tsx

Closes #760 
explanation of Single Click mechanics added to the Graph Tips overlay, only visible when feature flag is enabled.

feat: graph tips shows annotation tip if feature flag enabled

---

src/timeMachine/apis/queryBuilder.ts

fix: escape the text from tag selectors before using as RegEx

---

src/writeData/components/clientLibraries/Java.md
src/writeData/components/clientLibraries/Kotlin.md
src/writeData/components/clientLibraries/Scala.md
src/writeData/components/clientLibraries/Swift.md

Closes #795
Related to https://github.com/influxdata/influxdb-client-swift/pull/25
The API of client was slightly changed, this PR reflects this changes:

docs(clientLibs): updated Swift examples to reflect actual version of client

---

package.json

I added a shortcut to package.json to run the e2e cypress tests with baseURL and password set to what it needs to be to run against a local KinD cluster. 
This change is accompanied by changes to documentation that is coming up!

feat(ui-e2e): Add package.json shortcut to run e2e cypress tests against KinD

---

src/annotations/components/AnnotationsControlBarToggleButton.tsx
src/dashboards/components/DashboardHeader.tsx
src/dataExplorer/components/DataExplorerPage.tsx
src/visualization/types/Graph/view.tsx

Closes #819
`AnnotationsToggleButton` is now refactored to be named `AnnotationsControlBarToggleButton` and it is only responsible for toggling the visibility of the control bar. 
--
Comment for future reference:
Should we add a toggle to hide / show annotations inside the control bar? It would be nice to be able to disable/enable the visibility of the annotations without having to 'x' out the streams in the control bar.
Also, not sure if this was intended but the annotations toggle does nothing in the data-explorer page. The control bar is always visible regardless.
--

feat: annotationsControlBarButton only controls the control bar

---

src/authorizations/components/GenerateTokenDropdown.tsx
src/writeData/components/WriteDataDetailsContext.tsx
src/writeData/components/WriteDataDetailsView.scss
src/writeData/components/WriteDataHelperBuckets.tsx
src/writeData/components/WriteDataHelperTokens.test.tsx
src/writeData/components/WriteDataHelperTokens.tsx

Closes #598 
This PR introduces the ability to create a bucket and/or a token in the client libraries page. Previously, the page would display an empty list and the user would be forced to go to the tokens/buckets overlays in their respective tabs and create them, then navigate back to the current page.

feat: create bucket and token from client lib page

---

src/shared/components/DefaultErrorMessage.tsx

Clicking on the link to create a bug from the error boundary created a bug with a non descriptive hash in the title. This puts it back to the way it used to be. It keeps the hash in the url, but it's not possible to do anything with it, yet.

fix: default error message new github issue no longer puts hash as bug title

---

cypress/e2e/shared/checks.test.ts
src/timeMachine/actions/index.ts
src/timeMachine/components/RawDataToggle.tsx
src/timeMachine/components/Vis.tsx
src/timeMachine/reducers/index.ts
src/visualization/components/View.tsx
src/visualization/types/Check/view.tsx

Closes https://github.com/influxdata/idpe/issues/9590
Deadman checks should render the raw data view for non-numeric fields rather than showing an error message.
https://user-images.githubusercontent.com/6411855/110879006-13dc3700-8291-11eb-8743-0153f77927e7.mov
Test changes pass IDPE CI ✅

fix: deadman checks render table for non-numeric fields

---

src/visualization/types/Table/TableCell.tsx

Closes #815 
Follow-up to https://github.com/influxdata/ui/pull/780 - don't format the time column headers

fix: prevent time field names from being formatted

---

webpack.dev.ts

InfluxDB OSS switched it's default port to 8086 when it went GA.

fix: update default webpack port

---

src/style/chronograf.scss
src/tasks/components/TaskCard.tsx
src/tasks/components/TaskCardMeta.scss
src/tasks/components/TaskCardMeta.tsx

Closes https://github.com/influxdata/ui/issues/660
adds the task id to the task list page for easy copying. same code as the buckets page.

feat: adding task ids to the list page

---

package.json
src/flows/shared/Resizer.scss
src/flows/shared/ResizerHeader.tsx
yarn.lock

Update resize results pane icon to "DragToExpand" and updates clockface to 2.6.3
https://user-images.githubusercontent.com/6411855/111200476-0a97e680-857f-11eb-8fb0-f562a1df575a.mov

feat: update resize icon for notebooks

---

.github/pull_request_template.md

Adds a check for k8s-idpe test passing and removes redundant checkboxes from the template. Github won't let you merge the PR without a semantic PR title and commit messages, mergeable code, and passing tests.
Old:
New:

docs: adds check for k8s-idpe tests passing

---

package.json
yarn.lock

Lodash 4.17.20 has 2 identified vulnerabilities that are resolved in x.x.21. This should also improve our lighthouse "best practices" score.
https://snyk.io/vuln/npm:lodash?lh=4.17.20&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

chore: update lodash to avoid vulnerability

---

cypress/e2e/shared/checks.test.ts
src/checks/components/CheckHistory.scss
src/checks/components/CheckHistoryVisualization.tsx

Closes influxdata/idpe#9590
Deadman checks with non-numeric values should render the raw data table on the check history page instead of the line chart.

fix: non-numeric checks should render table on history page

---

src/annotations/components/controlBar/AnnotationsControlBar.tsx

Connects #728
Adds a quick example call to `event` for annotations

feat: add metrics call to annotations change write mode

---

src/perf/components/CellEvent.tsx
src/shared/components/RefreshingView.tsx

summary:  restored CellEvent.tsx from the grave and put it back into RefreshingView.  
<hr>
details:
restored CellEvent component; via git:
```
jill@jills-mbp ui % git co 9a6185cdca57b6bc90d125d0fc21557ba4b52e36~1 src/perf/components/CellEvent.tsx
Updated 1 path from 55cdf267d
```
put it back into RefreshingView, this time paired with the View (was the ViewSwitcher before the big refactor by @drdelambre )
here is what the old RefreshingView used to look like:
(the render method)
```
<>
<ViewLoadingSpinner loading={loading} />
<EmptyQueryView
errorFormat={ErrorFormat.Scroll}
errorMessage={errorMessage}
hasResults={checkResultsLength(giraffeResult)}
loading={loading}
isInitialFetch={isInitialFetch}
queries={this.queries}
fallbackNote={this.fallbackNote}
>
<>
<CellEvent id={id} …
```

fix: restoring CellEvent performance metrics (Cell Render Cycle)

---

src/dashboards/components/variablesControlBar/DraggableDropdown.tsx
src/variables/components/TypeAheadVariableDropdown.tsx

it was removed when the clockface 2.4.1 upgrade had bugs so had to be reverted
was: Revert "fix: revert to clockface 2.4.1 (#735)"
This reverts part of the commit 4f75c2c42a854974d3ead4dd87fb6fe0ffd2b941.
(the type-ahead dropdown, that is)

feat: re-applying the typeahead dropdown

---

.circleci/config.yml

Adds additional environment variables to `make lhr` command in circle config.
Checkout this monitor-ci PR: https://github.com/influxdata/monitor-ci/pull/186

chore: send lighthouse scores to tools

---

src/visualization/types/Graph/view.tsx

feat: add metrics to annotations rendering code

---

cypress/e2e/shared/dashboardsView.test.ts
cypress/support/commands.ts
src/shared/components/RefreshingView.tsx
src/shared/components/cells/Cell.tsx
src/shared/components/cells/CellContext.tsx

Closes #
This PR introduces the ability to refresh a single dashboard cell, as opposed to the old behavior of having to refresh the entire dashboard. This should allow users to use up less queries.

feat: single cell dashboard refresh

---

cypress/e2e/cloud/flows.test.ts
src/flows/components/panel/Results.tsx
src/flows/context/flow.list.tsx
src/flows/context/pipe.tsx
src/flows/pipes/MetricSelector/FieldSelectors.tsx
src/flows/pipes/MetricSelector/FilterTags.tsx
src/flows/pipes/MetricSelector/MeasurementSelectors.tsx
src/flows/pipes/MetricSelector/TagSelectors.tsx
src/visualization/types/Graph/view.tsx

Closes #890
- Fixes issue where results table doesn't show results from latest query due to memoization
- Fixes issue where visualization panel shows "an error has occurred" after executing some queries due to recent annotations changes to time machine
- Fixes issue where multiple list items in metric selector had the same key
- Adds e2e test for metric selector
- Adds testIDs to some components to make testing easier

fix: various bug fixes in notebooks

---

src/buckets/components/context/csvUploaderProvider.tsx
src/buckets/components/csvUploader/CsvUploaderBody.tsx
src/buckets/components/csvUploader/CsvUploaderHelperText.tsx
src/buckets/components/csvUploader/CsvUploaderWizard.tsx

This PR adds a link to the docs to describe what Annotation CSV format is. It also differentiates between actual errors and abort & incorrectly formatted CSV errors to reduce HB noise. Lastly, it adds events in places so we can get an idea of how people are using the uploader
Closes #893

chore: updated the CSV uploader to have helpful links to annotation docs, added eventing and removed HB notifications for most errors

---

.eslintrc.js
src/visualization/types/SimpleTable/PagedTable.tsx

TypeScript is complaining about ResizeObserver in `PagedTable`. This is a suggested fix from [this thread.](https://github.com/Microsoft/TypeScript/issues/28502#issuecomment-739996219)

fix: add reference to ResizeObserver for typescript

---

src/shared/components/CloudUpgradeButton.tsx
src/shared/components/CloudUpgradeNavBanner.tsx
src/shared/constants/index.ts

Closes #944 
This PR is a brief workaround until we can address the core issues for #930. As such, it's a hack to allow a beta region to be deployed today without needing to develop proper infrastructure for the core issue.

feat: add exception for beta region deployment on upgrade now

---

src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx
src/dataLoaders/components/collectorsWizard/select/StreamingSelector.test.tsx
src/dataLoaders/components/collectorsWizard/select/StreamingSelector.tsx

Closes #948 
Under this PR, if a user has no buckets the overlay will now prompt the user to create a bucket. When they do, they will then be able to see the regular overlay as was intended.

fix: telegraf no buckets overlay now works

---

src/annotations/actions/creators.ts
src/annotations/components/controlBar/AnnotationsControlBar.test.tsx
src/annotations/components/controlBar/AnnotationsControlBar.tsx
src/annotations/reducers/index.test.ts
src/annotations/reducers/index.ts
src/annotations/selectors/index.ts
src/shared/containers/SetOrg.tsx
src/visualization/types/Graph/view.tsx

Closes #901
Removes the following parts from the UI:
- streams search bar (far left arrow)
- gear icon that takes you to the streams homepage (far right arrow)
- also removed the route to this page
- Adds the `Show Annotations` toggle (middle arrow)
Considerations: show / hide annotations isn't saveable, so on page reload, they'll revert back to default

chore: remove references to streams

---

cypress/e2e/shared/explorer.test.ts
cypress/e2e/shared/variables.test.ts
cypress/support/commands.ts
mocks/dummyData.ts
package.json
src/variables/components/RenameVariableForm.tsx
src/variables/components/VariableCard.tsx
src/variables/components/VariableForm.tsx
src/variables/components/VariableFormContext.test.tsx
src/variables/components/VariableList.tsx
src/variables/components/VariablesTab.test.tsx
src/variables/utils/validation.ts
yarn.lock

Closes #611 
Help the user create proper names for variables so that Flux does not complain with squiggly lines in the Script Editor. We do this in two ways:
- validate the variable names when manually creating or renaming
- flag the variables on the Variables tab (in Settings) that have bad names to let the user know to rename them

fix: validate variables and flag when renaming is required

---

.github/pull_request_template.md

We're running the e2e tests via k8s-idpe in our CI now so we don't need this manual step in our pull template anymore.

docs: remove k8s-idpe checkbox

---

src/shared/copy/notifications.ts
src/shared/reducers/notifications.ts
src/timeMachine/actions/queryBuilderThunks.ts

Closes #25 
This PR introduces a toast when a user attempts to deselect the only remaining custom aggregate function, as this is a prohibited action and users have mentioned that it feels like a bug without some sort of message clarifying its intended. 
This also addresses something i noticed when working with toasts - the notification is prevented from being duplicated if the type is the same, but not if the message is the same, and it was allowing the notifications for the deselection prohibition to be duplicated. I added a check to ensure we aren't showing a duplicate message, but i'm curious if there was a reason i've failed to see as to why the check was specifically only on type and nothing else. If the reviewer can clarify, i'd appreciate it!

fix: custom aggregate deselection prohibition toast

---

package.json
src/shared/utils/vis.test.ts
src/shared/utils/vis.ts
src/visualization/types/Map/view.tsx
yarn.lock

Closes #963 
Maps in Data Explorer breaks if the user provides lat lon data without `s2_cell_id`. This change is so that our check if coordinates exist is no longer dependent on `s2_cell_id`.

fix: map getLatLon function returns correct error

---

src/annotations/api/index.test.ts
src/annotations/api/index.ts
src/annotations/components/AnnotationsControlBarToggleButton.tsx

Closes #985
Closes #728 
- Sends `content-type` header of `application/json`
- Finishes last metrics call on annotations control bar toggle

chore: annotations requests send proper content-type header

---

package.json
src/annotations/components/EditAnnotationForm.tsx
src/shared/copy/notifications.ts
src/visualization/types/Graph/view.tsx
yarn.lock

Closes #896
Closes #374 
This PR connects the upside-down triangle annotation pin introduced in https://github.com/influxdata/giraffe/pull/511 to the edit/delete modal https://github.com/influxdata/ui/pull/976.

feat: connect pin target on annotation to the edit/delete modal

---

src/flows/components/FlowsIndexEmpty.tsx

Closes #984 
Adds missing CSS import so we don't have to wait for the user to create a new notebook for the stylesheet to be imported.

fix: add missing css import

---

src/annotations/components/controlBar/AnnotationsControlBar.test.tsx
src/annotations/components/controlBar/AnnotationsControlBar.tsx
src/annotations/reducers/index.test.ts
src/annotations/reducers/index.ts

- annotation write mode is toggled off by default
- shows a message saying we only support annotations on XY graphs

chore: make annotation mode off by default, add note explaining xy plots only

---

src/visualization/types/Map/GeoOptions.tsx

Closes #1001 
Upon testing in Tools, I came across an issue, where the circle and heat maps are not loading the data points in map. Turns out my change in giraffe pr has broken this since the columns/tag values are pivoted and changed to `lat` and `lon`. So, updating the fields used in the options fixed this issue.

fix: circle and heatmap options

---

package.json
yarn.lock

Update giraffe's version to `2.7.1`. This allows us to use the latest fixes for the Annotation Click target from Giraffe.
closes: #1014

fix: bump up giraffe to 2.7.1

---

.circleci/config.yml

Push the built ui-e2e image to quay tagged with the current commit. Then pass the image name and commit tag to k8s-idpe via env var `UI_E2E_TESTS_IMAGE` so it can be used for testing.
See related k8s-idpe PR: https://github.com/influxdata/k8s-idpe/pull/2736

chore: push ui-e2e image to quay tagged with commit

---

package.json
yarn.lock

Closes #
chore: update clockface to 2.6.7 from 2.6.6

chore: update clockface

---

src/dashboards/components/DashboardPage.tsx

I'm able to reproduce the error in #1018 by doing the following:
1. clearing my localStorage in the browser console: `localStorage.clear()`
2. going to `src/userSettings/reducers/index.ts` and commenting out code that adds the new `showAnnotationsControl` key to the local storage.
3. reload the dashboard, it won't load. The screen displays a similar error, the console has a React Invariant Violation error as well.
Why it's happening?
I hypothesize: We have a variable that controls the visibility of the AnnotationContolBar, the variable's state is stored in the redux. When we shipped Annotation to our new users, the new key wasn't present in their localStorage, hence the value of the `AnnotationsControlBar`'s visibility variable was `undefined`, not `false`. Using a default `false` when …

fix: prevent DashboardPage from crashing due to the lack of updated redux store keys

---

cypress.json

Closes https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/cloud-2-cypress/19

feat: enable chrome web security for e2e testing.

---

src/shared/components/RefreshingView.tsx
src/visualization/components/View.tsx
src/visualization/index.ts

Closes #1041 
We need to pass in the `cellID` down to the XYplot graphs so we can use them in the new annotations architecture where their scope will be limited by `cellID`

feat: pass cellID from RefreshingView.tsx all the way down to view 

---

cypress.json

Enabling this flag works with monitor-ci but _not_ for k8s-idpe. Gotta turn it off for now.

chore: disable chrome security

---

cypress/e2e/shared/dashboardsView.test.ts
src/variables/components/TypeAheadVariableDropdown.test.tsx
src/variables/components/TypeAheadVariableDropdown.tsx

Closes #21020 in influxdb
https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/21020
addressing bucky's comments
the arrow buttons do NOT select the next one, they just hover like a mouse would; selection happens on return
if you type in a matching valid selection and press return, that selects the value as well
dependent variables now re-load correctly
added unit tests
added e2e tests
still testing original variable dropdown too

fix: type ahead drop down fixes

---

src/dashboards/components/DashboardPage.tsx

Closes #1051
Don't make GET requests to annotations if the flag is off

fix: flag the GET request to annotations

---

cypress.json
src/tasks/components/TaskRunsPage.tsx
src/tasks/components/TaskRunsRow.tsx

Closes #1055
We want to add a dropdown that allows the user to choose a time zone for time display in the task runs page. This is what it looks like:
https://user-images.githubusercontent.com/18511823/113243464-ec610480-9267-11eb-8285-527db61afaf5.mov

feat: add UTC/Local time dropdown to Task Runs page.

---

src/Signin.tsx
src/shared/constants/index.ts

Closes #1057 
This PR integrates the redirect to login functionality when a cloud user fails the `/me` call. With session sharing allowing for access to both platforms, we want to avoid making a silent request to Auth0 (which is currently done by the `/signin` endpoint). By redirecting the user to the `/login` page, we ensure that the `/signin` endpoint will not be hit and that the user will end up in a state where they can then login to the app

feat: complete redirect cycle to login and avoid the signin page

---

cypress/e2e/shared/tasks.test.ts
src/tasks/actions/thunks.ts

Closes #883 
This PR adds clone naming conventions to tasks.

feat: added clone naming for tasks

---

src/annotations/reducers/index.test.ts
src/annotations/reducers/index.ts
src/visualization/types/Graph/view.tsx

Closes #1074
Makes the annotation lines green instead of red.
The great honeydewing of 2021 is upon us!

chore: change annotations color from red to green

---

src/flows/components/panel/Results.tsx
src/timeMachine/components/Vis.tsx
src/visualization/types/SimpleTable/PagedTable.tsx
src/visualization/types/SimpleTable/index.tsx
src/visualization/types/SimpleTable/style.scss
src/visualization/types/SimpleTable/view.tsx

Closes #1011 
moves the page interface to the bottom of the interaction at the request of design
also stops filtering of the _start and _stop columns... in data explorer

fix: simple data tweaks

---

src/visualization/types/Graph/view.tsx

Closes #1085
In the view.tsx, `annotations` weren't being checked if they were empty, this caused it to crash when the XY plot was in a notebook context and no annotations were passed in. 
It didn't make sense to me why it didn't happen in the data-explorer, we use XY plot there as well. Did a little digging and found that this is because annotations were shown in data explorer prior to us constraining it to a dashboard-cell. This meant that an empty array was being passed here: [Vis.tsx/L59](https://github.com/influxdata/ui/blob/c03ce296402acd8419d361c0e0835c469cf4ffeb/src/timeMachine/components/Vis.tsx#L59) and not an `undefined` as in the context of the notebooks. 
This raises another point, should we remove annotation code from the data-explorer visualization code? 
Here is the …

fix: prevent annotations crashing XY plot when annotations aren't passed

---

src/visualization/types/Graph/view.tsx

The last fix in #1088 did stop the plot crash when no annotation were passed but it wasn't rendering any because the array was being accessed as if it was an object. this will fix it.

fix: fixed the array access method for annotations in view.tsx

---

src/tasks/actions/thunks.ts
src/tasks/components/TaskCard.tsx
src/tasks/components/TaskRunsPage.tsx

Closes #724 
This PR will redirect a user to the run tasks page if their scheduled task run is successful, otherwise it will simply notify the user that the task scheduling error message

feat: redirect after running the task

---

src/alerting/components/AlertHistoryIndex.tsx
src/checks/components/CheckHistory.tsx

noticed these pages didn't use the standard pageTitleSuffixer function

fix: update page titles

---

src/annotations/reducers/index.ts

Closes #1103
Deleting an annotation in one dashboard cell would cause other annotations to disappear

fix: don't disappear all annotations on delete

---

.circleci/config.yml

I'm tired of the emails from circle. Turning this off while I'm working on a solution to move these tests into a private repo/circle.
Related: https://github.com/influxdata/ui/issues/1112

chore: turn off k8s-idpe tests

---

src/tasks/components/TaskRunsList.tsx
src/tasks/constants/index.ts

We fetch 100 task runs from the API (https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetTasksIDRuns), then only show 20 of them for some reason. this updates to show all 100 task runs if they are available.

feat: display more task runs on the page

---

src/timeMachine/components/SelectorList.tsx

Closes #1094 
We need to scroll to the selected item in the selector list for the query builder so that when long list of buckets are present, it is obvious what bucket is currently selected.
Video in action:
https://user-images.githubusercontent.com/18511823/113468655-4f83a000-93fc-11eb-9d70-121547071a62.mov

fix: scroll the SelectorList to the selected bucket

---

cypress/e2e/cloud/geoOptions.test.ts
src/visualization/types/Map/GeoOptions.tsx

Closes #1005 
Closes #1061  
This PR hides the customization options behind a flag that currently is set to false (its just a variable that we can remove when we work on these again) and shows the message listed in #1061.

fix: remove geo options behind static flag and add message

---

src/timeMachine/components/Vis.tsx
src/timeMachine/selectors/index.ts
src/visualization/types/Graph/view.tsx

Closes #1091
We want to disable on-click-to-add-annotation behavior in the data explorer because it doesn't make sense anymore. We also  want to show the annotations in the VEO, the popover that lets you edit queries. 
This PR does that. Screen recording:
https://user-images.githubusercontent.com/18511823/113462506-13d5df80-93d6-11eb-9ab6-84982ff2c04d.mov

fix: disable writing annotation in dataExplorer

---

src/dashboards/components/variablesControlBar/VariablesControlBar.tsx
src/dashboards/components/variablesControlBar/VariablesControlBarList.tsx
src/shared/copy/notifications.ts
src/types/variables.ts
src/variables/actions/thunks.ts
src/variables/selectors/index.tsx

Closes #667
This PR connects with the backend change that introduces a `sort_order` property on variables. This allows us to save the order when they are moved in the control bar and display them in the correct order once they are saved, or otherwise show an error notification and snap them back to match the API order.

feat: variables reorder drag and drop saves through logout

---

src/dashboards/components/DashboardsCardGrid.scss

Closes #1070 
Fixes the boundary issue for dashboard names

fix: css for dashboard max name width

---

src/flows/pipes/Visualization/Controls.tsx
src/flows/pipes/Visualization/index.ts

part of #1083 
not all visualizations work well with aggregate window. while we map those out.. at least allow the user to opt out of the functionality

fix: allow the user to run a visualization without aggregate window

---

src/annotations/components/EditAnnotationForm.tsx

Closes #1123
Make the app useable again. Change label from `Summary` to `Message`

chore(annotations): change edit label from summary to message

---

src/functions/components/FunctionResponse.tsx

When managed function responses were large, the panel would enlarge to contain them. 
I gave a max width to panel, and scrolling.

feat(managed-functions): Add styles to functions response

---

cypress/e2e/cloud/checkout.test.ts
src/client/swagger/unity.yml
src/index.tsx
src/me/actions/creators/index.ts
src/me/actions/thunks/index.ts
src/me/mockUserData.ts
src/me/reducers/index.ts
src/operator/OperatorNav.tsx
src/operator/OperatorTabs.tsx
src/operator/OrgOverlay.tsx
src/operator/ResourcesTable.tsx
src/operator/api/index.ts
src/operator/constants.tsx
src/operator/context/operator.tsx
src/shared/containers/GetOrganizations.tsx
src/utils/api.ts

This PR addresses a couple of nagging UI issues that are lingering around the `/me` endpoint, namely that:
- the checkout & operator page should be authenticated routes
- the checkout & operator page should only be accessible with specific credentials
- the yml file had some potentially cyclical dependencies between orgs and accounts that were simplified by flattening account props onto the org
This PR does not address:
- Adding conditional rendering logic for the `upgrade now` button with meta data that should be available with the `/me` endpoint

chore: Clean up unity.yml to remove circular dependencies

---

src/shared/copy/notifications.ts
src/variables/actions/thunks.ts

Closes #1093
Shows an error message when the value for the variable name, provided as part of the query URL in the dashboard, doesn't exist.
Video :
https://user-images.githubusercontent.com/18511823/113470865-77c7ca80-940d-11eb-9e67-0226d220eafc.mov

fix: show error message when value for a variable name does not exist in dashboard queryURL

---

src/visualization/types/SingleStat/view.tsx
src/visualization/types/SingleStatWithLine/view.tsx

Closes #https://github.com/influxdata/influxdb/issues/18837
Our current single stat graph and single stat with line would show a time value dataType as epoch time but the numerical value. This PR enables it to display a much more user-friendly string representation of time in the globally configured timeZone.
**The code has been updated in the UI to display time in the timeFormat, now how do we fix it in the giraffe, is the current question.** 
Screen shots:
respects the timezone selector: 
for singleStatWithLine:

feat: display time as formatted value in single stat graph

---

src/external/monaco.python.syntax.ts
src/external/monaco.python.theme.ts
src/external/python.tmLanguage.json
src/functions/components/FunctionEditPage.tsx
src/functions/components/PythonMonacoEditor.tsx

Partially closes #9788
I added a basic grammar and syntax for python. 
I'm just coloring comments, and strings for now, but..... more should be possible.

feat(managed-functions): Add python editor grammar & syntax to monaco

---

src/client/swagger/unity.yml
src/shared/containers/GetOrganizations.tsx
src/utils/api.ts

This PR updates the new `/me` endpoint that's currently being built out. More specifically this PR replaces the entire `account` type that was being returned by the `/me` endpoint to a more narrow `accountType` that is the enum of possible account types associated with an account. The reason being that the UI has no need for all of the account information, just the type of account

chore: update the expected me endpoint

---

src/dashboards/components/dashboard_index/DashboardsIndex.tsx
src/dashboards/components/dashboard_index/DashboardsTableEmpty.tsx
src/shared/components/AddResourceDropdown.tsx
src/shared/constants/index.ts
src/tasks/components/EmptyTasksList.tsx
src/tasks/components/TasksHeader.tsx

Closes #1164
I forgot to remove the buttons for import task from template while removing the underlying code

fix: remove the buttons "import task from template"

---

cypress/e2e/shared/explorer.test.ts

Removes flakiness with variables in cypress explorer.test

test: pre-visit the save-as-variable tab to prevent flakiness

---

package.json
yarn.lock

Issue https://github.com/influxdata/idpe/issues/10138
Removes `acorn` from dev dependency list. It's not used anywhere and it's out of date with a vulnerability: https://github.com/influxdata/ui/pull/1140

chore: remove unused acorn package

---

src/shared/components/views/MarkdownRenderer.tsx

Closes #1194
Updated the `ReactMarkdown` component to pass the prop `renderers` along in the not-cloud case so that the placeholders in the code previews get interpolated with the actual values.

fix: code samples for client libraries in OSS show correctly

---

src/visualization/types/Gauge/Gauge.tsx

Closes https://github.com/influxdata/ui/issues/1177
The UI implementation had a minor bug that led to the needle fall below zero when the gauge value was 0. This PR fixes that.
Screenshot Before vs After
<div>
</div>
Of gaugePosition being below minValue:

fix: gauge needle at zero when value is zero

---

src/visualization/types/Table/properties.ts

Closes #1190
the default table view property was missing a required option that was handled by the default redux populator over in data explorer. no clue why typescript didn't catch this or why it hasn't come up since the visualization refactor, but this fixes it none the less

fix: bring tables alive in notebooks

---

package.json
src/shared/utils/vis.test.ts
src/shared/utils/vis.ts
src/views/helpers/index.ts
src/visualization/types/Map/view.tsx
yarn.lock

Closes #997 Closes #giraffe/523
Updated the function to get Lat Lon such that it will not render giraffe plot if the correct data is not provided. Added a condition to get `s2_cell_id` or `lat`/`lon` as fields/tags and throw an error if none of those exist in the data provided

fix: maps getting lat/lon from s2_cell_id or fields/tags

---

package.json
yarn.lock

Brings in the latest changes from Giraffe for the Annotation tooltip positioning, released in the [v2.7.5](https://github.com/influxdata/giraffe/releases/tag/v2.7.5)
closes #1121

chore: update giraffe to v2.7.5

---

cypress/e2e/cloud/annotations.test.ts
package.json
yarn.lock

Closes #1206
Brings in the change from the Giraffe [v2.7.6](https://github.com/influxdata/giraffe/releases/tag/v2.7.6) release to make annotations less intrusive on the plot with a smaller caret and a dashed line.

chore: update giraffe to v2.7.6

---

src/annotations/components/EditAnnotationForm.tsx
src/annotations/components/EditAnnotationOverlay.tsx
src/visualization/types/Graph/view.tsx

Closes #1211
Adds the following four events:
```
xyplot.annotations.edit_annotation.success
xyplot.annotations.edit_annotation.failure
xyplot.annotations.delete_annotation.success
xyplot.annotations.delete_annotation.failure
```
Removes extra create event that was called twice.

chore: add events for edit and delete; remove double-fired event

---

scripts/run-monitor-ci-tests.bash

Printing the url of each artifact is annoying since they can be seen in the Artifacts tab. This will just print the number of artifacts downloaded for each failed job instead.

chore: remove printing of each artifact url

---

src/client/swagger/unity.yml

Adds a cancellation route to the swagger for cancelling an account.

feat(unity): add cancel route to swagger

---

cypress/fixtures/view.json
mocks/dummyData.ts
src/cloud/constants/websiteMonitoringTemplate.ts
src/flows/pipes/TestFlux/index.ts
src/mockAppState.tsx
src/shared/utils/mocks/resourceToTemplate.ts
src/shared/utils/resourceToTemplate.test.ts
src/types/dashboards.ts
src/usage/GraphTypeSwitcher.tsx
src/views/helpers/index.ts
src/visualization/types/Band/properties.ts
src/visualization/types/Check/properties.ts
src/visualization/types/Gauge/properties.ts
src/visualization/types/Graph/properties.ts
src/visualization/types/SingleStat/properties.ts
src/visualization/types/SingleStatWithLine/properties.ts

Follow-up on https://github.com/influxdata/influxdb/issues/21154
Remove "Legend" which is not yet a thing in the UI. This will become the "Static Legend" in the near future.

fix: remove unused "Legend" to match updated swagger

---

src/App.tsx
src/cloud/components/onboarding/EngagementLink.tsx

This PR adds a component to App.tsx which sends user/org identifiers to Userpilot. This first stage only sends email, orgID, region, and provider to create records and dynamically build URLs in Userpilot. Future changes will send engagement state and other useful data for segmentation and displaying the correct onboarding experience.

feat: send identiers to userpilot onboarding tool

---

package.json
src/telegrafs/components/TelegrafExplainer.tsx
src/types/queries.ts
yarn.lock

Ran `yarn-deduplicate yarn.lock`
[yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) removes duplicate dependencies from our yarn.lock. This should reduce the number of packages we are pulling down.
Old yarn file number of lines:  **12880**
New yarn file number of lines: **12032** (-848 lines!)
Don't even try to expand the yarn.lock file differences in your browser - it'll crash Chrome lol.
I want to do this before upgrading a bunch of dependencies to fix vulnerabilities. Otherwise it's possible these dependencies will stick around since they are duplicated.
Other changes that were required as a result of the deduplication:
- Fixes improper usage of TextAlignProperty and csstype package
- Fixes incorrect null type on `upper` in `TimeRange` interface. It is now a nullable …

chore: de-dupe yarn.lock

---

.circleci/config.yml

Lots of pipelines have been failing because it's taking >10min to install npm packages when building the UI image. Circle kills all jobs that haven't produced output after 10min. I'm increasing that timeout to 15min
Example: https://app.circleci.com/pipelines/github/influxdata/ui/3887/workflows/97789f84-ee33-452d-b87f-ec6970295d65/jobs/30727

chore: increase build image timeout

---

cypress/e2e/cloud/billing.test.ts
cypress/e2e/cloud/checkout.test.ts
cypress/e2e/cloud/usage.test.ts
cypress/e2e/cloud/users.test.ts
src/pageLayout/components/UserWidget.tsx
src/shared/containers/GetOrganizations.tsx
src/shared/containers/SetOrg.tsx

Closes #950
This PR updates the routes for the unity epic to remove a reference to the `unity-` prefix. In addition, the feature flags are updated to a camelcased version, since that is what it is currently set in config cat. Finally, the tree-nav routes are conditionally rendering the href based on whether a feature flag is set for that route or not. That is to say, the route will either direct to the local UI instance or to Quartz depending on whether the feature flag is on or off.

chore: updated route and feature flag names

---

cypress/e2e/shared/explorer.test.ts

Closes #1271
Changed the cypress selector in the `can set min or max y-axis values` test to be more specific so that the test works if the `axisTicksGenerator` flag is `true` on the backend.

fix: e2e test works with axisTicksGenerator on or off

---

cypress/e2e/cloud/annotations.test.ts
src/annotations/components/EditAnnotationForm.tsx
src/annotations/components/EditAnnotationOverlay.tsx
src/annotations/components/annotationForm/AnnotationForm.tsx
src/annotations/components/annotationForm/AnnotationMessageInput.tsx
src/annotations/components/annotationForm/AnnotationStartTimeInput.tsx
src/annotations/constants.ts

Closes #1229
- Makes the edit annotation form match the create annotation form
- Adds a live character counter showing how close you are to the 255 character limit
- Allows the form to be submitted by pressing `enter`
https://user-images.githubusercontent.com/146112/115093887-911e4b80-9ed0-11eb-96ea-d297d5facf30.mov

fix(annotations): make create and edit forms match

---

src/visualization/types/Map/view.tsx

Closes #866 #1228
When viewing maps for visualization on Notebooks/Flows, the maps weren't rendering because the properties we were sending to giraffe are the defaults (with empty layers) and not the ones we use in Data explorer.

fix: maps in notebooks

---

src/Signin.tsx
src/shared/actions/flags.ts
src/shared/containers/GetFlags.tsx
src/shared/reducers/flags.ts
src/shared/selectors/flags.ts
src/shared/thunks/flags.ts

This PR aims to integrate the pre-authenticated feature flagged routes for the UI. Yesterday, a similar PR caused our feature flags to fall apart. The reason for this was because the thunk I had developed was using the existing `getFlags` as a basis for comparison. This ended up causing an incident whereby the initial setting of the public flags was setting the status of the flags to loading, thereby bypassing the original authenticated `getFlags` request, which is only requested when the `status` of the `flags` are `RemoteDataState.NotStarted`. Since the `getFlags` were never called, the authenticated feature flags were never being set. I'd be happy to go over this in more detail and would be happy to pair with anyone who knows / can think of a way to test this out before merging it in

feat: integrated public flags without negating the getFlags condition

---

src/pageLayout/components/RenamablePageTitle.scss

Closes #918 
Before
After
Both are the same for ipad sized devices
For squished computer screen

fix: Icon pencil closer to title

---

src/annotations/components/annotationForm/AnnotationStartTimeInput.tsx

To address https://github.com/influxdata/ui/issues/1266, I propose that we make the input field behave similar to the one we have in the date picker. It adds consistency across the app. This PR introduces that.
The behavior is as follows:
The input field makes sure that the time entered is in the format: `YYYY-MM-DD HH:mm:ss.SSS`. If it isn't, it shows an error with a message that shows what the format needs to be. 
Notes for the reviewer: 
* I am using the `moment` library to achieve formatting, we're already using it for the date picker component. If that is something we want to move away from, I can explore ways to achieve it using the default `Date` library.
* I can also add the form validation behavior, i.e. the save button is only enabled when the format in the input field is valid, …

fix: improved annotation start time input behavior

---

src/visualization/types/SimpleTable/PagedTable.tsx
src/visualization/types/SimpleTable/index.tsx

Closes https://github.com/influxdata/idpe/issues/10457
simple table didn't support simple tables! rejiggered the result filtering / pagination logic to allow for multiple columns with the same name (which happens when a result set has multiple tables that have the same column name, but with a different data type)

fix: allow multiple flux types on a column name

---

src/annotations/components/EditAnnotationOverlay.tsx
src/visualization/types/Graph/view.tsx

Closes #1230 
With our current state of handling the API call, we ship the call to a `dispatch` and this caused the error handling not possible because there was no catcher when the `dispatch` (making an `async` call) threw an error.
This PR makes that try-catch an async block and makes it so that a useful error message is shown on failure.

fix: make the dispatch async; add await for create and edit annotation forms

---

cypress/e2e/cloud/annotations.test.ts

Closes https://github.com/influxdata/ui/issues/1193
When the API failed to save our annotations, our tests didn't catch it because they were not checking if the backend actually had the annotation. We add a `cy.reload()` to verify that the change happened in the backend.
To test that the test fails when the backend is down / isn't functioning desirably, just do `make stop NODE=postgres` inside the root of `monitor-ci`. This will turn off the server for annotations, and then we can verify that the test fails.

fix: reload cypress test for edit and delete annotation

---

cypress/e2e/shared/dashboardsView.test.ts
src/dashboards/components/variablesControlBar/DraggableDropdown.tsx

removes the typeahead variable dropdown flag, to always use type ahead drop downs

chore: turn on type ahead flag

---

package.json
src/visualization/types/Graph/view.tsx
yarn.lock

Closes #1265
Previously - the raw timestamp of the position of the mouse would be used for the annotation timestamp. Now the nearest clamped/rounded timestamp will be used

feat: clamp annotation's timestamp to nearest domain timestamp

---

src/shared/components/CloudUpgradeButton.tsx
src/shared/components/CloudUpgradeNavBanner.tsx
src/shared/constants/index.ts

This PR is intended to remove the hacky beta region logic that was used to write in a UI exception to showing the `upgrade now` button when a user in a beta region was navigating our site

chore: remove hacky beta region logic

---

.gitignore
package.json
src/client/swagger/notebooks.yml
src/flows/context/flow.list.tsx
src/flows/context/notebooks.api.tsx

https://github.com/influxdata/idpe/issues/9806
Adds integration with `notebooksd` behind an unofficial feature flag called `notebooks-api`.
- adds `notebooks.yml` swagger
- adds `notebooks.api.tsx` which is identical to `api.tsx` for flows, but uses `notebooks.yml` swagger
To use this flag you'll first need to enable `notebooksd` in k8s-idpe locally by flipping this flag: https://github.com/influxdata/k8s-idpe/blob/3f0b5eb24b144802b62e425caae1dfd7706993a7/env/test/local/twodotoh-dev/conf.libsonnet#L221

feat: integration with notebooksd

---

.gitignore
package.json
src/checkout/context/checkout.tsx
src/client/swagger/notebooks.yml
src/client/swagger/unity.yml
src/flows/context/flow.list.tsx
src/flows/context/notebooks.api.tsx
src/shared/components/CloudUpgradeButton.tsx
src/shared/components/CloudUpgradeNavBanner.tsx
src/shared/constants/index.ts

Updated the path and params for `payment form` to `/payment_form/{form}` to account for the two different payment forms Zuora can return, and added defined errors for `/checkout`, `/payment_form/{form}`, and `/settings/notifications`.

feat(unity): Define errors for checkout routes

---

cypress/e2e/shared/checks.test.ts
src/alerting/components/AlertingIndex.scss
src/checks/components/CheckCard.tsx
src/notifications/rules/components/RuleCard.tsx
src/shared/components/CopyResourceID.tsx
src/types/alerting.ts

Closes #1169
- Shows underlying task id on the alerts page and notification rules page.
- Removes responsive css from Alerts page. Previously at sizes of 1500+ px it would expand to three columns. Now it is always tabbed. David and I chatted and we both agreed it was way easier to use in the larger format
https://user-images.githubusercontent.com/146112/116447179-8aff6780-a80c-11eb-9eb4-ff540c6c3a9b.mov

feat: show task ids on alerts + notifications

---

src/client/swagger/managedFunctions.yml
src/functions/context/api.tsx

The `/functions/...` endpoints will be used for named functions(flux) only, until the managed functions (python) functionality is in place. This routes the UI endpoints to `api/v2/poc-functions` instead for now so that we can continue demoing managed functions until we decide to devote resources to building out managed functions

feat(functions): Route requests to api/v2/poc-functions until the api/v2/functions EP is available

---

src/Logout.tsx

This PR closes the issue where users logging out using the shared session cookie were undergoing the original logout loop. This issue presented itself because the feature flag and local storage were being reset prior to hitting the condition of checking the feature flag. As such, we are now checking to see if the flag is enabled prior to resetting it

feat: resets flags state after the URL is set

---

cypress/e2e/cloud/annotations.test.ts

This PR fixes the flaky annotations e2e tests. In #1312 we fixed one instance of the chaining issue but we still had issues. Here's why: When the test launches the bucket-measurement selection window, some elements like the measurement values only appear after selecting an element in the selector list. Our test wasn't waiting for it to appear before clicking it. Hence the failure. 
Also fixed the issue with clearing the localstorage in the afterEach block, reliably. 
I ran the tests in the circle CI 3 times, all pass with no flakes.

fix: fix e2e test chaining issues and clearing local storage

---

cypress/e2e/shared/dashboardsView.test.ts
src/shared/constants/index.ts

Closes #1248 
The default timestamp set in UI was out of sync with the default timezone set in giraffe and resulted in this behavior.  The default in UI is now the same as timeFormats.local12 in giraffe which is set as the final fallback in formatters.ts
fix verification gif:

fix: set default UI timezone to match default timezone in giraffe

---

src/buckets/components/context/csvUploader.tsx

The CSV uploader isn't perfect, but the HB reporting makes it seems like things are failing apart regularly. This PR updates the condition when we report an error to HB so that we don't get spammed with a million emails

chore: update error condition on csv uploader to quiet things down

---

src/annotations/components/annotationForm/AnnotationStartTimeInput.tsx

Connects #1328
Adds a label to the annotations date input that says `UTC`

feat: add label mentioning time is in UTC

---

src/alerting/utils/activity.ts

Sorting by time in descending order is broken.

fix: fix sorting issue

---

cypress/e2e/shared/tokens.test.ts
src/timeMachine/components/SelectorList.tsx

Closes influxdata/idpe#10551
Updates the title when hovering over query builder elements. The title now shows the item's name with no instructions in both cases. This is a very quick fix - I looked into using `DraggableResizer` but it wasn't possible to get it working quickly.

fix: show tag name as title when hovering in query builder

---

src/cloud/components/RateLimitOverlay.tsx

Closes #1269 
This PR removes UI references to `walkme`. We'll need to remove the CSP headers from the `csp` file as well

chore: remove walkme from the UI

---

cypress/fixtures/good-csv.csv
src/buckets/components/context/csvUploader.tsx

Closes #1189
Escapes special characters according to https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#special-characters
Adds special characters in valid csv used for e2e tests so we can test these scenarios.

fix: csv parser escapes special characters

---

.circleci/config.yml

We really shouldn't start the rest of the pipeline if the unit tests are failing. And also waiting on unit tests gives the user some time to open a PR before monitor-ci-tests starts so lighthouse won't complain about not getting a PR url.

chore: have monitor-ci-tests wait on unit/lint

---

src/flows/context/flow.list.tsx

Some of the backend flag systems can't handle hyphens, so changing it to `notebooksApi`

chore: change api flag to not have hyphens

---

scripts/run-monitor-ci-tests.bash

Partially closes #1007
Related: [monitor-ci PR#228](https://github.com/influxdata/monitor-ci/pull/228)
Updates the `run-monitor-ci-tests` bash script to have a different behavior if it is executed with the intent of testing changes in the OSS backend from `influxdb` with the latest UI from the `ui` repository.
If the script is executed with the env var `OSS_SHA` set, the API call to start the pipeline in `monitor-ci` will be what is required by the config updates in [monitor-ci PR#228](https://github.com/influxdata/monitor-ci/pull/228). If `OSS_SHA` is not set, the script will execute the same as before. The diff is a little misleading - basically all that is changing in the script is some updates to the comments at the beginning, and a conditional wrapping the existing pipeline API call …

chore: allow for running OSS pipeline from monitor-ci script

---

assets/index.html
webpack.common.ts

Closes #1273
Also see: Relevant [slack thread](https://influxdata.slack.com/archives/CLHATC50E/p1619031531035500)
This PR will set the title of the sign-in page based on the environment that the UI is built in. By default, the title will be "InfluxDB" - this will be the title displayed for OSS & other environments where the `CLOUD_URL` environment variable is not set. If the `CLOUD_URL` environment variable is set, the title will be "InfluxDB Cloud".

feat: different page title for cloud vs OSS sign-in page

---

docker/Dockerfile.chronograf.prod

Currently the `Dockerfile.chronograf.docker` file uses an unnecessarily large base image, installs unneeded packages, and insecurely runs a downloaded script. This pr uses a slimmer base image and saves ~475MB per base image, speeds up required dependency installs by ~38 seconds, and doesn't require insecurely running downloaded scripts.
```
$ time docker build -t test/ui -f ./originalDockerfilePreReq .
...
Successfully tagged test/ui:latest
real    0m44.174s
user    0m0.138s
sys     0m0.082s
$ time docker build -t test/ui2 -f ./newDockerfilePreReq .
...
Successfully tagged test/ui2:latest
real    0m6.009s
user    0m0.588s
sys     0m0.685s
$ docker images --format "table {{.Repository}}\t{{.Size}}"
REPOSITORY                       SIZE
test/ui2                         129MB
test/ui …
```

feat: improve ui image build time, size, and security

---

.circleci/config.yml
package.json

chore: bump openapi sha

---

.circleci/config.yml
webpack.lighthouse.ts
webpack.prod.ts

There seems to be an issue right now with running lighthouse tests, but by removing the bundle analyzer from the ci chain, we save ~8 minutes off the prod image build.
before:
after:

chore: remove bundle analyzer plugin to speed up lighthouse builds

---

src/Signin.tsx

Closes #1368
Adds the conditional to only get the public flags `IF (CLOUD)`

fix: only get public flags if cloud

---

src/writeData/components/FileUploadSection.tsx

Closes #1397 
React doesn't like when you return undefined apparently

fix: FileUploadSection returns null instead of undefined

---

src/client/swagger/notebooks.yml
src/flows/context/notebooks.api.tsx

Closes #1383
This will allow the multi-org-per-user feature of OSS to work with the minimal amount of effort.
We may want to revisit this down the line when InfluxDB cloud implements multi-org-per-user.

feat(notebooks): pass org id as query param when getting all notebooks

---

src/annotations/components/EditAnnotationForm.tsx
src/annotations/components/annotationForm/AnnotationForm.tsx
src/visualization/components/annotationUtils.ts

Closes #1403
Moves cancel events lower down the stack so that they're not always called when the overlay is closed. They're now only fired when the cancel button is clicked.

fix(annotations): change annotation event structure so cancel metric isn't fired so often

---

src/flows/components/AddButtons.tsx
src/flows/components/header/Submit.tsx
src/flows/components/panel/FlowPanel.tsx
src/flows/components/panel/RemovePanelButton.tsx
src/flows/components/panel/Results.tsx
src/flows/context/flow.current.tsx
src/flows/context/flow.list.tsx
src/flows/context/flow.query.tsx
src/flows/context/pipe.tsx
src/flows/context/results.tsx
src/flows/pipes/MetricSelector/context.tsx
src/flows/pipes/QueryBuilder/AddButton.tsx
src/flows/pipes/QueryBuilder/BucketSelector.tsx
src/flows/pipes/QueryBuilder/CardList.tsx
src/flows/pipes/QueryBuilder/context.tsx
src/types/flows.ts

Closes #1414 
notebooks was in bad shape, mostly from stale updates clobbering each other in async calls. I sorted out a few of these by normalizing loading state and results away from source of truth for things like: query state, query builder cards' keys and values, some other things.
Also when i was running some graphs in tools to see how people were using notebooks... i found out that we couldn't see which panels people were deleting, so i added that in
Also, the metric selector filter logic was a bit weird after i touched it last. This one feels a lot better; it shows less stuff, but more accurately, making it more useful to search stuff

fix: misc notebook bugs

---

src/dashboards/selectors/index.test.ts
src/mockState.tsx
src/shared/actions/app.ts
src/shared/components/VersionInfo.tsx
src/shared/components/VersionInfoOSS.tsx
src/shared/reducers/app.test.ts
src/shared/reducers/app.ts
src/shared/selectors/app.ts
src/shared/thunks/app.ts
src/types/app.ts
src/utils/env.ts
webpack.dev.ts

Closes #334 and #1330
Adds some additional version information to the OSS login page and "Getting Started" page that you see right after logging in. This information comes from the OSS backend via the `/health` endpoint. The "Frontend" hash is the one that gets set when building the UI. The hashes for Server and Frontend are clickable links that will take you to the page on github, for example to https://github.com/influxdata/influxdb/tree/4db98b4c9a.

feat: better version info for oss

---

src/functions/components/FunctionHeader.tsx

As part of changing URLs, we need to change the URL for functions API.

fix: update URL for functions to include poc in URL

---

scripts/run-monitor-ci-tests.bash

Adds some `********` around the monitor-ci pipeline link to draw attention to it.

chore: improve url visibility with stars

---

cypress/e2e/shared/loadDataSources.test.ts
src/writeData/components/ClientLibrarySection.tsx
src/writeData/components/FileUploadSection.tsx
src/writeData/components/TelegrafPluginSection.tsx
src/writeData/components/WriteDataSearchBar.tsx

Closes #1425
just like.. dont forget your return types. i wonder if there's a lint rule for this

fix: less breaking on the data page

---

cypress/e2e/cloud/usage.test.ts
package.json
src/usage/context/usage.tsx
src/users/context/users.tsx

This PR updates the openAPI SHA that's being referenced in order to generate the unityRoutes. As a result, some of the non-nested changes that were made in the API definition have been updated to reflect the new contract

chore: update openAPI SHA and updated unity info accordingly

---

src/cloud/components/onboarding/EngagementLink.tsx

Send orgID to Userpilot as `company: id` as well as `orgID` (both are needed for different purposes).

feat: send orgID as Company ID to Userpilot

---

cypress/e2e/cloud/annotations.test.ts
src/annotations/actions/creators.ts
src/annotations/components/AnnotationsControlBarToggleButton.tsx
src/annotations/components/controlBar/AnnotationsControlBar.test.tsx
src/annotations/components/controlBar/AnnotationsControlBar.tsx
src/annotations/reducers/index.test.ts
src/annotations/reducers/index.ts
src/annotations/selectors/index.ts
src/visualization/types/Graph/view.tsx
src/visualization/types/SingleStatWithLine/view.tsx

Closes #1320
- Change `1-click annotations` to `Write mode`
- Write mode is on by default

feat(annotations): update annotation button ux

---

src/flows/components/header/index.tsx

a debug tool to allow someone to click a button and see the internal notebook representation
`influx.set('flow-snapshot', true)`

feat: export a notebook

---

cypress/e2e/shared/explorer.test.ts
src/visualization/types/Mosaic/index.tsx

Closes #1460 
Removes the feature flag `mosaicGraphType` and makes this feature permanent.

feat: remove feature flag for Mosaic

---

package.json
yarn.lock

Closes #
>The only thing it affects is it will change the way the draggable handle looks in data explorer but it won't change any functionality.
>I added things that aren't in use yet as welll (like full-screen overlay)
See: https://github.com/influxdata/clockface/releases/tag/v2.8.0

chore: updating clockface version

---

cypress/e2e/shared/explorer.test.ts
src/visualization/types/Band/index.tsx

Closes #1463 
Removes the feature flag `bandPlotType` and makes this feature permanent.

feat: remove feature flag for Band Plot

---

package.json

Closes #1481 
Grabs the latest swagger def, which sends a correct `content-type` header on retry requests

feat(swagger): get latest swagger defs to fix task retry issue

---

src/dashboards/components/DashboardHeader.tsx
src/dashboards/components/DashboardPage.tsx
src/shared/components/TimeSeries.tsx
src/timeMachine/actions/queries.ts
src/views/actions/thunks.ts

Closes [influxdb#21447](https://github.com/influxdata/influxdb/issues/21447)
The dashboard autorefresh stopped working with for OSS #146, which removed the feature flags around the dashboard query cache. Since this version of the UI was not used with OSS until much more recently, the problem went undiscovered until now.
Since we don't want to bring in the new dashboard autorefresh feature with the next OSS patch release and still want to restore functionality of the dashboard autorefresh, this PR effectively reverts #146 and adds the feature flag back in, so that the query cache is not enabled for OSS.

fix: re-enable feature flags for dashboard query cache

---

.circleci/config.yml
scripts/run-monitor-ci-tests.bash

Closes https://github.com/influxdata/ui/issues/1461
Modifies monitor CI tests script to support forks of the UI repo. Uses github's APIs to get the org and branch of the fork. We can't depend on Circle's env vars for this because they don't set them to the values of the org/branch of the fork, but instead it creates some sort of local branch and use `influxdata` as the org. Not sure why it behaves that way, but github's APIs are a decent work around.
And obviously this works...but this PR is opened from a fork! 😄

chore: ci works from fork

---

cypress/e2e/cloud/communityTemplates.test.ts
cypress/e2e/oss/explorer.test.ts
cypress/e2e/shared/buckets.test.ts
cypress/e2e/shared/checks.test.ts
cypress/e2e/shared/explorer.test.ts
cypress/e2e/shared/tokens.test.ts
cypress/support/commands.ts

Went through the skipped cypress tests and found some that could be re-enabled. I ran each test that I enabled 20 times with k8s-idpe and saw no failures.
I also removed a couple tests that no longer seem applicable to the product.

chore: enables skipped tests, removes some

---

cypress/e2e/shared/explorer.test.ts
src/visualization/components/internal/StaticLegend.tsx
src/visualization/types/Band/view.tsx
src/visualization/types/Graph/view.tsx
src/visualization/types/SingleStatWithLine/view.tsx
src/visualization/utils/useStaticLegend.ts

Closes #1498 
- Since we can't tell from the backend api whether `hide` is deliberately `false` or not yet defined by the user, we need to be more explicit when the feature flag is off
- Set the `heightRatio` to be the default value when not defined

fix: hide the static legend explicitly when feature flag is off

---

package.json
yarn.lock

Backports #1506 into the `OSS-2.0` branch

build(lsp): Upgrade flux-lsp-browser to v0.5.47

---

package.json
src/operator/account/AccountGrid.tsx
src/operator/api/index.ts
src/users/components/InviteListContextMenu.tsx
src/users/context/users.tsx

This closes the issue we were seeing where CSRF protections were put in place on the Quartz API that were returning a `415` status code on empty post requests

chore: update the openapi definition to reflect some changes to quartz api

---

src/checkout/CheckoutForm.tsx
src/checkout/context/checkout.tsx
src/shared/copy/notifications.ts

After testing the checkout page in production, a bug was found where we couldn't upgrade because of an issue with the way we were submitting a division. This PR fixes that and addresses some TODOs with regards to notifications and hacky workarounds for the original implementation

feat: complete checkout page

---

src/pageLayout/components/RenamablePageTitle.tsx

Closes #1487 
On saving the updated title, the function was making a component state change after unmounting RenamablePageTitle which was throwing a react error to use cleanUp in useEffect hook. Instead we removed the state change as it is not needed after the component has been unmounted.

fix: renamable page title throwing react error

---

src/notifications/rules/components/RuleLevelsDropdown.tsx

Closes #
This adds the ability for users to create notification rules that go from any status to any other status (which is a valid rule).
```
package main
// dfasdfsdfsdfsdf
import "influxdata/influxdb/monitor"
import "slack"
import "influxdata/influxdb/secrets"
import "experimental"
option task = {name: "dfasdfsdfsdfsdf", every: 10m, offset: 0s}
slack_endpoint = slack["endpoint"](url: "https://hooks.slack.com/services/X/X/X")
notification = {
_notification_rule_id: "07980c9d253a8000",
_notification_rule_name: "dfasdfsdfsdfsdf",
_notification_endpoint_id: "07980c5a8ac8c000",
_notification_endpoint_name: "Name this Endpoint",
}
statuses = monitor["from"](start: -11m)
any_to_any = statuses
|> monitor["stateChanges"](fromLevel: "any", toLevel: "any")
all_statuses = any_to_any
|> filter(fn: …
```

feat: allow any to any in notification rules

---

package.json
src/Logout.tsx
src/Signin.tsx
src/billing/components/PayAsYouGo/InvoiceHistoryRow.tsx
src/billing/context/billing.tsx
src/operator/account/AccountGrid.tsx
src/shared/containers/GetOrganizations.tsx
src/types/operator.ts
src/usage/context/usage.tsx

The primary purpose of this PR is to update the SHA for the OpanAPI reference. Unfortunately, we can't validate whether the change made to OpenAPI will fix the issue with getting the billing_stats since that depends on querying an external bucket that is inaccessible in local development (but is available in staging and production).
Wit the SHA being updated came some changes to some of the type definitions in the API for an account as it relates to the Account type. The current Account type was being used as a nested property of the Operator and contains more information than is necessary for most Account use cases and will therefore be partitioned for the Operator page.
Finally, there was some general house keeping with this PR (bumping the minimum balance threshold from 1 -> 10, adding …

chore: updating the OpenAPI SHA to test out the getUsageStats API

---

package.json

Allow configuring `PUBLIC` environment variable for `yarn start:kind` to enable hot reload when the UI is running under a different domain name.

chore: allow setting PUBLIC env variable for yarn start:kind

---

src/checks/components/CheckCard.tsx
src/checks/components/CheckCardContext.tsx
src/notifications/rules/components/RuleCard.tsx
src/notifications/rules/components/RuleCardContext.tsx
src/shared/copy/notifications.ts

Closes #1421 
Changed the eyeball icon to gearbox and added "Edit Task" to the drop down list of both Check and Notification rule. 
When "Edit Task" is clicked, user is directed to edit task page. A warning toast message pops up letting user know editing code might remove the ability to edit task in the UI.

feat(alerts): warned user of dangers of editing tasks

---

package.json
src/shared/apis/query.ts
src/usage/context/usage.tsx
yarn.lock

this PR is a sanity check to try and see if handling the response correctly will actually render the usage stats data on the Usage Page. This should be a temporary thing since we'd want to lean on oats as the ultimate tool for processing queries and their responses. Currently, this is utilizing the querying mechanism that the UI uses to issue queries to the `/query` endpoint, which handles `csv` responses

chore: creating a custom query for the usage stats to see if the results populate correctly when the results are received and handled correctly

---

src/templates/components/CommunityTemplateResourceContent.tsx

Closes #1430
Adds a title prop which was coming in as undefined bc it wasn't getting set in the list component, which allows the toggle to select the correct label 
https://user-images.githubusercontent.com/29473622/120361025-02725c00-c2cf-11eb-8cc4-01f08535fd82.mov

fix: add title prop to enable toggle to find correct label

---

src/checkout/context/checkout.tsx

This wraps the submit function in a useCallback to ensure that we are capturing the latest `inputs` when the user hits the submit button. Also updating the way we are setting the `isNotify` field so that it actually sends `isNotify` and not `shouldNotify`.

fix: handle submit bug for the checkout page

---

src/flows/components/FromTemplatePage.tsx
src/flows/context/flow.list.tsx
src/shared/containers/GetOrganizations.tsx

This allows us to generate any number of random notebooks from a template. You just add the template to the giant object, and it registers a route you can reference with a link (no user info in there like orgs or what not). should be able to deeplink from docs as well, but try it as a signed out user before shipping
turns out there's a bug with the youtube component where autoplay doesnt fire when we deeplink to the page, so please ignore

feat: generate notebook from template

---

cypress/e2e/shared/explorer.test.ts
src/shared/components/dateRangePicker/DatePicker.tsx
src/usage/context/usage.tsx

Closes #448 
This PR updates the validation mechanism to allow for ISOString formatted inputs to be valid. It also sets the default format to ISOString

feat: isoString is now the default for selected time ranges and is a valid format

---

src/checkout/CheckoutForm.scss
src/checkout/NotificationSettingsForm.tsx
src/checkout/context/checkout.tsx
src/checkout/shared/FormInput.tsx
src/shared/copy/notifications.ts
src/style/chronograf.scss

This PR addresses some styling issues that were found when testing out the checkout flow. 
More importantly this PR cleans up some of the useEffect dependencies that were causing excessive queries from firing by use `prevState` props rather than listening for changes to the `inputs`.

fix: checkout page bugs that were found in testing, mostly styling but cleaned up implementation

---

src/visualization/types/SimpleTable/style.scss

Closes #1540 
Adds `user-select: text` to simple table. Previously it was inheriting `user-select: none` from time machine
https://user-images.githubusercontent.com/6411855/120559469-f0b7b400-c3b5-11eb-8ee8-32e78e270d91.mov

chore: allow text selection in simple table

---

src/visualization/types/Graph/options.tsx

Closes #1445
Adds a default array to the colorschemedropdown value prop so that if there is not color defined, it will not error.

fix: add default so colorschemedropdown doesnt error if no color

---

src/shared/constants/fluxFunctions.ts

Closes #
Adds the missing flux functions from https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/all-functions/

feat: adding missing flux functions

---

scripts/run-monitor-ci-tests.bash

Closes #1538
Adds logic to `run-monitor-ci-tests.bash` script to look for failed pipelines with the same commit SHA and re-run them from failure using the CircleCI API instead of starting a brand new monitor-ci pipeline.
https://user-images.githubusercontent.com/6411855/120549612-ad0a7d80-c3a8-11eb-81e6-2767d32a6428.mov

chore: enhanced monitor-ci-tests retry from failure

---

src/eventViewer/components/TableRow.tsx
src/visualization/types/Table/TableCell.test.ts
src/visualization/types/Table/TableCell.tsx

Closes #1420 
Automatically adds links to the TableRow component (used by both the checks and notifications status pages) so that any link in a TableRow gets built into a link identically to the way it's done in EventTable.
Looks like this in action:

feat: Automatically link urls found in check and notification status messages

---

package.json
src/visualization/types/Graph/view.tsx
src/visualization/types/SingleStatWithLine/view.tsx
yarn.lock

Closes #1603 
- Prevents infinite re-renders on stacked lines by memoizing dependencies used by stacked lines
- Brings back the additional legend columns used by stacked lines
https://user-images.githubusercontent.com/10736577/120587114-99cbd200-c3e9-11eb-9866-437e008a8538.mp4

fix: prevent infinite re-render in stacked line graphs

---

src/flows/pipes/RawFluxEditor/index.ts

Closes #1613
regexp sure does suck, the ast is so much better!

fix: remove the regex parsing of comments

---

src/scrapers/components/CreateScraperOverlay.tsx

Closes #1622 
Attempts to fix an issue where the _monitoring bucket is selected by default for new scrapers.
old behavior:
new behavior:

fix: change default bucket for scraper

---

src/usage/context/usage.tsx

OK, so I think this is the solution. The previous implementation only replaced the first instance of the return and newline, this one replaces all of em. I validated it in a JS Fiddle. REALLY HOPING THIS IS IT
https://jsfiddle.net/Asalem1/mjzdph43/1/

chore: fixed replace statement, this should work

---

cypress/e2e/cloud/home.test.ts

Closes #
`home.test.ts` is flaky again because of the way checks run without a definitive answer to when the runs will be populated. Bumping up the wait until a better alternative is figured out.

fix: fix flaky test. yet again

---

src/usage/BillingStatsPanel.tsx
src/usage/GraphTypeSwitcher.scss
src/usage/GraphTypeSwitcher.tsx
src/usage/context/usage.tsx

This PR integrates the final piece of functionality associated with the usage page by using the usage vectors as the source of truth for rendering the usage stats at the top of the usage page. This differs from the original implementation in that it will show all the usage stats even if no data is present (even those that will be empty). This is by design

feat: usage stats page complete

---

src/checkout/CheckoutForm.scss

This PR updates the blank zuora form state by transferring a couple of classes from Quartz that were not being imported into the UI

chore: updated styling for empty zuora form

---

cypress/e2e/shared/explorer.test.ts
cypress/e2e/shared/flows.test.ts
package.json
src/visualization/types/SimpleTable/InnerTable.tsx
src/visualization/types/SimpleTable/PagedTable.tsx
yarn.lock

Closes #1548
Adds `useEffect` that sets the page to `1` every time `result` changes. This fixes the unwanted behavior where the table would vanish when you switch from a dataset with more pages to one with fewer. I also renamed the variable `page` to `size`.
Test included.
https://user-images.githubusercontent.com/6411855/120874009-732ca900-c559-11eb-8e45-857936320c38.mov

fix: simple table no longer vanishes

---

src/usage/GraphTypeSwitcher.scss
src/usage/GraphTypeSwitcher.tsx

Hopefully the final iteration of this styling issue. For some reason applying the styles locally had a different effect on the production image. I don't know what to make of it but it seems like making the height of the panel body a bit bigger allows for the numbers to be more legible. For example, `Data Out` is the older `50px` height, whereas `Storage` and `Query Count` are set to `75px`

chore: for some reason the styling looks different on prod

---

src/dashboards/components/DashboardPage.tsx

Closes #18998
Makes the fallback option for dashboard title "Name this Dashboard" so it matches the default name

fix: dashboard header when removing name is back to default

---

src/flows/pipes/Schedule/ExportTaskOverlay/context.tsx
src/templates/actions/thunks.ts
src/templates/components/CommunityTemplateInstallOverlay.tsx

For months now I've been getting emails about this error and it doesn't seem like it has any relevance for us as an organization to know that a specific README failed to fetch and set, or that a templateUrl failed to make due to a yaml definition. This morning, I deleted a few hundred honeybadger errors over the last 24 hours, most of which were traced to these two functions with those two consistent errors. This PR aims at reducing the level of noise produced by honeybadger in order to prevent actual issues from falling through the cracks when it comes to getting legitimate notifications through honeybadger

chore: exceptions to when we write to honeybadger

---

src/billing/components/PayAsYouGo/InvoiceHistoryRow.tsx

This resolves an issue where invoice PDFs that are generated in quartz could not be retrieved from the API due to a mismatch in the path.

chore: update the invoice URL

---

src/flows/context/api.tsx

flowd returned a 200 on successful deletion, notebooksd returns a 204 (which is the correct code to return since we do not return the entity in the response)
This change makes the UI code more flexible so that it accepts both statuses in the 200 range as success. I couldn't change the 200 to a 204 because we're still in the process of deploying notebooksd so the UI code needs to be flexible for now.

fix: delete notebooks accepts 200 or 204

---

src/pageLayout/constants/navigationHierarchy.ts

Closes #1677 
This is a precursor to some more operator work that should be rolling out soon regarding the way we're allowing internal users to access the operator page.

feat: adding the operator link to the navbar behind a feature flag

---

src/telegrafs/components/TelegrafOutputOverlay.tsx

Adds a little spacing so that this:
turns into this:

fix: add spacing for telegraf modal

---

package.json
yarn.lock

Trying to bump immer a couple major versions at a time to eventually get us to latest

chore: bumps immer to 3.3.0

---

cypress.json

Blocks requests to honeybadger while running cypress tests. Should reduce the noise in honeybadger.

chore: block honeybadger during cypress tests

---

package.json
src/visualization/utils/annotationUtils.test.ts
src/visualization/utils/annotationUtils.ts
yarn.lock

Closes #1501 
sorts the annotations so the ranges render first;
and bumps up the giraffe version to get the new changes so they render correctly

feat: overlapping annotations

---

package.json
yarn.lock

Closes #
Giraffe's geo code had a hardcoded value for displaying the tooltip Column name, which we fixed but need to release with a package to fix current maps in production.

fix: update package for giraffe to maps tooltips

---

src/billing/components/BillingPage.tsx
src/pageLayout/constants/navigationHierarchy.ts
src/pageLayout/containers/TreeNav.tsx
src/usage/UsagePage.tsx
src/users/components/UserListContainer.tsx

This PR updates the unifications pages to standardize the page titles based on the current UI conventions of adding a pageTitleSuffixer. It also adds a filter to the TreeNav prior to mapping out the results so that we can filter out the operator link for all users that are not operators

chore: updated unification pages to have pageTitleSuffixers, and added filter to treenav to remove operator for non-operators

---

src/dashboards/utils/cellGetters.ts
src/visualization/utils/useStaticLegend.ts

Part of #1523 
- Previously, i capped the upper bounds of static legend height. The lower bounds should also be capped. This is just for thoroughness, as the static legend height should come back as positive number from Giraffe's renderEffect options.
- Fix the default cell height when user creates a cell through the Data Explorer rather than "Add Cell"

fix: correct default cell height for static legend and cap lower bounds

---

src/tasks/actions/creators.ts
src/tasks/actions/thunks.test.ts
src/tasks/actions/thunks.ts
src/tasks/components/TaskCard.test.tsx
src/tasks/components/TaskCard.tsx
src/tasks/components/TaskRunsCard.tsx
src/tasks/components/TaskRunsPage.test.tsx
src/tasks/components/TaskRunsPage.tsx
src/tasks/reducers/helpers.ts
src/tasks/reducers/index.ts
src/types/tasks.ts

closes #1495 
To make code review/ merging easier, I've split #1655 into smaller portions.
This PR contains the remaining portion of changes implemented by PR #1655.
**Issue**: Whether user is editing task from task list page or task runs page, after clicking save, user is always routed back to task list page. 
PR **solution**:
If user edits task from task list page, after clicking save, they will be routed to task list page. 
if user edits task from task runs page, after clicking save, they will be routed to task runs page. 
https://user-images.githubusercontent.com/66275100/122278032-237ca480-ceac-11eb-9eac-6250d5231f75.mov

fix: Task Page/ Task Runs Page- task editing routing issue 

---

src/visualization/types/Map/view.tsx

Closes #1615 
Okay so this fixes the color issue by auto assigning the color similar to our logic for the tooltipColumns and this has layer opts be above all code calling for layer properties. I was finding that the code was crashing because it was look for layer.properties.blah and finding nothing. So i moved all the code underneath and i set layerOpts = layers, which was missing so things were still crashing when they checked the properties.

fix: Notebook maps error

---

cypress/e2e/cloud/annotations.test.ts
src/annotations/components/annotationForm/AnnotationForm.tsx
src/annotations/components/controlBar/AnnotationsControlBar.tsx

Closes #1750 
*  hides the range/point toggle when range annotations are off
*  hides the informational text on the annotations bar when range annotations are off
*  adding e2e tests to test this.

feat: only show range annotation information when the feature flag is on

---

package.json
yarn.lock

The final step on the journey of upgrading immer. This PR bumps it to 9.0.3 which is the latest version.

chore: upgrades immer to 9.0.3 (latest)

---

src/App.tsx

Changes `setAutoFreeze(false)` to remove `immer` console errors when developing locally. We plan to fix these errors at a later time

chore: setAutoFreeze(false)

---

cypress/e2e/cloud/annotations.test.ts
cypress/e2e/cloud/home.test.ts
cypress/e2e/shared/buckets.test.ts
cypress/e2e/shared/checks.test.ts
cypress/e2e/shared/dashboardsView.test.ts
cypress/support/commands.ts
docker/Dockerfile.cypress
package.json
yarn.lock

Closes #1660 
In Cypress v7 there are several breaking changes to `cy.intercept` command. This PR updates all the usages of the intercept command to make them compatible with the breaking changes.
In Cypress v7, all console errors will fail the tests by default. This was breaking our login flow because there is a (expected) 401 response when we login via DEX APIs. I also noticed that there are some console errors being logged for several of our tests. So for now I opt'd to dismiss all console errors (which was the default behavior of Cypress v6). I think we should open separate issues for addressing the console errors themselves.
In Cypress v7, `Cypress.moment` has been removed. I changed our usages to use `moment.js` instead.
Cypress v7 change log: …

chore: upgrade to cypress 7.5.0

---

cypress/support/commands.ts

I noticed some flakes where the tests fail during the beforeEach because ingress doesn't respond. And when the beforeEach fails, the entire test suite stops and is not retried. These failures are happening because of "NetworkErrors". This change makes it so that cypress ignores these errors and does not fail the tests immediately.

chore: ignore network errors during cypress tests

---

cypress/support/commands.ts

Change the abort error message cypress is looking for.
Noticed that "AbortError" wasn't doing the trick. See [this pipeline](https://app.circleci.com/pipelines/github/influxdata/monitor-ci/2215/workflows/a1ec8753-f8b6-4271-8bbf-11548e066615/jobs/18921/tests#failed-test-0) as an example. The error message actually is "The operation was aborted".

fix: cypress abort error message

---

cypress/e2e/shared/explorer.test.ts

Should fix the test failures we're experiencing related to missing right parenthesis. I think the `delay` option for the `cy.type()` func set to `0` was causing issues for these tests. The delay shouldn't be necessary.
I also removed some chaining while I was in there.

fix(test): remove typing delay and chaining

---

src/usage/BillingStatsPanel.tsx
src/usage/GraphTypeSwitcher.tsx
src/usage/UsageToday.tsx

This resolves an issue with some customer reported usage page wonkiness where the data that was being mapped was the csv `_value` rather than the `fluxKey`. It also reconciles the source of truth for mapping column data based on the usage vectors that are being returned by the API and simplifies some of the logic surrounding all that.

fix: usage page issue with mismatched data

---

package.json
src/annotations/actions/thunks.ts
src/annotations/api/index.ts

Closes #1645
Also see https://github.com/influxdata/openapi/pull/135
This PR will pull in the API definition for the OSS annotations API, which requires an org ID parameter for certain requests where required due to the multi-org-per-user behavior of OSS. The `openapi` SHA will be updated to the commit which added this API definition.
The actual requests which use these endpoints in the UI are being updated to send the org ID parameter where needed as well. The org ID parameter is not required for cloud and sending it should not have any impact on those requests since the annotations service for cloud derives the org ID for the token. This is a similar approach as was taken for Notebooks on OSS, see: https://github.com/influxdata/ui/pull/1390
An alternative for sending the org ID …

feat: send org id parameter for annotations requests to support OSS multi-org

---

src/usage/UsageToday.tsx

this PR adds some checks prior to getting the usage data to render the dropdown since the code is async but isn't dependent upon the usageVectors for rendering. This caused the usage page to break so now we're adding to checks to ensure that something exists prior to rendering it. This is the only place that should be affected since it the other places that make use of the GraphTypeSwitcher are:
- Only being generated when the data is mapped (so it won't generated without any data)
- Has the usageVector hard-coded so there is not concern about async code

fix: added guarding for async rendering of the usage dropdown data

---

src/utils/datetime/formatters.test.ts
src/utils/datetime/formatters.ts
src/visualization/utils/timeFormat.ts

Closes #1767 
```ts
import {createDateTimeFormatter} from 'src/utils/datetime/formatters'
const date = new Date(426196800000)
const formatter = createDateTimeFormatter('YYYY-MM-DD hh:mm:ss a')
formatter.format(date) // 1983-07-04 1:00:00 PM (for me, here on the west coast in summer)
const formatterUTC = createDateTimeFormatter('YYYY-MM-DD hh:mm:ss a', 'UTC')
formatter.format(date) // 1983-07-04 8:00:00 PM
```
Supports the formats enumerated by [this list.](https://github.com/influxdata/ui/blob/ab5d713b0a95980c9ee8ce8a525f09a15902ec13/src/visualization/utils/timeFormat.ts)
Co-authored-by: Beth Legesse <blegesse@influxdata.com>
Co-authored-by: Zoe Steinkamp <zsteinkamp@influxdata.com>
Co-authored-by: Palak Bhojani <pbhojani@influxdata.com>
Co-authored-by: Merrick Tian <mtian@influxdata.com>

feat: new DateTime formatter

---

scripts/run-monitor-ci-tests.bash

Noticed a lot of pipelines hitting the timeout marker but the pipelines end up succeeding over in monitor-ci. Checked out the "Insights" page in CircleCI and it looks like there has been an increase in the average time it takes `cloud-e2e-k8s-idpe` to complete. This is probably because there are new pods & services being added to k8s-idpe. I would look into it more, but we're already planning to move to a remocal CI where we won't be standing up the cluster locally every time which will eliminate this issue.
So, for now, I'm increasing the timeout to 50min.
Slack convo: https://influxdata.slack.com/archives/CLHATC50E/p1624576883002000

chore: increase timeout to 50min

---

package.json
src/authorizations/apis/index.ts
src/localStorage.ts
src/onboarding/containers/LoginPageContents.tsx

Closes #
We need to be able to login using SSO when a participating domain's email is trying to login. There's a fixme which is depending on #4824. Added feature flag `ssoLogin` temporarily to test in tools as this functionality can't be tested locally because we use dex for auth locally and this change requires Auth0 to redirect us to a callback route.

feat: sso login

---

src/visualization/components/internal/HoverLegend.tsx
src/visualization/components/internal/StaticLegend.scss
src/visualization/components/internal/StaticLegend.tsx
src/visualization/types/Band/options.tsx
src/visualization/types/Graph/options.tsx
src/visualization/types/Heatmap/options.tsx
src/visualization/types/Histogram/options.tsx
src/visualization/types/Mosaic/options.tsx
src/visualization/types/Scatter/options.tsx
src/visualization/types/SingleStatWithLine/options.tsx

As part of #1773 
Make the view options clearer to distinguish between Hover Legend and Static Legend

chore: update visual design for view options of Hover Legend and Static Legend

---

src/shared/constants/fluxFunctions.ts

according to the docs, this is no longer a valid option: https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/window/

fix: removing intervals param from window

---

src/cloud/components/RateLimitAlert.tsx
src/cloud/components/RateLimitAlertContent.tsx
src/cloud/components/WriteLimitAlertContent.tsx
src/cloud/components/WriteLimitOverlay.scss
src/cloud/components/WriteLimitOverlay.tsx
src/overlays/components/OverlayController.tsx
src/overlays/reducers/overlays.ts

Closes #10955
This introduces more detailed and functional write limit overlays that provide an opportunity for users to upgrade and/or submit requests for increases if they are PAYG. This is a major improvement over our previous implementation, which did.... nothing.

feat: write limit overlays

---

src/checkout/NotificationSettingsForm.tsx

Implementing a winning A/B test. Using the language of alerts rather than limits doubled conversion.
Closes #

fix: Checkout text change continued

---

src/dashboards/constants/index.ts
src/utils/datetime/formatters.test.ts
src/utils/datetime/formatters.ts

Closes #1823
Removed `case 'YYYY-MM-DD HH:MM:ss':` from formatter.ts because `YYYY-MM-DD HH:MM:ss` is not equivalent to `YYYY-MM-DD HH:mm:ss` (again, MM for months and mm for minutes)
Modified formatters.test.ts to test `YYYY-MM-DD HH:mm:ss` instead of `YYYY-MM-DD HH:MM:ss` because the latter is not a valid format and test file did not cover `YYYY-MM-DD HH:mm:ss`

fix: Replaced all instances of the format YYYY-MM-DD HH:MM:ss to YYYY-MM-DD HH:mm:ss

---

src/shared/utils/insertPreambleInScript.ts

Closes https://github.com/influxdata/ui/issues/1521
1. Create a bucket with `import` in the name (`devbucket-import` is what I used)
1. Try to create a task that references the bucket with import in the name
```flux
from(bucket: "devbucket-import")
|> range(start: v.timeRangeStart)
|> filter(fn: (r) => r._measurement == "system")
|> filter(fn: (r) => r._field == "load1" or r._field == "load5" or r._field == "load15")
|> to(bucket: "devbucket-downsampled", org: "dev")
```
1. Apply this fix and then retry the above

fix: handle creating tasks that work with buckets with import in its name

---

src/visualization/types/SimpleTable/InnerTable.tsx

Closes #1838 
Simple table can now handle receiving NaN values. I tested it by exporting the dataset from tools and importing it into my local env. I ran the same query and was able to reproduce it locally. This fix does the trick

fix: simple table handles NaN

---

cypress/support/commands.ts
package.json

Should resolve the cloud-e2e issue I think. Adds an additional login flow that uses Dex's UI. This will be used for when monitor-ci is run in cloud mode.

chore: add additional cypress login flow for monitor-ci

---

src/annotations/components/AddAnnotationOverlay.tsx
src/annotations/components/EditAnnotationOverlay.tsx
src/annotations/components/annotationForm/AnnotationForm.tsx
src/visualization/utils/annotationUtils.ts

Closes #1752 
changes:
note:  prefixes are either:
<ul>
<li>xyplot
<li>band
<li>singleStatWline
</ul>
<table>
<tr><th> original </th><th> changed</th></tr>
<tr><td>annotations.edit_annotation.success </td><td>${eventPrefix}.annotations.edit_annotation.success</td></tr>
<tr><td>annotations.edit_annotation.failure</td><td>${eventPrefix}.annotations.edit_annotation.failure</td></tr>
<tr><td>annotations.delete_annotation.success </td><td>${eventPrefix}.annotations.delete_annotation.success</td></tr>
<tr><td>annotations.delete_annotation.failure </td><td>${eventPrefix}.annotations.delete_annotation.failure</td></tr>
</table>
<div>special case for: dashboards.annotations.create_annotation.cancel</div>
<table><tr><th>creation</th><th>editing</th></tr> …

chore: Annotations-fix metric tags

---

package.json

Adds the `test:e2e:remocal` target which requires providing the `NS` variable which is the namespace of your remote cluster. 
So it is invoked like `NS=gene20210622081511 yarn test:e2e:remocal`.
Docs PR: https://github.com/influxdata/docs.influxdata.io/pull/210

chore: add test:e2e:remocal target

---

cypress/e2e/shared/dashboardsView.test.ts
src/shared/constants/index.ts
src/utils/datetime/formatters.test.ts
src/utils/datetime/formatters.ts
src/visualization/utils/timeFormat.ts

Closes #1834 
changed DEFAULT_TIME_FORMAT from `YYYY-MM-DD HH:mm:ss a` to ->  `YYYY-MM-DD HH:mm:ss` (no a). This change assures 24 hour time format doesn't contain a AM/PM 
Before: 
After:

fix: Default time format update

---

package.json
yarn.lock

https://github.com/influxdata/giraffe/releases/tag/v2.15.7

chore: upgrade to giraffe 2.15.7 to fix memory leak in PlotEnv

---

src/visualization/components/internal/HoverLegend.tsx
src/visualization/components/internal/LegendOptions.tsx
src/visualization/components/internal/StaticLegend.tsx
src/visualization/utils/useLegendOpacity.ts
src/visualization/utils/useStaticLegend.ts

Closes #1855 
orientation:
- added checks for 0 and -1 for vertical into the orientation toggle component
- updates will explicitly use -1 for vertical
opacity:
- added checks for valid opacity into the opacity slider component
- static legend will explicitly set a default opacity

fix: updates default values and sets explict values where appropriate for Hover and Static Legends

---

src/shared/constants/timeRanges.ts
src/types/queries.ts

Closes https://github.com/influxdata/influxdb/issues/21721
add's 1m to the time range selector.

feat: add 1m time range to dashboards

---

src/tasks/components/RunLogRow.tsx

see #1768
replaces moment.js in the RunLogRow component with date formatter.

feat: changed moment with date formatter in Run log row 

---

src/visualization/types/Map/utils.ts

Closes #1817 
For the dropdown, the function was excluding all number types of tags. This pr removes that condition so that when lat/lon as tags are given as floats/numbers, it can be displayed in the dropdown for customization options.

fix: maps lat/lon columns as float should display in dropdown

---

src/tasks/components/RunLogRow.tsx
src/tasks/components/TaskRunsRow.tsx
src/utils/datetime/FormattedDateTime.test.tsx
src/utils/datetime/FormattedDateTime.tsx
src/utils/datetime/formatters.ts

Closes #1856
* Creates a new component that handles the user's timezone (local | UTC) preference
* Replaces moment instance of this in `TaskRuns`
* Adds this functionality to `TaskRunsLog`

feat: TimeZone aware DateTime formatter component

---

cypress/e2e/shared/simpleTable.test.ts
src/visualization/context/pagination.tsx
src/visualization/types/SimpleTable/PageControl.tsx
src/visualization/types/SimpleTable/PagedTable.tsx
src/visualization/utils/paginationUtils.test.ts
src/visualization/utils/paginationUtils.ts

Closes #1813 and #1714
The original issues are resolved simply by changing the offset calculation to prevent the offset from becoming -1. However, this bug highlighted another issue with simpletable where the records from the `n-1` page were duplicated on the `nth` page. The solution to that was to set the `totalPages` variable whenever the result set changes or the height of the table changes. We cannot calculate the `totalPages` using `size` and `offset` because those numbers change as each page is rendered and not all pages show the same number of records.
I added unit and cypress tests

fix: simple table 0 of undefined and pagination bugs

---

src/alerting/components/AlertHistoryIndex.tsx
src/alerting/components/TimeTableField.tsx

Closes #1419
Adds the timezone dropdown to the Alert History page and uses the new Date-time formatter since we are now moving away from using MomentJs.
https://user-images.githubusercontent.com/18511823/124179660-ff9e8e80-da67-11eb-9a0d-d40083179027.mov

feat: add timezone dropdown to the alert history page 

---

cypress/e2e/cloud/annotations.test.ts

Closes https://github.com/influxdata/ui/issues/1808
The test `can add an annotation; that is originally a point and then switch to a range` fails in firefox. When I look at the recording, it's because moment cannot create the date correctly. I think adding this input formatting for the date will fix it 🤞 
JSfiddle illustrating the difference: http://jsfiddle.net/n1e5Lzjs/

fix: annotations test in firefox

---

cypress/e2e/shared/annotations.test.ts

Part of https://github.com/influxdata/influxdb/issues/21553
This is the first of one of 3 PRs that will be needed to "move" the annotations e2e tests from `cloud` to `shared`, so that they run against OSS as well, since OSS now supports annotations. This PR is just copying the annotations e2e test file into the `shared` folder.
There will also be an update in the `k8s-idpe` repo, and then another PR to delete the annotations tests from the `cloud` folder here so that they only run from from shared. There will be a brief period of time where the annotations tests run twice for `cloud-e2e` 😬 (I think? Unless cypress is smart enough to not run identical test names twice, or the globbing takes care of it somehow), but this is necessary since the list of tests that must be run is hard-coded in …

chore: copy annotations e2e tests to shared

---

src/alerting/components/AlertHistoryIndex.tsx
src/alerting/components/TimeTableField.tsx

The IDE auto-import was a relative path for this PR: https://github.com/influxdata/ui/pull/1877, we need to change it to absolute with the base at `src` to make it consistent across.

refactor: changed relative paths to absolute paths

---

cypress/e2e/shared/flows.test.ts
src/flows/components/PipeList.tsx
src/flows/context/flow.list.tsx

Closes https://github.com/influxdata/idpe/issues/10960
If presentation mode is on, run preview when entering the notebook and display the visualizations.
If presentation mode is off, do not run preview when entering the notebook.
Adds cypress tests for these two scenarios.
https://user-images.githubusercontent.com/6411855/124320574-fdeccd80-db30-11eb-9a0d-31be02d98f97.mov

fix(notebooks): run preview only when presentation mode is on

---

cypress/e2e/shared/tokens.test.ts

Closes #1701 
I think this will help with the flaky token test. The issue was that it was attempting to get the `.first()` card before the delete API had returned and when the API did return, the card was removed and the element it grabbed became detached. 
I also added the `{force:true}` to the click because sometimes it was failing because the button was hidden. I've tried to fix this before but cypress just doesn't work well with mouseover events.
I was able to run it 10 times in a row successfully after this change. Before the change I could only get it to run 3 times without failing.

test: fix flaky delete token test

---

src/shared/copy/notifications.ts
src/templates/components/CommunityTemplateInstallOverlay.tsx
src/templates/components/CommunityTemplatesInstalledList.test.tsx
src/templates/components/CommunityTemplatesInstalledList.tsx

Closes https://github.com/influxdata/idpe/issues/11155
Makes Community Template error messages more generic.

fix: make community template error messages more generic

---

cypress/e2e/cloud/operator.test.ts
src/operator/constants.tsx

This PR corrects the path that's referenced for orgIDs as the idpeId rather than the ID for org in quartz.

fix: operator page linking issues

---

cypress/e2e/shared/flows.test.ts

Closes #1911 
Waits for the notebook to save before navigating away from the page. There was a race condition where the cypress tests would sometimes navigate away too quickly and the PATCH request saving the notebook to enable presentation mode was cancelled. And that caused the test to fail.

test: wait for notebook to save before navigating

---

cypress/e2e/shared/tokens.test.ts

Closes #1701 
Another attempt at fixing the flakiness of this test. I was able to reproduce the issue from CI locally. It failed 1 out of 10 runs for me. 
The solution was to 1) only run a single command inside the `.within(() =>` to avoid the "element has been detached from dom" error and 2) to add `{force:true}` when clicking the Delete button. I also got rid of the `.contains('Delete')` because that seems like a silly assertion. 
Now it succeeds 20 out of 20 runs locally for me.

test: another attempt at the flaky token test

---

cypress/e2e/cloud/dashboardsView.test.ts
src/shared/components/views/MarkdownRenderer.tsx
src/templates/components/CommunityTemplateReadme.tsx
src/writeData/components/ClientCodeCopyPage/InstallPackageHelper.tsx
src/writeData/components/fileUploads/UploadDataDetailsView.tsx
src/writeData/containers/ClientLibrariesPage.tsx
src/writeData/containers/TelegrafPluginsPage.tsx

Only escape html when rendering editable markdown. For example, community templates should render html but dashboard notes should not. 
This change only applies to when the UI is in cloud mode.
Some examples showing that the markdown renderer works as expected after this change:

fix: only escape html for editable markdown

---

cypress/e2e/cloud/home.test.ts
cypress/e2e/shared/flows.test.ts

Attempts to fix the flake in this flows test again by waiting on a specific patch request to be successful with a specific body.
Also fixes flake in home tests where we were navigating away before the feature flags were fully set

test(flows): wait on specific patch request

---

src/functions/components/FunctionRunLogRow.tsx

closes: #1905
Replaces the `moment` library with the new `DateFormatter` in `FunctionRunLogRow`.
_Screenshots coming soon_

refactor: use new DateFormatter for FunctionRunLogRow

---

cypress/e2e/shared/simpleTable.test.ts
src/visualization/context/pagination.tsx
src/visualization/types/SimpleTable/PagedTable.tsx
src/visualization/utils/paginationUtils.ts

Closes #1884
Pagination jumping bug fixed. Solution involves calculating the size, comparing it to the maxSize, and replacing it if it is bigger. 
Also, so small calculation for size (line 45 in PagedTable.tsx). Fix does not change anything, but fixes the math in case it is important in the future.
**101 should be 100**
https://slack-files.com/T02GAR81Y-F027BGXJD4Z-41e69a30a6

fix: Pagination jump

---

src/flows/pipes/RawFluxEditor/view.tsx
src/shared/components/FluxMonacoEditor.tsx

Closes #1789
Wrap lines in flux editor in notebook cell

fix: add line wrapping to flux editor in notebooks

---

cypress/e2e/cloud/about.test.ts
cypress/e2e/cloud/billing.test.ts
cypress/e2e/cloud/users.test.ts
cypress/e2e/shared/about.test.ts
cypress/e2e/shared/nav.test.ts
cypress/e2e/shared/orgs.test.ts
cypress/e2e/shared/variables.test.ts
cypress/support/commands.ts
src/members/containers/MembersIndex.tsx
src/organizations/components/DeleteOrgOverlay.tsx
src/organizations/components/OrgHeader.tsx
src/organizations/components/OrgNavigation.tsx
src/organizations/components/OrgProfileDeletePanel.tsx
src/organizations/components/OrgProfileTab.tsx
src/organizations/components/OrgTabbedPage.tsx
src/organizations/components/RenameOrgOverlay.tsx
src/organizations/containers/OrgProfilePage.tsx
src/shared/components/CopyButton.tsx
src/shared/components/dangerConfirmation/DangerConfirmationForm.tsx
src/shared/components/notifications/NotificationButtons.tsx
src/shared/components/notifications/Notifications.tsx
src/shared/copy/notifications.ts
src/shared/selectors/flags.ts
src/types/notifications.ts
src/users/components/UserListContainer.tsx
src/users/components/UsersPage.tsx

Closes #934 
This PR adds the UI self-deletion for free CLOUD users. This PR also consolidates some of the users and about page logic to clean up the current implementation and make things a little more DRY. This PR also updates some of the notification logic to allow for an extra `styles` object to be passed in to allow for custom styling to be applied to the children (that are now being wrapped in a span). This feature should only appear if the feature flag is turned on AND if the user is a free user. In the event that the user has more than one user associated with the organization and they try to delete the account, they will hit this warning:
If they don't have more than one user on their account they will go through the typical flow:

feat: free user account self-deletion

---

mocks/dummyData.ts
src/shared/utils/relativeTimestampFormatter.ts
src/tasks/components/TaskRunsCard.tsx
src/tasks/components/TaskRunsPage.test.tsx
src/utils/datetime/formatters.ts

Connects #1844
removes [`fromNow`](https://momentjs.com/docs/#/displaying/fromnow/) calls to moment and uses our [relative formatter.](https://github.com/influxdata/ui/pull/1944)

chore: remove moment.fromNow calls

---

cypress/e2e/cloud/home.test.ts
src/onboarding/containers/LoginPage.tsx

Closes #https://github.com/influxdata/influxdb/issues/18362
This one's been on my mind. We shouldn't allow the user to access the login page once a valid session has been established since that can be a confusing state to be in, both for the user and for the browser in terms of establishing a session. This PR basically utilizes the existing session management for pre-auth users and makes a request to check whether a user has an established session prior to displaying the login page. If the user already has an established session, we just return them to whichever route they came from

feat: redirect away from the login page when a user has a valid session

---

mocks/dummyData.ts
src/tasks/components/TaskRunsCard.tsx
src/tasks/components/TaskRunsPage.test.tsx
src/types/tasks.ts

Closes #1864 
**Before** 
The `created by` section of task runs card shows the task name 
**After**
`Created by` shows the creator of the task.

fix: task runs card's created by shows creator of task

---

src/timeMachine/selectors/index.ts

completes part of #1844
This PR deletes the `moment` library's subtract usage and redoes the logic using the vanilla `Date` library, in the selectors/index.ts

refactor: replace moment.subtract in selectors/index.ts 

---

src/operator/OrgOverlay.tsx
src/operator/context/overlay.tsx

Straightforward bug fix. Moved the useEffect for the overlay context into the org overlay view layer. This move ensures that the orgId will be set prior to getting the info, whereas making it a concern of the context was making the orgID undefined in certain situations. This ensures that the orgID will always be defined.

fix: moved the useEffect to get org info into the view layer

---

src/flows/pipes/RawFluxEditor/functions.tsx
src/flows/pipes/RawFluxEditor/view.tsx
src/timeMachine/components/TimeMachineFluxEditor.tsx
src/timeMachine/components/fluxFunctionsToolbar/FluxFunctionsToolbar.tsx

Closes #1754 
Functions were being rendered multiple times on every keystroke and was causing a slow typing experience. I wrapped it in `useMemo` and now it only renders when the Function's search box is used. 
Before: 1 keystroke = 2 renders = 40ms render time
After: 1 keystroke = 0 renders = 16ms render time
Before: 1 keystroke = 10 renders = 47ms render time
After: 1 keystroke = 0 renders = 5ms render time
Before:
https://user-images.githubusercontent.com/6411855/125136684-28560200-e0c0-11eb-8b90-ac102ba1d21c.mov
After:
https://user-images.githubusercontent.com/6411855/125136787-53d8ec80-e0c0-11eb-85c3-86c86d4d7dc5.mov

chore: don't re-render functions on every keystroke

---

src/operator/OrgOverlay.tsx
src/operator/context/overlay.tsx
src/operator/utils.test.ts
src/operator/utils.ts

Closes #1977 
Fixes the issue where the displayed limits for a max duration were in nanoseconds and not hours

fix: format the operator max duration policy for limits on an org to display hours and not ns

---

src/shared/utils/duration.test.tsx
src/shared/utils/duration.ts

Completes part of #1844 
This PR deletes the `moment` library's subtract usage and redoes the logic using the vanilla `Date` library.

refactor: remove moment.subtract() from duration.ts

---

src/visualization/types/SimpleTable/style.scss

Closes #1949 
**Issue** 
With the flag simpleTable on:
The raw data view doesn't use a monospace font and so it's hard to quickly read which number is large down a column.
For example:
**Fix**
Raw data view displays table in monospace font.

feat: added monospace font to simple table

---

src/writeData/components/telegrafPlugins/cassandra.md
src/writeData/components/telegrafPlugins/httpjson.md
src/writeData/components/telegrafPlugins/influxdb_listener.md
src/writeData/components/telegrafPlugins/jolokia2.md
src/writeData/components/telegrafPlugins/systemd_units.md

Closes https://github.com/influxdata/ui/issues/1941
fixes broken links in telegraf plugin links

fix: broken links in telegraf inputs

---

src/shared/apis/singleQuery.ts

The issue was that when you click on `Submit` and before the query finishes, you click on `Save`, the query still gets cancelled but due to the discrepancy in syncing of the 2 states the loading spinner keeps on going.
I dug deeper into the issue and found that we aren't really rejecting when we need to reject a promise. Instead, we are calling a reject function which we created. So, I am adding a fix which we may or may not end up keeping. The fix is to actually reject after running our custom reject function. This actually acknowleges that the promise is finished and is not in lingering state. Makes sure a resolve or a reject has happened. There's a side effect(maybe?) which is kind of unexpected but below is the gif showing that. Basically, the cell we were trying to edit(save) will …

fix: fix cancel query issue in #1935

---

src/buckets/components/BucketCard.tsx
src/buckets/components/DemoDataBucketCard.tsx
src/flows/components/FromTemplatePage.tsx
src/shared/selectors/flags.ts

@Asalem1 had the best idea this morning and i couldn't wait to see it made, so i made it. when you click on a bucket, instead of opening up in crummy old data explorer, it makes a new notebook for you with the bucket selected in the metric selector. This specific link accounts for ~25% of the unique traffic to data explorer, so we should expect it to move the adoption needle a bit more organically.
check it out with `influx.set('exploreWithFlows', true)`

feat: open buckets in notebooks

---

cypress/e2e/shared/explorer.test.ts
src/visualization/types/Gauge/Gauge.tsx
src/visualization/types/Gauge/options.tsx

Closes #1858 
The gauge value and the gauge axis can and should have their own separate prefix and suffix. This is the best way to fix it.
https://user-images.githubusercontent.com/10736577/125709095-447b0555-c7f1-49aa-8cd0-47d47e8c605d.mp4
Screenshot of the updated view options

fix: separate prefix and suffix from tickPrefix and tickSuffix

---

src/visualization/types/Gauge/constants.ts
src/visualization/types/Gauge/view.tsx

Closes #2021 
Updates gauge arc length to 1.5π and moves the gauge value slightly lower to accommodate long prefix/suffix combinations

fix: update Gauge arc length to 1.5 PI when using Giraffe

---

src/timeMachine/components/QueryTab.tsx

Closes #1520
Updated the visibility logic to allow already hidden tabs to display the visibility icon

fix: data explorer tab visibility edge case bug

---

src/flows/context/flow.list.tsx
src/writeData/components/fileUploads/CsvMethod.tsx

Closes #https://github.com/influxdata/influxdb/issues/20692
I think this pattern might not be more helpful than the previous implementation in a case like tools where there's 1 org and the only difference will be the timestamp? 🤷🏽

feat: give notebooks default names

---

src/timeMachine/components/ViewTypeDropdown.tsx
src/visualization/components/ViewTypeDropdown.tsx

everything was working great until i learned that jest needed to be updated in order to run any tests that involve visualizations, and that i had to save to new visualization type through the timemachine endpoints... which currently isn't supported by the api!
while those things get sorted, lets just disable simple table as a visualization for data explorer for now

fix: disable simple table until backend is in there

---

src/dashboards/selectors/index.test.ts
src/dashboards/selectors/index.ts

Closes #2019
part of : #1844
This PR removes `moment` from `dashboards/selectors/index.ts`

refactor: remove moment from dashboards/selectors/index.ts 

---

src/App.tsx

This was the function that errored earlier today and caused a prod incident.  This will make it so that even if it errors the rest of the site doesn't go down.

fix: add try/catch so that no matter what things don't break

---

src/dataExplorer/components/SaveAsCellForm.tsx
src/dataExplorer/components/SaveAsOverlay.tsx
src/dataExplorer/components/SaveAsTaskForm.tsx
src/flows/pipes/Visualization/index.ts
src/tasks/components/TasksHeader.tsx
src/tasks/components/TasksList.tsx

there were a couple of questions we couldn't answer about how the current task interfaces are being used within the ui, so this fills in a few gaps for us. the main new events are:
`Task Created From Dropdown`: this event shows up when you click "create task -> new task" on the task list page and should help answer questions about how many users both enter through the tasks page and demonstrate the intent to create a task, while isolating the intent from the success/failures of the individual task editing interface.
`Data Explorer Save as Task Submitted`: this event is fired when we create a task from the data explorer page through the "save as" button in the top. This should allow us to quantify how many users are viewing tasks as an end state for their current query.

feat: adding task events

---

package.json
src/annotations/components/annotationForm/AnnotationForm.tsx
src/annotations/components/annotationForm/AnnotationMessageInput.tsx
yarn.lock

Closes #1124
removed 'enter' as the submit shortcut in the annotations form, thus allowing carriage returns to be entered into the textarea.
requires giraffe 2.16.1 for display of multi-line annotation tooltips

fix: allow multi line annotations

---

src/flows/pipes/Columns/view.tsx

Closes #
Fixes issue where empty columns table did not show message that its empty, potentially confusing

fix: empty columns message

---

src/buckets/components/BucketOverlayForm.tsx
src/buckets/constants/index.ts

Closes #2078
Just removing some unnecessary code I came across when trying to remove `moment` from our codebase. (#1844)

refactor: remove dead code from BucketOverlayForm

---

src/tasks/components/TaskRunsRow.tsx

Closes #2067
Use of `getRuns(taskID)` is following approach from the function `handleRunTask()` in `TaskRunsCard.tsx`
https://user-images.githubusercontent.com/39343323/126373776-cfa4bfe6-27ca-4914-b8d3-799c9580e532.mov
https://user-images.githubusercontent.com/39343323/126374199-8977d8a5-c1e4-4889-a970-1a02064e69ad.mov

fix: task run retry no longer opening editor

---

src/dashboards/selectors/index.test.ts
src/dashboards/selectors/index.ts
src/shared/utils/dateTimeUtils.ts

Closes #1830 
checks if the time string actually needs converting before converting it.
keeping conversion in if necessary for future timezone/flux work.

fix: #1830 toggling time fix

---

src/writeData/components/ClientCodeCopyPage/index.tsx

Closes #2076 
Now looks like this:

chore: remove code sample options from export to client library modal

---

src/annotations/components/AddAnnotationOverlay.tsx
src/views/selectors/index.test.ts
src/views/selectors/index.ts

Closes #2122
Notes for the reviewer:
* the issue we made (#2122) asks for a method called `getTimeFormatFromCell`, but since we were putting that method in the `views/selector`, I thought we should name it as `getTimeFormatFromView`. Not sure what the hierarchy is, is `Cell` a `View`? i noticed that the `cellID` and the view's `id` were the same. 
Also since the `timeFormat` was in `resources.views.view.properties.timeFormat` 
Added the unit tests to test the function as well.

feat: adds selector method to return the user's preferred time format for a view

---

src/variables/utils/astim.ts

Closes #2084
**Problem**
As described in #2084, ASTIM has been including all the variables found in the query regardless of their source object.
**Proposed Solution**
ASTIM only reads variables from the system object(`v`). There's a caveat that if someone renames `v` to something else, for example: `x=v`, then this fix is going to ignore all the `x.VARS`.

fix: only add v vars and not func vars

---

src/visualization/utils/getFormatter.test.ts
src/visualization/utils/getFormatter.ts

Closes #2123
Just a small bug fix, for when the API returns an empty string, not `undefined` for the timeFormat, we need to force it to be `DEFAULT_TIME_FORMAT`

fix: force timeFormat to be DEFAULT_TIME_FORMAT when it is an empty string

---

src/shared/utils/vis.test.ts
src/shared/utils/vis.ts

Closes #2096 
The reason maps was failing with `invalid Latlng object` is because we are trying to render Leaflet through giraffe even when lat/lon doesn't match the type of coordinates. So in this pr, I have added if the column chosen by the user is not type number, then throw an error instead of rendering giraffe and failing horrible..

fix: throw error when maps coordiates are NaN

---

src/shared/constants/fluxFunctions.ts

Updates the flux functions list to include the new sample data package.
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/influxdb-sample/

feat: add sample flux package

---

src/tasks/components/TasksList.tsx

The `TasksList` isn't the most performant Component. This is a small change, but has a noticeable affect with task lists > 120 or so.

fix: don't create an anonymous function on every render call

---

src/shared/utils/dateTimeUtils.ts
src/timeMachine/selectors/index.ts

This reverts commit 4e09f30d because that commit caused a bug in production. Temporarily reverting to diagnose locally.

revert: remove moment from timeMachine/selectors/index.ts

---

scripts/run-monitor-ci-tests.bash

actually set is_failure flag when we're looping over the failed job names

fix(ci): set is_failure for each failed job

---

cypress/support/commands.ts

Closes #1442 
Firefox no likey getting redirected to the dex url. So...lets not go to the app until after we're logged in!
The actual code change is easier to visualize if you add the `?w=1` param: https://github.com/influxdata/ui/pull/2188/files?w=1

fix: make firefox not hate us

---

docker/Dockerfile.chronograf

noticed that docker was complaining when building the chronograf image for me locally. Docker wants the env vars to have a value. Setting the defaults to be empty seems to do the trick
https://github.com/moby/moby/issues/34806#issuecomment-620678422

fix: docker requires envs to have a value

---

cypress/e2e/shared/explorer.test.ts
cypress/e2e/shared/tasks.test.ts
src/tasks/components/TaskCard.tsx

Closes #2128
After clicking the task name, user is navigated to the task runs page now instead of the edit task page. `View task runs` from gearbox list also replaced with `Edit run`, which opens up the edit window.
https://user-images.githubusercontent.com/39343323/127032271-8fcb2548-d332-4095-a0a9-16525e4f00fb.mov
https://user-images.githubusercontent.com/39343323/127031583-baad9376-a500-42f7-8847-7240f0b99c39.mov

feat: changed navigation to edit task to view task runs

---

src/visualization/types/Heatmap/options.tsx
src/visualization/types/Histogram/options.tsx
src/visualization/types/Scatter/options.tsx

Closes #2182
Updates the `setDomain` function for histograms and heat maps to correctly set the value as a number rather than a string.
I confirmed this works for saving a histrogram and heatmap on both OSS and remocal.

fix: send correct type of value when updating domain for histograms and heat maps

---

src/authorizations/components/redesigned/TokenList.tsx
src/authorizations/components/redesigned/TokenRow.test.tsx
src/authorizations/components/redesigned/TokenRow.tsx
src/authorizations/components/redesigned/TokensTab.tsx
src/utils/datetime/formatters.ts

Closes #2102 
With token redesign feature flag on (influx.toggle('tokenUIRedesign')), the resource card looks like this.

feat: redesigned tokens resource card

---

src/pageLayout/constants/navigationHierarchy.ts

Closes #2211 
There's an expanded view of the left navigation area.  This adds the Secrets functionality to show there if the appropriate feature flag is enabled.

fix: Add Secrets to expanded left nav

---

src/utils/datetime/formatters.test.ts
src/utils/datetime/formatters.ts

Closes #2202
This PR adds the functionality to make the date time formatter's hourCycle to be h23. Currently by default, its h24, which means the time formatting formats in the range : `01:00 - 24:59` 
The more familiar one, h23, formats it from `00:00 - 23:59`. This was the app's default formatting as well when using `momentjs`
Some reviewer notes: 
* I refactored the settings for the formatter, previously, the `dateTimeOptions` had the following parameters:
```
const dateTimeOptions: any = {
hour12: true,
day: '2-digit',
month: '2-digit',
year: 'numeric',
hour: 'numeric',
minute: 'numeric',
second: 'numeric',
}
```
Notice, the `hour12`, set to `true` by default, this felt like it was going against our `DEFAULT_TIME_FORMAT` which says 24h is the default. So instead of turning all the …

feat: make date time formatter hourCycle h23; minor refactor

---

src/authorizations/components/redesigned/TokenList.tsx
src/authorizations/components/redesigned/TokenRow.tsx

Closes #1933 
When a user selects an existing token from the main tokens page and clicks Clone,
a new token is generated with the same resources and permissions as the existing token, with the following naming convention in its description: {description} (clone #)

feat: added clone functionality to TokenRow

---

src/utils/naming.test.ts
src/utils/naming.ts

fix(cloning): guard against whitespace being added to cloned resource names

---

cypress/e2e/cloud/orgs.test.ts
cypress/e2e/cloud/usage.test.ts
cypress/support/commands.ts

fixes some cypress failures with firefox specifically now that we're going to be running the cloud tests against firefox

test: fix firefox test failures

---

src/timeMachine/selectors/index.test.ts
src/timeMachine/selectors/index.ts

Closes #2053
Part of #1844 
This PR removes `moment` from the timeMachine selectors.
We attempted this in another PR [#2054], here is what happened and why it didn't work:
* Our tests use `moment js` to test anything with time. The `Date` implementation of `Date.valueOf` is slightly different than `moment.valueOf`. To make the tests pass, I did a bunch of things to change timezones and time manipulation, which passed the tests, but was wrong. So that caused a bug in the production where we had empty spaces of graph visualizations. [[Slack conversation thread of bug]](https://influxdata.slack.com/archives/CLHATC50E/p1627583826386700)
This time, we replace the moment in the test as well, that way tests pass and the logic is correct as well. 
Screenshot. no blank spaces this time:

refactor: replace moment in timeMachine/selector/index.ts

---

src/flows/pipes/RawFluxEditor/index.ts

Closes #2205
DON'T PANIC
I can't actually say if this resolves ALL issues, I feel like we should add some error boundaries on panels just to make sure that things aren't inoperable when a panic or error is returned but this resolves the case that a broken flux query broke the notebook

chore: wrap the flux parser in a try catch so panics dont crash the app

---

scripts/run-monitor-ci-tests.bash

This should fix the "exit status 3" bug in our pipeline. The issue was that when you retried the pipeline more than once, it would find multiple failed workflows with the same name when it was expecting to only find one. The solution was to grab the most recent failed workflow.

fix: exit 3 bug in CI script

---

cypress/e2e/util/annotationsSetup.ts

This attempts to address this type of e2e test failure: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3581/workflows/85bfb072-17ec-4630-b264-9f56bb5ebee5/jobs/41635
note: this leaves `.focused()` in place to see if it has an influence on flakiness in chaining.

test: unchain the steps to create an annotation

---

src/cloud/actions/limits.ts

This addresses an issue that cropped up with the recent work to centralize queries in yaml definitions. The previous implementation wasn't refactored for status checks and assigned the response as the limits data, rather than the returned data as the limits data.

fix: update limits func to account for errors and status

---

src/alerting/components/TimeTableField.tsx
src/annotations/components/annotationForm/AnnotationForm.test.tsx
src/annotations/components/annotationForm/AnnotationForm.tsx
src/functions/components/FunctionRunLogRow.tsx
src/functions/components/FunctionRunsRow.tsx
src/shared/components/dateRangePicker/DatePicker.tsx
src/shared/constants/index.ts
src/tasks/components/RunLogRow.tsx
src/tasks/components/TaskRunsCard.tsx
src/tasks/components/TaskRunsPage.test.tsx
src/tasks/components/TaskRunsRow.tsx
src/utils/datetime/FormattedDateTime.test.tsx
src/utils/datetime/README.md
src/views/selectors/index.test.ts
src/views/selectors/index.ts
src/visualization/types/SingleStat/view.tsx
src/visualization/types/SingleStatWithLine/view.tsx
src/visualization/types/Table/transform.ts
src/visualization/utils/getFormatter.test.ts
src/visualization/utils/getFormatter.ts
src/visualization/utils/timeFormat.ts

Closes #2254
A simple refactor so that cypress e2e tests can use the `DEFAULT_TIME_FORMAT`.

refactor: move DEFAULT_TIME_FORMAT to src/utils/datetime/constants

---

src/visualization/context/pagination.tsx
src/visualization/types/SimpleTable/PagedTable.tsx

Closes #2170
The reason why there were duplicate pages with only a single row of data in #2170 is due to `setTotalPages(Math.ceil((result?.table?.length ?? 0) / size))`. Because `size` refers to how many rows are in the table not how many can fit, going to the last page where there is a partially filled table will cause the calculation to set the total number of pages to be much larger than what it should be. In the calculation of what rows appear on that page, if the page selected is out of the true bounds (meaning the math will result in a unexpectedly large offset), it will default it to show only the last row of data, which is what happened in #2170.
The change to setMaxSize has little to do with the issue, but it causes issues when resizing as well. …

fix: SimpleTable resizing bug that creates identical pages

---

cypress/e2e/cloud/home.test.ts

Home page test is very flaky and it's because of the data not getting written to monitoring bucket in time. Thus resulting in variable number of rows in the Alerts Activity dashboard.
Instead of writing and reading data, we decided to mock the response of the specific query and make the test a lot simpler.

chore: simplify home page test

---

src/authorizations/actions/creators.ts
src/authorizations/actions/thunks.ts
src/authorizations/components/redesigned/DisplayTokenOverlay.tsx
src/authorizations/components/redesigned/TokenRow.test.tsx
src/authorizations/components/redesigned/TokenRow.tsx
src/authorizations/containers/RedesignedTokensIndex.tsx
src/authorizations/reducers/index.test.ts
src/authorizations/reducers/index.ts
src/overlays/components/OverlayController.tsx
src/overlays/components/index.tsx
src/overlays/reducers/overlays.ts
src/types/resources.ts
src/types/schemas.ts

Closes #2217 
After a user clones a token successfully, an Overlay with the generated token and a copy button renders on UI.
The Overlay contains a warning telling user to copy token as it will be the only time they will see it. 
https://user-images.githubusercontent.com/66275100/128400683-732d8dc9-d6e5-4a84-9b68-1fd7ba901ddd.mov

feat:  added clone token overlay

---

src/buckets/components/BucketCardMeta.test.tsx
src/buckets/components/BucketCardMeta.tsx

* added unit tests
* if the data is not there, then  the  'implicit' type is the default
Closes #1578

feat: adding schema type (implicit or explicit) to bucket page

---

cypress/e2e/cloud/home.test.ts

This test in the cloud/home test suite is incompatible with remocal because dex is hosted at a different domain than our UI. When the app attempts to redirect the user to this second domain, Cypress freaks out and fails the test. I need this test suite to pass in remocal so we can switch to using remocal in our pipeline full time, so I'm skipping it for now
I filed an issue to investigate this further: https://github.com/influxdata/ui/issues/2272

test: skip incompatible test for now

---

package.json
yarn.lock

Closes https://github.com/influxdata/influxdb/issues/22080
Cherry-pick of a847c264e5e1be800adb2b63e4496128a18b6471
Updates the OSS-2.0 branch `flux-lsp-browser` to the latest version since the OSS 2.0.8 release will use the latest version of flux.
Note that the CI for this branch is currently very minimal since the e2e tests run on the OSS side when we update the pinned release number there.

build(lsp): Upgrade flux-lsp-browser to v0.5.53

---

src/flows/pipes/Visualization/index.ts

fixes an issue that came up in tools were `|> group() |> count() |> group()` (the only way to add things in our system) leaves you with no `_time` column, rendering and error when you run single stat and gauge visualizations with the changes from #2253. ` |> last()` doesn't seem to cause this

fix: move to last

---

src/flows/pipes/Markdown/style.scss
src/flows/pipes/Markdown/view.tsx

Closes #2070 
Reenables autosizing of the markdown panel

chore: undo resizing of the markdown

---

src/writeData/components/WriteDataHelperTokens.tsx

Closes #2199 
tokens without descriptions are showing up on the client libraries page with an empty description. 
Before: 
After: 
pr fixes this issue by importing `DEFAULT_TOKEN_DESCRIPTION` and using it in place of no name tokens.

fix: added default token description

---

src/flows/pipes/RawFluxEditor/view.tsx

Closes #2240
this just grabs the value directly from monaco at injection time instead of passing it all around the contexts and reducers and stuff

fix: query.text was being updated in place

---

src/tasks/components/TaskHeader.tsx
src/tasks/components/TaskImportOverlay.tsx
src/tasks/components/TasksPage.scss
src/tasks/containers/TaskPage.tsx

we think that people would want to build tasks in notebooks more than the current task creation interface, they just don't know how to. but we dont know that for sure, so lets give users who have demonstrated that they intend to create a task the option to use a notebook instead. if they dont want to, they just dont have to click on the link.
this experiment is to drive more people who want to create tasks through notebooks, and to validate that the task creation interface is better in notebooks. we can measure success by the conversion of people who generate a task through the notebook interface. more sustained tasks exported... the more confidence we have in depreciating the existing task interface. if a bunch of people click on the link and no more tasks are generated, we know we have …

feat: add more events and throw in an experiment to run

---

src/flows/templates/types/notification.ts

Closes #2152
Creates a prefab notebook that currently is "alert" in name only bc its waiting on the ticket that will rename all notification components to alert 
https://user-images.githubusercontent.com/29473622/128898029-c0d252dc-9e4f-477e-a896-8b56cad5c1cb.mov

feat: alert prefab notebook

---

src/flows/shared/FriendlyQueryError.tsx

Closes #2224 
This PR updates the FriendlyErrorQuery message to properly handle click events of the aggregate function selector to update the aggregate function that's currently selected

fix: aggregate type error selectionbr

---

src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/authorizations/components/redesigned/TokenList.tsx

Closes #1964 
Followed `CustomApiTokenOverlay.tsx` to set up the overlay frame.

feat: changed view overlay to edit overlay

---

src/buckets/components/CreateBucketForm.tsx
src/buckets/components/CreateBucketOverlay.tsx
src/buckets/constants/index.ts

As part of #1555 
Currently, the form that creates a new bucket is implemented directly into its own overlay. Soon, there will be multiple places in the ui that can create new buckets, and each of these places may use the overlay a little differently. Therefore, let's separate the overlay from the form so that a common form can be re-used.
This is what happened:
- almost all of the code for `CreateBucketOverlay` moved to `CreateBucketForm` (new file)
- only the `onClose` method was not moved
- `CreateBucketForm` contains all of the previous logic, except `onClose` which is now a prop
- `CreateBucketOverlay` imports the new component and passes in `onClose`

feat: move create bucket form into its own component

---

cypress/e2e/shared/dashboardsIndex.test.ts

Closes #2338 
The beforeEach was flaky because some of the async tasks were happening in parallel and the beforeEach was terminating prematurely. Chaining these async functions with `.then(() =>` makes sure that the beforeEach finishes when all the tasks are complete, making it more stable.

test: handle async fns better in beforeEach

---

src/shared/components/dateRangePicker/DatePicker.tsx

Closes: #2347
Part of #1844 
Now that we have a validator in our codebase, we can replace the moment's isValid in the datepicker.
_Video of the datepicker uploading soon_

refactor: replace isValid from the datePicker

---

cypress/e2e/cloud/pinned.test.ts
cypress/e2e/shared/tasks.test.ts
cypress/index.d.ts
cypress/support/commands.ts

Closes #2357
This hopefully addresses a flakiness in the pinned item tests related to tasks - i was seeing failures where it was attempting to hit the nav bar to get to tasks and it wasn't going there, so i made it a bit more explicit. Also, there was a function being imported from the tasks tests that was causing the pinned tests to run the entire tasks suite again, so i moved that to a command.

chore: fix flaky pinned tests

---

src/flows/components/FromTemplatePage.tsx

We are leaning into creating notebooks from a template as a way to improve the conversion rates of some key workflows we'd like to focus on. To be able to properly segment the data, we need to know where our users came from. this adds that event

chore: add template event

---

src/annotations/components/annotationForm/AnnotationTimeInput.tsx

Closes #2354
Part of #1844 
Replace moment.isValid in the AnnotationTimeInput

refactor: replace isValid from the AnnotationTimeInput.tsx

---

cypress/e2e/shared/secrets.test.ts

The secrets test was failing on the cy.reload() and it seems most likely that this was because the feature flag had not persisted to redux yet.  I couldn't intercept the cy.upsertSecret as the API returned too quickly for cy.wait.
So I've added a check on the value of the response status code from the API hoping that will be enough extra time for Redux to do its thing.
Closes #2361

fix: add check for response status to fix flaky test

---

src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep.tsx

Closes #2371
The component that controls the overlay sends `''` (empty string) to the new telegraf overlay. Using `??` (which only fails on `null` and `undefined`) will erroneously fail this check.

fix(telegraf): use logical or instead of nullish operator to allow empty strings

---

src/shared/components/dateRangePicker/DatePicker.tsx
src/shared/utils/dateTimeUtils.test.ts
src/shared/utils/dateTimeUtils.ts

Closes #2366
Part of #1844
Removes moment from `DatePicker`.

refactor: replace moment toISOString from the DatePicker.tsx

---

src/authorizations/apis/index.ts

After toggling the feature flag on in tools and production without any reported issue of the being incorrectly redirected, figured it was time to pull this flag out

chore: remove useGeneratedAuth flag

---

src/shared/components/VersionInfoOSS.tsx

Closes https://github.com/influxdata/influxdb/issues/22210
This is a small update to ensure that the OSS version info is always fetched anew when a component that displays the version info is rendered.
Previously it would only fetch the version info if the info was not currently present in state. This has proven to be problematic when people do OSS updates, since the state from the previous version was being re-generated from local storage which included the old version info, rather than the new version info. This would make it seem like the UI had not been updated with the OSS update, etc.
Making a new API call every time the version info component is rendered is doubtlessly less efficient than storing the information for use between renderings, but will ensure a consistent visual …

fix: always fetch latest OSS version info

---

src/visualization/types/Map/index.tsx
src/visualization/types/Map/view.tsx

This PR attempts to fix the issue where displaying the `maps` visualization was rendering an `InfluxDB Error has occurred`, but where the data was actually there. It appears as though some of the conditional import that was being used to separate the OSS build from the Cloud build contributed to these failures, this PR is an attempt to see if that separation is still necessary, and whether removing that conditional logic resolves this issue.
Unfortunately, every attempt made to query the maps endpoint returned a 500 error in remocal locally so I'm not certain if there's a gap in implementation that needs to be filled for remocal, or if that's to be expected anywhere but in production

fix: remove conditional imports to get maps to not error when requesting data

---

cypress/support/commands.ts

Noticed a bunch of tests were failing because the request to `/api/v2/me` was being aborted. I think this is because we were missing an explicit return in the `cy.signin()` chain. So basically it is possible that the signin flow isn't fully completed before the test starts execution.

fix: add return to handle promise correctly

---

cypress/e2e/util/annotationsSetup.ts

Closes #2334 
>There is another way to fix our flaky test. Whenever you write a longer test, **we recommend alternating commands with assertions.**
https://docs.cypress.io/guides/core-concepts/retry-ability#Alternate-commands-and-assertions

test: attempt to fix flakiness by alternating commands and assertions

---

cypress/e2e/cloud/pinned.test.ts
src/dashboards/components/dashboard_index/DashboardCard.tsx
src/flows/components/header/index.tsx
src/flows/pipes/Notification/styles.scss
src/flows/pipes/Notification/view.tsx

Closes #
This change should address the flakiness in the firefox pinned items tests, hopefully, along the way, but the main point is this:

chore: change notebooks alerts panel endpoints to dropdown and fix firefox tests for pinned items

---

cypress/e2e/util/annotationsSetup.ts

closes #2344
closes #2369
Cypress apparently has an issue where it will render the same component in the DOM twice, then fail tests that target that element because it assumes it's targeting a single element. We were seeing these issues in our annotations e2e tests on remocal where the annotations overlay would be rendered twice.
The fix is to target the visible instance of the overlay. I tested this by running the suite 15 times. There were three failures: one chunk loading issue and two timeouts from my computer being taxed, but no failures from detached DOM elements.

test(annotations e2e): target visible overlay component to avoid flakiness

---

cypress/support/commands.ts

Still trying to hunt down the cause for the timeouts during the initial UI page load in CI. The /api/v2/me requests are being aborted which means that we're navigating away from the root page prematurely. And because the request is aborted, the auth flows gets screwed up which causes the infinite spinner.
Going to try and wait for the page to load after the initial `cy.visit('/')` to see if that helps. I also cleaned up the handling of promises in the loginViaDex function

fix: wait for root page to load before continuing test

---

cypress/e2e/cloud/orgs.test.ts

Due to [this issue](https://github.com/influxdata/ui/issues/2427) we need to clear local storage before visiting the home page after deleting the org. This bug exposed itself after [this commit](https://github.com/influxdata/ui/commit/8ace8ccc219795a9000364eab5fd05b00f932952) forced all tests to wait for the homepage to load before beginning test execution (which is an intentional change that we want to keep).

test: add workaround for broken orgs test due to bug

---

cypress/e2e/util/annotationsSetup.ts

Closes #2334
Interacting with the `edit-annotation-message` element makes these tests flaky. We've found no way to ensure that the input box doesn't become detached from the DOM. So instead of editing the annotation via the UI, we'll edit the request body of the API request to update the annotation.

test: edit the annotation via api body instead of ui

---

.eslintrc.js
cypress/e2e/shared/telegrafs.test.ts
src/telegrafs/components/TelegrafOutputOverlay.tsx
src/timeMachine/components/WindowPeriod.tsx

Closes #956
Turns on lint checking for nested ternary operators

chore(lint): no nested ternaries

---

src/writeData/components/PluginCreateConfigurationWizard.tsx

Part of #1555 
BEFORE, too wide:
AFTER, much better:

chore: reduce the size of the first overlay in Plugin page configuration creation

---

src/shared/components/TimeSeries.tsx

Closes #1829 
When scrolling up from the bottom of a dashboard with graphs that aren't visible after a change to the date dropdown, the graphs that came into view would erroneously not reload. They now reload
https://user-images.githubusercontent.com/146112/130538743-56fd7a61-d9c7-4a38-8c55-cd2c3806438d.mov

fix: reload dashboard cells when they become visible while scrolling up

---

package.json

Now that remocal namespaces are not limited to starting with "twodotoh-dev" let's update the script to allow e2e tests to run locally with any namespace name.

test: update test e2e remocal script

---

src/flows/pipes/Notification/Endpoints.tsx
src/flows/pipes/Notification/PagerDuty.tsx
src/flows/pipes/Notification/view.tsx
src/shared/copy/notifications.ts
src/timeMachine/components/SubmitQueryButton.tsx

Closes #2287
This PR adds the ability for a user to send a test notification with integrated services like making an http post request, a pagerduty alert, and a slack notification.

feat: integrate test notifications for endpoints

---

cypress/e2e/util/annotationsSetup.ts

Closes #2468
The problem is that that overlay renders multiple times, from my understanding, and this causes the cypress element to be dead, and hence the complaint. 
This seems to be a common problem, Cypress is not automatically re-querying the element. [[Issue in cypress](https://github.com/cypress-io/cypress/issues/7306)] The best hacky solution seems to be using `.click({force: true})`. It is also a pattern in other e2e tests in our app. 
They [Cypress's team] said they will fix this issue, but it will most likely be after some time. The exact comment: [[Link](https://github.com/cypress-io/cypress/issues/7306#issuecomment-906547691)]
> Our team does have plans to address this issue. As with all the other long standing issues, it is very complex to fix and would likely introduce …

fix: flakey annotation xy, delete test

---

src/flows/components/Sidebar.tsx

Related #2469 
Not sure what caused the original issue and I was unable to reproduce it after trying all morning. But I was able to add the broken notebook into my env and from there, found the reason why the broken panel couldn't be deleted. Only happens when the `flowSidebar` flag is on. 
before:
after:
https://user-images.githubusercontent.com/6411855/131393217-640ff5ea-5b80-47c6-8ef6-403634ed886e.mov

fix(notebooks): should be able to delete broken panels

---

src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/authorizations/components/redesigned/TokenList.tsx

Closes #1965 
**proposed changes**: 
- user can change the status of a token from active to inactive or vise versa 
- user can now update the description of a token and clicking save will update token 
- saving a token sends a `patch` request to the api and updates existing token 
- user can now click on cancel button and be directed back to Tokens List
https://user-images.githubusercontent.com/66275100/131388696-5f23d1d5-3bc2-4db2-9da3-d247bb07d6b1.mov

feat: Edit overlay toggle for token status

---

src/tasks/components/TaskRunsPage.tsx

Sorting on task runs didn't work on duration - it just didn't sort because it was trying to sort by date instead of by number, which is what the task run duration is.

fix: allow sorting by duration in task runs

---

src/alerting/components/AlertingIndex.tsx
src/variables/selectors/index.tsx
src/variables/utils/hydrateVars.ts

Closes #2439 
`vari` is a read-only variable and that prevents us from overwriting `results` in `vari?.arguments?.values?.results`. So, the solution is to make a deep copy and use it as the variable so that we can overwrite any part of `vari` and its children.

fix: query variable read-only issue fix

---

src/shared/components/Filter.tsx
src/shared/utils/sort.test.ts
src/shared/utils/sort.ts

fix: resources are now sorted naturally

---

src/buckets/components/BucketCardMeta.test.tsx
src/buckets/components/BucketCardMeta.tsx

Closes #2520
Prevents bucket schema info from being shown on OSS, which does not have the concept of bucket schema.

fix: don't show bucket schema info on OSS bucket meta cards

---

src/App.tsx

This way we can toggle it for environments as needed.
The dynamic injection is the expedient method of getting this feature out behind a flag for demonstration purposes. The public key has been provided by Coveo and this was an implementation suggestion that allows us to work with their team on ensuring our integration is working as necessary. This shouldn't introduce any security concerns im aware of, and will allow us to work further with Coveo on developing a future-proof solution for integration
While this does represent a diversion from our usual implementation patterns, it should be noted that this suggestion was provided directly by the Coveo team and allows us to iterate quickly on the feature within a testing context and a public key that they can immediately invalidate should …

chore: add coveo script behind FF

---

src/flows/pipes/Notification/view.tsx
src/flows/pipes/Schedule/ExportTaskButton.tsx
src/flows/pipes/Schedule/ExportTaskOverlay/index.tsx

Closes #2522
This PR updates the overlay title to match the button whenever a user clicks the export alert task button.

chore: update export as alert task header and button text

---

src/buckets/components/createBucketForm/BucketOverlayForm.tsx
src/buckets/constants/index.ts

Closes #2326
Adds a check to invalidate bucket names that are only white spaces.
https://user-images.githubusercontent.com/18511823/132388304-6efb040c-ff26-463f-824b-5568217f29ad.mov

fix: add check to not allow only whitespace as bucket name

---

scripts/publish-oss-release.bash

Using the `>>` operator for adding the checksum of the built UI assets for OSS would result in a new checksum being appended to the file if the checksum file already exists. This would cause the checksum file to be invalid upon upload. This changes to the `>` operator, which will overwrite the contents of the file if it already exists.

build: replace OSS UI checksum instead of appending

---

src/visualization/types/Table/view.tsx

Closes #2569
Passes timezone information to the giraffe table graph.
Screen shot:

fix: pass time zone information to giraffe table graph

---

package.json
yarn.lock

To bring in some UI bug fixes [influxdata/idpe#10645], the solution to which went into `giraffe`, we need to update the version in UI.

chore: install giraffe 2.18.3

---

package.json
yarn.lock

Brings in a couple of bug fixes and UX improvements across different parts of the visualizations, released in giraffe [2.18.4](https://github.com/influxdata/giraffe/releases/tag/v2.18.4).

chore: install giraffe 2.18.4

---

src/visualization/types/SimpleTable/InnerTable.tsx

Closes https://github.com/influxdata/ui/issues/2035
A simple alignment change to fix the vertical alignment of the table header cell.

fix: valign the table header cell

---

src/shared/components/FluxMonacoEditor.tsx

Closes #2501 
As suggested in the issue below, turning off `scrollBeyondLastLine` fixes the issue where monaco takes up more height than its container, solving our scroll trap issue.
This also applies the same behavior to the data explorer page too which I think is desired.
https://github.com/microsoft/monaco-editor/issues/29
Notebooks:
https://user-images.githubusercontent.com/6411855/132924730-0cdebc55-fc45-48cb-aca5-6d5f54cb9fef.mov
Data Explorer:
https://user-images.githubusercontent.com/6411855/132924641-2001d9b7-a948-4394-b7d9-7253dd00da79.mov

chore: turn off scrollBeyondLastLine to fix scroll trap

---

src/flows/shared/Resizer.scss

Closes #2262 
Simple CSS change to allow for error messages in notebooks to be selectable

fix(notebooks): allow for selectable, copyable errors

---

src/tasks/pagination/TasksList.tsx
src/tasks/pagination/tasksPagination.scss

Closes #2601
Increases the `right` offset of the context menu buttons to account for the pinned items button.

fix: remove x scrollbar from TaskList by accounting for pinned items width

---

src/organizations/components/OrgProfileDeletePanel.tsx

Closes #2424 
We need to start tracking when a user initiates the process of deleting an organization. As soon as a user clicks the `Delete` button in the picture below, we need to send data to snowflake using rudderstack.

feat: track delete initiation

---

src/flows/pipes/Notification/view.tsx
src/flows/pipes/Schedule/ExportTaskButton.tsx
src/flows/pipes/Schedule/ExportTaskOverlay/context.tsx
src/flows/pipes/Schedule/ExportTaskOverlay/index.tsx
src/flows/pipes/Schedule/view.tsx

something happened and we found we had an issue where notification and alert panels were sharing some events, which means we have to throw out all the user data! This was the fastest way i could shoehorn this into here so we could start getting clean data for reading our funnels

fix: cleaning up some events

---

src/buckets/components/BucketCardMeta.tsx

Closes #2612
Fixes key prop warning by rendering components directly instead of in an array

fix: add keys to BucketMeta components that are rendered in lists

---

src/dataLoaders/actions/dataLoaders.ts
src/dataLoaders/reducers/dataLoaders.ts
src/dataLoaders/utils/pluginConfigs.ts
src/types/dataLoaders.ts
src/writeData/components/AddPluginToConfiguration.scss
src/writeData/components/PluginCreateConfigurationCustomize.tsx
src/writeData/components/PluginCreateConfigurationFooter.tsx
src/writeData/components/PluginCreateConfigurationWizard.tsx
src/writeData/constants/contentTelegrafPlugins.ts

Closes #2160 
Closes #2603 
- Consumes the appropriate .conf file for the selected Plugin when creating a Telegraf configuration from a Plugin's page.
- Fixes the flicker after clicking "Finish"
***EDIT: added:
- Removes "Download Config" and "Copy to Clipboard" buttons
- Changes "Agent Name" to "Configuration Name"
- Adds a line of text below the editor to warn user that a default agent and output will be inserted upon saving
https://user-images.githubusercontent.com/10736577/133173348-908b633a-6824-4ec1-ad2a-be0537b7a5f8.mp4
Also updated the customization step by removing some buttons, renaming the label "Agent Name" to "Configuration Name", and adding a note below the editor to let the user know that a default agent and output will be inserted.

feat: consume the input plugin configuration from .conf files

---

src/tasks/pagination/TasksList.tsx
src/tasks/pagination/TasksPage.tsx

Closes https://github.com/influxdata/idpe/issues/11749
Stores the current choice for page and sorting options in the url.
1. Allows a user to reload the page and see the same results they just saw
2. Allows a user to share their page with a teammate who can then see the same results
https://user-images.githubusercontent.com/146112/133320621-000137b3-1d07-4cf1-a144-d2eaa6d4b5e9.mov

feat: store pagination and filter state in url on change

---

cypress/e2e/shared/flows.test.ts
src/flows/pipes/Notification/Expression.tsx
src/flows/pipes/Notification/Expressions.tsx
src/flows/pipes/Notification/index.ts
src/flows/pipes/Notification/view.tsx
src/shared/selectors/flags.ts

Closes #2285
Dynamically populate list of expressions the user can insert into an alert message based on the results of their query. e2e test included.
https://user-images.githubusercontent.com/6411855/133347694-f1db1a6b-8249-491b-afab-758bd295b894.mov

feat(notebooks): expressions sidebar

---

src/authorizations/components/redesigned/EditResourceAccordion.tsx
src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/authorizations/components/redesigned/ResourceAccordion.tsx
src/authorizations/components/redesigned/ResourceAccordionBody.tsx
src/authorizations/components/redesigned/ResourceAccordionHeader.tsx
src/authorizations/utils/permissions.ts

Closes #1966 
Inside the Edit Token Overlay, user can now see permissions for a token. 
The permissions are disabled and not selectable.

feat: Edit overlay permissions

---

cypress/e2e/shared/flows.test.ts
cypress/support/commands.ts

We're still experiencing occasional issues with ui-test-provisioner where it errors saying "cannot provision user XYmcfly@influxdata.com because the user already exists". This PR adds logging to help us understand what's going on when this happens.
It also cleans up the before each of the flows.test.ts file.

chore: add more logs when provisioning user

---

cypress/e2e/shared/flows.test.ts
src/flows/pipes/Notification/Expressions.tsx
src/flows/pipes/Notification/NotificationMonacoEditor.tsx
src/flows/pipes/Notification/view.tsx

Closes #2636 
- fixes monaco syntax highlighting by moving the monaco editor out of the Notification panel's view and into its own component. 
- adds `${ }` around the inserted variables
- handles queries without measurements, fields, tags

fix: monaco syntax highlighting, other expression bugs

---

src/shared/search/DocSearch.tsx

This updates the Algolia docsearch facetFilters to match the new search tag pattern used in the docs. Search will temporarily stop working between the time we deploy the changes to the docs site and reindex our docs and when this change goes live.

feat(docsearch): update facetFilters for docsearch

---

src/writeData/components/PluginCreateConfigurationFooter.tsx

Closes #2625 
Certain plugins no longer have a duplicated `inputs` in the configuration.  See the list in #2625 
Here is an example with `inputs.kubernetes`
https://user-images.githubusercontent.com/10736577/133538891-78e6a22c-57ef-4a39-a106-1d90e26221f2.mp4

fix: remove duplicated input configuration from the backend when telegrafUiRefresh is active

---

src/tasks/pagination/TasksList.tsx

Closes #2641
Fixes the memory leak in paginated tasks, which isn't flagged on and wasn't included in https://github.com/influxdata/ui/pull/2645
Don't set state if the component isn't mounted

fix: fix memory leak in paginated task page

---

src/scrapers/components/CreateScraperForm.tsx

Closes https://github.com/influxdata/influxdb/issues/22512
Small correction for the error message displayed from the basic URL validity check that takes place when creating a scraper.

fix: better error message for scraper URL validity

---

src/flows/components/FlowCard.tsx

Closes #2675 
This PR adds meta key click functionality to open a notebook in a new tab from the index page

fix: meta key to open multiple notebooks from the index page

---

.github/ISSUE_TEMPLATE/bug_report.md

Closes #
Being on bug duty twice I noticed two things:
* Quite a few bug reports were entirely just blank templates, I think it is because the current one is too noisy and the reporter thinks that the bug information is pre-populated.
* As a bug squasher, the report has too many things, unorganized, the greeting message need not be shown in the final report, there was no separation between the bug and the environment information. No hint to let the user know to add screenshots/visual information.
Screenshot

chore: update the bug report template.

---

src/operator/constants.tsx

Closes #2648
This _should_ fix the issue that's being reported. This is a classic example of `get` leading to issues since we're obfuscating where the problem is. There's still the bigger issue of whether this works, since we don't have a way to test this functionality out in local development.

fix: updated the getter in the string to get the right data for the operator page

---

src/flows/pipes/Markdown/view.tsx

Closes #2674 
This PR updates the markdown panel so that clicking on it while the markdown pipe is in `preview` mode doesn't make it editable. It also introduces a new pattern where a flow that's in presentation will display the markdown as being in preview mode

fix: clicking on the markdown doesnt make it editable

---

src/flows/components/EmptyPipeList.scss
src/flows/components/FlowsIndexEmpty.tsx

remove create button from notebooks empty state, change image to grayscale, shrink component size to reduce unnecessary scrolling
Closes #2521

chore: cleanup Notebooks empty state

---

src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx

Closes #1932 
As a user going through token creation process,
when clicking `Generate`, the workflow now moves to Displaying Token Overlay.
The Display Token Overlay contains:
-  A token header
-  An alert displayed to copy token
-  Overlay dismiss button
-  The newly created token
-  Copy to Clipboard Button
https://user-images.githubusercontent.com/66275100/134379151-23b538d1-e813-4644-bb63-42118e5386ab.mov

feat: show newly created token

---

src/dataLoaders/components/collectorsWizard/TelegrafUIRefreshStepSwitcher.tsx
src/dataLoaders/components/collectorsWizard/TelegrafUIRefreshWizard.tsx
src/dataLoaders/components/collectorsWizard/select/SelectCollectorsStep2.tsx
src/telegrafs/containers/TelegrafsPage.tsx
src/writeData/components/PluginCreateConfigurationFooter.tsx
src/writeData/components/PluginCreateConfigurationOptions.tsx
src/writeData/components/PluginCreateConfigurationWizard.tsx

Closes #2663 
Fixes the "Create Configuration" flow from Data > Telegraf. Previously, the selected input plugin would not be saved even though the configuration itself was saved. The update api call was not being made because the component responsible for making that call was unmounted before it could do so.
We fix this by
- creating a new component hierarchy that uses the new telegraf configuration creation wizard properly (does not unmount)
- making minor adjustments to the Footer to allow for the usage from a different flow
- restoring CollectorsStepSwitcher to an earlier version by removing unused code
https://user-images.githubusercontent.com/10736577/134601560-1665d2c9-94d2-438c-a7c1-a3ca66641df5.mp4

fix: use a separate component hierarchy to prevent unmounting during telegraf configuration creation

---

cypress/e2e/shared/flows.test.ts
src/flows/pipes/Notification/Expressions.tsx

Removes "measurements" from the expressions side bar because they aren't valid expressions. If you tried to use them, the Alert will fail with:
```
Error exhausting result iterator; Err: runtime error @41:8-41:74: check: failed to evaluate map function: 37:367-37:389: interpolated expression produced a null value: runtime error @41:8-41:74: check: failed to evaluate map function: 37:367-37:389: interpolated expression produced a null value
```
What it looks like now:

fix: remove measurements from expressions sidebar

---

src/dataLoaders/components/collectorsWizard/select/StreamingSelector2.tsx

Closes https://github.com/influxdata/ui/issues/2711
In the [code here](https://github.com/influxdata/ui/blob/master/src/writeData/constants/contentTelegrafPlugins.ts#L414) we have a hard coded array of telegraf plugins, that was deciding the order of the plugins when we displayed it in the UI. 
I made it so that we use a sorted array, so no matter how we maintain the source array, we always have an alphabetically sorted UI.

fix: sorting bug of telegraf plugins

---

src/flows/pipes/RawFluxEditor/index.ts

Closes #2609
joins imports from both queries
injects body of the last query using ast (kind of)
supports multiple injections

fix: allow imports for previous_results

---

src/buckets/pagination/BucketList.tsx
src/buckets/pagination/BucketsTab.tsx
src/settings/components/LoadDataTabbedPage.tsx

Closes #2627
Moves the paginated bucket list into its own panel that scrolls, so that the pagination controls remain in the same place
https://user-images.githubusercontent.com/146112/135137615-be710b45-dcc6-4160-8a82-66b42f7c18e9.mov

feat(paginated buckets): made paginated list scrollable instead of the whole page

---

cypress/e2e/cloud/pinned.test.ts
src/flows/components/FlowCard.tsx
src/flows/context/flow.list.tsx
src/types/flows.ts

Closes #1381 
This PR integrates a recent API migration that sets a user's name when creating a notebook to the associated notebook. This PR also modifies the existing logic that displays the meta data of a notebooks since the styling was being thrown off whenever a user's meta data was set to `null`. This way existing notebooks that don't have the createdBy field won't look wonky

feat: add created by UI for flows

---

src/authorizations/components/redesigned/TokenRow.tsx

Closes #1934 
When a user is in the Tokens Page, and selects Delete for a token,
a confirmation appears, and if the users confirms, the token is deleted via the API and removed from the UI.
https://user-images.githubusercontent.com/66275100/134982942-3b0e66ea-d4c1-4de5-a4d5-f33174e39e5e.mov

feat: Tokens Redesign - delete token confirmation

---

src/flows/components/Sidebar.scss
src/flows/components/Sidebar.tsx

Cleans up the sidebar css to avoid the search box overlapping the scrollbar
Functions:
Expressions:

fix: sidebar css

---

src/settings/components/LoadDataTabbedPage.tsx

Starts https://github.com/influxdata/ui/issues/2736
A quick fix to put out the fire. We'll fix the logic later.

fix: make tabbed page scrollable again

---

src/settings/components/LoadDataTabbedPage.tsx

Closes #2736 
Depending on what page the user is on and the feature flag `fetchAllBuckets` (which allows for paginating the buckets and improves user experience) we need to decide whether the `scrollable` property is allowed to be `true` or `false`.
I wrapped it in a function so that when we paginate other areas like the `Tokens` we can just append that logic to the function.

fix: make tabbed page respect the feature flags for scrollable logic

---

src/flows/components/FlowCard.tsx
src/flows/components/header/index.tsx
src/flows/components/panel/FlowPanel.tsx
src/flows/constants.ts
src/flows/index.ts
src/flows/pipes/Columns/readOnly.tsx
src/flows/pipes/Columns/view.tsx
src/flows/pipes/Notification/readOnly.tsx
src/flows/pipes/Notification/view.tsx
src/flows/pipes/Visualization/view.tsx
src/flows/style.scss

Closes #2434 
This PR tweaks the existing "preview from here" functionality by plopping the preview button for specific pipes (visualization, columns, and notifications). It also cleans up some console errors, updates and centralizes the NotStarted state of specific pipes as per the design.

feat: preview button at the top of the pipe for certain pipe types

---

src/authorizations/components/TokenRow.tsx
src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/authorizations/components/redesigned/TokenRow.tsx
src/authorizations/utils/permissions.test.ts
src/authorizations/utils/permissions.ts

Closes #2107 
When user who is creating token using custom api option, selects list of resources and permissions, and clicks Generate, if  token description is not provided, the description is generated in the backend based on user selections. 
In the case of user giving a token multiple permissions, a token description with `Read Multiple Write Multiple` is generated.
https://user-images.githubusercontent.com/66275100/134956806-267961b9-0516-4525-b70f-1149adf4e722.mov

feat: generate token description

---

src/buckets/pagination/BucketList.tsx

I forgot to take care of this on the first go around - the number of pages should change when filtering. Filtering the list of buckets down to a single page should remove all but one page from the pagination controls.

fix(paginatedBuckets): have pagination respect the length of filtered items

---

src/buckets/pagination/BucketList.tsx
src/buckets/pagination/BucketsTab.tsx
src/tasks/pagination/TasksList.tsx

Closes https://github.com/influxdata/ui/issues/2725
This PR was inspired from https://github.com/influxdata/ui/pull/2610, basically does the same thing as implemented for paginated tasks, for buckets.
Video: 
https://user-images.githubusercontent.com/18511823/135359863-cc623bcc-c708-4b43-82a7-1d5a68f98abd.mov

feat(buckets): store pagination and filter state in url on change

---

cypress/e2e/shared/flows.test.ts
src/flows/pipes/Notification/Endpoints.tsx
src/flows/pipes/Notification/Expressions.tsx
src/flows/pipes/Notification/view.tsx

Closes #2671 
Adds a system var `_notebook_link` that can be used in the notification panel in notebooks like `${r._notebook_link}`. Also added this var to the Expressions sidebar. 
Also fixed a bug where the Expressions sidebar could be opened before the notification message monaco editor was mounted, causing the two to be disconnected. Now the expression button shows a loader until the editor is ready.
Includes e2e test.
Expression button waits for monaco editor:
_notebook_link added to expressions sidebar:
Task query contains url:
Example slack alert using variable:

feat(notebooks): alert _notebook_link var

---

src/authorizations/components/redesigned/ResourceAccordion.tsx

Closes #2682 
Reverting this change because lodash's `capitalize` function, capitalizes the first letter but lower cases everything else. This breaks the notification endpoints because they are being stored in our obj as `notificationEndpoints` and we are trying to access `notificaitonendpoints`. So this fix only capitalizes first letter for display of the resources on the CustomApiTokenOverlay

fix: notification endpoints toggle on token creation

---

src/buckets/pagination/BucketList.tsx

Closes #2761
If you're on a page of results and you filter those results and the number of pages is reduced below the page you're on, it should put you on the last of the results page.
https://user-images.githubusercontent.com/146112/135666089-ca3c0008-9ef5-4713-8f7d-438d2c5df474.mov

fix(paginated buckets): move user to last page of filtered results after filtering

---

src/buckets/pagination/BucketList.tsx
src/tasks/pagination/TasksList.tsx

Move a method call that eventually called forceUpdate() out of render
and into componentDidUpdate
This will fix warnings that 'render should be a pure method'

fix: make pagination render methods pure

---

src/writeData/components/PluginCreateConfigurationFooter.tsx

Closes #1406 
Search and replace "interval" in the agent settings when a Free tier user creates a new Telegraf configuration

feat: override interval for Free tier users in agent settings

---

src/writeData/components/telegrafPlugins/webhooks.md

Closes https://github.com/influxdata/influxdb/issues/20229
- use the correct url; redirect to the appropriate Telegraf README page
- use anchor tags to open links in a new tab

chore: fix broken links in Webhooks plugin page

---

cypress/e2e/shared/telegrafPlugins.test.ts
src/dataLoaders/components/collectorsWizard/verify/VerifyCollectorsStep.tsx
src/dataLoaders/components/verifyStep/TelegrafInstructions.tsx

Closes https://github.com/influxdata/ui/issues/2751
Remove the previous button from the last step of the Telegraf Refresh UI Overlay. (The one where it shows the instructions, the final step.)
Screenshot:

feat: remove prev button from the last step of telegraf overlay

---

src/buckets/components/BucketCardActions.tsx
src/writeData/components/fileUploads/AnnotatedCSV.md
src/writeData/components/fileUploads/CSV.md
src/writeData/components/fileUploads/UploadDataDetailsView.tsx
src/writeData/constants/contentFileUploads.ts

Closes #
Attempts to add a CSV Load Data card to the data sources page.

feat: add csv docs to load data

---

src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/authorizations/components/redesigned/ResourceAccordion.tsx

Closes #1927 
With search parameter entered in the overlay input box, user can now filter resources of Bucket names and Telegraf configs. 
https://user-images.githubusercontent.com/66275100/135907921-7e9e7fa9-fb3a-41ea-8671-5c8589448823.mov

feat: Tokens customApiToken overlay permissions filter

---

cypress/e2e/shared/dashboardsIndex.test.ts

`dshboard` -> `dashboard`
should fix this problem

fix: test typo

---

cypress/e2e/cloud/buckets.test.ts
src/buckets/actions/thunks.ts
src/buckets/components/createBucketForm/BucketOverlayForm.tsx
src/buckets/components/createBucketForm/CreateBucketForm.tsx
src/buckets/components/createBucketForm/MeasurementSchemaSection.test.tsx
src/buckets/components/createBucketForm/MeasurementSchemaSection.tsx
src/buckets/components/createBucketForm/MeasurementSchemaUtils.ts
src/buckets/components/createBucketForm/UpdateBucketOverlay.tsx
src/buckets/reducers/createBucket.ts

Closes #2505 
Can now add measurement schemas during bucket creation.  
the measurement schema section appears/disappears when you toggle the 'schematype' radiobutton.
this means that if you add data, then switch back to implicit, the section disappears (along with its data).
it does correct validation:  it only validates the data when the schema type is explicit.
and you don't have to add measurement schemas if you are creating an explicit bucket, measurement schemas can be added later.
added these two events:
bucket.schema.explicit.creation.uploadSchema: triggers for each schema being added
bucket.creation: when a bucket is created (this didn't already exist, so added it)
the validation, backend calls, etc are all the same as from when the bucket already exists.
the backend call needs …

feat: Explicit buckets- add schemas on create

---

src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/authorizations/components/redesigned/GenerateTokenDropdown.tsx

Closes #2807 
`Save` button inside `EditTokenOverlay` by default is inactive. Only when user interacts and updates the token description will the `save` button status changes to active.
Button right when `EditTokenOverlay` is opened ...
Button after user updates description...

feat: Save btn in EditTokenOverlay activates when description updates

---

src/dataLoaders/components/collectorsWizard/TelegrafUIRefreshWizard.tsx
src/style/chronograf.scss
src/writeData/components/AddPluginToConfiguration.tsx

Closes #2853 
Load the missing CSS so that the user does not have to visit Sources > Data to get that CSS.

fix: load the missing CSS for TelegrafUIRefreshWizard

---

src/dataLoaders/components/verifyStep/DataListening.tsx

Related to #2820 
During investigation of #2820 it was determined that no action is needed to address it since it is a non-issue. User must complete all steps before a measurable response comes back.
However, let's clarify this comment so that future eyes will see the reason quicker.

chore: clarify comment regarding query response from a new bucket

---

package.json
yarn.lock

Closes #2629 
This should work, as seen locally:
https://user-images.githubusercontent.com/10736577/137045414-f460ffde-18c9-4bc8-9483-c9a8e2b489d9.mp4

fix: update Giraffe to use latest icomoon assets

---

cypress/e2e/shared/annotations.range.test.ts
cypress/e2e/util/annotationsSetup.ts

Addresses: 
#2334 
#2466 
#2467 
#2692 
Potentially closes them out, but we'll see.
What we want is to trigger the annotation tooltip before making our assertions. Seems like this triggering of the annotation tooltip is the source of flakiness.
Instead of hovering over the whole graph, hover over an annotation line which will trigger the tooltip.

test: hover over an annotation line instead of the whole graph

---

package.json
src/buckets/components/context/lineProtocol.tsx

updates to the latest openApi sha for building the backend api that the ui calls.
tweaked the lineProtocol error codes that have changed.  
needed for explicit buckets 
#2231

chore: use latest openApi

---

cypress/e2e/util/annotationsSetup.ts
src/annotations/components/annotationForm/AnnotationMessageInput.tsx

From observing repeated flakiness, it is clear that Annotations tests have a common problem. Elements are detached from the DOM when a test command tries to execute. Let's guard against these.
- assert that certain elements are not detached
- execute certain commands only after the above
- use a new click target for annotations
- add a `testID` for the annotation message form to assert visibility

test: update annotations tests to prevent detaching

---

cypress/e2e/shared/annotations.range.test.ts
cypress/e2e/util/annotationsSetup.ts

- add assertion for overlay in the range annotation tests
- remove assertion in `addRangeAnnotation` helper function
- assert that range times are equal or not equal as appropriate per test
- call `invoke` on `<TextArea>` to insert text and reduce the amount of typing and re-renders

test: fix annotations tests with extra precautions

---

cypress/e2e/shared/annotations.band.test.ts
cypress/e2e/shared/annotations.range.test.ts
cypress/e2e/shared/annotations.singlestat.test.ts
cypress/e2e/shared/annotations.xy.test.ts
cypress/e2e/util/annotationsSetup.ts

The idea here is:
~~- `invoke('val', 'some annotations text')` to prevent re-render~~
~~- `type()` just one character to make the `<TextArea>` dirty and thus saveable~~
~~- avoid any flakiness from the re-render because we aren't typing 2 or more characters~~
~~- submit the annotation add/edit immediately~~
*** UPDATE:
The `<AnnotationMessageInput />` element does a focus on the text area. Let's use that forced focus to our advantage and type only in that focused element.

test: type only in the focused element

---

src/dataLoaders/components/collectorsWizard/select/TelegrafUIRefreshCollectorsStep.tsx
src/dataLoaders/components/collectorsWizard/select/TelegrafUIRefreshSelector.tsx

- Closes #3029 
- Bucket dropdown is now marked as required
- Updates wording for "Simply choose **a bucket and** one of..."
- The word "Telegraf" is now a link

fix: update wording and mark required in Telegraf configuration modal

---

src/billing/components/BillingContactDisplay.tsx
src/billing/components/PayAsYouGo/PlanTypePanel.tsx
src/billing/components/PaymentInfo/PaymentDisplay.tsx
src/billing/components/PaymentInfo/PaymentPanel.tsx
src/billing/context/billing.tsx

When the zuora outage flag is turned on in quartz, it starts sending `503` which UI isn't able to handle and crashes on billing page. See image below:
___________________________
So, adding a default empty `BillingInfo` and now will be accessing nullable fields.
If the quartz outage flag isn't turned on and there's a problem with the billing route, this is what this page will look like:
___________________________
When we set `influx.set('quartzZuoraDisabled', true)`, we should be seeing this:
______________________________
Checkout Page looks normal when the flag isn't turned on and looks like this when the flag is turned on:

chore: handle 503 from quartz billing

---

src/authorizations/actions/creators.ts
src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/types/resources.ts

Closes #2683 
The `allResources` in redux state for tokens has a type of String[] | Error. During investigation, it became apparent  having `Error` as an optional property for allResources was redundant since the `getAllResources` function inside thunks already contains code that takes care of >200 status.

chore: removed Error optional property from allResources

---

src/flows/components/ReadOnly.tsx
src/flows/components/header/index.tsx
src/flows/pipes/QueryBuilder/readOnly.tsx

Fixes some tiny notebooks bugs.
- we're going to change the structure of the accessID, so the UI can't be enforcing the length right now. Might re-add this at a later date
- I got the share button colors backwards in https://github.com/influxdata/ui/pull/3052 🤦 
- fixes a bug where the readonly query builder panel would crash a shared notebook because we weren't accessing the `.name` prop

fix(notebooks): accessID length, share btn color, query builder dropdown

---

src/authorizations/utils/permissions.test.ts

Closes #2877 
PR tests the two util functions inside Permissions.ts; `formatApiPermissions` (takes in accordion style permissions and converts it to api permission) and `formatPermissionsObj` (takes in api permission and converts it to accordion permissions)

test: testing both format util functions for permissions

---

src/buckets/actions/thunks.test.ts
src/buckets/actions/thunks.ts
src/buckets/api/index.ts
src/external/monaco.flux.server.ts
src/timeMachine/actions/queryBuilderThunks.ts

Closes #3091
methods that are used to fetch buckets in builders (query builder, notebooks) now check for the `fetchAllBuckets` flag and set the appropriate limit

fix: queryBuilder and notebooks correctly fetch all buckets now

---

src/alerting/components/builder/ThresholdStatement.tsx
src/checks/components/CheckTagRow.tsx

Closes #3024
Fix for the background color. screenshot:

fix: fix background color for the checks panel

---

src/flows/components/ReadOnly.tsx

Closes #3129 
This PR handles the new query errors returned from notebooksd for shared notebooks

chore(notebooks): handle when query errors are returned

---

cypress/e2e/shared/simpleTable.test.ts
package.json
src/dashboards/components/dashboard_index/DashboardsIndex.tsx
src/settings/components/LoadDataTabbedPage.tsx
src/settings/components/SettingsTabbedPage.tsx
src/tasks/containers/TasksPage.tsx
yarn.lock

Closes https://github.com/influxdata/ui/issues/3078
Larger scrollbars for Dashboard, Settings, Load Data and Task page

fix: scrollbar for dashboard, settings, load data and task page is Large

---

src/authorizations/actions/thunks.ts
src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/authorizations/utils/permissions.ts

Closes #2899 
Issue - When creating a Custom API Token and an error is thrown, the user selected permissions are removed. The user should still be able to see the selected permissions from before. Also, when clicking on different permissions while the Failed notification is displaying, the selected permissions disappear when the notification is dismissed.
Fix - added an if statement inside useEffect to check if permissions object has telegrafs and buckets values. if true, we can skip updating permission (state), which in turn will stop the component from re-rendering. 
https://user-images.githubusercontent.com/66275100/140400827-5c8c3101-ba18-4cb8-8c52-cd6b545a1b16.mov

feat: customApiTokenOverlay re-renders multiple times

---

src/writeData/components/PluginAddToExistingConfiguration/Configure.tsx

Closes #3167 
Only invalid selection was being checked. Add the check for a valid selection, so that user can continue.
https://user-images.githubusercontent.com/10736577/140585903-6eae6da3-13e7-4f60-b1c9-29d6ef405c4b.mp4

fix: allow continue Telegraf config editing to continue on valid default selection

---

cypress/e2e/cloud/buckets.test.ts
cypress/e2e/shared/tokens.test.ts
src/buckets/components/createBucketForm/BucketOverlayForm.tsx
src/buckets/components/createBucketForm/MeasurementSchema.scss
src/buckets/components/createBucketForm/MeasurementSchemaSection.test.tsx
src/buckets/components/createBucketForm/MeasurementSchemaSection.tsx
src/buckets/components/createBucketForm/MeasurementSchemaUtils.ts
src/buckets/components/createBucketForm/MiniFileDnd.test.tsx
src/buckets/components/createBucketForm/MiniFileDnd.tsx

Closes #3094 #3095 
before this pr; when uploading new measurement schemas, updating existing measurement schemas, and downloading measurement schemas, all the files were in the json format.
this ticket allows a user to use the csv file format as well.  
so they can do new uploads, updates,  and downloads in csv.
for updates/uploads, just select either a csv or json file and it just works transparently with no change for the user.
for downloads, there is a new radio button to specify the format.  it is by default json, but can be switched to csv instead.
https://user-images.githubusercontent.com/3900960/140376910-87cc9664-e06e-48be-95a6-eda3d2b746c1.mov

feat: explicit buckets: add csv for uploading and downloading

---

src/shared/components/cells/CellCloneOverlay.tsx

Closes #2993 
uses the new type-ahead clockface component to enable search on the dropdown; plus alphabetizing the entries (in ascending order)

feat: use type ahead dropdown

---

src/writeData/components/telegrafInputPluginsConfigurationText/knx_listener.conf
src/writeData/components/telegrafPlugins/knx_listener.md
src/writeData/constants/contentTelegrafPlugins.ts
src/writeData/utils/parsePluginsConfigurationText.ts

Closes #3163 
Changes `KNXListener` to `knx_listener` everywhere. Per the Telegraf Team, the correct name is `knx_listener`

chore: update KNXListener to knx_listener

---

src/writeData/components/telegrafInputPluginsConfigurationText/couchbase.conf
src/writeData/components/telegrafInputPluginsConfigurationText/elasticsearch_query.conf
src/writeData/components/telegrafInputPluginsConfigurationText/ethtool.conf
src/writeData/components/telegrafInputPluginsConfigurationText/intel_rdt.conf
src/writeData/components/telegrafInputPluginsConfigurationText/win_eventlog.conf
src/writeData/utils/parsePluginsConfigurationText.ts

Closes #3159 
Updates the script that fetches the latest configuration for all Telegraf plugins:
- use the latest release number if not given as an argument
- the latest release number is available from an api call to github
- resolve the above before proceeding to fetch the plugins
Runs the updated script to update the Telegraf plugins:
- exception: KNX Listener which appears to have its name changed yet again; will handle as a separate issue

feat: update script to fetch latest Telegraf plugins and run script

---

src/external/monaco.flux.theme.ts
src/shared/components/FluxMonacoEditor.scss

Closes #2995 
Just better colors for the Monaco editor so it fits in with the new Clockface 3 release.

fix: fix monaco editor colors after Clockface 3 release

---

cypress/e2e/shared/flows.test.ts

Removes extra unnecessary step in the test of opening the notebook and immediately leaving lol

test: fix bug in flows test

---

cypress/e2e/shared/flows.test.ts

This changes the test to wait on the `PATCH` request after editing the notebook before navigating away from the page. Passed 20x locally with firefox

test: another take at the flaky flows test

---

src/templates/components/CommunityTemplateHumanReadableResource.tsx
src/templates/components/CommunityTemplatesResourceSummary.tsx
src/templates/containers/CommunityTemplates.scss

Closes #3023
Minor UI fixes.
Before:
After:

fix: templates page font sizes

---

package.json
src/pageLayout/constants/navigationHierarchy.ts
yarn.lock

Closes https://github.com/influxdata/clockface/issues/683
Replaces the Load data icon. Screenshot:

fix: new icon for the load data menu item in nav bar.

---

src/billing/components/PayAsYouGo/CancellationOverlay.tsx
src/billing/components/PayAsYouGo/CancellationPanel.tsx
src/me/actions/thunks/index.ts
src/organizations/components/DeleteOrgOverlay.tsx
src/organizations/components/OrgProfileDeletePanel.tsx

There was a typo in RudderStack Reporting flag. The actual flag name is: `rudderstackReporting` but it was typoed as `rudderStackReporting`..

fix: fix rudderstack feature flag name

---

src/authorizations/utils/permissions.ts

Closes #3174 
Added an if statement inside `generateDescription` function in utils that checks if received api permission array is an orgs permission. If true, the function will take org's unique data structure into account and generate its name accordingly.
Top token has correct description (fix) . Botton token is wrong (before fix)

fix: generate correct name for orgs tokens

---

src/buckets/components/BucketCardMeta.test.tsx
src/buckets/components/BucketCardMeta.tsx

Closes #1721 
**Before fix:** 
UI didn't show IDs for automated buckets like `_tasks` and `_monitoring`. 
**After Fix:** 
`BucketMetaCard` displays bucket ID despite bucket type

feat: show bucket's ID for all buckets

---

src/billing/components/PayAsYouGo/CancelServiceReasonsForm.tsx
src/billing/components/PayAsYouGo/CancellationOverlay.tsx
src/organizations/components/DeleteOrgOverlay.tsx

Send information to Snowflake using Rudderstack Reporting on `Cancel Service` or `Delete Organization` Dialog Boxes Dismiss.

feat: add rudderstack reporting on dialog dismiss

---

src/tasks/actions/thunks.test.ts
src/tasks/actions/thunks.ts

Closes #3210
When on the Task runs page, toggling the task active status didn't update the page. FIXED.
The problem was an optimization made [here.](https://github.com/influxdata/ui/pull/3053/files#diff-c8f414b07947cac7332264ab0150c713ba9554309216393b7f91327b68e18774L148) That optimization removed the re-selection of the current task based on the task run's task id. Instead, the current task is updated when editing task status.
I think this is preferable, because it updates the store, which is the app's source of truth. So anyone selecting `state.resources.tasks.currentTask` can expect the store to be up to date, rather than relying on code calling the correct method.

fix: update the current task after updating task status

---

src/flows/context/flow.current.tsx

This PR adds a new emit event to the socket to send over the browser session for validation

chore: send the session at the socket connection

---

src/dashboards/components/dashboard_index/DashboardsIndex.tsx
src/shared/components/AddResourceDropdown.tsx

Closes #1451 
Added 'Add a Template' option inside Create Dashboard dropdown that takes user to Setting's Template page. 
https://user-images.githubusercontent.com/66275100/141349753-e028de6f-1a50-465f-b5e3-5f9bc8c19373.mov

feat: add link to template pages from dashboards dropdown

---

package.json
src/flows/components/FromTemplatePage.tsx
src/flows/components/header/Submit.scss
src/flows/components/header/index.tsx
src/flows/style.scss
src/pageLayout/constants/navigationHierarchy.ts
src/pageLayout/utils/index.test.ts
src/pageLayout/utils/index.ts
yarn.lock

fix(notebooks): presentation and nav tree bugs, share warning

---

cypress/e2e/cloud/buckets.test.ts

added checks to see that the dialogs actually closed before moving on to the next part of the test.
at this point, not adding additional checks to see if the file downloaded.  they already have 'should.exist' on them.

chore:  working on explicit bucket flaky testts

---

src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx

Closes #3226 
Background: 
Inside CustomAPITokenOverlay component, inside mstp, we fetch all telegrafs and buckets from redux store and populate fetched data inside bucketPermissions and telegrafPermissions object. 
Then after the component mounts, the useEffect hook constructs a new permissions object (perms) using our state props (bucketPermissions and telegrafPermissions) and updates the permission state. 
Before Fix: 
everytime props.bucketPermissions and props.telegrafPermissions change, the useEffect function check if the state has telegraf and bucket property. if false -> it updates the state (permissions). which causes components to re-render. 
But just because our permissions object has telegraf and buckets properties, it doesn't mean they have sublevel permission values. This is …

fix: individual buckets and telegrafs names should render when Buckets and Telegrafs accordion expands 

---

src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/telegrafs/actions/thunks.ts

Closes #2942 
For this fix, I added a state to store the new permissions in the component and a thunk that will get the telegraf name for a specified ID. I added the async function to be called for every telegraf permission that is missing the `name` field.

fix: fetch telegraf name using telegraf get api

---

package.json
src/external/monaco.flux.theme.ts
src/shared/components/FluxMonacoEditor.scss
src/tasks/components/TaskForm.scss
yarn.lock

Closes https://github.com/influxdata/ui/issues/3235
* updates the `monaco-editor` version so I could bring this patch in: https://github.com/microsoft/monaco-editor/issues/2074
* changes the minimap background using the color settings instead of overriding the CSS.

fix: monaco editor minimap background fix

---

src/authorizations/actions/thunks.ts
src/authorizations/components/redesigned/AllAccessTokenOverlay.tsx
src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/authorizations/components/redesigned/GenerateTokenDropdown.tsx
src/authorizations/components/redesigned/TokenRow.tsx

Closes #3132 
Added metrics for user events for the following: 
- when editing a token is a success
- when editing a token is a failure
-  when active/inactive happens (word differently)
-  when description on resource card is edited
-  when deleting a token is a success
-  when deleting a token is a failure
-  when cloning a token is a success
-  when cloning a token is a failure
-  when adding an all-access token is a success
-  when adding a custom api token is a success
-  when adding a token is a failure
-  fire each event when overlays are opened

feat: added metrics for user events 

---

src/flows/pipes/QueryBuilder/readOnly.tsx

Closes #3244
Previously the shared notebook would crash if no bucket was selected in query builder. This adds a safe guard so we show "No bucket selected"  instead

fix: handle no bucket selected

---

src/visualization/types/Map/index.tsx

Closes #3247
Makes it so that maps don't show up as a visualization option in OSS.

fix: remove maps as a vis option for OSS

---

src/authorizations/components/redesigned/TokenRow.tsx

Closes #3270 
Before fix: 
when user clicks on token's delete button, the confirmation reads "Yes, delete this dashboard" 
After fix:
Confirmation text for deleting token reads "Yes, delete this token"

fix: updated token delete confirmation wording

---

src/flows/context/flow.query.tsx

Closes #3232
re-enables the interface reloading on panel add / removal / cloning.
i hate this solution, because the issue feels like it's covering up a problem that is rooted more in a misrepresented responsibility, where the flow.query context needs to recalculate if it's parent context (flow.current) had manipulated a nested object, but i couldn't quite get myself to saying that the generateMap function should be owned by the flow.current context. it might very well make more sense there, but while i hem and haw over that, we can at least unbreak the interface for our users.

fix: reenables the run on add ability

---

src/checkout/CheckoutForm.tsx

add `isPaygCreditActive` flag from checkout context which adds a couple of additional checks
```
isFlagEnabled('paygCheckoutCredit') &&
getExperimentVariantId(PAYG_CREDIT_EXPERIMENT_ID) === '1' &&
checkoutCode === CHECKOUT_PARAM_CODE
```

fix: add additional check for showing payg experiment

---

cypress/e2e/cloud/buckets.test.ts
cypress/e2e/oss/buckets.test.ts
src/authorizations/components/redesigned/IndividualAccordionBody.tsx
src/buckets/components/BucketList.tsx
src/buckets/pagination/BucketList.tsx
src/timeMachine/components/queryBuilder/BucketsSelector.tsx

Closes #3080 
Before fix: 
buckets tab -> we have system buckets listed first and then the rest follow in alphabetical order.
In data explorer -> we have them all listed alphabetically. System & user buckets
lastly, in notebooks -> we have 3 categories. user, system, and sample. and buckets are listed in each category in alphabetical order
After fix: 
All three places in the UI where buckets are listed are now ordered alphabetically by bucket type (user buckets followed by system bucket) 
**Bucket Tab:** 
https://user-images.githubusercontent.com/66275100/142675310-c68da837-1354-4f5c-859b-3c44bba73680.mov
**Data Explorer:** 
https://user-images.githubusercontent.com/66275100/142675360-94ab9774-73bf-48fe-a2d2-6cae04e95987.mov
**Notebooks:** …

fix: sorting buckets across UI

---

src/authorizations/components/redesigned/EditTokenOverlay.tsx

When we create a custom api token for specific telegraf config, then viewing a token, we do a `GET` request for the telegraf to get the name to be displayed on the `EditTokenOverlay`. This failed when the specific telegraf is deleted. So, in this pr I have added a try and catch so that when it does fail we want to display `Resource deleted` instead of failing horrible. Also, I have added similar functionality for buckets.

fix: tokens empty string for when resource deleted

---

src/dataLoaders/components/verifyStep/ConnectionInformation.tsx

Closes influxdata/docs-v2#3439
This fixes a Telegraf troubleshooting link that is currently broken. Telegraf isn't versioned with InfluxDB, so the correct path for Telegraf links should just include `latest`. This will redirect to the latest Telegraf version.

fix: Fix broken Telegraf troubleshooting link

---

src/authorizations/pagination/TokenList.tsx

Closes #3324
overflow was set to `scroll` instead of `auto`.
See https://github.com/influxdata/ui/pull/2809/ which is a previous fix for the same issue on tokens and buckets

fix: remove persistent scrollbar on paginated token list

---

cypress/e2e/shared/tasks.test.ts

See #3333 
>The cron task is failing on idpe too and therefore blocking CI/CD to cloud2

test: skip flaky test that is holding up CI

---

src/flows/pipes/Notification/endpoints/PagerDuty/index.ts

The registered trademark name for PagerDuty does not include a space. This change updates the name for the endpoint selector in notebook alert cells to use the trademarked name.

fix: remove space from PagerDuty in notebook alert cells

---

src/authorizations/components/redesigned/EditResourceAccordion.tsx
src/authorizations/components/redesigned/EditTokenOverlay.tsx

flakey e2e tests are causing PR #3319 to fail monitor ci test. 
moved 3319's commits to a new branch to see if tests pass here. 
closes #3331. 
PR adds filtering abilities to `EditResourceTokenOverlay` which fixes the bug that's causing tokens UI to crash.

feat: add filter to EditTokenOverlay

---

src/usage/BillingStatsPanel.tsx

Closes #3062
with @appletreeisyellow
While the billing data is loading, we want the header to say "Billing Stats" instead of "Billing stats for to today" which looks like a typo. 
Loading:
Done loading:

fix: typo in billing stats while loading

---

src/buckets/components/BucketsTab.tsx
src/buckets/pagination/BucketsTab.tsx

Closes #3030
with @appletreeisyellow
Adds another grid width to the buckets tab to prevent the bucket helper text from getting too small.
https://user-images.githubusercontent.com/6411855/144333858-542d5bac-f420-4dd0-88b0-04ecb4f8e6bc.mov

fix: add more column width specs

---

src/me/containers/MePage.scss

Closes #3219
with @appletreeisyellow
Previously long dashboard names would wrap in the Recent Dashboards widget and made it look weird. This changes the css to `nowrap` which will add a horizontal scrollbar if the dashboard name overflows.

fix: recent dashboards wrapping

---

package.json
src/annotations/components/controlBar/AnnotationPills.scss
src/clockface/components/context_menu/ContextMenu.scss
src/flows/FlowVariables.scss
src/flows/components/panel/InsertCellButton.scss
src/flows/style.scss
src/pageLayout/components/RenamablePageTitle.scss
src/shared/components/Checkbox.scss
src/shared/components/ThresholdMarkers.scss
src/shared/components/cells/Cell.scss
src/shared/components/dapperScrollbars/DapperScrollbars.scss
src/shared/components/inlineLabels/InlineLabels.scss
src/shared/components/selectorList/SelectorList.scss
src/shared/components/tables/TableGraphs.scss
src/tasks/components/TasksPage.scss
src/timeMachine/components/Queries.scss
src/timeMachine/components/RawFluxDataTable.scss
src/timeMachine/components/builderCard/BuilderCard.scss
src/variables/components/VariableDropdown.scss
yarn.lock

Closes #3362
run `sass-migrator division **/*.scss` to automatically update scss files to fix deprecation warning.
See: https://github.com/influxdata/clockface/pull/707

chore: fix sass deprecation warnings

---

src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/authorizations/components/redesigned/EditTokenOverlay.tsx
src/authorizations/components/redesigned/IndividualAccordionBody.tsx
src/authorizations/utils/permissions.ts

Closes #3331 
Added a condition for `resource.id` which will exist if the token is a specific bucket/telegraf token before we make a request to fetch that specific bucket/telegraf.

fix: EditTokenOverlay doesn't fail when viewing buckets/telegrafs tokens

---

src/dataLoaders/components/DataLoadersOverlay.scss
src/shared/components/DragAndDrop.scss

Closes #2744
Now the filename and message are no longer covered.
Filename:
Message:

fix: show the filename and message for the uploaded file

---

src/billing/components/PayAsYouGo/CancellationOverlay.tsx
src/billing/components/PayAsYouGo/CancellationPanel.tsx
src/organizations/components/DeleteOrgOverlay.tsx
src/organizations/components/OrgProfileDeletePanel.tsx

Part of: #3322
Issue: Snowflake has been receiving data for a long while now. Rudderstack flag (rudderstackReporting) has been turned off and still the data has been reaching snowflake. We need to investigate, what's sending(leaking) data to rudderstack in order to get some clarity on the functionality which wasn't intended to be turned on yet.
One of the examples of the data in Snowflake which isn't being sent by `track` is: `loadTagSelectorValues function`. This is being sent only by `event`. I need to figure out if `/api/v2/app-metrics` is sending data to snowflake. I have reached out to Bucky as well as Ana and seems like they aren't sending data to snowflake. Ana will further investigate.
**Interim Solution:** In the meantime, I would like to segregate `event` and `track` to get …

chore: segregate track and event for trackCancellations feat

---

cypress/e2e/shared/checks.test.ts

Noticed locally that after PR #3350 the clone check test was failing.  
This should fix it. 
Replaces scoped variable in test group with cypress alias.

chore: update clone check test

---

src/flows/components/PipeList.tsx

Closes #3340
The scroll bar in notebooks was covered in presentation mode. Now the scroll bar is visible.
Before:
After:

fix: notebooks scroll bar in presentation mode

---

src/Signin.tsx
src/me/actions/thunks/index.ts
src/onboarding/containers/LoginPage.tsx

Closes #3383
Replace all usages of `clients.users.me` with the `getMe` request that's generated in generatedRoutes.

chore: remove clients.users.me usage

---

cypress/e2e/cloud/buckets.test.ts

Skipping this test because it has flaked 139 times and is blocking our CI. @jrenee42 is working on a fix in https://github.com/influxdata/ui/pull/3392

test: skip flaky buckets test for now

---

src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx
src/dashboards/components/dashboard_index/DashboardsIndexContentsPaginated.tsx
src/dashboards/components/dashboard_index/DashboardsIndexPaginated.tsx
src/shared/containers/SetOrg.tsx
src/shared/containers/index.tsx
src/tasks/pagination/TasksList.tsx

Closes #3386 
Added pagination to Dashboards. 
before pagination: 
https://user-images.githubusercontent.com/66275100/145273865-1da2c65d-ddfd-407e-aecb-1ea16d6aa3be.mov
After pagination: 
https://user-images.githubusercontent.com/66275100/145273990-99a3d393-d37b-4924-b378-479e259748c3.mov

feat: add pagination to Dashboard page

---

src/authorizations/pagination/TokensTab.tsx

Added tokens banner to tokens paginations page. 
Before fix, tokens banner only rendered when `paginatedTokens` feature flag is off. 
Picture attached below is UI with banner on paginated tokens page.

feat: adding Tokens banner to tokens pagination

---

src/flows/pipes/QueryBuilder/CardList.tsx
src/shared/components/TagSelectorCount.scss
src/shared/components/TagSelectorCount.tsx
src/style/chronograf.scss
src/timeMachine/components/TagSelector.tsx

Closes #2866 
**BEFORE**
**AFTER**

feat: show selected filters when searching in notebooks querybuilder

---

cypress/e2e/cloud/buckets.test.ts
cypress/e2e/shared/explorer.test.ts
cypress/fixtures/invalidSchema.json
cypress/fixtures/schema.csv
cypress/fixtures/updateValidSchema1.json
cypress/fixtures/validSchema1.json
package.json
yarn.lock

using cypress file fixtures; used 'within' more.

chore: make explicit bucket uploading tests less flaky

---

src/authorizations/components/redesigned/EditResourceAccordion.tsx
src/authorizations/components/redesigned/IndividualAccordionBody.tsx

Closes #3355 
Removed Bucket and Telegraf titles inside `EditTokenOverlay`. 
See #3355 for more info. 
Before fix: 
After fix:

feat: remove bucket and telegraf titles from `EditTokenOvelray`

---

docker/Dockerfile.chronograf.prod
package.json
src/me/containers/MePage.tsx
webpack.dev.ts
webpack.prod.ts
yarn.lock

This PR updates a few of our dev dependencies that had some severe security issues related to them. This work might also help us make a push to a higher version of webpack later on down the line

chore: update webpack-dev-server and related dependencies

---

yarn.lock

The previous commit, which updated some dependencies missed the lockfile. No big deal, adding it in now.

chore: add updated yarn.lock file which was accidentally missed

---

webpack.common.ts
webpack.dev.ts
webpack.prod.ts

TypeScript errors will no longer fail compilation
Tested dev builds and prod builds. Dev builds won't fail compilation under TS errors, prod builds will.

fix: remove regression in webpack dev configuration related to ts errors

---

package.json

Pretty straightforward clean-up. Removing a dependency that appears to have been accidentally added in the process of an upgrade

chore: remove duplicate dependency from package.json

---

src/writeData/components/WriteDataItem.scss
src/writeData/components/WriteDataSections.tsx

Addresses the performance issues in Safari with the Load Data > Sources page:
- reverts a previous attempt which only made plugins smaller and did nothing for visual peformance
- disables the CSS filtering which is the real culprit of the slow rendering
https://user-images.githubusercontent.com/10736577/146468321-7656140e-9144-4729-b8ad-b1b1083ba478.mp4

fix: disable clockface CSS filtering to improve visual performance

---

cypress/e2e/shared/dashboardsView.test.ts
src/shared/copy/notifications.ts
src/variables/actions/thunks.ts
src/variables/components/TypeAheadVariableDropdown.tsx
src/variables/mocks/index.ts
src/variables/utils/hydrateVars.test.ts
src/variables/utils/hydrateVars.ts

[Closes EAR#2795](https://github.com/influxdata/EAR/issues/2795)
- A query variable that 404ed when executing against a bucket would fail silently and keep the page in a loading state.
- `hydrateVars.ts` fires an error event with the variable that failed and the error message it failed with
- `variables/thunks.ts` shows an error notification with the variable name and the error
- `TypeAheadVariableDropdown.tsx` will show an error if the variable it's fetching is an an error state
**A single variable failing**
**Dependent Variable failing**

feat: when query variables fail to load, show a message to the user

---

package.json
src/visualization/types/Graph/view.tsx
src/visualization/utils/colorMappingUtils.test.ts
src/visualization/utils/colorMappingUtils.ts

Closes https://github.com/influxdata/ui/issues/3098
Bigger Picture: 
The `translate` is basically looking at the `viewProperties.colorMapping` object from the `idpe` and then looking up the `color` using the index in the `properties.colors` array. We then embed the `color` property into the `mappings.[series_index]` object in giraffe.
Visualization of how the colorMapping object is translated into color for the giraffe. This translation happens in the UI. (`getColorMappingObjects` function)

feat: Color Map pass the `colorMapping` object to giraffe

---

src/visualization/types/Map/view.tsx

Closes #3245
This PR (along with a corresponding API change), fixes the issue where maps in shared notebooks can't be displayed. The API PR goes into more detail as to what the issue is, and how it's resolved

fix: connect the API changes to the UI to get maps to display in shared notebooks

---

src/flows/context/flow.query.tsx
src/shared/contexts/query.tsx

removing the strange variable resource <-> AST partial mechanism of dealing with variables in queries in notebooks, which aren't technically supported but needed for setting the timerange and the like. the idea here is that we should be treating all variables within a query as a hashmap of strings, and whatever mechanisms are required for handling variable recursion and defining it as a string should be handled via a separate mechanism. hoping that this will be a precursor for defining a timeranges in a panel, decoupling from the `SelectableTimeRange` format and opening up the possibility for new ways of defining time ranges (eg { from: - 1w, to: -3d})

feat: simplify query vars

---

mocks/dummyData.ts
src/authorizations/apis/__mocks__/data.ts
src/authorizations/apis/__mocks__/index.ts
src/authorizations/components/ViewTokenOverlay.test.tsx
src/authorizations/components/redesigned/TokensTab.test.tsx
src/clockface/components/inputs/multipleInput/MultipleInput.test.tsx
src/clockface/components/inputs/multipleInput/MultipleRows.test.tsx
src/clockface/components/inputs/multipleInput/Row.test.tsx
src/dataLoaders/actions/dataLoaders.ts
src/dataLoaders/components/collectorsWizard/configure/ConfigFieldHandler.test.tsx
src/dataLoaders/components/collectorsWizard/configure/PluginConfigForm.test.tsx
src/dataLoaders/components/collectorsWizard/configure/PluginConfigSwitcher.test.tsx
src/dataLoaders/components/configureStep/streaming/ArrayFormElement.test.tsx
src/dataLoaders/components/configureStep/streaming/ConfigFieldSwitcher.test.tsx
src/dataLoaders/constants/pluginConfigs.ts
src/dataLoaders/reducers/dataLoaders.test.ts
src/dataLoaders/utils/pluginConfigs.test.ts
src/members/actions/thunks.ts
src/members/dummyData.ts
src/shared/utils/resourceToTemplate.test.ts
src/shared/utils/resourceToTemplate.ts
src/tasks/containers/TasksPage.test.tsx
src/templates/api/index.ts
src/templates/utils/index.test.ts
src/templates/utils/index.ts
src/types/auth.ts
src/types/dataLoaders.ts
src/types/templates.ts

Closes #3471 
This is part of a larger process to try and remove / update one of our dependencies. The point of this PR is to reduce the usage of the `@influxdata/influx` dependency by consolidating sources of truth to ones generated based on the OpenAPI yamls. Coupled with other work (both past and future), this should limit the usages of the `@influxdata/influx` dependency as best as possible so that we can look into removing it completely or updating it.

chore: swap influxdata/influx types for generated types or types defined in the UI

---

src/flows/components/ReadOnlyPipeList.tsx
src/shared/components/TimeZoneDropdown.tsx

Closes #3408
This matches the first new design. The second new design is considered part of issue #3325, so the code is not included in this PR. 
Before:
After:

style: reduce margin between each pipe card

---

src/shared/components/dateRangePicker/DatePicker.tsx
src/visualization/components/internal/TimeTickInput.tsx

Closes #3395 
The Date Picker for the Time Ticks customization was crashing because it did not have a handler that was added after the Time Ticks were implemented. We are adding the handler here. Also, let's correct the interface for the Date Picker by making the handler a required prop. Previously the prop was optional, but it should not have been.
Here is the Time Tick customization working correctly when the user types instead of clicks:
https://user-images.githubusercontent.com/10736577/148476127-f80e2500-2882-47e2-88d4-a724a577bd3d.mp4

fix: make invalid handler required and define in all consumers

---

src/shared/components/views/MarkdownRenderer.tsx
src/writeData/clients/Arduino/description.md
src/writeData/clients/CSharp/description.md
src/writeData/clients/Go/description.md
src/writeData/clients/Java/description.md
src/writeData/clients/Javascript/description.md
src/writeData/clients/Kotlin/description.md
src/writeData/clients/PHP/description.md
src/writeData/clients/Python/description.md
src/writeData/clients/R/description.md
src/writeData/clients/Ruby/description.md
src/writeData/clients/Scala/description.md
src/writeData/components/fileUploads/AnnotatedCSV.md

Closes #3239 
The UI wasn't showing the clickable link but HTML tag. We want the link to be clickable and opens in a new tab. This PR fixed the UI. 
Note that this fix doesn't support **"noreferrer noopener"** keyword as `< ReactMarkdown>` doesn't support `rel` attribute currently. 
Before:
After:

fix: clickable link on exporting to client library

---

src/flows/pipes/RawFluxEditor/dynamicFunction.tsx
src/flows/pipes/RawFluxEditor/dynamicFunctions.tsx
src/flows/pipes/RawFluxEditor/view.tsx

see #3105 & #3106 
As part of the Flux Dynamic Help Panels epic, this pr removes the example section from notebook's flux function flyover panel and lists flux functions without categories. This change is behind a feature flag influx.toggle('fluxDynamicDocs')
Notebooks flux functions with feature flag off: 
Notebooks flux functions with feature flag on:

feat: remove example and category from notebook's flux functions 

---

src/writeData/components/FileUploadSection.tsx
src/writeData/components/WriteDataItem.tsx
src/writeData/components/fileUploads/UploadDataDetailsView.tsx
src/writeData/constants/contentFileUploads.ts

Closes https://github.com/influxdata/ui/issues/2867
Following was addressed in this PR:
- remove verbiage under File Upload section that says at the click of a button so that CSV panel is not misleading
- Change CSV Data title to include some kind of CLI indicator (needs design)
- Inside CSV Data tile, remove bucket selector
- Inside CSV Data tile, add CLI description (needs design)
- Add metric for when the CSV Data tile is clicked (if not already available) to distinguish from CSV Flux uploader
https://user-images.githubusercontent.com/18511823/149013084-0cc92917-a824-49a9-970c-b08677683b21.mov

fix: file upload section fix for CSV Data 

---

src/flows/pipes/Notification/readOnly.tsx
src/flows/pipes/Notification/styles.scss
src/flows/pipes/Notification/view.tsx

Closes #3512 
There was a bug in Notebook Single Stat, when users configure, the view auto focused on a cell under the graph cell. We want the view to stay in place when users configure.
Before:
After:
---
The bug only appears when there is an Alert cell somewhere under the Single Stat graph cell. This is caused by using `<Dropdown.Menu>` in the Alert cell because the view is auto focused to show the selected dropdown item. 
Replace `<Dropdown.Menu>` with `<List>` fixed this issue because List doesn't have the side-effect of auto focusing.

fix: Notebook Single Stat view stays in place when users configure

---

src/utils/datetime/constants.ts
src/utils/datetime/formatters.test.ts
src/utils/datetime/formatters.ts
src/utils/datetime/validator.test.ts
src/utils/datetime/validator.ts
src/visualization/components/internal/AxisTicksGenerator.tsx
src/visualization/components/internal/TimeTickInput.tsx

Closes #3396 
- Fixes the "Start Time Ticks At" input to actually take a string in RFC3339 format. Previously, it was only taking a Unix timestamp.
- The time is converted to either "Local" or "UTC" based on the current selection for the Time Zone of the app. Must be done because the back-end still stores the "Start Time Ticks At" as a number (Unix timestamp) but we want to display a human readable format (RFC3339).
https://user-images.githubusercontent.com/10736577/149055860-d5bec2f2-98a1-4b23-91e0-0d87d2de8cc3.mp4

fix: allow RFC3339 as indicated in the placeholder for tick start

---

src/authorizations/components/PostDeploymentTokensBanner.tsx
src/authorizations/components/redesigned/CustomApiTokenOverlay.tsx
src/authorizations/components/redesigned/DisplayTokenOverlay.tsx
src/authorizations/components/redesigned/TokensTab.tsx
src/authorizations/pagination/TokensTab.tsx

Closes #3294 
Closes #3553 
Added a new component for `PostDeploymentTokensBanner`. I have kept the old banner there for now, when the feature flag is turned off. I will remove all the old code and banner in the next clean up pr.
This pr also updates the wording on the generate api token overlay from "Generate a Personal API Token" to "Generate a Custom API Token".

feat: add alert banner on new tokens UI

---

package.json
src/flows/components/Sidebar.scss
src/flows/pipes/Notification/Threshold.tsx
src/flows/pipes/Notification/view.tsx
src/flows/pipes/Visualization/Controls.tsx
src/flows/pipes/Visualization/ErrorThresholds.tsx
src/flows/pipes/Visualization/QRCode.tsx
src/flows/pipes/Visualization/style.scss
src/flows/pipes/Visualization/threshold.ts
src/flows/pipes/Visualization/view.tsx
src/flows/shared/Resizer.scss
src/shared/constants/graphColorPalettes.ts
yarn.lock

This PR is an initial attempt at allowing users to have UI-based alerting based on specific thresholds set in the UI. The story here is that we want a way to engage a user beyond the current alerting system so that, in the event a user is watching an updating notebook live in presentation mode, they will be able to somehow access that panel directly and take some sort of actionable steps to identifying and remediating that issue beyond the regular alerting system. We do this by allowing the user to set specific thresholds that will generate a QR code that can be scanned and deep-linked to in a notebook whenever the threshold appears.
As part of this, we will need to also integrate auto-refresh of notebooks so that notebooks can be run at a regular interval. In addition, in order to get …

feat: add error thresholds setting for visualization panels on notebooks

---

package.json
src/visualization/utils/formatStatValue.ts
yarn.lock

Closes #3519 
- updates Giraffe to update `formatStatValue`
- copies `formatStatValue` from Giraffe for posterity
_note_: `formatStatValue` should not be implemented by UI and will be removed in a separate pull request.

fix: update Giraffe to update formatStatValue

---

src/flows/context/flow.query.tsx

Closes #3526 
This PR addresses an issue where toggling the time range of a notebook would run the query for that notebook based on the previously selected timerange. This PR also cleans up some implementation details where we were setting the timerange of the notebook in two separate places, which was causing some weirdness with state syncing.

fix: fixes the issue that toggling the timerange didnt update the queries timerange

---

src/timeMachine/actions/queryBuilderThunks.ts
src/views/helpers/index.ts

Closes https://github.com/influxdata/ui/issues/3043
Allows to unselect the default values that way users can opt in to have no custom selected aggregate functions. 
Video: 
https://user-images.githubusercontent.com/18511823/149415871-06f0b91c-4106-4c3d-b3a2-7d8d56a0c64b.mov

fix: allow no functions to be selected in query builder custom aggregation

---

cypress/e2e/cloud/userAccounts.test.ts
src/accounts/SwitchAccountOverlay.tsx
src/accounts/context/userAccount.tsx
src/pageLayout/components/UserWidget.tsx
src/shared/copy/notifications.ts

Closes #3241 
* adds and enables the 'set as default' button in the account switch dialog
* uses notifications for success and failure
* adds e2e test
screencap: 
https://user-images.githubusercontent.com/3900960/149217185-466fea24-a2ee-485b-b5e7-09b4880e4134.mov

chore: phase 2: multiaccount/default setting

---

cypress/e2e/shared/dashboardsRefresh.test.ts
src/dashboards/components/DashboardContainer.tsx
src/dashboards/components/DashboardHeader.tsx
src/flows/components/header/index.tsx
src/shared/actions/autoRefresh.ts
src/shared/reducers/autoRefresh.ts

This is a pretty straightforward PR that's meant to be a step into integrating the autorefresh functionality into notebooks. We're going to want to expand the scope of the autorefresh functionality beyond dashboards, so this is just a step to take to normalize some of the naming and reduce confusion across the board when we get to integrating it into notebooks

chore: normalize the naming for autorefresh to make it more generic and intuitive

---

cypress/e2e/oss/onboarding.test.ts

Closes #3515
It appears that the test was moving too fast for the server by making use of a request that hadn't returned.
I'm not 100% sure how effective this will be. It was very difficult to get my environment set up to run the oss test. Onboarding failed to work in e2e tests and locally, and it wasn't clear why under kind, so this PR will be the canary on whether this change worked.

test: attempt to fix onboarding test flake by asserting on succes notication

---

src/utils/datetime/formatters.test.ts
src/utils/datetime/formatters.ts
src/visualization/components/internal/TimeTickInput.tsx

Closes #3620 
- uses `T` as the separator for the placeholder, reducing confusion for Safari users
- still allows space as the separator for other browsers that are more flexible such as Chrome and Firefox
- minor change to the case for the time portion of the format to differentiate `M` (month) and `m` (minutes)
This works in Safari:
https://user-images.githubusercontent.com/10736577/150049339-7923fd6b-6ead-487a-8c91-2ffa41db2d80.mp4
And it still works in Chrome using the space separator:
https://user-images.githubusercontent.com/10736577/150049484-263575dc-6ad3-4a6b-aae0-c2c982c3b837.mp4

fix: use "T" separator in time format placeholder to accomodate Safari

---

cypress/e2e/shared/dashboardsRefresh.test.ts

Closes #3621
This should resolve some flakey behavior under the current PR by removing an unnecessary assertion for the test. The failures have been happening when an event is dispatched from the test runner, which is causing some weirdness with state setting as it relates to the UI and the test runner

fix: update flakey test

---

src/authorizations/components/redesigned/DisplayTokenOverlay.tsx
src/authorizations/components/redesigned/TokenRow.tsx
src/overlays/components/OverlayController.tsx
src/overlays/reducers/overlays.ts

Closes #3616 
Before fix: Overlay title reads "You've successfully created an API token" whether token is being created or cloned. 
After fix: 
https://user-images.githubusercontent.com/66275100/150004759-b0bca547-b619-4566-ba02-ada9f70093fc.mov

feat: fix overlay title when token is cloned vs created

---

src/flows/components/header/index.tsx

Closes #3372
the titles of these are all wrong, but we essentially want to see how many users are trying  to share a notebook and then finding themselves without any tokens to make the share link with. so here is an event that'll let us say someone got to a notebook, they tried to create a share, and they had `n` api tokens available to them. we  should be able to see how many people are reaching that point with zero api tokens and use that to justify the work outlined for the  api token modal work

chore: adding new event for measuring empty token state

---

src/shared/selectors/flags.ts
src/users/components/UserListItem.tsx

Closes influxdata/quartz#4650
This allows users to remove themselves from an account when the `selfRemovalFromAccount` feature flag is on.

feat: allow self removal from account with ff on

---

src/dashboards/components/DashboardContainer.tsx
src/utils/AutoRefresher.ts

The intent of this PR is the final clean up prior to integrating the AutoRefresh work with notebooks. The crux of what we're doing is making the AutoRefresher responsible for registering and unregistering the window events rather than having the view layer be responsible for it. The reason being that the view layer should define the conditions that those events should be triggered by, rather than defining the events and their conditions

chore: make the autorefresher responsible for registering events

---

cypress/e2e/cloud/billing.test.ts
cypress/e2e/cloud/zuoraOutage.test.ts
src/me/components/UsagePanel.tsx
src/organizations/components/OrgNavigation.tsx
src/organizations/containers/OrgProfilePage.tsx
src/pageLayout/components/UserWidget.tsx
src/usage/UsagePage.tsx
src/users/components/UserListContainer.tsx

Closes #3463 #3568
renames pages,
(Organization: users->members, about->settings)
and puts the "Usage" page under the organization tabbed page
only shows if the flag is on.
just cosmetic; no functional changes.

chore: adjust page/tabbing for multi account

---

src/organizations/apis/index.ts
src/shared/components/NotFound.tsx

Closes #3569
Should handle deep linking for a user who is logged out and logs in. If `org` is null, which happens directly after they log in and hit the 404 handler, it will fetch the org and redirect them to the correct place.
Was kind of hard to test locally since we don't have an exact analogue for logging in locally. Will be able to do a better test behind a feature flag in production.

feat: handle deep linking for a logged out user

---

src/flows/pipes/Notification/view.tsx

This PR is some clean up around the auto refresh functionality for tools for users that have a notification already setup. We need to follow up on the design and user story here so that things are validated properly once the user already makes a selection but updates the existing query in the pipe above. Should we invalidate their previous selection? Should we keep it and make the sequence a submission error issue? Will need to sync with product about it @garylfowler

chore: notifications dont refresh all the time on autorefresh

---

src/flows/pipes/QueryBuilder/context.tsx
src/timeMachine/apis/queryBuilder.ts

Closes #3432
Increases the measurement tag limit from 200 to 500 for query builder and notebooks.

feat: increase measurement tag limit from 200 to 500

---

src/timeMachine/apis/QueryBuilderFetcher.ts
src/timeMachine/apis/__mocks__/queryBuilder.ts
src/timeMachine/apis/queryBuilder.ts

Closes #3688
When fixing a different bug, I noticed this function, `findBuckets`, which isn't used, but might be confused with the actively used [`getBuckets`](https://github.com/influxdata/ui/blob/9d4b60ddd95e7fbfc6818bf21413d1f18b0cfc1f/src/buckets/actions/thunks.ts#L83) which handles fetching all buckets with no limit. 
I checked on tools and this query hasn't been used in over a year; it fires an event with a tag that has no records in the past year.

chore: remove unused findBuckets function and functions making use of it

---

src/App.tsx

This PR is just some general clean-up around the GlobalRefresh work to remove the feature flag. The feature has been live for a while now with no reported issues

chore: remove GlobalRefresh feature flag

---

src/flows/pipes/QueryBuilder/context.tsx

seems like i forgot about this PR
https://github.com/influxdata/ui/pull/816
updating the query builder to escape it's regexps better

fix: escape query builder searches more better

---

src/flows/pipes/QueryBuilder/context.tsx
src/timeMachine/apis/queryBuilder.ts

Closes #3432
Follow-up to https://github.com/influxdata/ui/pull/3684

feat: increase limit of tag keys and values from 200 - 500

---

src/views/helpers/index.ts

Closes #3606
Closes #3625 
Like the description says, allows Simple Tables to be saved to dashboards. Allows other graphs to be converted to Simple Tables

fix: allow simpleTable to be saved and updated on dashboards

---

src/tasks/components/TaskRunsCard.tsx

i can't reproduce it locally, but there's a case where the task is being passed into the taskrunscard as null. i decided to patch up those cases where task can be null to see if it helps alleviate the problem.

fix: add some defensive programming in there

---

cypress/e2e/shared/explorer.test.ts

This PR is a fix on the test for #3699

fix: remove the old manual refresh test in data explorer

---

package.json
src/accounts/SwitchAccountOverlay.tsx
src/dashboards/components/variablesControlBar/DraggableDropdown.tsx
src/variables/components/VariableDropdown.scss
src/variables/components/VariableDropdownReactSelect.tsx
yarn.lock

Closes #3657 
accessible via the feature flag:  reactSelectVariableDropdown
will put in a separate idpe PR to add this (as well as put into config cat) before merging this PR
I went over the coloring and styles with andy moon.
the styling has been adjusted to look as similar as possible to the existing component.
when doing the review, compare the new file against the older, original component: https://github.com/influxdata/ui/blob/master/src/variables/components/TypeAheadVariableDropdown.tsx
screencap video:    (there are 900+ entries in the dropdown in the video below, btw)
https://user-images.githubusercontent.com/3900960/150604449-6c109c5d-e7a8-4b7c-a12c-e5b3b8201c52.mov

chore: react select type ahead var integration

---

src/tasks/components/TaskRunsCard.tsx

fix: don't reference the task's owner id's name unless it exists

---

cypress/e2e/cloud/userAccounts.test.ts
src/accounts/SwitchAccountOverlay.tsx

resets the quartz-mock testing environment.
it shouldn't need it under normal operations, but circle-ci needs our help; so here it is.

chore: resetTestEnvironment

---

src/settings/components/LoadDataTabbedPage.tsx
src/writeData/containers/WriteDataPage.tsx

Closes #215
- Makes the search box on the load-data/sources page sticky
- This makes a persistent scrollbar appear
https://user-images.githubusercontent.com/146112/151451466-56d3c989-e459-4fde-a875-8c2d89619c84.mov

fix: make the search box on the load-data/sources page sticky

---

cypress/e2e/shared/explorer.test.ts

Reverts influxdata/ui#3717
This is another part of reverting code in addition to #3737. The `AutoRefreshDropdown` is still used in Data Explorer by the code reverted in #3737, so we want to add this test back.

revert: "fix: remove the old manual refresh test in data explorer"

---

src/buckets/components/createBucketForm/BucketOverlayForm.tsx

Closes https://github.com/influxdata/ui/issues/3626
The onAddSchemasInternal is an optional property, so we should check to see when it exists when we call it. 
https://user-images.githubusercontent.com/18511823/151624127-b2ce38c4-b501-49cf-adb4-1f7f2acb5448.mov

fix: add guard rail to `onAddSchemasInternal's` `props.onAddNewMeasurementSchemas`

---

src/writeData/components/fileUploads/UploadDataDetailsView.tsx

Closes #3721
Adds back the bucket selector to Annotated CSV and Line Protocol. Keeps it removed from CSV

fix(load-data): add bucket selector back to flux annotated csv and LP

---

cypress/e2e/shared/dashboardsRefresh.test.ts
src/dashboards/components/DashboardHeader.tsx
src/flows/components/header/AutoRefreshButton.tsx
src/flows/components/header/index.tsx

Closes #3681 
This PR moves the auto refresh button next to "Run" button and update the button display name in Notebooks. 
Before:
After:

feat: move auto refresh button and update display name

---

src/timeMachine/components/Vis.tsx

Closes https://github.com/influxdata/ui/issues/3745
The problem is that the color mapping code assumes that `properties.colors` will exist. We missed the part to make sure the code is only called when the properties have the `colors` exist. 
https://user-images.githubusercontent.com/18511823/152029038-e5226173-59a0-438a-ab8b-216fcea7b543.mov

fix: check to see colors exist in the viewProperties before executing color mapping code

---

src/visualization/types/SimpleTable/style.scss

Closes #3650
Allows Safari users to select text from simple tables

fix: allow all three safari users to select simpleTable text

---

src/flows/pipes/Table/view.tsx
src/flows/pipes/Visualization/view.tsx

looks like we forgot to pass the scope into the download as csv functionality somewhere along the way. this closes that on up

fix: download as csv working again

---

src/writeData/clients/Python/dispose.example
src/writeData/clients/Python/execute.example
src/writeData/clients/Python/write.0.example
src/writeData/clients/Python/write.1.example
src/writeData/clients/Python/write.2.example

Closes #3523
Closes #3522
Closes #3524
- inter-related tickets.
- 3524 and 3523: all python block expressions, after initialization, needs to be indented.
- 3522: make sure to triple string quote the query, so no need to worry about escaping.
- copy/paste into python shell to make sure it worked.
- from all of the options on the client libraries page.
- from the export-to-client option off the flow pipes.
- could not re-create one of the situations seen in https://github.com/influxdata/ui/issues/3524.
- I assume this is the "export to client" from the flow pipes. 
- The only way this could happen would be if we were missing templates for both the `def.initialize` and `def.executeFull` in the ClientCodeCopyPage.
- not sure if I should do any hypothetical defensive coding here. I noted this …

fix(3523/3522/3524): python code gen formatting

---

src/accounts/AccountPage.tsx
src/accounts/SwitchAccountOverlay.tsx

Closes https://github.com/influxdata/ui/issues/3761
Minor styling fixes to match the design team's suggestions.
**Account Page**
Prev:
After change:
**Modal**
Prev:
After change:

fix: (Multi-Account) switch account modal styling tweaks

---

package.json
src/alerting/utils/history.test.ts
src/alerting/utils/statusEvents.test.ts
src/shared/contexts/csv.worker.ts
src/shared/utils/fromFlux.legacy.ts
src/shared/utils/fromFlux.test.ts
src/shared/utils/fromFlux.ts
src/timeMachine/selectors/index.ts
src/visualization/types/Map/view.test.tsx
src/visualization/types/Scatter/TimeAutoToggle.test.tsx
yarn.lock

Part 1 of #3404 
- updates Giraffe to use the new `fromFlux`
- updates all other versions of `fromFlux` to minimize confusion
- the new property `resultColumnNames` can be safely ignored if not needed

feat: update all versions of fromFlux

---

cypress/e2e/oss/onboarding.test.ts

Visiting before intercepting in Cypress is known to cause flakiness.
- move all `.intercept`s into the `beforeEach` and before `.visit`
- remove the unnecessary and deprecated `cy.server`
- assert the notification banner for the successful creation of a user in all 3 onboarding tests

test: move intercept before visit

---

src/flows/pipes/Notification/endpoints/HTTP/index.ts

Closes #3706
Issue was that the test Alert, in notebooks, was not functional.
* small change to query used for http alerts in notebook. 
* Update to latest flux syntax, and confirm is working.
* change the running task query to also use the latest flux syntax.
* confirmed is still working. payload not changed either.
* Confirmed the notebooks task lifecycle still works (for http notifications):
1. send test alert
2. export alert as task
3. task runs, sending notifications
4. inactivate task --> see that it stop sending notifications.
* test alert
* outut flux from exported task
* exported task will run
* comparison of parsed body (before and after changes). tl;dr payload is the same.
* before:
```
{
"_check_id": "d8b1gd7p7565",
"_check_name": "Notebook Generated Check",
"_level": "crit", …
```

fix(3706): test query for notebooks alert http endpoint

---

src/flows/pipes/Schedule/ExportTaskButton.tsx

we've been waiting on trying the new task publish lifecycle because it didn't work when the notebook isn't saved. this isn't the default in dev mode, and i'm pretty sure we're inverting this pattern to make the publish button responsible for exporting resources, but it's currently the way prod works.
SO WE'RE SHORING IT UP UNTIL THEN

fix: save a notebook if it is ephemeral before linking

---

package.json
src/flows/components/header/PublishedVersions.tsx
src/flows/components/header/VersionBullet.scss
src/flows/components/header/VersionBullet.tsx
src/flows/components/header/index.tsx
src/flows/context/version.publish.tsx
src/style/chronograf.scss

So KAP was giving me a hard time with a gif, here's a picture:
As part of the publish lifecycle work, we're going to want to allow users to scroll through their previous version history in order to potential revert / clone from a specific version of a notebook's published history. 
The purpose of this PR is to allow a simple interface for users to be able to see at a glance their published history (by who and when). This does not fully integrate the full lifecycle of a user viewing their published history, but merely introduces the first step at that.

feat: get all the version history for the user and have a hover state with a glimpse at the publish by and publish at

---

src/flows/components/header/index.tsx

Turns out moving the event.preventDefault on a function that shouldn't be invoked broke everything

chore: fix flow header issue where nothing is responsive

---

src/operator/account/AssociatedUsersTable.tsx

Closes influxdata/quartz#5656
Part of influxdata/quartz#5941
Hides button to delete the last user of an account from the operator page when they are the last user.

feat(ecommerce): Hide remove last user in operator page

---

src/accounts/AccountPage.tsx

Closes https://github.com/influxdata/ui/issues/3812
Missed adding the flag before shipping [this](https://github.com/influxdata/ui/pull/3770) 🚢 
Feature flag name: `freeAccountCancellation`
https://user-images.githubusercontent.com/18511823/153250208-623cffc7-e7e3-4055-bcb4-b9f811b3a043.mov

chore: add feature flag around the deactivate button

---

cypress/e2e/cloud/operatorRO.test.ts
package.json
src/billing/components/Free/OrgLimits.tsx
src/billing/utils/timeHelpers.test.ts
src/billing/utils/timeHelpers.ts
src/cloud/actions/limits.ts
src/cloud/reducers/limits.ts
src/operator/OrgOverlay.tsx
src/operator/context/overlay.tsx
src/operator/utils.test.ts
src/operator/utils.ts
src/types/operator.ts

Part of Quartz #5810
I added `query time` to the limits display in `Operator` view. This also required changing to the new `OperatorOrgLimits` type in the operator related files. Additionally `query time` was added to the `LimitsReducer` to allow for update request in Operator view, but is filtered from `LimitStatus` to avoid displaying the limit type for non-Operators. 
Non-operator view: 
Operator view and function:
https://user-images.githubusercontent.com/64158805/153093491-c4920cf2-1856-4041-a5c7-c5197518e6f4.mp4

feat: Add query time to Operator view

---

package.json
yarn.lock

There are a number of fixes and good features in the delta between
`0.8.0` and `0.8.5`, and there's a specific issue where the UI is acting
differently than the flux-lsp binary (with vim) and vsflux, and we'd
like to see if this update fixes it.

chore: upgrade lsp to 0.8.5

---

src/accounts/context/userAccount.tsx
src/me/actions/thunks/index.ts

Closes https://github.com/influxdata/ui/issues/3757
Depends on: https://github.com/influxdata/idpe/issues/13230
Bug fix is behind a feature flag. `avatarNameForMultiAccountFix`.
https://user-images.githubusercontent.com/18511823/153654020-c95c9abd-1795-45d2-96c4-7f5505532669.mov

fix: update the avatar name when account is switched

---

src/flows/context/flow.current.tsx
src/flows/context/pipe.tsx

Closes #3826
Previously there were two issues with deep-linking to a panel. Firstly, the deep linking would happen prior to the results being loaded in, rendering the deep link ineffective because the results would expand the previous panels and all context as to which panel was being linked to would be lost. Finally, since the deep-linking is in a useEffect, toggles and little interactions with a deep-linked panel would reset the location of the user to that panel, making the notebook frustratingly difficult to use once a panel query parameter was set in the URL. 
This PR resolves the aforementioned issues by:
1. Moving the deep linking to the panel level to check the status of the panels and only deep link to a panel once the panels have finished loading
2. Remove the query parameter in …

fix: deep linking to a notebook pipe

---

src/flows/pipes/Visualization/view.tsx

Closes #3828
This PR adds a lifecycle method to listen for changes to the results in the visualization. That listener then triggers a callback to check to see whether the existing error thresholds are still relevant to the given data set, and if not, then the error thresholds are updated to remove the no-longer-relevant error threshold

chore: invalidate error thresholds when the query has changed and they are no longer relevant

---

src/checkout/context/checkout.tsx
src/me/components/Resources.tsx
src/me/containers/MePage.tsx

UI part of removing the flag `paygCheckoutCredit` mentioned in #3686.
This PR removes the feature flag `paygCheckoutCredit` for PAYG Credit Test. 
Once this PR is merged, I'm going to remove this flag in IDPE.

chore: remove feature flag `paygCheckoutCredit`

---

src/flows/pipes/MetricSelector/index.ts
src/flows/pipes/QueryBuilder/index.ts

No ticket. (Found while using. Fast fix.)
* no newline inserted when going queryBuilder --> output to flux.
https://user-images.githubusercontent.com/10232835/153931604-8b09791e-4691-4eec-868d-30e6dba60be4.mov
https://user-images.githubusercontent.com/10232835/153931336-962e42c3-a9c4-42b4-b0bc-68c002f7ed90.mov

fix: add newline to flux output, after bucket src and before range

---

src/authorizations/components/CustomApiTokenOverlay.tsx
src/authorizations/components/EditResourceAccordion.tsx
src/authorizations/components/ResourceAccordion.tsx
src/authorizations/utils/permissions.test.ts
src/authorizations/utils/permissions.ts

Closes #3600 
When creating a custom api token and a user selects `read` permissions for a specific bucket but then toggles `write` permissions for all buckets, it creates the token for `bucket: read` and `all buckets: write` and fails horribly when trying to view that token. For now, I have added the logic that when all buckets `read/write` toggle happens, we want to keep the specific read/write selections and the accordion open. We will collapse the accordion only when both toggle all for read and write are checked.. Just trying to fix this issue instead of failing terrible in the UI. This is going to be discussed with Balaji and Daniel to get proper design and a new issue will be created to track the progress.

fix: token issue when creating specific/all buckets token

---

src/alerting/components/AlertingIndex.tsx
src/notifications/endpoints/selectors/index.ts
src/notifications/rules/components/NewRuleOverlay.tsx
src/notifications/rules/components/RuleMessage.tsx
src/notifications/rules/components/RulesColumn.tsx
src/notifications/rules/selectors/index.ts
src/overlays/components/OverlayController.tsx
src/overlays/reducers/overlays.ts

Closes #3629 
Problem was that in the Alerts part of the application, a disabled endpoint was still available to create a Notification Rule.
* make selector for getAllActiveEndpoints()
* use the new state connector pattern in the components touched (NewRuleOverlay, RuleMessage, RulesColumn, AlertsColumn)
* use our new overlay controller part in the overlay touched (NewRuleOverlay).
* confirmed worked (see video below).
* confirmed could still create function e2e alert notifications.
https://user-images.githubusercontent.com/10232835/153638262-5c4a79e7-4aa3-4ff0-9f5e-1ffd4bfd5569.mov

fix(3629): cannot create rules from deactive endpoints

---

src/me/components/PinnedItems.scss
src/me/components/PinnedItems.tsx

Closes #3860 
This PR fixed the pinned item titles overflow issue.

fix: wrap long words in pinned items titles into multiple lines

---

src/flows/pipes/Notification/endpoints/Mailgun/index.ts

Closes #3805 
**Error**
There were a couple of underlying causes. The first cause was with the existing escape sequence. The second cause was that the http post was not conforming to what mailgun expects.
Updated to send the payload expected by mailgun. Because we aren't escaping much, there's no issue of escape sequence anymore.

fix: fix mailgun alert

---

cypress/e2e/shared/explorerVisualizations.test.ts
cypress/e2e/shared/flows.test.ts

Fixes the flakiness with the Band tests.
- assert the visibility of the graph, which means the query has completed
- do not assert the icon, which is always there even before the query is submitted

test: assert the graph and not the icon

---

cypress/e2e/shared/explorerVisualizations.test.ts
cypress/e2e/shared/flows.test.ts

Not sure if this is the cause of all the other tests randomly failing. Probably not, but still. Let's close the brackets here.

test: close the brackets on the cypress selector

---

src/telegrafs/components/TelegrafConfigOverlay.tsx

we had a bunch of unique event names showing up in our dataset that were slowing down queries and making it hard to find things. turns out it was because there was an event that changed it's name everytime it was run, resulting in a lot of unique event names. the information it was embedding into the event name is already embedded in the event by the nature of it being an event, so it wasn't required to inject the user's browser's perspective of the time of the event into the meta data.

fix: cardinality issue

---

src/authorizations/components/AllAccessTokenOverlay.tsx
src/authorizations/components/GenerateTokenDropdown.tsx
src/authorizations/utils/permissions.test.ts
src/authorizations/utils/permissions.ts
src/resources/selectors/index.ts

Closes #3836 
Allows All Access Tokens to get all resources and use the tokens' `allResources` list to populate all the permissions.
https://user-images.githubusercontent.com/10736577/154393911-bcf63b2a-8131-4935-b412-42523ef171b0.mp4

fix: allow All Access Tokens to use all resources

---

cypress/e2e/cloud/checkout.test.ts

Adds a root level describe block to the checkout test suite. It is a bad practice to have a single test suite with more than one root level `describe` block as it can cause weird behavior during test execution.
https://stackoverflow.com/questions/56139892/having-multiple-describe-in-spec-leads-to-weird-behaviour
Note: visit this page to see changes more clearly: https://github.com/influxdata/ui/pull/3911/files?w=1

test(checkout): add root level describe block

---

cypress/e2e/shared/flowsAlerts.test.ts
src/flows/pipes/Notification/endpoints/HTTP/index.ts
src/flows/pipes/Notification/endpoints/HTTP/view.tsx

Closes #3873
Closes #3874 
Closes #3876 
* tickets 3873, 3874, and 3876 were all an artifact of the http notifications **basic auth** not yet using the secrets flux API. That has now been updated for notebook alerts.
* also then did the same for the http notifications **tokens**.
.
Test alert uses secrets, for basic auth:
Exported task uses secrets, for basic auth:
Exported task successfully runs:
.
Test alert uses secrets, for token:
Exported task uses secrets, for token:
Exported task successfully runs:
.

fix(3873/3874/3876): secrets in http alerts

---

cypress/e2e/shared/dashboardsView.test.ts
src/dashboards/components/AutoRefresh.scss
src/shared/components/cells/Cell.scss
src/shared/components/cells/CellCloneOverlay.tsx
src/shared/components/cells/CellContext.tsx

Closes #3934 
This PR updated the UI design for cloning cells across dashboards because we would like to release the ability to clone cells across dashboards to production (https://github.com/influxdata/ui/issues/3678). 
https://user-images.githubusercontent.com/14298407/155388378-1ea09410-b650-4bba-95cd-20ed10b9202a.mov

chore: update design for cloning cells across dashboards

---

src/flows/pipes/Notification/view.tsx

Closes #3927 
This PR updates the button name to "Test Endpoint" in Notebook alert panel.

chore(notebook): update button name to "Test Endpoint"

---

cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
cypress/e2e/shared/tasks.test.ts

Related #3898
Closes #2887
This PR updates a couple of the flakey tests since there seemed to be weirdness with the autocomplete type functionality that we were using in the tests. We lose out on testing that stuff out in these changes, but their inconsistency was leading to a level of flakiness that warranted something more predictable that wouldn't cause errors.

fix: work on some flakey tests

---

src/flows/components/header/index.tsx

Closes #3766
This is a weird edge case where navigating to a newly cloned notebook after sharing and cancelling out of the shared state would keep a reference to the original share in the state. Clearing it out seems to do the trick, but this kind of seems indicative that there's some sort of memoization happening where data isn't being properly cleared when the state changes for the component.

fix: set share to null to reset the state

---

src/dataLoaders/components/collectorsWizard/select/TelegrafUIRefreshSelector.tsx
src/flows/context/flow.query.tsx
src/flows/pipes/MetricSelector/index.ts
src/flows/pipes/QueryBuilder/AddButton.tsx
src/flows/pipes/QueryBuilder/BucketSelector.tsx
src/flows/pipes/QueryBuilder/CardList.tsx
src/writeData/components/ClientLibrarySection.tsx
src/writeData/components/FileUploadSection.tsx
src/writeData/components/TelegrafPluginSection.tsx
src/writeData/components/WriteDataItem.tsx

as part of this: https://github.com/influxdata/ui/issues/3941 and a greater question about user interaction with the query builder, i found out that we dont have a lot of data around the query builder interaction. While i was auditing in there, i found that we also dont have great events around the data sources page (the current version of the event prevents any kind of grouping), which triggered some rework of the module layout to allow for the different types of interactions to be segmented properly. 
also moved metric selector back behind a flag because product needed to review it

fix: auditing some events

---

package.json
src/buckets/components/BucketCardMeta.tsx
src/secrets/components/SecretContextMenu.tsx
src/shared/components/CopyButton.tsx
src/shared/components/CopyResourceID.tsx
src/shared/components/CopyToClipboard.tsx
src/shared/components/EmptyGraphError.tsx
src/shared/components/EmptyGraphErrorTooltip.tsx
yarn.lock

Closes #3591 
This PR removed the dependency library `react-copy-to-clipboard` and replaced it with native JS.

chore: replace `react-copy-to-clipboard` with native JS

---

cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
src/writeData/components/ClientCodeCopyPage/index.tsx
src/writeData/components/ClientCodeQueryHelper.tsx
src/writeData/components/WriteDataDetailsContext.tsx

we used to have a mechanism that would autoselect the first bucket and auth token, then load it for people into the template for their client code examples. we removed that feature, but kept in the mechanism, leading to weird behavior as the page lived on and tokens were loaded behind the scene. this removes those mechanisms.

fix: remove old token and bucket linking

---

src/flows/components/header/index.tsx
src/flows/pipes/Visualization/view.tsx

Closes #3829
Map background is not shown in the downloaded PDF/PNG files when the graph panel is set to 'Map' in Notebook. This PR fixes this issue. These features are behind the feature flags `downloadNotebookPDF` and `pdfImageDownload`.
https://user-images.githubusercontent.com/14298407/155740767-0292d84c-2384-4179-95d9-1b196720c658.mov

fix(notebook): enable map to show in pdf/png download

---

src/flows/components/FromTemplatePage.tsx
src/flows/components/header/SaveState.tsx
src/flows/components/header/index.tsx
src/flows/context/flow.current.tsx

Having the two enabled at the same time was confusing folks. Shutting this off to capture the fact that ephemeral notebooks should be removed if the publish lifecycle stuff gets prioritized

chore: remove the save ephemeral notebook when the publish lifecycle is set

---

src/operator/LimitsField.tsx

In the Operator UI for organization limits, some larger numbers are difficult to read without commas to break apart the places. For example, one million is easier to read as `1,000,000` than `1000000`. 
This adds these separators, based on region, to the rate limits screen.

chore(ecommerce): Add commas to Operator UI Limits

---

src/shared/apis/queryCache.ts

we are hitting some resource limits at amplitude, and there's some events we're not currently optimizing, so lets stop reporting them

chore: remove event we arent looking at

---

src/timeMachine/components/QueriesSwitcher.tsx
src/timeMachine/components/TimeMachineFluxEditor.tsx

We want to get an idea of how many users are ripping out the aggregateWindow that's baked into the query builder. By adding these events, we get a better idea of the feature's functionality and make some progressive developments based on that

chore: add eventing for query builder / script editor

---

cypress/e2e/cloud/userAccounts.test.ts

- moves all userAccount tests into a single `describe` block
- does the `cy.flush` during the setup instead of randomly for one block

test: move userAccount tests into a single root describe and flush during setup

---

cypress/e2e/cloud/userAccounts.test.ts

Fixes the flaky userAccounts tests:
- always check that Quartz has populated all of the multi-accounts first
- do not assume a particular account name is present
- rename the current account, then use that in the assertions

test: fix flaky userAccounts tests

---

src/flows/components/PipeList.tsx
src/flows/components/panel/FlowPanel.tsx
src/flows/components/panel/InsertCellButton.scss
src/flows/components/panel/InsertCellButton.tsx

people aren't adding cells into their notebooks. this has a bunch of problems like having people lean on the limited templating system and limiting a lot of the potential of notebooks to morph with people's needs and follow them along the journey of their data discovery. It turns out that 84% of users will never click on that little purple plus button. The edit queries and run them, but dont extend them. Of those who DO click on that button, 70% of the users find something useful in there.
this PR exposes the panel insertion interface right on the top level, which doesn't just make insertion a lot easier / quicker, but will hopefully get those 80% of users exposed to whatever those limited users found was useful in there. i'd expect the total number of users who add a panel to raise above …

feat: always on insert

---

src/authorizations/components/TokenRow.tsx

Closes #3868 
pr replaces `created by` with `owner` in Token's resource card meta data

feat: replacing created by with owner

---

cypress/e2e/shared/tasks.test.ts
src/shared/components/AddResourceDropdown.tsx
src/shared/containers/SetOrg.tsx
src/shared/containers/index.tsx
src/tasks/actions/thunks.ts
src/tasks/apis/index.ts
src/tasks/components/TaskCard.tsx
src/tasks/components/TaskImportOverlay.tsx
src/tasks/components/TasksHeader.tsx
src/tasks/containers/TasksPage.test.tsx
src/tasks/containers/TasksPage.tsx

Closes #3848 
PR fixes a bug in Tasks page of UI. The export button no longer works as the export overlay was removed.  
UI before fix: 
https://user-images.githubusercontent.com/66275100/156034490-2a40c88d-0611-423c-bfa0-85ba385f04db.mov
UI after fix: 
https://user-images.githubusercontent.com/66275100/156049806-e666d0ef-cf51-4f2e-b901-d697a95bc55e.mov

feat: added ability to export tasks using v2 template

---

src/flows/pipes/Notification/endpoints/Zenoss/index.ts

fix: fix zenoss alert parsing issue

---

src/flows/components/AddButtons.tsx
src/flows/context/flow.query.tsx
src/flows/pipes/Region/index.ts
src/flows/pipes/Time/index.ts
src/types/flows.ts

when importing from tools this week, i found that the cross region panel wasn't populating default values correctly for the scope. so i fixed that. I also moved those context panels into their own thing until we decide what to do with them

fix: region issues
