influxdata/ui

- cypress/e2e/shared/tasks.test.ts
Addresses #2887 
Addresses #3942 
while creating a task, cypress interprets new line in template literal as enter, which causes autocomplete to populate flux editor (adding an unnecessary syntax) 
fix ->  added an escape command `{esc}` to avoid auto completion.
> test(task): type esc to avoid auto complete

- cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
We want to do this because:
- `cy.monacoType` should be less aggressive, which works everywhere except here
- implement special monaco typing for Flows as isolated changes
- do this as a separate PR to get the multi-runs in the CI
> test: refactor the flowsSidebarExportToClipboard tests to avoid using .monacoType

- src/visualization/components/internal/ThresholdsSettings.tsx
Closes #3343
closes #3864 
When customizing color threshold of a table in Data Explorer page, the UI crashes and outputs a `maximum update depth exceeded` error in the console. This error is caused by a UseEffect hook that updates a variable in its own dependency array, causing an infinite re-render loop. 
fix: remove `onSetThresholds` from Effect's dependency array to stop the infinite re-rending.
https://user-images.githubusercontent.com/66275100/156592203-b349162a-0b70-473a-9870-85289c9504ed.mov
> fix: remove unnecessary variable from useEffect dependency array

- cypress/e2e/shared/explorer.test.ts
Refactors `explorer.test.ts`
- do not use `{rightarraow}` in some places
- explicitly call `.should('exist')` or `.should('be.visible')` for clarity
- updates test for manual refreshing to something simpler and more sane
> test: refactor explorer tests

- src/flows/pipes/Notification/view.tsx
- src/shared/copy/notifications.ts
Part of #3880 
* errors are surfaced when using bad creds for HTTP post notification
* cannot fix this specific one. the backend returns a 2xx, and nothing significant in the response body.
* general case: when the backend returns an error, we are not surfacing that specific error.
* note: backend has updated itself to throw when there is a badURL used.
* we need to surface that exact error returned.   
* error from the API call is already processed here: https://github.com/influxdata/ui/blob/master/src/shared/contexts/query.tsx#L509-L522
* then is caught, and only the message (which we want) is passed up: https://github.com/influxdata/ui/blob/master/src/shared/contexts/query.tsx#L562-L569
* therefore, we should only have to pass along this message to a UI view element
. …
> fix(3880): surface errors from query endpoint response, to the testNotification panel

- cypress/e2e/cloud/operator.test.ts
Makes cloud/operator test more reliable
- use `cy.intercept` because every character in the search bar triggers an api call
- wait on each call and assert at will
- a few other minor fixes
> fix: make cloud/operator test more reliable

- src/flows/components/header/AutoRefreshButton.tsx
- src/flows/components/header/Submit.tsx
- src/flows/pipes/Notification/ExportTask.tsx
when trying to reproduce this one: https://github.com/influxdata/ui/issues/3919
i found out that our imports are all messed up, and if you try  to use a query that implements an import, we just fail silently
this normalizes the imports for the task generation mechanisms and combines them with the user defined  query's imports
> fix: allow alerts with imports

- src/flows/pipes/Notification/ExportTask.tsx
- src/flows/pipes/Schedule/ExportTaskButton.tsx
based on tanking conversion numbers for alert generation while notebook utilization continues to climb, the front side validation of our notebooks alerts panel that was recently added seems to be preventing users from generating alerts over the past week. this pr is to unblock those customers trying to create an alert while we riff on the implementation to capture the intent of the original implementation.
> fix: unblock users for the weekend

- src/writeData/clients/Java/description.md
- src/writeData/clients/Kotlin/description.md
- src/writeData/clients/Scala/description.md
1. From the Gradle 7.0 the `compile` configuration is not supported anymore. The correct configuration is `implementation`.
2. Update JVM clients to latest version.
> fix(client_libs): installation instruction for Gradle

- src/operator/constants.tsx
In the operator UI, when viewing organizations, the account ID will now link the to associated account's details page.
> feat: Make `Account ID`link to the account details

- package.json
- src/shared/components/views/MarkdownRenderer.tsx
- yarn.lock
Closes https://github.com/influxdata/idpe/issues/13555
- Installs the plugin [rehype-external-links](https://github.com/rehypejs/rehype-external-links)
- Tested markdown in the following areas and saw no obvious regressions:
- dashboard notes
- notebook notes
- load-data markdown files
- community templates readme
> chore: add noreferrer to links generated in react-markdown

- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/dashboards/components/dashboard_index/DashboardCards.tsx
- src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx
- src/flows/components/FlowContextMenu.tsx
- src/tasks/components/TaskCard.test.tsx
- src/tasks/components/TaskCard.tsx
- src/tasks/components/TasksList.tsx
Closes #3862 
For pinned items, the current way to remove a pinned item is to unpin it from the home page. This PR enables another way of unpinning an item from the resource list location. This applies to Notebooks, Dashboards, and Tasks.
Here is a demo for Notebook:
https://user-images.githubusercontent.com/14298407/156846371-883fa1db-b50a-4a6b-8d87-b5f390c96d32.mov
> feat: unpinning an item from the resource location

- cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
- src/flows/components/ClientList.tsx
- src/flows/components/Sidebar.scss
- src/flows/components/Sidebar.tsx
Closes #3438 
This PR updates the exit button for Notebook side panel, and removes the awkward gaps between client libraries.
> style: update exit button and remove gaps in Notebook side panel

- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/flows/components/FlowCard.tsx
- src/tasks/components/TaskCard.tsx
Closes #4009 
This PR fixes the bug that showing notification for non-pinned items.
https://user-images.githubusercontent.com/14298407/157329339-9fc23692-4e2d-41e4-bb80-7879af8356f2.mov
https://user-images.githubusercontent.com/14298407/157330485-4f354883-6016-466f-b7e3-c35c35188b66.mov
> fix: only show notification for pinned items

- src/accounts/AccountPage.tsx
Closes https://github.com/influxdata/ui/issues/4061
The context was missing from the page, so the `users` were coming back as an empty array. This caused the self-removal button to not be visible.
https://user-images.githubusercontent.com/18511823/157530403-3ecb3182-6656-4fae-b395-f0ca51893dea.mov
> fix: provide usersProvider context to the AccountPage.tsx for self removal to work

- .circleci/config.yml
Part of: https://github.com/influxdata/ui/issues/3565
* When making changes in quartz-mock PR, incorporate CI tests including e2e with UI.
* Make it such that bad mock bad (in quartz-mock), does not break our CI pipeline.
* explicitly set the workflow enum which is run.
* have both a SHA and UI_SHA.
* confirmed it works by testing against a temporarily published ui-pipeline quay image, paired with the monitor-ci PR branch:
* https://github.com/influxdata/ui/pull/3988/commits/43668daa25ac3046177404e3330036228a66d9f9 
* https://github.com/influxdata/monitor-ci/pull/349
* revert: https://github.com/influxdata/ui/pull/3988/commits/43668daa25ac3046177404e3330036228a66d9f9
> chore: update to pipeline env vars passed to monitor-ci

- src/flows/pipes/Notification/endpoints/Mailgun/index.ts
Closes #3945 
* Notebook alert, for mailgun, gets exported to a task.
* This export succeeds --> because no validation before export (a.k.a. task creation).
* But when you try running the task --> it gives an error.
fixed the flux script.
task succeeds (runs successfully)
see the flux exported
**do not have a mailgun account** so cannot confirm that roundtrip. Can only confirm that the flux query runs.
> fix(3945): mailgun exported alert task

- src/flows/components/panel/FlowPanel.tsx
- src/flows/components/panel/InsertCellButton.scss
- src/flows/components/panel/InsertCellButton.tsx
- src/flows/style.scss
now that we're encouraging people to insert more panels in their notebooks, and they're getting introduced to the concept, lets dedicate less visual space to the edge cases of that process. 
query development in notebooks is predominately a top to bottom kind of thing. we want them to start, find something interesting, move on to finding something else interesting, and have a record of that whole exploration. if we think of the notebook as a chronological exploration and not as an artifact, inserting panels between each other becomes an edge case, predominately used for polishing an exploration into an artifact. because we want to focus on that initial exploratory interaction, even though we still need to give the user the affordances to do these actions for later, we dont need to make it …
> feat: less visual weight

- src/buckets/components/BucketsTab.tsx
- src/buckets/pagination/BucketsTab.tsx
Closes https://github.com/influxdata/idpe/issues/12739
Buckets list: allows filtering of bucket by bucket id. Works in paginated and non-paginated versions.
https://user-images.githubusercontent.com/146112/158209375-17992bd7-1888-4677-a3a8-f3cff058af9b.mov
> feat(bucket-list): allow filtering by bucket id

- package.json
- src/flows/components/header/MenuButton.tsx
- src/flows/context/version.publish.tsx
- yarn.lock
By bumping the clockface library and updating the icon to match the design, this _should_ mark the feature as complete
> chore: update the icon and complete the feature

- src/flows/pipes/Visualization/Controls.tsx
- src/flows/pipes/Visualization/view.tsx
This PR is follow-up on the error threshold work for notebooks. We've got eventing to track the feature usage and it's been stable for a while. Removing the feature flag and committing to the feature
> chore: remove the feature flag for error thresholds

- cypress/e2e/shared/buckets.test.ts
- cypress/e2e/shared/telegrafPlugins.test.ts
- cypress/e2e/shared/telegrafs.test.ts
- src/dataLoaders/actions/dataLoaders.ts
- src/dataLoaders/components/collectorsWizard/select/TelegrafUIRefreshCollectorsStep.tsx
- src/dataLoaders/reducers/dataLoaders.ts
- src/telegrafs/containers/TelegrafsPage.tsx
- src/writeData/containers/TelegrafPluginsPage.tsx
Part of #3747 
- removes the feature flag `telegrafUiRefresh`
- removes tests for code that no longer exists
- drastically reduce the usage of `telegrafUiRefresh` in naming
> chore: remove telegrafUiRefresh feature flag

- src/homepageExperience/components/steps/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/ExecuteQuery.tsx
- src/homepageExperience/components/steps/InstallDependencies.tsx
- src/homepageExperience/components/steps/WriteData.tsx
- src/homepageExperience/containers/HomepageContainer.tsx
- src/shared/components/CodeSnippet.tsx
Closes #4100
- Updates `CodeSnippet` to take in an optional prop to hide the `Copy To Clipboard` button
- Links the homepage cards to their respective places
- Updates the firstMile copy with the text changes from feeback
> chore: firstMile text tweaks

- src/flows/components/VersionSidebar.tsx
- src/flows/components/header/MenuButton.tsx
Closes #4120
This PR removes the conditional rendering of the back button for the publish history so that the draft version is always accessible from the version history. It also updates the view history button to be a bit better guarded against race 
conditions
> feat: keep draft state button accessible always

- src/homepageExperience/components/HomepageExperience.scss
Closes https://github.com/influxdata/ui/issues/4118
Prev:
https://user-images.githubusercontent.com/18511823/158647313-02deb72f-d45f-492c-a5e1-e8aa1a0b66f3.mov
After:
https://user-images.githubusercontent.com/18511823/158647348-d9287d38-e4f5-4713-99d0-8bea3ff100ea.mov
> fix: keep navigation buttons for the firstMile in the same place

- CODEOWNERS
- src/writeData/subscriptions/components/BrokerForm.tsx
Quick bug fix to the Subscriptions form regarding the max length properties
Also includes a change to the CODEOWNERS file that sets the data acquisition team as owners of the Subscriptions related code in this repo
> fix(sub): max lengths

- src/annotations/components/annotationForm/AnnotationForm.tsx
- src/dataExplorer/components/SaveAsCellForm.tsx
- src/dataLoaders/actions/dataLoaders.ts
- src/shared/components/cells/Cell.tsx
- src/templates/components/CommunityTemplateInstallOverlay.test.tsx
- src/templates/components/CommunityTemplateInstallOverlay.tsx
- src/visualization/utils/annotationUtils.ts
these events were blowing up our event cardinality by having improperly formatted event names (embedding segmentation keys into the event name). too much of that and our eventing gets turned off, so i cleaned them up
> fix: auditing more events

- src/homepageExperience/components/steps/CreateToken.tsx
- src/homepageExperience/components/steps/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/ExecuteQuery.tsx
- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/InitalizeClient.tsx
- src/homepageExperience/components/steps/InstallDependencies.tsx
- src/homepageExperience/components/steps/Overview.tsx
- src/homepageExperience/components/steps/Step.tsx
- src/homepageExperience/components/steps/WriteData.tsx
- src/homepageExperience/containers/HomepageContainer.scss
- src/homepageExperience/containers/HomepageContainer.tsx
- src/homepageExperience/containers/HomepagePythonWizard.tsx
- src/utils/SafeBlankLink.tsx
Connects https://github.com/influxdata/ui/issues/3897
Current progress:
- Track # accounts per next step selection 
- Track the time to completion per account
- ✅ Track % accounts complete wizard (% accounts complete setup) 
- Track time per step so that we can see where users are getting "Stuck" 
- ✅ Track how many times the user click the "previous" button per session 
- ✅ Track if a user clicks the documentation link per step/screen 
- ✅ Track if a user clicked on the copy/code snippet per step/screen; where applicable 
- Track Upgrade Now clicks before vs after completing wizard
- ✅ how many went to Python vs other options 
- how many dropped off at each step
> feat: first mile events for data collection

- src/homepageExperience/components/steps/ExecuteQuery.tsx
Closes https://github.com/influxdata/ui/issues/4135
Connects: https://github.com/influxdata/ui/issues/4140
The other half of the #4140 is addressed in #4142 
Somehow the `mean()` slipped into the query!
> fix: remove aggregate function from the Execute query page (first mile)

- src/authorizations/components/CustomApiTokenOverlay.tsx
- src/authorizations/utils/permissions.ts
- src/pageLayout/constants/navigationHierarchy.ts
- src/settings/components/LoadDataNavigation.tsx
- src/shared/containers/SetOrg.tsx
- src/writeData/components/WriteDataSections.tsx
This PR includes two changes:
1. Change subscriptions feature flag from `subscriptionsResourceType` to `subscriptionsUI`
2. Filters out `subscriptions` from the Custom API Token overlay unless `subscriptionsUI` flag is on
Due to some limitations on deployment's side of things we need to be able to turn on `subscriptionsResourceType` in all clusters now even tho Cloud Native Subscriptions will not be enabled in all clusters yet. We also want to be able to include `subscriptions` in the All Access tokens that are generated (again, for deployment reasons). But we don't want `subscriptions` permission to show up in the Custom API Token permissions list until the UI is turned on.
New flag has already been added to IDPE and config cat
`subscriptionsUI` enabled:
`subscriptionsUI` disabled:
> chore(sub): change subscriptions feature flag

- .gitignore
Simplifies various development flows by ignoring files they may be adding.
> chore: add test files in public to .gitignore

- src/flows/components/FlowCards.tsx
- src/flows/components/FlowContextMenu.tsx
- src/flows/components/FlowsIndex.tsx
- src/flows/components/FlowsIndexEmpty.tsx
- src/flows/components/PresetFlows.scss
- src/flows/components/PresetFlows.tsx
- src/flows/components/PresetFlowsButtons.tsx
- src/flows/components/ShareOverlay.tsx
- src/flows/components/header/MenuButton.tsx
- src/flows/components/panel/InsertCellButton.scss
- src/flows/style.scss
- src/variables/components/VariablesTab.test.tsx
after modifying the insert button within the notebook, i found a couple of css bugs dealing with padding and hover states. once those were fixed, i found a bunch of bugs on the list page dealing with scaling and scrolling of the page and trudged on. when fighting one of the grids, i found that we're creating problems for ourselves by the way we're structuring our grids within clockface's Page rules, all in order to facilitate that tutorial text that takes up 1/3 of the page. As i was trying to find solutions to that, i started to wonder if it were not just best to remove the text instead of restructuring the page. so i made a flag to do that so that people could click around and see which way we should invest our time later.
[without flag]
[with flag]
> fix: small insert panel bugs

- cypress/e2e/shared/legends.test.ts
- cypress/fixtures/routes.json
- src/visualization/components/View.test.tsx
- src/visualization/utils/useStaticLegend.ts
Closes #3962 
Static Legend now selects the correct context, either Notebooks or Time Machine, and does its magic in auto calculating the initial height for the size of the legend box.
https://user-images.githubusercontent.com/10736577/158919514-a808583d-f3ca-4bbb-8e93-5392e3ffbc39.mp4
> fix: allow StaticLegend to work with Notebooks pipe context

- src/flows/pipes/Notification/ExportTask.tsx
- src/flows/pipes/Notification/endpoints/AWS/index.ts
- src/flows/pipes/Notification/endpoints/Mailgun/index.ts
- src/flows/pipes/Schedule/ExportTaskButton.tsx
Closes #4159
This PR enables a few endpoints that are proven to work in the UI by removing their feature flags. It also adds eventing around successfully exported alerts so that we can gain an understanding of which exported alerts users are gravitating towards
> feat: remove feature flag from working alerts and add eventing for successful exports

- src/dashboards/components/AutoRefreshOverlay.tsx
- src/variables/components/VariablesTab.test.tsx
Closes #4164 
This PR updates the wording for the auto refresh overlay by making it context aware. This also updates the eventing so that we have more clarity on where this feature is being used more
> fix: make the autorefresh wording context specific

- cypress/e2e/cloud/billing.test.ts
- cypress/e2e/cloud/zuoraOutage.test.ts
- src/accounts/CancellationOverlay.tsx
- src/accounts/context/userAccount.tsx
- src/billing/components/PayAsYouGo/CancellationOverlay.tsx
- src/billing/components/PayAsYouGo/CancellationPanel.tsx
- src/billing/components/PayAsYouGo/TermsCancellationOverlay.tsx
- src/billing/context/billing.tsx
- src/organizations/components/DeleteOrgOverlay.tsx
- src/organizations/components/OrgProfileTab/DeletePanel.tsx
closes #4166 
`trackCancellations` got enabled on Nov 23rd 2021 in production. Thus we need to remove this flag.
> chore: remove trackCancellations flag

- cypress/e2e/shared/flows.test.ts
- src/flows/components/AddButtons.tsx
Closes #3777 
Any time of panel could be added anywhere, regardless of whether a panel is dependent upon previous query results or not
Conditionally disabled certain panel type additions so that users are forced into a flow of valid panel insertions based on the previous pipes.
> feat: restrict panel adding based on previous panels

- src/scrapers/components/ScraperList.tsx
Close #4095 
This PR removes the `memoize-one` dependency in scraper list. Passed tests in `cypress/e2e/scrapers.test.ts`
> chore: refactor scraper list to remove memoize-one dependency 

- src/pageLayout/constants/navigationHierarchy.ts
Closes #3447
`Help & Support` item is now added onto the nav, is hidden behind a feature flag `helpBar`.
> feat: add help & support item to nav bar behind feature flag

- cypress/support/commands.ts
This PR removes 1 line of cypress test code that is no longer valid. 
Neither `theme-btn--success` nor `theme-btn` is in ui repo nor clockface repo. Removing this line of test code enables the tests in `labels.test.ts` to pass.
> test: remove dead test code

- cypress/e2e/cloud/pinned.test.ts
- src/flows/components/FlowPage.tsx
- src/flows/components/header/MenuButton.tsx
- src/flows/context/flow.current.tsx
- src/flows/context/flow.list.tsx
- src/flows/context/shared.tsx
- src/flows/context/version.read.tsx
- src/shared/components/TimeZoneDropdown.tsx
This PR separates the flows list context from the current flow context. The rationale behind this move is so that we can keep the list page a dumb list, and make each flow a source of truth in and of itself. This renders a few methods from the list page irrelevant while making sure that the current functionality still exists. 
Since the list is now no longer the source of truth, we should update the API for the getAllNotebooks so restrict the data that's sent so that we don't end up with a potentially bloated list page.
> feat: separate the flow list from the current flow

- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/206
Fixes the form input for string parsing to not add extra backslashes and removes the timestamp option if it's not provided as this was also causing errors with parsing.
> fix: string parsing

- src/timeMachine/components/Vis.tsx
Closes https://github.com/influxdata/ui/issues/3790
Video: 
https://user-images.githubusercontent.com/18511823/160547676-ebc3bf6c-27b1-400c-a5c2-a6e01af9c10b.mov
> fix: call color mapping code after the render cycle in Vis.tsx

- src/writeData/subscriptions/components/CreateSubscriptionPage.scss
- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
- src/writeData/subscriptions/graphics/FormLogo.tsx
We're now using the shared subway component but the styling differs in our design to do with spacing/sizing. This updates the svg size, adds line breaks to our steps and hands in styling only affecting the subscriptions page. 
This makes no changes to the shared component. Also removes unneeded previous styling.
before:
after:
> chore: update menu style for subscriptions

- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/cloud/pinned.test.ts
- cypress/e2e/shared/flows.test.ts
- package.json
- src/flows/components/FlowCard.tsx
- src/flows/components/FlowContextMenu.tsx
- src/flows/components/header/MenuButton.tsx
- src/flows/context/flow.current.tsx
- src/flows/context/flow.list.tsx
- src/flows/context/flow.query.tsx
- src/flows/context/version.read.tsx
- src/pageLayout/components/RenamablePageTitle.tsx
Closes #4258
Closes #4259
Closes #4255
This PR updates the way that notebook updates are handled. Whereas beforehand a deep copy was created and used as a reference to update the flow, this PR ensures that the only data that's being updated should be passed into the current flow so that the update registers the most recent changes and doesn't have stale data.
In addition, this issue resolves a previously unreported bug with our renaming where if a user tabs out of naming a resource, those name changes didn't get registered
> fix: the way notebooks are updated

- package.json
- yarn.lock
Since (some of) the less urgent updates for the dependabot alerts have been lingering due to our dependencies not pulling in updated versions, I decided to explore other options and came across: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/. This should resolve all dependabot alerts except `clean-css`. There are 3 different commits:
* chore: resolve minimist to 1.2.6
* chore: resolve ansi-regex to 4.1.1 (ansi-regex is used in a number of places. The 4.0.0 series should use 4.1.1 though, so use 'yarn why ansi-regex' to pick out what to resolve to the various differently fixed versions). The others use 3.0.1, 5.0.1 and 6.0.1 since those are the ones that have the fix
* chore: resolve nanoid to 3.1.31 (first with the fix)
Each commit consisted of a) updating …
> chore: use resolutions for sec fixes

- src/homepageExperience/components/steps/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/ExecuteQuery.tsx
- src/homepageExperience/containers/HomepagePythonWizard.tsx
Closes https://github.com/influxdata/ui/issues/4275
- Uses docstrings:
- Use the bucket the user selected in the query example text
- Default empty buckets to `my-bucket`, rather than `""`
> chore(firstMile): use docstrings in python examples

- src/dataLoaders/actions/dataLoaders.ts
- src/dataLoaders/components/collectorsWizard/verify/VerifyCollectorsStep.tsx
Closes #4114 
When we are creating a telegraf, we are storing the telegraf config id in the state. So, when we create another telegraf, that id still exists and doesn't get into the `if(!telegrafConfig)` in the action to actually create a new one. Therefore, in the `VerifyCollectorsStep` we have added a call to action `clearDataLoaders` so that when we create new telegraf, the dataloader state is back to original state.
> fix: remove state update for telegraf config id

- src/homepageExperience/components/HomepageIcons.tsx
- src/homepageExperience/containers/HomepageContainer.tsx
- src/homepageExperience/containers/HomepageNodejsWizard.tsx
- src/shared/containers/SetOrg.tsx
- src/shared/containers/index.tsx
Closes #4261
Sets up the basic structure for nodejs.
- adds a route for nodejs, but doesn't connect it to the home page (it's only reachable by modifying the url)
- adds the super sweet nodejs logo and the text Nodejs to the Subway nav
- does _not_ change any of the content (e.g. the `Install Dependencies` page still shows instructions for using python's pip to install influxdb)
> feat(firstMile): add first structure for nodejs

- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
- src/shared/containers/SetOrg.tsx
- src/shared/containers/index.tsx
This is a small refactor - it tweaks the names of the first mile homepage containers just to keep things a little bit easier to follow
> chore(firstMile): tweak naming and structure after adding nodejs

- src/flows/components/ReadOnlyPipeList.tsx
- src/flows/components/VersionPage.tsx
This PR is some general clean-up around notebooks where a shared version of a notebook in presentation mode AND a versioned notebook in presentation mode both had the ability to resize the panel (albeit those changes weren't stored anywhere, and so the operation did nothing but update the state). This caused a weird user expectation on what they could actually do in a notebook in that state when it had the draggable styling attached to it
> fix: update it so that readonly pipelists cant be resized

- src/flows/pipes/QueryBuilder/AddButton.tsx
- src/flows/pipes/QueryBuilder/BucketSelector.tsx
- src/flows/pipes/QueryBuilder/CardList.tsx
- src/flows/pipes/QueryBuilder/context.tsx
- src/flows/pipes/QueryBuilder/index.ts
Got some feedback on the "always select a measurement first" product change made in #4286. measurement selection should mirror bucket selection for a product perspective in that it should clear the query and start over again when you select a new one.
this involved some clean up on bucket selection as well. we used some useEffects to sniff on changes to the data.buckets property to see if the bucket had changed, and thus we should perform some action on the data. Now that we wanted that action to also be connected to a measurement, but only if there was a flag on, the useEffect got a bit... tangled. In order to make the code a bit more straight forward, the useEffect logic for clearing a query when a bucket gets selected got moved to it's own function on the context. once this proved a …
> fix: atomic query builder actions

- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/nodejs/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/nodejs/ExecuteQuery.tsx
- src/homepageExperience/components/steps/nodejs/WriteData.tsx
- src/homepageExperience/components/steps/python/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/python/ExecuteQuery.tsx
- src/homepageExperience/components/steps/python/WriteData.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
A minor cleanup PR
- renames individual props to `OwnProps` to follow our loose conventions for props names
- allow passing of event name into the `Finsh.tsx` component so that each experience can send a unique event upon completion
> chore(firstMile): cleanup - props naming; passing in event name to Finish component

- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/224
If a user didn't provide a timestamp it would not create successfully.
> fix: json timestamp bug

- src/shared/components/dateRangePicker/DatePicker.tsx
- src/shared/components/dateRangePicker/DateRangePicker.test.tsx
Closes https://github.com/influxdata/ui/issues/4335
Connects https://github.com/influxdata/ui/issues/2350
* the `overrideInputState` is not necessary and was causing console log errors so I removed it
* made the default `inputFormat` state of the component to be `YYYY-MM-DD HH:mm:ss`
* added two integration tests
https://user-images.githubusercontent.com/18511823/162237629-349fb188-9c43-4910-beef-f91df0503954.mov
> fix: datepicker time format on input should stay the same when calendar selection is made

- src/flows/pipes/RawFluxEditor/FunctionsList/perFunction/FluxDocsTooltipContent.tsx
- src/style/chronograf.scss
- src/timeMachine/components/dynamicFluxFunctionsToolbar/FluxFunctionsToolbar.scss
- src/timeMachine/components/dynamicFluxFunctionsToolbar/TooltipArguments.tsx
Closes #4342 
- In flux functions tool tip, indicate whether a param is Required or Optional. 
- Required's color should be red. 
Before: 
After:
> feat: add params requirement to tool tip

- cypress/e2e/shared/notificationRules.test.ts
- src/notifications/rules/components/RuleEndpointDropdown.tsx
> fix: notification endpoint Dropdown width to extend all the way

- src/flows/pipes/Visualization/ErrorThresholds/FieldColumnDropdown.tsx
- src/flows/pipes/Visualization/view.tsx
There's an assumption that fields will exist in results from a query. This adds guardrails against that. We should iterate on this so that we can make sure the error threshold work is still applicable after this gets in. For context, check out the conversation around the issue [here](https://influxdata.slack.com/archives/CLHATC50E/p1649348887581009)
> chore: add guardrails in case there arent fields

- package.json
- src/operator/ResourcesAccountType.tsx
- src/operator/ResourcesTable.tsx
- src/operator/context/operator.tsx
This adds a dropdown to the operator UI which will allow for filtering based on account-type. By default, none will be selected al all accounts will be shown. After the operator selects one or many types, the results will be filtered based on the types chosen.
> feat(ecommerce): Add Account Type Dropdown to Operator UI

- src/flows/pipes/RawFluxEditor/FunctionsList/perFunction/FluxDocsTooltipContent.tsx
- src/timeMachine/components/dynamicFluxFunctionsToolbar/TooltipArguments.tsx
Bug fix for #4342 
`param` needs to be reset back to the default "Optional" or else all params become "Required" after the first "Required".
BEFORE:
https://user-images.githubusercontent.com/10736577/162499349-db907123-ac9a-4eef-b033-1ba8abe68dbf.mp4
AFTER:
https://user-images.githubusercontent.com/10736577/162499377-d144c407-8840-46b3-8241-ed6c95ab39fa.mp4
> fix: move param to correct scope

- src/checks/components/CheckCard.tsx
- src/notifications/rules/components/RuleCard.tsx
- src/shared/components/lastRunTaskStatus/LastRunTaskStatus.scss
- src/shared/components/lastRunTaskStatus/LastRunTaskStatus.tsx
- src/tasks/actions/thunks.ts
- src/tasks/components/TaskCard.tsx
- src/tasks/components/TaskRunsCard.tsx
- src/tasks/components/TaskRunsPage.test.tsx
- src/tasks/components/TaskRunsPage.tsx
Helps https://github.com/influxdata/ui/issues/4356
Ever had a failed alert and wanted to know why? Well today's your lucky day! Now you can click the warning symbol and be taken to the associated task's runs page and view the logs!
If the user navigates to the task runs page, we now confirm the task is editable before letting them edit it. We can confirm the task is editable by checking if it exists in the response from the `/tasks?name={task name}` API. Tasks created by Alerts are not returned in this API response. I used the `name` filter because the Task created by an Alert always shares the same name as the Alert. From this list, I set `isTaskEditable=true` iff I can find a task in the response with the matching task ID from the Alert.
All of this is behind flag `navToTasksRuns` …
> fix(alerts): navigate to task runs

- cypress/e2e/shared/explorer.test.ts
- cypress/e2e/shared/legends.test.ts
- cypress/e2e/shared/queryBuilder.test.ts
- src/dataExplorer/components/SaveAsNotebookForm.tsx
- src/dataExplorer/components/SaveAsOverlay.tsx
This work stems from frustration trying to debug the differences between the way data explorer handles the gauge and histogram visualizations vs notebooks. I figured if I could save the data correctly, then things should work as a like-for-like replacement.
> feat: add save as notebook option from data explorer

- src/flows/components/FlowCard.tsx
- src/flows/components/header/index.tsx
- src/flows/context/flow.list.tsx
Closes #4360 
This PR closes two bugs surrounding renaming a notebook. The first, when a user renaming a notebook in the list page wouldn't have their changes reflected immediately since the state wasn't setting correctly based on the user's input. The second one being that if a user renamed a notebook from the notebook view & immediately went off to perform another update (like updating a flux script in a panel), then the user's secondary patch (with an out of sync notebook name) would overwrite the original changes.
> fix: naming issues for notebooks referencing stale state

- src/flows/pipes/Visualization/ErrorThresholds/ErrorThresholds.tsx
Closes #4365
Offlined with @garylfowler about the best approach for this feature at this stage w/r/t to the linked. The crux of the issue can be boiled down to two separate issues:
1. Do we want to broaden setting error thresholds when the user doesn’t have a field (meaning, support measurements as an error threshold), or do we want to maintain the current dynamic of a field being required for setting a threshold. For example, I want to set an alert for when the field data for the measurement doesn’t have a value returned (meaning, that some data might not be coming through)
2. If i have an error threshold set for a field, and I update the original query so now that field is no longer being returned, do I automatically want to remove the existing error threshold, or do I want to keep it …
> chore: disable the add button if there is nothing to add

- cypress/e2e/shared/dashboardsView.test.ts
- src/shared/components/cells/CellContext.tsx
This feature has been enabled for quite some time in the UI. It's time to rip out the feature flag now that we're certain that this is a feature we want to maintain
> chore: remove cloneToOtherBoards feature flag

- src/flows/pipes/RawFluxEditor/view.tsx
- src/timeMachine/components/FluxToolbar.tsx
- src/timeMachine/components/TimeMachineFluxEditor.tsx
- src/timeMachine/components/dynamicFluxFunctionsToolbar/FluxFunctionsToolbar.tsx
Closes #4367 
- Fixes an obscure bug when a user manually toggles the `fluxDynamicDocs` feature flag causes a memory leak
- Adds a check for CLOUD since this feature is only available for CLOUD
BEFORE:
AFTER:
https://user-images.githubusercontent.com/10736577/162855780-24d06836-9930-4399-9f82-03ffaa1854b8.mp4
> fix: add CLOUD check and cleanup function to DynamicFluxFunctionsToolbar to prevent memory leak

- src/overlays/components/OverlayController.tsx
- src/overlays/components/index.tsx
- src/overlays/reducers/overlays.ts
- src/pageLayout/containers/TreeNav.tsx
- src/support/components/FreeAccountSupportOverlay.tsx
- src/support/components/PayGSupportOverlay.tsx
Closes #3450 
- adds `PayGSupportOverlay` and `FreeAccountOverlay` to overlay controller file. So when `Contact Support` is clicked, depending on the account type, we direct user to the correct support overlay.
> feat(HelpBar): Display support overlays for payg and free accounts 

- src/homepageExperience/containers/HomepageContainer.tsx
Somehow I keep messing up the go lang link. 
Tested thoroughly this time. 
https://user-images.githubusercontent.com/18511823/163041107-67db3901-e129-4850-8c5f-65c7d9efd353.mov
> fix: go lang link for first mile

- src/homepageExperience/components/steps/python/InitalizeClient.tsx
Closes https://github.com/influxdata/ui/issues/4402
Need to update the code snippet so that it that works. The previous one is missing or has incorrect import statements.
Figma says the code should be : 
After fix the code snippet says this (identical to the latest figma) :
> fix: InitalizeClient code snippet for python

- cypress/e2e/shared/dashboardsVariables.test.ts
- cypress/e2e/shared/dashboardsView.test.ts
Splits `dashboardsView.test.ts` into two files:
- `dashboardsView.test.ts`
- `dashboardsVariables.test.ts`
Cleans up unnecessary code.
No functional changes to any tests.
> test: split dashboardsView into two files

- src/shared/copy/notifications/categories/subscriptions.ts
- src/writeData/subscriptions/components/SubscriptionsLanding.tsx
- src/writeData/subscriptions/context/subscription.list.tsx
Closes https://github.com/influxdata/data-acquisition/issues/261
If errors are thrown from GET or DELETE endpoints, we should show a notification and disable the loader. Also moves the loading spinner inside the tabs, rather than the whole page.
> chore(sub): handle errors from GET and DELETE endpoints

- src/support/components/PayGSupportOverlay.tsx
Closes #3452 
pr adds the following to the payg support overlay
- A status page link is displayed at the top of the modal with verbiage
- Severity dropdown, with description values in dropdown (with integers assigned behind those values)
- A Tooltip is displayed next to severity dropdown to provide a link to the support policy website for definitions of severity.
- Description, a text field with a limit of 2500 characters.
https://user-images.githubusercontent.com/66275100/163423777-bf7d3acf-20c5-412e-8db9-bbef534abce2.mov
> feat(HelpBar): add content to payg support overlay

- src/flows/components/header/Submit.tsx
- src/flows/context/flow.query.tsx
Closes #4366 
This PR fixed the bug that the "Run" button sometimes got disabled when a flux script is valid.
https://user-images.githubusercontent.com/14298407/163861127-3fb9f433-2b69-4393-9a43-4a2bf6dbd857.mov
https://user-images.githubusercontent.com/14298407/163861305-df21c127-7420-4e63-83ea-1a6346a444ec.mov
> fix(notebook): fix run button disable/enable

- src/writeData/subscriptions/utils/form.ts
Adds optional chaining and fallbacks for properties that are not required.
When the server response is not what you expect, console errors begin to appear due to undefined properties that are assumed to be present but are defined in the interface as optional. This can be reproduced by trying to save again after a non-200 response.
The above happens because when the form fails to save, certain fields have already been sanitized or deleted. Attempting to save again will try to sanitize properties that are nested in non-existent fields.
> fix: add checks and fallbacks for optional properties

- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/shared/checks.test.ts
- cypress/e2e/shared/dashboardsIndex.test.ts
- cypress/e2e/shared/dashboardsView.test.ts
- cypress/e2e/shared/flows.test.ts
- cypress/e2e/shared/notificationRules.test.ts
- cypress/e2e/shared/tasks.test.ts
- cypress/e2e/shared/telegrafs.test.ts
- src/authorizations/components/TokenRow.tsx
- src/checks/actions/thunks.ts
- src/dashboards/actions/thunks.ts
- src/flows/components/VersionSidebar.tsx
- src/flows/context/flow.current.tsx
- src/flows/context/flow.list.tsx
- src/notifications/endpoints/actions/thunks.ts
- src/notifications/rules/actions/thunks.ts
- src/shared/components/cells/CellCloneOverlay.tsx
- src/tasks/actions/thunks.ts
- src/telegrafs/components/CollectorCard.tsx
- src/utils/naming.test.ts
- src/utils/naming.ts
Closes #4241
Naming a cloned resource was a pretty resource intensive operation that typically involved getting ALL of the resources, flat mapping them to get the name, then using regex to determine an incremented clone value for the new name.
Simplify the process so that cloning assigns a UTC-based time appended to the clone so that the naming convention is `name (cloned at month-day-year:hour:minute:second)`. For example:
`flow (cloned at 04-20-2022:06:17:32)`
- Updates the `naming` utility to `setCloneName` that trims the name parameter and appends a ` (cloned at ...`) based on the current UTC date
- updates the tests to account for these changes
The `setCloneName` takes in a second parameter to make testing dates easier and predictable
> feat: update name cloning conventions and update tests

- package.json
- src/types/operator.ts
Updates Operator Organization type names to avoid conflicts with multi org changes.
Corresponding openapi changes can be found here: https://github.com/influxdata/openapi/commit/4e27f5d5e552e962164d1455d5249ec2d6d0588b
Updates Organization to OperatorOrganization
Updated Organizations to OperatorOrganizations
OperatorOrganization will continue to be aliased as OperatorOrg
OperatorOrganizations will now be aliased as OperatorOrgs
The `Organizations` type was not used anywhere so it did not require any updates (Only `OperatorOrg[]` was used).
Since `Organization` was already aliased, we only needed to update the `type` file.
Co-authored-by: Grace Spletzer <gspletzer@influxdata.com>
Part of https://github.com/influxdata/quartz/issues/6138
> chore: Update Operator Types Names

- src/alerting/reducers/alertBuilder.test.ts
- src/alerting/reducers/alertBuilder.ts
- src/checks/utils/index.ts
Closes #4348 
This PR fixed a bug in alert description where the description of an alert got erased after the alert was edited.
https://user-images.githubusercontent.com/14298407/164305163-96ca83fa-a927-45d7-a811-fc0851f6c074.mov
https://user-images.githubusercontent.com/14298407/164304776-ebd0df5e-caf1-439d-83c7-59cf41017a23.mov
> fix(alert): keep alert description saved after an alert is edited

- src/homepageExperience/components/steps/Overview.tsx
Connects https://github.com/influxdata/ui/issues/4372
Waiting on design to add the videos for the finish page.
> feat: add time series video to the overview page

- src/cloud/components/RateLimitAlert.tsx
- src/cloud/components/RateLimitAlertContent.tsx
- src/shared/components/cloud/CloudOnly.scss
- src/shared/components/notifications/Notifications.tsx
- src/shared/copy/notifications/categories/limits.ts
Closes #4310 
Adds the messaging for the $250 credit experiment, including minor styling updates where necessary.
> feat: add messaging for the $250 credit experiment

- package.json
- src/shared/utils/vis.ts
- src/visualization/types/Graph/options.tsx
Closes #2651 
pr adds two more interpolation options to customize graphs. 
Before Change: 
https://user-images.githubusercontent.com/66275100/164498698-70ac24c2-294b-457d-8418-5822fcbc3f49.mov
After Change: 
https://user-images.githubusercontent.com/66275100/164498877-ab63ba09-1a09-4bed-bc4e-34c96babd9d5.mov
> feat: expose stepBefore and stepAfter interpolation options

- package.json
- src/checks/components/CheckCard.tsx
- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/flows/components/FlowCard.tsx
- src/tasks/components/TaskCard.tsx
- src/utils/crossPlatform.test.ts
- src/utils/crossPlatform.ts
- yarn.lock
Closes https://github.com/influxdata/clockface/issues/723
Previously, we only recognized the `metaKey` being pressed when handling click events. This maps to `command` on MacOS, which allows links to be opened in new tabs. This doesn't work for Windows or Linux though. This change recognizes the modifier keys (ctrl+click and clicking with the middle-mouse button on Windows and Linux) for those platforms and modifies existing `metaKey` handlers to work cross platform. It also adds the proper browser context menu for links, by passing in an `href` argument.
I tested this on my personal Windows PC and got Will Cooke to test it on his Linux machine.
- Adds a function `shouldOpenLinkInNewTab` which abstracts checking the current platform and key combination on click events
- Makes existing …
> feat: make opening links with modifiers work cross-platform

- docker/Dockerfile.chronograf.prod
- webpack.common.ts
- webpack.vendor.ts
Closes #4448 
Do not override publicPath for the webpack-plugin-monaco-editor. Keep the same as the project route.
.
**Visual evidence:**
Deployed remocal with prod build (ui-acceptance quay image).
**See for yourself:**
Currently deployed remocal cluster is using the commit with the prod ui-acceptance image.
https://twodotoh-dev-denisewiedl20220405130506.remocal.influxdev.co
> fix(4448): editor service worker loads in prod

- package.json
- src/accounts/context/userAccount.tsx
Updates `Account` to `UserAccount` in accordance with the openapi change made here: https://github.com/influxdata/openapi/commit/b983e6ecc75f9b9852401e5585f2706890b10bb3
`Account` was already being aliased as `UserAccount` so the only change needed was in the type.
The plural `Accounts` was not being used so no change was needed to reflect the openapi rename from `Accounts` to `UserAccounts`. (UI just uses an array of `UserAccount`).
Part of quartz #6138 changes for multi org.
> Update Account to UserAccount

- src/cloud/components/RateLimitAlertContent.tsx
- src/shared/components/CloudUpgradeButton.tsx
- src/shared/components/cloud/CloudOnly.scss
Closes #4309 
Adds "Get $250 free credit" to the Upgrade Now button in most, but not all, contexts.
> feat: add $250 credit message to upgrade button

- src/shared/contexts/query.tsx
Closes #4463 
See ticket details, for how tracked down this bug.
> fix(4463): millisecond discrepancy was causing wrong Duration Literal calculation

- src/homepageExperience/components/FeedbackBar.tsx
- src/homepageExperience/components/steps/CreateToken.tsx
- src/homepageExperience/containers/GoWizard.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
Closes https://github.com/influxdata/ui/issues/4457
Closes https://github.com/influxdata/ui/issues/4474
* user can only select feedback once
* token is only created once per session
https://user-images.githubusercontent.com/18511823/165136211-a1e8f64d-37d1-4671-95d2-86054b80daec.mov
> fix(firstMile): create token once per session; allow feedback selection once

- src/visualization/utils/useStaticLegend.ts
Closes #4451 
problem pr fixes: function inside `useStaticLegend` component gets executed (unnecessarily) each time a render happens. Causing a bad setState error in the console. 
solution: wrap function in a useEffect hook so state only gets updated when one of the three values in dependency array change. 
on the second rendering (when `XYPlot` isn't rendered yet), `updateStaticLegends` gets executed one too many times.
On each render, the three values in the dependency array, `[isViewingVisOptions, show, heightRatioget]` get evaluated and in turn cause `updateStaticLegends` to get executed. This execution happens during a particular render where `XYPlot` was not already mounted on the DOM. This here is why pr executed this inside a `useEffect` so the only way function gets called is if …
> fix(Bug): remove unnecesary state setting to stop multiple re-renderings

- docker/Dockerfile.chronograf.prod
Currently Dockerfile.chronograf.prod specifies node:lts-alpine3.12, but
according to https://hub.docker.com/_/node this is no longer supported.
Instead of hard-coding an alpine version, simply specify lts-alpine
(which currently is the same as lts-alpine3.15 (16-alpine3.15).
Successfully built an image using:
$ docker build -f ./docker/Dockerfile.chronograf.prod .
I have not tested this beyond building the image.
> chore(Dockerfile.chronograf.prod): use node:lts-alpine

- src/homepageExperience/components/steps/python/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/python/ExecuteQuery.tsx
- src/homepageExperience/components/steps/python/InitalizeClient.tsx
- src/homepageExperience/components/steps/python/WriteData.tsx
Closes https://github.com/influxdata/ui/issues/4458
adds new lines to the end of all the python scripts in the firstmile. this makes it work well with the python interpreter.
> fix(firstMile): newlines at the end for python code snippets

- src/homepageExperience/components/steps/go/WriteData.tsx
Closes #4489
What it says on the tin - adds one second sleep in the golang wizard so that the points being written are one second apart
> chore(firstMile): golang wizard - add 1 second sleep between point writes

- cypress/e2e/shared/flowsAlerts.test.ts
- src/flows/context/flow.current.tsx
- src/flows/pipes/Notification/ExportTask.tsx
- src/flows/pipes/Notification/Measurement.tsx
- src/flows/pipes/Notification/Threshold.tsx
- src/flows/pipes/Notification/endpoints/AWS/index.ts
- src/flows/pipes/Notification/endpoints/HTTP/index.ts
- src/flows/pipes/Notification/endpoints/Mailgun/index.ts
- src/flows/pipes/Notification/endpoints/Mailjet/index.ts
- src/flows/pipes/Notification/endpoints/PagerDuty/index.ts
- src/flows/pipes/Notification/endpoints/SendGrid/index.ts
- src/flows/pipes/Notification/endpoints/Slack/index.ts
- src/flows/pipes/Notification/endpoints/Telegram/index.ts
- src/flows/pipes/Notification/endpoints/Zenoss/index.ts
- src/flows/pipes/Notification/index.ts
- src/flows/pipes/Notification/readOnly.tsx
- src/flows/pipes/Notification/view.tsx
- src/flows/pipes/Schedule/ExportTaskButton.tsx
- src/flows/pipes/Visualization/threshold.ts
Closes #3707 
Closes #4021 
Closes #4479
Also fixed one other found bug.
* bug 4021. The addition of multiple thresholds, resulted in invalid flux being exported to a task.
* flux was writing `(r) => r["a"] > 0 and (r) => r["a"] = 0` . This is an incorrect lambda.
* Bug found. We were setting the default `threshold.field` to a string value `"_value"`.
* this was occurring even without a user selecting a field.
* <img width="300" alt="Screen Shot 2022-03-09 at 7 04 58 PM" src="https://user-images.githubusercontent.com/10232835/157586533-f6521a02-982d-4ab8-9c59-9c4ee546f9b6.png">
* produced flux with `r["_value]`
* bug 3707: alerts are being received as spam
* the filter/threshold-predicate was being given to the monitor.check() method, but never applied as a transformation in the current …
> fix(3707/4021/4479): notebooks alerts multiple predicates, don't hold pipe threshold state after pipe deletion, and have flux not spam the endpoint.

- src/flows/pipes/QueryBuilder/CardList.tsx
- src/flows/pipes/QueryBuilder/context.tsx
- src/shared/contexts/query.tsx
Closes #4282
There's currently an issue where whenever a user toggles between buckets / measurements / fields / tags in the query builder, a query will fire off and continue processing even when a user toggles away from that previously selected value. 
This PR aims to resolve this by canceling existing pending queries when they are toggled away from. This is achieved by:
1. Prior to returning the promised fromFlux result in the query context, we set the `cancel` property onto it (since this was previously being wiped away in the promise chain sequence)
2. We set that promise (with the cancel property) onto the query builder context state for the specific key / value that's being loaded so that we have access to it in the event that we need to cancel the query
3. If the CardList unmounts …
> feat: cancel queries in query builder when toggling between values

- src/flows/components/VersionSidebar.tsx
Cancel all in-flight queries when switching notebooks versions
**My Query Time**
**Working Query Cancellation**
> chore: cancel all in-flight queries when switching versions

- package.json
Per https://nodejs.org/en/about/releases/, nodejs v12 is going EOL on
2022-04-30. package.json currently specifies >=12.13.0, so update it to
14.17.0 (14 is also an LTS and supported until April 2023).
Ideally we would update this to the latest LTS (16.14.2), but images
used in CI/CD generated from this repo's docker/Dockerfile.cypress
currently specify quay.io/influxdb/cypress-slim:9.5.2-included which
uses:
```
FROM cypress/base:14.17.0 AS original
```
When https://github.com/influxdata/cypress-slim/blob/main/Dockerfile#L2
is updated to use node 16, then we can update the node engine in this
repo's package.json accordingly.
'yarn clean && yarn build' succeeds. I have not tested this beyond
these yarn commands.
> chore(package.json): use node engine 14.17.0

- src/homepageExperience/components/DataListening.tsx
Closes https://github.com/influxdata/ui/issues/4491
When we changed bucket, i.e. component was updated, we didn't clear out the old timer that was running, this was causing the component to send extra queries even after data was found in the bucket. 
After fix: 
https://user-images.githubusercontent.com/18511823/165746914-6ea647a6-1e01-4c52-8282-1ee04e6398aa.mov
> fix(firstMile): data listening component clear old interval id's when bucket changed

- src/homepageExperience/containers/HomepageContainer.tsx
To keep us from holding up the prod release while we diagnose what's causing the issue of writing to buckets from the nodejs client library
> chore(firstMile): point nodejs homepage card to library page, not wizard

- src/writeData/subscriptions/components/BrokerFormContent.tsx
- src/writeData/subscriptions/components/JsonParsingForm.tsx
- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/components/SubscriptionDetailsPage.scss
- src/writeData/subscriptions/context/subscription.create.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/281
Helps with https://github.com/influxdata/data-acquisition/issues/269
- Copy change
- Makes timestamps editable
- Error state text fix
- Move handling of timestamps into nifid
- Makes sure if you edit json inputs they are sanitized with prepended $.
> fix: subscriptions json bugs/ clean up

- src/homepageExperience/components/FeedbackBar.tsx
- src/index.tsx
Closes #4370
- Adds a call to `userpilot.trigger` if it exists on `window` when the user clicks on the feedback icons, but only if they haven't clicked on it in this firstMile session
> chore(firstMile): add userpilot trigger call on feedback

- src/checks/components/CheckHistoryVisualization.tsx
- src/shared/components/TimeSeries.tsx
Closes #4517 
Inside `CheckHistoryVisualization` component, we are attempting to update a state  (statuses) before the component `CheckProvider` mounts. I believe this is what’s causing the bad state error in the console. I don’t understand the reason behind the need to update statuses inside `CheckHistoryVisualization`, when it can be updated in the parent component (TimeSeries). 
In my pr, I passed setState `updateStatuses` as a prop to `TimeSeries`. Once this line `statuses = await this.pendingCheckStatuses.promise` is resolved, inside componentDidUpdate(), we can set the state to the new value.
> fix: update statuses after promise resolves 

- src/homepageExperience/components/steps/nodejs/WriteData.tsx
- src/homepageExperience/containers/HomepageContainer.tsx
Closes #4485
When writing to a measurement with an existing name, the types have to match. The Python and Go libraries both wrote integers, but I copied an example for nodejs that wrote floats. Since all the examples write to `measurement1`, python and go worked, but nodejs would fail. Changing the write example for nodejs to create an `intField` instead of `floatField` allowed me to write to a bucket that would previously fail.
I tested this with a new bucket and all the wizards. They all wrote to it correctly.
> fix(firstMile): makes the nodejs examples write ints instead of floats

- src/flows/pipes/RawFluxEditor/view.tsx
- src/timeMachine/components/TimeMachineFluxEditor.tsx
- src/timeMachine/utils/insertFunction.ts
Closes #4525 
For nested flux packages, the import statement needs to use the path property instead of func.package. One way to check if a package is nested is by checking out the path property. If path contains `/` sign, it means it's nested. If so, pr re-assigns the importStatement variable to use the path value instead of package. 
Before fix: 
https://user-images.githubusercontent.com/66275100/165997033-8ccc5ca6-95ba-4f85-b282-6ea649d4e4fa.mov
After fix: 
https://user-images.githubusercontent.com/66275100/165997250-0f9a5b66-b098-4c92-8ee3-890002ff0797.mov
> fix(bug): use path property to import nested package

- src/billing/components/BillingContactDisplay.tsx
- src/billing/components/Checkout/BillingContactForm.tsx
Currently, Quartz updated the billing contact's email address to the current user's email every time there is a change to the billing information. The Quartz API will be updated to receive an Email Address an a parameter in the `handleConfirmContactInfo` request.
**NOTE:** It looks like there were a lot of changes to this, but the main change is that I added the field for email. Additionally, I raised the `<Form>` element higher in the dom so that it would contain the submit `<Button>`. I did this so that we could have email validation for the new `type={InputType.Email}` `<FormInput>`.
Image of the contact information display:
Image of the contact information update
> feat(ecommerce): Add Email to Update Billing Contact

- src/flows/pipes/RawFluxEditor/view.tsx
- src/shared/utils/fluxExample.ts
- src/timeMachine/utils/insertFunction.ts
Closes #4534 
The `universe` package is loaded by default and does not require an import statement or functions in that package to be prepended with universe. PR removes import statements for all universe packages and removes `universe` prefix from the injected flux function.
Before Fix: 
https://user-images.githubusercontent.com/66275100/167665421-88edc5b8-9f26-4626-89d6-9ea119605012.mov
After Fix:
https://user-images.githubusercontent.com/66275100/167665161-869f6471-9815-4cab-837a-7f3d3d3af94d.mov
> fix: remove import statement for universe pkg

- src/billing/components/PayAsYouGo/TermsCancellationOverlay.tsx
We want to remove this option until bulk export is available.
This is in response to [EAR #3232](https://github.com/influxdata/EAR/issues/3232)
> chore: Remove list item for requesting archival of data from support

- cypress/e2e/cloud/explorer.test.ts
- src/flows/pipes/RawFluxEditor/view.tsx
- src/timeMachine/components/TimeMachineFluxEditor.tsx
Closes #4535 
In both current and older flux panel UI, all flux functions get injected in the editor with a pipe-forward operator `|>`. 
This isn't correct. Not all functions require `|>`. Pr leverages the `fluxType` property for each flux function to determine whether pipe-forward sign is needed. All functions that require this operator contain a pipe-receive operator `<-` in the fluxType property. 
Before: 
https://user-images.githubusercontent.com/66275100/167695593-fad8c98e-ab12-4971-8428-ac8b2d4a269f.mov
After: 
https://user-images.githubusercontent.com/66275100/167695446-a3ac26e0-e7e1-408e-b8cf-be18115584a5.mov
> feat: inject pipe-forward operator only when necessary 

- src/flows/pipes/RawFluxEditor/FunctionsList/DynamicFunctionsList.tsx
- src/timeMachine/components/dynamicFluxFunctionsToolbar/FluxFunctionsToolbar.tsx
Closes #4524 
UI's flux panel isn't clear on how users can search for flux functions. Search widget only filters functions when given package name OR function name. PR clears this up by adding a more descriptive placeholder _Filter by Package or Function_
Data Explorer: 
Notebooks:
> chore: update flux search panel placeholder

- src/pageLayout/containers/TreeNav.tsx
Closes #4557 
PR uncomments Contact Support and Feedback code for phase 1 release. 
This is only temporary, as we will need both nav items once backend work is complete.
>  chore: hide support and feedback code for Help panel phase 1 release

- package.json
- src/shared/containers/GetOrganizations.tsx
Closes #4464 
- uses the updated openapi definition for `Me` which was updated by https://github.com/influxdata/openapi/pull/318
- adds the `accountCreatedAt` property to `window.dataLayer`
> feat: add accountCreatedAt to dataLayer

- package.json
- src/me/components/PinnedItems.tsx
- src/onboarding/components/HelperText.tsx
- src/onboarding/containers/LoginPage.tsx
- yarn.lock
Closes #4567
Upgrades to version `4.0.1` of clockface, which has font-face changes from [`4.0.0`](https://github.com/influxdata/clockface/releases/tag/v4.0.0) and the Subway Nav changes from [`4.0.1`](https://github.com/influxdata/clockface/releases/tag/v4.0.1)
> feat: upgrade clockface from 3.12.0 => 4.0.1

- src/billing/components/Free/PAYGConversion.tsx
This should have been included in https://github.com/influxdata/ui/pull/4551
When the feature is off, we still want to use `Intl.NumberFormat` to display large numbers that use grouping.
> chore: use Intl.NumberFormat

- src/pageLayout/containers/TreeNav.tsx
fix for Help Bar feature crashing UI when user signs out and signs in again. 
`useEffect` hook in `TreeNav` component targets the help and support nav element and adjusts the style depending on the mode of the nav bar.
The purpose behind this code is to keep the sub nav items rendering on the side whether the nav is expanded or collapsed 
Error we see in the console in prod reads `cannot read properties of undefined`. This error occurs only when user switches orgs. Pr introduces a fix -  an `if` statement inside hook that returns early if targeted element doesn't exist.
> fix(HelpBar): return early if helpBarMenu doesn't yet exist

- src/resources/selectors/index.ts
- src/shared/containers/GetOrganizations.tsx
Follow-up to #4464 
Wraps the properties for the Credit 250 Experiment under an `identity` object before pushing to the `dataLayer`
> fix: wrap experiment properties under identity object

- src/resources/selectors/index.ts
- src/shared/containers/GetOrganizations.tsx
Part of #4464 
Adds an error state to `OrgsState` when `resources.orgs` cannot be found. Initially, `OrgsState` is set by the reducer, which should not use this fallback unless `resources.orgs` was modified by something else.
> fix: add fallback OrgsState for getAllOrgs

- cypress/e2e/shared/explorerVisualizations.test.ts
- src/flows/context/editor.tsx
- src/flows/pipes/RawFluxEditor/view.tsx
- src/shared/utils/fluxExample.test.ts
- src/shared/utils/fluxExample.ts
- src/shared/utils/fluxFunctions.ts
- src/timeMachine/components/TimeMachineFluxEditor.tsx
- src/timeMachine/utils/insertFunction.ts
Temporary fix for https://github.com/influxdata/flux/issues/4720
* Pro: have dynamic list of available flux functions, served from the backend.
* Con: we lost the hardcoded examples for flux functions.
* suggestions from LSP are not sufficient. 
* Hardcode the top 20 flux functions, with an example.
* future plans are to have the backend (or LSP) provide data for examples. But not yet ready. 
* Make sure the example insertion considers the cursor position, versus the type of insertion (e.g. on the same line, or another line).
* This just meant using existing code for `calcInjectionPosition()`.
* knows when the flux function should be injected on the same line, vs different line. Then does the math.
* For different line (on own line), injects based on where cursor is in line --> will …
> fix(flux-4720): temporary fix to hardcode top20 examples, plus add cursor awarenss in function injection

- cypress/e2e/cloud/flows.test.ts
- src/checks/reducers/checks.test.ts
- src/checks/reducers/index.ts
- src/flows/pipes/QueryBuilder/context.tsx
- src/timeMachine/apis/queryBuilder.ts
- src/timeMachine/selectors/index.ts
- src/variables/utils/ValueFetcher.ts
Closes #4289 
This PR does three things:
- updates the tagKeys query for the query builder in data explorer to match the work done in notebook
- updates the previous `queryBuilderUseMetadataCaching` to `newQueryBuilder` since the two features go hand in hand
- updates ValueFetcher and the timeMachine/selector to use the fastFromFlux behind a feature flag
> feat: set the function up everywhere

- src/homepageExperience/containers/HomepageContainer.tsx
Closes  #4584
Eventing in onboarding was set up for users clicking the python wizard icon, but not for users clicking the node wizard or go wizard icons.
Fix adds eventing, and changes function name to be more semantic: e.g., `logPythonWizardClick` instead of `logPythonEvent`
> fix: add missing events for node.js wizard and go wizard

- src/checkout/CheckoutForm.tsx
- src/checkout/context/checkout.tsx
- src/usage/context/usage.test.ts
- src/usage/context/usage.tsx
- src/utils/datetime/constants.ts
Closes #4385 
Also part of quartz 6164
- Updates the Usage Panel to work with the Credit 250 Experiment
> fix: update usage panel to use Credit 250 experiment

- src/cloud/utils/reporting.ts
Part of #4313 
Fixes the `a.trim is not a function` by guaranteeing the value is a string before calling `.trim()`
> fix: force value to string before calling trim

- src/homepageExperience/containers/HomepageContainer.tsx
Closes #4618
Eventing was present for python, node, go, and 'more' buttons on firstMile, but not the CLI or telegraf buttons.
Fix adds eventing for these buttons (below image has streamEvents turned on to illustrate).
Note that the click handlers all have identical functionality with different event names. Another approach would be to combine them into one, and pass the event (firstMile.nameOfEvent.clicked) as an argument to a single handler when the function is invoked in each `<Link />`. On balance, I'd propose keeping separate event handlers, since this is a little easier to debug if we have to add or change event names.
> fix: add missing eventing for CLI and telegraf buttons

- cypress/e2e/shared/deepLinks.test.ts
Closes https://github.com/influxdata/ui/issues/4604
Adds the e2e tests for first mile deep links.
> test: deeplink tests for firstmile

- src/shared/containers/GetOrganizations.tsx
- src/shared/utils/dateTimeUtils.test.ts
- src/shared/utils/dateTimeUtils.ts
Part of #4313 
Change `account_created_at` to epoch time, because it is easier to manage as a number in the Google Optimize experiment dashboard.
> feat: convert account_created_at to epoch time

- src/timeMachine/apis/queryBuilder.ts
This is just me cleaning up a sloppy copy job on my part and not bothering to look at the root of what the existing query was doing. The solution here was a few things:
1. not prepending a `(r) => ` onto the predicate since the tagFilters already does that through a function
2. Changing the `tagKeys` to `tagValues` for the values 🤦🏽 
3. Adding in the selected tag `key` for the tagValues
Visual proof here is that the query doesn't error out:
> fix: queryBuilder tag key & value gets

- src/timeMachine/components/TagSelector.tsx
This PR addresses inconsistencies with the loading state for the newQueryBuilder forced measurement selector. Whereas previously the filter / group field was available while the measurements were loading, this implementation aligns more closely with the product intent by limiting the user manipulation of queries within the query builder experience by removing that option for users. Effectively this looks like:
> chore: fix the loading state for the query builder

- package.json
- src/pageLayout/containers/TreeNav.scss
- src/pageLayout/containers/TreeNav.tsx
- yarn.lock
Closes #
Pr introduces the following changes 
- moves `Help & Support` nav item to the bottom of the nav bar. 
- adjusts the position of popover modal 
Before 
After
> feat: Move help bar nav item to bottom of nav bar

- src/pageLayout/containers/TreeNav.tsx
PR updates Help Bar's FAQ link for InfluxDB Cloud and OSS 2.2+. The previous link directed users to InfluxDB 1.8 FAQ therefore needed changing
> chore: update help bar faq link

- src/cloud/components/AssetLimitAlert.tsx
- src/dashboards/components/dashboard_index/DashboardCards.tsx
- src/dashboards/components/dashboard_index/DashboardCardsPaginated.tsx
Closes #4596 
Sets the resource card with the asset limit alert with the correct height when the card is the first one in the row
> fix: use standard dashboard card height when alert is first in a row

- src/homepageExperience/components/steps/Overview.tsx
- src/homepageExperience/containers/GoWizard.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
Closes #4623
Eventing was not present for the tutorial 'what is time series' video in the Node, Go, and Python wizards. 
`<iframe>` can't accept onClick or similar events [because iframe represents a new nested browsing context](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). This fix is adapted from solution found [here](https://github.com/springload/react-iframe-click), which infers the click from an onBlur event in `window` when the iframe is the then-active DOM element.
This fix fires the event on every click where the user changes context to the `<iframe>`. If this behavior is only desired on first click (e.g., shouldn't refire if user pauses, clicks out, then later clicks back in), we should remove the event listener after the first fire. …
> fix: Add missing eventing to firstMile video

- src/buckets/actions/thunks.ts
Closes #4592 
Re-fetch the bucket labels when updating the bucket retention, because the api does not include labels on `PATCH` operation to buckets. It requires a separate call to get the bucket labels.
https://user-images.githubusercontent.com/10736577/169623950-c090aed0-9362-4437-8ada-556fdd3b9e35.mp4
> fix: re-fetch bucket labels when updating bucket retention

- src/support/components/PayGSupportOverlay.tsx
Adding a subject field in payG support overlay because salesforce needs it.
> feat: added a subject section in payG support overlay

- src/buckets/components/CreateBucketButton.tsx
- src/buckets/components/createBucketForm/CreateBucketForm.tsx
- src/buckets/components/createBucketForm/CreateBucketOverlay.tsx
- src/writeData/components/WriteDataHelperBuckets.tsx
Closes https://github.com/influxdata/ui/issues/4455
I use callbacks to send the bucket name up until the WriteData command so that after creation, the bucket can be auto-selected.
https://user-images.githubusercontent.com/18511823/169996528-a568098d-f54a-4859-8abe-29d6d3722add.mov
> feat: update bucket in bucket selector after Create Bucket button is used

- cypress/e2e/shared/tasks.test.ts
- src/tasks/reducers/index.ts
Unblock CI pipeline.
Part of #4673 
Does not fix all of the shared state issues in the Tasks part of the application. But hits at single the single biggest culprit.
* We are using a global store to fill out the form.
* The form gets filled out, depending on which task cypress test, as either 'Task' or '🦄ask.
* When the tests failed locally, they did it when it was expecting 'Task' but got '🦄ask'.
* Usually I try to keep form state as local state (react hooks or stateful components), and keep it out of any global store (e.g. redux). Because it can easily cause shared state issues.
* The specific error here was a mutable default object.
> test: debug tasks test, to unblock CI pipeline

- src/dataExplorer/components/BucketSelector.tsx
- src/dataExplorer/components/FieldSelector.tsx
- src/dataExplorer/components/MeasurementSelector.tsx
- src/dataExplorer/components/SelectorTitle.tsx
- src/dataExplorer/components/TagSelector.tsx
Closes #4679 
This PR adds content into the tooltips in schema browser to explain what bucket, measurement, fields, and tag keys are.
> feat: add tooptip content to schema browser

- src/support/components/ContactSupport.scss
- src/support/components/PayGSupportOverlay.tsx
PR adjusts the margin of the question tooltip to properly align it with the severity field. 
And moves the status page text inside the overlay body. 
Before 
After
> chore: correctly align question mark tooltip in help bar 

- src/pageLayout/containers/TreeNav.tsx
- src/support/components/FeedbackQuestionsOverlay.tsx
- src/support/components/PayGSupportOverlay.tsx
Closes #4589 
Pr adds events for the following scenarios 
- When support request is submitted from PAYG user 
- When feedback and question is submitted 
- when help bar docs are opened (including where the user was in the UI when seeking help)
> feat: add eventing for helpbar

- .circleci/config.yml
Connects https://github.com/influxdata/idpe/issues/14626
> chore: remove now unneeded auth block from circleci config

- src/support/components/FreeAccountSupportOverlay.tsx
New info icon inside free-tier support overlay needs to be correctly aligned. 
Pr moves the `p` tag containing status text and icon inside `Overlay.Body`. Check out screenshot below to see the change. 
Before: 
After:
> chore(HelpBar): move text inside overlay body

- src/timeMachine/utils/rawFluxDataTable.ts
Closes https://github.com/influxdata/ui/issues/4583
https://user-images.githubusercontent.com/18511823/171056239-9f6b6868-9a72-4094-b3d3-9e4f3459b67d.mov
> fix: wrap strings in double quotes so strings with commas can render in Table / SimpleTable

- src/languageSupport/languages/flux/lsp/prelude.ts
Had unwrapped external method; needed to handle throws.
Noticed when working on another PR. Was not handling the occasional throw. It will error with the black screen and general "InfluxDB error occurred". (Note this is a rare event, and is not the root of all other errors which also trigger the black screen of doom.)
> fix: handle lsp method throw

- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
Closes #4676 
~~This PR replace the `-30d` time range with constant start and end dates to speed up query.~~
This PR replace the `-30d` time range with `-100y` for sample data. See [below](https://github.com/influxdata/ui/pull/4678#issuecomment-1138944434) for the reason why query sample data is different from query real data.
> chore: replace `-30d` time range with `-100y` for sample data

- src/timeMachine/reducers/index.ts
Closes #4635 
Applies to Dashboard and DataExplorer.
* The `|> keys()` transformation will only return those items which are a group key.
* See video of presumed, expected interaction (a.k.a. changes to flux query constructed).
* Notebooks query builder. 
* New QX flux builder.
https://user-images.githubusercontent.com/10232835/171297109-f17a06f5-d238-4460-bc1b-3823c219f286.mp4
> feat: when using group aggregate function, set default to all grouping tag values

- cypress/e2e/shared/tasks.test.ts
- cypress/support/commands.ts
Closes https://github.com/influxdata/ui/issues/4707
The problem is with the `cy.type` and how monaco editor is responding with the auto-complete. 
When cypress test types `import "` the monaco editor attempts to autocomplete with `import ""` (auto closing the double quotes). Sometimes monaco editor seems to glitch out and misplace the cursor, causing cypress to enter an invalid query. 
(note the missing end quote)
--- 
My attempt to fix it does two things: 
1. Force an `{enter}` after the first line so that it is explicit.
2. Make the `delay` between keystrokes to be 0, this seems to fix the autocomplete issue because it doesn't give monaco editor / lsp the time to think too much (?). The reasoning of why it works is a hypothesis of mine. 
Proof of it working: (50 runs with no flakes)
> test: press {enter} explicitly in tasks test to avoid invalid query in cypress test

- src/support/components/FreeAccountSupportOverlay.tsx
Inside free tier contact support, the link directing user to feedback and questions form has an empty href. 
Pr adds an `onClick` property that opens the Feedback and Questions form. 
https://user-images.githubusercontent.com/66275100/171212858-97e0329c-ebb1-46e6-ac53-2b2a5f1b4738.mov
> feat(HelpBar): connect feedback form with feedback link

- src/shared/components/EmptyGraphError.scss
- src/shared/components/EmptyGraphError.tsx
Closes [#4694](https://github.com/influxdata/ui/issues/4694)
Before: 
After: 
https://user-images.githubusercontent.com/18511823/171439831-5e516139-236a-4edf-a810-d110e18166a2.mov
> fix: better error message display in data explorer

- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
This PR updates queries to use the built-in functions in [flux schema package](https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/) to get values for measurements, fields, tag keys, and tag values. 
1. Replace the generic function `tagKeys()` and `tagValues()` with the built-in functions `measurements()`, `measurementFieldKeys()`, `measurementTagKeys()`, `measurementTagValues()`
2. Swap the order of `sort()` and `limit()`. Now the query do sort first, then limit
> chore: use built-in functions in flux schema package to query

- src/Signin.tsx
Closes #4657 
When a session expires, redirect to the Quartz login page rather than the cluster's login page.
> fix: redirect to Quartz login upon session expiration

- src/dataExplorer/components/MeasurementSelector.tsx
- src/dataExplorer/components/Schema.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/newDataExplorer.tsx
This PR renames components to `MeasurementsContext` and `MeasurementsProvider` with "measurements" in plural.
`MeasurementsContext` is a place to keep track of *all* the measurements in a specific bucket, instead of which *one* of the measurements that is selected by a user. Changing the name to use plural can avoid confusion.
This change is related to a discussion from [here](https://github.com/influxdata/ui/pull/4650#issuecomment-1140050696)
> refactor: rename to `MeasurementsContext` and `MeasurementsProvider` with plural

- cypress/e2e/shared/buckets.test.ts
- src/buckets/components/BucketCard.tsx
- src/flows/pipes/QueryBuilder/BucketSelector.tsx
- src/flows/templates/types/bucket.ts
- src/writeData/components/fileUploads/CsvMethod.tsx
Closes #4669 
Closes #4671 
Closes #4696 
Closes #4697 
* steps as identified by Will Baker.
1. make new bucket
2. click on new bucket name
3. --> it tries to generate a template notebook (when `influx.set('exploreWithFlows’, true)` as in prod)
4. black screen of doom.
* local ts-node dev server: `TypeError: bucket.retentionRules is undefined.` 
* transpiled js code error: Error for `find()` on the expected array.
* Issue:
* Was generating a template notebook with only the passed in name (and a hard-coded type=='user'). Then failing on an expectation of retention values in getReadableRetention().
* fix: provide template array. Page now loads without error.
* Issue:
* BucketContext is out of sync with the generated new bucket in the reducer entities.
* This is because the TEMPLATE.init …
> fix(4669/4671/4696/4697): template notebook generated from bucket, must also include retentionRules.

- src/buckets/components/CreateBucketButton.tsx
- src/writeData/components/WriteDataHelperBuckets.tsx
- src/writeData/subscriptions/components/SubscriptionFormContent.tsx
Closes https://github.com/influxdata/data-acquisition/issues/324
* If advanced `CreateBucketOverlay` is used, `callbackAfterBucketCreation` should still be invoked
* `useEffect` for `SubscriptionFormContent` should run whenever list of bucket is added or removed
* `WriteDataHelperBuckets` sorts buckets by 1) if they are selected and 2) name
Bug is fixed:
https://user-images.githubusercontent.com/6411855/171730415-210f84db-9a6e-49d5-b2c6-69c5d38c9126.mov
`usgs` is last alphabetically, but is at the top because it's selected:
> fix: advanced bucket selector onCreate callback

- src/timeMachine/utils/rawFluxDataTable.ts
Closes #3637 
In https://github.com/influxdata/ui/pull/4700, we handled a special case where the data in the column can be a string of `CSV` data. 
In this one, we handle the case when the data is a `JSON` object. 
The approach is to take the JSON string, remove all the double quotes and replace them with single quotes, (this saves the csvParser from being thrown off) and then wrap the JSON object in double quotes. 
Example
-> `{"key" : "value"}` came in from the flux query
-> `{'key': 'value'}` : we replace double quotes with single quotes
-> `"{'key': 'value'}"` : we wrap the string form of the JSON object in double quotes so we can display it.
----
Please look at the `_value` column in all the screenshots for the demo of JSON and CSV strings working.
**Simple CSV in Simple Table:** …
> fix: handle JSON Objects in parseFromFluxResults

- src/shared/components/CodeSnippet.scss
- src/shared/components/CodeSnippet.tsx
Closes #4537 
`Codesnippet` component's footer was an empty div with styling even when the `copy to clipboard`  button/`label` were absent so we hide the entire div when none of those two elements are present. (`label` or `copy to clipboard` button).
This makes it so that the component doesn't look like the copy button is clipped when we set `showCopyControl` to false.
Before: 
After:
> fix: codesnippet without copy button

- src/dataExplorer/components/QueryTime.scss
- src/dataExplorer/components/QueryTime.tsx
- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/ResultsContext.tsx
- src/dataExplorer/components/ResultsPane.tsx
moves the query time status information into the space between the editor and the viz
> feat: moving query time over to new status

- jest.config.js
- jsdom-custom.js
- package.json
- yarn.lock
* chore: use resolution to resolve cross-fetch to 3.1.5
* chore: use jsdom-custom.js to re-add TextEncoder and TextDecoder
It seems that the newer `cross-fetch` pulls in changes that break builds: https://app.circleci.com/pipelines/github/influxdata/ui/13386/workflows/befcfefa-441f-47c7-9979-60c13eb40f3c/jobs/79358. This appears related to https://github.com/jsdom/whatwg-url/issues/209 and is related to using `jsdom` as the `testEnvironment` where `TextEncoder` and `TextDecoder` are removed from the environment at some point and no longer available in the environment. This can be worked around by using a custom environment based on jsdom that conditionally extends the environment to add back `TextEncoder` and `TextDecoder`.
With a fresh checkout, I see errors with `yarn test`:
```
$ yarn …
```
> chore: use resolutions for cross-fetch

- cypress/e2e/shared/about.test.ts
- docker/Dockerfile.cypress
- src/organizations/actions/thunks.ts
[Quartz #6173](https://github.com/influxdata/quartz/issues/6173)
This implements the new route for renaming `org`; org renames for Cloud users will now run exclusively through Quartz. UI currently doesn't support `org description` but it remains an optional parameter in the event it becomes available.
> chore: org rename exclusively done in quartz

- src/buckets/components/BucketCard.tsx
- src/dashboards/components/DashboardHeader.tsx
- src/dashboards/components/EditVEO.tsx
- src/dashboards/components/GetTimeRange.tsx
- src/dashboards/components/NewVEO.tsx
- src/dashboards/selectors/index.test.ts
- src/dataExplorer/components/SaveAsButton.tsx
- src/mockState.tsx
- src/shared/actions/app.ts
- src/shared/components/TimeSeries.tsx
- src/shared/components/cells/CellContext.tsx
- src/shared/reducers/app.test.ts
- src/shared/reducers/app.ts
- src/shared/selectors/app.ts
- src/timeMachine/components/Queries.tsx
This PR resolves an issue where changing the timerange in a cell editor overlay would trigger a the background cells to update as well. Not entirely sure when this mechanism broke, but somewhere along the way this stopped work. 
The crux of the issue was that we referencing the wrong route, `cell` vs `cells`. Not sure when that change happened but it looks like this has been broken and unreported for a while.
There was a bunch of state setting that I cleaned up to just derive values off of existing information that's available in the TimeSeries component
> chore: freeze timerange changes from triggering background queries in dashboards

- src/pageLayout/containers/TreeNav.tsx
Closes #4730 
Pr adds Status Page to Help Bar so that users can see information about regional uptime and incident management. 
https://user-images.githubusercontent.com/66275100/172636606-f3e3f3ae-507b-48de-b43e-9ad1c1e35c3b.mov
> feat: add status page in help bar sub menu

- src/dataExplorer/components/MeasurementSelector.tsx
In schema browser, the search bar for measurement selector could not type anything. This PR fixes the bug and enables the typing and search functionality.
https://user-images.githubusercontent.com/14298407/172668222-ffb87546-3466-447d-bcad-ceb285c0f34e.mov
> fix: enable search in measurement selector

- src/flows/pipes/Notification/view.tsx
- src/languageSupport/languages/flux/lsp/prelude.ts
- src/languageSupport/languages/flux/lsp/worker/utils.ts
- src/timeMachine/actions/queries.ts
- src/variables/utils/astim.ts
- src/writeData/components/ClientCodeQueryHelper.tsx
Part of (possibly closes) #4677 
* when occurs:
* on load of the old DataExplorer, with the queryBuilder (not the flux script editor):
* get error in the queryBuilder loading
* on load of an existing Dashboard, once you click to open a cell:
* this again loads DataExplorer subcomponents, with a queryBuilder (not a flux script editor). 
* console errors:
* lsp library error.
1. since the script editor is not loaded in these^^ views, the error is likely in an lsp helper method.
2. found downstream code in these^^ use cases:
* which use the lsp helper methods
* where are not error handling
3. if I manually force throw at these points --> I see the same UI error screens.
4. These errors only occur in certain use cases:
* based upon the user query and/or the source data loaded in the query …
> fix(4677): lsp helper methods need to be error handled.

- src/dataExplorer/components/FieldSelector.tsx
- src/dataExplorer/components/TagSelector.tsx
- src/dataExplorer/shared/utils.ts
This PR updates the number of showing items from 8 to 25 when the "Load More" button is clicked. The initial number of showing is still the same, 8.
Here is the requirement mentioned in #4510:
> When Load More is chosen, up to 25 additional entries will be shown to the user; if more than 25 more exists in the list, the user will again have the option to load more which will result in an additional 25
https://user-images.githubusercontent.com/14298407/172711855-6c38358e-6081-456b-ba60-01bcba16b2d3.mov
> chore: update "Load More" to show 25 additional items each time

- package.json
- yarn.lock
Closes #4651 
Fixed previous issue with PR, added yarn.lock after `yarn install`
> chore: update giraffe version v2262

- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
- src/dataExplorer/shared/utils.ts
This PR adds case-insensitive sort in schema browser query to get the values of measurements, fields, tag keys, and tag values. 
This is a suggestion from @jsternberg (on [slack](https://influxdata.slack.com/archives/C030G5783M3/p1653681553393739))
> chore: perform case-insensitive sort in schema browser

- src/support/components/ConfirmationOverlay.tsx
- src/support/components/PayGSupportOverlay.tsx
Closes https://github.com/influxdata/EAR/issues/3323
Connects https://github.com/influxdata/EAR/issues/3322
- Appends the current org id to the description
- Translates the severity we show on the dropdown into the value SF uses (e.g. `3 - Standard` becomes `Severity 3`)
- Updates the text in the confirmation overlay to say for critical issues, calling support is required
- Makes Severity 3 the default:
> chore(helpBar): usability tweaks after feedback

- src/pageLayout/containers/TreeNav.tsx
Closes #4744 
Pr adds InfluxDB University to Help Bar. Upon clicking on the link, InfluxDB University page opens up in a new tab. 
https://user-images.githubusercontent.com/66275100/172637213-fa5ce116-37d8-4899-95eb-8051a94e4ccd.mov
> feat: add influxdb uni to help bar sub menu

- cypress/e2e/shared/about.test.ts
- src/organizations/components/OrgProfileTab/CopyableLabeledData.tsx
- src/organizations/components/OrgProfileTab/index.tsx
Closes #4791 
Closes #4052 
Closes both of the issues above. Made an optional prop on `CopyableLabeledData` to toggle the rename org button being visible. Left the Copy button to say "Copy to Clipboard" for upcoming facelift. Also adds "(Host Name)" next to Cluster URL to make it clear to users.
https://user-images.githubusercontent.com/106361125/173078264-5e72d5c8-2696-4f8f-a037-df720b765254.mov
> fix: updated rename org setting and Host Name

- src/Signin.tsx
Part of #4657 
- Refreshing doesn't work because it handles testing of edge cases poorly
- Redirecting seems the best approach, but not for dev environments
- Ignore this issue for dev environments
> fix: redirect to CLOUD but not for dev environments

- src/Signin.tsx
- src/shared/constants/index.ts
Part of #4657 
Production also sets `CLOUD_URL` to something other than what we want. We will have to be explicit.
> fix: use the explicit quartz login url

- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
Fixes a bug where we were attempting to deconstruct the quartzMe object and it was null sometimes
> fix(sub): avoid deconstructing quartzMe

- cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
Closes #4811 
- select the first line to activate the `textarea` or else it is considered disabled
- type into the `textarea` activated by the previous action
> test: type into the textarea to satisfy Firefox

- src/dataExplorer/context/fluxQueryBuilder.tsx
This PR removes the variables that never used in `FluxQueryBuilderContext` to prepare for the schema injection code
> chore: remove variables that never used

- README.md
This fixes the Remocal Quickstart link and removes the K8s-IDPE Quickstart link since it's the same as the Remocal Quickstart one.
> fix: Starting Dev Server readme links

- assets/images/radial-power-level.svg
Closes https://github.com/influxdata/ui/issues/4832
Adds the correct SVG:
> chore: update radial-power-level.svg with the correct one

- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
Temporarily removing payg requirement for CNS feature while it is under development
> chore(sub): remove payg requirement

- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/flows/pipes/RawFluxEditor/view.tsx
- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/lsp/monaco.flux.lsp.ts
- src/languageSupport/languages/flux/lsp/utils.ts
- src/shared/components/FluxMonacoEditor.tsx
- src/shared/contexts/editor/index.tsx
Part of #4591 
* Enable schema code injection for the new QX FluxBuilder.  
* This PR provide the interface to be used, for schema injection.
* `EditorContext.injectViaLsp()` for use by all downstream injections.
* Use differently typed payloads, per what get's injected.
* monaco-editor has commands and actions.
* these do not seem to be a 1-to-1 mapping with the spec executeCommand and codeActions.
* editor.addCommand(keyBinding, args => stuff)
* reasons rejected:
* bound to keys, cannot be triggered by name/enum
* editor.executeCommand()
* reasons rejected:
* is about asking the editor to execute a command, from a list of existing commands
* ICommand accepted:  https://github.com/microsoft/monaco-editor/blob/2c5c9636a276ffd00d78d8d7f9bfb13fb7740f77/website/typedoc/monaco.d.ts#L2181-L2195 …
> feat(4658/4709): sending executeCommand payload to LSP to trigger code injection

- src/variables/selectors/index.tsx
- src/variables/utils/getWindowVars.ts
- src/visualization/utils/useVisDomainSettings.ts
Closes idpe 14802
Closes #4855 
Zooming in on a graph re-issues the query with:
- an updated time range based on the domain (size of the zoom)
- an updated window period based on the updated domain
https://user-images.githubusercontent.com/10736577/175183376-a610190c-e7b8-4d09-bf86-e162a8934baa.mp4
> feat: use dynamic window period for zoom re-query

- src/visualization/utils/useVisDomainSettings.ts
Part of idpe 14803
Fixes a bug where the initial, pre-zoom domain is not equal to the selected time range.
Here is a video of the bug:
https://user-images.githubusercontent.com/10736577/175443825-e236284d-7939-499b-ac1f-aba1a2fe09d7.mp4
With the fix, we use one-way state to lock in the pre-zoom domain which is equal to the selected time range.
Here is a video of the fix:
https://user-images.githubusercontent.com/10736577/175444116-44d0a682-1d74-4604-9971-6dcec66c5d56.mp4
> fix: use one-way state to capture the initial, pre-zoom domain

- src/dataExplorer/components/BucketSelector.tsx
- src/dataExplorer/components/Schema.scss
the addition of sample data psuedo buckets into the selectable bucket list was a big win for new users in the notebook's query builder, so the state was adopted for the flux query builder. but we forgot to bring over the design language! this left a couple of buckets at the end of the list with no information about where they came from or why they were added. here is an attempt to add the section headers to bring this context back from the query builder and into the bucket selector dropdown.
@juliajames12 look ok?
> feat: attempt to normalize the bucket language

- src/homepageExperience/components/steps/Finish.tsx
Closes #4571 
Closes #4570
PR adds a sample app section to the node.js "finish" page to navigate users to a repo where users can view boilerplate code and a README.
https://user-images.githubusercontent.com/66275100/174398523-b7f9f8b6-f2ed-46c7-86ad-1718ce3e8452.mov
> feat: add sample app to node.js finish page

- src/homepageExperience/containers/HomepageContainer.tsx
Closes #4760 
Redirects users with no telegraf configs to the config overlay when clicking on the homepage telegraf link
https://user-images.githubusercontent.com/106361125/175976049-f61ae7f2-0579-4371-9a96-82ca7763551b.mov
> feat: users with no configs redirect to overlay

- package.json
- yarn.lock
This PR updates clockface version to 4.6.0 (influxdata/clockface#784) on Accordion Header Caret. This component is used in schema browser.
> chore: update clockface to 6.4.0

- src/writeData/subscriptions/components/BrokerForm.tsx
Enable CNS feature if account is not-upgradable or if `enableFreeSubscriptions` flag is enabled (also enforced on the backend)
> chore(subs): check if enableFreeSubscriptions flag is enabled

- src/organizations/components/OrgProfileTab/index.tsx
Closes #4597 
When the `quartzIdentity` feature flag is true, it displays the correct cloud provider, shown here:
When the `quartzIdentity` feature flag is false, it doesn't display a provider, shown here:
Edit (After styling update):
Completed during pair programming with @alexjw3
> fix: fix incorrect provider information

- src/homepageExperience/containers/HomepageContainer.tsx
Closes #4761
Changed the InfluxCLI name and description as it appears on the homepage:
> fix: changed CLI name and description

- src/dataExplorer/components/Results.scss
- src/dataExplorer/components/ResultsPane.tsx
- src/timeMachine/components/TimeMachineFluxEditor.scss
Closes #4904
the flux display property has some cool abilities to resize it's children based on their content, but when a child gets a fixed dimension (width: px or height: px) then it prevents the flex parent from shrinking to consume the extra space. this caused our resizing component to collide with our monaco component creating a condition where the editor could only become bigger. at first this just looked like bizarre resizing behavior, but soon induced a state where the editor was the only component on the screen.
turns out the logic was fine for the resizer as long as there weren't these fixed children, we just needed a way to force the child component to be decoupled from the sizing calculations being made for the parent component during rending the IE box model hierarchy. the …
> fix: force recalc of child component size

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- package.json
- src/dataExplorer/components/FieldSelector.tsx
- src/dataExplorer/components/Schema.scss
- src/dataExplorer/components/TagSelector.tsx
- src/shared/components/FilterList/MinimalistInjectionOption.scss
- src/timeMachine/components/FluxToolbar.scss
Closes #4905 
This PR updates the font of the field and tag values to "Roboto Mono", and update the hover color of function injectable elements to match with the color in Monaco editor
Note that this PR doesn't change the hover color of fields and tag values in schema browser to match with the green in Monaco editor because of the reason mentioned by Julia [below](https://github.com/influxdata/ui/pull/4912#issuecomment-1168959947)
> chore: update code font and hover color to match Monaco editor

- cypress/e2e/cloud/operatorRO.test.ts
- src/operator/ResourcesSearchbar.tsx
When using the search box in the operator page, the cursor jumps to the end of the line whenever the user tries to edit the text. See the before video. This PR fixes that by decoupling the component state from the provider's, which keeps he cursor in place. See the after video.
Before:
https://user-images.githubusercontent.com/4347903/176316008-23a50fba-2556-4825-9f89-e1fe56e02880.mov
After:
https://user-images.githubusercontent.com/4347903/176316073-b1e66c76-a90a-4215-97dc-9e7ad493306c.mov
> fix(AIM): Fix operator search field to keep cursor location

- src/writeData/subscriptions/components/BrokerDetails.scss
- src/writeData/subscriptions/components/BrokerDetails.tsx
- src/writeData/subscriptions/components/BrokerForm.scss
- src/writeData/subscriptions/components/BrokerForm.tsx
Closes https://github.com/influxdata/data-acquisition/issues/398
Lowers z-index so errs are shown above the fixed header.
Fixes width to account for whether the side nav is toggled or not.
Adds padding so we aren't losing the header / text at the top of the page.
https://user-images.githubusercontent.com/38860767/176711677-d950a466-c021-4af3-9df6-529a581dc274.mov
> fix: subscriptions header

- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/components/StringPatternInput.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/403
Currently, we are adding extra complexity and confusion by replacing `\\` to be `\` in a regular expression. We don't need it, thus removing the functionality.
> chore: do not escape backslashes in measurements and fields regex

- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/SampleAppCard.tsx
- src/homepageExperience/components/steps/SampleCode.tsx
Closes #4891 
Closes #4893 
Closes #4894 
Changes introduced in PR 
-  updated first mile python's sample app link 
- Added boilerplate code link for python 
- refactors `finish.tsx` by creating a new component `SampleAppCard` to render sample apps and boileplate codes
> chore: refactor first mile sample app code

- cypress/e2e/shared/buckets.test.ts
- src/telegrafs/components/CollectorCard.tsx
Closes #4818 
PR removes bucket name from telegraf card's metadata. 
After a telegraf configuration is created, the UI sets the bucket name once on the configuration card and it never changes. Even if user edits configuration to use a different bucket, the original bucket name will always be what's displayed in the card. Instead of constantly updating bucket's name, we will be removing it all together from the card. 
To see which bucket(s) is being used in a telegraf config, users can click on the edit button and view on the edit page. 
Before:
After:
> chore: remove bucket name from metadata

- src/writeData/subscriptions/components/BrokerFormContent.tsx
Closes https://github.com/influxdata/data-acquisition/issues/411
The default behavior of a number input is if it's focused to go up/down on scroll. This makes our port field behave oddly in the case of our single page scrolling form.
This prevents the number from going up or down on scroll for our create/edit view.
Also removes the auto focus on the ip and port so as the user lands on the page they are focused on the name field.
before:
https://user-images.githubusercontent.com/38860767/177419080-53ae3ac5-9d67-46a4-b8d6-88dcfe19fd25.mov
now:
https://user-images.githubusercontent.com/38860767/177419106-bd5c8c48-4cbe-4df2-9abe-8e57d70d8a2f.mov
> fix: do not effect the number input on scroll

- src/tasks/components/RunLogRowFlux.tsx
- src/tasks/components/RunLogsList.scss
Closes #4971 
Ensures flux is displayed correctly on all browsers in the task run logs. Screenshots for each browser below:
Firefox:
Chrome:
Safari:
> fix: display flux correctly in firefox

- src/shared/copy/notifications/categories/tasks.ts
- src/tasks/actions/thunks.test.ts
- src/tasks/actions/thunks.ts
Closes #4898 
When updating tasks in task page (active/inactive or name update), success or error notification that pops up doesn't indicate which task was updated. This can be troublesome for users performing mass updates (read linked ticket for in-depth explanation). 
PR adds an optional parameter `task.name` to `taskUpdateSuccess` and `taskUpdateFailed` so the task name can be visible in the notification message. 
https://user-images.githubusercontent.com/66275100/177643431-38b9d99e-2f5a-454e-a535-11b75938018f.mov
> feat: show task name in notification message

- src/visualization/types/SimpleTable/PagedTable.tsx
Part of #4882 
Part of bug squashing mission.
* general window.onerror triggered via the ResizeObserver
* What this is:
* Excessive recursion upon resize. But is a know issue because of how this window API should be used, and is chrome-specific behavior (matching what we see in honeybadger for the browsers).
* This is expected, and highly reported elsewhere:
* https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
* `https://github.com/WICG/resize-observer/issues/38`
* Previously done:
* we are already doing 2 (out of 3) code patterns to reduce the triggering occurrences. We can also do the 3rd one too (cancel animation frame).
In addition to this PR, going to be requesting permission to start filtering out (ignoring) this error in honeybadger.
> fix(4882): reduce ResizerObserver looping even further

- src/writeData/subscriptions/components/BrokerDetails.tsx
- src/writeData/subscriptions/components/BrokerForm.tsx
- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
- src/writeData/subscriptions/components/DetailsSubscriptionPage.tsx
- src/writeData/subscriptions/components/ParsingDetails.tsx
- src/writeData/subscriptions/components/ParsingForm.tsx
- src/writeData/subscriptions/components/SubscriptionDetails.tsx
- src/writeData/subscriptions/components/SubscriptionForm.tsx
Closes https://github.com/influxdata/data-acquisition/issues/409
When the parent div or any of its children of Subscription sections receive focus, the Subway Nav step should be updated with the currently active step(in which the focus was just received).
> feat: add onFocus for subscription sections

- src/operator/OrgOverlay.scss
- src/operator/OrgOverlay.tsx
see #[14853](https://github.com/influxdata/idpe/issues/14853)
PR edits `OrgOverlay.scss` to override overly header style to make title (OrgID) selectable.  
After Change: 
https://user-images.githubusercontent.com/66275100/177415033-db1a31b5-e209-4278-b014-673ecb3b8999.mov
> feat(operatorUI): add css to make orgid selectable

- src/tasks/actions/thunks.ts
- src/tasks/containers/TasksPage.test.tsx
- src/tasks/containers/TasksPage.tsx
Closes #4897 
Bug: show inactive toggle inside Tasks page resets back to true when user leaves and returns to page. 
fix: removed setState responsible for re-setting `showInactive` to true.  
https://user-images.githubusercontent.com/66275100/177883487-ea85201c-4ba3-41bb-8ecb-14fe25bb63e5.mov
> fix(TasksPage): remove showInactive setState from constructor

- src/identity/apis/auth.test.ts
- src/identity/apis/auth.ts
Connects #4798 
Adds the function `retryFetchIdentity` and associated tests. It's not hooked up into the application, that will come in a future PR.
This function will retry `500` level errors after requesting data from the identity endpoint (either `/me`, `/quartz/me`, or `/quartz/identity` depending on the state of the application flags). It will retry up to 4 times, for a total of five attempts to authenticate, with an increasing backoff time between retries.
Descriptions of the jest tests added:
```
retrying failed authentication attempts
✓ doesn't retry when the first call is successful
✓ throws the error in the event of a 401
✓ retries once
✓ retries multiple times
✓ retries up to the retry limit
✓ retries until a non 500 error is encountered
the timing of auth retrying
✓ retries …
```
> feat: add ability to retry-with-backoff for failed auth attempts

- src/Signin.tsx
- src/identity/apis/auth.ts
- src/onboarding/containers/LoginPage.tsx
Closes [IDPE #15135](https://github.com/influxdata/idpe/issues/15135)
As implemented in [this PR](https://github.com/influxdata/ui/pull/4896/files), the UI currently decides whether to check for session validity using quartz or IDPE based on whether the user is a cloud user. But there are a limited number of cloud environments that do not yet have access to quartz. This is in the process of being resolved in [quartz](https://github.com/influxdata/quartz/issues/6458). For now, it can't be inferred with certainty that a cloud user can check session validity using a quartz endpoint.
This patches the issue by reverting to the behavior of always using IDPE `/me` to check the user's session validity. I will add a new issue to remind us to return to using quartz endpoints once the quartz …
> fix: use idpe /me in lieu of quartz for auth polling

- .gitignore
- project.garden.yml
Placeholder files for using `garden dev --local-mode` (reverse proxy mechanism) to work with UI.
> chore: add placeholder files for garden-based development

- src/operator/OrgOverlay.scss
- src/operator/OrgOverlay.tsx
PR touches Org overlay of Operator UI in an attempt to fix the styling of the overlay grid. 
Before fix: 
After fix: 
> fix(operatorUI): improve orgOverlay grid design

- src/accounts/context/userAccount.tsx
- src/identity/apis/auth.ts
- src/identity/quartzOrganizations/actions/creators/index.ts
- src/identity/quartzOrganizations/actions/thunks/index.ts
- src/identity/quartzOrganizations/reducers/index.ts
- src/shared/copy/notifications/categories/accounts-users-orgs.ts
This PR provides a framework that will be used to support the user profile page: UI #4049. Specifically, it
1. Adds a thunk and a reducer to handle changing the user's default organization.
2. Adds a method in the API layer to clean up error handling for changing the user's default account
* (switch-account functionality is handled by context, not redux)
3. Adds error notifications if the request to change the user's default organization fails. 
Also cleaned up error notifications for failure to change the default account.
> feat: Add redux and API layer support for User Profile

- src/timeMachine/reducers/index.ts
Part of #4882 
* `TypeError: Cannot read properties of undefined (reading 'values')`
*  <img width="500" alt="Screen Shot 2022-07-11 at 4 50 15 PM" src="https://user-images.githubusercontent.com/10232835/178377425-f712c59c-2316-4ed2-9290-bccf461f2061.png">
* This error first occurred on May 31st, after this PR was merged. https://github.com/influxdata/ui/pull/4716/files
*  <img width="500" alt="Screen Shot 2022-07-11 at 4 48 49 PM" src="https://user-images.githubusercontent.com/10232835/178377276-c12d1639-313b-4dc5-ae0d-63e3f0e12531.png">
* We added groupby tags to the builderConfig state, but not the queryBuilder state. Need both.
> fix(4882): groupby values should be added to both builderConfig and queryBuilder

- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/ResultsContext.tsx
- src/dataExplorer/components/ResultsPane.tsx
- src/dataExplorer/context/fluxQueryBuilder.tsx
- src/dataExplorer/shared/utils.ts
idk if this closes the issue or not (#4906) as there's some unknown distinction between prod and local dev environments and even testing prod builds locally didn't seem to manifest the issue that is so replicate-able in prod, but there have been issues in the past with getting our local storage libs to survive the prod build. seeing as we didn't want this behavior anyways (#4941) there's a chance that solving one problem fixes the other.
There was also a strange updating artifact locally where the reference for view properties would only update every other key stroke. this isn't a complete outage like we're seeing in production, but some weird skip state, so you'd type `te` as an axis label and just get `t`, but as soon as you typed `s`, you'd get `tes`. Forcing the subobject's reference …
> fix: allow view options to update

- src/writeData/components/fileUploads/AnnotatedCSV.md
Part of #4882 
* `uploadCsv function: error in csv.from()...`
* There is a whole set of these errors coming from when the csv uploaded (via flux query to backend) is invalid.
* Expected error. This information is already surfaced to the user.
* However, there is ALSO a big spike in these errors starting April 12th.
* <img width="500" alt="Screen Shot 2022-07-11 at 6 24 26 PM" src="https://user-images.githubusercontent.com/10232835/178387951-ebceb780-4681-439d-bb26-d8e841a06a28.png">
* the vast majority of these are `error in csv.from(): failed to read metadata: missing expected annotation datatype. consider using the mode: "raw" for csv`
* the example provided at the link does not work.
* is both out of date (older flux version). And points out a bunch of annotated csv examples which does …
> fix(4882): change docs link used for csv.from(), to get closer to what works.

- src/tasks/containers/TaskEditPage.tsx
- src/types/tasks.ts
Closes #4978
This addresses an experience concern where a task is backed by a script by blocking users from saving flux if their task is backed by a script.
This fills the flux editing area with some notice text informing the user to use the api to interact with their script-backed task. It disables the save button as well. No impact on flux-backed task editing that I found.
> chore: don't allow editing of a task if it is backed by a script

- src/writeData/subscriptions/components/BrokerDetails.tsx
- src/writeData/subscriptions/components/BrokerFormContent.tsx
Closes https://github.com/influxdata/data-acquisition/issues/415
Edit form field validation:
- same validation as create form - "save changes" button is disabled if form is not valid
- tweaked edit button - Edit -> Cancel
- editing broker hostname clears password
- added note that changing broker hostname will clear password
https://user-images.githubusercontent.com/6411855/178611046-835affb7-5f69-41b3-91bf-b932ead0e702.mov
> feat(sub): edit form field validation

- src/dataExplorer/components/SaveAsNotebookForm.tsx
- src/flows/pipes/RawFluxEditor/view.tsx
this is for https://github.com/influxdata/EAR/issues/3436
there was a bug in the way that DE exported raw flux script panels when making a notebook. so i cleaned that up and added some migration code so that the user would be unblocked, automatically update their broken notebook, and we can later remove the migration
> fix: broken export from DE

- src/visualization/utils/useVisDomainSettings.ts
Part of EAR 2422
- refits the graph on the value axis when the query results change
- adds documentation on the differences between "preZoomDomain" and "domain"
https://user-images.githubusercontent.com/10736577/178601526-07cd553d-ecbe-451d-aa1e-12cccb94ff5d.mp4
> fix: refit the graph on the value axis when the query results change

- src/dataExplorer/components/ResultsPane.tsx
Closes #5001
force cancels all running queries on the page when the cancel button is pressed.
> fix: force cancel

- src/dataExplorer/components/Results.tsx
- src/visualization/components/View.tsx
Closes #5002
adds an optional parameter to not display the default loading indicator in a visualization
> fix: hide the view timer in flux schema builder

- src/authorizations/components/AllAccessTokenOverlay.tsx
Closes #4992 
Fixes the token overlay behavior when there is an error on creation.
Error behavior:
https://user-images.githubusercontent.com/10736577/178867454-dae61700-a5b7-4661-b5cb-0d512da86033.mp4
Success behavior (no change):
https://user-images.githubusercontent.com/10736577/178867492-d1c8675e-0bea-4042-a9d2-157ecfc0281c.mp4
> fix: use correct overlay behavior for All Access API token creation

- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/SampleAppCard.tsx
Closes #4987 
Closes #4986 
PR adds the following to the Go First Mile Finish page:
- Sample App [https://github.com/influxdata/go-samples/tree/master/cmd/iot_app]
- Boilerplate Code [https://github.com/influxdata/go-samples/tree/master/cmd/boilerplate]
- removes code conditionally rendering sample app and boiler plate code.
> feat(FirstMile): add Go sample app and boilerplate code to finish page

- src/dashboards/selectors/index.test.ts
- src/mockState.tsx
- src/shared/actions/app.ts
- src/shared/contexts/app.tsx
- src/shared/reducers/app.test.ts
- src/shared/reducers/app.ts
- src/shared/selectors/app.ts
- src/writeData/subscriptions/components/BrokerForm.tsx
- src/writeData/subscriptions/components/BrokerFormContent.tsx
- src/writeData/subscriptions/components/CertificateInput.tsx
- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
- src/writeData/subscriptions/components/DetailsSubscriptionPage.tsx
- src/writeData/subscriptions/components/SubscriptionsLanding.tsx
Closes https://github.com/influxdata/data-acquisition/issues/417
- certificate coming soon with notify me button
- clicking the notify me button sends a UI event that we can query for in monitor301 and use the email address to know who to email
- once button is clicked, a boolean is persisted to the App state so the button is not shown again to the user
- fix bug where "changing broker will require password change" was showing during create flow
- fixed bug where header was covering mqtt icon + "setting up" text at larger screen sizes
Before clicked: 
After clicked:
> feat(sub): certificates coming soon + bug fix

- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
- src/flows/pipes/QueryBuilder/context.tsx
- src/shared/constants/queryBuilder.ts
- src/timeMachine/apis/queryBuilder.ts
Closes #5047 
This PR increases the measurement (and tag) limit from `500` to `1000` when the feature flag  `increasedMeasurmentTagLimit` is on. The constant names are also updated to more general names since the limit applies to both measurements and tags.
I will turn on the feature flag in monitor301, tools, and production once this is merged into master
> chore: increase measurement limit to 1000

- src/writeData/subscriptions/components/JsonParsingForm.scss
- src/writeData/subscriptions/components/JsonParsingForm.tsx
- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/context/subscription.create.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/405
Helps https://github.com/influxdata/data-acquisition/issues/400
Allows users to switch between providing a static measurement name and using jsonpath or regex to pull the measurement from their message. Totally works 😱 
Regex
Json
Merge first:
- https://github.com/influxdata/idpe/pull/15161
Manually tested create & update with json & string. Also manually tested switching from static to dynamic and vice verse for json & string.
> feat(sub): toggle between static and dynamic measurement

- cypress/e2e/cloud/operator.test.ts
- src/operator/account/AccountViewHeader.tsx
This enables the convert to contract operator UI feature for direct payg accounts. Previously this was only available to free accounts.
> feat: Enable convert to contract for direct payg accounts

- src/identity/actions/thunks/index.ts
- src/identity/quartzOrganizations/actions/thunks/index.ts
- src/shared/copy/notifications/categories/accounts-users-orgs.ts
Closes #5067
There are still cloud environments without quartz access, and those environments request data from /`quartz`. Previously, those requests could return a `401`, and the data would not be provided, but no error was reported. With the upgrade to the `identity` endpoint, they are now handled but produce a toast notification for the user. This PR changes the error reporting so that requests to `/quartz/identity` that fail are sent to honeybadger for tracking, instead of generating a toast.
This PR proposes adding this reporting only for `/quartz/identity`, not `/quartz/me`, since the latter endpoint is being deprecated, and will be unused once the feature flag for `quartzIdentity` is switched on.
> fix: use honeybadger over toast for identity error reporting

- src/types/subscriptions.ts
- src/writeData/subscriptions/utils/form.ts
Helps https://github.com/influxdata/data-acquisition/issues/425
Removes the `createdBy` and `updatedBy` properties that might exist before making an update request. These audit columns are managed by the backend and the UI should not attempt to provide them in the PUT request.
> chore(sub): remove createdby, updatedby for update

- src/dataExplorer/components/BucketSelector.tsx
- src/shared/components/SearchableDropdown.scss
- src/shared/components/SearchableDropdown.tsx
Closes #5072 
This PR fixes the bug that search bar disappears when there is no found buckets.
> fix: show search bar for bucket even when no bucket is found

- src/dataExplorer/components/MeasurementSelector.tsx
- src/shared/components/SearchableDropdown.scss
This PR fixes a bug that the old measurement search term still remains when a new bucket is selected.
https://user-images.githubusercontent.com/14298407/179556747-4da7c07a-6d04-4d9a-a8e3-ba43428fceeb.mov
https://user-images.githubusercontent.com/14298407/179556771-7e7e5e0a-90d9-47cd-ab5c-dd541654cf53.mov
> chore(schemaBrowser): clear old measurement search term when select a new bucket

- package.json
- yarn.lock
PR updates `package.json` with newest giraffe version to include ability to properly scale large data points on the y-axis 
> chore: update giraffe from 2.31.1 to 2.32.0

- src/visualization/types/Gauge/constants.ts
- src/visualization/types/Gauge/view.tsx
Part of #4882 
* error in honeybadger:
* <img width="718" alt="Screen Shot 2022-07-18 at 2 31 29 PM" src="https://user-images.githubusercontent.com/10232835/179621882-807ed2f0-ae60-4984-b633-bfc1400d3f40.png">
* is this code:
* https://github.com/influxdata/giraffe/blob/master/giraffe/src/components/Gauge.tsx#L364-L372
* is missing a default, which we provide for the Y (not the X)
> fix(4882): set default for Gauge input

- src/writeData/components/ClientLibrarySection.tsx
Closes #4903
Navigate users to new onboarding wizards if GO, Python, or Node.js is clicked on the Load Data page.
https://user-images.githubusercontent.com/66275100/179632518-8fb304ea-d4b9-49b9-bc1d-3f23d9d6ae5b.mov
> feat(LoadData): direct go/python/node clicks to onboarding page

- src/shared/containers/SetOrg.tsx
**Issue:** 
Every time I get redirected to one of the onboarding pages (python, go, node), I see a react router warning in the console. 
`React Router Warning: <Route> elements should not change from controlled to uncontrolled (or vice versa)`
The issue was in SetOrg.tsx, when conditionally rendering onboading components, we only wrap routes with fragments `<></>`. 
https://user-images.githubusercontent.com/66275100/179791597-a99d2a9c-8f3b-4219-bb77-f5ee6d23c599.mov
**Fix:** 
According to https://v5.reactrouter.com/web/api/Switch/children-node  `all children of a <Switch> should be <Route> or <Redirect> elements.  `
Alternative solution is to wrap first mile components with additional `Route` and `Switch`. Or just render routes as array, like shown in this pr. …
> fix(firstMile): render routes as array to fix react warning

- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/SampleAppCard.tsx
Closes #4995 
Pr removes `onClick` property from `ResourceCard` and adds it to `SafeBlankLink`. 
Background: 
While adding eventing in `SampleAppCards` I noticed events weren't being logged properly. The assumption here was when a resource card is clicked, the `onClick` prop will fire and execute the eventing function `handleNextStepEvent`. This wasn't happening. Looking into the Clockface doc, it turns out `onClick` is a prop of `ResourceCardEditableName` and only fires when the name itself is clicked not edited. 
Clearly, we aren't using `ResourceCardEditableName` component for our purposes, so we need to move the onClick prop into `SafeBlankLink` to be able to capture `onClick` events. 
> feat(firstMile): add UI eventing to finish page

- src/operator/OrgOverlay.tsx
- src/usage/BillingStatsPanel.tsx
Closes #
no ticket - capitalization typo and wrong units on the operator page. The rate limit units are _per second_, not _-seconds_. 
- [na] Feature flagged, if applicable
> chore(usage,operator): fix typo and units

- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/flows/components/header/MenuButton.tsx
- src/tasks/components/TaskCard.tsx
Closes https://github.com/influxdata/ui/issues/5110
The `deletePinnedItemByParam` was being called without catching the error it potentially throws, in some places of the app. This caused our tests to flake out. This should fix it. 
> fix: Error handling for pinned items

- package.json
Updates the openapi sha to reflect changes in https://github.com/influxdata/openapi/pull/448
> chore: update openapi sha

- src/homepageExperience/components/steps/cli/CliSteps.scss
- src/homepageExperience/components/steps/cli/InitializeClient.tsx
- src/writeData/components/WriteDataHelperBuckets.tsx
Since free users have a limited number of free buckets to use, we should give them an option to select an existing bucket in the `Initialize Client` section of the CLI onboarding. If users select a bucket here, it will use that bucket to auto-populate the commands in later steps. If they create a bucket rather than selecting one, the rest of the steps will still show `sample-bucket` in the command. 
Below is a screenshot of the proposed menu and a demo of it updating the commands.
EDIT: Added back the `Create Bucket` button to align with other onboarding flows, updated screenshots below.
Note: more pages need to be added, but they will come in separate PRs!
https://user-images.githubusercontent.com/106361125/180059593-832a13ae-fae9-42be-b3dd-3b5ad080d9f7.mov
Authors and Reviewer(s), …
> feat: allow users to select bucket in cli wizard

- src/visualization/context/pagination.tsx
Part of https://github.com/influxdata/giraffe/issues/781
This bug was demonstrated with Giraffe code, but it is the same code in UI's implementation of the `PaginationProvider` of SimpleTable. It's easier to reproduce in Giraffe than with the full UI and InfluxDB.
- Fixes the `PaginationProvider` by running the `useCallback` correctly when the page `total` changes, as can be the case going from one set of results to a different set of results.
- This fix will be implemented in Giraffe also.
Here is a demo of it working by going between an empty result set (no csv) and a valid result set:
https://user-images.githubusercontent.com/10736577/180324355-59bde922-e878-4c8b-9f86-c3d175456a00.mp4
> fix: use correct dependencies to set page for SimpleTable

- src/variables/actions/thunks.ts
Closes #5092
Removes the flag `hydrateRelevantDashboardVariables` which has been on in production for months. This flag made it so that only variables used by the dashboard being loaded were hydrated, rather than all variables in an organization.
> chore: remove feature flag hydrateRelevantDashboardVariables

- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
Closes #4765, #4766, #4767
Adds the install dependencies page on the new CLI walkthrough.
> feat: install dependencies page for CLI

- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/ResultsContext.tsx
- src/dataExplorer/components/ResultsPane.tsx
- src/dataExplorer/context/fluxQueryBuilder.tsx
removes the migration for #4906, to be delivered after people have had a chance to let their migration run (EOW or so)
> chore: clean up migration

- src/visualization/types/SimpleTable/PagedTable.tsx
Part of https://github.com/influxdata/giraffe/issues/781
- Use optional chaining in a few places to prevent a console error when the results are an empty data set (blank csv)
- Remove `ref.current` as a dependency because `ref` is mutable and has no effect on the hook, see https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom
NOTE: the above fixes will be implemented in Giraffe also.
> fix: use optional chaining and fix dependency array for SimpleTable

- cypress/e2e/cloud/pinned.test.ts
related to #5149 
PR adds code to all individual tests in `Pinned.test.ts` to wait on UI elements to be visible before accessing said element. 
I ran each test at least 10 times to check for flaky behavior. No issues observed. 
> test(pinned): wait for element to be visible before accessing

- src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx
Closes #4772 
Pr adds `Execute a Flux Aggregate Query` step to influx CLI Onboarding. 
Not behind a feature flag currently. Will be behind `onboardCLI` once all components are linked to the homepage. 
> feat(firstMileCLI): add execute aggregate query page

- src/homepageExperience/components/steps/cli/ExecuteQuery.tsx
Closes #5174
Adds `bucket` prop back to `Execute Query` page so that the flux script can update the users bucket name dynamically.
> fix: add bucket prop back to execute query page

- src/identity/quartzOrganizations/mockOrgData.ts
- src/identity/quartzOrganizations/reducers/index.test.ts
- src/identity/quartzOrganizations/reducers/index.ts
Closes #5136 
Closes #5160
Adds unit test coverage for the quartzOrganizations reducer to check if:
1. Organizations are correctly loaded into state.
2. User can set a new default.
3. `status` of redux state corresponds to whether data was loaded or not.
Also fixes an inconsistency between the reducer and quartz. Quartz doesn't allow an account with orgs to have _no_ default org. That's unexpected, so we should be setting an error in redux state if that happens, and can then use that state for error handling in the UI.
> feat: add unit tests to quartzOrganizations reducer

- src/visualization/types/SimpleTable/style.scss
Left over from https://github.com/influxdata/ui/issues/3064
Part of https://github.com/influxdata/giraffe/issues/777
Originally, https://github.com/influxdata/ui/pull/3065 addressed https://github.com/influxdata/ui/issues/3064 and everything worked as expected.
However, we should also remove extraneous code that makes it hard to understand why the casing for header cells are styled 3 times which makes it difficult for maintainers to understand the intent, and consequently much harder to move the code, as is the situation now. We are trying to move this into Giraffe while keeping the same look and feel.
To summarize:
1. Clockface transforms table header cells into uppercase.
2. Simple Table originally had uppercase table header cells, similar to what clockface uses.
3. A design decision …
> chore: remove unnecessary text-transform for clarity

- cypress/e2e/shared/fluxQueryBuilder.test.ts
Relate to #5171 
This PR skips the test for schema browser temporarily so that we can work on it while unblocking the other PRs.
> test: skip the entire test for schema browser

- src/homepageExperience/containers/CliWizard.test.tsx
- src/homepageExperience/containers/CliWizard.tsx
- src/homepageExperience/utils.ts
Closes #4762 
Closes #4763 
Adds the CLI Wizard navigation. This adds the container for the pages previously added, but it is still not routed. The next PR will add the route for it and hide this feature behind a feature flag. Below, there is a demo video of the wizard nav going through each page.
Demo:
https://user-images.githubusercontent.com/106361125/180865570-bdbb84b1-889b-4e13-b4dd-1183e05fa501.mov
> feat: adds wizard nav to the cli onboarding

- src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/cli/InitializeClient.tsx
- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
- src/homepageExperience/containers/CliWizard.tsx
- src/homepageExperience/containers/HomepageContainer.tsx
Closes #5163
Updated naming convention from `InfluxCLI` to `InfluxDB CLI`. Saved the name to an exported variable in `CliWizard.tsx`.
Example screenshot:
> feat: update InfluxCLI to InfluxDB CLI

- src/writeData/clients/Java/description.md
- src/writeData/clients/Kotlin/description.md
- src/writeData/clients/Scala/description.md
- src/writeData/clients/Scala/dispose.example
- src/writeData/clients/Scala/execute.example
- src/writeData/clients/Scala/executeFull.example
- src/writeData/clients/Scala/index.ts
- src/writeData/clients/Scala/initialize.example
- src/writeData/clients/Scala/write.0.example
- src/writeData/clients/Scala/write.1.example
- src/writeData/clients/Scala/write.2.example
- src/writeData/clients/Swift/description.md
Related to https://github.com/influxdata/influxdb-client-java/pull/347
1. Added examples how to use Scala's `WriteAPI`:
2. Updated client versions
> feat(client_libs): add Scala WriteAPI example

- src/identity/apis/auth.ts
Closes #5182 
Adds functions to API layer to handle two new AIM endpoints, `getAccountsOrgs` (retrieve list of accounts from quartz, given an account id) and `putAccountsOrgsDefault` (given an account id and org id, set that org as the default org for the given account). 
These endpoints provide more functionality than their pre-existing counterparts (which could only `GET`/`PUT` data for the _currently active_ account). Those old functions will be removed by [UI #5183](https://github.com/influxdata/ui/issues/5183).
Also cleaned up some comments in the API layer.
> feat: add getAccountsOrgs and putAccountsOrgsDefault to api layer

- cypress/e2e/shared/deepLinks.test.ts
- src/shared/components/NotFound.tsx
Closes #5130
https://github.com/influxdata/ui/pull/4826 Changed `NotFound.tsx` from a class component to a function component, and in doing so, chaged what used to be an instance variable into a React `ref`. Unfortunately, it didn't update the check if `org` existed, and so the code that handles org not being present (in the case of logged-out users) never runs, causing OSS tests to fail and the feature to be broken for logged-out users.
> fix(deepLinks): fix broken check against org reference

- src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/go/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/nodejs/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/python/ExecuteAggregateQuery.tsx
Closes #5193 
Updates text on all `Execute Aggregate` pages.
Screenshot:
> feat: changed aggregate text and add bucket logic

- src/pageLayout/containers/TreeNav.tsx
Closes #5120 
Closes #5119 
New feature inside Help Bar that allows user to request POC via this [link](https://www.influxdata.com/proof-of-concept/).
It's currently behind a feature flag `requestPoc`
https://user-images.githubusercontent.com/66275100/181284747-2e429d39-bb95-4f06-98e9-e1bf50061504.mov
> feat(helpBar): add request poc link to helpbar

- src/homepageExperience/components/steps/Finish.tsx
Closes #4773 
Finish page from cli onboarding is missing a resource card (CLI Commands) that should link users to the docs page. 
Pr adds this resource card and code to make sure no sample cards are shown on the page. 
> feat(CLIWizard): add cli commands resource card

- src/writeData/subscriptions/components/BrokerDetails.scss
- src/writeData/subscriptions/components/BrokerDetails.tsx
- src/writeData/subscriptions/components/BrokerForm.tsx
- src/writeData/subscriptions/components/JsonParsingForm.scss
- src/writeData/subscriptions/components/JsonParsingForm.tsx
- src/writeData/subscriptions/components/JsonPathInput.tsx
- src/writeData/subscriptions/components/StringParsingForm.scss
- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/components/StringPatternInput.tsx
Closes https://github.com/influxdata/data-acquisition/issues/218
- Adds links to documentation for native subs, json parsing and string parsing. Doc links shown on create and edit but not on details view.
- Links to our documentation, json path and regex101.
- Adds timestamp headers as I noticed they were missing while editing.
- Cleans up styling discrepancies.
**Video:**
https://user-images.githubusercontent.com/38860767/181568328-e74dad17-8bc2-4070-a63e-958ce8562846.mov
**Screenshots:**
Create subscription:
Create json parsing:
Create string parsing:
Edit view subscription:
Edit view string parsing:
Edit view json parsing:
> feat: add documenation links, cleanup styling, timestamp header

- src/buckets/components/createBucketForm/CreateBucketForm.tsx
- src/schemas/buckets.ts
- src/timeMachine/components/SelectorListCreateBucket.tsx
Addresses [#](https://github.com/influxdata/ui/issues/5127)
i can't reproduce this one, but there's only one place in the code that matches the pattern from the referenced issue. it's a path where the shared bucket context loads a bucket into the redux store that doesn't have a retention rule. technically, the line just under this updated guard says "dont worry about it, it's cool" so it seems that this state is supported, just not guarded correctly
> fix: optional bucket retention

- package.json
- src/cells/selectors/index.ts
- yarn.lock
Connects #5234
- Adds reselect library
- Uses reselect's `createSelector` to memoize the dashboard cell selector
This provides minimal performance gains, but gaining performance on dashboards is going to be a marathon, not a sprint.
Attached are two screenshots which perform a very simple performance test - a console log statement - on a dashboard with 4 cells.
| Function Name | Function calls |
|---------------|----------------|
| Cell Selector | 18             |
| Cell Render   | 9 * 4 = 36     |
| Function Name | Function calls |
|---------------|----------------|
| Cell Selector | 1             |
| Cell Render   | 1 * 4 = 4     |
- ~[ ] Feature …
> perf(dashboards): add reselect, memoize cell selector

- src/shared/copy/notifications/categories/subscriptions.ts
- src/writeData/subscriptions/context/api.tsx
- src/writeData/subscriptions/context/subscription.create.tsx
- src/writeData/subscriptions/context/subscription.update.tsx
Helps https://github.com/influxdata/data-acquisition/issues/468
When bad requests occurs in Native Subscriptions we want to show the user the error message from the API so they know what they need to change to fix it. An example of this is if the user provides a bad broker connection URI
> feat(sub): show 400 errors to user

- src/me/components/DocSearchWidget.tsx
Closes #5120 
Adds `Request Proof of Concept` under Useful Links of UI homepage. 
behind `requestpoc` feature flag. 
> feat(DocSearch): add poc link under Useful Links

- src/visualization/types/SimpleTable/InnerTable.tsx
- src/visualization/types/SimpleTable/PagedTable.tsx
Closes #5239  
- Instead of using old and incorrect values for the header and row heights of the SimpleTable, calculate them.
- This allows SimpleTable to make all rows visible without relying on vertical scrolling.
- **_There must be enough vertical space to fit at least 25% of the height of the next row for that row to render._**
https://user-images.githubusercontent.com/10736577/181658050-05cc838a-e5a1-4823-95e4-89a8c8eaeb32.mp4
> fix: calculate the correct heights for the header and rows in SimpleTable

- cypress/e2e/shared/firstmile.tests.ts
- cypress/e2e/shared/influxCLI.test.ts
- src/homepageExperience/containers/HomepageContainer.tsx
- src/homepageExperience/containers/PythonWizard.tsx
- src/homepageExperience/utils.ts
Closes #4776
- Added e2e tests for the CLI onboarding flow and updated the firstMile e2e tests, now both use regex for navigation to avoid flakiness. 
- Added test ids to the next/previous buttons on the python flow. 
- Also updated the spacing on the names for the subnav on the onboarding wizards.
> test: e2e testing for CLI and firstMile

- src/identity/components/GlobalHeader/GlobalHeader.tsx
- src/identity/quartzOrganizations/actions/thunks/index.ts
Part of [#4049](https://github.com/influxdata/ui/issues/4049)
UI PR [#5197](https://github.com/influxdata/ui/pull/5197) added API layer support for new backend routes that can (1) retrieve the orgs associated with any given account id and (2) set the default org for any given account. 
This PR makes corresponding updates to the quartzOrganizations thunks to use these new routes, as the old ones will be deprecated. The new user profile page is based on these updates.
This PR also improves error handling in the thunk for setting a new default org, distinguishing for reporting purposes whether the failure resulted from a state management problem or a network error. 
> feat: sync quartzOrganizations thunks to new API layer for new quartz organizations routes

- src/identity/components/GlobalHeader/GlobalHeaderDropdown/index.tsx
Part of [UI #4049](https://github.com/influxdata/ui/issues/4049)
The multi-org figma uses the same design for the globalheader (which has a menu menu, and typeahead sub-menu) as for the dropdown typeahead on the user profile page (which is just the typeahead submenu). This tweaks the globalheader by adding an optional property `typeAheadOnly`, which will cause only the submenu to render.
With `typeAheadOnly` not set (or `false`), the main menu renders. Here's an example from GlobalHeader.
With `typeAheadOnly` set to `true`, main menu doesn't render, and goes straight to typeahead, to be used on the user profile page.
> chore: allow globalheader to serve typeahead independently

- src/dataExplorer/components/FluxQueryBuilder.scss
- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/visualization/types/SimpleTable/PagedTable.tsx
Closes #5256    
This guy:
And this guy:
should be wrapped in a flexbox. This fixes the issue of the hidden navigation in SimpleTable for New Data Explorer.
BEFORE: hidden navigation
AFTER: all fixed
https://user-images.githubusercontent.com/10736577/182278279-7ace3b11-fdbd-482a-9e67-eac017f9195b.mp4
> fix: wraps page elements in a flexbox to give SimpleTable correct height

- src/shared/containers/GetFlags.tsx
- src/shared/selectors/flags.ts
Connects #5234 
Using reselect, memoize the `activeFlags` selector.
| Page                   | GetFlags.tsx Render Count |
|------------------------|---------------------------|
| Homepage               | 25                        |
| Dashboard With 4 Cells | 45                        |
| Page                   | GetFlags.tsx Render Count |
|------------------------|---------------------------|
| Homepage               | 3                         |
| Dashboard With 4 Cells | 5                         |
Homepage: 25 => 3
Dashboard: 45 => 5
> perf: memoize flag selector using reselect

- src/dashboards/components/dashboard_index/DashboardCard.tsx
Closes https://github.com/influxdata/ui/issues/5263
- When deleting a dashboard, only notify that a pinned dashboard has been deleted if that dashboard was actually pinned
- Fix notification text to say dashboard, not task
- ~[] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)~
> fix(dashboards): only notify when a pinned item is actually deleted

- src/writeData/subscriptions/components/BrokerFormContent.tsx
- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/476
Optional parameter chaining was happening without the use of `?` thus resulting in an error.
Subscription details page should be loading fine.
- [] Documentation updated or issue created (provide link to issue/PR)
> fix: fix access of optional parameter issue

- cypress/e2e/cloud/billing.test.ts
- cypress/e2e/cloud/zuoraOutage.test.ts
- package.json
- src/billing/components/PayAsYouGo/PlanTypePanel.tsx
In a multi-org/account world, instead of displaying the current organization's region. We have opted to remove the region altogether.
I have to update the OpenAPI repo to remove the `region` from `BillingInfo`
> chore(billing): Remove Region from Billing Info

- src/homepageExperience/components/steps/cli/InitializeClient.tsx
- src/homepageExperience/containers/CliWizard.tsx
Closes #5177 
Since `InitializeClient` file is only being used by CLI Wizard, there is no need to pass `cliWizard` as a prop. The event name should simply be hardcoded. 
The rest of the component mentioned in the ticked linked above (`Overview` and `Finish` ) are being consumed by python, go, and node wizard. Therefore, event names have to be passed as prop. 
> chore(cliWizard): hardcode cliWizard as event name

- cypress/e2e/cloud/subscriptions.test.ts
- src/types/subscriptions.ts
- src/writeData/subscriptions/context/subscription.create.tsx
- src/writeData/subscriptions/context/subscription.update.tsx
Closes related: https://github.com/influxdata/data-acquisition/issues/317
qos is no longer part of the request
> fix: remove qos

- package.json
- src/identity/apis/auth.ts
Closes #5183 
This ticket removes `updateDefaultQuartzOrg` (`PUT` /quartz/orgs/default ) and `fetchQuartzOrgs` (`GET` /quartz/orgs) from the UI's API layer, because they were removed from quartz and openAPI. See [/quartz/orgs/](https://github.com/influxdata/quartz/pull/6651), [/quartz/orgs/default](https://github.com/influxdata/quartz/pull/6650).
These routes are replaced in the UI API layer by `fetchOrgsByAccountID` (/quartz/accounts/:accountId/orgs) and `updateDefaultOrgByAccountID` (/quartz/accounts/:accountId/orgs/default).
> chore: remove old quartz routes for getting orgs, setting default orgs

- cypress/e2e/cloud/flows.test.ts
Closes #5279 
Cloud's Flows test fails with `Expected to find content: 'Flowbooks' within the element` error.
Issue is coming from cypress adding text to an already populated input field. And later, when it tries to find this new text on the page, it doesn't exist. 
To fix this, clear the input field first before adding new text.
> test(flows): clear input before typing

- package.json
- yarn.lock
Closes #5276  
FIXED, ascending:
FIXED, descending:
> fix: updates Giraffe to use the correct "caret down" icon hex value

- src/dataExplorer/components/Results.scss
Closes #5285 
This PR adds dark background to the table and graph to new data explorer results. 
> feat: add dark background to Results table and graph

- src/shared/containers/GetOrganizations.tsx
Closes https://github.com/influxdata/ui/issues/5290
`/quartz/identity` was being called multiple times by the `GetOrganizations` component. The HTTP response on subsequent calls was a 304, meaning the browser has cached the response and is working from the cache. While this is good because we're not using a ton of HTTP resources, the response from the API still updated redux state, which causes re-renders.
The issue was that the call to `getIdentityThunk` was only checking that `quartzMe.status` isn't `NotStarted`. The fix is to make it also check that `me.identity.status` is `NotStarted`. When the `quartzIdentity` flag is true, `quartzMe.status` isn't updated from `NotStarted` to `Done` until after several re-renders of `GetOrganizations`. Within that time, `getIdentityThunk` is called …
> fix(GetOrganizations): check quartzIdentityStatus before calling getQuartzIdentityThunk

- src/languageSupport/languages/flux/lsp/worker/utils.ts
Closes #5073 
We have JSON.parse() errors in the console. It's because we are not handling the use case of no response sent from the LSP.
> fix(5073): enable handling of empty LSP responses

- src/identity/components/GlobalHeader/AccountDropdown.tsx
- src/identity/components/GlobalHeader/OrgDropdown.tsx
Closes #5293
Switch-account in GlobalHeader was not working because the URL the user needs to visit to change accounts should be `${CLOUD_URL}/accounts/:accountId` (not the current URL that included the org id - like `/orgs/:orgId/accounts/:accountId`. We can be confident this works effectively, since this exact URL is used on the switch account page (which works).   
The switch orgs URL should be similarly updated to `$CLOUD_URL/orgs/:orgId`.
> fix: correct globalheader switch-account URL.

- package.json
- yarn.lock
Part of https://github.com/influxdata/ui/issues/3650
<a href="https://imgflip.com/i/6ox1ar"><img src="https://i.imgflip.com/6ox1ar.jpg" title="made at imgflip.com"/></a>
> chore: update Giraffe to allow Safari users to select text in SimpleTable

- package.json
- src/identity/components/GlobalHeader/GlobalHeader.tsx
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderDropdown.scss
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/index.tsx
- src/identity/components/GlobalHeader/UserPopoverStyles.scss
- yarn.lock
Closes https://github.com/influxdata/ui/issues/5284
Icons are out of alignment. 
After: 
Also fixes the hover styles for the avatar menu.
Note: we can not use clockface component to fix the hover style for the User Avatar because the styles vary a lot and its easier to override the css through the current class names instead.
> fix(multi-org): align dropdown icons and fix user avatar dropdown hover styles

- src/me/components/DocSearchWidget.tsx
Closes #5286 
Adds eventing in homepage for the following links:
- Get Started with Flux
- Explore Metrics
- Build a Dashboard
- Write a Task
- Report a bug
- Community Forum
- Feature Requests
- Request Proof of Concept
> chore(homePage): add eventing for helpful links

- src/dataExplorer/context/fluxQueryBuilder.tsx
Closes #5280 
This PR fixes the bug that measurement selector becomes disabled on page refresh.
https://user-images.githubusercontent.com/14298407/182942026-62726dc3-e63f-41ba-b067-37ef9e603244.mov
https://user-images.githubusercontent.com/14298407/182942036-124e702f-85b5-47e5-ac91-a06c6b4bd4c7.mov
> fix: get measurement list on page refresh

- src/cloud/components/OrgSettings.tsx
- src/identity/actions/thunks/index.ts
- src/organizations/components/OrgProfileTab/index.tsx
- src/shared/containers/GetOrganizations.tsx
While working on reducing re-renders, it became apparent that the call to `getCurrentOrgDetailsThunk` in `GetOrganizations` wasn't currently doing anything and was called later in the component tree. This PR removes the later call and tweaks the call in `GetOrganizations` so that it relies on `org.id`. This has the effect of making call slightly more obvious, and reducing re-renders, since `GetOrganizations` doesn't have to wait on deeper component to populate data.
> chore(identity): tweak getCurrentOrgDetailsThunk signature and when it's called

- src/shared/contexts/query.tsx
Closes #5310 
in addressing some PR comments for #5270, i lost a few return conditions. adding them back here to ensure that options is always populated, even if windowPeriod isn't detected
> fix: always return options

- src/resources/selectors/index.ts
Connects #5234 
Memoize the `getAllOrgs` selector, which is only called from `GetOrganizations` for a modest performance gain. This results in the same number of render calls for `GetOrganizations`, but fewer calls to `getAllOrgs`.
| Function Name    | Number of Calls |
|------------------|-----------------|
| getAllOrgs       | 21              |
| GetOrganizations | 10              |
| Function Name    | Number of Calls |
|------------------|-----------------|
| getAllOrgs       | 4               |
| GetOrganizations | 10              |
> perf(GetOrganizations): memoize getAllOrgs selector

- src/identity/selectors/index.ts
- src/me/selectors/index.ts
- src/shared/containers/GetOrganizations.tsx
Connects #5234
Moves selectors created in `GetOrganizations.tsx` into their own selector files. There probably isn't any performance to be gained from this, but it makes things easier and simpler in general, especially for future work when trying to memoize selectors.
From the react-redux docs:
>When using `useSelector` with an inline selector as shown above, a new instance of the selector is created whenever the component is rendered. This works as long as the selector does not maintain any state.
https://react-redux.js.org/api/hooks
> perf(GetOrganizations): move selector creation to outside of component

- src/visualization/utils/useVisDomainSettings.ts
Closes #5306 
When the time range changes (from user selection), update the graph to show the desired time range.
https://user-images.githubusercontent.com/10736577/183223755-540db649-f4a2-4d18-81dc-d9881298b704.mp4
> fix: refit the graph when the time range changes

- src/visualization/types/SimpleTable/PagedTable.tsx
Closes #5317  
Cap the estimated initial height. This prevents further calculations on ridiculously large heights that wouldn't fit everything on the screen anyways.
> fix: cap the estimated height to the screen height

- src/homepageExperience/components/steps/cli/InitializeClient.tsx
Closes #5334
Fixes command in `Initialize Client` step so that it is properly pasted into the terminal without the user having to manually fix the formatting before executing.
> fix: the command format when pasted in terminal

- cypress/e2e/cloud/deepLinks.test.ts
- src/utils/deepLinks.ts
Closes #5221
Adds deeplink and deeplink test for arduino onboarding
> feat: add deep linking to arduino wizard

- src/users/components/InviteListItem.tsx
- src/users/components/UserList.tsx
- src/users/components/UserListItem.tsx
In https://github.com/influxdata/quartz/pull/2486 we removed name from the user list until we had backfilled all names for users. We have completed that work in https://github.com/influxdata/quartz/issues/2389 so this PR adds the names back in.
Part of https://github.com/influxdata/quartz/issues/2389
- [ x ] A PR description, regardless of the triviality of this change, that communicates the value of this PR
- [ x ] [Well-formatted conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) that provide context into the change
- [ x ] Documentation updated or issue created (provide link to issue/PR)
- [ x ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)
- [ x ] Feature flagged, if …
> chore: Add name back to user list

- cypress/e2e/shared/firstmile.tests.ts
- src/homepageExperience/components/steps/go/InitializeClient.tsx
- src/homepageExperience/components/steps/nodejs/InitializeClient.tsx
- src/homepageExperience/components/steps/python/InitializeClient.tsx
- src/homepageExperience/containers/GoWizard.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
Closes #5358
Minor refactor to change `InitalizeClient` => `InitializeClient`.
- Renamed files called `InitalizeClient` => `InitializeClient`
- Renamed components in said files from `InitalizeClient` => `InitializeClient`
- Updated imports that referenced above files to use new component and file name
> fix(firstMile): fix typo - InitalizeClient => InitializeClient

- src/homepageExperience/components/steps/arduino/PrepareIde.tsx
- src/homepageExperience/containers/ArduinoWizard.tsx
- src/homepageExperience/utils.ts
Closes #5355 
Adds `Prepare Arduino IDE` step to the onboarding flow. This step takes users through the steps of adding an arduino board to the arduino ide. Screen shots below:
Updated images:
> feat: add prepare ide step to arduino onboarding

- src/buckets/components/CreateBucketButton.tsx
- src/writeData/components/WriteDataHelperBuckets.tsx
- src/writeData/subscriptions/components/BrokerForm.scss
- src/writeData/subscriptions/components/BrokerForm.tsx
- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
- src/writeData/subscriptions/components/JsonParsingForm.tsx
- src/writeData/subscriptions/components/JsonPathInput.tsx
- src/writeData/subscriptions/components/ParsingForm.tsx
- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/components/StringPatternInput.tsx
- src/writeData/subscriptions/components/SubscriptionForm.tsx
- src/writeData/subscriptions/components/SubscriptionFormContent.tsx
Closes #https://github.com/influxdata/data-acquisition/issues/494 && https://github.com/influxdata/data-acquisition/issues/478
Interim change to disable subscription form for free users to alleviate some confusion.
- makes upgrade button same color as the rest of the app
- disables form elements
- adds optional variables to the shared create bucket component so that we can make it disabled but not require changes elsewhere in the codebase
- fixes placeholder text bug
Before:
https://user-images.githubusercontent.com/38860767/183917553-f72ae38e-5bd2-45ca-a2cb-80991d4b9c47.mov
After:
https://user-images.githubusercontent.com/38860767/183917606-48e0d276-bba4-4d12-9f66-f47ae656b920.mov
changed color of text and fontweight since screenrecording:
Placeholders:
Authors and Reviewer(s), please …
> fix: disable form if not pay as you go or free flag customer

- package.json
- src/types/operator.ts
This updates the Unity Routes to the latest SHA and changes the Operator UI to use the `OperatorUser` type instead of the `User` type.
> feat: Update unity routes and OperatorUser type

- src/homepageExperience/components/steps/cli/ExecuteQuery.tsx
- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
- src/homepageExperience/containers/CliWizard.tsx
Closes #4774 
Adding eventing in following areas: 
- Track if the user clicked the time series video on the overview page
- eventing for the previous and next buttons needs to specify the page on which it was clicked, not just the language.
- Track if a user clicked on the copy/code snippet per step/screen; where applicable
- Track if a user clicks the documentation link per step/screen
> feat(cliWizard): additional eventing for cli

- src/shared/components/CSVExportButton.tsx
Closes #5371
When downloading a CSV of a query built in Data Explorer, when creating the file, the script would insert a space character when replacing `:`. This changes it so that it replaces `:` with `_`
*Previously*:
`2022-08-11_09 09_influxdb_data`
*New*:
`2022-08-11_09_09_influxdb_data`
> fix(CSVExportButton): convert : into _ when downloading a CSV

- src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderTypeAheadMenu.tsx
Connects #5307 
Added some logic to dynamically calculate the height of the dropdown. 
https://user-images.githubusercontent.com/18511823/184192436-90fef23a-ee85-42cb-80f3-709618fa5e24.mov
> fix(TypeAheadDropdown): dropdown hugs the item's list

- src/homepageExperience/components/steps/arduino/InitializeClient.tsx
Closes #5214
Adds `Initialize Client` page to the arduino onboarding wizard. This page allows user to select or create a bucket to use for the tutorial. If the user selects or creates one, the code autopopulates with the bucket name. If the user does not select a bucket, `YOUR_BUCKET` is placed as a place holder. The code also autopopulates with a token, org-id, and host url.
https://user-images.githubusercontent.com/106361125/184224600-15be6717-9ebe-477f-bf81-8dcb7be797bb.mov
> feat: arduino init client page

- src/homepageExperience/components/steps/cli/InitializeClient.tsx
Closes #5384
Users do not have to create a bucket using the CLI if they have selected or created one using the bucket list above the code snippet, so I added a small sentence telling them to skip that step if they already selected a bucket.
> chore: tells users to skip cli bucket creation

- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
Closes #5377
Adds a note telling users that if they have an M chip, they will need Rosetta before continuing.
> feat: notify users with M chip to install rosetta

- src/homepageExperience/components/steps/cli/ExecuteAggregateQuery.tsx
- src/homepageExperience/components/steps/cli/ExecuteQuery.tsx
- src/homepageExperience/components/steps/cli/InitializeClient.tsx
- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
- src/homepageExperience/components/steps/cli/WriteData.tsx
- src/utils/crossPlatform.test.ts
- src/utils/crossPlatform.ts
Closes #5390
Displays commands based on which OS the user is using. Now windows commands are correct and the directions are more clear. More work needs to be done to figure out why the queries are not identifying the buckets in windows.
> fix: fixes most of the windows commands

- cypress/e2e/shared/dashboardsVariables.test.ts
- src/variables/components/TypeAheadVariableDropdown.tsx
Closes https://github.com/influxdata/ui/issues/5347
I tried all sorts of ways to make it dynamic, from `width: auto`, `fit-content` etc and it won't work. this could be because of how clockface is doing styles. this was the best way to do it:
`calculate the length of the string * 8 (a character 8px is a close enough approximation) + 95 (account for paddings)`
https://user-images.githubusercontent.com/18511823/183755257-2dff5495-15da-4e56-9a4f-51662cd5d51a.mov
> fix(TypeAheadVariableDropdown): dynamic width for input bar

- src/accounts/AccountTabs.tsx
- src/organizations/components/OrgNavigation.tsx
- src/pageLayout/components/UserWidget.tsx
Closes #5309 
pr reorders 
- Account page from Billing > Setting to Setting > Billing.
- Organization page from Members > Settings > Usage to Settings > Members > Usage. 
- User Widget items to lead with Settings page
https://user-images.githubusercontent.com/66275100/184663659-7c493ff8-94f4-4cb2-b687-fbf0a9d2ba5b.mov
> fix(AccountTabs): reorder tabs in account and org page

- src/homepageExperience/components/steps/arduino/InstallDependencies.tsx
Closes #5212 
Adds Install Dependencies page to Arduino onboarding.
> feat: add install dependencies page for Arduino wizard

- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
Closes #5395
Adds link to homebrew so users can install it if necessary.
> feat: add homebrew link to cli onboarding

- src/homepageExperience/components/steps/arduino/InitializeClient.tsx
Closes #5405
Adds more context to the `Initialize Client` page of the arduino onboarding wizard to give users more information and direction. 
> chore: add more context to init client

- src/shared/components/inlineLabels/InlineLabels.tsx
Closes #5439 
Pr adds a check in `mstp` in order to prevent null value `props.selectedLabelIDs` from being used in selector. 
Before fix: 
https://user-images.githubusercontent.com/66275100/185191639-e0407a4d-130b-499f-96d2-21a7d66e412d.mov
After fix: 
https://user-images.githubusercontent.com/66275100/185191722-7b2d2ece-2504-4edf-bdc1-b98ad12c8b93.mov
> fix(inLineLabels): handle null prop in selector

- src/homepageExperience/components/HomepageExperience.scss
Closes #5424
Makes all `h1` headers have a font weight of 600 in the onboarding wizards, so it matches the `h2` headers.
Before:
After:
> style: change font weight of h1 headers

- src/buckets/actions/thunks.ts
- src/shared/components/inlineLabels/InlineLabels.tsx
see #5439 
Due to recent changes made to the labels API, `getBucketsLabels` returns  `null` instead of `[]` for buckets with no labels. This response is incongruent with what the UI expects and causes the crash mentioned in the ticket linked. 
Pr adds a guard forcing `labels` to be an empty array when the api responds with a `null`. 
after fix: 
https://user-images.githubusercontent.com/66275100/185214225-7ccec46f-3b59-40bc-81b0-d6ca574ccdd4.mov
> fix(updateBucket): set labels to [] if reponse is null

- src/homepageExperience/components/steps/arduino/ExecuteQuery.tsx
Closes #5216 
Adds executeQuery page to arduino onboarding. 
Updated Screenshots:
> feat: add executeQuery page for arduino wizard

- src/homepageExperience/components/steps/arduino/ExecuteAggregateQuery.tsx
Closes #5217 
Adds ExecuteAggregateQuery page for the Arduino onboarding page.
> feat: add executeAggregateQuery page for arduino onboarding

- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
Closes #5435
Automatically detects which OS the suer is using and displays the correct install dependencies tab accordingly. 
Enhancement was suggested by @wojciechka, thanks!
> feat: auto selects users os

- cypress/e2e/cloud/globalHeader.ts
- src/identity/components/GlobalHeader/AccountDropdown.tsx
- src/identity/components/GlobalHeader/GlobalHeader.tsx
- src/identity/components/GlobalHeader/OrgDropdown.tsx
Closes #4053 
Adds e2e tests for the 'change account' and 'change org' dropdowns in the multi-org phase 1 global header. The remaining e2e tests for multi-org were completed in #5386 and #5381. 
1. Don't render the header if the server fails to provide the user's account/org data.
3. Account Dropdown
- Navigate to the Settings page
- Navigate to the Billing page
- Change the current account
4. Organization Dropdown
- Navigate to the Settings page
- Navigate to the Members page
- Navigate to the Usage page
- Change the current organization
The hurdle in testing global header is that the URLs targeted by the dropdown include IDPE-generated org IDs. In prod, the IDPE org id and the quartz org ID are the same. In remocal and CI, they are not, because quartz-mock serves static org ids.
This PR …
> feat: add e2e tests for change-account and change-org dropdowns

- cypress/e2e/shared/influxCLI.test.ts
- src/homepageExperience/containers/CliWizard.test.tsx
- src/homepageExperience/utils.ts
Closes #5441 
Changes the Finished! text to just Finish on both the Arduino and CLI pages.
> chore: changing finished to finish on CLI and arduino wizards

- package.json
- yarn.lock
Bring this release in: https://github.com/influxdata/clockface/releases/tag/v6.1.1
This helps with the TypeAhead dropdown selecting all text in the input upon click, for safari.
> chore: update clockface to 6.1.1

- src/homepageExperience/components/steps/cli/InstallDependencies.tsx
Closes #5453
Updates the `wget` links to be correct for linux.
> fix: update linux install link

- src/homepageExperience/components/steps/arduino/WriteData.tsx
- src/homepageExperience/containers/ArduinoWizard.tsx
Closes #5215 
Adds writeData pages to the Arduino onboarding.
> feat: add writeData pages to arduino onboarding

- cypress/e2e/cloud/about.test.ts
- cypress/e2e/cloud/deepLinks.test.ts
- cypress/e2e/cloud/globalHeader.ts
- cypress/e2e/cloud/users.test.ts
- cypress/e2e/shared/about.test.ts
- cypress/e2e/shared/nav.test.ts
- src/checkout/SuccessOverlay.tsx
- src/identity/components/GlobalHeader/OrgDropdown.tsx
- src/organizations/components/OrgNavigation.tsx
- src/organizations/components/OrgProfileTab/CopyableLabeledData.tsx
- src/organizations/components/OrgProfileTab/DeletePanel.tsx
- src/organizations/components/RenameOrgForm.tsx
- src/organizations/containers/OrgProfilePage.tsx
- src/pageLayout/components/UserWidget.tsx
- src/shared/constants/index.ts
- src/shared/containers/SetOrg.tsx
- src/utils/deepLinks.ts
Closes #5396 
Inside organization page, navigating to Settings tab takes user to `/orgs/:orgId/org-settings` 
navigating to Members tab takes user to `/orgs/:orgId/members`
Pr adds new paths `/org-settings` and `/members` inside `SetOrg.tsx` and updates links to point to the newly added routes. 
For now, old routes `/about` and `/users` will remain in the codebase to maintain backwards compatibility. 
https://user-images.githubusercontent.com/66275100/184909555-8ad967bd-5d32-46b7-84f0-a057e222c470.mov
> feat(SetOrg): update url to match page title

- src/homepageExperience/containers/HomepageContainer.tsx
Closes https://github.com/influxdata/ui/issues/5440
I put a flag check because we want the View More option when we publish the Arduino changes. (i.e Turn on the onboardArduino flag.) without it, there would be a blank space instead of the MORE tile and looks weird.
https://user-images.githubusercontent.com/18511823/185492586-1ff24b8d-fa3a-4caa-ab9e-d6c4717097c9.mov
> feat: FirstMile tiles "view more"

- src/variables/selectors/index.tsx
- src/variables/utils/getWindowVars.ts
- src/visualization/utils/useVisDomainSettings.ts
Closes #5354  
- Change the `timeRangeStart` variable to a `DurationLiteral` if the type of timeRange selected by the user is a duration
- Handle the case of `Infinity` when normalizing
Here is a video showing the user selecting both a duration (Last 1hr) and a custom time range successfully using the adaptive zoom feature
https://user-images.githubusercontent.com/10736577/185463821-f7eec55c-a019-4877-b870-211df37744d5.mp4
> feat: use DurationLiteral or DateTimeLiteral depending on the type of timeRange

- src/homepageExperience/components/steps/Finish.tsx
Closes [#5443](https://github.com/influxdata/ui/issues/5443)
We don't want to show the sample app and the boilerplate for MVP of arduino onboarding. We hide it.
https://user-images.githubusercontent.com/18511823/185498454-33dffb7e-2044-436e-ac80-7d9694fc454d.mov
> fix(firstMile): no sample app or boilerplate app for arduino onboarding

- src/me/actions/thunks/index.ts
- src/shared/containers/GetOrganizations.tsx
Closes https://github.com/influxdata/ui/issues/5472
Rudderstack calls `identify` with user id, user email address, and org id. The call to `identify` was using an `org` variable that didn't exist under certain circumstances, and was crashing the application. Where the call is in the flow of the application depends on `org.id` existing in local state. If it doesn't it casues the black screen shown in the referenced issue.
> fix(rudderstack): move identify call later where org.id will exist

- src/identity/components/GlobalHeader/UserPopoverStyles.scss
Closes https://github.com/influxdata/ui/issues/5480
Using visibility instead of opacity fixes the issue where the hidden element is still clickable. 
https://user-images.githubusercontent.com/18511823/185682604-9508e304-f13e-4664-a396-0b73647337c8.mov
> fix(multi-org): Avatar Profile popover hide via visibility

- cypress/e2e/cloud/billing.test.ts
- cypress/e2e/cloud/usage.test.ts
- cypress/e2e/cloud/zuoraOutage.test.ts
- src/accounts/AccountHeader.tsx
- src/accounts/AccountTabContainer.tsx
- src/billing/components/BillingPage.tsx
- src/dashboards/components/dashboard_index/DashboardsIndex.tsx
- src/homepageExperience/containers/HomepageContainer.tsx
- src/operator/AppPageHeader.tsx
- src/organizations/components/OrgHeader.tsx
- src/organizations/components/OrgTabbedPage.tsx
- src/settings/components/LoadDataHeader.tsx
- src/settings/components/LoadDataTabbedPage.tsx
- src/settings/components/SettingsHeader.tsx
- src/settings/components/SettingsTabbedPage.tsx
- src/tasks/components/TaskRunsPage.tsx
- src/tasks/components/TasksHeader.tsx
- src/tasks/containers/TasksPage.tsx
- src/writeData/components/fileUploads/UploadDataDetailsView.tsx
- src/writeData/containers/ClientLibrariesPage.tsx
- src/writeData/containers/TelegrafPluginsPage.tsx
Closes https://github.com/influxdata/ui/issues/5456
For consistency across all pages, this sets a full width for all pages. The effect of this PR will only be visible on larger screens.
The Notebooks section still needs some work. It has some inconsistencies causing it to distort the UI. I'll put a separate PR to address that section.
Some examples:
Without: 
With: 
The consistent page layout just looks better.
> chore: full width pages for everything but Notebooks

- cypress/e2e/shared/labels.test.ts
- src/labels/components/LabelOverlayForm.tsx
- src/labels/constants/index.ts
- src/shared/components/inlineLabels/InlineLabelPopover.tsx
Closes: https://github.com/influxdata/ui/issues/5482
1. Made a constant that contains the label name max length.
2. In the test, we reduce the label name length to less than 30 chars
3. Also adds a test case to make sure you cant type a name more than 30 chars.
> test: fix labels test to limit input name to 30 characters

- src/visualization/types/Graph/view.tsx
- src/visualization/utils/useZoomQuery.ts
Closes #5319  
- allows adaptive zoom to be used in Notebooks by getting the right context to access the query
- allows adaptive zoom to be used in New Data Explorer by getting the right context to access the query
Here are the 3 different primary ways to visualize a graph and the adaptive zoom working in all of them:
https://user-images.githubusercontent.com/10736577/185716360-d560f815-2ed9-4424-95a5-ed37081135f9.mp4
> fix: centralize the getter for the query needed by adaptive zoom

- cypress/e2e/cloud/deepLinks.test.ts
- src/utils/deepLinks.ts
Closes #5483
Adds two new deep links
- mqtt subscriptions: `/me/load-data/subscriptions -> /orgs/:orgId/load-data/subscriptions`
- mqtt create flow:  `/me/load-data/subscriptions/create -> orgs/:orgId/load-data/subscriptions/create`
> feat(deepLinks): add deep links for mqtt subscriptions index and creation

- cypress/e2e/shared/dashboardsVariables.test.ts
- cypress/e2e/shared/simpleTable.test.ts
- src/App.tsx
- src/MultiOrgOverrideStyles.scss
- src/homepageExperience/containers/HomepageContainer.tsx
Closes [#5431](https://github.com/influxdata/ui/issues/5431)
Conditionally imports Override Styles based on toggle state of `multiOrg` flag.
Flag off: 
Flag on: 
> feat(multi-org): smaller height for page headers with multi-org flag on

- src/accounts/AccountPage.tsx
Closes #5475 
This PR hides the 'switch account' button in the old 'switch account' page when the user has access to the switch-account functionality provided by the 'global header' in multi-org phase 1.
https://user-images.githubusercontent.com/91283923/185956941-7f32f783-7d9f-4808-b16a-a863cc56f26f.mov
> chore: hide switch account button in old account page when multiOrg is enabled

- cypress/e2e/cloud/userProfile.test.ts
- cypress/fixtures/multiOrgAccounts1.json
- cypress/fixtures/multiOrgOrgs1.json
Connects #5498 
The user profile tests weren't passing CI, because the tests run in parallel and were simultaneously updating default orgs on the quartz-mock backend out of sync with each other. 
This PR resolves that issue by intercepting the network requests with a fixture. In also slightly increases the initial wait time before running all tests, to avoid performance issues during slow CI runs.
[The test now passes 20x runs of Chrome and 20x runs of Firefox](https://app.circleci.com/pipelines/github/influxdata/ui/15749/workflows/d42f20fc-9fdd-41b7-aeb1-01424800525e/jobs/90529/steps)
> fix: refactor user profile test to avoid flake

- src/dataExplorer/components/ResultsPane.tsx
- src/timeMachine/components/SubmitQueryButton.tsx
Close #5495
This PR adds the disabled and hover tooltip to "Run" button when the user has not selected a measurement. The disabled tooltip text is suggested by Julia in [figma design](https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1719%3A71011)
https://user-images.githubusercontent.com/14298407/186033200-dee98792-5bd6-435c-a327-6fbfb282e541.mov
> feat(schemaBrowser): add disabled and hover tooltip to "Run" button when no selected measurement

- src/dataExplorer/components/Schema.scss
- src/dataExplorer/components/Schema.tsx
- src/dataExplorer/components/SchemaBrowserHeading.tsx
- src/dataExplorer/components/SelectorTitle.tsx
- src/dataExplorer/context/fluxQueryBuilder.tsx
Closes #5501
This PR adds a toggle button in schema browser for controlling the sync of query composition between schema browser and the text editor.
https://user-images.githubusercontent.com/14298407/186187033-74f62768-a8cb-4c84-8a4f-6d89b99bfda3.mov
> feat(schemaBrowser): add "Flux Sync" toggle button

- src/homepageExperience/containers/ArduinoWizard.tsx
- src/homepageExperience/containers/CliWizard.tsx
Closes #5449
Allowing the next button to be used in the aggregate query page.
> chore: fixing the next button in arduino wizard

- src/homepageExperience/containers/CliWizard.tsx
- src/homepageExperience/containers/GoWizard.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
Closes #5469 
Here we plan on changing all wizards to have the same eventing for the next, previous, and nav button clicks. Previously, the Go, Nodejs, and Python wizards all had less descriptive (number of page rather than name) eventing for the next and previous functions and no eventing for the nav clicks. The CLI had a differently structured eventing that was incorrect and led to inconsistencies because of the asynchronous nature of the setState function. This PR plans on standardizing all of them to be the same as the newly updated Arduino eventing.
> chore: normalizing eventing between all wizard next and previous navigation

- src/identity/components/GlobalHeader/GlobalHeader.tsx
Turning on this FF on in staging shows that some staging environments are hitting an error in globalheader's conditional logic for whether (a) the dropdowns and (b) the avatar should be loaded. 
This can be resolved by adding an optional chaining operator.
Not sure of root cause yet, as this data is provided by default redux states, but could be that environments without quartz are overwriting the value with a null, making the property on the original default object inaccessible.
> fix: add guards to conditional loading in globalheader

- cypress/e2e/cloud/globalHeader.test.ts
- cypress/fixtures/multiOrgIdentity.json
- cypress/fixtures/orgDetails.json
Closes #5498 
Refactors global header e2e test to resolve flakiness, particularly in Firefox.
The primary issue is that Firefox doesn't play well with the work-around for syncing quartz IDs to IDPE IDs that is necessary to use the URIs targeted by global header. I.e., intercepting requests to quartz-mock and replacing the returned org id with the org ID from IDPE.  That works fine in Chrome, but Firefox often generates a network error. Changing the headers and CORS mode doesn't fix it, and we can't change web security settings for Firefox. 
Firefox also doesn't play nice when attempting to intercept calls to `/logout` or the quartz redirects for changing accounts or orgs.
The fix proposed here is to use fixtures mimicking quartz and injecting the IDPE org id into that, instead of trying …
> fix: refactor global header e2e test

- src/writeData/subscriptions/components/CertificateInput.tsx
A flag `subscriptionsCertificateSupport` already exists in `idpe`. So, it doesn't make sense to add a new feature flag for the same feature. Changing the name of the flag from `enableCertificateSupport` to `subscriptionsCertificateSupport`.
> chore: change cert support flag name

- package.json
- src/flows/pipes/Notification/Threshold.tsx
- src/flows/pipes/Schedule/History.tsx
- src/visualization/components/internal/StaticLegend.tsx
- yarn.lock
Connects #5532
Upgrades eslint to `7.32.0`
Fixes a couple of new errors found by this new version. All errors were due to naming collisoins where a React component was named the same as an imported type.
> chore(dependencies): upgrade eslint to v7.32.0

- src/identity/components/GlobalHeader/GlobalHeader.tsx
Closes #5526
This fixes a bug where globalheader could throw minified react error #152 - `Nothing was returned from render.` This was identified in Electron environments in staging, but I'm able to reproduce it elsewhere by manually setting values associated with the user's identity to `undefined`.
The cause of the issue is that the expressions used for checking whether the data associated with the header and user avatar weren't type cast to `boolean`.
When at least one element in _both_ the guards against loading the avatar and dropdown was `undefined` - for example, when the optional chaining operator cast the value to `undefined` because the property didn't exist yet - `shouldLoadGlobalHeader` also evaluated to undefined, a value that the functional component can't return, throwing an …
> fix: force null return from global header until all values loaded

- cypress/e2e/shared/simpleTable.test.ts
- src/App.tsx
- src/MultiOrgOverrideStyles.scss
Closes https://github.com/influxdata/ui/issues/5431
Instead of conditionally importing the CSS file, we're conditionally _applying_ the styles to the header. This is much more reliable way of doing it. 
Solution credit: @hoorayimhelping 
https://user-images.githubusercontent.com/18511823/186476969-f181f685-73ab-4011-a3f7-f327eb68a2b5.mov
> fix(multi-org): conditionally applying CSS to page header correctly

- src/dataExplorer/components/SchemaBrowserHeading.tsx
Closes #5536 
This PR adds the disable logic and hover tooltip to the "Flux Sync" toggle. 
This change is behind the feature flag `schemaComposition`.
https://user-images.githubusercontent.com/14298407/186526032-6a599b2f-f97d-457d-9737-d6d73e88898b.mov
> feat(schemaBrowser): add disable logic to "Flux Sync" toggle

- src/identity/components/GlobalHeader/GlobalHeader.tsx
- src/identity/components/GlobalHeader/IdentityUserAvatar.tsx
Closes #5520 
Connects #5444, #5494 
If a user doesn't have a `firstName` or `lastName` (`null` or `undefined`), guards around the profile avatar prevent it from loading. We want the avatar to load and render a default image if the user doesn't have a name.
This PR removes the requirement that `firstName` and `lastName` be set before the user avatar renders. If `firstName` or `lastName` are `null` or `undefined`, the values will be set to empty `string`. Here is the new behavior:
- Both names: image using the user's initials is rendered
- Only one name: image using the one initial is rendered
- No names: default image renders.
User Has First and Last Name
--
One Name Null
--
One Name Undefined
--
Both Names Null
--
Both Names Undefined
--
Authors and Reviewer(s), please verify the …
> fix: user avatar renders a default avatar for users with no name

- src/dataExplorer/components/DataExplorerPage.tsx
- src/dataExplorer/components/resources/TemplatePage.tsx
- src/dataExplorer/components/resources/index.ts
- src/dataExplorer/context/persistance.tsx
- src/types/resources.ts
part of the split up of the giant save/load pr (found here: https://github.com/influxdata/ui/pull/5540/files).
In this chapter, we add a generic `/from` templating system for the new data explorer that'll allow us to load any registered resource into the new flux editor and save it out again.
> feat: adding generic resource interface

- package.json
- yarn.lock
Update clockface version to 6.3.0 release https://github.com/influxdata/clockface/releases/tag/v6.3.0
This brings in new Sync icon and the collapse functionality in the Draggable Resizer Component.
> chore: update clockface to 6.3.0

- src/languageSupport/languages/flux/lsp/connection.ts
- src/shared/components/FluxMonacoEditor.scss
- src/shared/components/FluxMonacoEditor.tsx
Closes #5544 
This PR updates the styling of the schema composition code block when turning "Flux Sync" toggle on and off.
This change is behind the feature flag `schemaComposition`
> style: update styling of schema composition code block

- src/dataExplorer/components/SchemaBrowserHeading.tsx
- src/dataExplorer/context/fluxQueryBuilder.tsx
- src/dataExplorer/context/persistance.tsx
- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/lsp/utils.ts
- src/shared/contexts/editor/index.tsx
Fix for #5342 
Closes #5539 
https://user-images.githubusercontent.com/10232835/186798228-77e5bf25-d45b-4d2a-817b-f0c8ecc76711.mp4
* on page reload with existing schema composition:
1. LspConnectionManager detects the schema, and sends jsonrpc to init the composition
2. editor has not yet sent the `didOpen` for the file
3. the schema composition init will fail, on no File being found yet.
* on re-syncing, (or reload) with existing schema composition:
1. all the executeCommands get sent to the Lsp too fast.
2. Lsp spec assumes atomic changes, without a reliance on order.
*composition looks at most recent text....and then make the applyEdit.
* so our next read (of the current text), must occur after the previous edit has been applied
* need to resize the `clickableInvisibleDiv` each time we …
> fix(5342): with flux-LSP composition released, test and debug coordination (UI vs LSP vs editor)

- src/dataExplorer/components/SchemaBrowserHeading.tsx
- src/shared/components/FluxMonacoEditor.tsx
This PR updates the "Flux Sync" icon to the new sync icon in clockface
This change is behind the feature flag `schemaComposition`
> chore(schemBrowser): update to clockface sync icon

- src/dataExplorer/components/resources/index.ts
- src/dataExplorer/components/resources/types/script/editor.tsx
- src/dataExplorer/components/resources/types/script/index.ts
this is part of splitting up the big PR at https://github.com/influxdata/ui/pull/5540/files in order to make the review cycle more digestible. this piece adds the generic interface for loading and saving scripts into the persistance layer of the new data explorer
> feat: add generic script loader

- package.json
This updates the SHA for the openapi spec to include the new `GET /clusters` endpoint.
> feat: Update SHA for new GET clusters endpoint

- src/homepageExperience/components/steps/arduino/InitializeClient.tsx
Closes #5488 
Fixes eslint warnings on Arduino page. Its also important to note with this PR, especially having it have been done previously, that we have to be careful while reusing/copy and pasting code from other components that they are completely bug free. This is an extremely easy way to multiply small bugs into bigger problems. All homepage lint warnings had previously been fixed but now came back up because of code reuse.
Showing that the behaviour is still as expected:
https://user-images.githubusercontent.com/13280708/186968526-c5dcb386-604d-4f2a-aa4a-5fcf3c67080c.mov
> chore: fixing linter warnings in arduino

- src/pageLayout/components/UserWidget.tsx
- src/pageLayout/containers/TreeNav.tsx
Closes #5564 
In cloud environments, removes the user-widget, and user-specific account and org links, from the lefthand nav bar when multi-org is `true`. The user will already have access to the same links through the multi-org phase 1 header. 
- These links will only fail to appear when the `multiOrg` flag is `true`. When `multiOrg` is false, the old left-hand links will be displayed. 
- Toggling the flag immediately changes the state of the navbar without a hard refresh, as the change in flags state results in a different prop value for `<TreeNav />`. 
- No changes will occur in non-cloud environments. 
Old structure of `<TreeNav />` is in blue; new structure includes the path shown in green.
https://user-images.githubusercontent.com/91283923/187227071-fbda7d14-e8c9-4faa-b389-0873a988b8 …
> chore: remove user banner when multiOrg is enabled

- src/shared/components/FluxMonacoEditor.scss
This PR updates the sync icon color. If sync is turned off the icon should be gray, not blue.
This change is behind the feature flag `schemaComposition`
> style: change sync icon to gray when sync is off

- package.json
- yarn.lock
Updating `jspdf` to v2.5.1 in this PR.
Customer shouldn't see any impact of this change.
> chore: update jspdf package to 2.5.1

- package.json
- yarn.lock
> chore: update webpack cli to 4.10.0

- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/resources/TemplatePage.tsx
- src/dataExplorer/context/persistance.tsx
Part of #5575.
(Line item: turn on sync by default.)
Fixes error introduced here:
https://github.com/influxdata/ui/commit/34920a77d765a939edb5e292a6827c481715f137#diff-dc45f9353f4973afb51830453f2b9afd104ab1b0057ab80ba84b9f4cf2b09f7d
* single line change, to make the default for sync be true
* rest of lines is to fix this found bug:
* introduced because 2 different  groups pushing code (without tests yet)
* Add back in schema resetting behavior for new script, which got accidentally removed [with this commit/merge](https://github.com/influxdata/ui/commit/34920a77d765a939edb5e292a6827c481715f137#diff-dc45f9353f4973afb51830453f2b9afd104ab1b0057ab80ba84b9f4cf2b09f7d).
> fix: schema composition sync and resetting

- src/visualization/components/internal/AdaptiveZoomOption.tsx
Closes #4990 
Updates the informational tooltip for adaptive zoom. It actually _can_ use custom window periods.
https://user-images.githubusercontent.com/10736577/187309436-72488bc1-8763-4be6-9b78-7ccf5b412021.mp4
> chore: update adaptive zoom informational tooltip to describe actual behavior

- src/dataExplorer/components/Schema.scss
- src/dataExplorer/components/SchemaBrowserHeading.tsx
Related to #5573 
This PR updates the styling of "Flux Sync" toggle when it is disabled. 
This change is behind the feature flag `schemaComposition`
https://user-images.githubusercontent.com/14298407/187297893-f4185009-24e7-40dd-9a85-85aaa7c98f99.mov
> fix: add disable style on "Flux Sync" label

- src/dataExplorer/components/DataExplorerPage.tsx
Closes #5515 
This PR changes the text "Try New Data Explorer" to "Preview New Script Editor" as requested in the original issue
> chore: change "Try New Data Explorer" to "Preview New Script Editor"

- package.json
- yarn.lock
update `webpack-bundle-analyzer` to 4.6.1
> chore: update webpack bundle analyzer

- src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderDropdown.scss
Closes [#5595](https://github.com/influxdata/ui/issues/5595)
Simple CSS fix, fixes a two things:
1. The extra scrollbar
2. The HR now spans until all the rectangular elements, looks more cohesive.
> fix(multiOrg/dropdown): margins on the horizontal divider

- package.json
- yarn.lock
update `webpack-dev-server` to 4.10.1
> chore: update webpack dev server to 4.10.1

- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/context/persistance.tsx
Closes #5591 
* extend existing `editor.tests.js`: 
* to also cover new Script builder 
* add new Schema Composition tests in `fluxQueryBuilder.test.js`:
* these test how schema composition fits into the rest of the UI
* e.g. schema composition versus the session versus the UI sync versus the "New Script" functionality.
Note: is not the integration (non-cypress) tests we plan to add later, for the UI vs LSP coordination (e.g. middleware etc).
> feat(5591): schema composition cypress tests.

- src/App.tsx
- src/utils/vwo.ts
Closes #5545 
The VWO analytics script has an anti-flicker function that temporarily sets `<body>` opacity to zero using a `<style>` element. The script is behind the `vwoAbTesting` flag, which is currently `false` in prod.
The element is supposed to be removed if the remote VWO script (a) doesn't load, (b) finishes loading, or (c) fails to finish loading after a given time period (default, 2s). As explained in EAR 3553, the VWO script doesn't have sufficient error handling to deal with failures in the script itself, so errors can cause the opacity-zero `<style />` tag to remain on the DOM.
Proposed Changes
--
1. Change the value of the `hide_element` variable in the script from `body` to an empty string. 
This is endorsed by VWO for situations where the anti-flicker script isn't working …
> fix: improve error handling around vwo-script anti-flicker

- src/dataExplorer/components/Schema.tsx
- src/dataExplorer/components/SchemaBrowserHeading.tsx
This PR fixes a bug where `schemaComposition` feature flag wasn't responsive. With the bug, the users have to refresh the page in order to see the feature behind the flag. Now, no need to refresh the page.
https://user-images.githubusercontent.com/14298407/187776906-739f2e6f-7316-4461-815a-65f872d9d888.mov
https://user-images.githubusercontent.com/14298407/187776641-6ac505dc-ae51-4f82-8114-5573c2a8bc78.mov
> fix: make `schemaComposition` feature flag responsive

- src/MultiOrgOverrideStyles.scss
- src/authorizations/components/TokensTab.tsx
- src/buckets/components/BucketsTab.tsx
- src/flows/components/FlowPage.tsx
- src/identity/components/GlobalHeader/GlobalHeaderStyle.scss
- src/identity/components/GlobalHeader/constants/index.ts
Connects #5607  
Closes #5603 
When multi-org is on, the bottom of certain pages is being clipped. The primary cause is that our existing `Page` components and `DapperScrollBars` presume that 100% of the viewport is available for rendering the page. The `GlobalHeader` component is out of `Page`, so we end up with a slight overflow on certain pages beyond the viewport (equal in size to the height of `GlobalHeader`).
Adjusting `Page` size conditionally does not work consistently on all pages due to minor formatting differences, so some custom page-specific adjustments are needed.
This PR resolves the cutoff on all pages on which I've located this problem except for pages using `MonacoEditor`. I'll make that the subject of a separate PR, as it requires more investigation, and need not hold …
> fix: adjust page-specific styles for globalheader

- package.json
- yarn.lock
Closes https://github.com/influxdata/giraffe/issues/799
Points required for shading correctly are no longer dropped.
BEFORE:
AFTER:
> chore: update giraffe to fix band visualization

- src/MultiOrgOverrideStyles.scss
Closes #5594 
This PR reduces top and right margins on top-right notifications because those notifications' slight overlap with the user avatar from multi-org isn't visually appealing.
Ideally we'd apply the style conditionally. But we can't apply conditional styles to the notifications in the UI code using `classNames` without more significant restructuring of the notification code than this change warrants, because the notification container and its `className` properties are created by Clockface using a React Portal that lives in a separate DOM element outside of `React.root`.
Once multi-org is no longer being tweaked, we could consider making this change in clockface for everyone, instead of doing a css override. 
Before:
--
Multi-Org Off
-- …
> fix: adjust top-right notification margins for multi-org

- src/tasks/components/TasksList.tsx
Closes #5632
Tasks page performs a manual re-calculation of page height to accommodate pagination (and seemingly the task filter) bar. As a result, a custom conditional adjustment is required to that page when multiOrg is on, and the user needs to be able to browse to more than one page of tasks.
Before
--
After
--
https://user-images.githubusercontent.com/91283923/188032720-3cf84bea-6882-4cf9-9743-cabf46c095a0.mov
> fix: manually adjust heightWithPagination of Tasks page with multiOrg

- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/lsp/utils.ts
Closes #5622 
* updated resyncing (and page reloads):
* **Problem:** on re-sync with an entire change in the schema composition block, with new measurements + fields + tagValues, right now that's a series of request/response loops (executeCommand and applyEdits). This has a ramification of: (1) increased chance of getting out of sync, and (2) takes more time.
* **Solution:**  instead, have a single composition block initialize command be able to handle fields and tagValues too. So is a single request/response.
* fixed heuristic used in `_editorChangeIsFromLsp()`, to be accurate (based on LSP implementation).
https://user-images.githubusercontent.com/10232835/188017441-4c9a602e-62da-476e-9bcd-fa655dc55e1d.mov
We replace the composition block entirely each time, in the applyEdit from the …
> feat(5622): reinit full composition block at once

- package.json
- yarn.lock
Changes in composition block, would duplicate code outside the block. Could not copy/paste subqueries below, and then keep editing the block.
https://github.com/influxdata/ui/issues/5634
https://user-images.githubusercontent.com/10232835/188196185-b585210c-8e25-4524-8827-45f1d8e884d9.mov
It does still keep chopping of the first letter of the text below. But that's a smaller bug, and we can fix it after this major patch goes in.
> build(lsp): upgrade flux-lsp to 0.8.33

- src/visualization/utils/useVisDomainSettings.ts
Closes #5627 
Updates the query results for an adaptive zoom only when the response is non-empty. This prevents the graph from erroring out.
Adaptive Zoom over empty time period:
https://user-images.githubusercontent.com/10736577/188025067-0ff43a23-48fa-4f81-a2ea-4ae16f28f23d.mp4
> fix: update the query results for adaptive zoom only for a non-empty response

- src/telegrafs/components/Collectors.test.tsx
- src/telegrafs/components/Collectors.tsx
- src/telegrafs/components/TelegrafOutputOverlay.tsx
- src/telegrafs/containers/TelegrafsPage.tsx
Part of #3970 
This is a part of a bigger pr that refactors `TelegrafsPage` to use overlay controller instead of React Router. 
This pr removes the `/output` route for `TelegrafOutputOverlay` and connects it to the overlaycontroller so it can be triggered without route change. 
https://user-images.githubusercontent.com/66275100/188188026-928987ab-42d9-46b6-9c69-9db2f9c35999.mov
> feat(telegrafsPage): use OverlayController to trigger telegraf output overlay

- src/overlays/components/OverlayController.tsx
- src/overlays/components/index.tsx
- src/overlays/reducers/overlays.ts
- src/telegrafs/components/CollectorCard.scss
- src/telegrafs/components/CollectorCard.tsx
- src/telegrafs/components/TelegrafInstructionsOverlay.tsx
- src/telegrafs/containers/TelegrafsPage.tsx
Part of #3970 
This is a part of a bigger pr that refactors `TelegrafsPage` to use overlay controller instead of React Router.
This pr removes the `/instructions` route for `TelegrafInstructionsOverlay` and connects it to the overlay controller so it can be triggered without route change.
https://user-images.githubusercontent.com/66275100/188704485-238274d8-cf39-4273-bbfd-103590364092.mov
> feat(telegrafPage): use OverlayController to open instructions overlay

- package.json
- yarn.lock
> chore: upgrade eslint to 8.23.0

- src/telegrafs/components/CollectorCard.tsx
- src/telegrafs/components/TelegrafConfig.tsx
- src/telegrafs/components/TelegrafConfigOverlayForm.tsx
- src/telegrafs/containers/TelegrafsPage.tsx
Part of #3970 
This is a part of a bigger pr that refactors TelegrafsPage to use overlay controller instead of React Router.
This pr removes the `/view` route for `TelegrafConfigOverlay` and connects it to the overlay controller so it can be triggered without route change.
https://user-images.githubusercontent.com/66275100/188324148-f504f9cb-c0cf-4258-8481-bee5b841bb20.mov
> feat(telegrafPage): user OverlayController to open /view

- src/buckets/components/BucketCardActions.tsx
- src/dataLoaders/components/collectorsWizard/TelegrafUIRefreshWizard.tsx
- src/dataLoaders/components/collectorsWizard/verify/VerifyCollectorsStep.tsx
- src/overlays/components/OverlayController.tsx
- src/overlays/components/index.tsx
- src/overlays/reducers/overlays.ts
- src/telegrafs/components/Collectors.tsx
- src/telegrafs/containers/TelegrafsPage.tsx
Part of  #3970 
This is a part of a bigger pr that refactors TelegrafsPage to use overlay controller instead of React Router.
This pr removes the `/new` route for `TelegrafUIRefreshWizard` and connects it to the overlay controller so it can be triggered without route change.
https://user-images.githubusercontent.com/66275100/188735937-a6846860-2aa4-4112-a549-31a04c1daf5a.mov
> feat(telegrafPage): use OverlayController to open /new

- package.json
- yarn.lock
update `babel-loader` to 8.2.5.
> chore: upgrade babel loader to 8.2.5

- src/MultiOrgOverrideStyles.scss
Closes #5649 
The notebooks browser isn't behaving correctly with `multiOrg` on when the user has more than a few notebooks - the top and bottom of the page are squished. The style adjustments for other pages were not working with notebooks, as there is custom logic on the page that adds more content into the header if the user needs to scroll into more pages of notebooks.  
This PR fixes that issue by adjusting the size of the page title, header, and size of the notebooks (flows) page specifically. 
Note
--
PR #5651 (not yet merged) would change the app structure to have a page element instead of a div. This PR is probably unaffected because its selectors are so specific, but this PR should be rebased and retested if that PR is merged first.
Before
-- …
> fix: adjust notebooks margins and header size when multi-Org is enabled

- src/MultiOrgOverrideStyles.scss
Closes #5657 
This PR fixes the issue with the task editor touching the bottom of the screen when multi-org is enabled. The size of the editor was set to the size of the screen minus the height of a toolbar on the task page. 
This PR adjusts that CSS so that, when multi-org is on, the calculation will be: height of the task page, minus multi-org header, minus task page toolbar.
Video
--
https://user-images.githubusercontent.com/91283923/188747471-617b8d1b-dff6-45b9-9998-1a3b86a0c869.mov
> fix: adjust task-editor size for multi-org

- cypress/e2e/util/annotationsSetup.ts
Just housekeeping to clean up something i noticed in my code editor.
While there have not been any recent issues with the annotation e2e tests, i noticed that the function call `cy.createBucket(orgID, name, 'devbucket')` is actually referencing an undefined variable called `name`. A quick search in the file will confirm this.
This looks like the code was originally copied over without the `name` variable being destructured from an outer function call. We fix this by doing that now.
> test: fix undefined variable in annotation test setup

- src/shared/components/FluxMonacoEditor.tsx
Closes #5617 
* the persisted `fluxQueryBuilder` is the user preference, not if the user is currently in the new QxBuilder.
* instead, use the current pattern with which we check it. (This^^ bool, and the route path.)
https://user-images.githubusercontent.com/10232835/188037746-347828a7-2b40-4d1a-956e-e552727321c7.mov
> fix(5617): composition styling not in notebooks

- src/writeData/components/PluginAddToExistingConfiguration/Configure.tsx
Closes #5661 
When selecting a telegraf to add a plugin to an existing configuration, we see a bad set state warning in the console. 
The issue is coming from `Configure.tsx` - an if statement that updates `isValidConfiguration` state (a state maintained inside parent component `Wizard.tsx`) based on whether user has selected a telegraf or not. If a telegraf is selected, it updates the `isValidConfiguration` state to true which activates the `ADD TO EXISTING CONFIG` button in the footer of the overlay. Otherwise, if a telegraf is not selected, it updates the state to false. 
But because `isValidConfiguration` is initialized with a false value, there is no need to update it to false again. Whenever user selects a telegraf, the `onClick` function will update this state to be true which will …
> fix: remove unnecessary set state

- package.json
- yarn.lock
> chore: upgrade prettier to 2.7.1

- package.json
- yarn.lock
Bug patch. Removed off-by-1 error in the schema composition applyEdit messages.
ASAP patch, before internal release.
> build(lsp): upgrade flux-lsp to 0.8.34

- src/dataExplorer/components/ResultsPane.tsx
Closes #5652
by popular demand, this adds the same submit hotkey found in the original data explorer into the new one!
> feat: add hotkey for rerunning a query

- package.json
- yarn.lock
> chore: upgrade immer to 9.0.15

- package.json
- yarn.lock
update `qrcode.react` to 3.1.0.
> chore: upgrade qrcode.react to 3.1.0

- .prettierrc.json
Prettier upgrade changed the behavior of `arrowParens` to `always` by-default. This will cause our touched files to be modified when prettier is run which may cause some confusion as well as frustration due to changes in expectation.
Changing the config to `avoid` instead to avoid the above mentioned issues.
> chore: update prettier config to keep previous behavior

- src/variables/selectors/index.tsx
Connects #5523 
I'm unable to reproduce the `object not extensible` error caused by the app trying to push into a frozen array (`vari.selected`) when there is no currently selected variable, either in remocal or in the environment in which we actually see the error (New Tools). 
This PR adds specific error reporting around this code block, so that we can actually see which variable is causing the issue, and what the state of the app is at that time. The current top-level error reporting doesn't provide that level of detail.
> fix: add specific error reporting around default-selected-variable code

- package.json
- yarn.lock
update `y-websocket` to 1.4.4.
> chore: upgrade y-websocket to 1.4.4

- cypress/e2e/shared/adaptiveZoom.test.ts
Closes #5492 
Test for a query being made when zooming on with the feature on.
With the feature off, we don't need to test, mainly due to the difficulty of proving that an api call does not happen in Cypress rather than happening. There is no clean way to do this without arbitrary wait times.
> test: add new test for adpative zoom

- src/dataLoaders/components/DataLoadersOverlay.scss
- src/dataLoaders/components/collectorsWizard/TelegrafUIRefreshWizard.tsx
- src/writeData/components/PluginAddToExistingConfiguration/Wizard.tsx
- src/writeData/components/PluginCreateConfiguration/Wizard.tsx
Closes #5700 
Adds styling to three telegraf overlays found 
- Inside Telegraf page when creating a new telegraf configuration
- Inside Source page when adding a plugin to an existing configuration
- Inside Source page when adding a plugin to a new configuration
Depending on where user is at in the configuration step (`currentStepIndex` `substepIndex`), pr adds padding to the overlay body. 
Before: 
https://user-images.githubusercontent.com/66275100/189175626-8664e8b2-999b-4767-bb7a-51c19710fd1f.mov
After: 
https://user-images.githubusercontent.com/66275100/189175604-e9bef583-c130-4dcd-a647-952b5e4dac41.mov
> fix(dataLoaders): add styling to telegraf conf overlay

- src/types/subscriptions.ts
- src/writeData/subscriptions/components/CertificateInput.tsx
related https://github.com/influxdata/data-acquisition/issues/442
nifid will be storing brokerCertCreationDate so updating this key in the UI as currently you cannot edit the certificate even when the flag is on and a certificate is created
> fix: change from certProvided to certCreation

- cypress/e2e/shared/secrets.test.ts
- src/flows/pipes/RawFluxEditor/view.tsx
Remove the feature flag for `fluxInjectSecrets`.
Has been on in prod since 2022.02.02.
> chore: remove fluxInjectSecrets flag

- src/languageSupport/languages/flux/lsp/connection.ts
This PR fixes a bug listed in #5573. When the sync is disabled, the icon and highlight shouldn't be shown.
This fix is behind the feature flag `schemaComposition`
https://user-images.githubusercontent.com/14298407/189156754-e3f130ec-98c8-48f4-bfa9-f87a5a315746.mov
https://user-images.githubusercontent.com/14298407/189156702-5d1327fb-6976-468e-8da6-992f541b8c93.mov
> fix(schemaComposition): remove editor styles when sync is disabled

- src/usage/context/usage.tsx
The `storage_gb` calculation didn't match what the pricing information is on our website. Update it to match.
- ~[ ] Documentation updated or issue created (provide link to issue/PR)~
> fix: make storage_gb calculation match pricing info

- cypress/e2e/cloud/explorer.test.ts
- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/oss/explorer.test.ts
- cypress/e2e/shared/explorer.test.ts
- cypress/e2e/shared/explorerVisualizations.test.ts
- src/dataExplorer/components/Sidebar.tsx
- src/flows/pipes/RawFluxEditor/view.tsx
- src/shared/contexts/editor/index.tsx
- src/shared/contexts/editor/insertFunction.ts
- src/shared/utils/fluxFunctions.ts
- src/timeMachine/components/FluxToolbar.tsx
Closes #5660 
Pr removes `fluxDynamicDocs` from the UI. 
This means `Cloud` UI will be leveraging dynamic flux service in all areas of UI where script editor is used. 
Removal of this ff means `Cloud` and `OSS` will no longer have the same logic behind displaying and injecting flux functions into the`Script Editor`. `OSS` uses static flux docs to display flux functions while cloud uses dynamic flux. This means the e2e tests for injecting flux functions into script editor need to be moved from shared folder to `cloud` and `oss` respectively. 
> chore: remove fluxDynamicDocs feature flag

- package.json
- yarn.lock
> chore: upgrade sass to 1.54.9

- package.json
- yarn.lock
Closes #5692 
Update Giraffe to get the latest Simple Table. See https://github.com/influxdata/giraffe/pull/802 for details
> fix: update Giraffe to improve Simple Table performance

- package.json
- yarn.lock
update `style-loader` to 2.0.0.
> chore: upgrade style loader to 2.0.0

- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/explorer.test.ts
- cypress/e2e/shared/flows.test.ts
- cypress/e2e/shared/fluxQueryBuilder.test.ts
- cypress/e2e/shared/variables.test.ts
- src/shared/components/FluxMonacoEditor.tsx
Part of e2e tests #5591 
* composition block styling, should not exist in:
* notebooks
* old data explorer
* new QX builder, when feature flag is off
* should only exist:
* new QX builder, when feature flag is on
* normal injection routes, outside of composition, are already tested. Did not need to add those tests.
* injection via schema composition
> chore(5591): tests to ensure composition does not accidentally appear where it shouldn't

- src/dataExplorer/context/persistance.tsx
Closes #5756
This PR increases the default height size of the Monaco editor so that there is a 50/50 split between the Monaco editor and results panel
> chore: increase Monaco editor default size

- cypress/e2e/cloud/about.test.ts
- cypress/e2e/cloud/billing.test.ts
- cypress/e2e/cloud/buckets.test.ts
- cypress/e2e/cloud/checkout/checkoutinaccessible.test.ts
- cypress/e2e/cloud/checkout/checkoutpage.test.ts
- cypress/e2e/cloud/communityTemplates.test.ts
- cypress/e2e/cloud/dashboardsView.test.ts
- cypress/e2e/cloud/deepLinks.test.ts
- cypress/e2e/cloud/explorer.test.ts
- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/cloud/geoOptions.test.ts
- cypress/e2e/cloud/helpBar.test.ts
- cypress/e2e/cloud/operator.test.ts
- cypress/e2e/cloud/operatorRO.test.ts
- cypress/e2e/cloud/pinned.test.ts
- cypress/e2e/cloud/subscriptions.test.ts
- cypress/e2e/cloud/usage.test.ts
- cypress/e2e/cloud/userAccounts.test.ts
- cypress/e2e/cloud/userProfile.test.ts
- cypress/e2e/cloud/users.test.ts
- cypress/e2e/cloud/zuoraOutage.test.ts
- cypress/index.d.ts
- cypress/support/commands.ts
Closes #5737
This PR toggles the `quartzIdentity` and `multiOrg` flags on for all cloud2 e2e tests, as these flags are going to be on in prod for all users. Where feasible, I've refactored to make sure any flag adjustments happen in a single `beforeEach` rather than in multiple individual tests (`it`). There are a few places this isn't possible - e.g., where cypress needs to toggle on one flag for a specific block to test a new feature.
> chore: toggle quartzIdentity and multiOrg on in cloud e2e tests

- src/Signin.tsx
- src/identity/apis/auth.ts
- src/onboarding/containers/LoginPage.tsx
Closes #5022 
This PR changes login behavior so that, in Cloud, Quartz (not IDPE) is polled to check for the validity of the user's session. 
New code block is behind the flag `quartzSession` and will be tested in other environments before being enabled in prod.
Old Behavior
--
At login, and every 60 seconds . . . 
Make a `GET` request to `/api/v2/me` (IDPE /me).
New Behavior
--
At login, and every 60 seconds . . . 
OSS
1. No change.
CLOUD
1. `quartzIdentity` enabled? Make `GET` request to `/api/v2/quartz/identity`
2. Otherwise, make `GET` request to `/api/v2/quartz/me`
Notes
- The second option in cloud will be removed soon, as `/quartz/identity` is on in all environments and `/quartz/me` is deprecated, and is slated to be removed from the codebase shortly.
- Once the flag is removed …
> feat: use quartz, not idpe, for user sessions

- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/resources/TemplatePage.tsx
- src/dataExplorer/components/resources/types/script/index.ts
- src/dataExplorer/context/fluxQueryBuilder.tsx
- src/dataExplorer/context/persistance.tsx
- src/shared/components/FluxMonacoEditor.tsx
Closes #5340 
* in new QX script editor:
* Use default text for:
* default session query string
* clear() methods to reset the session
* default query string in script resource
* Could have tried doing the minimum (change only the default script resource). But decided to make all reference the proper default, to avoid any current/future races.
* Is not feature flagged since the description is accurate with, or without, the new features in the QX script editor.
* Default message does NOT appear in:
* notebooks
* old data explorer. 
https://user-images.githubusercontent.com/10232835/189738763-27194a58-4a62-4537-8306-1ec5955bbeed.mov
> feat(5340): use default editorText in script editor

- src/variables/selectors/index.tsx
We added more error [reporting to honeybadger](https://github.com/influxdata/ui/pull/5689/) around a code block in `variables` that throws an `object not extensible` error to resolve this [issue](https://github.com/influxdata/ui/issues/5523). We're now getting more detailed error reports, but when the monitor301 dashboard that experiences this error hits it, it hits it 300+ times. We're getting reports of sluggishness on that monitor301 dashboard and the following error, which suggests the network reporting of the error might be overkill. Also, we don't really need it anymore, since we have logs of the error in honeybadger.
This PR does two things. 
- First, it removes the honeybadger reporting added to this block. 
- Second, it attempts to resolve the immediate error by _not_ pushing a …
> chore: add guards to pushing into selected variable array, remove extra reporting

- src/dashboards/components/DashboardHeader.tsx
- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/dashboards/components/dashboard_index/DashboardCards.tsx
Part of https://github.com/influxdata/idpe/issues/15219
Pinned Items are not used on the landing page. But we left in the functionality to pin Dashboards. Remove this functionality.
Before:
* can pin a dashboard
* but doesn't appear on landing page
* https://user-images.githubusercontent.com/10232835/190515588-4ac0126d-1a65-4346-8b05-b2dd574fada7.mov
After:
* cannot pin a dashboard
* https://user-images.githubusercontent.com/10232835/190515641-d21da5c9-124a-4b2c-9e5c-36084016ab91.mov
> feat(idpe-15219): remove pinned items from Dashboards

- package.json
- yarn.lock
removes http-proxy-middleware as it isn't being used.
> chore: remove http-proxy-middleware

- src/dataExplorer/components/FluxQueryBuilder.scss
- src/dataExplorer/components/Results.scss
- src/dataExplorer/components/Schema.scss
- src/dataExplorer/components/Sidebar.scss
Closes #5765 
This PR updates styles on 1) the corner radius of the Monaco editor and Results panel, 2) the padding below the menu heading
> style: remove the corner radius of the Monaco editor and Results panel

- src/tasks/components/TaskCard.test.tsx
- src/tasks/components/TaskCard.tsx
- src/tasks/components/TasksList.tsx
- src/tasks/containers/TasksPage.test.tsx
Part of https://github.com/influxdata/idpe/issues/15219
Pinned Items are not used on the landing page. But we left in the functionality to pin Tasks. Remove this functionality.
Before:
* can pin a task
* but doesn't appear on landing page
* https://user-images.githubusercontent.com/10232835/190507193-01618bca-eb2e-48a1-8263-7e11c6795faa.mov
After:
* cannot pin a task
* https://user-images.githubusercontent.com/10232835/190507198-87a7723e-e02c-489d-88b1-e435edf23861.mov
> feat(idpe-15219): remove pinned items from Tasks

- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/522
The subscription password field should be required basic auth is selected and a subscription is being created. It should be optional when basic auth is selected and a subscription is being edited. This is because we do not return the password in the API response so the field is empty when the subscription is being edited and that's ok. If the password field remains empty, we [do not include it](https://github.com/influxdata/ui/blob/master/src/writeData/subscriptions/utils/form.ts#L142) in the update API request. The user is still free to edit the password if they like.
Before (save changes is disabled)
After (save changes is enabled)
Password is not included in the PUT request when field is empty
Authors and Reviewer(s), …
> fix(sub): password field optional during update

- src/flows/components/FlowCard.tsx
- src/flows/components/FlowCards.tsx
- src/flows/components/FlowContextMenu.tsx
- src/flows/components/header/MenuButton.tsx
- src/flows/components/header/index.tsx
Part of https://github.com/influxdata/idpe/issues/15219
Pinned Items are not used on the landing page. But we left in the functionality to pin Notebooks. Remove this functionality.
Before:
* can pin a notebook
* but doesn't appear on landing page
* https://user-images.githubusercontent.com/10232835/190510274-cfa0d56e-183f-43d1-9c04-3b23785fccc5.mov
After:
* cannot pin a notebook
* https://user-images.githubusercontent.com/10232835/190510289-8819bba7-a7bd-41e7-9451-5864c7d39071.mov
> feat(idpe-15219): remove pinned items from Notebooks

- src/accounts/context/userAccount.tsx
- src/identity/apis/auth.ts
- src/shared/copy/notifications/categories/accounts-users-orgs.ts
Related: #5029
Refactor user accounts page (UserAccount.tsx) so that `getAccounts` and `patchAccount` from unityroutes are being used by the auth API layer.
> chore: refactor useraccounts to use api layer

- src/identity/reducers/index.ts
- src/identity/utils/convertIdentityToMe.ts
- src/shared/containers/GetOrganizations.tsx
Closes #4823 
This PR adds the `account.isUpgradeable` property into state, and adjusts the app to pull the user's eligibility to access the checkout page from that property, instead of the old `isRegionBeta` property.
Previously, we needed to make an extra network call (to api/v2/quartz/orgs/:orgId) on the home page after the `identity` upgrade. The reason was that we have a check in `GetOrganizations` (which controls our routes) that denies the user access to the checkout page if they're in a beta cluster (`isRegionBeta`) and therefore shouldn't be able to upgrade their account yet. `identity` didn't have a property on it that corresponded to `isRegionBeta`, so we had to make a separate network call to the orgs/:orgId route to get that data, and confirm whether the user can check out. …
> feat: remove unnecessary org-details fetch on homepage once isUpgradeable is available

- package.json
- yarn.lock
We can only upgrade to `5.2.7`. the V6 of css-loader requires webpack v5.
> chore: upgrade css-loader to v5.2.7

- src/accounts/context/userAccount.tsx
We are seeing some new error reporting after PR #5773 . Root cause is that refactor changed a `filter()` to a `find()`, which is going to return an `undefined` or single `object` from the array of objects, as opposed to an array containing a single object.
> fix: change expected acct endpoint response to single object

- package.json
- yarn.lock
Closes [#5624](https://github.com/influxdata/ui/issues/5624)
The [version](https://github.com/rudderlabs/rudder-sdk-js/blob/production/CHANGELOG.md#v1016---2021-03-24) we're currently using is from `2021-03-24`, there are some changes that went in here that mention [anti-flicker ](https://github.com/rudderlabs/rudder-sdk-js/pull/379/commits/9d3a557a334efc532ccf5ab23d3e2196ab3014c4) so I thought i'd try updating the version as a try at fix. 
Seems to work.
https://user-images.githubusercontent.com/146112/187999253-a65190ea-a8df-41b8-abf6-6a48ece46a0d.mov
https://user-images.githubusercontent.com/18511823/191373378-3b70f02a-cd5d-4743-9282-e599776051c9.mov
> fix(rudderstack): update version to remove initial app flicker

- package.json
- yarn.lock
Closes #1673
Closes #2629
Closes https://github.com/influxdata/giraffe/issues/811
Pulls in the latest giraffe which adds the following fixes:
- fixes font sanitizer console warnings
- Gauge and SingleStat/SingleStat with Line graphs now use Proxima Nova instead of the default system serif font
> fix: update to latest giraffe to fix font issues

- src/cloud/components/experiments/GoogleOptimizeExperiment.tsx
Closes [#5628](https://github.com/influxdata/ui/issues/5628)
My hypothesis of what was happening: 
`useSelector` is an async operation, and the current config of useEffect hook it runs on `mount` as well as `update`.
Perhaps we don't need to run this on mount, i.e. when the org info isn't retrieved yet. 
We can see these errors in honey-badger occasionally. Seems like a race condition. 
`
> fix(reporting): guards to prevent accessing null values from useSelector

- src/writeData/subscriptions/utils/form.ts
related https://github.com/influxdata/data-acquisition/issues/532
A user should be able to edit their certificate subscription even if they haven't replaced their certificate 
> fix: if no new cert is provided a user should be able to submit

- package.json
- yarn.lock
Part of #5757 
Update clockface version to 6.3.5 release https://github.com/influxdata/clockface/releases/tag/V6.3.5
This brings in a clockface fix for the draggable resizer component that will be used in new script editor
> chore: upgrade clockface to 6.3.5

- src/App.tsx
- src/billing/components/BillingPageContents.tsx
- src/identity/actions/thunks/index.ts
- src/identity/apis/auth.ts
- src/identity/utils/shouldUseQuartzIdentity.ts
- src/me/actions/thunks/index.ts
- src/organizations/components/OrgProfileTab/index.tsx
- src/shared/components/NotFound.tsx
- src/shared/containers/SetOrg.tsx
- src/support/components/PayGSupportOverlay.tsx
The `quartzIdentity` flag - which makes the UI use `/quartz/identity` instead of `/quartz/me` to support the development of the multiOrg epic - has been on in prod without issue since July 13. Any conditionals in the UI that use `quartz/me` as a fallback for `/identity` are no longer necessary.
There are 5 steps to getting rid of all references to quartzMe.
1. Remove the conditional checks in the UI that made quartzIdentity used over quartzMe when the flag was on. Also remove any related thunks and API calls. (THIS PR)
NOTE: This doesn't have any effect in prod since the flag is on everywhere. It _DOES_ have an immediate effect on the UI e2e tests, which try to hit /quartz/me until `cy.setFeatureFlags` turns `quartzIdentity` on.
2. Remove the _conversion_ functions in the …
> chore: remove ability to use quartzMe

- package.json
- yarn.lock
Closes #4506
Pulls in clockface version 6.3.6, which changes how CSS files are built. It adds in a `@charset: "UTF-8";` declaration. This should help with the corrupt font icons.
> chore: update to clockface 6.3.6 to attempt fixing corrupt icon fonts

- src/dataExplorer/components/FluxQueryBuilder.tsx
Closes #5755 
This PR updates two new icons from clockface
> chore: update icon for Open and Save

- src/dataExplorer/context/fluxQueryBuilder.tsx
- src/languageSupport/languages/flux/lsp/utils.ts
- src/shared/contexts/editor/index.tsx
Part of influxdata/flux-lsp#584
Since we decide to remove the original injection commands in flux lsp, this PR removes the usage of these commands in ui before removing the code in flux lsp. 
> chore: remove original injection commands

- cypress/e2e/cloud/globalHeader.test.ts
Closes #5869 
The globalheader test requires temporarily syncing the IDPE org id and the quartz-mock org id using `cy.intercept()`. The function that does that should be invoked in every test. There were some gaps that, in local testing, appeared to be providing an opportunity for the `orgs` and `identity` endpoints to get called again, which would reset the synchronization of the IDPE and quartz ids.
Passed 20x firefox, 20x chrome.
> fix: resolve flakiness in gh test by filling gaps in call to makeQuartzUseIDPEOrgID()

- src/buckets/components/BucketsTab.tsx
Closes #5814 
In a free account at the buckets limit, the bottom advertisement to upgrade the user's account to get more buckets when their bucket limit status is "exceeded" wasn't visible.  Without multi-org, the ad doesn't display at all; with multi-org on, it does display, but it's cut off. Reverting the code structure to the pre-multi-org state also doesn't show the ad, so it's possible this hasn't displayed for a while since some earlier adjustment to the UI or clockface.
Regardless, the cause is that the buckets tab is a page with custom page-height adjustments to accommodate the tabs that display at the top of the screen. Basically, the grid of buckets shown to the user was given a fixed size on the assumption the bucket limit exceeded ad didn't exist. But there's no one-size-fits …
> fix: add space in buckets for more-buckets ad when limit is hit

- cypress/e2e/shared/about.test.ts
The shared `about` test in the Cloud CI run has gone flaky in firefox. In firefox, the org Rename button is deemed visible, but on click, it's deemed detached from the DOM. 
Underlying cause is the `useEffect` hook in this component. This page requires a separate network call in cloud to retrieve additional information about the user's org. The cypress test verifies that the rename button is visible, but the panel re-renders on response from the new network call, which causes cypress to find the previously identified element detached from the DOM.
Credit to @TCL735 for the more comprehensive fix here, which explicitly waits for the response from that network call in cloud before checking for the rename button.
Repro:
--
https://user-images.githubusercontent.com/91283923/191995187-d050890b- …
> fix: resolve flaky about test 

- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/tags.tsx
* fields was holding state
* session itself was correctly updating
https://user-images.githubusercontent.com/10232835/191843865-473eea69-58bf-48eb-91e9-2410d82ca0fa.mov
* error disappeared on page reload -- so is the non-session store.
* we were using the same pointer object when resetting fields, and tags. Fixed that code.
> fix: tags and fields are pointer objects, so stop resetting with the same pointer to a stateful object.

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/dataExplorer/context/persistance.tsx
- src/languageSupport/languages/flux/lsp/connection.ts
Closes #5874 https://github.com/influxdata/ui/issues/5874
Found by @barbaranelson . Is actually 2 bugs:
1. edge case when divergence is not detected.
* a multiline deletion (which changes the size of the composition block) may not be detected as a change within the block
2. on divergence, should still be able to browse the schema
* this is a NPE which prevents session updates. (`schema.composition.<prop>` will NPE.)
* also made a test to check for the general use case (of schema browsing after divergence)
Vid of bug. Bugs are show in order:
https://user-images.githubusercontent.com/10232835/191865422-b85c39e8-0b8c-41fc-aab0-3e0be93e5424.mov
https://user-images.githubusercontent.com/10232835/191866390-0cf7f7a5-ffd4-4804-b972-84ad432a2a51.mov
Authors and Reviewer(s), please verify the …
> fix: enable schema browser when diverged, and fix divergence detection with multiline deletion event.

- src/shared/components/CopyToClipboard.tsx
- src/shared/components/cells/CellContext.tsx
- src/shared/copy/notifications/categories/dashboard.ts
- src/types/dashboards.ts
Closes #2147
Adds a copy query option to the cell context menu. Only adds it if there is a query to copy
https://user-images.githubusercontent.com/146112/192034334-353dc238-f36b-4aa4-adeb-7387e4a583ed.mov
> feat(dashboards): add copy query to cell context menu

- src/identity/selectors/index.ts
- src/operator/OperatorNav.tsx
- src/operator/context/operator.tsx
For other PRs removing this code see #5847, #5876, #5878
Removes references to the quartzMe data shape on operator-related pages.
> chore: remove quartzMe references from operator pages

- src/accounts/CancellationOverlay.tsx
- src/billing/components/BillingPageContents.tsx
- src/billing/components/PayAsYouGo/CancellationOverlay.tsx
- src/billing/components/PayAsYouGo/CancellationPanel.tsx
- src/billing/context/billing.tsx
- src/checkout/context/checkout.tsx
For other PRs removing this code see #5847, #5876
Removes references to the quartzMe data shape in the account and billing pages.
> chore: remove refs to quartzMe shape in account and billing

- src/organizations/components/DeleteOrgOverlay.tsx
- src/organizations/components/OrgProfileTab/DeletePanel.tsx
- src/organizations/components/OrgProfileTab/index.tsx
- src/organizations/containers/OrgProfilePage.tsx
- src/usage/context/usage.tsx
For other PRs removing this code see #5847, #5876, #5878, #5883
Removes references to the quartzMe data shape on the org profile tab and related pages.
> chore: remove quartzMe references from org pages

- src/pageLayout/constants/navigationHierarchy.ts
> fix(TreeNav): change notebooks icon from pencil to notebook

- src/writeData/subscriptions/components/CertificateInput.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/551
If a user selects cert auth (currently feature flagged) all three fields are required.
> fix: subs all certs fields required

- src/billing/components/BillingPageContents.tsx
Using a free account, a notification appears when clicking to the Account/Billing page about being unable to retrieve the user's marketplace data. There is no marketplace data for a free account. Cause is [UI #5878](https://github.com/influxdata/ui/pull/5878), which pulls the information from the identity state directly, not identity-as-converted-to-quartzMe.
Cause: the conversion utility (and quartzMe itself) set `billingProvider` to `null` by implication if the user doesn't have a billing provider. In `identity`, no billing provider is set by default because it isn't part of that endpoint - you have to wait for a call to /orgs/:orgsId. So there is a period on the account/billing page before the data is fetched where a free account will have a billingProvider of `undefined`, which will …
> fix: account for possibility of undefined billingProvider until api call completes

- package.json
- yarn.lock
Update clockface version to 6.3.7 release https://github.com/influxdata/clockface/releases/tag/v6.3.7
This brings in a clockface fix for Save button icon that was mixed with PieChart icon
~~- [ ] Documentation updated or issue created (provide link to issue/PR)~~
> chore: update clockface to 6.3.7

- src/homepageExperience/components/steps/arduino/InitializeClient.tsx
- src/homepageExperience/components/steps/cli/InitializeClient.tsx
- src/homepageExperience/components/steps/go/InitializeClient.tsx
- src/homepageExperience/components/steps/nodejs/InitializeClient.tsx
- src/homepageExperience/components/steps/python/InitializeClient.tsx
Connects issue [#4821](https://github.com/influxdata/ui/issues/4821) and PR #5847 
Removes references to the quartzMe data shape from the homepage experience portion of the app.
This is one of several PRs that are going to remove references to the `quartzMe` data shape. The app no longer uses `quartzMe`, but is still referencing properties using the old `quartzMe` selectors (which are populated using a conversion function from the `identity` api). 
All references using the old selector will be removed; then the conversion function that populates the `quartzMe` reducer using the identity data will be removed.
> chore: remove refs to quartzMe data shape in onboarding experience

- src/dataExplorer/components/ResultsPane.tsx
- src/shared/components/FluxMonacoEditor.tsx
Closes #5886 
* outdated, memoized query sent via hotkey submit.
* vid:
https://user-images.githubusercontent.com/10232835/192363924-3e9fb6ae-8c1f-4cc6-89c5-9f1894b55884.mov
https://user-images.githubusercontent.com/10232835/192363842-c328383f-13e2-4fff-9b64-a6d4734e4bfe.mov
> fix(5886): FluxEditor hotkey submit should not use memoized version of script

- src/identity/components/GlobalHeader/GlobalHeader.tsx
- src/shared/components/cloud/CloudOnly.scss
Closes [#5779](https://github.com/influxdata/ui/issues/5779)
Hides things of less relevance as screen gets smaller to display the most important parts only, when the available estate is lesser.
https://user-images.githubusercontent.com/18511823/192393608-f6431535-2b9e-496e-bba2-8ffb213f7d8b.mov
> fix(globalHeader): make header work better with small screens

- src/homepageExperience/containers/ArduinoWizard.tsx
- src/homepageExperience/containers/CliWizard.tsx
- src/homepageExperience/containers/GoWizard.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
- src/homepageExperience/utils.ts
Closes #5452 
Adds a function that is called when `Next`, `Previous` or the Subway Nav buttons are clicked, which scrolls the `h1` element at the top of each page into view.
Since setting state and re-rendering is an asycnrhonous operation, the function sets a timeout of 0 seconds so that the function call is added to the next run of the event queue, to let react render the next component. **This solution is a bit hacky and might end up causing weird race conditions.** This is why it has been hidden behind the feature flag `firstMileScrollTop`
https://user-images.githubusercontent.com/146112/192382849-03734be8-0346-4838-b0a1-f7ffcdcf82b4.mov
> feat(onboarding): scroll next page into view if previous page was scrolled

- src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderDropdown.scss
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderTypeAheadMenu.tsx
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/index.tsx
Closes [#5778](https://github.com/influxdata/ui/issues/5778)
This PR changes the height of the individual items and forces **all the** items to be 36px (height upon selection) so there is no height changing effect.
It happens in all dropdowns, but we notice it more because of the horizontal dividers we have in the dropdown.
After fix:
https://user-images.githubusercontent.com/18511823/192591107-cd94eb65-8701-4e4b-9d15-84694255275b.mov
> fix(globalHeader): Global header typeahead menu item height

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/dataExplorer/components/ResultsPane.tsx
Closes #5912 
Fixing a bug I accidentally introduced yesterday (while fixing an unrelated bug).
Daterange updates is now being included in the extern payload:
https://user-images.githubusercontent.com/10232835/192630723-b5ac6587-6209-4d6e-8239-21a13eb91089.mov
> fix(5912): query with updated/latest time range

- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/SaveAsScript.scss
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/resources/types/script/index.ts
Closes #5836
exposes to the user if the api believes that there's an error with the script they tried to save
a couple of one liners are in there as well that came through, like fixing the text change I missed the last time I was in there and the request that a user should always be able to clear their script
> fix: forward errors from save api

- src/onboarding/containers/LoginPage.tsx
Part of https://github.com/influxdata/idpe/issues/15477
Finally, using the unauth-ed version of the API to hopefully close out that issue. Still, want to test it after this merges, hence the "Part of" instead of Closes.
> feat(universalLogin): use unauth-ed api endpoint to fetch login URL

- src/billing/components/BillingPageContents.tsx
- src/identity/actions/creators/index.ts
- src/identity/actions/thunks/index.ts
- src/identity/apis/auth.ts
- src/identity/mockUserData.ts
- src/identity/quartzOrganizations/actions/thunks/index.ts
- src/identity/quartzOrganizations/reducers/index.test.ts
- src/identity/quartzOrganizations/reducers/index.ts
- src/identity/reducers/index.test.ts
- src/identity/reducers/index.ts
- src/identity/selectors/index.ts
- src/organizations/components/OrgProfileTab/index.tsx
Closes #5936 
Splits the single redux loading status for `quartzIdentity` into three separate statuses. 
The motivation for this is more fully explained in UI #5917. But basically, [having a single loading status ](https://stackoverflow.com/questions/65849464/react-and-redux-proper-way-to-store-loading-state-in-redux) for all identity-related data increases the risk of a render loop in child components that update aspects of the identity state through calls to other endpoints.
The loading state shouldn't be focused on whether we're in the process of changing the state maintained for the user. Instead, it should answer the question: Did we already get a good response from the endpoint we needed to hit _to load this specific part of the app_ - or do we still need to make another call? 
This …
> fix: split up quartz-identity redux loading state into three states

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/monaco.flux.hotkeys.ts
- src/types/monaco.ts
Closes #5809 
* we found one example where hotkeys were not triggering the composition divergence, while editing the composition block.
* bug found: commenting out --> was not diverging. 
* goal of this PR is to test the suite of default hotkeys:
* to make sure we diverge properly.
* fix it when we don't.
* what we care about per hotkey action, is if there is:
1. a code change triggered (resulting in a monaco-editor change object).
2. the change occurs in the composition block .
* since our code is checking the outcomes (e.g. the change object), we can write a test per class of change.
* hotkey action classes:
* add lines
* remove lines
* move lines, without impacting line counts
* mutate lines in place.
* we wrote general test cases for all of these^^, except for the mutate-in-place …
> fix(5809): test and debug composition divergence with hotkeys.

- cypress/e2e/cloud/about.test.ts
- cypress/e2e/cloud/billing.test.ts
- cypress/e2e/cloud/buckets.test.ts
- cypress/e2e/cloud/checkout/checkoutinaccessible.test.ts
- cypress/e2e/cloud/checkout/checkoutpage.test.ts
- cypress/e2e/cloud/communityTemplates.test.ts
- cypress/e2e/cloud/dashboardsView.test.ts
- cypress/e2e/cloud/deepLinks.test.ts
- cypress/e2e/cloud/explorer.test.ts
- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/cloud/geoOptions.test.ts
- cypress/e2e/cloud/globalHeader.test.ts
- cypress/e2e/cloud/helpBar.test.ts
- cypress/e2e/cloud/operator.test.ts
- cypress/e2e/cloud/operatorRO.test.ts
- cypress/e2e/cloud/subscriptions.test.ts
- cypress/e2e/cloud/usage.test.ts
- cypress/e2e/cloud/userAccounts.test.ts
- cypress/e2e/cloud/userProfile.test.ts
- cypress/e2e/cloud/users.test.ts
- cypress/e2e/cloud/zuoraOutage.test.ts
- cypress/index.d.ts
Connects #4821
The UI no longer references or takes any action based on the quartzIdentity flag (all cloud paths use /quartz/identity over /quartz/me). So it can be removed from the flag toggle in our e2e tests.
> chore: remove quartzIdentity flag from e2e tests

- src/onboarding/containers/LoginPage.tsx
Part of https://github.com/influxdata/idpe/issues/15477
React needs us to return something, instead of `undefined`. `null` is a valid return. 
> fix(universalLogin): return null instead of undefined to prevent render errors

- src/operator/utils.ts
- src/shared/containers/GetOrganizations.tsx
Removes references to the old quartzMe data shape in the getOrganizations component. Component still uses the same ultimate data source (quartz/identity), but now actually uses the quartzIdentity selector, not the quartzMe selector through which the /identity data is converted.
A prior version of this commit was reverted (#5917 reverts #5910) because it caused issues with the Account/Billing component. 
Root cause was that a previous version of that component could create a render loop. Resolution (#5938) was to split the identity 'loading' state in redux into three states, so that child components don't affect the broader identity state on which the `PageSpinner` in `GetOrganizations` is waiting to load the app. 
That issue is not present here, because `quartzIdentity` …
> chore: transition getOrgs to identity selector

- src/identity/selectors/index.ts
- src/writeData/components/PluginCreateConfiguration/Footer.tsx
- src/writeData/subscriptions/components/CreateSubscriptionPage.tsx
Replaces references to the quartzMe state in the `writeData` components with quartzIdentity state.
Video
--
https://user-images.githubusercontent.com/91283923/193696850-659dca39-5c8d-4346-bd74-3e021a4ce40b.mov
https://user-images.githubusercontent.com/91283923/193697329-ce65a6b5-433f-49f6-a1d9-5de838a6c49d.mov
> chore: remove quartzMe references from writedata components

- package.json
- src/visualization/types/SingleStatWithLine/options.tsx
- src/visualization/types/SingleStatWithLine/view.tsx
- yarn.lock
Closes #5922 
- adds the adaptive zoom feature to Graph + Single Stat
- disables the text selection of the single stat when it appears with a line graph
https://user-images.githubusercontent.com/10736577/193708925-e120a401-7086-4dbf-ab7b-b6e32dbefca7.mp4
> feat: add adaptive zoom to Graph + Single Stat

- cypress/e2e/shared/nav.test.ts
- cypress/e2e/shared/notificationRules.test.ts
CI runs are frequently flaking on the shared nav and notificationRules tests in cloud. Both after deployment of K8s-idpe PR #12038, which synced remocal flags to current prod flags. 
- In the nav test, it can't find the `user-nav` element. That's expected. In cloud, user-nav doesn't exist anymore, because that functionality is in global header. Fixed this by skipping that portion of the test _only_ when the environment is CLOUD.
- In the notificationRules test, it tries to find the first 'dropdown-button' on the page. Previously, that would've been part of the alerts form. But now there's a dropdown in the page header too, which cypress finds first. Fixed by making the selector appropriately specific, so it targets the dropdown on the _page_.
Not clear why this flakiness only arose after …
> chore: resolve flaky nav and notificationRules tests

- cypress/e2e/cloud/subscriptions.test.ts
- src/authorizations/components/CustomApiTokenOverlay.tsx
- src/authorizations/utils/permissions.ts
- src/pageLayout/constants/navigationHierarchy.ts
- src/settings/components/LoadDataNavigation.tsx
- src/shared/containers/SetOrg.tsx
- src/writeData/components/WriteDataSections.tsx
No need for this anymore 🎉  Removes usage of the `subscriptionsUI` flag that was only used to determine if we should display the Native Subscriptions page or not. This flag is enabled everywhere and will remain that way so we can remove it.
> chore(sub): remove subscriptionsUI flag

- src/buckets/components/createBucketForm/BucketOverlayForm.tsx
Part of https://github.com/influxdata/ui/issues/2815
250 Credit promo message skews the banner. Disabling it for the Bucket Selector.
> fix(Buckets): disable 250 credit experiment on custom bucket selector

- src/App.tsx
- src/shared/components/NotFound.tsx
- src/shared/reducers/currentPage.ts
Closes #5750 
In cloud, the multi-org global header displayed on 404 pages, because it was rendered by the parent of the component containing our React Router routes (SetOrg).
This PR adds another condition for rendering the header: it won't display if the current page is the `not found` page. 
Conveniently, we already have a redux state for this (which is used in dashboards). So detecting the 'not found' page simply requires updating (and cleaning up) that state when the user hits the `Not Found` component.
Before
--
https://user-images.githubusercontent.com/91283923/194159129-70806657-b8d7-410f-8601-446805c046d2.mov
After
--
https://user-images.githubusercontent.com/91283923/194159141-8626a047-8675-4ac2-870e-2758438ba804.mov
> fix: dont show header on 404 page

- package.json
- src/types/subscriptions.ts
- src/writeData/subscriptions/components/BrokerDetails.scss
- src/writeData/subscriptions/components/BrokerForm.scss
- src/writeData/subscriptions/components/BrokerFormContent.tsx
- yarn.lock
Closes https://github.com/influxdata/data-acquisition/issues/464
Users can now specify a custom client ID. Behind feature flag `subscriptionsClientId` (to be created).
https://user-images.githubusercontent.com/6411855/194186021-d32bf918-f1cc-4572-9ca7-fb97b47c7021.mov
> feat(sub): can specify custom client id

- src/visualization/components/internal/DecimalPlaces.tsx
- src/visualization/types/Gauge/index.tsx
- src/visualization/types/Gauge/options.tsx
- src/visualization/types/SingleStat/index.tsx
- src/visualization/types/SingleStat/options.tsx
- src/visualization/types/SingleStatWithLine/index.tsx
- src/visualization/types/SingleStatWithLine/options.tsx
- src/visualization/types/Table/index.tsx
- src/visualization/types/Table/options.tsx
Closes #5977  
- adds a new component `DecimalPlaces` to handle the customization of decimal places
- prevents the visualization from crashing while changing the input for decimal places
- updates the visualization only upon valid input
Note: `DecimalPlaces` was added to Table's options as a placeholder to replace the customization's previous incarnation. Table does not actually adjust any decimal places at the moment. This visualization is slated for a major design overhaul or possibly deletion (and folded into a different table-like visualization.)
https://user-images.githubusercontent.com/10736577/194127600-96bbf10d-1459-41e0-9275-d10b35a367b2.mp4
> fix: prevent decimal places customization from crashing the visualization

- src/dataExplorer/components/Aggregate.tsx
- src/dataExplorer/components/FieldsAsColumns.tsx
- src/dataExplorer/components/GroupBy.tsx
- src/dataExplorer/components/ResultOptions.tsx
- src/dataExplorer/components/Sidebar.scss
- src/dataExplorer/components/Sidebar.tsx
- src/dataExplorer/components/ToggleWithLabelTooltip.tsx
Closes #5976 
This PR adds basic structure of the Result Options in new Script Editor so that the future work of fields as columns, group, and aggregate can be done independently. 
This work is behind the feature flag `resultOptions`
https://user-images.githubusercontent.com/14298407/194126338-a9ed9a52-2349-4291-9c45-3c1af64503c8.mov
> feat: add basic Result Options

- cypress/e2e/cloud/globalHeader.test.ts
- cypress/e2e/cloud/globalHeaderOrgMenuItems.test.ts
- cypress/fixtures/multiOrgIdentityContract.json
- cypress/fixtures/multiOrgIdentityPAYG.json
- cypress/support/Utils.ts
- src/identity/apis/auth.ts
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/CreateOrganization/MenuItem.tsx
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/GlobalHeaderDropdown.scss
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/index.tsx
- src/identity/components/GlobalHeader/OrgDropdown.tsx
Closes #5898 
This work is behind `createDeleteOrgs` feature flag.
Add menu items in Global Header.
**For FREE accounts, add `Add More Organizations` menu-item:** which redirects to `/checkout`
**For PAYG and Contract accounts, add `Create Organization` menu-item:**
When you click on `Create Organization`, it's supposed to show a modal and that work is slated for #5899 
More details on mockups are to be found here: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1961%3A18426
> feat: add menuitems for create org and add more orgs to global header

- cypress/e2e/cloud/globalHeaderOrgMenuItems.test.ts
Reduces flake on the create-org button test in PR #5923  by ensuring that the feature flag override happens after `cy.visit()`.
> chore: reduce flake on create-org button test

- src/shared/components/cells/Cell.tsx
- src/variables/selectors/index.tsx
Co-authored-by: Sahas Chitlange chitlangesahas@gmail.com
Helps with #6017
Memoize the `getAllVariables` selector for use in dashboard cells. On a dashboard with 5 cells, this reduces calls to the `getVariables` selector from 39 => 9, for a reduction of 77%. 
| Selector                | Call Count | Table Cell Count |
|-------------------------|------------|------------------|
| getAllVariables | 39         | 5                |
| getAllVariablesMemoized | 9          | 5                |
The results are even more dramatic on a dashboard with 10 cells (2x cells). 160 calls => 15 calls or 91%
| Selector                | Call Count | Table Cell Count |
|-------------------------|------------|------------------|
| getAllVariables         | 160        | 10               |
| …
> feat(dashboards): use memoized variables selector

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/ResultsPane.tsx
- src/flows/context/results.tsx
- src/flows/pipes/Table/view.tsx
- src/shared/contexts/query.tsx
- src/shared/copy/notifications/common.ts
- src/types/flows.ts
Closes #5901 
* bugs:
* we got `0 tables` when had 1 table.
* this is because lastTableValue of 0 || -1  => returned -1, then added +1 to make zero tableCnt
* clarify when data is truncated with a permanent UI message
* this means only presenting metadata when not truncated 
* cleanup test suite, before adding new tests:
* make `selectSchema()`, `selectBucket()`, and `resetSession()` into suite utils
* that way can use in new tests. 
* skip flaky test and comment reasons for flake (to later debug in another PR).
new QxBuilder is fixed.
https://user-images.githubusercontent.com/10232835/194426765-3a7f41da-3cc9-4a32-987b-cdd6d0d1ed3a.mov
notebooks gives the truncation message too:
**OUT OF SCOPE -- in notebooks.**
Note that the table counts, even when not truncated, in notebooks are not …
> fix(5901): display of query metadata (table and row counts) in QxBuilder and DataExplorer

- src/Logout.tsx
- src/onboarding/containers/LoginPage.tsx
We want to use the quartz endpoint to logout instead.
Note: I used `api/env/quartz-login-url` , it might be confusing at a first glance why it's calling a `login` path to logout. This was just a naming thing, we thought the endpoint will only be used for logging in, but now that we're using it for logging out, I will make follow up changes to rename it to `quartz-url`
> feat(Logout): use quartz logout endpoint + refactoring login redirect code

- cypress/e2e/cloud/globalHeader.test.ts
- cypress/e2e/cloud/globalHeaderOrgMenuItems.test.ts
Still some flakiness in Global Header Tests. Trying out a fix.
> fix: reposition setfeatureflag function for gh tests

- src/homepageExperience/containers/CliWizard.tsx
Connects #4055 
Missed one: there is one more reference to the `multiOrg` flag that needs to be removed (from the CLI wizard).
> chore: remove multiOrg flag reference from CLI wizard

- cypress/e2e/cloud/about.test.ts
- cypress/e2e/cloud/billing.test.ts
- cypress/e2e/cloud/buckets.test.ts
- cypress/e2e/cloud/checkout/checkoutinaccessible.test.ts
- cypress/e2e/cloud/communityTemplates.test.ts
- cypress/e2e/cloud/dashboardsView.test.ts
- cypress/e2e/cloud/deepLinks.test.ts
- cypress/e2e/cloud/explorer.test.ts
- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/cloud/geoOptions.test.ts
- cypress/e2e/cloud/globalHeader.test.ts
- cypress/e2e/cloud/globalHeaderOrgMenuItems.test.ts
- cypress/e2e/cloud/helpBar.test.ts
- cypress/e2e/cloud/operator.test.ts
- cypress/e2e/cloud/operatorRO.test.ts
- cypress/e2e/cloud/subscriptions.test.ts
- cypress/e2e/cloud/usage.test.ts
- cypress/e2e/cloud/userAccounts.test.ts
- cypress/e2e/cloud/userProfile.test.ts
- cypress/e2e/cloud/users.test.ts
- cypress/e2e/cloud/zuoraOutage.test.ts
Connects #4055 
Removes references in `cy.setFeatureFlags` to the `multiOrg` flag, which is no longer present in the UI.
This PR should be reviewed with ?w=1 - otherwise, it's difficult to see what was removed.
> chore: remove references to multiOrg flag in cypress tests

- src/Authenticate.tsx
This fixes a bug found in prod that was temporarily fixed by flipping a feature flag off.
This PR https://github.com/influxdata/ui/pull/6038 broke some functionality to the API which required a user id when the component making the request to the api used the legacy method (ipde me vs quartz identity) of retreiving the user id. This adds the call back in until https://github.com/influxdata/ui/issues/5826 can be addressed.
- ~[ ] Documentation updated or issue created (provide link to issue/PR)~
> fix(Authenticate.tsx): call idpe/me to maintain backwards compatibility

- src/writeData/clients/Swift/description.md
- src/writeData/clients/Swift/execute.example
- src/writeData/clients/Swift/executeFull.example
- src/writeData/clients/Swift/initialize.example
- src/writeData/clients/Swift/write.0.example
- src/writeData/clients/Swift/write.1.example
- src/writeData/clients/Swift/write.2.example
Closes https://github.com/influxdata/influxdb-client-swift/issues/58
This PR changes code examples for `Swift` library to use new modern `async/await` pattern (instead of callbacks) which was introduced by https://github.com/influxdata/influxdb-client-swift/pull/49:
```swift
let query = """
from(bucket: "\(self.bucket)")
|> range(start: -10m)
|> filter(fn: (r) => r["_measurement"] == "cpu")
|> filter(fn: (r) => r["cpu"] == "cpu-total")
|> filter(fn: (r) => r["_field"] == "usage_user" or r["_field"] == "usage_system")
|> last()
"""
print("\nQuery to execute:\n\(query)\n")
let records = try await client.queryAPI.query(query: query)
```
Updated UI:
> chore(client_libs): Swift client uses new modern async/await pattern

- cypress/e2e/shared/notificationEndpoints.test.ts
On notification endpoint creation, OSS parses the url to validate that it is the proper format. These tests failed as a result of that change.
> fix: oss validates the slack endpoint for url correctness

- src/types/subscriptions.ts
- src/writeData/subscriptions/components/BrokerForm.scss
- src/writeData/subscriptions/components/JsonPathInput.tsx
- src/writeData/subscriptions/components/ParsingForm.tsx
- src/writeData/subscriptions/components/StringPatternInput.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/421
Do not allow duplicate field/tag names.
> feat(sub): validate against duplicate field and tag names

- cypress/e2e/cloud/checkout/checkoutpage.test.ts
- src/checkout/shared/FormInput.tsx
Needs to be reviewed with `?w=1` - otherwise makes it look like more lines are changed. Should see this.
This PR started as an effort to remove a flag toggle from the checkout test. Making edits to that individual test - or even making no changes to the test - resulted in a CI test failure, which didn't make sense. The cause is that the test was already broken, but wasn't being run by our CI pipeline (unless you made edits to this test specifically) because it was in a separate subfolder that wasn't being run by the test runner.
This PR resolves the first part of the issue by fixing the broken test, by removing the `required` from an `<Input />` tag. The `required` was supposed to be present only in the parent component, as having `required` in the child component prevents the form …
> chore: fix broken checkout test and related form validation issue

- src/writeData/subscriptions/context/subscription.list.tsx
Closes https://github.com/influxdata/data-acquisition/issues/427
When loading the edit page, only call to get subs once via useEffect
> fix(sub): do not get subs twice

- src/writeData/subscriptions/components/BrokerDetails.scss
- src/writeData/subscriptions/components/BrokerForm.scss
- src/writeData/subscriptions/components/BrokerFormContent.tsx
Tweaks to the Client ID layout after getting feedback
New look:
> fix(sub): clientID layout

- package.json
- src/types/me.ts
- src/types/subscriptions.ts
- src/writeData/subscriptions/components/BrokerForm.scss
- src/writeData/subscriptions/components/BrokerFormContent.tsx
- src/writeData/subscriptions/context/subscription.create.tsx
- src/writeData/subscriptions/context/subscription.update.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/560
Adds an `Enable SSL` toggle to the subscriptions form. If checked, this sets `useSSL: true` in the api request. 
If "Certificate" auth type is chosen, the `Enable SSL` toggle is automatically flipped. 
If the `Enable SSL` toggle is enabled, the protocol preview changes from `mqtt://...` to `mqtts://...`
Behind flag `subscriptionsSSLSupport`
> feat(sub): add enable SSL toggle

- src/writeData/subscriptions/components/DetailsSubscriptionPage.scss
- src/writeData/subscriptions/components/JsonParsingForm.tsx
- src/writeData/subscriptions/components/JsonPathInput.tsx
- src/writeData/subscriptions/components/StatusHeader.tsx
- src/writeData/subscriptions/components/StringParsingForm.tsx
- src/writeData/subscriptions/components/StringPatternInput.tsx
- src/writeData/subscriptions/components/SubscriptionCard.tsx
- src/writeData/subscriptions/components/SubscriptionErrorsOverlay.tsx
- src/writeData/subscriptions/components/UserInput.tsx
- src/writeData/subscriptions/context/subscription.list.tsx
- src/writeData/subscriptions/utils/form.ts
Closes https://github.com/influxdata/data-acquisition/issues/408
Closes https://github.com/influxdata/data-acquisition/issues/392
Adds:
- Re-organizes the subscription card, adding the missing Description info and Last Updated By.
- When editing an existing subscription with User/Basic auth, changing the Host field will highlight the password field to indicate it needs to be re-populated.
Fixes various bugs:
- Username and Password should be required fields with validation.
- Save button should check for bucket being selected.
- Relative imports.
- Wrap subscription name so it doesn't run off screen
> fix(sub): card updates, various bug fixes

- src/shared/components/dateRangePicker/NewDatePicker.tsx
- src/shared/utils/duration.ts
- src/timeMachine/selectors/index.test.ts
- src/timeMachine/selectors/index.ts
Closes #6058 
`NewDatePicker` allows:
- `From` and `To` fields can be Flux syntax
- `From` field cannot be blank and is enforced with input validation
- `To` field can be blank and will be updated with `now()` via auto-injection if it is blank
- numbers are interpreted as Unix timestamps in **seconds** (per Flux specification)
- timestamps must be RFC 3339 format or from clicking the calendar
https://user-images.githubusercontent.com/10736577/196080899-a52da651-5210-4345-bffe-9c0500f785ee.mp4
> feat: make custom time ranges smarter

- cypress/e2e/shared/about.test.ts
- src/organizations/components/OrgProfileTab/index.tsx
Part of #6109 
Pr fixes a flaky test  in shared folder -  `about` e2e test. 
Flakiness is caused by failure to find text content `Cloud Provider` within DOM element. 
Fix: target direct parent element of text content.
> fix(about): target parent element to access content

- src/accounts/context/userAccount.tsx
- src/identity/apis/account.ts
- src/identity/apis/org.ts
- src/shared/components/NotFound.tsx
- src/types/error.ts
Helps with #5932, #5894
Adds UI API layer support for the quartz endpoints for creating orgs (`POST` /orgs) and getting the list of available clusters in which an org can be created (`GET` /clusters).
Matching openAPI specs: [create orgs](https://github.com/influxdata/openapi/blob/master/src/unity/paths/orgs.yml), [get clusters](https://github.com/influxdata/openapi/blob/master/src/unity/paths/clusters.yml).
Create Orgs Response
--
In quartz-remocal, we get a `401` as expected, as the default free account cannot create more than one org.
Get Clusters Response
--
> feat: add createNewOrg and fetchClusters to API layer

- package.json
- src/identity/apis/org.ts
Helps with #6121 
Updates the openAPI SHA to pull in the [spec for getAllowancesOrgsCreate](https://github.com/influxdata/openapi/commit/f7cc87286abffcea007df69e74b4162f9f1790b3), and adds it to the UI API layer.
Not used, and AIM hasn't added this endpoint to quartz yet. It will be mocked in quartz-mock so we can proceed with UI development until the endpoint is ready.
> feat: update openAPI SHA and add fetchOrgCreationAllowance to UI

- src/dataExplorer/components/FieldSelector.tsx
- src/dataExplorer/components/Schema.scss
- src/dataExplorer/components/Schema.tsx
- src/dataExplorer/components/TagSelector.tsx
- src/dataExplorer/components/resources/index.ts
Close #6103 
This PR adds read-only property to schema browser, specifically to field selector and tag selector. ~~This is to prepare for SQL editing once the SQL option is available.~~ The readOnly is derived from `resource.data.language`
> feat(schemaBrowser): add read-only property

- src/Logout.tsx
part of https://github.com/influxdata/idpe/issues/15477
When we tried testing the **logout** portion of the universal login feature, i.e. logout should use `quartz` endpoint and not idpe's, we noticed that the code under the flag `universalLogin` inside `Logout.tsx` was never hit.
After some digging this was the issue in summary:
User clicks logout -> flags cleared -> code looks for the flag value and sees it's false (because it was cleared), so it never runs.
the solution is to save a local copy of the flag on component mount, and then use that instead, so we don't have to worry about flags being cleared.
> fix(universalLogin): create a local copy of flag before signout clears it

- cypress/e2e/shared/loadDataSources.test.ts
- src/writeData/components/ClientLibrarySection.tsx
Closes #5983 
Adds 'arduino' to the onboarding items for Client Libraries
https://user-images.githubusercontent.com/10736577/197079482-4229c5c4-5d46-4ffa-94eb-007d06831278.mp4
> feat: use Arduino wizard for Arduino Client Library

- src/organizations/selectors/index.test.ts
- src/organizations/selectors/index.ts
Closes #6151 
Adds selector for determining if the selected org is an IOx org
> feat(orgs): add selector to determine if org is an IOx org

- src/shared/apis/queryCache.ts
- src/visualization/types/Band/view.tsx
- src/visualization/types/Graph/view.tsx
- src/visualization/types/Scatter/view.tsx
- src/visualization/types/SingleStatWithLine/view.tsx
- src/visualization/utils/useVisDomainSettings.ts
- src/visualization/utils/useZoomQuery.ts
Closes #5956  
Closes #6134  
- Adds multi-query support for Adaptive Zoom in Data Explorer and Dashboard Cells.
- Disables Adaptive Zoom whenever queries cannot be found, such as on the `/usage` page
https://user-images.githubusercontent.com/10736577/196830215-10b9c534-c055-41be-9929-3e8f4a796047.mp4
> feat: add multi-query support for Adaptive Zoom

- package.json
- yarn.lock
Use resolutions for minimatch to resolve https://github.com/influxdata/ui/security/dependabot/36. Also  clean out the following from `resolutions` in `package.json` which are no longer needed:
- minimist
- ansi-regex
- async
- nanoid
- cross-fetch
For each on of these I did:
$ yarn why <pkg>
$ rm -rf ./node_modules && yarn install && yarn why <pkg>
and compared the second 'yarn why' to the first. In all cases, the versions are resolved to the same version and with all the dependencies in yarn.lock resolving to the same version as before. Note: ansi-regex 4.1.1 and 6.0.1 dropped out completely (no longer needed).
> chore: use resolutions for minimatch and remove unneeded resolutions

- src/visualization/types/Map/view.tsx
Closes #6160
Connects maps visualizations to `uiproxyd`s version of the `getMapToken` route, rather than `mapsd`s version.
Works locally:
You can test the route in cloud environments by going to your cloud instance and logging in, then appending `/api/v2private/uiproxy/mapToken` to the end of the url. You should get a maps token back.
> chore(maps): make maps use uiproxyd routes instead of mapsd routes

- src/buckets/components/createBucketForm/CreateBucketOverlay.tsx
Closes #6057
Doesn't show the explicit bucket accordion when creating a bucket in an IOx org.
Also tested (but not shown): Bucket creation in first mile onboarding remains unchanged
**Bucket creation for an org that isn't IOx**
**Bucket creation for an org that is IOx**
> feat(buckets): don't show explicit schema when an iox org creates a bucket

- package.json
- yarn.lock
upgrades @types/text-encoding to latest
> chore: upgrade @types/text-encoding to latest

- src/dataExplorer/components/ResultsPane.tsx
- src/flows/pipes/Notification/NotificationMonacoEditor.tsx
- src/flows/pipes/RawFluxEditor/style.scss
- src/languageSupport/languages/sql/monaco.sql.hotkeys.ts
- src/languageSupport/languages/sql/monaco.sql.syntax.ts
- src/languageSupport/languages/sql/monaco.sql.theme.ts
- src/shared/components/FluxMonacoEditor.tsx
- src/shared/components/MarkdownMonacoEditor.tsx
- src/shared/components/MonacoEditor.scss
- src/shared/components/SqlMonacoEditor.tsx
- src/shared/components/TomlMonacoEditor.tsx
- src/timeMachine/components/TimeMachineFluxEditor.scss
- src/types/monaco.ts
Closes #6106 
* Provide the monaco-editor with pgsql specific:
* syntax tokenizer
* theme/coloring of that syntax
* submit hotkey
* Decided to provide separate root editor because:
* we already provide editor components per language (e.g. toml, markdown, python, flux, etc)
* will need a separate LSP connection anyways.  
@juliajames12 -- I am guessing these styles will need updated colors. Took a guess based upon colors used in the flux editor.
> feat(6106): pgsql support in monaco-editor

- docker/Dockerfile.chronograf
- docker/Dockerfile.chronograf.prod
`node:lts` is now using node18 which has a requirement for OpenSSL v3 which requires Webpack 5. 
https://stackoverflow.com/questions/69665222/node-js-17-0-1-gatsby-error-digital-envelope-routinesunsupported-err-os
Until we can upgrade to Webpack 5, we will need to stay on a node16 image.
> fix: pin to node image with node16

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/dataExplorer/components/ResultsPane.tsx
- src/shared/contexts/query/context.tsx
- src/shared/contexts/query/preprocessing.ts
Closes #6107 
* add queryOptions for language
* then have `buildQueryRequest()` and downstream consume this language option.
* submit and downloadCsv disablement rules:
* SQL
* must have query text and bucket selected
* Flux:
* if using composition --> must have bucket && measurement.
*  if not using composition --> must not have default text (or blank text).
* also remove the dateRangePicker when using sql.
* Also make more explicit what the override mechanism type means (a.k.a. params versus variables).
https://user-images.githubusercontent.com/10232835/198145261-0bb20177-8c02-4ecc-9d70-df171d6ea860.mov
> feat(6107): runQuery with iox sql.

- docker/Dockerfile.chronograf
- docker/Dockerfile.chronograf.prod
node:lts-alpine and node:lts break webpack 4 so temporarily choose a currently supported node release that uses node 16. When we migrate to webpack 5, move back to node:lts-alpine and node:lts.
Dockerfile.chronograf would ideally use node:lts, but choose node:gallium for now, both of which are Debian based.
Dockerfile.chronograf.prod would ideally use node:lts-alpine, but choose node:16-alpine3.16 for now, both of which are alpine 3.16 based.
Note: node 16 is also an LTS release and both node:gallium and node:16-alpine3.16 are listed as still supported.
References:
- https://nodejs.org/ar/blog/announcements/nodejs16-eol/
- https://hub.docker.com/_/node.
Successfully built both with:
* `docker build -f ./docker/Dockerfile.chronograf .`
* `docker build -f ./docker/Dockerfile.chronograf.prod …
> chore: pin to supported node 16 image

- src/dataExplorer/components/FluxQueryBuilder.tsx
Part of #6179 
This PR uses the solid clockface icon "Save" for the save button in the New Script Editor
> chore: use solid clockface icon `Save` for save button

- src/dataExplorer/components/FluxQueryBuilder.tsx
Part of #6179
This PR is the step two of the above issue. It uses the outlined clockface icon "Save" for the save button in the New Script Editor
> chore: use outline clockface icon `SaveOutline` for save button

- package.json
- yarn.lock
Part of #5949 
Bump `flux-lsp` version to have multi tag values support
> build(lsp): upgrade flux-lsp to 0.8.36

- src/visualization/utils/useVisDomainSettings.ts
Closes EAR 3724
The problem: syncing an axis has many conditions and not all of them worked. One hook was trying to do too much. Cross-axis syncing, which is when a user zooms and the re-query affects the limits of the data (the domain) of the other axis, was not properly updated. We move this into another hook that conveniently has the the proper conditional in place.
The fix: 
- zooming in on the value axis simply adjusts to the selected domain
- zooming in on the time axis will adjust the time axis (working as before), and also the value axis when new limits are found
Here is a video of the fix. Zoom re-query works. Zooming in on the value works, again.
https://user-images.githubusercontent.com/10736577/199049847-09511caa-aba2-47a9-a0eb-1150a5b71495.mp4
> fix: move cross axis syncining into a separate hook

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/languageSupport/languages/flux/lsp/connection.ts
Part of #6063 
* onChange() detect:
* occurs **after** change is applied.
* the change object's positional information (range lines), are based on the previous editor value **before the change** was applied
* solution:
* to really see if change occurred within the composition block, we need to compare to the snapshot editor text from **before** the change.
https://user-images.githubusercontent.com/10232835/195953925-6fc436bf-8d5e-40c7-a6d4-cd28dc082716.mov
> feat(6063): suppport import statements with composition

- src/onboarding/containers/CloudLoginPage.tsx
Part of [#6217](https://github.com/influxdata/ui/issues/6217)
When testing https://github.com/influxdata/ui/pull/6238 I found that when there is an auth failure, we use `redirectTo` to bring the user back to where they started. Since `redirectTo` is a param, it doesn't get added to the `pathname` by just using the default `location.pathname`.
I added some extra logic to append the redirectTo's pathname to the quartz path.
> fix(UniversalLogin): handle redirectTo upon auth failure

- src/flows/pipes/Notification/ExportTask.tsx
- src/flows/pipes/Notification/view.tsx
- src/flows/pipes/RawFluxEditor/index.ts
- src/flows/pipes/Schedule/view.tsx
- src/flows/pipes/Table/index.ts
- src/flows/pipes/Visualization/index.ts
- src/flows/templates/types/task.ts
- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/parser/index.ts
- src/shared/contexts/query/preprocessing.ts
- src/writeData/components/ClientCodeQueryHelper.tsx
There is currently a shim for both `parse` and `format_from_js_file` for
using those functions in a node environment. However, not all call to
`parse` or `format_from_js_file` use that shim. This patch fixes that.
_Why is this needed?_, you may ask yourself. Well, it's not, but it certainlys
makes it easier toidentify places that need to be ported over to the
(in progress) async versions of both of those functions. We'll know we
got all the places it's used when we can delete `parse` and
`format_from_js_file` and nothing breaks.
> chore: consolidate imports to flux-lsp-browser

- package.json
- yarn.lock
In performing 'yarn install', yarn corrected a few extra items to update the urls for big.js, emojis-list and json5, but it didn't change the version. It also pulled in minimist 1.2.7, which is also fine.
> chore: resolve monaco-editor-webpack-plugin#loader-utils to ^2.0.3

- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/Sidebar.tsx
Closes influxdata/ui#6240 
Sidebar container is used for other launched menus (such as graph customize). Have the sidebar container always exist, and only remove flux-specific sidebar menus when in SQL mode.
https://user-images.githubusercontent.com/10232835/200433616-3fbdd867-ace2-4627-a040-c0c933c12492.mov
> fix(6240): have Sidebar container always render

- src/visualization/components/internal/HoverLegend.tsx
- src/visualization/components/internal/LegendOptions.tsx
- src/visualization/components/internal/StaticLegend.tsx
- src/visualization/types/Graph/options.tsx
Closes #6283
Jankiness was caused by updating the redux store every time an input in the options panel changed. In text boxes: every keystroke. In sliders: every time the slider was moved. We'd dispatch an action, which would update the redux store, which would cause re-renders which would make the UI appear sluggish.
https://user-images.githubusercontent.com/146112/200597573-90d80871-86c2-4f90-94e5-f7dea7621421.mov
Store these changes in local component state, then debounce the call to update redux state so that the visualization will be updated after the input stops.
https://user-images.githubusercontent.com/146112/200598326-7e465d5e-b387-4cde-9f07-c418a017c614.mov
> perf: reduce jank in graph options sliders

- src/dataExplorer/components/Schema.tsx
- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
Closes #6201 
Since the feature flag `newQueryBuilder` was originally created for the query builder in the old Data Explorer and Notebooks, there is no need to check for this flag in new Script Editor. So the main purpose of this PR is to remove the logic check in if statements for `isFlagEnabled('newQueryBuilder')`. I also refactored the code to remove un-used variables.
> chore: remove `newQueryBuilder` in new script editor

- src/identity/components/OrganizationListTab/OrgList.tsx
- src/identity/components/OrganizationListTab/OrganizationCard.scss
- src/identity/components/OrganizationListTab/OrganizationCard.tsx
- src/identity/components/OrganizationListTab/index.tsx
Closes #6223 
1. Reverts organization list cards back to their original design based on further design feedback (thin cards - all data on one line).
2. Searching in the text box now allows for searching not only by name, but also by provider, region, and location.
Also adjusted pagination tab so that (consistent with figma) it doesn't display when there is one page or fewer of 'results' from the user's search.
Before Changes
--
Uses the Original Org Card Design 
--
https://user-images.githubusercontent.com/91283923/200882252-352f2c1a-e076-4edf-ba8e-7eb1a774bb77.mov
Adds More Filtering Options
--
https://user-images.githubusercontent.com/91283923/200882512-eeea781c-b5c5-48d1-88fc-a8466a1b06f3.mov
No Pagination Displayed When There is Only One Page of Results
--
Authors and Reviewer(s), …
> chore: adjust task card and filter appearance based on design input

- src/scripts/apis/index.ts
- src/shared/copy/notifications/categories/scripts.ts
- src/tasks/components/TaskScheduler/ScriptSelector.tsx
- src/tasks/components/TaskScheduler/TaskScheduler.scss
- src/tasks/components/TaskScheduler/TaskScheduler.tsx
- src/tasks/containers/TaskPage.tsx
- src/types/scripts.ts
Part of #6186 
Behind `tasksUiEnchancements` feature flag
For new Task create page, pr adds functionality to the Select Script drop down and search bar. 
Upon page load, ScriptSelector will fetch scripts and display them inside the dropdown component. User can filter through scripts by typing inside the search bar. 
Upcoming Pr will introduce the next step - showing parameters, description, and name of script on the right side of the page when a script is clicked. 
https://user-images.githubusercontent.com/66275100/200870805-f25f74bf-45c6-40d7-87c1-8c2ec5a49d60.mov
> feat(taskScheduler): fetch and list scripts

- jestSetup.ts
- package.json
- src/checks/components/CheckHistory.tsx
- src/checks/reducers/checks.test.ts
- src/notifications/endpoints/components/EndpointOptions.tsx
- src/notifications/endpoints/components/EndpointOverlay.reducer.ts
- src/types/alerting.ts
- src/writeData/containers/ClientLibrariesPage.tsx
- webpack.dev.ts
- webpack.fast.ts
- webpack.lighthouse.ts
- webpack.prod.ts
- webpack.vendor.ts
- yarn.lock
This PR is related to some ongoing work to update our dependencies. The initiative behind this change was prompted by some TS issues that arose with some updates to transition our LSP work to WebWorkers. That work has been staled in our pipeline due to TS mismatches between the dependency being introduced and the TS dependency we're currently pinned to. For context, those changes can be found [here](https://github.com/influxdata/ui/pull/6253).
This is a POC to see if bumping TS to 4.X resolves the TS issues we're seeing in the pipeline here:
#6253
The jump from 3.8.3 -> 3.9.2 resulted in a few TS errors surrounding implicit `never` types that were being assigned to merged / overriding types. Since our TS types are generated with generic `type: string` associations, the TS compiler can't …
> chore: update typescript to 4.0.2

- package.json
- src/identity/apis/org.ts
- src/types/error.ts
Closes #6292 
Pr updates openAPI SHA and updates postOrg call to handle 403 response 
> chore(org): handle 403 error for postOrg

- src/identity/components/OrganizationListTab/OrgBannerPanel.tsx
Connects #6197 
In the multiorg phase 2 (create org) epic, users who have hit their org limit in a free account (with an upgrade option to PAYG) will see a banner displayed on the new org list page, which identifies that they can upgrade and directs them to the checkout page.
This fixes the link that will be seen by free users (should take them to /checkout, not /org/:orgId/checkout).
This is behind the `createDeleteOrgs` flag.
> fix: correct url in createorg-orglist page

- CODEOWNERS
This corrects a syntax issue with #6318. The CODEOWNERS syntax requires teams with parallel code ownership status to be listed on the same line (not subsequent lines - [otherwise the later line takes precedence). ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location)This is causing ecommerce but not the UI team to be tagged on UI PR approvals.
What we want is this:
> chore: fix parallel code ownership of ui repo by ui and aim

- cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
- cypress/e2e/shared/fluxQueryBuilder.test.ts
In an effort to reduce CI pipeline costs, reviewed the top bad actors under notebooks and qx. 
https://app.circleci.com/insights/github/influxdata/monitor-ci/workflows/build/tests?branch=master
* `will allow querying of different data ranges` --> fixed with PR merged 6 days ago.
* `diverges when typing in composition block` --> Qx. skipped for now (future debugging?)
* `Export to Clipboard as Code` --> Notebooks. Likely to be deprecated. Skipped.
> fix: skip most flaky tests under old qx-team purview.

- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/dataExplorer/components/ResultsPane.tsx
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/Sidebar.tsx
- src/dataExplorer/context/persistance.tsx
- src/shared/components/FluxMonacoEditor.tsx
Part of influxdata/idpe#16468
Close #6314 
Since the feature flag `uiSqlSupport` has been turned on for more than a week and the UI behind this feature flag has been stable, this PR removes this flag and makes SQL support to be enabled by default for IOx customers in UI. After this PR is merged, I'll remove the feature flag from idpe.
> chore: remove feature flag `uiSqlSupport`

- package.json
- src/operator/OrgOverlay.tsx
This adds the state field to the org overlay in the operator UI.
> chore: add state field to the operator org overlay

- cypress/e2e/cloud/globalHeaderOrgMenuItems.test.ts
- cypress/fixtures/createOrgAllowance.json
- cypress/fixtures/createOrgAllowanceContract.json
- cypress/fixtures/createOrgAllowancePAYG.json
- cypress/support/Utils.ts
- src/identity/allowances/actions/creators/index.ts
- src/identity/allowances/actions/thunks/index.ts
- src/identity/allowances/reducers/index.ts
- src/identity/apis/auth.ts
- src/identity/apis/org.ts
- src/identity/components/GlobalHeader/OrgDropdown.tsx
- src/identity/selectors/index.ts
- src/store/configureStore.ts
Closes #6224 
Pr adds org creation allowance property to the Identity state in redux and uses `state.identity.allowances.orgCreation` to determine whether the user can create organizations.
Pr also refactors code to replace use of `accountType` with  `state.identity.allowances.orgCreation` to determine whether the Upgrade button should be shown in the global header. 
behind `createDeleteOrgs` feature flag
https://user-images.githubusercontent.com/66275100/202481864-032d0b98-a36f-44fe-9485-eb45ec23821d.mov
> feat(Identity): use account allowances state to allow org creation

- src/identity/allowances/actions/thunks/index.ts
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/CreateOrganization/CreateOrgInput.tsx
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/CreateOrganization/CreateOrganizationOverlay.tsx
- src/shared/copy/notifications/categories/accounts-users-orgs.ts
Closes #6267 
This PR adds a notification and associated business logic so that, after a user creates a new org, the allowances endpoint is re-queried. If the response indicates no more orgs can be created in the account, it sends the user a notification indicating that they have hit their organization quota. Design is per [this figma].(https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1961%3A18041&t=5XorbJgkM9q43DnN-0).
https://user-images.githubusercontent.com/91283923/203148438-4e562358-7126-44de-8845-b8267eab80ed.mov
> feat: on creating last org in account, user gets an upgrade notification

- src/accounts/context/userAccount.tsx
- src/identity/components/userprofile/UserDefaults.tsx
Closes #6336 
On initial load, the app hits the /accounts endpoint three times. This PR reduces it to one call.
Root cause is a `useEffect` hook that has been hanging out in the user account context. The hook calls a function (`handleGetAccounts`) that fetches from `/accounts` on initial app load, or when there is a change in the value of the user's `defaultAccountId` or `activeAccountId`. Since `handleGetAccounts` itself sets the `defaultAccountId` and `activeAccountId` based on the array the endpoint returns, we end up with three API calls: (1) when the context loads; (2) when the context sets the default account id based on the response; (3) when the context sets the active account id based on the response.
There's no need for the `defaultAccountId` dependency because the user's new …
> fix: only one /accounts call on app load

- src/cloud/notifications/account-settings-notifications.ts
- src/identity/components/OrganizationListTab/OrgBannerPanel.tsx
- src/identity/components/OrganizationListTab/index.tsx
Closes #6338 
Multiple components in the UI now require access to the data returned from the /orgs/allowances/create endpoint. Since this data is now fetched on application load and stored in redux state, this PR makes the organization list tab rely on the state stored in redux so that no new API call is required.
In the edge case where the data isn't loaded in redux state yet, a thunk is dispatched.
Before
--
https://user-images.githubusercontent.com/91283923/203386402-be7ee284-7515-48ed-ac55-8fdff9349788.mov
After
--
https://user-images.githubusercontent.com/91283923/203386407-dc6f40e9-6fde-482c-8d15-30421bba21a8.mov
> chore: make org list tab use allowances state

- package.json
- src/identity/apis/org.ts
- src/identity/components/GlobalHeader/DefaultEntities.tsx
- src/identity/components/GlobalHeader/GlobalHeader.tsx
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/CreateOrganization/CreateOrganizationOverlay.tsx
- src/identity/components/GlobalHeader/IdentityUserAvatar.tsx
- src/identity/components/OrganizationListTab/index.tsx
- src/identity/components/userprofile/UserDefaults.tsx
- src/identity/quartzOrganizations/mockOrgData.ts
- src/identity/quartzOrganizations/reducers/index.ts
- src/identity/selectors/index.test.ts
- src/identity/selectors/index.ts
Closes #5935 
The list of all orgs in an account now includes a `state` property to indicate whether each org is `provisioned`, `pending`, or `suspended`. 
This PR adds a new selector for provisioned orgs, so that only those organizations are shown in the global app header, and on the profile page for changing default orgs. 
Edit: added unit tests to ensure the `selectQuartzActiveOrg` selector is working as expected.
Unit tests may not be used by CI until [this issue](https://github.com/influxdata/ui/issues/6346) is resolved.
Before
--
https://user-images.githubusercontent.com/91283923/204320736-f96d2e43-d479-47db-bf78-f35bb04c99fc.mov
After
--
https://user-images.githubusercontent.com/91283923/204321084-464266e1-7450-4342-bba9-b69cd0796cad.mov
Quartz-Remocal Testing
-- …
> chore: filter inactive orgs from global header and user profile

- cypress/support/commands.ts
Allows for testing with iox from cypress tests.
Passing `useIox: true` in `cy.signin` is one way to run a single test against Iox. Setting env var `CYPRESS_useIox=true` will run all the tests against Iox.
This PR does not change existing testing behavior, it just allows for customization in future PRs.
> chore: add ability to use Iox org in tests

- package.json
- src/operator/OrgOverlay.tsx
- src/operator/context/overlay.tsx
- src/shared/copy/notifications/categories/operator.ts
Part of influxdata/quartz#6866
As part of Multi-Org, this adds a button to the operator UI to reactivate a suspended organization. This is only available to PAYG organizations that are suspended, but have not yet been deleted.
I made a fix to the OpenAPI Spec, hence the SHA change: https://github.com/influxdata/openapi/pull/620
> feat(aim): Add Reactivate Org Button

- src/identity/components/GlobalHeader/GlobalHeaderDropdown/index.tsx
- src/identity/components/GlobalHeader/OrgDropdown.tsx
- src/identity/components/MarketoAccountUpgradeOverlay.scss
- src/identity/components/MarketoAccountUpgradeOverlay.tsx
- src/identity/components/OrganizationListTab/OrgBannerPanel.tsx
- src/identity/selectors/index.ts
- src/overlays/components/OverlayController.tsx
- src/overlays/reducers/overlays.ts
- src/shared/copy/notifications/categories/accounts-users-orgs.ts
Closes #6206 
Adds the 'marketo' form used to contact support if the user elects to upgrade their account to add more organizations. 
When the `createDeleteOrgs` FF is on and the user has hit their org quota in the current account, the 'Upgrade to Create More Organizations' ad appears both in the global header, and also on the banner that displays on the orgslist page. Clicking that ad pulls up this overlay.
Since the data being submitted to associate the user with the sales inquiry already exists in the client redux state, we don't need to actually _display_ the marketo form to the user. For simplicity (and to avoid inserting the inconsistent marketo stylings into the app), this PR instead hides the form itself, and uses the Marketo Forms API to submit the form with our stock clockface …
> feat: add marketo overlay to orgs list and global header

- src/shared/workers/downloadHelper.ts
We're seeing CI test failures in remocal-ui-test-firefox-1-tsm-shared/explorer that seem tied to recent changes to the csv downloader and explorer test. There's a service worker that appends a new content-type header. Proper behavior is to set rather than append the content-type header. 
The cred goes to @hoorayimhelping for tracking this down.
> fix: fix shared/explorer test with overwrite, rather than append request header in downloadhelper

- CODEOWNERS
Removes the Data Acquisition team from the codeowners file, since 2/3 of the team is gone and the sole remaining member is working in other domains.
> chore: remove data acquisition from codeowners

- cypress/e2e/shared/explorer.test.ts
Hotfix current CI blockage.
* explorer tests have begun timing out without failure:
* https://app.circleci.com/pipelines/github/influxdata/monitor-ci/18092/workflows/0543693d-be04-4647-a709-4a149de97935/jobs/1285612
* https://app.circleci.com/pipelines/github/influxdata/monitor-ci/18087/workflows/e5af1ea5-70f5-4e22-b742-c6dca3c49091/jobs/1285232
* https://app.circleci.com/pipelines/github/influxdata/monitor-ci/18085/workflows/681f11a6-6128-4703-ad8f-272aff1389bf/jobs/1284833
* https://app.circleci.com/pipelines/github/influxdata/monitor-ci/18076/workflows/7433d3a2-fac9-46f3-a264-f4dd1575552f/jobs/1283822
* Not sure of the root cause. Test the below scenarios in 20x test runs:
* Attempting various explicit timeout controls at any waiting points...no dice.
* Tried with latest service worker …
> fix: skip flaky csv download test for explorer.

- src/identity/components/MarketoAccountUpgradeOverlay.scss
- src/identity/components/MarketoAccountUpgradeOverlay.tsx
Connects #6206 
This PR implements the UI side of changes by sales to the Marketo form to add user email and a comments field. This data is needed to associate submissions of the form with a specific user/account combination.
https://user-images.githubusercontent.com/91283923/205763653-5e63fae6-4da4-4d29-a8e6-5cdd451cfafd.mov
> feat: add email and comment fields to marketo account upgrade form

- src/identity/components/OrganizationListTab/OrgList.tsx
- src/identity/components/OrganizationListTab/OrganizationCard.scss
- src/identity/components/OrganizationListTab/OrganizationCard.tsx
See #5477 
Pr adds unique styling and deletion status indicator for orgs that are in the process of deletion. In addition, for users looking to reactive or recover their org, it adds a tooltip with link to InfluxData support. 
> feat(identity): show deleted org status in orgs list

- src/identity/components/MarketoAccountUpgradeOverlay.tsx
Closes #6380 
Adds the first name and last name fields to the marketo form used for upgrading the org quota for PAYG or Contract accounts. 
> chore: add firstName and lastName fields to marketo form

- src/shared/components/CSVExportButton.tsx
- src/shared/contexts/app.tsx
- src/shared/workers/downloadHelper.ts
- src/shared/workers/serviceWorker.ts
- tsconfig.json
- webpack.fast.ts
- webpack.prod.ts
Closes https://github.com/influxdata/EAR/issues/3809.
Upon registration the service worker takes [the scope ](https://web.dev/service-worker-lifecycle/#scope-and-control)(by default) of its path. In the webpack dev build, that is `<origin>/`. In the prod build, that is `<origin>/static`. The network intercepts only work within that path; meaning a fetch `<scope>/restOfRequestPath`.
* explicitly set the scope, when registering the worker.
* `{scope: '/api/v2/query'}` which is relative to the current scope
* browser security only allows scope narrowing, not broadening, of the resource path.
* What this means is that:
* the script registering the worker must the served from `<origin>/<filename>`  , not `<origin>/static/<filename>`.
* the script of the worker worker itself must also …
> fix(EAR-3809): explicitly set service worker scope

- src/identity/components/OrganizationListTab/OrganizationCard.scss
fix to remove a small indentation of active org name in the org list page. 
Before 
After
> fix: remove indentation of active org name

- package.json
Updates the openAPI sha to add the appropriate content-type for the delete orgs endpoint: https://github.com/influxdata/openapi/pull/623.
> chore: update openapi sha for delete org

- package.json
- yarn.lock
upgrades @babel/runtime to 7.20.6
> chore: upgrade @babel/runtime to latest

- src/languageSupport/languages/flux/lsp/worker/flux.worker.ts
Since this topic keeps coming up in conversation, decided to document in code. For our future selves.
The current time and ordering dependencies of how the LSP server boots up.
> chore: document in code the tech debt behind the LSP worker buffer.

- package.json
- src/identity/components/GlobalHeader/AccountDropdown.tsx
- yarn.lock
Closes #6215 
Updates the Organization List icon in the account dropdown from this:
To what is planned in the multi org figma:
This PR also bumps clockface up two versions, to include this icon.
Validate UI Based on Clockface Upgrade:
--
https://user-images.githubusercontent.com/91283923/207457376-b2545de3-4cb1-47fd-b41d-e2a797cc75ba.mov
> chore: change orgs icon in accounts dropdown

- package.json
- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/lsp/utils.ts
- yarn.lock
Part of https://github.com/influxdata/ui/issues/6334
Closes https://github.com/influxdata/ui/issues/6341
Note: this is part of a chain of PRs.
`staging/yieldless-composition`  <-- 1st PR <-- 2nd PR <-- 3rd PR
The final staging branch will be the merge into master.
1. this PR.
2. https://github.com/influxdata/ui/pull/6374
3. https://github.com/influxdata/ui/pull/6397 where tests finally pass!
Closes #6341  (`FIRST TASK` on the epic, UI side changes).
That^^ issue ticket describes in detail, on why these changes were required.
Video of current status after UI and flux-lsp `FIRST TASK` changes:
https://user-images.githubusercontent.com/10232835/203626079-946b8ed6-2c4a-47a3-8106-8384306d265b.mov
> feat(6341): get basic composition working with yieldless

- src/dataExplorer/components/SchemaBrowserHeading.tsx
- src/dataExplorer/context/fluxQueryBuilder.tsx
- src/dataExplorer/context/persistance.tsx
- src/languageSupport/languages/flux/lsp/connection.ts
- src/languageSupport/languages/flux/lsp/monaco.flux.lsp.ts
- src/languageSupport/languages/flux/lsp/types/executeCommand.ts
- src/languageSupport/languages/flux/lsp/types/index.ts
- src/languageSupport/languages/flux/lsp/types/methods.ts
- src/languageSupport/languages/flux/lsp/types/showMessage.ts
- src/languageSupport/languages/flux/lsp/utils.ts
- src/languageSupport/languages/flux/lsp/worker/flux.worker.ts
- src/shared/components/FluxMonacoEditor.tsx
- src/shared/components/MonacoEditor.scss
- src/shared/contexts/editor/index.tsx
- src/shared/copy/notifications/categories/dashboard.ts
Part of https://github.com/influxdata/ui/issues/6334
Note: this is part of a chain of PRs.
`staging/yieldless-composition`  <-- 1st PR <-- 2nd PR <-- 3rd PR
The final staging branch will be the merge into master.
1. https://github.com/influxdata/ui/pull/6344
2. this PR.
3. https://github.com/influxdata/ui/pull/6397 where tests finally pass!
Closes #5926 — trace/intercept lsp requests from the server
Closes #5717, #5305 — build a middleware, or equivalent solution, to prevent composition from getting out of sync with ui
Closes #5925 — surface to user the errors
Each commit gives a rough outline of the item done. ("Rough" because broke up the commits after the fact.). A high level summary is:
* break out the lsp-related types into a submodule. Divided into client-initiated commands …
> feat(6334): UI responds at acts upon LSP-initiated commands, as a result of new yieldless paradigm.

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/languageSupport/languages/flux/lsp/connection.ts
Part of https://github.com/influxdata/ui/issues/6334
Note: this is part of a chain of PRs.
`staging/yieldless-composition`  <-- 1st PR <-- 2nd PR <-- 3rd PR
The final staging branch will be the merge into master.
1. https://github.com/influxdata/ui/pull/6344
2. https://github.com/influxdata/ui/pull/6374
3. this PR.
Update tests to handle yieldless composition. This includes:
* remove any references to `|> yield()` transformation
* remove the concept of composition divergence. (Since this no longer exists.)
* handle slightly different timings, in how the stateful composition works.
> feat(6334): update tests to handle yieldless composition

- src/languageSupport/languages/flux/lsp/connection.ts
Issue seen in prod, were fields and tagValues added are not being sent to the LSP.
Reason is because this line, added after the local manual QA:
```
const hasMultipleItemsToSync =
Object.keys(toAdd).length + Object.keys(toRemove).length > 1
```
Therefore, we cannot add empty `toAdd.fields = []` etc in the diffing method.
Hotfix now. Later PR will add test coverage to prevent regression.
> fix: for new yieldless composition, hasMultipleItemsToSync requires to empty keys.

- src/writeData/clients/Java/write.2.example
java pojo api error code example
‘writeMeasurement’ should be used, rather than use ‘writeRecord’
> fix: java pojo api error code example

- cypress/e2e/cloud/about.test.ts
- src/organizations/components/OrgProfileTab/DeletePanel.tsx
Closes #6396 
For proof of concept use cases we want the ability to give a user more than one org in a free account - and to be able to delete those orgs. This PR adjusts the logic for the 'delete' buttons on the org settings page.
Old Behavior:
- In a free account, your only "delete" option is to delete the free account. 
- If the `createDeleteOrgs` FF is on, a payg or contract account can delete the currently active org.
New Behavior:
- If you're in a free account with _only one org_, same behavior as before (only option is to delete the free account).
- If the `createDeleteOrgs` FF is on (and you're not in a free account with only one org), you can delete the current org.
> chore: allow free org with non-default allowances to delete org

- cypress/e2e/shared/fluxQueryBuilder.test.ts
Need to boost test coverage in schema composition. Already had a regression this week.
Tested with the 20x runs in CI. To help reduce flake.
.
Broken out per commit:
* make explicit `DELAY_FOR_LAZY_LOAD_EDITOR` versus `DELAY_FOR_LSP_SERVER_BOOTUP`
* debug existing tests
* new tests:
* LSP composition construct be it's own test case.
* Include add/remove fields, add/remove tags.
* magic number tuning, to handle slower CI cypress test runs. 😭
> chore: boost test coverage composition

- src/flows/actions/flowsActions.ts
- src/flows/actions/flowsThunks.ts
- src/flows/reducers/flowsReducer.ts
- src/flows/selectors/flowsSelectors.ts
- src/shared/containers/GetOrganizations.tsx
- src/store/configureStore.ts
- src/types/resources.ts
Connects: https://github.com/influxdata/idpe/issues/16723
- Creates the redux machinery to store a list of notebooks in redux state for simple checking if an org has notebooks.
- Calls the thunk in `GetOrganizations` after `org.id` is retreived. This makes a request across the wire and stores notebooks in redux state
- Nothing is currently done with the notebooks in state, that will come in a future PR
This doesn't use the existing flows context in order to avoid wrapping most of the appliction in the flows provider, which seems an odd thing to do when deprecating a feature. This also avoids potentially re-rendering of the entire application (since `GetOrganizations` is a component that is at the root of nearly every other component in the application) when a single thing in flows is …
> feat(notebooks): add actions, thunks, reducer, selector for checking if org has notebooks

- cypress/e2e/cloud/globalHeader.test.ts
- src/Authenticate.tsx
- src/onboarding/containers/CloudLoginPage.tsx
Helps with #5771
Removes the `quartzSession` feature flag from the UI, which controls the use of quartz in lieu of IDPE for authentication. This has been on in all cloud environments without issue since 10/14 so no change in behavior is expected.
`quartzSession` is a flag for which auth is not required, so it is retrieved from the `/api/v2private/flags` endpoint and used in prod before the first authentication request is made.
Proof
--
Separately tested this in quartz-remocal to ensure no change in behavior.
Login unaffected
--
https://user-images.githubusercontent.com/91283923/208174937-2cd7f46a-ff68-4428-852f-f30be0c76ed7.mov
API Calls
--
There is still a call to api/v2/me for now - but it's not being used for auth. That's the thunk call that is still required by certain parts of the …
> chore: remove quartzSession flag

- cypress/e2e/shared/fluxQueryBuilder.test.ts
- src/languageSupport/languages/flux/lsp/connection.ts
- src/shared/components/MonacoEditor.scss
When we merged the yieldless work, we forgot that there is still a use case for composition-off styling. As the user can still toggle the composition sync on/off, and need a visual indicator.
Working -- Composition could be sync'ed on/off.
Not working -- the styling was not appropriately updating to match.
Toggling styling, whenever sync is toggled.
Still enable the LSP to overwrite the styling. (e.g. in the video, you can see the dropped composition at the end --> which removes the style completely and turns off sync.)
https://user-images.githubusercontent.com/10232835/208490906-aa31b06e-0f23-47bd-864c-80d98cc2c010.mov
> fix: re-enable sync off styling, for composition

- src/languageSupport/languages/flux/parser/index.ts
Follow up to https://github.com/influxdata/flux-lsp/issues/618
The LSP wasm [was panicking](https://github.com/influxdata/flux-lsp/issues/618) due to use of a logger which was [not compatible with wasm](https://github.com/influxdata/flux-lsp/pull/619#issue-1485914085). The recent LSP version bump included:
1.  a global wasm logger init whenever the [LSP server was init](https://github.com/influxdata/flux-lsp/pull/619).
* no UI change required, outside of the version bump
2. the option to [manually init the wasm logger](https://github.com/influxdata/flux-lsp/pull/621), when the LSP utils methods are used without the LSP server being init first
* this does require calling `initLog()` in the UI, to handle race condition if LSP server is not loaded --> but LSP utils methods are used
* setting …
> chore: use initLog() in utils, to handle use case when LSP server is not loaded

- package.json
- src/operator/OrgOverlay.tsx
Removes the cardinality limit from the UI for iOX-enabled organizations. This will require a new SHA pending influxdata/openapi#625.
> feat(aim): Hide Cardinality for iOX Orgs

- src/identity/components/GlobalHeader/GlobalHeaderDropdown/CreateOrganization/CreateOrganizationOverlay.tsx
- src/identity/components/GlobalHeader/GlobalHeaderDropdown/CreateOrganization/MenuItem.tsx
- src/identity/components/GlobalHeader/OrgDropdown.tsx
- src/identity/components/MarketoAccountUpgradeOverlay.tsx
- src/identity/components/OrganizationListTab/OrgBannerPanel.tsx
- src/identity/events/multiOrgEvents.ts
- src/identity/selectors/index.ts
- src/organizations/components/OrgProfileTab/DeletePaidOrgOverlay.tsx
Closes #5707 
Pr adds UI eventing for multi org phase 2 features 
All events introduced in this pr are documented [here](https://influxdb.atlassian.net/wiki/spaces/IPO/pages/2530574337/UI+Eventing+Dictionary). 
Events fire...
> feat: add ui eventing for multi-org phase 2

- .circleci/config.yml
- docker/Dockerfile.chronograf
- docker/Dockerfile.chronograf.prod
- docker/Dockerfile.cypress
- package.json
closes #4487
PR upgrades node from v14.17 -> v18.12.1 (LTS)
> chore: upgrade node to version 18.12.1

- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/flows.test.ts
- cypress/e2e/shared/flowsAlerts.test.ts
- cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
- cypress/e2e/shared/legends.test.ts
- cypress/e2e/shared/secrets.test.ts
- cypress/support/commands.ts
- src/flows/selectors/flowsSelectors.test.ts
- src/flows/selectors/flowsSelectors.ts
- src/organizations/selectors/index.ts
- src/pageLayout/containers/MainNavigation.tsx
- src/shared/constants/index.ts
- src/shared/containers/SetOrg.tsx
- src/shared/selectors/flags.ts
Closes https://github.com/influxdata/idpe/issues/16723
See the above linked ticket for a flowchart describing the logic of showing or hiding notebooks.
Notebooks will be hidden in the UI's navigation and the routes will throw 404s under the following conditions:
- the organization was created on or after January 31, 2023
- the organization was created before January 31, 2023, but has no saved notebooks
All other organizations will show notebooks.
> feat(notebooks): conditionally hide notebooks if specific conditions are met

- src/organizations/components/OrgProfileTab/DeletePanel.tsx
- src/shared/components/notifications/NotificationButtons.tsx
- src/shared/copy/notifications/categories/accounts-users-orgs.ts
- src/shared/copy/notifications/categories/billing-checkout.ts
Helps with #5245
In working on e2e tests for the delete-orgs page, I noted that free account deletion is blocked if there are other users in the current account. Multi-org does not currently notify that there are other users in the org, or require a user to remove the other users in the org before hitting delete.
This PR will (once the feature flag for creating and deleting PAYG/Contract orgs is turned on in prod) make the ability to delete PAYG or contract orgs in the UI contingent on the current user removing the other users from the org. This is easily reverted if removal of the other users in the org is not desirable or required before deletion.
An alternative would be to warn the current user that there are other users in the org, but let them proceed with deletion of the org anyway. …
> chore: add warning if deleting payg or contract org with other users

- cypress/support/Utils.ts
Helps with #5245 
To ensure the tests in [this PR](https://github.com/influxdata/ui/pull/6438) are run 20x against chrome (not just once against all of CI), that PR must contain only updates to test files. 
This PR makes a necessary update to a cypress util that is used to synchronize idpe and quartz-mock for purposes of e2e tests for use in that PR.
> chore: update idpe-quartz sync function for delete-org tests

- cypress/e2e/cloud/org-list.test.ts
Closes #5245 
Adds end to end tests for the Account Page - Org List tab.
https://user-images.githubusercontent.com/91283923/209964623-9d5a70c9-ff04-4506-9386-1c31f41cdfc1.mov
> feat: add e2e tests for the account/orgslist page

- src/accounts/AccountPage.tsx
- src/accounts/AccountPageStyles.scss
- src/organizations/components/OrgProfileTab/DeletePanel.tsx
- src/organizations/components/OrgProfileTab/LeaveOrg.tsx
- src/organizations/components/OrgProfileTab/index.tsx
- src/organizations/components/OrgProfileTab/style.scss
- src/users/components/UserListItem.tsx
- src/users/context/users.tsx
Closes #6434 
Pr introduces change in Orgs settings page by adding `Leave Organization` button (behind `createDeleteOrgs` feature flag. 
When flag is off, The button is displayed only inside Account's settings page. 
Orgs Settings page when `createDeleteOrgs` feature flag is on (updated image: Leave org comes before Delete)
Orgs Settings page when `createDeleteOrgs` feature flag is off
https://user-images.githubusercontent.com/66275100/210096412-1f8a19fc-d5a2-43f1-9ef9-9f2d725e93dd.mov
Accounts Settings page when `createDeleteOrgs` feature flag is on 
https://user-images.githubusercontent.com/66275100/210096505-749efe39-b850-4a24-bbe4-eb1131d73884.mov
Accounts Settings page when `createDeleteOrgs` feature flag is off
https://user-images.githubusercontent.com/66275100/210096584-415dc095-173 …
> feat(OrgProfileTab): add Leave Org button in Org settings page

- src/languageSupport/languages/flux/lsp/connection.ts
Closes #6429 
This PR fixes a bug in flux composition that upon a new measurement selection on an existing flux composition, the LSP went out of sync with the UI. 
https://user-images.githubusercontent.com/14298407/210408168-83e08512-acdc-4871-a90a-e83a33ebfc28.mov
https://user-images.githubusercontent.com/14298407/210430599-63b18454-2fef-4aad-bac8-a6e29bf9d7ed.mov
> fix: keep flux in sync when select a new measurement with existing fields and tag values selection

- cypress/e2e/cloud/deepLinks.test.ts
- src/utils/deepLinks.ts
Closes #5244 
Multiorg phase 2 added an "organization list" tab to the Accounts page so that users can browse the statuses of all organizations in the current account. This adds a deeplink to that page.
This also adds an intercept to ensure the link actually works properly - since e2e tests run against the mock, we need to intercept the real IDPE org ID and make the mock use that ID.
> chore: add deeplink for multiorg phase 2

- src/checkout/context/checkout.tsx
Closes #6457 
Calls the thunk for refreshing the organization creation allowance after a user checks out. 
When checking out from free to PAYG, the user's org creation allowance must be updated so that they are immediately able to create additional orgs, up to the PAYG default (3), and increase from the Free default (1).
This is feature flagged because the organization creation allowance is not used unless the `createDeleteOrgs` FF is on.
> chore: refresh org creation allowance after free-checkout

- .circleci/config.yml
- cypress/e2e/cloud/buckets.test.ts
- cypress/e2e/shared/checks.test.ts
- cypress/e2e/shared/dashboardsRefresh.test.ts
- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/explorer.queries.graphs.test.ts
- cypress/e2e/shared/scriptQueryBuilder.flux.test.ts
- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- cypress/support/commands.ts
- cypress/support/index.js
- package.json
- src/dataExplorer/components/FluxQueryBuilder.tsx
- src/shared/contexts/buckets.tsx
- yarn.lock
Part of https://github.com/influxdata/monitor-ci/issues/402
~Revert the 1st commit, so we point to monitor-ci master branch.~ DONE. Reverted.
Then the remocal-iox e2es will only run (on merge queue) once the other 2 PRs in k8s-idpe and monitor-ci are merged.
**Basic upgrade to fixtures:**
* handle conditional testing scenarios, based on "if iox":
* new command `cy.isIoxOrg()`
* should be used in cypress chainable, such as `return cy.isIoxOrg().then(isIox => { //do stuff })`
* new test support via `@cypress/skip-test`
* main commands are `cy.skipOn(boolean)` and `cy.onlyOn(boolean)` 
* be able to run your iox e2es locally.
* `test:e2e:remocal:iox` 
**Specific modification in tests, in order to handle iox:**
* handle remocal-iox setup nuances:
* orgIDs which need to be escaped (e.g. the CI …
> feat(monitor-ci/402): get remocal-iox e2es passing

- cypress/e2e/cloud/about.test.ts
- package.json
- src/organizations/components/OrgProfileTab/index.tsx
- src/organizations/selectors/index.ts
Closes [AIM #7058](https://github.com/influxdata/quartz/issues/7058)
Adds display on the org profile page to disclose whether the current org is an iox or a tsm org. Adds associated cloud2 e2e test.
> feat: add storage type to org profile page

- src/writeData/clients/Ruby/executeFull.example
Related to https://github.com/influxdata/influxdb-client-ruby/pull/127
The **InfluxDB::Client** can be also used as a resource:
```ruby
InfluxDB2::Client.use('https://localhost:8086', 'my-token') do |client|
client.do_something
end
```
> chore(client_libs): use ruby client as a resource

- docker/Dockerfile.chronograf.prod
- package.json
- src/cloud/utils/reporting.ts
- src/shared/constants/index.ts
- yarn.lock
Connects #6463
Removes calls to Amplitude from the app-metrics eventing system. The people who championed Amplitude as our analytics system don't work here anymore, and no one is using it.
> chore: remove amplitude

- src/shared/components/TimeSeries.tsx
- src/timeMachine/actions/queries.ts
Closes #6363 
This PR removes the legacy function `getOrgIDFromBuckets`. See the original issue for the reason. 
This PR also removes one of the `parse()` item related to #6447 
> chore: remove `getOrgIDFromBuckets`

- cypress/e2e/cloud/about.test.ts
- src/organizations/components/OrgProfileTab/DeletePanel.tsx
- src/organizations/components/OrgProfileTab/SuspendPaidOrgOverlay.tsx
Closes #6450 
Currently in the UI, if a non free account user tries to delete an org with multiple users associated with it, the deletion process gets blocked by a notification warning user to remove other users first before deleting the org. 
Pr removes this block (notification) and instead display the delete org overlay that allows user to delete org. The number of users associated with the org will now be shown inside the overlay, and when clicked, user will be redirected to the members page as shown in the demo below. 
> feat: 'remove users first' block on deleting orgs in payg/contract accounts

- src/languageSupport/languages/sql/connection.ts
I stumbled on this while playing around with SQL queries. I don't know what I did to get the app in this state. It might be transient, because when I go to the same page in a new tab/window, everything works. It's only in the existing tab I have that this crash happens. It's been very difficult to re-trigger it, but it seems to be related to having an empty `WHERE` clause and then removing all keys from the clause.
Regardless, if I ran into it, it means it's probably possible for a user to run into it, so I added this fix, which causes the crash not to happen locally.
> chore(sql-composition): guard against null pointer exception

- .circleci/config.yml
Closes https://github.com/influxdata/ui/issues/6346
Add `shopt -s globstar` to circleci's config so that it can explicitly get the correct glob to run all tests.
```sh
Test Suites: 1 skipped, 168 passed, 168 of 169 total
Tests:       35 skipped, 954 passed, 989 total
```
```sh
Test Suites: 43 passed, 43 total
Tests:       22 skipped, 235 passed, 257 total
```
```sh
Test Suites: 42 passed, 42 total
Tests:       1 skipped, 258 passed, 259 total
```
```sh
Test Suites: 42 passed, 42 total
Tests:       1 skipped, 247 passed, 248 total
```
```sh
Test Suites: 1 skipped, 41 passed, 41 of 42 total
Tests:       11 skipped, 214 passed, 225 total
```
```sh
Test Suites: 1 skipped, 168 passed,  168 of 169 total
Tests:       35 skipped, 954 passed, 989 total
```
```sh
Test Suites: 1 skipped, 168 passed, …
```
> ci: update circleci config so it properly recurses all files

- cypress/e2e/cloud/globalHeader.test.ts
- cypress/fixtures/multiOrgIdentityContract.json
- cypress/fixtures/multiOrgIdentityPAYG.json
- src/cloud/components/CardinalityLimitAlertContent.tsx
- src/cloud/components/CardinalityLimitOverlay.tsx
- src/cloud/components/RateLimitAlert.tsx
- src/me/selectors/index.ts
- src/overlays/components/OverlayController.tsx
- src/overlays/reducers/overlays.ts
- src/usage/RateLimits.tsx
- src/usage/UsagePage.tsx
- src/usage/UsageToday.tsx
Helps with [AIM 7046](https://github.com/influxdata/quartz/issues/7046)
Eliminates ability to generate a cardinality rate limit alert if org is iox.
Hit Cardinality Limit - TSM - Account is Upgradeable (Banner Has Upgrade Button)
--
Hit Cardinality Limit - TSM - Account Not Upgradeable (Banner Has No Upgrade Button, only "Inspect Series Cardinality")
--
Hit Cardinality Limit - TSM - Account Not Upgradeable (Inspect Series Cardinality Overlay)
--
The Limit Does Not Exist - IOx
--
> chore: RateLimitAlert - cardinality alerts only in non-iox orgs

- cypress/e2e/cloud/billing.test.ts
- src/billing/components/Free/FreePanel.tsx
- src/billing/components/Free/OrgLimits.tsx
- src/billing/components/Free/PAYGConversion.tsx
Helps with [AIM 7046](https://github.com/influxdata/quartz/issues/7046)
Removes cardinality references from the org limits page when an org is an iox org. Adds corresponding test.
This component needed a refactor because it was too complicated, and the variable names obscured what it was doing. It renders 9 limit cards. The reason it was confusing is that the data from the api comes in three different formats, so different render logic is needed for the buckets limits, rate limits, and other limits. 
This goes partway to simplifying it for the next person. The better fix would be to change the data shape, but that would require some heavier lifting in other components.
Not an IOx Org
--
An IOx Org
--
> chore: no cardinality on orglimits page if org is iox; simplify limits

- src/buckets/components/context/lineProtocol.tsx
- src/buckets/components/lineProtocol/configure/LineProtocolTabs.tsx
- src/buckets/components/lineProtocol/verify/StatusIndicator.tsx
- src/writeData/components/fileUploads/UploadDataDetailsView.tsx
- src/writeData/containers/FileUploadsPage.tsx
Helps with AIM [7046](https://github.com/influxdata/quartz/issues/7046)
The line protocol context manages error messages that are shown when an attempt to upload a document in line-protocol format fails. One example is 'Failed due to plan limits: read cardinality reached' when the `postWrite` endpoint returns a `429` status code in Cloud2. 
IOx orgs don't have cardinality. But more broadly, the error message isn't right because the `429` from that endpoint isn't identifying a cardinality exceedance specifically. See the [openapi spec](https://github.com/influxdata/openapi/blob/master/src/common/paths/write.yml). The `429` is just a rate-limit code for exceeding plan limits. In TSM that can be read, write, or cardinality; in IOx, read or write. This makes the error messages reflect that. …
> chore: fix cardinality messaging in line protocol provider

- cypress/e2e/shared/scriptQueryBuilder.flux.test.ts
- cypress/e2e/shared/scriptQueryBuilder.sql.test.ts
Part of #6282 
Script Builder e2es for SQL Composition.
Is slightly different UX from flux composition -- but is close. `cy.log()` comments doc the differences.
> feat(6282): add SQL composition e2es

- cypress/e2e/cloud/billing.test.ts
- src/billing/components/PayAsYouGo/CancelServiceContext.tsx
- src/billing/components/PayAsYouGo/CancelServiceReasonsForm.tsx
- src/billing/components/PayAsYouGo/CancellationOverlay.tsx
- src/billing/components/PayAsYouGo/CancellationPanel.tsx
- src/billing/components/PayAsYouGo/TermsCancellationOverlay.tsx
- src/cloud/components/RateLimitAlert.tsx
Helps with [AIM 7046](https://github.com/influxdata/quartz/issues/7046)
When canceling service in PAYG, the user is presented with options to identify why they're leaving. This PR drops the cardinality 'reason' if the org is iox (since cardinality wouldn't be a reason).
The remaining changes reflect some tidying up and readability improvements.
Not IOx Org
--
IOx Org
--
> chore: remove cardinality option from cancel service context if org type is iox

- cypress/e2e/cloud/userAccounts.test.ts
- src/accounts/AccountPage.tsx
Closes #6472 
Pr removes restriction preventing free account deletion if the account has more than one org. 
With this change, users will now be able to delete their accounts regardless of the numbers of orgs associated with the account.
> chore: remove org count restriction

- src/dataExplorer/components/DeleteScript.tsx
- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
- src/dataExplorer/components/SqlViewOptions.scss
- src/dataExplorer/components/SqlViewOptions.tsx
- src/dataExplorer/context/results/childResults.tsx
- src/dataExplorer/context/resultsView.tsx
- src/dataExplorer/context/tags.tsx
Part of #6482 
Closes #6496 
Closes #6503
Add ability to groupby tagKeys (a.k.a. into dataSeries) for SQL queries being graphed.
* how many queries (network calls) are run:
* when I change by query viewOptions => re-run the query
* if I change queryText => have no viewOptions => only 1 query with run (see network tab in vid)
* if I change queryText => have viewOptions => 2 queries will run (one for table, one for graph)
* how are the groupby options chosen?
* when produce results => use the table column headers for the groupby options
* **THIS IS THE SAME CONTRACT** as displaying the table data. You have to re-run the query to produce results. 
* set the default groupby, to be the tagKeys
* once we choose the bucket & measurement => we can then know the tagKeys for the default …
> feat(6496): SQL graphing viewOptions: groupby tag keys

- src/dataExplorer/components/SchemaBrowserHeading.tsx
- src/dataExplorer/context/scriptQueryBuilder.tsx
A bit more cleanup.
Remove remaining references to "flux sync", in what is actually "composition sync".
> chore: remove remaining refers to flux in the composition sync

- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/SqlViewOptions.scss
- src/dataExplorer/components/SqlViewOptions.tsx
- src/dataExplorer/context/results/childResults.tsx
Part of #6482 
Provide the ability to see the "magic" (a.k.a. the subquery) used to populate the graph data.
Place the subquery next to the options which populate the subquery.
Note: as per [this spike](https://github.com/influxdata/ui/issues/6085#issuecomment-1380974158), we decided to:
* keep the table data as the src of truth ("this is what your SQL returns")
* have the graph data be the explorer mode
https://user-images.githubusercontent.com/10232835/213326893-3d170fe0-4271-4b07-90f7-95b632634caa.mov
> feat(6482): show graph subquery to  user

- src/organizations/components/OrgProfileTab/index.tsx
- src/organizations/containers/OrgProfilePage.tsx
Closes #6511
Resolves issue with org profile tab where "leave org" button doesn't appear to allow user to leave org with other users in it.
The UsersProvider needs to be moved up a level, from within the Org Profile Tab to above the Org Profile Tab to ensure it's possible for the "leave org" button to display.
Before
--
After
--
> chore: wrap users provider around org profile tab

- src/alerting/utils/activity.ts
- src/alerting/utils/history.ts
- src/alerting/utils/statusEvents.ts
- src/shared/components/TimeSeries.tsx
- src/shared/utils/dataListening.ts
- src/timeMachine/apis/queryBuilder.ts
- src/types/queries.ts
- src/variables/utils/ValueFetcher.ts
- src/writeData/components/fileUploads/CsvMethod.tsx
- src/writeData/components/fileUploads/UploadDataDetailsView.tsx
Part of [#7046](https://github.com/influxdata/quartz/issues/7046)
Pr removes cardinality reference inside CsvMethod component for IOx orgs and refactors files calling `runQuery` endpoint to use a predefined set of response types. 
iox: 
tsm: 
> fix(csvMethod): update rate limit error msg for iox

- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/SqlViewOptions.tsx
- src/dataExplorer/context/results/childResults.tsx
- src/dataExplorer/context/resultsView.tsx
Part of #6482 
The table view tab shows the raw output of the SQL query.
The graph view tab shows the graph subquery, based on QueryModifiers chosen on the upper right sidebar.
In this PR, we add the ability to adjust the amount of data retained when using the data smoothing. Since the graph subquery is separate from the raw table query, we also implemented a separate message when the graph subquery had truncated data.
The net result:
The user can slide down to retain fewer data points (in the smoothing) --> resulting in the entire timespace being retained for all dataseries. (Versus the raw table data still being truncated.)
* add slider to data smoothing, such that can retain more vs less data points
* surface separate msg when data is truncated, based on the graph subquery
* this is …
> feat(6482): Message separately if graph subquery hits limit

- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/SqlViewOptions.scss
- src/dataExplorer/components/SqlViewOptions.tsx
Part of #6482 
Per feedback from product, removing the "show subquery" button.
(Reason is that no flux should be show-able in the SQL editor.)
> fix(6482): remove show subquery button

- src/dataExplorer/components/SaveAsOverlay.tsx
Closes https://github.com/influxdata/idpe/issues/16723
See https://github.com/influxdata/ui/pull/6422
In Data Explorer, there's an option to save a query as a notebook. I missed this option in the initial pass in #6422. This PR applies the same conditionally logic around rendering the Save As Notebook functionality as displaying notebooks in #6422.
> chore(data-explorer): conditionally hide Save As Notebook option

- src/languageSupport/languages/sql/monaco.sql.syntax.ts
- src/shared/components/SqlMonacoEditor.tsx
> fix(6527): have the monaco-editor show sql, not pgsql

- cypress/e2e/cloud/users.test.ts
- src/organizations/components/OrgProfileTab/LeaveOrg.tsx
- src/overlays/components/OverlayController.tsx
- src/overlays/reducers/overlays.ts
- src/users/components/RemoveMemberOverlay.tsx
- src/users/components/UserList.tsx
- src/users/components/UserListItem.tsx
- src/users/context/users.tsx
Closes #5207 
Adds a new 'remove user' overlay and adjusts the users context so that, when removing a member from an organization, the user can select a different member to whom the removed member's idpe assets (tasks, alerts) should be transferred. 
Members Page: If removing another member and transferring assets, the overlay will close.
Org Settings Page: If removing _yourself_ from an organization and transferring assets, you will be redirected back to login (since you'll no longer have rights with respect to that org).
When Removing a Member, Can Transfer their Assets to a New Member
--
Create an IDPE Task
https://user-images.githubusercontent.com/91283923/214885528-3e99461d-faf8-47bb-93e9-3c2467cbf1ae.mov
Remove That User and Transfer the Task …
> feat: transfer tasks and alerts when removing a team member

- src/dashboards/selectors/index.ts
- src/dataExplorer/components/SaveAsOverlay.tsx
- src/pageLayout/containers/MainNavigation.tsx
- src/shared/containers/SetOrg.tsx
Closes #6519 
Behind feature flag `hideDashboards`
Pr hides Dashboards from CLOUD users whose orgs that are IOx enabled and are created after 1/31/23
For those orgs that meet this requirement, they will no longer see Dashboards in Navigation bar, can no longer use a link to route to Tasks, or save their queries as Dashboards.
UI demo with feature flag on and off
https://user-images.githubusercontent.com/66275100/215119690-69782052-0d1d-4b55-9eea-36f6498fc42d.mov
> chore(Dashboards): conditionally show Dashboards in UI

- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/pageLayout/containers/MainNavigation.tsx
- src/shared/components/AddResourceDropdown.tsx
- src/shared/containers/SetOrg.tsx
Closes #6520
Makes use of the feature flag `hideTemplates`
If the conditions outlined below to hide templates are met:
- Templates navigation option is removed from the Settings sub nav on the main navigation page
- Option to import a dashboard from a template is removed from the Create Dashboard dropdown button
- Option to save a dashboard as a template is removed from the dashboard card on the dashboard list page
Flow chart showing the logical progression (in the order it happens) to determine whether to show templates:
> chore: conditionally hide templates under certain conditions

- src/homepageExperience/containers/HomepageContainer.tsx
- src/me/components/AnnouncementBlock.tsx
- src/me/components/AnnouncementCenter.tsx
- src/me/components/DocSearchWidget.tsx
- src/me/components/Resources.tsx
- src/shared/components/VersionInfo.scss
- src/shared/components/VersionInfo.tsx
Closes https://github.com/influxdata/ui/issues/6533
Adds engine version (TSM/IOx) along with version number. Replaces useful links section with announcement block for IOx.
> feat(ui): add engine version and announcement for IOx

- src/dashboards/components/dashboard_index/DashboardCard.tsx
- src/dataExplorer/components/DataExplorerPage.tsx
- src/dataExplorer/components/SaveAsOverlay.tsx
- src/pageLayout/containers/MainNavigation.tsx
- src/settings/components/SettingsNavigation.tsx
- src/shared/components/AddResourceDropdown.tsx
- src/shared/containers/SetOrg.tsx
- src/shared/selectors/app.ts
Closes #6521 
Pr updates all UI deprecation flags from `hide${Resource}` to `show${Resource}InNewIOx` to show flag overrides deprecation and forces resource to display in new IOx. 
If org is iox enabled, is created after 1/31/23 and feature flag is false 
- Variables will be removed from Nav bar 
- Users wont be able to save queries as Variables in Data Explorer 
- Routing to Variables link will throw a 404
Flow Chart:
IOx enabled org created after 1/31/23:
https://user-images.githubusercontent.com/66275100/215230493-b53c2d60-332f-4a4e-97f6-ab3f1624e391.mov
> chore: conditionally render variables in the UI, correct isNewIOxOrg selector

- src/cloud/components/CardinalityLimitAlertContent.tsx
- src/cloud/components/RateLimitAlert.tsx
- src/dataLoaders/components/verifyStep/DataListening.tsx
- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/arduino/ExecuteQuery.tsx
- src/homepageExperience/components/steps/cli/ExecuteQuery.tsx
- src/homepageExperience/components/steps/cli/WriteData.tsx
- src/homepageExperience/components/steps/go/WriteData.tsx
- src/homepageExperience/components/steps/nodejs/WriteData.tsx
- src/homepageExperience/components/steps/python/WriteData.tsx
- src/shared/components/VersionInfo.tsx
- src/shared/constants/fluxFunctions.ts
- src/writeData/components/PluginCreateConfiguration/Customize.tsx
- src/writeData/components/fileUploads/CSV.md
- src/writeData/components/telegrafPlugins/dcos.md
- src/writeData/components/telegrafPlugins/http.md
- src/writeData/components/telegrafPlugins/influxdb_listener.md
- src/writeData/components/telegrafPlugins/kapacitor.md
- src/writeData/components/telegrafPlugins/kube_inventory.md
- src/writeData/components/telegrafPlugins/kubernetes.md
- src/writeData/components/telegrafPlugins/net.md
- src/writeData/components/telegrafPlugins/passenger.md
- src/writeData/components/telegrafPlugins/sflow.md
This PR updates the static version docs link to use the redirect URL that gets the latest version. It also addresses some dead docs links and replaces them with working links.
> chore(ui): update docs links to use redirect url

- cypress/e2e/shared/dashboardsIndex.test.ts
- src/pageLayout/containers/MainNavigation.tsx
- src/shared/containers/SetOrg.tsx
In local testing, if I simulate the conditions of being a new IOx org, clicking the settings link gives me a 404. The reason is that the link is still hardcoded to send the user to variables by default, which won't exist for new IOx orgs.
Solution is to send the user to labels by default if it's a new IOx org.
> fix: Settings page sends user to settings/labels in new iox orgs

- src/dataExplorer/components/DataExplorerPage.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
Closes #6522 
For CLOUD IOx enabled users who's org is created after 1/31/23, the following items are hidden 
-  the `switch to old Data Explorer` toggle in the top right corner of the UI
- the old Data Explorer page 
- The flux functions inside the New Query Builder 
- the `flux` option in the New Script drop down button inside New Query Builder
When `showOldDataExplorerInNewIOx` feature flag is flipped on, new IOx users will be able to access both old Data Explorer and New Query Builder just like TSM users
Logic flow chart:
UI Demo: new IOx org when feature flag is on and off
https://user-images.githubusercontent.com/66275100/215594720-bf33947f-009e-46da-bdf4-9a0d9c7ae016.mov
UI Demo: non-IOx org when feature flag is on and off …
> chore: conditionally show old Data Explorer 

- src/shared/selectors/app.ts
Adds a feature flag (local only - not in IDPE or ConfigCat) to simulate the state of being a newly created IOx org. 
This allows an influxer to simulate which portions of the UI are still visible, even if testing from a TSM or pre-cutoff IOx org.
With Flag Off (normal behavior)
--
With Flag On (show only UI elements presented to new IOx users)
--
> chore: add flag to simulate new iox org

- cypress/e2e/cloud/flows.test.ts
- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/flows.test.ts
- cypress/e2e/shared/flowsAlerts.test.ts
- cypress/e2e/shared/flowsSidebarExportToClipboard.test.ts
- cypress/e2e/shared/legends.test.ts
- cypress/e2e/shared/secrets.test.ts
- cypress/index.d.ts
- src/flows/selectors/flowsSelectors.ts
First commit is an empty commit, demonstrating the following:
Tests are failing, even with no change to master. 
Provide a flag, used in CI, to override the hardcoded cutoff timestamp.
> fix: hardcoded comparison timestamp, prevents CI from running flows tests.

- src/pageLayout/containers/MainNavigation.tsx
In testing of what the navbar should look like for new IOx orgs, the helpbar is behaving as expected when collapsed, but not when expanded. The reason is that the expanded style targets the 4th navbar link with submenus (array item `[3]`), but for new iox orgs, there are only 3 navbar links with submenus (because alerts are disabled).
We can set this consistently and dynamically by targeting the _last_ navbar link, rather than a static array index.
Current - TSM (Works)
https://user-images.githubusercontent.com/91283923/215665694-f3037c96-f6ef-47bf-bc6f-2d03e211a6e3.mov
Current - New IOx (Not opening when navbar expanded)
https://user-images.githubusercontent.com/91283923/215665706-44df16cf-a4d0-4486-972d-fcf4345f8e5f.mov
After PR - TSM (Works) …
> chore: correct helpbar styling for new iox

- src/homepageExperience/components/HomepageExperience.scss
- src/homepageExperience/components/steps/DashboardIntegrations.tsx
- src/homepageExperience/components/steps/Finish.tsx
This adds 2 cards to the end of any IOx onboarding flow to link to the docs for integrating with Superset & Grafana.
> feat(ui): add links for superset and grafana docs

- src/writeData/components/ClientLibrarySectionSql.tsx
- src/writeData/components/WriteDataSections.tsx
Curates the client library page for IOx to only show those updated with SQL instructions.
> feat(ui): curate client libary list for sql

- cypress/e2e/shared/editor.test.ts
- cypress/e2e/shared/scriptQueryBuilder.flux.test.ts
- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- src/dataExplorer/components/Results.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
Asap fixes for UI changes request today, as well as things which broke in the past few days with the last minute marty-related commits.
* flux language still needs to be available for CI tests, especially new scripts crud tests (to be merged shortly) and the iox-only tests which are not currently running.
* The graph optimization sidebar needs to be open:
* when using SQL
* when graph subquery results are nothing --> due to query optimization parameters chosen by the user.
* in this case, surface a useful message to the user
* also surface any graph subquery errors --> in the graph area.
*  The graph optimization sidebar should be closed, if and only if:
* there are no results from the parent query. 
Showing the various use cases of:
* no data from parent query
* data from parent query, …
> fix: sql graph optimizations, handling various edge cases with data returned

- cypress/e2e/shared/helpBar.test.ts
- src/me/components/DocSearchWidget.tsx
- src/me/components/Resources.tsx
- src/pageLayout/containers/MainNavigation.tsx
Changes the documentation link in the help bar and removes the docs search bar.
The current search bar is only searching the old docs site and not the IOx docs.
> feat(ui): update main doc link

- cypress/e2e/shared/editor.test.ts
Part of #6562 
iox, passing locally:
> fix(6562): editor test on iox

- cypress/e2e/cloud/dashboardsView.test.ts
- cypress/e2e/cloud/helpBar.test.ts
- cypress/e2e/shared/adaptiveZoom.test.ts
- cypress/e2e/shared/scriptQueryBuilder.flux.test.ts
- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- cypress/e2e/shared/scriptQueryBuilder.sql.test.ts
- cypress/e2e/shared/tasks.pagination.test.ts
- cypress/support/commands.ts
- package.json
Part of #6562 
* fix error were we grabbed the wrong env variable. It should be `CYPRESS_useIox` as [per here](https://github.com/influxdata/k8s-idpe/blob/master/remocal-ci/cd-app-e2e-test-remocal-ui-test.bash#L43-L45).
* we had cy.sign() and cy.setupUser() using different ones. This is why we got different behaviors per some tests.
* turn on flags to `shared/tasks.pagination` test
* passing iox tests:
*  ![Screen Shot 2023-02-01 at 2 37 22 PM](https://user-images.githubusercontent.com/10232835/216192105-5965e723-d066-4f58-b17c-5a97d842f085.png)
* skip tests which are now failing:
* could have passed last night, due to the first-iox-login-is-actually-tsm bug.
* could also be related to the cy.signin() using the wrong env.
* Can figure out which (and make any other changes as needed), when …
> fix(6562): iox should use proper env var, and skip more failing tests.

- cypress/e2e/shared/tasks.test.ts
- cypress/support/commands.ts
Part of #6562 
Updates the tasks tests to work with the IOx pipeline:
(1) If in a TSM org, run the old tasks tests.
(2) If in an IOx org, flip the 'show tasks in iox' flag on so that we simulate the environment for old iox orgs and Tools.
(3) If in an IOx org, also run an extra test to make sure tasks doesn't show for new users.
> fix: update task test to work with iox pipeline

- cypress/e2e/shared/dashboardsView.test.ts
Part of #6562
This PR updates the shared dashboardsView tests to make sure:
1. If in a TSM org, run the tests for dashboardsView 
2. If in an IOx org:
* with the feature flags on (`showDashboardsInNewIOx` and `showVariablesInNewIOx`) to simulate the environment for old IOx orgs and Tools, run the tests for dashboardsView
* with the feature flags off (by default) to simulate new IOx org, new users shouldn't see dashboards button and page
Screenshots of this PR passing locally. Two tests kept crashing the browser, so I tested them separately.
> fix(6562): update shared dashboardsView on iox

- cypress/e2e/shared/variables.test.ts
Helps with #6562 
Pr updates variables test by making sure test passes for `TSM` and `IOx` utilizing the `showVariablesInNewIOx` feature flag. 
A new test is also added for IOx that checks for a 404 page when routing to `/variables`
> fix: fix variables test to work for IOx

- cypress/e2e/shared/simpleTable.test.ts
Part of #6562
This PR updates the test case for simple table to run in IOx orgs with the feature flag `showOldDataExplorerInNewIOx` on to simulate the environment for old IOx orgs and Tools. Since simple table is a component used in the old and the new data explorer, there is no need to test the unavailability of the component in new IOx org. 
Passing locally:
> fix(6562): update simple table test on iox

- cypress/e2e/cloud/communityTemplates.test.ts
Helps with #6562 
Pr updates community templates test to make sure test passes for TSM and IOx. 
it toggles on `showTemplatesInNewIOx` feature flag to force templates to show before running tests. 
For IOx, it adds a test that checks for a 404 page when routing to the templates page. 
> fix: update templates e2e to work with iox

- cypress/e2e/shared/checks.test.ts
See #6562 
Pr updates Checks e2e test to make sure it passes for TSM and IOx.
it toggles on `showAlertsInNewIOx` feature flag to force Alerts to show before running tests.
For IOx, it adds a test that checks for a 404 page when routing to the templates page.
> chore: update checks to work with iox

- cypress/e2e/shared/loadDataSources.test.ts
Part of #6562 
Updates the load data sources test to be compatible with both the TSM and IOx pipeline.
There was a 'write data' test in here that had been skipped even before the IOx release. Unskipped and updated it so that it works with the combination of the load data page and new data explorer.
> fix: update load data sources test for iox

- cypress/e2e/shared/queryBuilder.test.ts
Part of #6562
This PR updates the query builder to work with iox by turning on feature flags `showOldDataExplorerInNewIOx` and `showDashboardsInNewIOx`. Since query builder is a component used in the old data explorer, there is no need to add test on 404 page for new IOx orgs since it will be covered in `shared/explorer.test.ts`
Test pass locally:
> fix(6562): update query builder to work with iox

- cypress/e2e/shared/notificationRules.test.ts
Part of #6562 
Updates the notification rules (alerts) test for iox. Adds a test for the absence of alerts in new IOx orgs.
Removes the buggy test for 'what to do when you manually try to navigate to an alert identifier that doesn't exist'. In remocal, it creates difficult-to-trace auth issues with subsequent tests. It also isn't providing value, as it's a quirky edge case for a feature that doesn't exist prospectively in Cloud2 iox.
> chore: update notification rules test for iox

- cypress/e2e/shared/explorerVisualizations.test.ts
Part of #6562 
This PR updates the old data explorer visualization to work with iox by turning on feature flags `showOldDataExplorerInNewIOx` and `showVariablesInNewIOx`. Since visualization is a component used in the old data explorer, there is no need to add test on 404 page for new IOx orgs because it will be covered in `shared/explorer.test.ts`
Passing locally:
> fix(6562): update explorer visualization to work with iox

- cypress/e2e/cloud/explorer.test.ts
- cypress/e2e/shared/explorer.queries.graphs.test.ts
- src/timeMachine/components/TagSelector.tsx
Part of #6562 
This PR updates two tests related to the old data explorer to work with iox. Since these two tests are sub-tests of the old data explorer test, there is no need to add test on 404 page for new IOx orgs because it will be covered in `shared/explorer.test.ts`
cloud/explorer.test.ts
* `showOldDataExplorerInNewIOx`
* `showDashboardsInNewIOx`
shared/explorer.queries.graphs.test.ts
* `showOldDataExplorerInNewIOx`
* `showTasksInNewIOx`
* `showVariablesInNewIOx`
Passing locally:
Browser crashed when I tested `explorer.queries.graphs.test.ts` locally, so I split the test and they all passed:
> fix(6562): update explorer to work with iox

- cypress/e2e/cloud/dashboardsView.test.ts
- cypress/e2e/shared/dashboardsIndex.test.ts
- cypress/e2e/shared/dashboardsRefresh.test.ts
- cypress/e2e/shared/dashboardsVariables.test.ts
- cypress/e2e/shared/dashboardsView.test.ts
part of #6562 
* e2es goals:
* prevent regressions of any existing code (by internal or external users)
* to ensure e2e compatibility with the full stack.
* any exceptions added are about the backend/storage
* e.g. only tsm supports explicit bucket schema --> use cy.skipOn() as needed
* e.g. only iox supports SQL --> use cy.skipOn() as needed
* enablement flags are selectively on:
* which flags are required, explicitly indicates the feature coupling.
* we could also use this to set ordering of feature deletion (when we eventually get there).
* e.g. `showDashboardsInNewIOx` + `showVariablesInNewIOx` => dashboards have to be removed, before we can remove variables.
Screenshots from after the rebase onto the proper cypress env vars.
> fix(6562): dashboard tests passing on iox

- cypress/e2e/cloud/releases.test.ts
- cypress/e2e/shared/dashboardsView.test.ts
- src/settings/components/SettingsHeader.tsx
- src/shared/selectors/app.ts
- src/usage/context/usage.tsx
part of #6562 
Since the rest of the e2es are testing UI compatibility with the backend, we also need a specific test for deprecations of each cloud release.
> feat(6562): marty release test

- cypress/e2e/shared/notificationEndpoints.test.ts
See #6562 
Pr adds `showAlertsInNewIOx` featureFlag to test to turn on Alerts in NotificationEndpoints test.
> chore: update notificationEndpoints test to work with iox

- cypress/e2e/cloud/scriptQueryBuilder.scriptsCrud.test.ts
- cypress/e2e/oss/scriptsCrud.test.ts
- cypress/support/commands.ts
- src/dataExplorer/components/DataExplorerPage.tsx
- src/dataExplorer/components/DeleteScript.tsx
- src/dataExplorer/components/OpenScript.tsx
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
Closes #6537 
* for bug #6537 
* Turn off toolbar items related to scripts crud, when not on cloud 
* add data-Ids to the various UI elements related to scripts crud
* e2es:
* create a new scripts crud test, for cloud-only
* show the crud elements are not present in oss.
* modify scripts test fixtures (a.k.a. cypress commands) to handle additional use cases (i.e. oss, already saved script)
> fix(6537): script crud should not be enabled for non-cloud. Scripts e2es cleanup.

- cypress/e2e/cloud/scriptQueryBuilder.scriptsCrud.test.ts
- src/dataExplorer/components/resources/index.ts
- src/dataExplorer/components/resources/types/script/index.ts
- src/dataExplorer/context/persistance.tsx
Fix https://github.com/influxdata/EAR/issues/3937
Users cannot save complicated flux queries even though the queries can be executed and show graphs. See the [EAR issue comment](https://github.com/influxdata/EAR/issues/3937#issuecomment-1422913489) for the finding. 
This PR is a quick fix that removes the validation on flux so that users can save scripts regardless if that's valid or not. This gives users a way to save any work in progress flux quires and/or complicated flux queries. 
> fix: remove validation on flux before persistance

- cypress/e2e/cloud/scriptQueryBuilder.scriptsCrud.test.ts
- cypress/e2e/shared/tasks.test.ts
- docker/Dockerfile.chronograf.prod
This PR replace `npm bin` with `npm exec` since `npm bin` was recently removed in Node 18.14.0. 
https://nodejs.org/en/blog/release/v18.14.0/#config-command-deprecations-or-removals
> fix: update dockerfile for image build

- cypress/e2e/cloud/scriptQueryBuilder.scriptsCrud.test.ts
- cypress/index.d.ts
- cypress/support/commands.ts
> fix(6609): deflake scripts crud test, by making scripts fixture via network calls

- src/dataExplorer/components/Results.scss
Closes #5316 
Just some minor styling fixes, so this box has a max height.
https://user-images.githubusercontent.com/10232835/218899140-d1da85dd-f4d0-44b6-88f9-e7218337d8d5.mov
> fix(5316): set upper limit on size of error

- src/visualization/components/internal/StaticLegend.tsx
Closes #6598 
Was not properly consuming the default versus the not_set. The default should be 20%.
https://user-images.githubusercontent.com/10232835/218907789-b6ace46b-230a-47b3-819c-fd0b777b6407.mov
> fix(6598): properly use default static legend height

- cypress/e2e/cloud/helpBar.test.ts
See #6562 
Because navigation items are few in number in IOx orgs compared to tsm, test needed to be updated to target the correct element to properly trigger the popover that displays help bar sub menu items. 
> fix(helpBar): target correct DOM element

- cypress/e2e/shared/tasks.test.ts
- cypress/e2e/shared/tasks2.test.ts
- cypress/support/commands.ts
Closes #6609 
Fixes and unskips the other flaky test - tasks. Primary issues were targeting of the wrong test ID for one of the tasks buttons, and inconsistent behavior on portions of the tasks test where visibility wasn't checked before clicking. 
Was hard to diagnose in CI because the test is so long that when it fails, the test times out and doesn't leave a video artifact. As a result, I've also split the test into two tests so that future failures give us a video artifact.
> chore: fix and unskip tasks tests

- cypress/e2e/shared/scriptQueryBuilder.datePicker.test.ts
- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- docker/Dockerfile.chronograf.prod
- src/shared/components/dateRangePicker/NewDatePicker.tsx
- src/shared/utils/sqlInterval.test.ts
- src/shared/utils/sqlInterval.ts
Closes #6451 
This PR persists the custom time range in UTC time zone with ISO format for the new date picker. Then the input form converts and displays the time according to the time zone that's selected by users. 
https://user-images.githubusercontent.com/14298407/215828719-73c89995-53d8-43a2-9765-9545052bde6f.mov
https://user-images.githubusercontent.com/14298407/215828298-fac53073-8a0f-4383-995d-189c01fa0fe3.mov
> fix(NewDatePicker): utilize local vs. UTC time zone

- src/dataExplorer/components/SaveAsScript.tsx
Closes #6565 
This PR removes the invokable link for InfluxQL and SQL scripts. 
Since InfluxQL cannot be saved as a script since the backend is not ready yet, there is no way for users to click on "Edit" button to see the overlay that has the invokable link. Since SQL script is not invokable, I also removed the link from the overlay, and the screenshots below are from SQL scripts. 
> chore: remove invokable link for InfluxQL and SQL scripts

- cypress/e2e/cloud/releases.test.ts
- cypress/support/commands.ts
Add test which will detect if we get provisioning errors again.
Test on iox:
> chore: e2e cleanup

- package.json
- src/operator/OrgOverlay.tsx
Closes #6495 
Pr updates openapi `sha` to generate updated unity routes and adds two fields to the Limits section of the Org detail overlay in the Operator UI. 
> chore: add new limits to Operator UI org overlay

- src/dataExplorer/components/Schema.scss
Closes #6600 
This PR fixes the overlapping bug in schema browser
https://user-images.githubusercontent.com/14298407/221053647-ba76939c-17b1-4e2b-8458-bfc5b942c518.mov
https://user-images.githubusercontent.com/14298407/221053661-623a5455-1d7b-4ae1-a2d5-bf35aecfcf7d.mov
> fix: resolve the overlapping bug in schema list

- cypress/e2e/shared/tasks.test.ts
- src/tasks/containers/TaskPage.tsx
Users are hitting an error trying to save [this data migration task](https://docs.influxdata.com/influxdb/cloud/migrate-data/migrate-cloud-to-cloud/#migration-flux-script) in the Cloud2 UI. This PR fixes it by preventing a recursive loop caused by regex.
Before
--
https://user-images.githubusercontent.com/91283923/222728028-b6ed6e0b-ae00-4c78-927a-bcd4d444faf4.mov
After
--
https://user-images.githubusercontent.com/91283923/222728017-289e6b4f-0a32-44ab-a0f0-b271d0d04a0d.mov
Cause
--
The following regex on the "create task" page was intended to ensure that what the user selects for the task name and frequency in the panel on the left-hand side of the page takes precedence over any definition of the task name and frequency in the script.
`script = script.replace(new …
> fix: prevent recursion in task regex

- cypress/e2e/shared/legends.test.ts
- src/dataExplorer/components/DataExplorerPage.tsx
- src/dataExplorer/components/SaveAsButton.test.tsx
- src/dataExplorer/components/SaveAsButton.tsx
- src/dataExplorer/components/SaveAsOverlay.tsx
Part of #6562 
This PR:
1. Updates the legends tests to work with IOx.
2. Unskips tests that weren't being run due to Cypress firefox compatibility issues (we only test Chrome now).
3. Fixes a bug where a new iox user with access to old data explorer but none of the other features could still see the 'Save As' button, even if there was nowhere to save the query.
> fix: update legends test for iox

- src/shared/contexts/dbrps.tsx
Closes #6638. Related to #6637
To prepare for the InfluxQL editor, this PR creates a DBRP ([Database Retention Policy](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)) context that stores DBRP mappings in local storage. This new file is a simpler version of [bucket context](https://github.com/influxdata/ui/blob/80e3e0360b490f5f29cdf034adf760379e459463/src/shared/contexts/buckets.tsx).
> feat(dbrp): create DBRP context and store mappings in local storage

- package.json
- yarn.lock
Fix https://github.com/influxdata/ui/security/dependabot/53
> Minimist prior to 1.2.6 and 0.2.4 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).
`minimist` is a dependency used in `mocha` and `mocha-junit-reporter`. This PR upgrades `mocha` from 5.2.0 to the latest 10.2.0, which bumps the `minimist` version to 1.2.6. This PR removes `mocha-junit-reporter` since it is not used anywhere.
> chore: upgrade `mocha` to 10.2.0 and remove `mocha-junit-reporter`

- src/shared/components/NotFound.tsx
The current 404 page is the same as Cloud:
However we don't want users directed to support, and don't want cloud branding. The updated page addresses that:
> fix: remove cloud branding and support link from OSS 404 page

- src/dataExplorer/components/BucketSelector.tsx
- src/dataExplorer/components/DBRPSelector.tsx
- src/dataExplorer/components/Schema.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
- src/dataExplorer/context/persistance.tsx
- src/dataExplorer/context/scriptQueryBuilder.tsx
- src/shared/contexts/dbrps.tsx
Closes #6637 
This PR adds the database / retention policy (DBRP) list for InfluxQL which is the equivalent of bucket list for Flux and SQL. It only allows a user to use InfluxQL in the script editor if the user's org has one or more DBRP mappings AND the org is powered by IOx.
All the work is behind the feature flag `influxqlUI`. 
To test on local remocal:
1) create DBRP mappings in your org ([instruction](https://github.com/influxdata/idpe/issues/17205)), and 
2) also make sure to turn on the following flags in your browser:
* `showOldDataExplorerInNewIOx`
* `newDataExplorer`
* `schemaComposition`
https://user-images.githubusercontent.com/14298407/223872771-5864b8aa-473f-4096-9efe-6080fa5fc5a5.mov
https://user-images.githubusercontent.com/14298407/224354856-a0442bfb-aea1-4fdb-a10a-5df701 …
> feat: add DBRP schema list

- CODEOWNERS
Removes ecommerce team from codeowners. 
This was added as a failsafe around vacations and at a point where it wasn't clear how many ui engineers would be around to approve PRs, but no longer necessary and the extra ping to the former ecommerce team isn't worth the disruption.
> chore: remove ecommerce from codeowners

- src/onboarding/actions/index.ts
- src/onboarding/components/CompletionStep.test.tsx
- src/onboarding/components/CompletionStep.tsx
- src/onboarding/components/OnboardingStepSwitcher.tsx
- src/onboarding/containers/OnboardingWizard.tsx
- src/onboarding/reducers/index.ts
Closes https://github.com/influxdata/influxdb/issues/24082
After updating the UI in OSS, we lost the ability to see the operator token after creation. This causes a lot of headache and confusion for users.
I have simply added the token to the final page in the onboarding wizard.
> feat: add operator token to onboarding wizard

- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
- src/dataExplorer/components/Sidebar.tsx
Closes #6652
This PR allows TSM users to use InfluxQL in the script editor if they already have one or more DBRP mappings
All the work is behind the feature flag `influxqlUI`. 
To test on local remocal:
1) create DBRP mappings in your org ([instruction](https://github.com/influxdata/idpe/issues/17205)), and 
2) also make sure to turn on the following flags in your browser:
* `showOldDataExplorerInNewIOx`
* `newDataExplorer`
* `schemaComposition`
https://user-images.githubusercontent.com/14298407/225366054-bd894b5c-a603-4307-991d-c8e26edaa58c.mov
> feat: make InfluxQL available to TSM orgs

- src/shared/components/VersionInfo.tsx
Renames "InfluxDB Cloud powered by IOx" to "InfluxDB Cloud Serverless" and updates the docs link to `https://docs.influxdata.com/influxdb/cloud-serverless/`.
> feat(ui): rename iox to serverless

- src/homepageExperience/components/OptionAccordion/OptionAccordion.scss
- src/homepageExperience/containers/HomepageContents.scss
- src/homepageExperience/containers/HomepageContents.tsx
- src/me/components/AnnouncementBlock.scss
- src/me/components/AnnouncementBlock.tsx
- src/me/components/AnnouncementCenter.tsx
- src/me/components/BlogFeed.scss
- src/me/components/BlogFeed.tsx
- src/me/components/CloudWidgets.tsx
Swaps the announcement to one about Cloud Dedicated. Also adds some CSS tweaks for better responsiveness.
> feat(ui): cloud dedicated promo and css tweaks

- src/usage/context/usage.tsx
This resolves a pending EAR in which the user is seeing a higher amount of 250 PAYG credit usage than expected. It required a backend change linked below so that more timeframes are available for usage queries. This should resolve the issue by scoping the query correctly to the timeframe in which the user has had a 250/30day credit for upgrading to PAYG. 
Deployed behind the `credit250fix` flag for now pending confirmation.
> fix: resolve incorrect display of 250 credit used

- cypress/e2e/cloud/operator.test.ts
- cypress/e2e/cloud/operatorRO.test.ts
Quartz-mock was updated to add more test orgs and accounts here https://github.com/influxdata/quartz-mock/pull/51. We need a parallel UI update to permit UI e2es to continue to run.
> chore: update accounts and orgs to 7

- src/usage/context/usage.tsx
Two fixes related to https://github.com/influxdata/ui/pull/6650:
(1) The existing useeffect hooks were making requests to the quartz api for usage to compute 250 credit participation even _after_ 30 days had expired, which is unnecessary. Now, a query is only made when the user is within 30-day credit window.
(2) Need to throw an error on an invalid (or 0) computation of credit days, which will set the shown credit usage back to the default (0).
> chore: no query if payg credit not enabled, no queries over 30d

- src/languageSupport/languages/influxql/connection.ts
- src/languageSupport/languages/sql/connection.ts
- src/shared/components/dateRangePicker/NewDatePicker.tsx
- src/shared/utils/rangeToInterval.test.ts
- src/shared/utils/rangeToInterval.ts
- src/types/queries.ts
Closes #6653
This PR adds the time range from date picker into the InfluxQL query composition. I also add unit tests to cover the utility function that converts UI date picker time range into InfluxQL time syntax.
https://github.com/influxdata/ui/assets/14298407/38b1fa36-55b7-4fe0-b8f1-444739b64b0c
All the work is behind the feature flag `influxqlUI`.
To test on local remocal:
1. create DBRP mappings in your org ([instruction](https://github.com/influxdata/idpe/issues/17205)), and
2. also make sure to turn on the following flags in your browser:
* `showOldDataExplorerInNewIOx`
* `schemaComposition`
> feat(influxql): add time range into query composition

- cypress/e2e/cloud/operator.test.ts
- cypress/e2e/cloud/operatorRO.test.ts
- package.json
- src/operator/account/AccountView.tsx
- src/operator/account/AccountViewHeader.tsx
- src/operator/account/CancelAccountOverlay.tsx
- src/operator/context/account.tsx
This change allows a user to cancel a direct payg account through the operator page.
> feat(operator): Allow operators to cancel accounts

- src/languageSupport/languages/influxql/connection.ts
- src/languageSupport/languages/sql/connection.ts
Closes #6714
This PR fixes the bug that composition sync should not auto turn off when creating a new script for SQL and InfluxQL
SQL
https://github.com/influxdata/ui/assets/14298407/dbf8a521-5644-4fc0-8371-1f9ba5dae286
InfluxQL
https://github.com/influxdata/ui/assets/14298407/1e430d84-a708-4e56-bf1a-354874c77a47
SQL
https://github.com/influxdata/ui/assets/14298407/cca9e358-0792-4a91-b650-a3ce3605edea
InfluxQL
https://github.com/influxdata/ui/assets/14298407/7def0e03-68f9-4bd6-a5da-0c51273b5cd8
The fix for SQL will be seen in production, but the fix for InfluxQL is behind the feature flag `influxqlUI`.
To test on local remocal for InfluxQL:
1. create DBRP mappings in your TSM org ([instruction](https://github.com/influxdata/idpe/issues/17205)), and
2. also make sure to turn on the …
> fix(script-editor): composition sync should not auto turn off when creating a new script

- src/dataExplorer/components/ResultsPane.tsx
Closes #6601
I came across the origin issue and found that it is a low hanging fruit. 
This PR disables the run button for SQL script editor until a measurement is selected when the composition sync is on. A message will show up when users hover over the disabled run button. 
https://github.com/influxdata/ui/assets/14298407/0ec88005-74ec-4999-8eb2-6e80feb5e98b
https://github.com/influxdata/ui/assets/14298407/9c03dffc-db70-411f-9ee1-e88673a57b74
> fix(sql): disable the run button until a measurement is selected

- src/me/components/CloudWidgets.tsx
I found this warning when I was working on another UI dev work. Seems like a quick fix.
> chore(announcement): fix dev warning

- src/languageSupport/languages/influxql/connection.ts
Closes #6724
Fix a minor bug in InfluxQL composition sync -- add double quotations around database name and retention policy name which are called identifiers in InfluxQL. 
Recommendation from [InfluxQL doc](https://docs.influxdata.com/influxdb/cloud/query-data/influxql/explore-data/select/#quoting):
> [Identifiers](https://docs.influxdata.com/influxdb/cloud/reference/syntax/influxql/spec/#identifiers) must be double quoted if they contain characters other than [A-z,0-9,_], begin with a digit, or are an [InfluxQL keyword](https://github.com/influxdata/influxql/blob/master/README.md#keywords). While not always necessary, we recommend that you double quote identifiers.
https://github.com/influxdata/ui/assets/14298407/f13290ac-cec1-4ce3-bbd7-d21cfdf89296 …
> chore: add double quotations to database and retention policy names

- src/dataExplorer/components/DBRPSelector.tsx
- src/languageSupport/languages/agnostic/utils.test.ts
- src/languageSupport/languages/agnostic/utils.ts
- src/languageSupport/languages/influxql/connection.ts
Closes #6715
This PR adds the selected tag keys to the `SELECT` statement so that the tag keys show up as a column in the result table
https://github.com/influxdata/ui/assets/14298407/7c163da3-48fa-4b92-bb98-6fa9efeb72a4
https://github.com/influxdata/ui/assets/14298407/d35b8bcb-c4e9-497f-a723-b93e15fd14ea
> fix(influxql): add selected tag keys to `SELECT` statement

- package.json
- src/dataExplorer/components/ScriptQueryBuilder.scss
- src/dataExplorer/components/ScriptQueryBuilder.tsx
- src/dataExplorer/components/resources/index.ts
- src/languageSupport/languages/influxql/monaco.influxql.theme.ts
- src/shared/components/FluxMonacoEditor.tsx
Closes #6730
This PR is the last piece to support InfluxQL save/load. The backend works (https://github.com/influxdata/idpe/pull/17768 and https://github.com/influxdata/openapi/pull/639) have already been merged. 
1. Update the OpenAPI SHA to the latest https://github.com/influxdata/openapi/commit/eec3a9ed87d664529e6a5dddad76232ed9e823bf
2. Change the language code to all lowercase `influxql`, which was requested in https://github.com/influxdata/openapi/pull/639#discussion_r1230218119. Now idpe, OpenAPI, and UI are all in consistency using the same language code.
3. Minor fix: show `FLUX` in the script editor for TSM orgs, so that users can differentiate which script editor they are using. 
https://github.com/influxdata/ui/assets/14298407/7db99df9-474f-4651-bd6a-4b38ab7ade3b
All the work …
> chore(influxql): support save/load

- jestSetup.ts
- src/dashboards/selectors/index.test.ts
- src/dataExplorer/components/ResultsPane.tsx
- src/mockState.tsx
- src/shared/actions/app.ts
- src/shared/components/CSVExportButton.tsx
- src/shared/contexts/app.tsx
- src/shared/copy/notifications/categories/dashboard.ts
- src/shared/reducers/app.test.ts
- src/shared/reducers/app.ts
- src/shared/workers/downloadHelper.ts
- src/shared/workers/serviceWorker.ts
- src/timeMachine/components/Queries.tsx
Closes #6704
This PR adds CSV download to the InfluxQL script editor. In addition, a service worker for scope `/query` is also added to make the feature complete. 
If you wonder why the UI uses service worker to download csv file, [here](https://github.com/influxdata/ui/blob/9c77358d8d75e2c7bff59203db4324471d93506a/src/shared/workers/downloadHelper.ts#L2-L23) is a good explanation. The TL;DR summary is that service worker can perform tasks in the background, which makes downloading large csv file fast and not blocking other UI interactions. 
The backend work (https://github.com/influxdata/idpe/pull/17737) is already merged.
https://github.com/influxdata/ui/assets/14298407/e210d453-5aac-4fb3-92a4-761f62e50e9b
All the work is behind the feature flag `influxqlUI`.
To test on local remocal: …
> feat(influxql): add csv download

- src/operator/OrgOverlay.tsx
Part of #6708 
When an account is canceled, we should not show the reactivate option, even if the org is suspended.
> fix: Hide reactivate org button for cancelled accounts

- package.json
- src/operator/OrgOverlay.tsx
- src/operator/account/AccountGrid.tsx
Quartz now optionally includes the date an account was cancelled as well as the date a suspended org will be deleted on. We're going to show these in the UI.
> feat(operator): Add Org `DeleteOn` and Account `CancelledAt` dates

- package.json
- src/operator/account/AccountView.tsx
- src/operator/account/AccountViewHeader.tsx
- src/operator/account/ReactivateAccountOverlay.tsx
- src/operator/context/account.tsx
- src/shared/copy/notifications/categories/operator.ts
When an account is canceled and has suspended organization(s), it can be reactivated.
> feat(operators): Add reactivate account button

- src/utils/vwo.ts
Addresses https://github.com/influxdata/idpe/issues/16543
This PR updates the version of the VWO smartcode to v1.5
> chore: update vwo smartcode

- cypress/e2e/cloud/userAccounts.test.ts
- src/accounts/context/DeleteFreeAccountContext.tsx
- src/billing/components/PayAsYouGo/CancelServiceContext.tsx
Closes #6758 
The user accounts e2e test is failing because changes were made to the structure of some of the pages on our website. The CMS appears not to support underscores so the `mkt_cancel` page was moved to `mkt-cancel`. A redirect was added from the URL including the underscore, but it still causes our e2e tests to fail because it expects the user in that test to end on a url including `mkt_cancel`, not `mkt-cancel`.
This changes the references in the user accounts test and the UI from `mkt_cancel` to `mkt-cancel` so that the user is directed to the new page instead of relying on the redirect.
> chore: change mkt_cancel refs to mkt-cancel

- package.json
- src/operator/MigrateOrg.tsx
- src/operator/MigrateOrgOverlay.tsx
- src/operator/OrgOverlay.tsx
- src/operator/OrgOverlayWrapper.tsx
- src/operator/account/AccountView.tsx
- src/operator/account/MigrateOrgs.tsx
- src/operator/account/MigrateOrgsOverlay.tsx
- src/operator/context/account.tsx
- src/operator/context/overlay.tsx
- src/shared/copy/notifications/categories/operator.ts
Allows operators to migrate all of an account's organizations or a specific organization to a different account.
> feat(operators): Add Migrate Organization Tool

- cypress/e2e/shared/helpBar.test.ts
- src/pageLayout/containers/MainNavigation.tsx
Closes #6765
This PR corrects the join Slack link in the UI by removing the specific invite id.
> fix(ui): update slack join link

- src/homepageExperience/components/OptionAccordion/QueryDataAccordion.tsx
- src/homepageExperience/components/steps/nodejs/ExecuteQuerySql.tsx
- src/homepageExperience/components/steps/nodejs/InitializeClientSql.tsx
- src/homepageExperience/components/steps/nodejs/InstallDependenciesSql.tsx
- src/homepageExperience/components/steps/nodejs/WriteDataSql.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
1. Changed `Node.js` wizard to use new https://github.com/bonitoo-io/influxdb3-js for `ioxOnboarding`
> docs(client_libs): update Node.js wizard to use new v3 client

- src/homepageExperience/components/steps/python/ExecuteAggregateQuerySql.tsx
- src/homepageExperience/components/steps/python/ExecuteQuerySql.tsx
- src/homepageExperience/components/steps/python/InitializeClientSql.tsx
- src/homepageExperience/components/steps/python/InstallDependenciesSql.tsx
- src/homepageExperience/components/steps/python/WriteDataSql.tsx
- src/homepageExperience/containers/PythonWizard.tsx
Closes #6761
This PR updates the Python onboarding with the new client library and adds InfluxQL aggregation instructions.
> feat(ui): python onboarding updating to influxdb3 python

- cypress/e2e/cloud/about.test.ts
- cypress/e2e/cloud/createOrg.test.ts
Part of #6779 
The two e2e tests that call the marketo script for sending inquiries when a self serve user wants to upgrade from PAYG to contract are failing, as the expected call in the third-party script that submits the form does not appear to occur. While we debug the issue with the third party script this will temporarily disable that line in the tests to unblock CI.
> chore: temporarily disable wait for marketo response to unblock ci

- src/shared/contexts/query/context.tsx
Closes influxdata/idpe#17953
This PR is the start of the UI work for [this epic issue](https://github.com/influxdata/idpe/issues/17711). 
This PR adds the path `/api/v2private/query` for SQL queries. When the feature flag is on and the script language is SQL, the query will send to this path instead of being wrapped in `iox.sql()` and sending to `/api/v2/query` in Flux.
The change is behind the feature flag `v2privateQueryUI` and it is set to false by default
To test locally, deploy the remocal with the following flag:
```
make deploy-remocal DEPLOY_IOX=true ENABLE_IOX_FLIGHT=true
```
Then you will see SQL queries will send to `/api/v2private/query` in DevTool Network tab
> feat(sql): add `/api/v2private/query` for SQL query

- cypress/e2e/cloud/about.test.ts
- src/organizations/components/OrgProfileTab/index.tsx
- src/shared/components/VersionInfo.tsx
This PR fixes the version number on the home page to reflect the major version of the storage engine (2 or 3). It also updates the Storage Type name on the Organization Settings page.
TSM Org Info:
Serverless Org Info:
TSM version number on the home page:
Serverless version number on the home page:
> fix(ui): version name and number

- cypress/e2e/shared/helpBar.test.ts
- src/homepageExperience/components/OptionAccordion/AddDataAccordion.tsx
- src/homepageExperience/components/OptionAccordion/ManageDatabasesAccordion.tsx
- src/homepageExperience/components/OptionAccordion/QueryDataAccordion.tsx
- src/homepageExperience/components/OptionAccordion/VisualizeAccordion.tsx
- src/homepageExperience/components/steps/DashboardIntegrations.tsx
- src/homepageExperience/components/steps/Finish.tsx
- src/pageLayout/containers/MainNavigation.tsx
- src/telegrafs/components/TelegrafExplainer.tsx
This PR adds a Tableau docs link. It also updates all the docs links from `cloud-iox` to `cloud-serverless`. In doing so it fixes some broken links. Lastly, it replaces the "Key Concepts" link at the end of the onboarding flows with a "Best Practices" link because the previous links to TSM documentation.
> feat(ui): tableau instructions

- src/dataExplorer/components/Results.tsx
Part of https://github.com/influxdata/idpe/issues/17986
This PR updates the query statistics to only show number of tables for Flux. Number of tables is a Flux concept, and it doesn't apply to SQL and InfluxQL, so removing it
> chore(epic-idpe-17711): only show table stat for Flux

- jestSetup.ts
- src/dashboards/selectors/index.test.ts
- src/dataExplorer/components/ResultsPane.tsx
- src/mockState.tsx
- src/shared/actions/app.ts
- src/shared/components/CSVExportButton.tsx
- src/shared/contexts/app.tsx
- src/shared/reducers/app.test.ts
- src/shared/reducers/app.ts
- src/shared/workers/downloadHelper.ts
- src/shared/workers/serviceWorker.ts
Closes https://github.com/influxdata/idpe/issues/18001
This PR routes the CSV download for SQL through the HTTP path `/api/v2private/query`. In addition, a service worker for scope `/api/v2private/query` is also added to make the feature complete.
The backend work (https://github.com/influxdata/idpe/pull/18054) is already merged
The change is behind the feature flag `v2privateQueryUI` and it is set to false by default
1. Deploy the remocal with the following flag:
```
make deploy-remocal DEPLOY_IOX=true ENABLE_IOX_FLIGHT=true
```
2. Then you will see the query for measurement list will send to `/api/v2private/query` in DevTool Network tab
Customers won't notice any difference before and after the change
https://github.com/influxdata/ui/assets/14298407/fc01d6fc-5c63-4702-8f07-c2a694a2388c …
> chore(epic-idpe-17711): update csv download to path `/api/v2private/query`

- src/dataExplorer/components/TagSelector.tsx
- src/dataExplorer/context/tags.tsx
Part of https://github.com/influxdata/idpe/issues/17981
This PR uses the SQL HTTP API to query tag values
The change is behind the feature flag `v2privateQueryUI` and it is set to false by default
1. Deploy the remocal with the following flag:
```
make deploy-remocal DEPLOY_IOX=true ENABLE_IOX_FLIGHT=true
```
2. Then you will see the query for measurement list will send to `/api/v2private/query` in DevTool Network tab
https://github.com/influxdata/ui/assets/14298407/63a6db58-63b4-42ec-b672-f40c834c7b75
> chore(epic-idpe-17711): use SQL HTTP API to get tag value list

- src/buckets/components/BucketExplainer.tsx
This PR changes some text on the Buckets helper panel as well as corrects the URL for Serverless.
> fix(ui): update bucket helper

- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
- src/dataExplorer/shared/utils.ts
A follow-up PR for https://github.com/influxdata/ui/pull/6791#pullrequestreview-1604900949
This RP removes unnecessary `as` type casting and add explanations for those that need the type casting
> refactor(epic-idpe-17711): remove unnecessary `as` type casting

- src/dataExplorer/components/Results.tsx
- src/dataExplorer/context/results/childResults.tsx
- src/shared/contexts/query/context.tsx
Closes https://github.com/influxdata/idpe/issues/17986
This PR refactors the code to make the Script Editor (new Data Explorer) always use the Flux query endpoint (`/api/v2/query`) to get data that is used for plotting graphs when user select SQL as the query language. In this way, regardless whether the feature flag `v2privateQueryUI` is on or off, the graphs can work as usual. See the [original issue](https://github.com/influxdata/idpe/issues/17986) for the reason.
https://github.com/influxdata/ui/assets/14298407/e825319d-c950-42c6-a35f-d75d4fd094dc
https://github.com/influxdata/ui/assets/14298407/fdb54674-ddac-4d87-b523-ec7badec55d5
> chore(epic-idpe-17711): keep graphs working for SQL by using Flux query

- cypress/e2e/cloud/scriptQueryBuilder.influxql.test.ts
- cypress/e2e/shared/scriptQueryBuilder.sql.test.ts
Closes https://github.com/influxdata/idpe/issues/18029
This PR turns on the flag `v2privateQueryUI` in the e2e tests for SQL and InfluxQL and add CSV download for SQL. 
The existing test cases already cover schema browser, run button, CSV, graphs, and table, so just turning on the feature flag is good enough!
> chore(epic-idpe-17711): add e2e tests and turn on flag `v2privateQueryUI` in tests

- cypress/e2e/cloud/scriptQueryBuilder.influxql.test.ts
- cypress/e2e/shared/scriptQueryBuilder.sql.test.ts
- src/dataExplorer/components/ResultsPane.tsx
- src/dataExplorer/context/fields.tsx
- src/dataExplorer/context/measurements.tsx
- src/dataExplorer/context/tags.tsx
- src/shared/components/CSVExportButton.tsx
- src/shared/contexts/query/context.tsx
Part of https://github.com/influxdata/idpe/issues/18016
`v2privateQueryUI` has been on in production for two weeks and it's working without issues. This PR removes the feature flag `v2privateQueryUI` in UI.
> chore: remove feature flag `v2privateQueryUI`

- cypress/e2e/cloud/scriptQueryBuilder.influxql.test.ts
- cypress/support/commands.ts
- src/dataExplorer/components/SaveAsScript.tsx
- src/dataExplorer/components/ScriptQueryBuilder.tsx
Part of https://github.com/influxdata/ui/issues/6800
The feature flag `influxqlUI` has been on in production for two weeks without any issues, so removing it in this PR
> chore: remove feature flag `influxqlUI`

- cypress/e2e/cloud/createOrg.test.ts
- cypress/index.d.ts
- cypress/support/commands.ts
- src/billing/components/PayAsYouGo/PayAsYouGo.tsx
- src/billing/components/PayAsYouGo/PricingAlert.tsx
- src/homepageExperience/ClickThroughAnnouncementHandler.tsx
- src/homepageExperience/containers/HomepageContainer.tsx
- src/me/components/ClickThroughAnnouncementOverlay.tsx
- src/overlays/components/OverlayController.tsx
- src/overlays/reducers/overlays.ts
- src/shared/containers/GetOrganizations.tsx
This PR adds a new feature to Serverless, the click-through announcement. It is used for important announcements that users must see and includes event tracking for interacting with the announcement component.
The first announcement is for the PAYG pricing increase. There is also a banner on the billing page regarding this announcement. Both of these are limited to direct signup PAYG users.
> feat: Add click through announcement feature

- src/homepageExperience/components/steps/python/ExecuteAggregateQuerySql.tsx
Closes #6831 
- Remove unmatched closing paren.
- Remove quotes from InfluxQL duration. Durations aren't strings. If using SQL, the interval expression ('10 minutes') would be a string.
> fix(python): unmatched paren and influxql syntax:

- cypress/support/commands.ts
- src/homepageExperience/ClickThroughAnnouncementHandler.tsx
- src/me/components/ClickThroughAnnouncementOverlay.tsx
- src/me/components/announcements/MqttEolAnnouncement.tsx
- src/me/components/announcements/PaygPriceIncreaseAnnouncement.tsx
- src/writeData/subscriptions/components/MqttEolAlert.tsx
- src/writeData/subscriptions/components/SubscriptionsLanding.scss
- src/writeData/subscriptions/components/SubscriptionsLanding.tsx
Closes #6828 
This PR updates the click-through announcement overlay feature to be able to handle multiple sequential announcements. It also adds an announcement for the MQTT end-of-life. It adds a click-through overlay to the home page and a permanent alert banner on the Subscriptions page.
Alert Banner
Click-Through Overlay
Click-Through Overlay with Open FAQ Sections (scrolls)
> feat(ui): add mqtt eol overlay and alert banner

- src/pageLayout/components/RequestPocWidget.scss
- src/pageLayout/components/RequestPocWidget.tsx
- src/pageLayout/containers/MainNavigation.scss
- src/pageLayout/containers/MainNavigation.tsx
This PR adds a panel to the nav bar to encourage free account users to request a POC instead of running performance tests in Serverless.
> feat(ui): add request poc panel

- src/homepageExperience/components/OptionAccordion/DeployAccordion.tsx
- src/homepageExperience/containers/HomepageContents.tsx
This adds a new accordion to the homepage with links to information about the deployment options. This is only shown to users on a free account.
> feat(ui): add deployments option accordion

- package.json
Updates the influxdb-template version to pull in quick start template that has names for all the cells. This avoids seeing "Name this cell" for the unnamed cells.
Currently, when an OSS user chooses to quick-start, a dashboard is created, but the names of the cells are not set in the template and so the user sees "Name this template":
With the new version, the following shows:
> chore(deps): bump influxdata/influxdb-templates from 0.9.0 to 0.11.0

- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- src/dataExplorer/context/tags.tsx
- src/shared/constants/queryBuilder.ts
Add a time interval limit when populating a tag values menu, this is to avoid the need to process the entire measurement.
Closes #
> feat: limit the time period used in tag values queries

- package.json
- yarn.lock
Closes https://github.com/influxdata/idpe/issues/18591
Downgrades rudderstack to not pull in debug `0.7.4`. Hopefully this version is ok, in the future we will probably remove rudderstck completely since it has been deprecated.
> fix: downgrade rudderstack so debug is not pulled in

- src/me/components/CurrentAnnouncement.tsx
Updates the announcement center with a new announcement for the Flux to InfluxQL influxDBU course.
> feat(ui): New InfluxDBU announcement

- cypress/e2e/cloud/usage.test.ts
- src/usage/UsageSingleStat.tsx
Clarifies that the query count on the C2 usage page reflects flux queries only.
> fix: add guidance re usage query count

- cypress/e2e/shared/explorer.queries.graphs.test.ts
- cypress/e2e/shared/simpleTable.test.ts
- cypress/e2e/shared/tasks-searching.test.ts
- cypress/support/commands.ts
Part of internal AUX team issue. 
Best reviewed with ?w=1 for whitespace changes
This PR resolves several issues with UI e2e tests that cause the tests to fail when running on a different CI runner. Primary issue is that existing runners generated some built-in delay was effectively adding a `.wait()` or `should()` where not present in the code. On the faster runner this is no longer the case.
1. Using `cy.wait`s to handle cases where a `click` did not wait for a corresponding DOM change. _Once this is tested with the new runner, I would prefer to convert `wait`s to asserting on the presence of specific DOM elements if time allows._
2. Using `.first()` to handle cases where later renders generated more than one DOM element matching on the selector when we are only looking for the first …
> fix: correct tests to be handled by faster ci runner

- cypress/e2e/shared/tasks-searching.test.ts
This adds a wait needed to stop some ongoing flake in one of the tests using the new test runner. See https://github.com/influxdata/ui/pull/6910, https://github.com/influxdata/ui/pull/6911
> chore: add delay to tasks-searching test

- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- cypress/e2e/shared/tasks-searching.test.ts
This reduces flake in the two most frequently flaking tests in the e2e CI pipeline. This should help the pipeline generally, but particularly for the new runner for OSS CI.
> fix: flake in scriptquerybuilder, tasks e2es

- package.json
- src/dashboards/components/NoteEditorPreview.test.tsx
- src/me/actions/thunks/index.ts
- src/organizations/actions/creators.ts
- src/shared/utils/errors.ts
- yarn.lock
Part of [#1980](https://github.com/influxdata/quartz/issues/7619)
This is based on honeybadger's migration guide here: https://docs.honeybadger.io/lib/javascript/support/upgrading-to-v3/
> chore: Replace `honeybadger-js` with `honeybadger-io/js`

- package.json
- src/dashboards/components/NoteEditorPreview.test.tsx
- src/me/actions/thunks/index.ts
- src/organizations/actions/creators.ts
- src/shared/utils/errors.ts
- yarn.lock
Reverts the just merged https://github.com/influxdata/ui/pull/6904. I am seeing errors related to honeybadger on our honeybadger console and would like to pull this back for further testing.
> chore: revert honeybadger-js upgrade

- src/users/components/RemoveMemberOverlay.tsx
As a followup to [this EAR](4677), we thought it would be helpful to indicate to customers that API tokens will be transferred when deleting a user.
> chore: Add "API Tokens" to transfer text

- package.json
- yarn.lock
Part of [#1980](https://github.com/influxdata/quartz/issues/7619)
There is a vulnerability with superagent on versions before 9.X which results in the following warning:
```
warning auth0-js > superagent@7.1.6: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
```
Superagent is a sub-dependency of auth0/auth0.js, which has not updated to a recent version. Superagent has not had a breaking change since v6 and everything looks to be good with Auth0. I have opened a PR with Auth0 to hopefully resolve the issue auth0/auth0.js#1445. But for the …
> chore(deps): Pin auth0 superagent version

- cypress.json
- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- cypress/e2e/shared/tasks-searching.test.ts
This PR is part of ongoing work on using a different CI runner and reducing test flake. Based on review in CircleCI, we still have two tests that flake consistently. This PR makes two proposals:
1. Add an additional allowed retry as a fallback for flaky tests.
2. Disable one of the test cases for the two most significantly flaking e2es. After significant work trying to de-flake these suites, on these particular tests we have reached the point where the benefit has been outweighed by the detrimental CI impact. The test would be more efficient to rewrite at a stage when these pages are modified in the future.
> fix: combat flake on two most frequently flaking e2es

- src/operator/OrgOverlay.tsx
Closes #6745 
The org details overlay on the operator page has a second copy of the 'organization state' field. This removes it.
> chore: remove repeated org state from operator org details

- src/homepageExperience/components/steps/python/InitializeClient.tsx
- Fix variable name in InitializeClient to agree with write and query examples.
- Reported in Docs-v2
Closes #6921
> fix: (onboarding) Wrong variable name for python initialized client. #6921

- cypress/e2e/cloud/usage.test.ts
- src/usage/UsageSingleStat.tsx
@btasker rolled out the fix that includes SQL queries in the query count usage vector (thanks Ben!), meaning we can get rid of the tooltip that explained that the query count only shows flux queries in the UI.
> chore: revert messaging regarding query count sources

- src/annotations/components/annotationForm/AnnotationForm.tsx
- src/dashboards/actions/thunks.ts
- src/dataExplorer/components/DataExplorerPage.tsx
- src/flows/context/api.tsx
- src/flows/context/flow.current.tsx
- src/flows/context/flow.list.tsx
- src/flows/context/version.publish.tsx
- src/labels/actions/thunks.ts
- src/shared/copy/notifications/categories/dashboard.ts
- src/shared/copy/notifications/categories/notebooks.ts
- src/shared/copy/notifications/categories/tasks.ts
This is a cherry-pick of pr #6927 and commit 71f8c458bec3320f665ef65d35478700c79e0dfc
I noticed that annotations and notebooks could display the api error
when requests fail - they are not consistent about it.
* fix: improve failure error message notifications
Including the underlying error in error messages, this improves
notebooks, dashboards, labels, and annotations. Many other error
notifications all need improving e.g. in tasks and secrets.
> chore: improve error notifications in annotations and notebooks (cherry-pick)

- package.json
Related to https://github.com/influxdata/edge/issues/751
This PR updates `influxdb-templates` to the latest version, which includes security updates for the `rollup` dependency.
> chore(deps): bump influxdata/influxdb-templates from 0.11.0 to 0.12.0

- package.json
Related to https://github.com/influxdata/edge/issues/751
This is a cherry-pick of pr #6960 and commit ff83a1e53db1aa12048a2b07c5a824022ec750d0.
This PR updates `influxdb-templates` to the latest version, which includes security updates for the `rollup` dependency.
> chore(deps): bump influxdata/influxdb-templates from 0.11.0 to 0.12.0 (#6960) (cherry-pick)

- src/App.tsx
- src/utils/analyticsTools.ts
This is re-enabling some UX analytics software so we can better understand usage patterns for future UI/UX updates across the InfluxData suite of products.
> chore: add Heap analytics

- package.json
- yarn.lock
This fixes `nanoid` more completely for https://github.com/influxdata/ui/security/dependabot/100. https://github.com/influxdata/ui/pull/6986 updated yarn.lock for the `dependencies`. This updates package.json so that `dependencies` will correctly contain 3.3.8 instead of 3.2.0 (but yarn.lock stays the same for this resolution) and updates `resolutions` to use 3.3.8 for 3.3.3 in the `mocha` devDependency.
In terms of runtime effects, there are no changes for prod and we now use 3.3.8 for the `mocha` devDependency.
Closes https://github.com/influxdata/idpe/issues/19022
> build(deps): bump nanoid from 3.2.0 to 3.3.8

- cypress/support/commands.ts
Adds a minor wait to the `monacoType` support command used in numerous tests to combat flake where the element is not focused in time.
> fix: wait for focus on monacotype support cmd

- cypress.json
- cypress/e2e/shared/explorer.queries.graphs.test.ts
- cypress/e2e/shared/scriptQueryBuilder.results.test.ts
- cypress/e2e/shared/simpleTable.test.ts
- cypress/e2e/shared/tasks-searching.test.ts
- cypress/support/commands.ts
- package.json
- yarn.lock
Closes https://github.com/influxdata/edge/issues/779
This pulls back the following from ui master:
* PR #6756 - semver - cherry-pick d625f5eddd5ef8aa4ee51e2a4f812b06e1dcc6ae
* PR #6768 - word-wrap - cherry-pick 73f0cde8ff90726f74b01a5680c95b06e18c37f2
* PR #6795 - @adobe/css-tools - cherry-pick b7ba6e9a0865d37712134f840b484cb3262966fe
* PR #6815 - postcss - cherry-pick 66fe1d1fe70c0d6b6a1753757a2880b84410de03
* PR #6820 - @babel/traverse - cherry-pick 16fbfc2eb4be8c0e033e217d6798d3fff7f6476c
* PR #6825 - crypto-js - cherry-pick 407a31efd798855337da7629ce0ec6a9e74f0297
* PR #6843 - @adobe/css-tools - cherry-pick 32976ea4706ed2e4791b713bd46ed2673cdc52f1
* PR #6849 - follow-redirects - cherry-pick 2c92b88ab0d0ced3864e6a85f7b3ff8d6bbbfe88
* PR #6878 - webpack-dev-middleware - cherry-pick …
> chore: cherry-pick dependabot updates from master

- package.json
- yarn.lock
Closes: https://github.com/influxdata/edge/issues/779.
This addresses two stray dependabot alerts:
* build(deps): bump follow-redirects from 1.15.4 to 1.15.6 (Based on https://github.com/influxdata/ui/pull/6872)
* build(deps): bump nanoid from 3.2.0 and 3.3.3 to 3.3.8 (Adjust mocha/**/nanoid resolution to use ^3.3.8 from https://github.com/influxdata/ui/commit/9f138ec14f9765411eaa1685e2993ba317c62ebb in master)
> chore: backport dependabot updates from master

- webpack.common.ts
- webpack.dev.ts
- webpack.fast.ts
- webpack.lighthouse.ts
- webpack.prod.ts
[Module resolution](https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require) has changed with Node 23.6.0. Node permits importing ESM with require statements, but require statements now require specifying rather than inferring a file extension. This breaks production builds with Node versions >= 23.6.0. Thank you to @philjb for identifying this.
> fix: specify env.ts more specifically for newer node versions

- src/homepageExperience/components/steps/java/ExecuteQuerySql.tsx
- src/homepageExperience/components/steps/java/InitializeClientSql.tsx
- src/homepageExperience/components/steps/java/InstallDependenciesSql.tsx
- src/homepageExperience/components/steps/java/WriteDataSql.tsx
Updates the onboarding steps for the Java v3 client. 
Introduces new library features.
* Query parameters
* Up to date Write API
> docs: update onboarding steps for Java v3 client

- src/homepageExperience/components/steps/Finish.tsx
- src/homepageExperience/components/steps/cli/InitializeClient.tsx
- src/homepageExperience/containers/ArduinoWizard.tsx
- src/homepageExperience/containers/CSharpWizard.tsx
- src/homepageExperience/containers/CliWizard.tsx
- src/homepageExperience/containers/GoWizard.tsx
- src/homepageExperience/containers/JavaWizard.tsx
- src/homepageExperience/containers/NodejsWizard.tsx
- src/homepageExperience/containers/PythonWizard.tsx
- src/homepageExperience/containers/WizardContainer.tsx
This PR replaces the use of the `ioxOnboarding` feature flag with the `isOrgIox` selector. It refactors all the components from class to functional components using the useSelector hook.
> fix: Replace onboarding wizard flags with selector

- package.json
- yarn.lock
This also drops the no longer needed resolution for canvg
> chore: update jspdf to 3.0.1

- src/flows/components/header/MenuButton.tsx
- src/flows/components/header/index.tsx
Closes https://github.com/influxdata/ui/issues/6931
Remove two unused buttons in the Notebook screen for OSS:
Before: 
After:
> feat(ui): remove notebook's unused buttons

- src/flows/context/api.tsx
- src/flows/context/flow.current.tsx
- src/shared/copy/notifications/categories/notebooks.ts
Closes https://github.com/influxdata/ui/issues/6999
https://github.com/user-attachments/assets/8f73fe1b-3243-472d-bf83-175cb205625b
> feat: show error update notebook fail

- src/buckets/components/createBucketForm/UpdateBucketOverlay.tsx
Closes #1607
Fix the bug when updating the retention period of buckets:
-  Before fix: set a retention period, eg. 1 hour, then change to never -> the retention period is still 1 hour
-  After fix: set a retention period, eg. 1 hour, then change to never -> the retention period changes to never
The recorded screen is the result when update in OSS:
https://github.com/user-attachments/assets/88c03b7a-06fb-4f68-a66b-62bddf8217b8
The image is the result  when update in CLOUD:
Note: I have to mock the variable CLOUD because I don't know how to run the CLOUD in my local. In the captured screen the retentionRules in the payload is not exists when send to the backend like ui team suggested
> fix: update retention rule for CLOUD and OSS

- yarn.lock
* build(deps): bump http-proxy-middleware from 2.0.7 to 2.0.9 (cherry-pick 328ae3d010)
* build(deps): bump formidable from 3.5.1 to 3.5.4 (cherry-pick 242f719232)
> build(deps): bump http-proxy-middleware from 2.0.7 to 2.0.9 (#7038)
